### ISSUE TITLE
Add libogg/libvorbis/libvorbisfile

### ISSUE THREAD

**Issue by corporateshark** [Microsoft/vcpkg#1]
https://xiph.org/downloads/

**Comment by Outurnate** [comment]
How does vcpkg handle dependencies?  Libflac requires libogg to be built first

**Comment by ras0219-msft** [comment]
In each package's `CONTROL` file, the field `Build-Depends` specifies the dependencies.

https://github.com/Microsoft/vcpkg/blob/master/ports/opencv/CONTROL

**Comment by ZeroCrunch** [comment]
How can those dependencies be passed onto the module we're building?

**Comment by ras0219-msft** [comment]
If the module is built with CMake, then the `vcpkg_configure_cmake()` command will automatically add the appropriate paths to the CMake line such that `find_package()` and friends will work without modification.

Otherwise, there is a `CURRENT_INSTALLED_DIR` variable[1] available inside the portfile so you can construct paths to the installed files.

[1] https://github.com/vlj/vcpkg/blob/e507c14229e5dd206499eef3ffa4e887131b9678/scripts/ports.cmake#L23

**Comment by Outurnate** [comment]
This looks like it is complete now

**Comment by ras0219-msft** [comment]
We do have libogg and libvorbis, but I don't believe we have libvorbisfile.

It might be a good idea to close this issue and open a new one specifically for libvorbisfile.
