### ISSUE TITLE
[glad] Support for building GLES specific headers should be added

### ISSUE THREAD

**Issue by tannergooding** [microsoft/vcpkg#10098]
Glad supports generating bindings for a multitude of specs, profiles, and apis and by default, it just builds `gl=latest, profile=compatibility`.
Support should also be added for generating the `gles=latest` APIs and for targeting the `core` profile.

**Proposed solution**
Glad should be updated to have a `gles` feature.
I'm unsure how you would expose functionality such that `gl=latest` could be avoided (generating only `gles` is valid) or how the profile could be toggled.
Namely because `vcpkg install` doesn't look to have a mechanism for specifying options like that.

**Describe alternatives you've considered**
Create a separate port specific to GLES.

**Additional context**
Happy to implement the feature if we can come to an agreement about how it should be done.

**Comment by capnkenny** [comment]
Based off of testing with glad's generator, it appears that the portfile uses a specification to follow instead of manipulating the API field. Also, with that said, if the specification is removed, glad will automatically pull the latest version of GL by default.

A proposed solution to this would be to break out the APIs into their own "features" (ie. `gles2` would invoke `gles2=latest` in the generator). Specifying `glad[core]` or `glad` by itself would leave the API field blank, allowing the end user to pull in OpenGL bindings by itself - however, if the end user would like multiple APIs included, they can also include `gl` to ensure that the OpenGL bindings are brought in as well. 

Additionally, an additional feature flag could be used to specify compatibility mode by changing the profile. This would mean that only specifying `glad` would generate bindings for the latest OpenGL API using Core Profile, but specifying `glad[compat]` would generate the API bindings using Compatibility Profile. (This would also apply to the additional features from above.)

If you'd like to see this in more detail, I can certainly link to a test branch that shows this implemented 🙂

**Comment by MrROBUST** [comment]
Probably relative. I moving my project build to use CMake with Vcpkg, and have some missing defines:
GL_COMPRESSED_RGBA_S3TC_DXT1_EXT
GL_COMPRESSED_RGBA_S3TC_DXT3_EXT
GL_COMPRESSED_RGBA_S3TC_DXT5_EXT
Looks like the Vcpkg uses the GLAD source without extensions. Maybe some configuration options or Feature Packages can be added to specify extensions set?

**Comment by petersteneteg** [comment]
I would also like this to be added! @capnkenny did you already have an implementation? 
are Vcpkg feature allowed to be mutually exclusive? i.e. one can not add use glad[core] and glad[compability] at the same time.

**Comment by capnkenny** [comment]
@petersteneteg Sorry for the delay!
If you'd like, you can take a look at https://github.com/novelrt/vcpkg/tree/port-feature/glad-apis which is the attempt I did back in February to get GLADs customization working as features. If you need a specific API set, you can specify it as a feature (i.e. `glad[gl,gles2]` ).

As far as exclusivity goes (for Core/Compatibility), it should override it forcefully to Compatibility profile if `compat` is used as a feature flag, otherwise it should always use Core profile.
