### ISSUE TITLE
[freeglut] build failure

### ISSUE THREAD

**Issue by traumedy** [microsoft/vcpkg#10171]
**Host Environment**
- Windows 10
- Visual Studio 2017 19.16.27035
- vcpkg 2020.02.04-nohash

**To Reproduce**
`vcpkg install freeglut:x64-windows`
`vcpkg install freeglut:x86-windows`

**Failure logs** 
```
-- Building x64-windows-dbg
-- Restarting Build without parallelism because memory exceeded
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: D:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
```

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4238627/install-x64-windows-dbg-out.log)
[install-x64-windows-dbg-out-1.log](https://github.com/microsoft/vcpkg/files/4238629/install-x64-windows-dbg-out-1.log)

**Additional context**
Not sure what to make of this, never seen the 'memory exceeded' error before and can't find any useful error messages in the logs.  I think this began failing several weeks ago.

**Comment by NancyLi1013** [comment]
Hi @traumedy 

Thanks for posting this issue.
Could you please remove `freeglut `source codes from `buildtrees `and try to build it again?
or clone vcpkg to a clean environment and then build it?

**Comment by traumedy** [comment]
I deleted the entire builtrees directory and rebuilt freeglut and it does in fact build fine now.

**Comment by gjgiezeman** [comment]
I have a similar issue.  Actually more like the issue reported in "Downloading freeglut failed #5861".
I work on Windows 10 Home and have vcpkg 2020.02.04-nohash
vcpkg install freeglut:x64-windows fails.

The freeglut-3.0.0.tar.gz file is downloaded but cannot be unpacked:

[extract-err.log](https://github.com/microsoft/vcpkg/files/4413424/extract-err.log)

The problem is that there is a symbolic link: freeglut-3.0.0/progs/test-shapes-gles1/android_toolchain.cmake
If I try to use 7-zip to extract the tar-file, I get a more useful error message (Can not create symbolic link).

After replacing the symbolic link with a copy of the file it points to, I can extract the archive and compile freeglut. Unfortunately, but understandably, this does not work for vcpkg. If I put the modified freeglut-3.0.0.tar.gz file in the downloads folder, I get a hash error.
