### ISSUE TITLE
zlib build failure

### ISSUE THREAD

**Issue by grimgort** [microsoft/vcpkg#10192]
hello . 
i have no admin right

[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/4243678/config-x86-windows-out.log)

./vcpkg.exe install zlib
Computing installation plan...
The following packages will be built and installed:
    zlib[core]:x86-windows
Starting package 1/1: zlib:x86-windows
Building package zlib[core]:x86-windows...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
Please install the English language pack.
-- Using cached D:/ftarroux/Logiciel/vcpkg/downloads/zlib1211.tar.gz
-- Using source at D:/ftarroux/Logiciel/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: D:/ftarroux/Logiciel/vcpkg/buildtrees/zlib/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\ftarroux\Logiciel\vcpkg\buildtrees\zlib\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:295 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by linquize** [comment]
Please post the content of your `D:\ftarroux\Logiciel\vcpkg\buildtrees\zlib\config-x86-windows-out.log`

**Comment by timautry** [comment]
vcpkg needs the following installed to function:
- Desktop development with C++
- English Language Pack
- Windows SDK

vcpkg is telling you to install the **English Language Pack:**

Computing installation plan...
The following packages will be built and installed:
zlib[core]:x86-windows
Starting package 1/1: zlib:x86-windows
Building package zlib[core]:x86-windows...
**Warning: The following VS instances are excluded because the English language pack is unavailable.**
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
**Please install the English language pack.**
-- Using cached D:/ftarroux/Logiciel/vcpkg/downloads/zlib1211.tar.gz
-- Using source at D:/ftarroux/Logiciel/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
Command failed: ninja -v

You may need admin rights to install the English Pack.

**Comment by NancyLi1013** [comment]
Hi @grimgort 

Thanks for posting this issue.
As @timautry said above, please install English language pack in Visual Studio first. Then try to build it again.

@linquize @timautry thanks for your above info.

**Comment by timautry** [comment]
You are most welcome @NancyLi1013 :)

**Comment by NancyLi1013** [comment]
@grimgort 
Does this issue still exist now?

**Comment by NancyLi1013** [comment]
Please feel free to reopen this if this is still a problem for you.
