### ISSUE TITLE
'vcpkg export' and non-relocatable config files

### ISSUE THREAD

**Issue by codicodi** [microsoft/vcpkg#1027]
CMake configuration files for several packages use absolute paths to refer to their dependencies. This obviously doesn't play well with the new 'export' feature.
Some examples among the libraries I have installed locally:
```
PS G:\dev\vcpkg\installed\x64-windows\share> ls -r | sls "G:/dev/vcpkg"

double-conversion\double-conversionConfig.cmake:11:  set(double-conversion_INCLUDE_DIRS "G:/dev/vcpkg/packages/double-c
onversion_x64-windows/include/double-conversion")
double-conversion\double-conversionConfig.cmake:14:include("G:/dev/vcpkg/packages/double-conversion_x64-windows/lib/cma
ke/double-conversion/double-conversionLibraryDepends.cmake")
globjects\globjects-config.cmake:57:  INTERFACE_INCLUDE_DIRECTORIES "G:/dev/vcpkg/installed/x64-windows/include;${_IMPO
RT_PREFIX}/include"
libpng\libpng16-debug.cmake:12:  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "G:/dev/vcpkg/installed/x64-windows/debug/lib/
zlibd.lib"
libpng\libpng16-release.cmake:12:  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G:/dev/vcpkg/installed/x64-windows/lib/zl
ib.lib"
libwebsockets\LibwebsocketsTargets-debug.cmake:12:  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "G:/dev/vcpkg/installed/x64
-windows/debug/lib/zlibd.lib;G:/dev/vcpkg/installed/x64-windows/debug/lib/ssleay32.lib;G:/dev/vcpkg/installed/x64-windo
ws/debug/lib/libeay32.lib;ws2_32.lib"
libwebsockets\LibwebsocketsTargets-release.cmake:12:  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G:/dev/vcpkg/installed
/x64-windows/lib/zlib.lib;G:/dev/vcpkg/installed/x64-windows/lib/ssleay32.lib;G:/dev/vcpkg/installed/x64-windows/lib/li
beay32.lib;ws2_32.lib"
```

**Comment by Cheney-W** [comment]
This issue has been fixed by adding the vcpkg_fixup_cmake_targets function into each port's portfile.cmake file.
double-conversion:       [38c9c97](https://github.com/microsoft/vcpkg/commit/38c9c97b6b2106304a9602ddf580b17e7bf56311#diff-05e444ca9f1a54ddc922f48e1503673f)
globjects: [4568b57](https://github.com/microsoft/vcpkg/commit/4568b57ad7728f30c1e2badc9735c8990cd51265#diff-b3fb0dd3e2f26d36b2e5cac3487e86d4)
libpng: [d60f874](https://github.com/microsoft/vcpkg/commit/d60f8744001b45989fdb21696ca66c740d61cd10#diff-cc99b4f16870e2adeb193a7711b3a318)
libwebsockets: [482f85f](https://github.com/microsoft/vcpkg/commit/482f85f4142fb02ec6a39ae7d264901bc1e162c1#diff-f30e836e3905f319247a2f7afe854be8)
