### ISSUE TITLE
bond - please support building with DBOND_ENABLE_GRPC=TRUE

### ISSUE THREAD

**Issue by eitanhs** [microsoft/vcpkg#10316]
****

**Is your feature request related to a problem? Please describe.**
Currently editing the portfile manually and speciying DBOND_ENABLE_GRPC=TRUE breaks the build 

```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: E:/foundations/vcpkg/buildtrees/bond/x64-windows-rel/vcpkg-parallel-configure
```

From bond documentation it seems that in order to build it requires some 'choco' packages:
activeperl golang ninja yasm
I'm not familiar with cmake so i'm not sure how and if it can be automated but since there's already a port for gRPC i'm guessing this is a viable option.

**Proposed solution**
Support building together with grpc as a package flavor

**Comment by chwarr** [comment]
Those additional packages are needed to build gRPC from source only. However, in vcpkg, it would be possible to depend on the gRPC port--which already handles building gRPC. I expect that some changes to Bond's CMakeLists.txt would be needed to consume a pre-compiled gRPC library instead of building from source.

If you're interested in contributing this to Bond, we'd be happy to have such a PR.

**Comment by eitanhs** [comment]
Opened PR https://github.com/microsoft/vcpkg/pull/10319/
