### ISSUE TITLE
[osg] build failure

### ISSUE THREAD

**Issue by Xenoxax** [microsoft/vcpkg#10320]
**Host Environment**
- OS: Windows 10.0.18363
- Compiler: MSVC 19.24.28316.0
Windows SDK version 10.0.18362.0 
Environment variable VCPKG_DEFAULT_TRIPLET=x64-windows

**To Reproduce**
`./vcpkg install osg`

Building package osg[core]:x64-windows...
-- Downloading https://github.com/openscenegraph/OpenSceneGraph/archive/OpenSceneGraph-3.6.4.tar.gz...
-- Extracting source C:/dev-tools/vcpkg/downloads/openscenegraph-OpenSceneGraph-OpenSceneGraph-3.6.4.tar.gz
-- Applying patch collada.patch
-- Applying patch static.patch
-- Applying patch fix-sdl.patch
-- Applying patch fix-example-application.patch
-- Applying patch disable-present3d-staticview-in-linux.patch
-- Applying patch fix-curl.patch
-- Applying patch remove-prefix.patch
-- Using source at C:/dev-tools/vcpkg/buildtrees/osg/src/raph-3.6.4-9780889fab
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/dev-tools/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: C:/dev-tools/vcpkg/buildtrees/osg/x64-windows-dbg
    See logs for more information:
      C:\dev-tools\vcpkg\buildtrees\osg\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/osg/portfile.cmake:57 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package osg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: osg:x64-windows
  Vcpkg version: 2020.02.04-nohash

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4295539/install-x64-windows-dbg-out.log)

**Comment by jepessen** [comment]
I've had a similar issue. The problem seems to be that some osg examples, like `osgmovie`, need `sdl1` package installed in order to work, while osg checks only for `sdl2`.

Can you run `vcpkg install sdl1:x64-windows` and then re-run `vcpkg install osg:x64-windows`?

**Comment by Xenoxax** [comment]
Seems like installing sdl1 allows osg to compile. It looks like the code was written to support one or the other, but I'm guessing that's not the case?

**Comment by jepessen** [comment]
It should be. I'm not an expert of SDL so I don't know if it's a matter of only configuring the `osgmovie` example project for using `sdl2` instead of `sdl1`, or also some code must change, but I've noticed in the log that it was something related to some `sdl` missing header, so I've tried. I was not able to check and make a PR because I was busy with personal stuff.

**Comment by NancyLi1013** [comment]
Hi all,

Thanks for posting this issue.

It seems that there is something wrong with `sdl2 `when building `osg`. The origin cause is that it
cannot find `SDL/SDL.h`. Since this include file is from `sdl1`.

`C:\dev-tools\vcpkg\buildtrees\osg\src\raph-3.6.4-9780889fab\examples\osgmovie\osgmovie.cpp(694,10): fatal error C1083: Cannot open include file: 'SDL/SDL.h': No such file or directory [C:\dev-tools\vcpkg\buildtrees\osg\x64-windows-dbg\examples\osgmovie\example_osgmovie.vcxproj]`

Even if we changed it as `SDL2/SDL.h`, there were still some errors.

If we choose to use `sdl1`, we also need to update the dependency as `sdl1 `instead of `sdl2 `in `CONTROL `file.

**Comment by omaralvarez** [comment]
Same issue here, exact same error (W10 x64).

Installing sdl1 fixed it.

**Comment by JackBoosY** [comment]
Hi guys, I've fixed this issue.
Please update vcpkg and rebuild osg.

Thanks.
