### ISSUE TITLE
Simple updating between VS-versions

### ISSUE THREAD

**Issue by erl987** [Microsoft/vcpkg#1033]
This is rather a feature request.

One of the most annoying problems when updating the VS-version is that most of the times you need to recompile all your libraries. I know that this is not required with VS 2017, but this is an exception in the past years.

So I would like to have clean management of library compilations for different compiler versions in vcpkg. I currently have VS 2015 and VS 2017 installed and see no way to really determine which compiler is to be used.

**Comment by ras0219-msft** [comment]
We currently use VS2017 when available and fall back to VS2015 when it is not, because they are binary equivalent.

However, in the future, we plan to do exactly what you're suggesting! For VS20XY, we'll have a separate set of triplets (x86-winXY, for example) that _cleanly_ separate each VS version and make it incredibly easy to switch and rebuild.
