### ISSUE TITLE
Packaging github projects with submodules

### ISSUE THREAD

**Issue by szellmann** [microsoft/vcpkg#1036]
I'd like to package a project that is hosted on github and that uses git submodules. Unfortunately, github source releases don't recursively include the submodules' source code in the tarball.

I've seen the `vcpkg_from_github` command and had hoped that it would actually allow you to clone a certain tag, but it doesn't. Is there either a way to recursively clone the github repo (instead of downloading a tarball), or a canonical way / common practice to download the tarball forthe main project, and then download the subproject to the desired location inside the main project's source tree?

**Comment by ras0219-msft** [comment]
Hi @szellmann,

_Generally_, we've found that projects use submodules to pull in 3rd party code. If you'll let me use https://github.com/szellmann/visionaray as an example, we actually _want_ to skip the submodule and instead package CmdLine as an independent port. This ensures that if multiple libraries use CmdLine, they all will end up using the same version.

Since CmdLine uses Premake, the easiest way to port it is probably to create a simple CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.8)
project(cmdline)

option(INSTALL_HEADERS "Install header files" ON)

set(CMAKE_DEBUG_POSTFIX d)
file(GLOB SOURCES src/*.cpp)
file(GLOB_RECURSE HEADERS include/*)
add_library(cmdline ${SOURCES} ${HEADERS})
set_target_properties(cmdline PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON)

install(TARGETS cmdline
  RUNTIME DESTINATION bin
  LIBRARY DESTINATION lib
  ARCHIVE DESTINATION lib
)

if(INSTALL_HEADERS)
  install(FILES include/support DESTINATION include)
endif()
```

However, it's true that sometimes submodules are used for code that was meant to be released and built together as a unit (Boost does this, for example). For those libraries, the _best_ option is unfortunately still to download each submodule archive individually and unpack them into the appropriate structure. It's slightly more costly to maintain the port (upgrades require "resolving" all the submodule links), but it is extremely robust and efficient for users -- it downloads the absolute minimum needed and works very well across package version upgrades.

The canonical way to download subprojects would be to just call `vcpkg_download_distfile()` multiple times [1][2] and then call `vcpkg_extract_source_archive()` with a second parameter. You could use `vcpkg_from_github()` for the main project, but it doesn't currently have a way to override the target extract folder.

[1] https://github.com/Microsoft/vcpkg/blob/master/ports/libuv/portfile.cmake#L2-L26
[2] https://github.com/Microsoft/vcpkg/blob/master/ports/bond/portfile.cmake#L9-L23

**Comment by szellmann** [comment]
Hi @ras0219-msft,

thanks, that makes it clear and the links to the two portfiles are helpful.

I'd say that one tends to use submodules with projects that don't use versioning rigorously, or that have unstable APIs (both definitely true with CmdLine). If CmdLine's API changes, and the port is updated, ports depending on CmdLine could silently break, right?

Btw. how's versioning between ports handled by vcpkg in general? Even if APIs are stable, every now and then a project might rely on a certain feature that was removed or changed in a 3rd party port.

**Comment by ras0219-msft** [comment]
Glad to help!

Yeah, it is possible for untested ports to "silently"[1] break. As we improve our CI coverage, we will detect these failures earlier -- we eventually hope to have CI coverage of _all_ ports.

For projects that are truly totally unstable, such that every commit should be considered a totally incompatible library, the system does start to show cracks. The _best_ option in those cases is if all downstream projects actually vendor (check in) the entire library and -- most importantly! -- rename all of the symbols[2] such that they cannot conflict with any other's use of the library. This has the moral effect of making a _totally unique_ library that happens to resemble the upstream, but will actually work properly in the face of multiple copies. Effectively, it would make a `visionaray_cmdline` library that can live side-by-side with `qt5_cmdline` in the same process -- even with static linking!

To state it another way, if your dependency is more unstable than you are, you need to "take ownership" of a copy and force a sufficient amount of stability onto it. This is obviously unrealistic for large dependencies like boost, but it should work fine for CmdLine if you feel it's the right way to go.

##### Versioning
We take the stance that it is (in the general case) _completely unreasonable_ for one library to request another to be held back. We expect all libraries to absorb dependency updates in a reasonable timespan (we're willing to perform limited backporting of fixes!) and we expect dependencies to generally strive for _source_ compatibility. We place no restrictions on ABI compatibility, because we insist on rebuilding from source upon any changes.

Of course, for very important libraries, we apply reasonable judgement; if Boost requires the OpenSSL 1.0.2 release train, we won't update the default to 1.1 (since they are both secure). If OpenCV takes a month to absorb the latest breaking libpng changes, we're ok with holding the libpng upgrade back a month (barring CVE issues).

We believe we can take such a harsh/principled stance because you can always freeze Vcpkg at a particular version. All updates are pulled through git, so they can always be rolled back if you need it.

[1] Silently here means that attempts to _upgrade_ will noisily fail. This will not result in silent runtime failures in any of your applications, which would be totally unacceptable. Note that _all_ version and build information is checked into `git`, so you can always get back to a working copy by checking out an older copy of vcpkg.
[2] The easiest way to do this would be to wrap every header and source file in a giant namespace.

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in two year, if it is still an issue, please reopen.
