### ISSUE TITLE
[SDL2] update to <2.0.12>

### ISSUE THREAD

**Issue by Zingam** [microsoft/vcpkg#10429]
Library name: SDL2

New version number: 2.0.12

Other information that may be useful (release notes, etc...)
https://www.libsdl.org/download-2.0.php

**Comment by Cheney-W** [comment]
@Zingam 
Thanks for reporting this to us! Since VCPKG download the SDL2 from https://github.com/SDL-mirror/SDL , and the current release of it is still 2.0.10, so we will update this port until the latest version is released on GitHub.

**Comment by RT222** [comment]
I already made a working port for this new version, I'll create a PR as soon as the 2.0.12 is available on the mirror.

**Comment by Zingam** [comment]
Interesting. Just a couple of unrelated questions though. Why doesn't vcpkg use the official sources: https://www.libsdl.org/download-2.0.php ? Who is maintaining this  unofficial repository and on what criteria are made the releases there. It's the same source after all?

**Comment by RT222** [comment]
Good question. I think it's because vcpkg_from_github is the preferred way to get sources in vcpkg. I was waiting for the github mirror to add the last version, but as it is taking too much time for my taste, I modified the port to get the sources from the sdl2 website and made a pull request #10500.

**Comment by Cheney-W** [comment]
Port has been updated by PR https://github.com/microsoft/vcpkg/pull/10500.
