### ISSUE TITLE
Please Port GoogleTestAdapter into vcpkg

### ISSUE THREAD

**Issue by L4ZZA** [microsoft/vcpkg#10434]
Library name: GoogleTestAdapter

Library description: Google test adapter. Can't run c++ unit tests in a sensible way without it. 

Source repository URL: https://github.com/csoltenborn/GoogleTestAdapter

**Comment by Neumann-A** [comment]
I don't think you want GoogleTestAdapter in vcpkg since GoogleTestAdapter is a Visual Studio Extension/Tool which you can simply install via the VS Extension Manager or the other ways mentioned on the github readme.
The library the extension uses is google test and that library is already in VCPKG as the port `gtest`

**Comment by L4ZZA** [comment]
I was just looking for alternatives, since all the other options don't seem to work in our vs2019.sln

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
