### ISSUE TITLE
[tbb:x64-windows] build failure

### ISSUE THREAD

**Issue by danrbailey** [microsoft/vcpkg#10490]
@BurningEnlightenment - I just started getting this TBB error today, looks like it might be related to your recent change:

> Building package tbb[core]:x64-windows...
> -- Downloading https://github.com/intel/tbb/archive/427c252e0bb9e191767a62d8a744b21950c343f6.tar.gz...
> CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):
>   
> 
>   File does not have expected hash:
> 
>           File path: [ C:/vcpkg/downloads/temp/intel-tbb-427c252e0bb9e191767a62d8a744b21950c343f6.tar.gz ]
>       Expected hash: [ b61107a751363f6acbf31297fc1232314a41622d6e89fe87dedb34a11c9a1d04dd1be724e7a6021e889342e7a453b6605523560441460716933817dffd4a4191 ]
>         Actual hash: [ 01307b689680c8d796357a65258257b0c54336aa2a5dc75746d65e169988b8cb353537ad480cc4b8970b32667ab7f965bfedee4a15186f2a3159c9f130667f26 ]

**Comment by BurningEnlightenment** [comment]
I would be quite surprised if any of my recent changes did cause this. In fact [only one of recent my PRs](https://github.com/microsoft/vcpkg/pulls?q=is%3Apr+author%3ABurningEnlightenment) did land on master. Furthermore all of my PRs only change or add ports which are unrelated to `tbb`.

I think the underlying issue is that the tbb repository was renamed/moved from [intel/tbb](https://github.com/intel/tbb) to [oneapi-src/oneTBB](https://github.com/oneapi-src/oneTBB) which in turn changed the directory name within the archive which in turn changed the archive hash...

**Comment by danrbailey** [comment]
@BurningEnlightenment - thanks! That does look like the problem.

**Comment by NancyLi1013** [comment]
Hi @danrbailey 
Thanks for posting this issue.
It's duplicated to #10447. I have submitted a PR #10456 to fix this issue.
