### ISSUE TITLE
`integrate install` doesn't work

### ISSUE THREAD

**Issue by goodguysoft** [microsoft/vcpkg#10534]
I use Windows 7 x64 and Visual Studio 2019 Enterprise.

I run `vcpkg --triplet x64-windows-static integrate install`

It write me:

```
Applied user-wide integration for this vcpkg root.

All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.
```

However, it is not true. Visual Studio doesn't see any libraries compiled by `vcpkg`.

If `vcpkg` can not install itself, you probably have to remove this feature from documentation to avoid people to waste time trying to make it working.

**Comment by linquize** [comment]
When you were asked to elevate permission, did you allow it?

vcpkg integrate install currently only writes file to `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140` where VS2015 uses it.

But VS2019's MSBuild directory is somewhere else.

**Comment by goodguysoft** [comment]
May be. But why: 1. Documentation says nothing about that. 2. Program reports that it performed task successfully without any check whether it **really** performed task successfully. It looks like `vcpkg` is good example how to teach children what is "bad style".

**Comment by timautry** [comment]
@goodguysoft  
 - check the location where @linquize  states 
 - cd  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\ImportBefore\Default
     - there should be a file named vcpkg.system.props
 - cd  %LOCALAPPDATA%\vcpkg
 - there should be 3 files:
    - config
    - vcpkg.path.txt
    - vcpkg.user.targets
 - if not, then **vcpkg integrate install** failed for some reason, most likely it was not run as administrator aka elevated command prompt
    - To remedy:
       - Open a command prompt as administrator
        - cd to _vcpkg-root_ folder
        - type in and run **.\vcpkg.exe integrate install**
- Check for two locations for the files mentioned again.
   - If the files now exist, the problem is solved, one can now _#include "any/library"_ installed in vcpkg without having to modify project properties for includes, libs, etc...
   - If not, another problem exists, likely a corrupted vcpkg instance, one may need to delete and recreate it or create a new one.

**Comment by JackBoosY** [comment]
```
Then, to hook up user-wide integration, run (note: requires admin on first use)
```

You need to open powshell with administrator privileges to execute the integrate command.

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.

**Comment by dddictionary** [comment]
On Linux (WSL Ubuntu 20.04), running `vcpkg integrate install` outputs 
```
Applied user-wide integration for this vcpkg root.
CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=/home/####/vcpkg/scripts/buildsystems/vcpkg.cmake"
```

After restarting vscode (several times), intellisense fails to find the packages I plan on using. I have confirmed packages are installed using `vcpkg list`.

**Comment by JackBoosY** [comment]
cc @Cheney-W

**Comment by OmranSyria** [comment]
> @goodguysoft
> 
> * check the location where @linquize  states
> * cd  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\ImportBefore\Default
>   
>   * there should be a file named vcpkg.system.props
> * cd  %LOCALAPPDATA%\vcpkg
> * there should be 3 files:
>   
>   * config
>   * vcpkg.path.txt
>   * vcpkg.user.targets
> * if not, then **vcpkg integrate install** failed for some reason, most likely it was not run as administrator aka elevated command prompt
>   
>   * To remedy:
>     
>     * Open a command prompt as administrator
>     * cd to _vcpkg-root_ folder
>     * type in and run **.\vcpkg.exe integrate install**
> * Check for two locations for the files mentioned again.
>   
>   * If the files now exist, the problem is solved, one can now _#include "any/library"_ installed in vcpkg without having to modify project properties for includes, libs, etc...
>   * If not, another problem exists, likely a corrupted vcpkg instance, one may need to delete and recreate it or create a new one.

I have checked everything, but it still does not work.

**Comment by K9PAL** [comment]
I am seeing the exact same error message. Repeat case:
o install vcpkg from github ( version 2023-03-01-538539c4e364dd6f14f5e36f6704144254845159)
o vcpkg install boost-test
Expected: installs boost-test
Actual: installs boost-test without error
o Right-click Powershell from the dock, choose Run as Administrator
o Verify that Powershell window title says "Administrator"
o .\vcpkg integrate install
Expected: makes boost-test usable across my machine or an error message with the cause of the error
Actual: "error: failed to install system targets file to C:\Program Files (x86)\MSBuild/Microsoft.Cpp/v4.0/V140/ImportBefore/Default/vcpkg.system.props"
Additional data: the path to vcpkg.system.props exists.
Speculation: is Administrator access sufficient to write to Program Files? Could this be a permissions problem despite running as Administrator? Does this require TrustedInstaller?

**Comment by JackBoosY** [comment]
@K9PAL You need the admin permission to run integrate command.

**Comment by K9PAL** [comment]
As I said above, 
"o Right-click Powershell from the dock, choose Run as Administrator
o Verify that Powershell window title says "Administrator"
"

That means that I am running with admin permission, doesn't it?. And yes, of _course_ I said yes to the UAC prompt. 

Additional data: from the same Powershell window, I have write access to the .props file-- I can add a space to one of the comments and save it. So it doesn't look like a permissions problem.

**Comment by JackBoosY** [comment]
@K9PAL I never thought triplet would cause the integration to fail, what's your default triplet?

**Comment by K9PAL** [comment]
Yep, I also think it's odd. I don't know how to check the default triplet directly, but some recent Microsoft documentation says 
"
The default triplet when running any vcpkg command is %VCPKG_DEFAULT_TRIPLET% or a platform-specific choice if that environment variable is undefined.

    Windows: x86-windows
"
(https://learn.microsoft.com/en-us/vcpkg/users/triplets)

and I did not have an environment variable VCPKG_DEFAULT_TRIPLET. If the default triplet contained "x86" that would explain why it was trying to write to Program Files (x86).

**Comment by JackBoosY** [comment]
@Cheney-W Maybe check the default triplet related code?

**Comment by BillyONeal** [comment]
>and I did not have an environment variable VCPKG_DEFAULT_TRIPLET. If the default triplet contained "x86" that would explain why it was trying to write to Program Files (x86).

No, it tries to write to Program Files (x86) because that is where VS 2015 looks for its extensions. The VS2017+ integration lives in `%LOCALAPPDATA%`.

This looks like you did `vcpkg install something`, which installed `something:x86-windows`, but you're compiling with VS targeting something that can't link with `x86-windows` (like `x64`), so no libraries are found. There should be a warning about that printed in your build logs but I'm not sure it shows up in the default log level.

**Comment by BorderKeeper** [comment]
Similar issue trying to setup ndisapi. I have tried integrating (with elevated permissions) and it created the props file in `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\ImportBefore\Default` problem is that MSBuild of VS 2022 uses V170 MSBuild. I tried copying the `ImportBefore` into the V170 folder but then I get a props collision between `vcpkg.user.props` and `vspkg.system.props`.

I also tried:
1. Run `vcpkg integrate project` and the run the command
2. ndisapi is C++ only so I added a dummy C# project just in case
3. Installed on C# and C++
The nuget extracts to the packages folder, but the props file does not contain the same the `ImportBuild` props file has:
```<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VCPkgLocalAppDataDisabled>true</VCPkgLocalAppDataDisabled>
  </PropertyGroup>
</Project>
```

So far I am at lost at what to do instead of just copying the libraries and headers into the bin files manually or linking them directly by hardcoding them.
