### ISSUE TITLE
apache arrow build failure: clobbers arrow.lib from shared (.dll) with static (.lib)

### ISSUE THREAD

**Issue by swilson314** [microsoft/vcpkg#10585]
**Host Environment**
- OS: Windows 10
- Compiler: VS 2017

> [C++] vcpkg build clobbers arrow.lib from shared (.dll) with static (.lib)
> --------------------------------------------------------------------------
>
>                 Key: ARROW-8248
>                 URL: https://issues.apache.org/jira/browse/ARROW-8248
>             Project: Apache Arrow
>          Issue Type: Bug
>          Components: C++, Developer Tools
>    Affects Versions: 0.16.0
>            Reporter: Scott Wilson
>            Priority: Major
>

After installing Arrow via vcpkg, build the library per the steps below. CMake builds the shared arrow library (.dll) and then the static arrow library (.lib). It overwrites the shared arrow.lib (exports) with the static arrow.lib. This results in multiple link/execution problems when using the vc projects to build the example projects until you realize that shared arrow needs to be rebuilt. (This took me two days.) 

Also, many of the projects added with the extra -D flags (beyond ARROW_BUILD_TESTS) don't build.

> "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\Tools\VsDevCmd.bat" -arch=amd64
> cd F:\Dev\vcpkg\buildtrees\arrow\src\row-0.16.0-872c330822\cpp
> mkdir build
> cd build
> cmake .. -G "Visual Studio 15 2017 Win64" -DARROW_BUILD_TESTS=ON -DARROW_BUILD_EXAMPLES=ON -DARROW_PARQUET=ON -DARROW_PYTHON=ON -DCMAKE_BUILD_TYPE=Debug
> cmake --build . --config Debug

**Comment by PhoebeHui** [comment]
@swilson314, I'm not clear what's the issue here, do you have a problem for installing arrow via vcpkg? why do you build arrow with the cmake commands again after installed arrow by vcpkg, do you try to build arrow tests and examples? 

We tried the cmake commands you provided, however it failed on cmake configuration step, do you have some custom setting for the comamnd, could you share with us?

**Comment by swilson314** [comment]
ASIDE: the .dll/.lib installed in F:\DEV\VCPKG\INSTALLED\X64-WINDOWS\DEBUG\LIB doesn't seem to be the current version. I get unresolved externals that are only found when I build the dll myself.

A related question comes from trying to use one of the example projects as a starting point for my own code. I'm not used to using VS projects generated from cmake files, and there are some actions taking place that I can't track down:

1) link.read.1.tlog lists input files, including F:\DEV\VCPKG\INSTALLED\X64-WINDOWS\DEBUG\LIB\ARROW.LIB. However, the per the link properties, I'm using the newer .lib I created at F:\Dev\vcpkg\buildtrees\arrow\src\row-0.16.0-872c330822\cpp\build\debug\Debug\arrow.lib. Where is the path F:\DEV\VCPKG\INSTALLED\X64-WINDOWS\DEBUG\LIB\ARROW.LIB set? I can't find it in any of the solution/project settings.

2) The seems related. After the link step, a number of .dlls are copied into the outdir. However, the arrow.dll that is copied is from F:\DEV\VCPKG\INSTALLED\X64-WINDOWS\DEBUG\LIB, rather than the newer version I created. Again, where is the setting for copying this dll?

**Comment by swilson314** [comment]
Lastly, the install seems to include two identical, multiple versions of the debug arrow.dll in the folders (neither is updated when I build arrow.dll from the VS project):

F:\Dev\vcpkg\buildtrees\arrow\x64-windows-dbg\debug
F:\Dev\vcpkg\packages\arrow_x64-windows\debug\bin

**Comment by Cheney-W** [comment]
@swilson314 Thanks for your reply!
After the `./vcpkg install arrow` command run successfully, you have completed a series of steps such as arrow download, cmake, and build. This command will directly generate available header files, lib files, and dll files. These files will be stored in `vcpkg\packages\arrow`. This result is equivalent to you manually download the arrow source, and execute the following command:
```
cd cpp
mkdir build
cd build
cmake .. -G "Visual Studio 14 2015 Win64" ^
-DARROW_BUILD_TESTS = ON
cmake --build. --config Release
```
And after you using the` ./vcpkg integrate install` command, all the generated files will be loaded into the Visual Studio of your current machine, you do not need to set the relevant environment variables, your project can automatically find the corresponding config arrow file. 
Note: If you use `./vcpkg install arrow`, then you must set your project config to x86, if you want to use the arrow file generated by vcpkg under x64 config, then you have to use ./vcpkg install arrow: x64- Windows to install arrow.

About "the .dll/.lib installed in F:\DEV\VCPKG\INSTALLED\X64-WINDOWS\DEBUG\LIB doesn't seem to be the current version", which version is your expected? In general, vcpkg will install the current release version of the third-party library. You can find the version of arrow currently used by vcpkg from `vcpkg\ports\arrow\CONTROL` file.

About your questions:
As I said above, because you executed the `./vcpkg integrate install` command, the files generated by vcpkg have been automatically loaded into your project. If you do not want to use them, you can execute this command: `./vcpkg integrate remove` and reopen your project. At the same time, you need to manually add the path of the file you generated to the corresponding environment variable, so that your project will use them instead of the file generated by vcpkg.

About multiple versions of the debug arrow.dll exist, because the specific build process occurs under `buildtrees\arrow\x64-windows-dbg`, the corresponding dll and lib files will be generated here, and finally vcpkg will copy them to `packages\arrow_x64-windows`, so it exists here multiple files of the same version.

Finally, vcpkg will not install port examples and tests at the same time when installing ports. They will be provided to users as port features, but unfortunately, arrow has not yet added these features. We hope to have more contributors to complete this matter together.

**Comment by swilson314** [comment]
@Cheney-W many thanks for your response, it was extremely helpful.

Just to be clear, there seem to be three copies each of the debug/release arrow.dlls, see listing below. Is this expected? It causes confusion and I don't understand what possible purpose it could serve.

Something else I don't understand is this: I used one of the example projects as the starting point for my code. During the link step, it copies arrow.dll (unfortunately not the one I built) and a number of boost dlls to the output folder for the resulting executable. I'm now thinking this occurs because "files generated by vcpkg have been automatically loaded into your project". I went through all the VS settings and couldn't find where this copying of dlls is specified. Per your comment, I'm now thinking there is a VS configuration file (or the like) that contains the paths for these dlls. How can I edit this?

F:\Dev\vcpkg Original>dir /s arrow.dll
 Volume in drive F is Dev
 Volume Serial Number is 5496-F751

 Directory of F:\Dev\vcpkg Original\buildtrees\arrow\x64-windows-dbg\debug

03/26/2020  07:49 PM        33,775,616 arrow.dll
               1 File(s)     33,775,616 bytes

 Directory of F:\Dev\vcpkg Original\buildtrees\arrow\x64-windows-rel\release

03/26/2020  07:52 PM         5,540,352 arrow.dll
               1 File(s)      5,540,352 bytes

 Directory of F:\Dev\vcpkg Original\installed\x64-windows\bin

03/26/2020  07:52 PM         5,540,352 arrow.dll
               1 File(s)      5,540,352 bytes

 Directory of F:\Dev\vcpkg Original\installed\x64-windows\debug\bin

03/26/2020  07:49 PM        33,775,616 arrow.dll
               1 File(s)     33,775,616 bytes

 Directory of F:\Dev\vcpkg Original\packages\arrow_x64-windows\bin

03/26/2020  07:52 PM         5,540,352 arrow.dll
               1 File(s)      5,540,352 bytes

 Directory of F:\Dev\vcpkg Original\packages\arrow_x64-windows\debug\bin

03/26/2020  07:49 PM        33,775,616 arrow.dll
               1 File(s)     33,775,616 bytes

     Total Files Listed:
               6 File(s)    117,947,904 bytes
               0 Dir(s)  402,353,115,136 bytes free

**Comment by Cheney-W** [comment]
Yes, those three copies each of the debug/release arrow.dlls is expected. 
Buildtree is an intermediate folder generated during port installation. Files such as dlls are built here. After the install command is executed, the files in the buildtree can be deleted, and it will not affect your use of this port.
The files in the Packages are all copied from the buildtree. There is a step called post-check during the install port. It will check the correctness of the files generated by the build here. The files in this folder can also be deleted.
Installed folder integrates the generated files of all installed ports, why after executing the ./vcpkg integrate install command, your project can directly call the port files installed by vcpkg, in fact, because the path of each folder under this folder is added to the environment variables of the project.

**Comment by Cheney-W** [comment]
Please run this command: `./vcpkg integrate remove`, and reopen VS. In this case, VS will no longer automatically use the arrow related files provided by vcpkg.
If you want use the dll generated by yourself, please refer this: https://docs.microsoft.com/en-us/windows/win32/dlls/using-dynamic-link-libraries.

**Comment by swilson314** [comment]
Thanks again @Cheney-W for your explanation. I think I can now explain what I'm trying to do.

As installed by vcpkg, the arrow.dll is missing some classes/function exports (e.g. LocalFileSystem) that I need. These functions are included if I build arrow.dll myself via these steps:

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\Tools\VsDevCmd.bat" -arch=amd64
cd F:\Dev\vcpkg\buildtrees\arrow\src\row-0.16.0-872c330822\cpp
mkdir build
cd build
cmake .. -G "Visual Studio 15 2017 Win64" -DARROW_BUILD_TESTS=ON -DARROW_BUILD_EXAMPLES=ON -DARROW_PARQUET=ON -DARROW_PYTHON=ON -DCMAKE_BUILD_TYPE=Debug
cmake --build . --config Debug

I suspect it is the addition of the ARROW_PARQUET flag that adds the extra classes to the library.

The resulting arrow.dll/.lib ends up in F:\Dev\vcpkg 002\buildtrees\arrow\src\row-0.16.0-872c330822\cpp\build\debug\Debug. This is the version that my program needs to use for linking and runtime. The VS studio project I'm using for my program (copied from one of the arrow examples) copies one of the three arrow.dlls to the executable's output folder during the link step. However, this dll doesn't work because it has unresolved externals (e.g. LocalFileSystem). **Which folder do I copy the arrow.dll that I created to in order to have this be the one used by the VS project?**

Aside: I still think there's an underlying problem with the VS project (ALL_BUILD) that builds the libraries because it builds both the dynamic and static versions of arrow.lib, but overwrites the dynamic .lib with the static .lib. However, I can work around this by manually building just the dynamic library.

**Comment by JackBoosY** [comment]
@swilson314 
1. You should not use arrow libraries or any header files in _VCPKG_PATH/buildtrees/arrow_ or _VCPKG_PATH/packages/arrow-TRIPLET_. We should use them in _VCPKG_PATH/installed/TRIPLET_.
2. We should add the vcpkg toolchain to the cmake configuration using the parameter `-DCMAKE_TOOLCHAIN_FILE=${VCPKG_PATH}/scripts/buildsystems/vcpkg.cmake` according to your vcpkg path.
3. The port arrow does not yet contain the functions `test`, `example` and `python`.
4. Vcpkg will build dynamic / static library based on the triples you choose, so no coverage issues will occur.

**Comment by Cheney-W** [comment]
@swilson314 We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
