### ISSUE TITLE
[cpr-x86-windows-static] build failure

### ISSUE THREAD

**Issue by brah** [microsoft/vcpkg#10728]
**Host Environment**
- OS: Windows
- Compiler: vs2019

**To Reproduce**
compile in vs2019 including "cpr/cpr.h" after `PS C:\vcpkg> .\vcpkg install cpr:x86-windows-static`

**Failure logs** 
There is 130 errors (not present if compiling regular cpr, only with static; most are unresolved externals like:
"`0>libcurl.lib(curl_gethostname.c.obj)(0,0): Error LNK2001: unresolved external symbol __imp__gethostname@8`
`0>D:\Documents\snip\snip\snip\Release\snip.exe(0,0): Error LNK1120 fatal: 59 unresolved externals`
other that may stand out are mismatches such as:
`0>cpr.lib(session.cpp.obj)(0,0): Error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in Injector.obj`
(I have tried after cleaning solution and rebuilding, errors persist)

**Additional context**
thanks for any help! unsure if it's a me problem or a port problem; I'm just trying to avoid the zlib and libcurl DLLs produced and required with a regular vcpkg install of cpr

**Comment by JonLiu1993** [comment]
I did not reproduce your question. Are you sure that x86-windows-static is set in vs2019 cmake setting? You can refer to this:
Using an environment variable instead of a command line option
The CMAKE_TOOLCHAIN_FILE setting simply must be set before the project() directive is first called. This means that you can easily read from an environment variable to avoid passing it on the configure line:

if(DEFINED ENV{VCPKG_ROOT} AND NOT DEFINED CMAKE_TOOLCHAIN_FILE)
   set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
       CACHE STRING "")
endif()

project(myproject CXX)
Using multiple toolchain files
To use an external toolchain file with a project using vcpkg, you can set the cmake variable VCPKG_CHAINLOAD_TOOLCHAIN_FILE on the configure line:

cmake ../my/project \
    -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake \
    -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=../my/project/compiler-settings-toolchain.cmake

**Comment by Adela0814** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
