### ISSUE TITLE
[opencv] FFMpeg compiled as static library into OpenCV's DLL when x64-windows-static is selected.

### ISSUE THREAD

**Issue by mansa34** [microsoft/vcpkg#10880]
FFMPEG license is LGPL but OpenCV license is 3-clause BSD License.

If FFmpeg is compiled as a static library and included into OpenCV and eventually into a user application, then the user should release their source code.

To overcome this problem, when OpenCV is compiled using CMake in static build, FFmpeg is wrapped into a dll which is called openCV-FFMpeg.dll and the OpenCV use the dll for all works that it is doing in relation to FFmpeg.

This behaviour can be set on CMake and the OpenCV build process, create the proper DLL.

in vcpkg implementation, all of the FFmpeg libraries will be linked into the OpenCV and later to user application which may invalidate the license.

vcpkg should have an option to generate similar behaviour as opencv own make in this regard.

More information :

https://docs.opencv.org/3.4/d0/da7/videoio_overview.html
https://answers.opencv.org/question/56787/how-to-build-opencv-so-it-statically-link-to-ffmpeg/
https://github.com/opencv/opencv/issues/5920
https://stackoverflow.com/questions/34605330/building-static-opencv-with-ffmpeg-is-still-looking-for-shared-libavcodec

**Comment by cenit** [comment]
it has, you have to manually define a triplet in which ffmpeg is compiled dynamically even if everything else is static

**Comment by mansa34** [comment]
You are right that there is a workaround, but unfortunately, it is not compatible with the way that OpenCV deals with FFMpeg.

In my company, we started to use vcpkg on some projects and it is very good, but this discrepancy, generate problems for us as some of our application which doesn't use vcpkg, are shipped with opencv_ffmpeg libraries and some others are shipped with FFmpeg dlls. 

The OpenCV solution required one dll to be shipped, but dynamic build of FFMpeg required 5 or 6 dll to be shipped. 

I tried to find how vcpkg would use OpenCV CMake file to build it, but I could not find any documentation or sample, so I can not do it by myself.

**Comment by Neumann-A** [comment]
>I tried to find how vcpkg would use OpenCV CMake file to build it,

It is all in the `portfile.cmake` (assuming v4 it is here https://github.com/microsoft/vcpkg/blob/master/ports/opencv4/portfile.cmake)

As @cenit mentioned you probably want to define a custom triplet and maybe use the port overlay feature to define a custom build for opencv4 fitting your requirements better?

**Comment by cenit** [comment]
@Neumann-A it's not OpenCV, it's ffmpeg which should be built differently.
Maybe we can implement it in our ffmpeg port, as a feature, something along the line of "ffmpeg[singleDll]"

@mansa34 i can't understand fully the problem: is it because you have problems bundling 8 dlls instead of only one? Because the single `opencv_ffmpeg.dll` is in any case the summation of the
`avcodec-58.dll avdevice-58.dll avfilter-7.dll avformat-58.dll avresample-4.dll avutil-56.dll swresample-3.dll swscale-5.dll` files, built with these rules (which we can implement in the ffmpeg port maybe)
https://answers.opencv.org/question/124858/how-to-build-opencv_ffmpegdll-from-patched-ffmpeg-source/

**Comment by cenit** [comment]
tbh, the more I think about produce a single dll, the more I am against.
1) we did a lot of work trying to move OpenCV to use ffmpeg on windows like it does on any other OS, which is to link to an external "standard" ffmpeg
2) we should maintain our own "cap_ffmpeg_impl.hpp" to trigger inclusion of all exported symbols in the single-dll-to-be-provided, otherwise if we use the one provided by OpenCV to produce the single dll and bundle it in the ffmpeg port, we would expose only symbols used by OpenCV in a single dll which maybe also other would like to use... (I hope this sentence is clear enough)

**Comment by mansa34** [comment]
The problem is on openCV is build and not how FFmpeg builds.
Let me try to explain it:
We are building a library to share with other companies or internally (as a DLL).
We started to use vcpkg and we are very happy with the result with the only problem: FFmpeg integration.

When we use OpenCV which is build by vcpkg, we need to ship it with FFmpeg dynamic libraries (such as avcodec-58.dll and avformat-58.dll etc)

when other companies getting our library and they want to use it alongside of their product which uses OpenCV, if they do not use vcpkg, then they should ship another Dll (opencv_videoio_ffmpeg411_64.dll) which means that we are shipping two copies of FFmpeg.

When I use vcpkg, and when I build OpenCV from source, I assume I would get the same result, but apparently only for FFmpeg, we are not getting the same result.

I tried to add new feature cvffmpeg, to the list of features that I can select when building openCV using vcpkg, but I am not successful. The first problem is that vcpkg disable openCV to download any packages. The second problem was that I could not find any way to add this new feature to the list of features that can be accepted by vcpkg.

Please note that I am good in CMake and I can not find my way in cmake hierarchy. 

Any help in this matter is very appreciated.

**Comment by cenit** [comment]
I understand the pain in standardizing on a single toolchain. It’s a pity that the other company does not want to use vcpkg.
In any case, pardon me for insisting, but it is a problem of ffmpeg building, because opencv_videoio_ffmpeg411_64.dll (and its parent opencv_ffmpeg411_64.dll), despite the name, contain ffmpeg as you say, not OpenCV!

Yes, the opencv vcpkg portfile disables any download. This is *a must* on vcpkg. We build everything from source.
@ras0219-msft what’s your opinion on this problem? To recap, OpenCV ships a single dll containing the necessary subset of ffmpeg on Windows, while we build it linking to the full ffmpeg library. A couple of comments ago I posted the recipe of the single dll, but it may create problems for many while solving one for few

**Comment by BillyONeal** [comment]
@cenit 

>Maybe we can implement it in our ffmpeg port, as a feature, something along the line of "ffmpeg[singleDll]"

Generally speaking features should not be used for either/or alternatives; that is to say, if you have port[a,b,c] installed and then install port[a,b,c,d], there should only be additions, not removals or conflicts with other ports that only expected [a,b,c].

@mansa34

I agree having multiple ffmpegs in the tree would be problematic, and I don't think we should be maintaining independent copies. I am not a lawyer, but as far as I understand it, the application author doesn't need to release their source code, but they would need to release the objects which were ultimately combined into the opencv DLL. (The goal of GPL'd things is to allow replacement of the (L)GPL'd piece if someone wants to.

This might be an interesting problem to solve but I think if you want to turn it into a more concrete feature request you need to be more specific in specifying how the relationships between ports would function in this "different world order".

**Comment by ras0219** [comment]
Thanks for going into details @mansa34!

As I understand the situation:
1. You want to ship ffmpeg as a DLL for licensing reasons
2. You'd like to minimize the size a user needs to ship

You're shipping a DLL to a customer which might include arbitrary other dependencies in their final product. _Generally_, you'd like to static link all your dependencies to minimize the number of DLLs your customer needs to deploy.

I'd like to first point out two things that are a bit obvious. First, even if there was a solution for ffmpeg, this still results in a duplication of the code for OpenCV -- there's one copy in your DLL and a separate copy in the consumer's EXE/DLL. Second, if the user decides to use ffmpeg directly and _not_ use OpenCV, then the current behavior would actually result in a _reduction_ of what's shipped.

Second, we are unlikely to solve this in upstream vcpkg for several reasons:
1. We want to minimize headaches between platforms, like totally different deployment stories
2. We want to preserve the ability to static-link ffmpeg
3. We want the ability to update ffmpeg
4. We do not want to pessimize users that want to use ffmpeg _and_ OpenCV -- we'd like them to only ship one copy of ffmpeg
5. We do not currently have a reasonable way to offer this option to customers _and continuously test it_ in addition to the above

Finally, I think there are a few options:
1. Following @cenit's suggestions, static link OpenCV, dynamic link the real ffmpeg, and just accept that customers who add other dependencies may ship a second copy of ffmpeg (same as they would if they used a different version of ffmpeg/opencv).
2. In addition to (1), you can use `./vcpkg export opencv:x64-windows-custom --zip` to export precisely the static libs +headers you're using and give that to customers. This doesn't require them to use vcpkg at all -- it will create a separate standalone shrink-wrapped zip. This would save your customers build pain (they don't have to figure out how to build opencv!) and enable them to reuse the same ffmpeg that you're using.
3. You could locally modify the opencv port to use the prebuilt ffmpeg. We recommend `--overlay-ports=` for this; essentially you can copy `ports/opencv4` out of the vcpkg tree to privately modify it. You'll want to remove the patch [1] that prevents downloads in addition to the other changes that revert the behavior on windows to use the bundled ffmpeg.

[1] https://github.com/microsoft/vcpkg/blob/85247c398141ab4d692b8fd61dbfcb845e79d2f2/ports/opencv4/portfile.cmake#L18

**Comment by talregev** [comment]
We can add this as a opencv feature, and compile opencv_ffmepg as feature to opencv.
you can compile it from here:
https://github.com/opencv/opencv_3rdparty/tree/ffmpeg/master
