### ISSUE TITLE
How do I include 7zip headers?

### ISSUE THREAD

**Issue by jepessen** [microsoft/vcpkg#10939]
I've installed 7zip with vcpkg, and I want to use it in a cmake project. It's already configured for vcpkg since I use other libraries for it.

In a source file not maintained by me (I cannot modify it) headers are include this way:

```
#include "7zip/Common/MyCom.h"
#include "7zip/PropID.h"
```
So I wanted to find the correct path by finding `7zip/PropID.h`. I can find it in my vcpkg directory in
`vcpkg\installed\x64-windows\include\7zip\CPP\7zip\PropID.h` so I think that I need only to use `find_path`.

This is the code that I use in `CMakeLists.txt` for finding the header directory:

```
find_package(7zip CONFIG REQUIRED)
find_path(SZIP_INCLUDE_DIR NAMES "7zip/PropID.h")
if(SZIP_INCLUDE_DIR MATCHES "NOTFOUND" )
  message(FATAL_ERROR "Could not find 7zip headers")
endif()
```
But even if I find the package, headers are not found:

```
  CMake Error at /my/path/CMakeLists.txt:22 (message):
    Could not find 7zip headers
```
What's the correct way to include 7zip headers in my project?

**Comment by NancyLi1013** [comment]
Hi @jepessen 
Thanks for posting this issue.
Since `ProID.h` is installed in` vcpkg\installed\x64-windows\include\7zip\CPP\7zip\PropID.h`.
The PATH should be _7zip/CPP/7zip/PropID.h_ instead of _7zip/PropID.h_.

In source file, we should use the headers like this:
`#include <7zip/CPP/7zip/PropID.h>`
For `MyCom.h`, I didn't find it in 7zip. So I don't know the path.

Please try again.

**Comment by NancyLi1013** [comment]
@jepessen 
Is there any problems for this issue?

**Comment by NancyLi1013** [comment]
I'm going to close this due to no response.
Please feel free to reopen this if it is still a problem for you.
