### ISSUE TITLE
How do I get Vcpkg to generate an executable on my desktop?

### ISSUE THREAD

**Issue by Jkpath86** [microsoft/vcpkg#10961]
I am trying to use Vcpkg to get a "C" header file <stdio.h> needed by Visual Studio to compile and run a simple test program. However, I can't seem to generate a "vcpkg.exe" file. I am working on a desktop running Windows 7 SP1 (64-bit operating system). The following are the steps I've done so far:

   1.    Copied the "vcpkg-master.zip" file to my secondary hard drive folder (G:/John/Downloaded 
         Libraries)

   2.   Ran "vcpkg-master.zip" by double clicking on this file. This seemed to populate the folder 
        called   "vcpkg-master". In this folder I found the file call "bootstrap-vcpkg.bat". 
 
   3.  Ran the file  "bootstrap-vcpkg.bat" by double clicking on it. I was expecting to find the file 
        "vcpkg.exe" somewhere. I did not find it anywhere.

Am I looking at the right software to do what I am trying to do? If so, what step am I missing? I have looked at a bunch of documentation, but I haven't been able to figure out how to get it to work. Help!!!

**Comment by timautry** [comment]
You have all the prerequisites installed under Quick Start on the vcpkg homepage? https://github.com/microsoft/vcpkg

1. Windows 7 x64 SP1 - done
2. Visual Studio 2015 with Update 3 or newer (VS2017 or VS2019 Community versions are free) with the following installed:
  - Under Workloads Desktop Desktop Development with C++ ?
  - One of the Windows SDK's version 8.1 or higher ?
  - English under Language Packs ?
3. Git for windows https://git-scm.com/download/win ?
4. Once all the software above is installed:
  - Open a cmd or powershell prompt
  - cd to the location where you want to put the vcpkg software
  - git clone https://github.com/Microsoft/vcpkg.git
  - cd vcpkg
  - .\bootstrap-vcpkg.bat
  - If you have errors, post back with the screen/console output from running the bootstrap-vcpkg.bat
  - otherwise you are good to go to install packages as your discretion

**Comment by Jkpath86** [comment]
Hi Tim,
   I wanted to be sure to thank you for your response. I was able to generate the vcpkg.exe file with your help. However, I still have alot to learn about how to use the software (visual studio).  I open a file (in the editor of visual studio) that I had created with a few lines of C code. Under the drop down Debug menu the Run options were grayed out and couldn't be selected.I suppose it was because I had not yet compiled and linked my code to make an executable image. Anyway, I have to learn how to do this in the IDE environment I have setup.   Thanks once again for helping me get to this point.
John
P.S.
 I thougt that I would send you a copy of the command file window to see if everything that occurred was what you would expect.    On Wednesday, April 22, 2020, 10:15:28 PM EDT, Tim Autry <notifications@github.com> wrote:  
 
 


You have all the prerequisites installed under Quick Start on the vcpkg homepage? https://github.com/microsoft/vcpkg
   
   - Windows 7 x64 SP1 - done
   - Visual Studio 2015 with Update 3 or newer (VS2017 or VS2019 Community versions are free) with the following installed:
   
   - Under Workloads Desktop Desktop Development with C++ ?
   - One of the Windows SDK's version 8.1 or higher ?
   - English under Language Packs ?
   
   - Git for windows https://git-scm.com/download/win ?
   - Once all the software above is installed:
   
   - Open a cmd or powershell prompt
   - cd to the location where you want to put the vcpkg software
   - git clone https://github.com/Microsoft/vcpkg.git
   - cd vcpkg
   - .\bootstrap-vcpkg.bat
   - If you have errors, post back with the screen/console output from running the bootstrap-vcpkg.bat
   - otherwise you are good to go to install packages as your discretion

**Comment by JackBoosY** [comment]
For usage, I think you need [this](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md).
