### ISSUE TITLE
In which file is the `_execute_process` command defined?

### ISSUE THREAD

**Issue by goproxies** [microsoft/vcpkg#10978]
I searched the `_execute_process` command  in all *.camke files and source files of the vcpkg project even in all source files of cmake,but nothing was found.In which file is it defined indirectly?

**Comment by Neumann-A** [comment]
`_execute_process` is the default `execute_process` of CMake if  `execute_process` has been overwritten by some script (which it maybe has in VCPKG: see `execute_process.cmake` in `<vcpkg>/scripts/cmake`). https://cmake.org/cmake/help/latest/command/execute_process.html

**Comment by goproxies** [comment]
Oh,I did some tests with CMake.It sounds that this is a general rule -- `_command` defined as the old command when `command` is overwritten .Is this behavior documented? It's not easy to prove this conclusion from `https://cmake.org/`.

**Comment by Neumann-A** [comment]
It is mainly considered an internal development feature to inject extra code so you shouldn't use it in general. It is probably documented somewhere in the dark corners of cmake but don't ask me where. The reason you should not use it because it is very easier to create infinit call loops with it. If you overwrite a command more than one time the original implementation of the command will be not accessible and you might call the same function over and over again.

**Comment by goproxies** [comment]
Thanks!You are right.The execution of cmake scripts is dynamic-symbol-binding and calling  `_command` in `command` is a infinit call loops when  `command` defined twice with the same code.
