### ISSUE TITLE
Things break version to version.

### ISSUE THREAD

**Issue by acdemiralp** [microsoft/vcpkg#11529]
**Describe the bug**
A library which was in vcpkg started having build failures, and as a result my whole application, which I hadn't touched for a month, but was working perfectly last month, no longer works.

**Environment**
- OS: Linux
- Compiler: GCC 9.3

**To Reproduce**
1. ./vcpkg install (about 25 dependencies including boost and python)

**Expected behavior**
I want my code to not break every month without me modifying it. This is too much maintenance. 

**Failure logs** 
- N/A

**Additional context**
The central problem is, I am already spending months getting code to work, and vcpkg updates are making it not work again. Although having my dependencies automated is cool, it is meaningless if it adds regular overhead equivalent to building the dependencies from scratch.

Conan had a variant of this problem due to the ports being maintained by public without a central administration. And it died. If you don't wanna be like conan, you will have to find a solution to this, a better way than specifying a historical commit of vcpkg explicitly when downloading it.

**Comment by Neumann-A** [comment]
Wild guess: I broke your code with the VTK update to 9.0
Solution: Don't depend on upstream/HEAD if you don't want to update your code with a port update. Use a private fork which you update when you are ready for it or use a port overlay for your "fixed in time" dependencies.
Other Solution: read the roadmap https://github.com/microsoft/vcpkg/wiki/Roadmap and see that versioning is on it.

**Comment by acdemiralp** [comment]
@Neumann-A thank you for the info, the versioning update looks great and is apparently to be released soon. Closing this issue since it will largely be solved by this.
