### ISSUE TITLE
Minimum powershell version to use VCPKG?

### ISSUE THREAD

**Issue by stekyne** [Microsoft/vcpkg#1156]
What is the minimum version of PS required to run VCPKG? The requirements mention VS2015 update 3 only. 

There is someone trying to build our project with Windows 8 (not 8.1) and VS2015 but is having problems. Just trying to find out if it's workable to get it running with that configuration.

Thanks

**Comment by ras0219-msft** [comment]
We support Windows 7 SP1 and above as a host operating system, so our minimum powershell requirement should be 2.0+.

However, bugs are always possible, so please let us know if you have an issue you think is caused by an old powershell version!

[TODO: I see our readme doesn't list our minimum OS version]

**Comment by ras0219-msft** [comment]
After looking at the csound thread, I think we have probably introduced a regression in a very recent change for older windows versions while adding support for Powershell Core.

I'll push a fix in a bit.

**Comment by stekyne** [comment]
That's great, thanks a lot. I'll wait for Michael to reply and see if it solves the problem.

**Comment by stekyne** [comment]
Seems to have done the trick
