### ISSUE TITLE
[podofo] fontconfig feature in portfile.cmake is not correct

### ISSUE THREAD

**Issue by maidamai0** [microsoft/vcpkg#11587]
**Portfile.cmake configure error**
Search `podofo` with `vcpkg` gives:

```powershell
❯ vcpkg search podofo
podofo               0.9.6-7          PoDoFo is a library to work with the PDF file format
podofo[fontconfig]                    Enable font manager support on Unix platforms.
``` 
In portfile.cmake:
```
set(PODOFO_NO_FONTMANAGER ON)
if("fontconfig" IN_LIST FEATURES)
  set(PODOFO_NO_FONTMANAGER OFF)
endif()
```
In podofo source code: `podofo-0.9.6\src\doc\PdfFontCache.cpp:447`
```cpp
#if defined(_WIN32) && !defined(PODOFO_NO_FONTMANAGER)
                pFont = GetWin32Font( it.first, m_vecFonts, pszFontName, bBold, bItalic, bSymbolCharset, bEmbedd, pEncoding, bSubsetting  );
#endif // _WIN32
```

When you installed `podofo` without the `[fontconfig]` on windows you will fail on loading font, because `GetWin32Font()` is ignored.

This may be a bug of the source code, since we may install the wrong version according to the name and description

**Environment**
- OS: Win10
- Compiler: 
```powershell
❯ msbuild
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
❯ cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27040 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```

**To Reproduce**
1. ./vcpkg install podofo
2. compile and run an simple example to load a font.
3. font load faild

Repro code when
always.

**Expected behavior**
font load without any problem

**Comment by maidamai0** [comment]
This can be a bug of the source code or a config error on windows, I don't know how to make a pull request.Install the `podofo[fontconfig]` version is a workaround for now.

**Comment by NancyLi1013** [comment]
Hi @maidamai0 
Thanks for posting this issue.

If you install `podofo[fontconfig]`, `PODOFO_NO_FONTMANAGER
` will be set as `OFF`. In another word, `podofo `will build with `fontconfig`. So you can load font successfully.

Otherwise, there will be no `fontconfig` to build with, of course, you cannot get any fonts on Windows.

So, if you want to use font on Windows, you have to install `podofo[fontconfig]`.

On Unix platform, the situation is just the opposite.

Please refer to this comment.  https://github.com/microsoft/vcpkg/pull/3516#issue-188474763

**Comment by maidamai0** [comment]
Thanks, I will close this issue.
Maybe `vcpkg search podofo` results ia a little  confuse.
