### ISSUE TITLE
issue with installation

### ISSUE THREAD

**Issue by scifuentes23** [microsoft/vcpkg#11591]
Hi I try to run integrate the install in the command prompt and I get this:
Error: failed to copy targets file to C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\ImportBefore\Default\vcpkg.system.props
I am working on windows 10 and cloned the code from the GitHub desktop. 
I appreciate any help with this.

**Comment by Voskrese** [comment]
admin open cmd

**Comment by scifuentes23** [comment]
I already did that and I get the same error

**Comment by JackBoosY** [comment]
@scifuentes23 Please use PowerShell with admin.

Thanks.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by ardubluesky** [comment]
still doesn't work, tried with both cmd and powershell elevated terminal

**Comment by crb123456** [comment]
I got same error running from powershell in admin mode.  I tried elevated command prompt and it worked.  Cant explain just thought this might help someone

**Comment by JustifYI** [comment]
Same error, cmd with admin mode..

**Comment by exwhyz** [comment]
Use Windows CMD shell instead of Poweshell

**Comment by sinasojoodi** [comment]
I was running into the same issue at the vcpkg integrate and install step but with docker (mcr.microsoft.com/windows/servercore:ltsc2019). The issue seems to have been introduced since the latest release (2023-04-15) and continues to be present in master branch. 

Once I switched to 2023-02-24 release of vcpkg, docker builds fine.  I tried this with different ports and it didn't matter.

I believe this is a new regression, but I'll do a bit more investigation before filing it as new issue.
