### ISSUE TITLE
Add ragel [was: exe files forbidden]

### ISSUE THREAD

**Issue by vlj** [Microsoft/vcpkg#116]
I'm trying to package ragel : http://www.colm.net/open-source/ragel/
It's a tool that generate .cpp file implementing state machines.
It's a dependency of harfbuzz.
Unfortunatly it looks like exe are invalid distribution target for vcpkg. Here is the warning emitted by vcpkg :

___________________________________________________________________________________
The folder /include is empty. This indicates the library was not correctly installed.
The software license must be available at ${CURRENT_PACKAGES_DIR}/share/ragel/copyright .

    file(COPY ${CURRENT_BUILDTREES_DIR}/src/ragel-6.9/COPYING DESTINATION ${CURRENT_PACKAGES_DIR}/share/ragel)
    file(RENAME ${CURRENT_PACKAGES_DIR}/share/ragel/COPYING ${CURRENT_PACKAGES_DIR}/share/ragel/copyright)
The following EXEs were found in /bin and /debug/bin. EXEs are not valid distribution targets.

    C:/Users/vljno/Documents/GitHub/vcpkg/packages/ragel_x86-windows/bin/ragel.exe
    C:/Users/vljno/Documents/GitHub/vcpkg/packages/ragel_x86-windows/debug/bin/ragel.exe
___________________________________________________________________________________

Is there a recommended way to build tools ? I guess it will likely matter for libintl too (which relies on tool to manage .po files)

**Comment by ras0219-msft** [comment]
Take a look at #59. For code generation tools, we actually recommend downloading pre-built binaries for x86 (if possible) and using them directly instead of building against the ports tree. The prebuilt executable should be placed in `tools\ragel.exe` or `tools\ragel\ragel.exe` if it has `dll` files that need to accompany it applocally.

If pre-built binaries aren't available (I didn't see any on ragel's website), then make sure to override the `GENERATOR` option to `vcpkg_configure_cmake` with "Visual Studio 14 2015". In the future, we will likely need a separate command to explicitly target the host's architecture (perhaps `vcpkg_configure_host_cmake`).

**Comment by alexkaratarakis** [comment]
Fixed with #117
