### ISSUE TITLE
Qt 5.8 deployment problem - could not find or load the Qt platform plugin

### ISSUE THREAD

**Issue by Fleischner** [Microsoft/vcpkg#1172]
Problem occurs when building an QT application (debug, release not tested yet), with 'vcpkg integrate install' applied.

VS does not copy freetype.dll (and its dependencies) to the output directory.
The dependency is indirect over the qwindows.dll platform plugin.
Surprisingly the qwindows.dll gets copied even if it is a plugin dynamically loaded at runtime. Seems there is somewhere a hardcoded dependency. The other plugins (qdirect2d, qminimal, qoffscreen) don't get copied. When starting the application qt crashed with "This application failed to start because it could not find or load the Qt platform plugin "windows""
I checked with dependency walker. qwindows.dll depends on freetype. After copying the dlls by hand qt starts without problems.

Can someone replicate the behavior?
(A quick fix would be to make a fix dependency on freetype in Qt5Gui.dll)

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue!

Yeah, you're right that there's a hardcoded dependency. In the specific case of Qt, I reimplemented the "windeployqt.exe" as a powershell script [1]. It looks like we need to do a bit more though!

I think the right fix would be to have some way to analyze qwindows.dll at deploy time but ensure its dependencies are put into the _application_ folder instead of the _plugin_ folder. We currently only handle deploying dependencies into the same folder as the module being analyzed.

[1] https://github.com/Microsoft/vcpkg/blob/11d4a5c47edb75c8aaaa7d86bc2d351af8b32e28/ports/qt5/qtdeploy.ps1

**Comment by JackBoosY** [comment]
Hi @Fleischner ,this issue should be fixed in nearly PR. I found nothing wrong with build QT5.
Plz update vcpkg and rebuild it.
Thx,

**Comment by JackBoosY** [comment]
Please open a new issue if this is still a problem for you.
Thx.
