### ISSUE TITLE
How do I help vcpkg package and distribute Halide?

### ISSUE THREAD

**Issue by alexreinking** [microsoft/vcpkg#11761]
I'm a developer on the [Halide](https://github.com/halide/Halide) team and one of my responsibilities is maintenance of our CMake build, which I understand vcpkg uses to provide Halide builds to its users. I think vcpkg is great and we now recommend that our users use vcpkg to install our dependencies on Windows.

We have recently merged an overhaul of the CMake build (and now require 3.16+) and I thought this would be a good opportunity to ask what we can do to make Halide easier for vcpkg to package. In particular, we're using the GNUInstallDirs module now, so I hope you will no longer need to maintain a patch of our install rules (ports/halide/fix-install-path.patch). We also provide standard HalideConfig{,Version}.cmake files so that `find_package` can work out of the box.

I apologize in advance if this is not the appropriate venue to build this bridge.

**Comment by NancyLi1013** [comment]
Hi @alexreinking
Thanks so much for your above info. It's so nice that you can support and help us, which is really what we need.

As for the dependencies, we prefer to use the libraries provided by vcpkg, since it is more easier to maintain. So we might not install the dependencies that embedded your source codes.
Please refer to this [doc ](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-vendored-dependencies)to learn more about this.

We have updated CMake to 3.17.2 in vcpkg, so the new `Halide `version should work.

Thanks for providing `HalideConfig.cmake` file and it's more convenient for users to use this library.

I notice that there is no new released version recently (last version is 2019-08-27). So it might be better to release a new version for `Halide`.

**Comment by alexreinking** [comment]
Yes, the plan is to get a new release together ASAP. Ideally that release would contain any changes that support your work.

**Comment by NancyLi1013** [comment]
Thanks for your quick reply.
It's perfect that there is no any dependencies bundled  in your repository.
Let's wait for the new release. Once released, we will try to update it ASAP.

 Really appreciate for your help. Welcome you join in vcpkg. 😄

**Comment by NancyLi1013** [comment]
@alexreinking 
Please let me know if you have any other concern about this.

**Comment by NancyLi1013** [comment]
I'm closing this issue for now since there seems to be no any concern.
Please feel free to reopen this if you still have any other issues about this.

Thanks again for your support. Looking forward to next release for `halide`.
