### ISSUE TITLE
How do I update portfile of llvm to consider preinstalled binaries instead of building?

### ISSUE THREAD

**Issue by ahmed-zubair-1998** [microsoft/vcpkg#11760]
I am trying to build Halide on windows which requires llvm. Building llvm is taking too much time so I installed prebuilt binaries for llvm. I looked at the docs and they say that you must change portfile to use prebuilt private library. This is my first time using cmake so I am having difficuties understanding the provied example. Some tips would be helpful. Thanks.

**Comment by JackBoosY** [comment]
Related #11204.

**Comment by JackBoosY** [comment]
Because vcpkg is an open source project and follows an open source agreement. In order to ensure the **security** of the binary, we currently only provide a way to build and generate the binary.

Since the feature binarycaching has been merged into master branch, you only need to install llvm once, and subsequent installations will use the cache without wasting too much time.
