### ISSUE TITLE
[tbb:x64-windows] build failure

### ISSUE THREAD

**Issue by atharkes** [microsoft/vcpkg#11792]
**Host Environment**
- OS: x64-windows
- Vcpkg version: 2020.02.04-nohash

**To Reproduce**
`./vcpkg install tbb`

**Failure logs** 
```
Starting package 2/2: tbb:x64-windows
Building package tbb[core]:x64-windows...
-- Using cached */vcpkg/downloads/oneapi-src-oneTBB-427c252e0bb9e191767a62d8a744b21950c343f6.tar.gz
-- Using source at */vcpkg/buildtrees/tbb/src/1950c343f6-81f8b97441
-- Building build/vs2013/makefile.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: msbuild "*/vcpkg/buildtrees/tbb/x64-windows-rel/1950c343f6-81f8b97441/build/vs2013/makefile.sln" /p:Configuration=Release /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.18362.0 /p:VcpkgTriplet=x64-windows "/p:VcpkgCurrentInstalledDir=*/vcpkg/installed/x64-windows" /m
    Working Directory: */vcpkg/buildtrees/tbb/x64-windows-rel/1950c343f6-81f8b97441
    Error code: 1
    See logs for more information:
      *\vcpkg\buildtrees\tbb\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_msbuild.cmake:161 (vcpkg_execute_required_process)
  ports/tbb/portfile.cmake:62 (vcpkg_install_msbuild)
  scripts/ports.cmake:76 (include)


Error: Building package tbb:x64-windows failed with: BUILD_FAILED
```
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4735632/build-x64-windows-rel-out.log)
\* is substituted for my vcpkg location

**Additional context**
The problem seems to with LINK not able to open/find SDL2.lib
"LINK : fatal error LNK1181: cannot open input file 'SDL2.lib'" (see error log)
I tried installing SDL2 but that didn't fix anything. The SDL2.lib seems to already be present in some of the build projects, but my guess is that a link is broken in the build project of tbb.
I also installed vcpkg on my laptop (also x64-windows) and there it seemed to install tbb fine.

**Comment by timautry** [comment]
@atharkes Thank you for posting this issue.
- Yes I can see where the process is trying to link the SDL2.lib SDL2main.lib SDL2_ttf.lib files???
- I have no idea why/how the tbb.proj (Intel thread building blocks) would need these files???
- I checked my installation, the vcpkg portfiles and https://www.github.com/oneapi-src/oneTBB source and find no reference to SDL (Simple Direct Media) libraries.
- somehow the `*\vcpkg\buildtrees\tbb\x64-windows-rel\1950c343f6-81f8b97441\build\vs2013\tbb.vcxproj` has been modified to include those libraries.

May I suggest the following:
- cd to `*/vcpkg` and do `get pull` to update vcpkg to latest
- cd to `*/vcpkg/downloads` and delete the `oneapi-src-oneTBB-427c252e0bb9e191767a62d8a744b21950c343f6.tar.gz` source file
- cd to `*/vcpkg/buildtrees` and delete the `tbb` folder using `rmdir /q /s tbb`
- cd back to  `*/vcpkg` and run `.\vcpkg.exe install tbb`

**Comment by atharkes** [comment]
Hi @timautry 

Thanks for looking into this issue.

After following the steps you suggested I still get exactly the same error messages

**Comment by timautry** [comment]
Hmm... may I suggest creating a new instance:
1. git clone https://github.com/microsoft/vcpkg.git vcpkg.test
2. cd to vcpkg.test
3. vcpkg install tbb

If this does not work, then somewhere in the msbuild process there may be a file adding the SDL libraries...
Check in `C:\Program Files (x86)\MSBuild\Microsoft.Cpp` for any .xml files in the BuildCustomizations or v140 folder. There may be a `before build` or `after build folder` adding these to the `.vcproj` file???

**Comment by atharkes** [comment]
I made a new instance of the vcpkg repository but that didn't fix it.

I don't have the `Microsoft.cpp` folder you mentioned, neither in `C:\Program Files (x86)\MSBuild` or `C:\Program Files\MSBuild`.

**Comment by NancyLi1013** [comment]
Hi @atharkes 
`sdl2 `is not the dependency of `tbb`. So it might be something wrong with your local environment.
Could you please remove `sdl2 `and try to build this again?

@timautry 
Thanks for your help to look into this issue.

**Comment by NancyLi1013** [comment]
It seems a bit wired. Which version do you use Visual Studio? Could you please reinstall it and try this again?

**Comment by atharkes** [comment]
Of Visual Studio I am using enterprise 2017 and community 2019, but it is using the 2019 version for compiling and building.

I repaired the 2019 version and the tried again, but no luck. Later i can try to reinstall the 2019 version.

**Comment by RameshKandukuriB** [comment]
Still see the build error, pleas let me know any fix avialable?
**Error: Building package tbb:x64-windows failed with: BUILD_FAILED**
**2020-07-06T12:29:29.0459650Z   Package: tbb:x64-windows
2020-07-06T12:29:29.0459913Z   Vcpkg version: 2020.02.04-nohash**


2020-07-06T12:29:26.8367152Z Building package tbb[core]:x64-windows...
2020-07-06T12:29:29.0448598Z -- Downloading https://github.com/intel/tbb/archive/427c252e0bb9e191767a62d8a744b21950c343f6.tar.gz...
2020-07-06T12:29:29.0449309Z CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):
2020-07-06T12:29:29.0449712Z   
2020-07-06T12:29:29.0449823Z 
2020-07-06T12:29:29.0450033Z   File does not have expected hash:
2020-07-06T12:29:29.0450213Z 
2020-07-06T12:29:29.0450544Z           File path: [ D:/a/1/s/vcpkg/downloads/temp/intel-tbb-427c252e0bb9e191767a62d8a744b21950c343f6.tar.gz ]
2020-07-06T12:29:29.0451246Z       Expected hash: [ b61107a751363f6acbf31297fc1232314a41622d6e89fe87dedb34a11c9a1d04dd1be724e7a6021e889342e7a453b6605523560441460716933817dffd4a4191 ]
2020-07-06T12:29:29.0451955Z         Actual hash: [ 01307b689680c8d796357a65258257b0c54336aa2a5dc75746d65e169988b8cb353537ad480cc4b8970b32667ab7f965bfedee4a15186f2a3159c9f130667f26 ]
2020-07-06T12:29:29.0452377Z 
2020-07-06T12:29:29.0452618Z   The file may have been corrupted in transit.  This can be caused by
2020-07-06T12:29:29.0452980Z   proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
2020-07-06T12:29:29.0453267Z   environment variables to
2020-07-06T12:29:29.0454454Z   "https://user:***@your-proxy-ip-address:port/".
2020-07-06T12:29:29.0455356Z 
2020-07-06T12:29:29.0455514Z   
2020-07-06T12:29:29.0455610Z 
2020-07-06T12:29:29.0455879Z Call Stack (most recent call first):
2020-07-06T12:29:29.0456170Z   scripts/cmake/vcpkg_download_distfile.cmake:182 (test_hash)
2020-07-06T12:29:29.0456781Z   scripts/cmake/vcpkg_from_github.cmake:132 (vcpkg_download_distfile)
2020-07-06T12:29:29.0457147Z   ports/tbb/portfile.cmake:1 (vcpkg_from_github)
2020-07-06T12:29:29.0457391Z   scripts/ports.cmake:90 (include)
2020-07-06T12:29:29.0457537Z 
2020-07-06T12:29:29.0457626Z 
2020-07-06T12:29:29.0458636Z Error: Building package tbb:x64-windows failed with: BUILD_FAILED
2020-07-06T12:29:29.0459018Z Please ensure you're using the latest portfiles with `.\vcpkg update`, then
2020-07-06T12:29:29.0459370Z submit an issue at https://github.com/Microsoft/vcpkg/issues including:
2020-07-06T12:29:29.0459650Z   Package: tbb:x64-windows
2020-07-06T12:29:29.0459913Z   Vcpkg version: 2020.02.04-nohash

**Comment by timautry** [comment]
@RameshKandukuriB 
- Is the vcpkg up to date? 
   `cd <vcpkg-root>`
   `git pull`
- You may also need to run `.\bootstrap-vcpkg.bat` if vcpkg has not be updated in a while.
- `.\vcpkg.exe upgrade` (review)
- `.\vcpkg.exe upgrade --no-dry-run` to implement changes
- If vcpkg has not been updated in a while, you may need to just delete the vcpkg instance and clone again, as there has been major changes done to the package the last few months.
 
Note:
- The log information posted shows the file being downloaded from:
   https://github.com/intel/tbb/archive/427c252e0bb9e191767a62d8a744b21950c343f6.tar.gz
   with a filename of intel-tbb-427c252e0bb9e191767a62d8a744b21950c343f6.tar.gz
- The current vcpkg portfile.cmake for port tbb shows it should be downloaded from:
   https://github.com/oneapi-src/oneTBB/archive/427c252e0bb9e191767a62d8a744b21950c343f6.tar.gz
   with a filename of oneapi-src-oneTBB-427c252e0bb9e191767a62d8a744b21950c343f6.tar.gz
- The SHA512 hash for the filename is correct in the current vcpkg portfile.cmake for port tbb.

**Comment by NancyLi1013** [comment]
@RameshKandukuriB 

Please follow the guidelines from @timautry to update vcpkg to the latest commit to build `tbb`.

**Comment by RameshKandukuriB** [comment]
@timautry , @NancyLi1013 I followed above, still its referencing https://github.com/intel/tbb/archive/427c252e0bb9e191767a62d8a744b21950c343f6.tar.gz...
Same issue on log is from azure dev-ops. I am referencing vcpkg as submodule for devops, every time it pulls the submodule (vcpkg). I think the submodule-vcpkg should be latest.  Then  bootstrap-vcpkg.bat,  upgrade & install.
Not sure why its still referencing old tbb.

**Comment by NancyLi1013** [comment]
If you cannot update successfully, it might be better to build this in a clean environment.

**Comment by RameshKandukuriB** [comment]
Thanks @NancyLi1013, @timautry  I did updated, pulling oneTBB and building successfully.

**Comment by NancyLi1013** [comment]
Thanks for your update @RameshKandukuriB.

@atharkes 
Do you still have this issue now?

**Comment by NancyLi1013** [comment]
I'm closing this issue for now since no response in a long time.
