### ISSUE TITLE
[qt5-x11extras:x64-linux] build failure

### ISSUE THREAD

**Issue by hellozee** [microsoft/vcpkg#11886]
**Host Environment**
- OS: Kubuntu 20.04
- Compiler: GCC 9.3.0

**To Reproduce**
`./vcpkg install qt5-x11extras`

**Failure logs** 
```
The folder /include is empty or not present. This indicates the library was not correctly installed.
Found 1 error(s). Please correct the portfile:
    /home/hellozee/vcpkg/ports/qt5-x11extras/portfile.cmake
-- Performing post-build validation done
Error: Building package qt5-x11extras:x64-linux failed with: POST_BUILD_CHECKS_FAILED
```

**Comment by Neumann-A** [comment]
This happens if not all the required system libraries for the xcb feature in qt5-base are installed. With #11596 you will get an error in qt5-base instead. 
```
sudo apt -y install libxext-dev libxfixes-dev libxrender-dev libxcb1-dev libx11-xcb-dev libxcb-glx0-dev
sudo apt -y install libxkbcommon-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev
```

**Comment by hellozee** [comment]
Thanks a lot, @Neumann-A that fixed the issue, :smile:

**Comment by jsutes** [comment]
@Neumann-A Do you know how to get feedback from the `./vcpkg install qt5-x11extras` install process to determine which system libraries are still missing?

I'm running into this issue on centos 8 which uses DNF as the package manager.  I've been going through each package name in the apt install list and trying to search for the corresponding name for dnf, but I must still be missing something because `./vcpkg install qt5-x11extras` still gives the same error.

**Comment by Neumann-A** [comment]
You have to look into the qt5-base config error log. `<buildtrees>/qt5-base/config-<triplet>-(dbg|rel)-err.log`. Or you add to variable `CORE_OPTIONS` in the portfile the switch `-system-xcb`. Then `qt5-base` should fail if it is missing the dependencies
