### ISSUE TITLE
This seems like something you'd have to report to Defender (via the Windows Feedback tool), or otherwise exclude.

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#11972]
`This seems like something you'd have to report to Defender (via the Windows Feedback tool), or otherwise exclude.`

_Originally posted by @BillyONeal in https://github.com/microsoft/vcpkg/issues/11854#issuecomment-641685023_

also reference: https://github.com/microsoft/vcpkg/issues/11944

Why? 

Microsoft/Windows Defender has done exactly what it was designed to do - flagged a script  having commands to add virus exclusions to exempt all the files/folders on C:\ and D:\ and several binaries from being scanned. 

Just the script being present makes the system ripe for the picking as it is being pushed to all vcpkg instances local or not. 

A nefarious person just needs to find a system with vcpkg running windows using only windows defender as malware protection.

MS Windows Defender/Powershell Commands Reference:
https://docs.microsoft.com/en-us/powershell/module/defender/Add-MpPreference?view=win10-ps

**Question: why does vcpkg need to make all of the files/folders on C:\ D:\ and other processes exempt from being scanned by malware software?**

`I would guess performance on the azure-pipeline, but to sacrifice security for performance in today's age would be highly irregular.`

**Comment by BillyONeal** [comment]
That script is the script that provisions vcpkg's test machines used for PR validation here on GitHub. It is not invoked by vcpkg itself under any circumstances. The test machines, by design, build any PR submitted on GitHub, and we have no means of ensuring those PRs contain no malicious code. Example: https://github.com/BillyONeal/temp-vmss-demo/pull/1

As a result we already consider the test machines hostile entities, so information that they are infected is not interesting to us; the machines only live for a few hours at most and then are completely nuked from orbit (by outright deleting the underlying Azure VM) regularly. Moreover, leaving the AV enabled on them creates false positive / reliability problems because those machines run scripts that create thousands of binaries the AV has never seen. (That is, this script is trying to prevent the same condition on our CI machines that the script itself is creating for the reporter of the original issue)

Maybe if we rename the file with a .txt extension or something that will make the AV happy....

**Comment by BillyONeal** [comment]
>Just the script being present makes the system ripe for the picking as it is being pushed to all vcpkg instances local or not.

No, because anyone who could run the script could themselves run the underlying `Add-MPPreference`.

**Comment by timautry** [comment]
Is there a mechanism or one developed to have some type of a 
hidden or inaccessible branch of vcpkg that is only cloned or updated if the remote system initiating the git clone or pull request is identified as an azure pipeline, using a specific account and/or falls within a certain range of ip addresses?

In other words if the remote system does not meet certain criteria then the components required for the azure pipeline PR approval process are not cloned/updated.

Please note:
- The external users of vcpkg do not consider their systems hostile entities or compromised.
- The external users of vcpkg also compile and link those same binaries on their machines having domain/security/system  administrators with policies in place to prevent even the existence of such a script.
- Just in this day and age, developers have a hard enough time satisfying administrators, auditors, insurance underwriters and c types in what the developers are doing is safe and meets all kinds of tests, rules, acts, especially the dreaded Sarbanes Oxley Act (SOX) on financial systems.
- The obstacles one has to overcome can play into a decision to propagate the adoption and use of a software package, especially open source. One less red flag makes it easier to check all the boxes.

**Comment by BillyONeal** [comment]
>Is there a mechanism or could one be developed to have some type of a hidden or inaccessible branch of vcpkg that is only cloned or updated if the remote system initiating the git clone or pull request is identified as an azure pipeline, using a specific account and/or falls within a certain range of ip addresses?

No. Part of doing development in the open is that the infrastructure must also be in the open. Anyone can set up their own fork with CI set up identically to ours. We also get contributors who modify that script to install additional prerequisites of some ports occasionally.

I was going to try mitigations like changing the file extension (in the normal scenario the script is passed to `Invoke-AzVmCommand` so it need not have a .ps1 extension on disk) or removing the C:\ entry (now that we've migrated all the interesting work to D:\) but I asked Defender to explicitly scan our scripts directory and it reported no hits, so I can't really fix it to avoid the detection.

>The external users of vcpkg do not consider their systems hostile entities or compromised.

That's fine, they aren't running that script. Notably that script requires administrative permissions and vcpkg does not, so it couldn't run that script even if it wanted. You can just delete the whole azure-pipelines directory.

>The external users of vcpkg also compile and link those same binaries on their machines having domain/security/system administrators with policies in place to prevent even the existence of such a script.

Do they realize that the command to do the problematic part of the script you're complaining about is shorter than the script? By this logic the literal command itself can't exist because after all the code to do it is in there.

>The obstacles one has to overcome can play into a decision to propagate the adoption and use of a software package, especially open source. One less red flag makes it easier to check all the boxes.

If you're in an environment with such issues you can always export a built package; you probably don't want the tool that exists to download code from the internet and execute it running in such a sensitive environment anyway. (That applies equally to npm, Conan, crate, etc. since they all run external code)

**Comment by timautry** [comment]
I added the following lines to my main clone/pull script from github/microsoft/vcpkg - it will solve the problem for me at this time.

`git rm .\scripts\azure-pipelines\windows\provision-image.ps1`
`git commit -m "remove .\scripts\azure-pipelines\windows\provision-image.ps1"`

**Comment by BillyONeal** [comment]
@timautry Can you give the PR linked above a shot and let me know if it resolves the detection for you?

```
git remote add BillyONeal https://github.com/BillyONeal/vcpkg
git fetch BillyONeal
git switch mitigate_attempt
```

**Comment by timautry** [comment]
@BillyONeal It works great for me - windows defender and malwarebytes stand-alone scans did not raise any flags.
Like mentioned, I think the warning comes when the scanner sees those commands in a script type file, a ps1, cmd, bat, etc...
Thank you for taking the time to do this... 
I am sorry for taking so long, I had take my automobile to the dealer for work this morning.
