### ISSUE TITLE
Enable HAVE_GLIB flag in harfbuzz

### ISSUE THREAD

**Issue by zcream** [microsoft/vcpkg#12142]
I have a custom static build for glib. In vcpkg\buildtrees\harfbuzz\src\2.6.6-8af0fa33ca\src\hb-glib.cc there are some functions disabled under 
>#ifdef HAVE_GLIB

So I enabled the flag in CMakeLists.txt in 
>vcpkg\buildtrees\harfbuzz\src\2.6.6-8af0fa33ca\CMakeLists.txt in 

It was originally
>option(HB_HAVE_GLIB "Enable glib unicode functions" OFF)

I changed it to
>option(HB_HAVE_GLIB "Enable glib unicode functions" ON)

However, this did not change the build behaviour. so I had to replace the 
>#ifdef HAVE_GLIB

by 
>#if 1

Why doesnt the change in CMakeLists.txt affect the build?

**Comment by NancyLi1013** [comment]
Hi @zcream 
Thanks for posting this issue.
If you want to build with `glib`, you need to install like this:
`./vcpkg install harfbuzz[glib]`

Since the value of option `HB_HAVE_GLIB` has been controlled by feature `glib`.

BTW, currently glib doesn't support static build. I'm not sure if you can build successfully.

**Comment by NancyLi1013** [comment]
I'm closing this issue for now since no response.
Please feel free to reopen this if it is still a problem for you.
