### ISSUE TITLE
Failed to take the filesystem lock on .vcpkg-root

### ISSUE THREAD

**Issue by AlexAltea** [microsoft/vcpkg#12286]
Our CI relies on a global vcpkg installation for each platform. Build jobs happen in unique directories where we run `vcpkg install` to deal with any necessary dependencies. After the merging of https://github.com/microsoft/vcpkg/pull/11757 we started using manifest files, which worked perfectly (thanks @strega-nil!).

**Describe the bug**

The manifest PR (https://github.com/microsoft/vcpkg/pull/11757) added a filesystem lock (*.vcpkg-root*) which multiple build scripts might try to acquire simultaneously. The current timeout of 1.5-ish seconds is not enough since the lock seems acquired until the `vcpkg install` command finishes. See: https://github.com/microsoft/vcpkg/blob/a28bfe76740349b519d4737260dad8e160b41f6c/toolsrc/src/vcpkg/base/files.cpp#L932-L943
Calling `vcpkg install` in directories with manifest files shouldn't modify the global `%VCPKG_ROOT%/installed` folder (afaik!), but place everything in `./vcpkg_installed` instead. Thus, it seems unnecessary to lock *vcpkg* globally for minutes at a time.

**Environment**
- OS: Any
- Compiler: Any

**To reproduce**

1. Simultaneously run two instances of `./vcpkg install` in different repositories.
2. One of the instances will fail to acquire the filesytem lock on *.vcpkg-root*:
    ```
    $ vcpkg install
    Waiting to take filesystem lock on /Users/ci/vcpkg/.vcpkg-root...
    Failed to take the filesystem lock on /Users/ci/vcpkg/.vcpkg-root:
        Resource busy
    ```

**Expected behavior**

I think there's two possible solutions to this problem (or even a combination of both):
1. Adding `--lock-timeout <seconds>` (or similar) argument for any *vcpkg* command that might try to take the lock, so that multiple `vcpkg install` invocations could execute in series for a sufficiently high timeout.
2. **Only** acquire the lock when writing to files under `%VCPKG_ROOT%`. When installing dependencies from *vcpkg.json* manifest files, everything will be written to `vcpkg_installed` folder, so there's no need to lock *vcpkg* globally while that happens.

**Comment by Voskrese** [comment]
![2020-07-06_211050](https://user-images.githubusercontent.com/10104740/86596749-55fbfd00-bfcd-11ea-8cb6-9e35477066e6.png)

**Comment by strega-nil** [comment]
The reason we do this is so that we lock the buildtrees and downloads and such, which are shared globally -- would adding a `--wait-for-lock` flag work for you? Or do you need a more fine-grained locking mechanism?

**Comment by Voskrese** [comment]
why don't immediately do with the parameter, lock by default, and don't block with the parameter

**Comment by strega-nil** [comment]
@Voskrese because that is a disaster waiting to happen -- if you both try to write to buildtrees at the same time, then you're gonna get bad failures.

**Comment by AlexAltea** [comment]
> would adding a `--wait-for-lock` flag work for you?

Yes, this would solve the issue. Currently we are working around this issue by manually wrapping `vcpkg install` commands with *flock* in Linux/macOS and *System.Threading.Mutex* in Windows (Powershell), but this feels rather hacky.

> Or do you need a more fine-grained locking mechanism?

Are there any plans to cache built vcpkg packages? (Judging by https://github.com/microsoft/vcpkg/pull/12091 it seems so).
If so, then a simple `--wait-for-lock` would be enough, as in *N* simultaneous CI jobs, only 1 job would actually build dependencies and the remaining N-1 would wait for the lock and immediately return the cached dependencies.

If there's no caching then `--wait-for-lock` "solves the error" but at the expense of increasing build times up to N times.

**Comment by strega-nil** [comment]
Cool, then I'll add that feature in #12227 :)

**Comment by christophe-calmejane** [comment]
@strega-nil Since I merged the manifest code, I too have issues with our CI. We use and mix some complex ports and custom toolchain that leads to a reentrant call to `vcpkg install` (on purpose) but always on the same process. Would it be possible for **the lock to be reentrant**, or delay the lock for when it's actually needed?
My reentrant call immediately returns because the sub-package I try to install is guaranteed to always be installed already, so it's just a matter or letting vcpkg check for the package to be installed then return.

**Comment by strega-nil** [comment]
Hmm... alright, yeah, I think I'll take the lock out for now in non-manifest builds until we can lock cleanly.

**Comment by christophe-calmejane** [comment]
Thanks, although I do have a need for a lock on vcpkg database to prevent multiple install from different process, but I’d rather tell my users to not run multiple CI at the same time than it failing all the time :)

Implementing a reentrant file lock might be challenging, as it’s usually not supported by system APIs, but it should be doable.
Could you add a reference to this ticket when you have merged your « fix »?
Thanks a lot

**Comment by strega-nil** [comment]
@christophe-calmejane I'm not concerned about it right now, because I'm keeping the file lock for users of the new manifest mode; this means that existing users _will not_ be broken, while new users using the new mode will write their code as if the manifest mode exists (and hopefully we won't need reentrant locks)

**Comment by ras0219-msft** [comment]
From https://github.com/googleapis/google-cloud-cpp/issues/4487:

> docker .... --volume /tmpfs/src/github/google-cloud-cpp/cmake-out/home/ci-ubuntu-18.04-quickstart-cmake:/h ....
> ...
> Waiting to take filesystem lock on /h/vcpkg-quickstart/.vcpkg-root...
Failed to take the filesystem lock on /h/vcpkg-quickstart/.vcpkg-root:
    Device or resource busy
Exiting now.

It looks like the file locking APIs we use are unavailable in a mapped docker volume. This looks like a straightforward case of "we should offer an environment variable to not take the lock". Users in docker can pass `--env VCPKG_SKIP_LOCKING=1`.

**Comment by ras0219-msft** [comment]
@christophe-calmejane JFYI, reentrant calls to `vcpkg install` on the same install tree _will_ corrupt the database. This is because the database is not synchronized to disk during port builds. We'd strongly recommend that either:
1. The port checks-with-failure and the install lifted out and run before the port's build
2. The port clones/embeds an inner copy of vcpkg with different root, packages, buildtrees, and installed directories. This ensures no corruption.

Ideally, the install could be listed as a dependency, but I assume you're doing this because of a cross-compilation scenario?

**Comment by christophe-calmejane** [comment]
@ras0219-msft Well, it's not that simple as I'm mixing multiple build systems together :)
I actually considered looking at the files directly but I didn't want to hardcode anything in the main build system (that is calling vcpkg), like for exemple the path to installed folder, just in case it changes in the future. I mean, it's safer to let vcpkg do it's job and not having to understand its underlying/internal/private stuff, that's why I call the binary directly.
I also considered parsing the output of a `vcpkg list` but I don't like it either (same reason, in case the output changes).
I'll probably have to think about it at some point anyway, thanks for your input :)
