### ISSUE TITLE
portfile.cmake question

### ISSUE THREAD

**Issue by KindDragon** [Microsoft/vcpkg#123]
Why most portfile calls `vcpkg_build_cmake()` and `vcpkg_install_cmake()`?
`vcpkg_install_cmake` build package too, so we can remove `vcpkg_build_cmake()`

**Comment by ras0219-msft** [comment]
I think removing `vcpkg_build_cmake()` from most portfiles should be fine; as you've mentioned it serves no purpose most of the time (and overbuilds sometimes). We additionally are unaffected by a partial installation (say the build fails halfway through installation) because we "stamp" the package as good only after the portfile completes successfully.

**Comment by KindDragon** [comment]
> (and overbuilds sometimes)

Yeah, it increases build time of about two times

**Comment by ras0219-msft** [comment]
Thanks for bringing this up.
