### ISSUE TITLE
[opencv4, opencv4[gtk], gtk:x64-linux] build failure

### ISSUE THREAD

**Issue by TumanovM** [microsoft/vcpkg#12395]
**Host Environment**
- OS: Linux x64, Ubuntu 18.04
- Compiler: gcc 10.1, CMake 3.18

**To Reproduce**
`./vcpkg install opencv4`
`./vcpkg install gtk`

**Failure logs** 
opencv4 [install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/4910332/install-x64-linux-dbg-out.log)
gtk [config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/4910336/config-x64-linux-dbg-err.log)

**Additional context**
I've rebuilt glib:x64-linux but it didn't affect opencv build process, also see [these](https://github.com/microsoft/vcpkg/issues/12275#issuecomment-656586291) comments

**Comment by JackBoosY** [comment]
@cenit Could you please take a look?

Thanks.

**Comment by JackBoosY** [comment]
Related: #12275

**Comment by TumanovM** [comment]
> ```
> /usr/include/gstreamer-1.0/gst/gst.h:27:10: fatal error: glib.h: Нет такого файла или каталога
>    27 | #include <glib.h>
>       |          ^~~~~~~~
> ```

Sorry, I forgot that logs are on russian. :)
It says "no such file or directory"

**Comment by cenit** [comment]
I removed gtk feature of opencv from the 4.3 update. I didn't inspect its history, but somehow it was mismanaged, because vcpkg gtk is broken on osx/Linux (custom CMakeLists.txt is not so portable) and opencv can use gtk only on osx/Linux, so there was no way it was a working or tested feature.

Fixing gtk on Linux would require abandoning the custom CMakeLists.txt and using its native build toolchain. Something very interesting and important, but beyond the scope of an opencv PR

**Comment by JackBoosY** [comment]
Hmm I can't repro this issue now, is this resolved?

**Comment by cenit** [comment]
yes, gtk feature has been restored when we moved from custom cmakelists to meson build
