### ISSUE TITLE
Triplets simplifying suggestion 

### ISSUE THREAD

**Issue by zabulus** [Microsoft/vcpkg#1241]
Inspired by issue: https://github.com/Microsoft/vcpkg/issues/1240 and others regarding static/dynamic linking.
What if we won't use predefined triplets, but instead use some fine grained parts, that can be consumed by explicitly specifying.
For example, we have arm-uwp, x64-uwp, x86-windows. Let's split them to separate arm, x64, x86, uwp, windows. After that we would have arm-windows, x64-windows, x86-uwp and so on, all combinations without blowing up with count of triplets.
vcpkg could use the same syntax, and should search for this parts, and combine them into resulting triplet. 
Conflicts should be detected if a different part changes already set variable.

**Comment by ras0219-msft** [comment]
I just added some more docs on triplets, which might be useful here: http://vcpkg.readthedocs.io/en/latest/users/triplets/

This is definitely the core of how things already work; we just record the particular selections of those fine grained parts in a small number of files inside `triplets\` for the combinations that the user actually cares about.
```cmake
# x86-windows-static.cmake
set(VCPKG_TARGET_ARCHITECTURE x86) # x64, arm, etc
set(VCPKG_CRT_LINKAGE static) # dynamic
set(VCPKG_LIBRARY_LINKAGE static) # dynamic

set(VCPKG_CMAKE_SYSTEM_NAME) # WindowsStore
set(VCPKG_PLATFORM_TOOLSET) # v141, v140
```
However, the triplets system is quite a bit more powerful than just this; every setting can be potentially adjusted on a per-port basis.
```cmake
if(PORT MATCHES "qt5|zlib|openssl|tiff")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
else()
    set(VCPKG_LIBRARY_LINKAGE static)
endif()
```
We also allow specifying additional compiler flags (a very recent feature which only works for cmake libraries at the moment):
```cmake
set(VCPKG_CXX_FLAGS -D_WIN32_WINNT=0x600)
set(VCPKG_C_FLAGS -D_WIN32_WINNT=0x600)
```
I suspect we will also use them in the future to handle complex library settings that can't be managed by Feature Packages (#1205):
```cmake
# Hypothetical future
if(PORT STREQUAL "harfbuzz")
    set(USE_UNICODE_BACKEND icu)
    # set(USE_UNICODE_BACKEND glib)
endif()
```
These settings can clearly get pretty complex, which is why we need to store them in files with nice names. Each triplet encapsulates a lot more than just a single build configuration -- it actually captures unique build configurations for every individual library at once!

---

Finally, the concern with blowing up the count of triplets isn't just having a lot of files on disk (it would be pretty trivial to just generate the hundred or so files and check them in). The real problem is that the test space facing maintainers gets just as large! By providing a select subset of all the possible triplets by default (while still leaving it open to the user to create their own) we hope to focus usage and testing on a practical core, which means users are more likely to have things work without wasting maintainer's time on combinations that aren't used.

**Comment by zabulus** [comment]
I'd like to clarify what my suggestion could allow.
Ok, let's leave existing triplets as is.
Issue I mentioned was about specifying WINVER. I suggest to add winxp, win7, win8 triplets(???) that could be used in addition to existing:
```vcpkg install pkg:x64-windows-winxp```
```vcpkg install pkg:x64-windows-win7```
Latter is optional and could be ommitted. This allows to manually add specific options without editing/copying existing triplets by end-user.
Same could be used for port-specific defines: 
```vcpkg install harfbuzz:x64-windows-icu_backend```

If you think such extension won't be useful for end-user, feel free to close the issue.

**Comment by ras0219-msft** [comment]
> This allows to manually add specific options without editing/copying existing triplets by end-user.
Same could be used for port-specific defines:
vcpkg install harfbuzz:x64-windows-icu_backend

The trouble is that this approach would quickly result in truly insane triplets:
```
vcpkg install harfbuzz --triplet x64-windows-use_harfbuzz_icu_backend-glib_use_opengl_backend-nodejs_use_chakracore-boost_use_python3-win10.0.15350.0-static_crt-....
```

I do agree we should look at making it easier to specify targeting down-level Windows versions, but we can better discuss that in the other issue.

It may also be worth looking at some sort of `vcpkg create-triplet` bootstrapper if users actively need to create unique, non-default triplets.
