### ISSUE TITLE
ragel:x64-windows-static not working

### ISSUE THREAD

**Issue by sibylantonioforanna** [microsoft/vcpkg#12557]
Qt5 uses this library so it isn't working as well.
Problem: the following url is ko: http://www.colm.net/files/ragel/ragel-6.10.tar.gz

**Comment by StarGate-One** [comment]
- Have you tried clicking on the link and downloading it manually?
- I was able to download the file manually.
- If you can download manually, put the file in `<vcpkg-root>\downloads` and try again.
- Otherwise post the console output and any error logs produced to assist in troubleshooting further.

**Comment by sibylantonioforanna** [comment]
Looks like I wasn't able to reach the server only temporarily, so I manually downloaded the file from a different server and put it into the downloads folder. Now I can reach the server though, so we can close the issue.
Thanks.

**Comment by PhoebeHui** [comment]
@StarGate-One, thanks for your commnent!
