### ISSUE TITLE
[eastl] Incorrect EABase include 

### ISSUE THREAD

**Issue by valenotary** [microsoft/vcpkg#12734]
**Describe the bug**
EABase is not included correctly, and not in sync with the EASTL port either. EABase is stored in a different file directory level than what EASTL expects.

**Environment**
- OS: Windows
- Compiler: MSVC

**To Reproduce**
1. ./vcpkg install eastl 
2. See error

**Expected behavior**
Should just work out of the box (compile and link with no issues).

**Failure logs** 
-(please attached failure logs)
![image](https://user-images.githubusercontent.com/32428785/89259433-25fd4500-d5df-11ea-9523-c6c81b65086b.png)
![image](https://user-images.githubusercontent.com/32428785/89259475-3dd4c900-d5df-11ea-978e-0b42468a7c43.png)
![image](https://user-images.githubusercontent.com/32428785/89259492-488f5e00-d5df-11ea-942b-d67733931f77.png)

**Comment by PhoebeHui** [comment]
Duplicated issue to https://github.com/microsoft/vcpkg/issues/11262

**Comment by PhoebeHui** [comment]
See more information in issue #11262.

**Comment by xgalaxy** [comment]
So it looks like this works fine when using cmake but if using Visual Studio directly it does not.
That screams vcpkg issue to me **not** an upstream issue.

The cmake patch file appears to be adding `include/Common` to the includes list but when using Visual Studio directly this doesn’t happen. How do we fix this ports file or the `EABase` port file so that does happen correctly?
