### ISSUE TITLE
Get our act together regarding _ underscores

### ISSUE THREAD

**Issue by ignacionr** [microsoft/vcpkg#12816]
****

**Is your feature request related to a problem? Please describe.**
At some point back in 2017, you guys merged https://github.com/microsoft/vcpkg/pull/1773/commits/aef3577672b469ed915a7b0680d5e1ccf36347ed which explicitly allowed the use of '_' (underscore) as part of the package name. The code there was refactored into what is now:

https://github.com/microsoft/vcpkg/blob/master/toolsrc/src/vcpkg/packagespec.cpp#L107
-so back to not allowing underscores.

That lack of underscores has surfaced as issues sometimes, such as https://github.com/microsoft/vcpkg/pull/10820 .

In the implementation of manifests, you are explicitly banning underscores. See https://github.com/microsoft/vcpkg/blob/f4b66c5e2bea02aaa9569b5369e3af3bb0bf737c/scripts/vcpkg.schema.json#L30 

**Proposed solution**
Just allow underscores.

**Describe alternatives you've considered**
Alternatively, document the reason why you may want to disallow underscores as part of a package name.

**Additional context**
Given by the history of the project, current code, and issue cited.
Additional context: Github repos CAN feature underscores. So we either support them, or issues will keep surfacing.

By the way, sending much LOVE to this product. Started using it and it JUST WORKS. This is beautiful.

**Comment by strega-nil** [comment]
The reason I don't want to allow both, at least personally, is then suddenly we have to deal with having both for names of projects -- should it be `directx-sdk` or `directx_sdk`? Rust had this exact issue, with their solution (<https://github.com/rust-lang/rfcs/blob/master/text/0940-hyphens-considered-harmful.md>) being to allow `-` in package names and convert them to underscores in Rust code (but if they didn't have backwards compatibility to worry about, it's likely they wouldn't have had both options in the first place). My opinion is that it's good to have One, and Only One way to do things. However, we will bring this up at our next meeting. Thanks so much for bringing it up!

**Comment by ignacionr** [comment]
Thank you for the quick turnaround! By the way, do you guys have weekly meetings? Do you publish your conclusions somewhere?
I may have missed that info, don't mind RTFM as an answer.

**Comment by ignacionr** [comment]
Today I found an interesting **argument against the use of ```-```**.

- One way of helping cmake find a package, is by setting an environment value with the name of the package and ```PATH``` appended.

- Environment variables **cannot** contain dashes (they follow C symbol rules). [related stack exchange question](https://unix.stackexchange.com/questions/23659/can-shell-variable-name-include-a-hyphen-or-dash)

- As a result, if the name of the package is ```sdl2-image``` then the resulting ```sdl2-imagePATH``` environment variable cannot be set.

**Comment by BillyONeal** [comment]
I vote with Nicole that we should pick one or the other, and given that we've already effectively chosen `-`, that argues to keep `-`.

**Comment by BillyONeal** [comment]
@ras0219 @strega-nil and I just talked about this in person and effectively ended up at the same place. To confirm:

* We would not want to allow *both* `_` and `-`, because those characters are commonly mistyped/confused and only allowing one gives us the ability to fix that up.
* Even though we might have liked `_` if we had made a different decision back in 2016 (at least I am personally persuaded by your C symbol name description above), the horse has already left the barn here. Changing this to standardize on `_` instead, even if we could magically fix that up in the tool, would break most users of overlay-ports, outstanding PRs, etc.

As a result we land at the status quo of accepting only `-`. We appreciate the suggestion though!

Thanks for your contribution.

**Comment by ras0219** [comment]
That's a great point about environment variables; however it's actually a different namespace. The name of the cmake `find_package()` doesn't actually need to match the vcpkg package name (and we have several ports where they do use underscores in the CMake package name). I'd argue this is actually a bit of a CMake bug and CMake should probably offer something for users that decide to provide `foo-bar-config.cmake` files (maybe it should automatically consider `FOO_BAR_ROOT`?).

Due to this CMake bug, it actually makes it even more important for us to require only one; this way, if we generate CMake config files in the future, we have the ability to "uppercase" the hyphens to underscores and guarantee no conflicts.

**Comment by ras0219** [comment]
Also you'll find that in the PR https://github.com/microsoft/vcpkg/pull/1773 I reverted that particular commit before merging :)
