### ISSUE TITLE
How do I integrate PowerShell

### ISSUE THREAD

**Issue by TheVeryDarkness** [microsoft/vcpkg#12872]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

I can't integrate PowerShell, though I have installed one, whose version is exactly 6.2.1. It seems vcpkg can't find my PowerShell.

I wanna know how to specify the PowerShell path.

![QQ图片20200812171305](https://user-images.githubusercontent.com/50262419/89997886-5b7cef00-dcbf-11ea-9686-839ad04cbf32.png)

**Comment by JackBoosY** [comment]
At present, the powershell used by vcpkg is downloaded by vcpkg itself, and the system or user installation is not accepted temporarily.
This is because we need to ensure that the powershell version is consistent with the ps1 script in vcpkg, so as to avoid execution failures caused by function changes.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
