### ISSUE TITLE
LNK1104 "sqlite3.lib"

### ISSUE THREAD

**Issue by coderc264** [microsoft/vcpkg#12952]
**Describe the bug**
I've recently updated my vcpkg installation. Aftyer that i changed the find_package and target_link_libraries from "sqlite3" to "unofficial-sqlite3" the compiler works but the linker not. The problem is that the cmake insert 2 rows for the library sqlite3.lib
one with the full path and another only with the name "sqlite3.lib".

**Environment**
- OS: Windows-10.0.19041
- Compiler: MSVC 14.27.29110

**To Reproduce**
1. install sqlite3 (vcpkg.exe install sqlite3:x64-windows)
2. add in the cmake "find_package(unofficial-sqlite3 CONFIG REQUIRED)"
3. add in the cmake "target_link_libraries(main PRIVATE unofficial::sqlite3::sqlite3)"
Repro code when

**Expected behavior**
Compiler link perfectly

**Failure logs** 
-LINK : fatal error LNK1104: cannot open file 'sqlite3.lib'

**Additional context**

**Comment by PhoebeHui** [comment]
@coderc264, I can't repro this issue.

Do you execute './vcpkg integrate install' before using it? you need pass the -DCMAKE_TOOLCHAIN_FILE in your project.

**Comment by coderc264** [comment]
yes './vcpkg integrate install' and -DCMAKE_TOOLCHAIN_FILE. I have the same issue with CLion only after the new release that changed "sqlite3" with "unofficial-sqlite3"

**Comment by PhoebeHui** [comment]
@coderc264, could you double check the below files under .\installed\x64-windows\

Check if the libs, config and targets files installed correctly.
lib\sqlite3.lib
debug\lib\sqlite3.lib
share\unofficial-sqlite3\unofficial-sqlite3-config.cmake 
share\unofficial-sqlite3\unofficial-sqlite3-targets-debug.cmake 
share\unofficial-sqlite3\unofficial-sqlite3-targets-release.cmake

It should find the lib successfully since the lib path has specified in the targets files.

**Comment by coderc264** [comment]
I resolved the problem, i forgot to change "sqlite3" in to  "unofficial-sqlite3" it even in tests. 
Thank you very much
