### ISSUE TITLE
[brotli:x64-windows] build failure

### ISSUE THREAD

**Issue by jens1433** [microsoft/vcpkg#12955]
**Host Environment**
- OS: Windows 10 Pro 2004
- Compiler: VS 2019 16.7.1

**To Reproduce**
`./vcpkg install cpprestsdk:x64-windows` or `vcpkg install brotli:x64-windows`

**Failure logs** 
C:\dev\vcpkg>vcpkg install cpprestsdk:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * brotli[core]:x64-windows
    cpprestsdk[brotli,compression,core,default-features]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/3: brotli:x64-windows
Building package brotli[core]:x64-windows...
Could not locate cached archive: C:\Users\Jans\AppData\Local\vcpkg\archives\09\0972168266a4f4da734fe6b114049419121737df.zip
-- Using cached C:/dev/vcpkg/downloads/google-brotli-v1.0.7.tar.gz
-- Cleaning sources at C:/dev/vcpkg/buildtrees/brotli/src/v1.0.7-c2af986dcd.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/google-brotli-v1.0.7.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Using source at C:/dev/vcpkg/buildtrees/brotli/src/v1.0.7-c2af986dcd.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/dev/vcpkg/buildtrees/brotli/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\dev\vcpkg\buildtrees\brotli\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:300 (vcpkg_execute_required_process)
  ports/brotli/portfile.cmake:13 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package brotli:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
I first had another error but when i replaced all the files in ports/brotli with fresh ones from the source by just downloading it all as a zip it came up with this error.
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/5083407/config-x64-windows-out.log)
[CMakeError.log](https://github.com/microsoft/vcpkg/files/5083409/CMakeError.log)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/5083410/CMakeOutput.log)
i think it has something to do with this line
`LINK : fatal error LNK1104: cannot open file 'libucrt.lib'` from CMakeError.log

Old error
C:\dev\vcpkg>vcpkg install cpprestsdk:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * brotli[core]:x64-windows
    cpprestsdk[brotli,compression,core,default-features]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/3: brotli:x64-windows
Building package brotli[core]:x64-windows...
Could not locate cached archive: C:\Users\Jans\AppData\Local\vcpkg\archives\ed\edfd767db332644d676fdc61a2052baea824c2c5.zip
-- Using cached C:/dev/vcpkg/downloads/google-brotli-v1.0.7.tar.gz
-- Extracting source C:/dev/vcpkg/downloads/google-brotli-v1.0.7.tar.gz
-- Applying patch install.patch
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:51 (message):
  Applying patch failed.  error: corrupt patch at line 56

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:141 (vcpkg_apply_patches)
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/brotli/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:79 (include)

Error: Building package brotli:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by LilyWangL** [comment]
@jens1433 Thanks for posting this issue. I found the error message in your config log:
```
CMake Error at C:/dev/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/dev/vcpkg/buildtrees/brotli/x64-windows-rel/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/dev/vcpkg/downloads/tools/ninja/ninja-1.10.0/ninja.exe cmTC_c9c3d && [1/2] Building C object CMakeFiles\cmTC_c9c3d.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_c9c3d.exe
    FAILED: cmTC_c9c3d.exe 
    cmd.exe /C "cd . && C:\dev\vcpkg\downloads\tools\cmake-3.17.2-windows\cmake-3.17.2-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_c9c3d.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_c9c3d.dir\testCCompiler.c.obj  /out:cmTC_c9c3d.exe /implib:cmTC_c9c3d.lib /pdb:cmTC_c9c3d.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    LINK Pass 1: command "C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_c9c3d.dir\testCCompiler.c.obj /out:cmTC_c9c3d.exe /implib:cmTC_c9c3d.lib /pdb:cmTC_c9c3d.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_c9c3d.dir/intermediate.manifest CMakeFiles\cmTC_c9c3d.dir/manifest.res" failed (exit code 1104) with the following output:
    LINK : fatal error LNK1104: cannot open file 'ucrtd.lib'
    ninja: build stopped: subcommand failed.
```
This error is duplicate with issue: #12607 #6324, could you try the solution in these issues?

**Comment by LilyWangL** [comment]
Pinging @jens1433 for response.

**Comment by andnej** [comment]
I also have a similar issue

Computing installation plan...
The following packages will be built and installed:
    brotli[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: brotli:x86-windows
Building package brotli[core]:x86-windows...
Could not locate cached archive: C:\Users\Andre Prasetya\AppData\Local\vcpkg\archives\b0\b04406db1825bcccd0306d570c97cd7bc9a4fbb8.zip
-- Using cached C:/Users/Andre Prasetya/source/repos/vcpkg/downloads/google-brotli-v1.0.7.tar.gz
-- Cleaning sources at C:/Users/Andre Prasetya/source/repos/vcpkg/buildtrees/brotli/src/v1.0.7-c2af986dcd.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Andre Prasetya/source/repos/vcpkg/downloads/google-brotli-v1.0.7.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Using source at C:/Users/Andre Prasetya/source/repos/vcpkg/buildtrees/brotli/src/v1.0.7-c2af986dcd.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Fixing pkgconfig file: C:/Users/Andre Prasetya/source/repos/vcpkg/packages/brotli_x86-windows/lib/pkgconfig/libbrotlicommon.pc
-- Fixing pkgconfig file: C:/Users/Andre Prasetya/source/repos/vcpkg/packages/brotli_x86-windows/lib/pkgconfig/libbrotlidec.pc
-- Fixing pkgconfig file: C:/Users/Andre Prasetya/source/repos/vcpkg/packages/brotli_x86-windows/lib/pkgconfig/libbrotlienc.pc
-- CHECK_LIB_brotlicommon_RELEASE:CHECK_LIB_brotlicommon_RELEASE-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:232 (message):
  Library "brotlicommon" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:297 (vcpkg_fixup_pkgconfig_check_files)
  ports/brotli/portfile.cmake:25 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)


Error: Building package brotli:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
@andnej, this is a different issue, duplicated to https://github.com/microsoft/vcpkg/issues/13103, and will fixed by PR https://github.com/microsoft/vcpkg/pull/13126

@jens1433, try to reisntall the windows sdk, and reopen this issue if it still be a problem for you.
