### ISSUE TITLE
[opencv4] NVCUVID for ffmpeg.

### ISSUE THREAD

**Issue by FishHe** [microsoft/vcpkg#13120]
Now the opencv port can not build ffmpeg with NVCUVID.

**Comment by JackBoosY** [comment]
cc @cenit

**Comment by cenit** [comment]
Can you please post any error log?

**Comment by FishHe** [comment]
When I cv::cudacodec::VideoReader, it breaks with no_cuda error. 
I think there may be a new feature for opencv to enable:

**CONTROL**

`
Feature: nvcuvid
Build-Depends: cuda, ffmpeg
Description: GPU acceleration for video decomposition.
`

**portfile.cmake**

`
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
 "ade"      WITH_ADE
 "contrib"  WITH_CONTRIB
 "cuda"     WITH_CUDA
 "cuda"     WITH_CUBLAS
 "eigen"    WITH_EIGEN
 "ffmpeg"   WITH_FFMPEG
 "gdcm"     WITH_GDCM
 "halide"   WITH_HALIDE
 "jasper"   WITH_JASPER
 "jpeg"     WITH_JPEG
 "nonfree"  OPENCV_ENABLE_NONFREE
 "openexr"  WITH_OPENEXR
 "opengl"   WITH_OPENGL
 "png"      WITH_PNG
 "qt"       WITH_QT
 "sfm"      BUILD_opencv_sfm
 "tiff"     WITH_TIFF
 "webp"     WITH_WEBP
 **"nvcuvid"  WITH_NVCUVID**
 "world"    BUILD_opencv_world
)

`

**Comment by JackBoosY** [comment]
@cenit  Any ideas?

**Comment by cenit** [comment]
might require a ffmpeg feature and not just base ffmpeg to work? @mcmtroffaes might be more helpful

**Comment by mcmtroffaes** [comment]
Hypothetically, if opencv4 uses ffmpeg for cuvid acceleration (I don't know if that's the case), it would need at least ``ffmpeg[core,avcodec,nvcodec]``. I'm not sure how to reproduce the problem however...

**Comment by patrikhuber** [comment]
I need `opencv4` with working nvcuvid video decoding, because the software version is too slow. #38928 never fixed/closed this: It just set `-DWITH_NVCUVID=OFF`.

There is no vcpkg feature flag to turn this on.

As far as I can see there are two roads to enabling this:

A) Use the NVIDIA Video Codec SDK (https://developer.nvidia.com/video-codec-sdk). We could provide a thin wrapper port like CUDA or cuDNN in vcpkg which just points to the system Video Codec SDK. But then OpenCV also needs a patch so that it can find the Video Codec SDK - current OpenCV expects this to be in the CUDA directory, which it is *not*. (This fix should be upstreamed but we could add it to the port while upstream doesn't have it - it looks like OpenCV's code for this is very old/deprecated. Note there is a `CUDA_nvcuvid_LIBRARY` but no variable for the header search path.)

B) We could use ffnvcodec. But since OpenCV calls nvcuvid directly (AFAICS), we'd need a thin wrapper-patch and a `.def` checked into the port, with the import lib generated at build time by `lib.exe /def` so OpenCV can link to it. I have this working locally already. Precedent: #9171 added `ffmpeg[nvcodec]` on top of `ffnvcodec`.

In both cases, the functionality actually comes from the DLL shipped by the NVIDIA driver, so A) or B) are merely a build-time question.

This is a bit out of my depth in terms of my vcpkg knowledge but if the maintainers tell me how they want this fixed, I can try and create a PR with Claude and test it?

**Comment by patrikhuber** [comment]
I created PR https://github.com/microsoft/vcpkg/pull/53839 as a proposal to fix this.
