### ISSUE TITLE
[ gtk:x86-windows-static] build failure

### ISSUE THREAD

**Issue by ScSofts** [microsoft/vcpkg#13208]
**Host Environment**
- OS: Windows 10 19041.450
- Compiler: Visual Studio 2017 Latest

**To Reproduce**
`./vcpkg install gtk:x86-windows-static`

**Failure logs** 
```
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows-static...
Starting package 1/16: glib:x86-windows-static
Building package glib[core]:x86-windows-static...
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg/archives\48\48b19ae47fe5a7257f9fcb1cebd423ee37a7c127.
zip
-- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: F:\SDK\vcpkg\triplets\community\x86-windows-static.cmake
-- Note: glib only supports dynamic library linkage. Building dynamic library.
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:42 (message):
  Refusing to build unexpected dynamic library against the static CRT.  If
  this is desired, please configure your triplet to directly request this
  configuration.
Call Stack (most recent call first):
  ports/glib/portfile.cmake:6 (vcpkg_check_linkage)
  scripts/ports.cmake:79 (include)
```
**Additional context**
###### I think this is just a small cmake problem.
Please help me as soon as possble.
Thank you.

**Comment by ScSofts** [comment]
Now I found that gtkmm has the same trouble.

**Comment by StarGate-One** [comment]
1. Community triplets are not guaranteed to work with all ports
2. gtkmm fails because it has a dependency of gtk, so it will have all the same prerequisite dependencies (and most likely more) as gtk.
3. glib is the failing because it can only be compiled dynamically and you have specified a static compile.
4. Try building with either x86-windows (dynamic), x64-windows (dynamic) otherwise you will need to create your own customized triplet file with the appropriate allowing a dynamic library to compile against static CRT. See issue #6343 on how you can modify a triplet/portfile to allow you to accomplish this.

**Comment by LilyWangL** [comment]
The related issue: #3409

**Comment by LilyWangL** [comment]
@ScSofts Does this issue occur? Is Jack's comments is a workaround for you?

**Comment by ScSofts** [comment]
> @ScSofts Does this issue occur? Is Jack's comments is a workaround for you?

Yell. I'm now trying to modify the cmake script by myself.I often meet with compile problems,and every time I can solve it by that.

**Comment by LilyWangL** [comment]
Thanks for your reply. If your problem solved, please close this issue. You are very welcome to share your solution to solve this problem.

**Comment by PhoebeHui** [comment]
Looks the problems solved, so close this issue.
