### ISSUE TITLE
[vcpkg] Support for building CMake targets with RelWithDebInfo and MinSizeRel configuration

### ISSUE THREAD

**Issue by yhyu13** [microsoft/vcpkg#13284]
****

**Is your feature request related to a problem? Please describe.**
For libraries that support cmake build, vckpg only generate target for Debug and Release but ignores options that are RelWithDebInfo and MinSizeRel which is critical for application such as game engines. I am using vckpg to manage assimp (asset importer) and bullet3 (physics engine) with their debug build being 10~100 times slower than the release build. Game developers such as me would like to have RelWithDebInfo and Release for debugging and releasing in their projects. Debug build is simply not performant enough for debugging, my application could only run about 5fps without any optimization flag.

**Proposed solution**
I would like to see a few required install option flags 
```vcpkg install XXX --RelWithDebInfo --Release``` 
That only builds RelWithDebInfo and Release if possible.
Bins, libs, and includes are then under the folder ./RelWithDebInfo in ./package for the RelWithDebInfo build.

**Describe alternatives you've considered**
I fall back to use CMake to build projects such as assimp and bullet3 for RelWithDebInfo and MinSizeRel.

**Comment by BillyONeal** [comment]
For `RelWithDebInfo`, we currently have a post-build lint on plain release ensuring debug info is generated, at least in "PDB world (windows)". We encourage use of separate DWARF info as well on *nix. In such cases there's no reason to ever use a `RelWithDebInfo` build, because plain release has debugging info. Unfortunately, the Windows `RelWithDebInfo` settings CMake ships with are bad and don't turn on large parts of the optimizer, so you don't actually get the advertised effect.

I'm less sure about MinSizeRel; I think we would encourage defining a triplet which adds appropriate flags for that purpose instead.

The big issue with trying to enable this is that the "installed" schema is "stuff" and "debug/stuff" -- that is, all the release artifacts go into a port's installation directory, and all the debug parts go in a "debug/" subdirectory, so there's nowhere for other configurations to go.

**Comment by cenit** [comment]
> The big issue with trying to enable this is that the "installed" schema is "stuff" and "debug/stuff" -- that is, all the release artifacts go into a port's installation directory, and all the debug parts go in a "debug/" subdirectory, so there's nowhere for other configurations to go.

What’s the problem in having as many config folder as necessary?
MinSizeRel/stuff might work as good as debug/stuff is working... Or am I missing something?!?

**Comment by BillyONeal** [comment]
>What’s the problem in having as many config folder as necessary?

2 major things:

1. Our toolchain won't know how to look in there.
2. We wrap a lot of build systems that are not cmake and therefore have no such "minsizerel" or "relwithdebinfo" concept. The convention we've chosen was chosen to be a reasonable lowest-common-denominator among anything we might want to package.

I'm not saying we would never consider adding something like this, but I am saying we added the triplets system specifically to enable these kinds of customizations.

**Comment by yhyu13** [comment]
@BillyONeal Thanks for answering
