### ISSUE TITLE
Releasing vcpkg as a conda-package

### ISSUE THREAD

**Issue by wolfv** [microsoft/vcpkg#13482]
Dear maintainers, 

I am looking to add vcpkg (the tool) to conda-forge: https://github.com/conda-forge/staged-recipes/pull/12635

I am wondering if someone from the core team of vcpkg wants to help maintain vcpkg over there on conda (occasionally merging new version updates etc).

Just wanted to also say thanks for this great package manager! It could be quite useful to boostrap conda-packages in the future.

**Comment by traversaro** [comment]
Hi @wolfv ! Just a curiosity, in which workflow do you think that having vcpkg available as a conda-forge package can be useful?

**Comment by wolfv** [comment]
My personal "problem" is that I need to bootstrap some static libraries to build `micromamba` and link it statically. I just had the crazy idea that using vcpkg for the libraries that I need for that (libarchive, libcurl, yaml-cpp) would be great!

Also users might want to use vcpkg and install it through conda-forge (and get the dependencies with it, e.g. curl, unzip and tar).

And thirdly, other packages could be bootstrapped through vcpkg... but I am not entirely sure that would make sense. But the binaries build with vcpkg could be distributed through conda...

**Comment by traversaro** [comment]
> And thirdly, other packages could be bootstrapped through vcpkg... but I am not entirely sure that would make sense. But the binaries build with vcpkg could be distributed through conda...

I was a bit confused thinking about the possible conflicts of a binary that builds its own version of its dependencies via vcpkg instead of re-using the one that are in conda-forge, but if you think instead of independent conda channels for statically linked binaries that are not related at all with conda-forge, then indeed it could make sense. The major problem that I see for this scenario is that at the moment vcpkg, by downloading a huge amount of files from servers from all over the world is quite fragile, and it is quite common that older version stop working due a change in MSYS2 repos o similar issue. However, there are indeed some progress on this, so in the future the situation may improve.

**Comment by ras0219-msft** [comment]
This is really cool!

We're happy to answer any questions we can to support this effort, but for now we'd prefer to support your role as a maintainer than to take ownership ourselves. None of our core team is very familiar with Conda, so I feel you'll do a much better job than we could!

Thanks again for making this possible :)

**Comment by wolfv** [comment]
@ras0219-msft sure, no worries at all. The easiest explanation of conda is that it's like `apt` or `dnf` but for all platforms (win, linux and osx).

So now there is a binary package for conda that ships vcpkg to these three platforms, comes with compilers and all the port files from the latest release :) 

The "feedstock" that builds the packages is here: https://github.com/conda-forge/vcpkg-feedstock 

There is a bot that automatically checks whenever you tag a new release of vcpkg and comes around to update the conda package recipe, and makes a PR to the feedstock. So in case you want to check that everything works fine I encourage you to watch the feedstock (if you were a co-maintainer you could also merge changes to the recipe).

Cheers & thanks for vcpkg!
