### ISSUE TITLE
cpp-netlib package relies on header missing from current version of boost in vcpkg

### ISSUE THREAD

**Issue by Apache-HB** [microsoft/vcpkg#13591]
**Describe the bug**
cpp-netlib references boost header `boost/asio/stream_socket_service.hpp' which is no longer a part of boost

**Environment**
- OS: Windows server 2019 build 17763
- Compiler: cl.exe 19.27.29111 for x64

**To Reproduce**
1. ./vcpkg install cpp-netlib:x64-windows
```cmake
add_executable(exe main.cpp)

find_package(cppnetlib 0.13 REQUIRED)
include_directories(${CPPNETLIB_INCLUDE_DIRS})
target_link_libraries(exe ${CPPNETLIB_LIBRARIES})

find_package(Boost REQUIRED)
include_directories(${Boost_INCLUDE_DIRS})
target_link_libraries(exe ${Boost_LIBRARIES})
```

```cpp
// main.cpp
#include <boost/network/protocol/http/server.hpp>

int main() {}
```

2. cmake . -GNinja
3. ninja

**Expected behavior**
Program builds with no compile errors

**Failure logs** 
`fatal error C1083: Cannot open include file: 'boost/asio/stream_socket_service.hpp': No such file or directory`

**Comment by StarGate-One** [comment]
I see the cpp-netlib source package supplies its own `boost sub-directory` with the required `boost\network` libraries and vcpkg does install them in the `[vcpkg-root]\installed\[triplet]\include\boost\boost-network` directory, but I do not know if there is a special cmake configuration so it can find those headers/source files?

**Comment by PhoebeHui** [comment]
@Apache-HB, the file boost/asio/stream_socket_service.hpp seems to be removed, I didn't find it from  https://github.com/boostorg/asio/tree/develop/include/boost, so you can't find them in vcpkg installed directory.

**Comment by StarGate-One** [comment]
@PhoebeHui as I stated above, the cpp-netlib source package downloaded from github has the boost/network headers/sources included - see https://github.com/cpp-netlib/cpp-netlib 
- The boost\asio is where cmake is looking for `boost/asio/stream_socket_service.hpp` but since it is no longer part of or supported by boost.
- When cpp-netlib port was added vcpkg was configured to put the headers/sources in `include\boost\network\` where in a sub-directory is where `protocol\stream_socket_service.hpp` exists.
- The `boost\network` directory does not exist until cpp-netlib is installed.
- The `boost\network` was removed from boost proper, many versions ago, but the maintainer of cpp-netlib has included the old version needed to compile\use the boost\network instead re-writing parts of cpp-netlib.
- @Apache-HB just needs to know how to include them in his cmake project, since they are not part of the current boost, using the cmake find package on boost will not find them.
- Please could we ask @Neumann-A or @JackBoosY for some assistance here as the header/source libraries are there and installed.
- We may need to consider removing the port from vcpkg as the source (https://github.com/glynos/cpp-netlib) where  cpp-netlib was forked from is archived and no longer maintained? 

![image](https://user-images.githubusercontent.com/68293825/93614831-a534b580-f9a0-11ea-8d6a-b9ed7bbef0a6.png)

https://github.com/cpp-netlib/cpp-netlib 
![image](https://user-images.githubusercontent.com/68293825/93614978-d319fa00-f9a0-11ea-83bc-b23f7f9c8d7e.png)

**Comment by PhoebeHui** [comment]
@StarGate-One, thanks for the details!

Same issue with https://github.com/cpp-netlib/cpp-netlib/issues/888, but no response by now, for me, it make sense to remove the port from vcpkg as the source no longer maintained. I will talk this with team.
