### ISSUE TITLE
C++ 2a modules support

### ISSUE THREAD

**Issue by bitnick10** [microsoft/vcpkg#13696]
Hey, guys. Is there a plan to support C++ 2a modules?

**Comment by PhoebeHui** [comment]
@bitnick10, do you mean if the C++2a modules support when building vcpkg or building the port that vcpkg provided?

**Comment by bitnick10** [comment]
@PhoebeHui I would like to use vcpkg with module like vcpkg install abclib:x64-module

**Comment by strega-nil** [comment]
@bitnick10 We don't have any concrete plans at this point, since modules are _such_ a new feature, and it's really not obvious at this point how they'll change tooling. Likely, we'll just follow existing build systems' support for modules.

Also, fwiw, your use of vcpkg with libraries that support modules probably won't be any different. This is mostly about interaction with your build system and compiler; thus, we can't actually do anything to give you modules, besides what the underlying library does. If boost supports modules, you'll be able to access them, but until they do support modules there's nothing we can do to move that along.

Thanks for the issue, though! Are you okay with me closing as "needs underlying library support", or do you have other questions?
