### ISSUE TITLE
Run bootstrap-vcpkg.bat and bootstrap-vcpkg.sh always rebuild vcpkg executable

### ISSUE THREAD

**Issue by ThomsonTan** [microsoft/vcpkg#13738]
****

ootstrap-vcpkg.bat and bootstrap-vcpkg.sh always does rebuild (compilation and link) of vcpkg, even if the it was just built and there is no change in the vcpkg repo.

**Proposed solution**
The vcpkg bootstrap script should track dependency of vcpkg.exe and don't trigger rebuild if it is up-to-date.

**Comment by JackBoosY** [comment]
I think that's no needed.

**Comment by StarGate-One** [comment]
As long as it will allow recompile/link when the compiler/linker version changes and/or any of the system libraries it links with are changed, otherwise there's nothing wrong with how it works now.
You can see when any vcpkg source proper is changed when doing the git pull, you know when you update system libraries or  update the c/c++ compiler/linker and related tools, so you run the bootstrap otherwise you do not... IT 101.

**Comment by kobykahane** [comment]
This bug makes it difficult to integrate vcpkg as a submodule in a project that's using manifest mode.
The dev workflow is: 1. git pull. 2. update submodules (including vcpkg submodule). 3. run project build script.
Ideally the project's build script would only build a new vcpkg.exe if the newer submodule reference actually modified vcpkg code. Subsequently, invocations of vcpkg install would reuse the existing vcpkg binary and usually pick up existing package zips via the binary caching feature.
Instead, right now every invocation of the project's build script would end up redundantly rebuilding vcpkg.exe, unless you add special code to the script like "if vcpkg.exe exists don't bootstrap" - but that's only a partial approximation because after the vcpkg submodule is updated as a result of a pull, you do want to rebuild the tool, so the vcpkg.exe you have matches the vcpkg tree you now have in your submodule. So essentially your project's build script now has to figure out when the submodule has "changed enough" for it to be appropriate to reinvoke bootstrap - basically working around the bootstrap script not allowing for incremental builds.

**Comment by strega-nil** [comment]
@kobykahane we'll discuss this today and come back to you :)

**Comment by PhoebeHui** [comment]
Related to PR https://github.com/microsoft/vcpkg/pull/12502

**Comment by NancyLi1013** [comment]
Duplicated to #9948.
