### ISSUE TITLE
How do I pass dupbuild=warn to Ninja

### ISSUE THREAD

**Issue by crjc** [microsoft/vcpkg#13922]
Hi.

I'm trying to update the ogre-next package to the latest version. However, I'm having troubles building it on MacOS due to ninja complaining about duplicate rules.

```
CMake Error:
  Running

   '.../vcpkg/downloads/tools/ninja-1.10.1-osx/ninja' '-C' '.../vcpkg/buildtrees/ogre-next/x64-osx-mixed-dbg' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:788: multiple rules generate lib/macosx/OgreMainStatic.framework/Versions/2.2.4/Headers/OgreTagPoint.h [-w dupbuild=err]
```

As a temporary measure, I'd like to be able to pass "-w dupbuild=warn" to Ninja, just to allow me test this port, but I'm not sure how to do this. I've tried copying what was done in #10964, however this doesn't seem to to work.

**Comment by crjc** [comment]
Although this solution will pass the parameter for all ports, I was able to modify

https://github.com/microsoft/vcpkg/blob/3714469e0e928b06e20dde2473b90bac9c505368/scripts/cmake/vcpkg_build_cmake.cmake#L43 to

```
set(BUILD_ARGS "-v" "-w" "dupbuild=warn") # verbose output
```

**Comment by cedral** [comment]
This does not work. The event where this is happening is not the build, it is the recompact and the build args aren't passed to it. This problem will have to be fixed upstream by kitware because there is currently no way to pass arguments to the recompact action.
[KitWare Issue 21706](https://gitlab.kitware.com/cmake/cmake/-/issues/21706)
