### ISSUE TITLE
[PDAL] update to 2.2.0

### ISSUE THREAD

**Issue by GeorgeR** [microsoft/vcpkg#13946]
Library name:
PDAL

New version number:
2.2.0 (current on vcpkg is 1.7.2)

It contains multiple features and perf improvements since 1.7.2 (it's a whole release in ahead!). I did try doing this myself by changing the download source and re-implementing the patches but my lack of knowledge of cmake has me stuck this:

```
CMake Error: install(EXPORT "PDALTargets" ...) includes target "pdalcpp" which requires target "pdal_arbiter" that is not in any export set.
CMake Error: install(EXPORT "PDALTargets" ...) includes target "pdalcpp" which requires target "pdal_kazhdan" that is not in any export set.
```

You can see my changes here:
https://github.com/microsoft/vcpkg/compare/master...GeorgeR:master

**Comment by apiszcz** [comment]
Is there an update on this? Assume 2.2.0 is not available yet?

```
pdal                 1.7.1#11         PDAL - Point Data Abstraction Library is a library for manipulating point clou...
pdal-c               1.8-2            C API for the Point Data Abstraction Library (PDAL)
```

**Comment by JonLiu1993** [comment]
Fix by #14055

**Comment by NancyLi1013** [comment]
The version update to 2.3.0 is still blocked by the same problem. 

```
CMake Error: install(EXPORT "PDALTargets" ...) includes target "pdalcpp" which requires target "pdal_arbiter" that is not in any export set.
CMake Error: install(EXPORT "PDALTargets" ...) includes target "pdalcpp" which requires target "pdal_kazhdan" that is not in any export set.
```

I also noticed that @GeorgeR has reported this issue to `padl `https://gitter.im/PDAL/PDAL?at=5fea156fc746c6431cdfcc4f.

```
Andrew Bell @abellgithub Jan 05 20:52
@GeorgeR : I don't understand why you'd get this. Both of those libraries are statically linked to PDAL and are listed as private dependencies, though I have no idea what vcpkg is or what it's doing. This is more of a cmake issue than a PDAL issue.
```
As @Andrew Bell said, this is more of a cmake issue than a PDAL issue.

I also searched the related issue about cmake. https://gitlab.kitware.com/cmake/cmake/-/issues/15415.
There was a workaround that can fix this problem, but not sure if it is reasonable for CMake since this issue still keeps open.

Adding `$<BUILD_INTERFACE:...>` for `pdal_arbiter `and `pdal_kazhdan `in target_link_libraries().

**Comment by dg0yt** [comment]
Work in progress now in #21275.
