### ISSUE TITLE
assimp doesn't build on OSX without irrlicht

### ISSUE THREAD

**Issue by Yaski** [microsoft/vcpkg#14015]
Library name: assimp

Library description: Open-Asset-Importer-Library 

Source repository URL: https://github.com/assimp/assimp

I cannot use assimp on OSX 10.15.7 because build failed.

``` CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:93 (message):
  Target 'osx' not supported by irrlicht!
```

If it is possible could you remove irrlicht dependency from assimp library in vcpkg?

**Comment by neverfelly** [comment]
Yep, assimp build failed on OSX 10.15.7 too.

**Comment by shauser67** [comment]
It seems to be possible to remove the irrlicht loader from assimp under macOS. Having a look into the source files (e.g. into code/Irr/IRRLoader.cpp) there is a define called ASSIMP_BUILD_NO_IRR_IMPORTER.

This define can be added to the assimp portfile:

```
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS -DASSIMP_BUILD_TESTS=OFF
            -DASSIMP_BUILD_ASSIMP_VIEW=OFF
            -DASSIMP_BUILD_ZLIB=OFF
            -DASSIMP_BUILD_SHARED_LIBS=${ASSIMP_BUILD_SHARED_LIBS}
            -DASSIMP_BUILD_ASSIMP_TOOLS=OFF
            -DASSIMP_BUILD_NO_IRR_IMPORTER=ON # <--Added
            -DASSIMP_INSTALL_PDB=OFF
            -DSYSTEM_IRRXML=ON
            -DIGNORE_GIT_HASH=ON
)
```

Unfortunately I had problems to disable the installation of irrlicht (especially to remove the references to irrlicht from buildfixes.patch) since I am not a vcpkg expert, so I couldn't test if the library builds with the new modification.

**Comment by lerppana** [comment]
Having Irrlicht importer is optional feature for assimp (which does not work in macOS). I do not know if it should be forced by vcpkg like this.

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg/issues/15011

**Comment by NancyLi1013** [comment]
Hi all,

`assimp `has supported osx now, please update to the latest vcpkg to rebuild this port.

Thanks.

**Comment by emctague** [comment]
Irrlicht still appears to be blacklisted on ARM / M1 Macs, making assimp still not installable due to this optional component on those platforms, it seems - unless I'm doing something wrong?
