### ISSUE TITLE
problem in opencv port

### ISSUE THREAD

**Issue by RamadanAhmed** [microsoft/vcpkg#14149]
****

**Is your feature request related to a problem? Please describe.**
Hi, 
I have a problem with opencv port that it must install opencv4 even if opencv3 is already installed
if there is away to make it depend on opencv3 or opencv4 or opencv2 so if one is installed in vcpkg it doesn't break installation of other packages depend on opencv

**Proposed solution**
I have solved using overlay ports option and change opencv port to use opencv3 but in my opinion its not an elegant solution or even a solution 

**Describe alternatives you've considered**
**Additional context**

**Comment by cenit** [comment]
Unfortunately that's the way to go.
We have a general opencv port which depends on opencv4, and other ports must depend on opencv and not a specific version.
In this way with overlays you only have to overlay opencv and make it depend on opencv3.
Only the darknet port can be installed with dependency on a specific opencv version using features, others have to rely on the method you have already discovered by yourself. It might not be very elegant, but for now it's the only way we have.
vcpkg is "bleeding edge" by design, it's already a little bit strange that opencv3 and opencv2 were allowed :)

**Comment by RamadanAhmed** [comment]
Thanks @cenit for clarification
