### ISSUE TITLE
change the policy about  lib and source  

### ISSUE THREAD

**Issue by wangniancai** [microsoft/vcpkg#14151]
I found the vcpkg is so big ,how to compress the folder or just install the lib/dll.

**Comment by drescherjm** [comment]
https://github.com/microsoft/vcpkg/issues/2202 may be an option if you don't need to debug the sources of a library

**Comment by NancyLi1013** [comment]
Hi @wangniancai 
Thanks for posting this issue.
Currently, there are no ways to implement what you hope to do.

In order to save your space, you can remove some temporary files, such as removing `packages\`, `buildtrees\`, and `downloads\` folders.

https://github.com/microsoft/vcpkg/blob/master/docs/about/faq.md#how-can-i-remove-temporary-files

**Comment by NancyLi1013** [comment]
Hi @wangniancai 
Please let me know if this is still a problem for you.

**Comment by NancyLi1013** [comment]
Closing this issue for no response here.
