### ISSUE TITLE
Toolchain file vcpkg.cmake cannot support libraries from x64-windows and x64-windows-static at the same time

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#1436]
My `VCPKG_DEFAULT_TRIPLET` environmental variable is x64-windows.

For my project, it is required to use glew statically and the rest like glfw and glm dynamically. Hence I installed glew with x64-windows-static and glfw, glm with x64-windows. 

The problem is when I specify `-DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake` flag when I build my project it is unable to glew.

If I set `VCPKG_DEFAULT_TRIPLET` environmental variable to x64-windows-static then when I build my project it is unable to find glfw.

I had to hack the vcpkg.cmake file in line 70 by manually adding

``````
list(APPEND CMAKE_PREFIX_PATH
        ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}
    )

# manual add
    list(APPEND CMAKE_PREFIX_PATH
        ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}-static
    )

    list(APPEND CMAKE_LIBRARY_PATH
        ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/manual-link
    )
``````

to get my project to build. Is there a way make it work without a hack?

**Comment by ras0219-msft** [comment]
Yes! This is exactly the use case for alternate triplets[1].

This is as simple as creating a file in `triplets\`:
```cmake
# triplets\x64-windows-jasjuang.cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)

if(PORT MATCHES "glew")
  set(VCPKG_LIBRARY_LINKAGE static)
else()
  set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
```
This will also correctly build glew with dynamic _CRT_ linkage.

Then, you simply use
```
> vcpkg install --triplet x64-windows-jasjuang glfw glm glew
```
and `-DVCPKG_TARGET_TRIPLET=x64-windows-jasjuang` (or the environment variable if you'd like to always use this triplet).

[1] https://vcpkg.readthedocs.io/en/latest/users/triplets/

**Comment by jasjuang** [comment]
@ras0219-msft works like magic but there is one small problem. The environment variable doesn't seem to work. I tried setting the environment variable `VCPKG_TARGET_TRIPLET` to `x64-windows-jasjuang` and `VCPKG_DEFAULT_TRIPLET` to `x64-windows-jasjuang` but non of them have any effect. Only adding `-DVCPKG_TARGET_TRIPLET=x64-windows-jasjuang` in the cmake arguments works. Can you let me know what I am missing?

**Comment by ras0219-msft** [comment]
The environment variable `VCPKG_TARGET_TRIPLET` shouldn't affect anything (by design).

I also realized made a mistake in my post above -- we don't allow environment variables like `VCPKG_DEFAULT_TRIPLET` to affect the triplet selection for a project because it _needs_ to switch based on the target architecture and platform. It's conceivable we could do something like have `VCPKG_DEFAULT_X86_WINDOWS_TRIPLET` et al, however that seems incredibly unwieldy.

CMake does have the ability to "seed" the cache with a file on disk[1], so you could simply check in a text file to your sources like:
```cmake
# vcpkgcmakesettings.txt
set(CMAKE_TOOLCHAIN_FILE $ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake CACHE STRING "")
set(VCPKG_TARGET_TRIPLET x64-windows-jasjuang CACHE STRING "")
```
and then configure like
```
set VCPKG_ROOT=C:\vcpkg
mkdir build && cd build && cmake -C ..\vcpkgcmakesettings.txt ..
```

Alternatively, a bat file containing the full configure line would also work. Once a tree has been configured once, you don't need to keep supplying all the `-D` options, so this should only affect the first configure step.

[1] https://cmake.org/cmake/help/v3.8/manual/cmake.1.html

**Comment by jasjuang** [comment]
The initial cache is a great alternative. Thanks!
