### ISSUE TITLE
Add an option to default to a static triple

### ISSUE THREAD

**Issue by bin** [microsoft/vcpkg#14432]
On windows vcpkg defaults to using dynamic linking.  This can be bypassed by supplying a triple, but doing so is an additional flag that must be passed to every build.  It's difficult to get cmake to detect platform information before the call to `project()`, but vcpkg is set up then when used as a toolchain.

Please consider adding an option to prefer static triples in the `vcpkg.json` manifest.

**Comment by vicroms** [comment]
You can change the default triplet by setting a `VCPKG_DEFAULT_TRIPLET` environment variable.

**Comment by bin** [comment]
Is this not able to be added?  I am aware of the environment variable, but it is difficult in cmake to detect the system before the call to `project()`.  Since vcpkg integrates with cmake by running on a call to `project()`, it is no good trying to do this after.  Having a manifest option to simply select the static triplet if possible would be very helpful.

**Comment by jh7370** [comment]
Please could this feature be reconsidered. We don't want to set an environment variable, because most developers will need to be able to generate both 32-bit and 64-bit builds. We don't want to pass in an option at CMake time, as it is easy to forget to do it. As far as I can tell, the `VCPKG_TARGET_TRIPLET` requires setting before the `project` tag, but at that point, 
the recommended way in CMake to distinguish between 32-bit and 64-bit (`CMAKE_SIZEOF_VOID_P`) is not available. It therefore seems to be impossible to determine whether the triplet needs to be set to `x86-windows-static` or `x64-windows-static`. I think we need another variable, e.g. `VCPKG_USE_STATIC_LIBS`, and then the vckpg code can use that to choose whether to append `-static` to the default triplet or not.

**Comment by bugproof** [comment]
I set `VCPKG_DEFAULT_TRIPLET` to `x64-windows-static` but when I install it defaults to x86-windows...

**Comment by vicroms** [comment]
@bugproof can you elaborate further on where did you set the variable? 

`VCPKG_DEFAULT_TRIPLET` should be set as an environment variable.
`VCPKG_TARGET_TRIPLET` can be set as a CMake variable before calling `project()` when using manifest mode.

**Comment by bugproof** [comment]
> @bugproof can you elaborate further on where did you set the variable?
> 
> `VCPKG_DEFAULT_TRIPLET` should be set as an environment variable. `VCPKG_TARGET_TRIPLET` can be set as a CMake variable before calling `project()` when using manifest mode.

I set it as a system variable in windows 11 21h1
