### ISSUE TITLE
msys2   libiconv-1.16-1-x86_64.pkg.tar.xz  Failed to download file.

### ISSUE THREAD

**Issue by ducdY** [microsoft/vcpkg#14441]

**Comment by StarGate-One** [comment]
@ducdY Your vcpkg instance is out of date - the issue was fix in PR https://github.com/microsoft/vcpkg/pull/14220
1. `cd [vcpkg-root]`
2. `git pull` gets updates from https://github.com/microsoft/vcpkg
3. Recompile/link vcpkg binary:
  -- For windows `.\bootstrap-vcpkg.bat` 
  -- For linux `./bootstrap-vcpkg.sh`

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
