### ISSUE TITLE
When should I upgrade?

### ISSUE THREAD

**Issue by nil-is-lin** [microsoft/vcpkg#14501]
vcpkg is now very actively maintained, which is very exciting. But this causes me to always get updates every time I run git pull & vcpkg upgrade. There are several libraries, such as vtk, opencascade, mlpack, qt5, that I have rebuild several times, can there be a hint to tell the user which updates are important and which can be left alone for now? Because it does take a lot of time for my computer configuration.

**Comment by PhoebeHui** [comment]
@nil-is-lin, I think you can try following steps to avoid to rebuild all updated packages every time.

1. Git pull the latest source, and rebuild vcpkg if there has new change from vcpkg, this could make sure you get the latest feature every time.
2. Avoid to use 'vcpkg upgrade', since it will rebuild all updated ports, however, you may not need the latest revision for all these ports, you can only rebuild the port you want by 'vcpkg install  xxx --recurse'.
2. Use the release revision from https://github.com/microsoft/vcpkg/tags, and rebuild the package when get new release.

**Comment by nil-is-lin** [comment]
Thank you very much for your advice. maybe it's a compromise to check the release tag and update it in my free time.
