### ISSUE TITLE
set(VCPKG_PLATFORM_TOOLSET v140) fails despite having both VS2015 and VS2017

### ISSUE THREAD

**Issue by paercebal** [Microsoft/vcpkg#1463]
I'm trying to compile zlib for VS2015, and it fails because the `findVisualStudioInstallationInstances.ps1` script finds only VS2017.

## Details:

- I have both VS2015 and VS2017 installed (and able to compile C++ projects)
- My vcpkg version is: `Vcpkg package management program version 0.0.81-6950aeb6378adb47ff467a79d58ae8d4b5abe9cb`
- I created a triplet `rbr-x64-vs2015` with the following content:
`set(VCPKG_TARGET_ARCHITECTURE x64)`
`set(VCPKG_CRT_LINKAGE dynamic)`
`set(VCPKG_LIBRARY_LINKAGE dynamic)`
`set(VCPKG_PLATFORM_TOOLSET v140) `
- The command line is: `vcpkg install zlib:rbr-x64-vs2015`
- The failure message (from the `vcpkg\buildtrees\zlib\config-rbr-x64-vs2015-rel-err.log` file)is: `CMake Error: Could not create named generator -DCMAKE_BUILD_TYPE=Release`
- This error seems normal as the extract from the CMake error is: 
` [...];-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-G;-DCMAKE_BUILD_TYPE=Release;[...]`

## Speculations:

From there, I've tried to understand what was happening, so, after looking around in the issues, I tried this:

`D:\_dev\_pkg\vcpkg>vcpkg env --debug --triplet rbr-x64-vs2015`
`[DEBUG] _wpopen("where.exe cmake 2>&1")`
`[DEBUG] _wpopen() returned 1`
`[DEBUG] _wpopen(""D:\_dev\_pkg\vcpkg\downloads\cmake-3.8.0-win32-x86\bin\cmake.exe" --version 2>&1")`
`[DEBUG] _wpopen() returned 0`
`[DEBUG] _wpopen(""D:\_dev\_pkg\vcpkg\downloads\cmake-3.8.0-win32-x86\bin\cmake.exe" "-DCMAKE_TRIPLET_FILE=D:/_dev/_pkg/vcpkg/triplets/rbr-x64-vs2015.cmake" -P "D:/_dev/_pkg/vcpkg/scripts/get_triplet_environment.cmake" 2>&1")`
`[DEBUG] _wpopen() returned 0`
`[DEBUG] _wpopen("powershell -NoProfile -ExecutionPolicy Bypass -Command "& {& 'D:\_dev\_pkg\vcpkg\scripts\findVisualStudioInstallationInstances.ps1' }" 2>&1")`
`[DEBUG] _wpopen() returned 0`
`Could not find toolset 'v140'`
`[DEBUG] ..\src\VcpkgPaths.cpp(367)`

The `findVisualStudioInstallationInstances.ps1` script seems to fail.

_Note: Changing the toolset inside the triplet to v141 works. So the VCPKG_PLATFORM_TOOLSET macro works without error._

Looking at the `findVisualStudioInstallationInstances.ps1` script's source, I see it uses the program `Microsoft.VisualStudio.Setup.Configuration.Console.exe` to detect the Visual Studio installations.

Launching it manually with the same parameters as the script (`-nologo -value InstallationPath`), it returns only `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional`.

But I also have: `C:\Program Files (x86)\Microsoft Visual Studio 14.0` installed.

My conclusion is the `Microsoft.VisualStudio.Setup.Configuration.Console.exe` doesn't return all the installations of Visual Studio (perhaps it was never expected to...), which means no `v140` toolset is found.

_Note: I remember something like installing the v140 toolset with Visual Studio 2017, but I didn't do it, as I already have vs2015 separately installed. I'm wondering if this isn't tied to my problem. (UPDATE: I verified with my VS2017 installer, and it says VC++ 2015.3 v140 toolset is installed)_

**Comment by albertziegenhagel** [comment]
I don't think that the `findVisualStudioInstallationInstances.ps1` script is the problem here, since it is used to find VS2017 only. For VS2015 the environment varibale `VS140COMNTOOLS` is used.

You can have a look at the function `find_toolset_instances` at https://github.com/Microsoft/vcpkg/blob/4c33195759bfc2b3bde8628a6617f46040721330/toolsrc/src/VcpkgPaths.cpp#L272 to see how the detection works.

To me it seems as if the function is able to detect at least one VS toolset which I assume to be VS2017s v141 toolset (else you should see a different error). For some reason the v140 toolset from VS2015 is missing.

You could check manually if any of the files

- `%VS140COMNTOOLS%\VC\vcvarsall.bat`
- `%VS140COMNTOOLS%\VC\bin\dumpbin.exe`

is missing on your system.

 @ras0219-msft maybe it makes sense to show the detailed errors from
https://github.com/Microsoft/vcpkg/blob/4c33195759bfc2b3bde8628a6617f46040721330/toolsrc/src/VcpkgPaths.cpp#L340
at
https://github.com/Microsoft/vcpkg/blob/4c33195759bfc2b3bde8628a6617f46040721330/toolsrc/src/VcpkgPaths.cpp#L366
as well, or to keep the implementation more simple, just print the examined paths immediately while examining them when --debug is passed?

**Comment by paercebal** [comment]
After verification, debugging, and fooling around, Visual Studio 2015 is installed on my system, and is found by VCPKG. The problem comes from elsewhere (see details).

I can reproduce the issue simply by copy-pasting a standard triplet file, naming the copy with a specific name, and using it for zlib.

The exact steps to reproduce, when, starting from scratch, are:

- `git clone https://github.com/Microsoft/vcpkg.git`
- go into the vcpkg directory
- `.\bootstrap-vcpkg.bat`
- in the triplets directory, make two copies of `x64-windows.cmake`, naming them `x64-rbr.cmake` and `rbr-x64.cmake`
- install zstd for the three triplets above (i.e. `vcpkg install zstd:x64-windows`, then `vcpkg install zstd:x64-rbr`, then `vcpkg>vcpkg install zstd:rbr-x64`). everything succeeds.
- install zlib for the three triplets above (i.e. `vcpkg install zlib:x64-windows`, then `vcpkg install zlib:x64-rbr`, then `vcpkg install zlib:rbr-x64`). the first 2 succeed, but the last fails.

The error messages don't really help here (as we both went exploring in the wrong direction).

I've tried to understand why the name seems so important. While some docs advises us to use a standard format for triplet names (https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md), but nothing implies it MUST follow a specific format.

I also tried to find where in the CMake files this name was "parsed", but I failed, too (I am not really CMake-fluent).

So, my question: Am I the only one having this issue when following the steps above?

## Details

It is the CMake script launch that fails at:

https://github.com/Microsoft/vcpkg/blob/master/toolsrc/src/vcpkg_Build.cpp#L154

`        int return_code = System::cmd_execute_clean(command);`

The command being:

`L"\"D:\\_dev\\_pkg\\vcpkg\\downloads\\cmake-3.8.0-win32-x86\\bin\\cmake.exe\" \"-DCMD=BUILD\" \"-DPORT=zlib\" \"-DCURRENT_PORT_DIR=D:/_dev/_pkg/vcpkg/ports/zlib/.\" \"-DTARGET_TRIPLET=rbr-x64-vs2015\" \"-DVCPKG_PLATFORM_TOOLSET=v141\" \"-DVCPKG_USE_HEAD_VERSION=0\" \"-D_VCPKG_NO_DOWNLOADS=0\" \"-DGIT=C:/Program Files/Git/cmd/git.exe\" -P \"D:/_dev/_pkg/vcpkg/scripts/ports.cmake\""`

(This string is the result of the original debug, before I moved on to play with triplet names, so please ignore the fact the triplet is still `rbr-x64-vs2015` or the toolset is `v141`)

**Comment by paercebal** [comment]
I'm dumb.

The problem is clearly this:

scripts\ports.cmake (https://github.com/Microsoft/vcpkg/blob/master/scripts/ports.cmake#L35):

`string(REGEX REPLACE "([^-]*)-([^-]*)" "\\1" TRIPLET_SYSTEM_ARCH ${TARGET_TRIPLET})`

If we already  have:

`set(VCPKG_TARGET_ARCHITECTURE x64)`

in our triplet, then I guess (again, I'm not CMake fluent) we could replace the regular expression above with:

`set(TRIPLET_SYSTEM_ARCH $(VCPKG_TARGET_ARCHITECTURE))`

... and solve all problems, and remove the implicit specifications from the triplet name.

(The same should be done in the C++ code, where we verify the triplet name has a minus character inside)
:-/

**Comment by paercebal** [comment]
Working on the solution above.

I've launched the install of two identical versions of VCPKG, one vanilla, and one with the fix above. I'll let it go through the night, and if tomorrow the diff is coherent (i.e. the only difference is the fixed version accepting the "different" triplet), I'll send a patch.

If there something else I should do to make sure this fix breaks nothing, I'm interested.

Thanks,

**Comment by paercebal** [comment]
BTW: Should I rename this issue, into something like: "Using triplet not following implicit format (e.g. abc-x64) fails on zlib and some other libraries"?

**Comment by ras0219-msft** [comment]
The one issue that will remain is that our qualified dependencies still unfortunately depend on the triplet name [1]. This is a bit tricky to fix, since we need to "run" the triplet file in order to discover the architecture settings. We already run it per-port, but there's a chicken-and-egg issue between dependency analysis to figure out what ports we need and running the files to figure out the dependencies of the ports.

The right answer here (I think) is to run the triplet file once at the very beginning without any `PORT` setting and then asserting that the resulting architecture doesn't change for each of the built ports.

[1] https://vcpkg.readthedocs.io/en/latest/maintainers/control-files/ At the bottom, under `Build-Depends`.

**Comment by paercebal** [comment]
I've tested the fix on *all* the packages (but ogre, which fails on my machine because the install uses too much memory), and it revealed quite a few packages broken by this bug.

For some reason, zlib was not one of them in my tests.

As my disk is almost full, I will remove the packages and try again with zlib. I expect: without the fix, it fails, with the fix, it succeeds.
