### ISSUE TITLE
[fontconfig:x86-windows] build failure on Windows 7

### ISSUE THREAD

**Issue by westshellX** [microsoft/vcpkg#14830]
**Host Environment**
- OS: [Windows 10, Windows7]
- Compiler: VS2017

**To Reproduce**
`./vcpkg install fontconfig

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:106 (message):
Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:527 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:19 (vcpkg_configure_make)
  scripts/ports.cmake:136 (include)
**Additional context**

**Comment by JackBoosY** [comment]
Confirmed:
```
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
/usr/bin/autopoint: line 487: tar: command not found
autopoint: *** infrastructure files for version 0.19.8 not found; this is autopoint from GNU gettext-tools 0.19.8.1
autopoint: *** Stop.
autoreconf: autopoint failed with exit status: 1
```

**Comment by JackBoosY** [comment]
@smalltree Are you using Windows 7 too?

**Comment by smalltree** [comment]
> @smalltree Are you using Windows 7 too?

yes，OsgEarth recommend to use vcpkg，but in practice it's not easy to use.

**Comment by Wedge009** [comment]
This seems to be the same as #15508 (which I've also confirmed), albeit for x64 instead of x86.

In contrast to @smalltree I actually find vcpkg much easier than trying to compile GTK components on Windows manually. It's worked well for me in the past so I'm surprised to find it's broken currently (after more than a year since I last used it).
