### ISSUE TITLE
On Windows how to solve the problem that different C++ standards are not always compatible?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#14983]

**Comment by BillyONeal** [comment]
The MSVC++ compiler lets different C++ standard modes be link compatible. Can you be more specific about the problem you're trying to solve?

**Comment by vicroms** [comment]
Probably related to #14965

**Comment by playgithub** [comment]
> The MSVC++ compiler lets different C++ standard modes be link compatible. Can you be more specific about the problem you're trying to solve?

C++17 appliation can't link  lib `poppler` that is build with C++14.
After build `poppler` with C++17, it works.

#14982

**Comment by BillyONeal** [comment]
I see; in that case, generally speaking, you can't. You are locked into using the same C++ version as that library because they have dependence on the C++ version. As I understand it vcpkg generally tries to target C++17, so if there is a port producing bits that don't work when used with `/std:c++17` that's a bug in the port.

**Comment by playgithub** [comment]
That's ok, thanks.
