### ISSUE TITLE
port request: vtk with openvr

### ISSUE THREAD

**Issue by xoviat** [Microsoft/vcpkg#1498]
vtk is already a package but openvr is not enabled.

**Comment by jasjuang** [comment]
I actually looked into porting openvr but the problem is it doesn't even have proper CMakeLists. It doesn't install headers, and it doesn't install config.cmake files. Were you able to build VTK from source with openvr installed? If you are able to please let me know how you did it then I might be able to make a port.

**Comment by xoviat** [comment]
AFAIK the following variables need to be set (using the HEAD vtk):

```
set(OPENVR_ROOT_DIR "C:/Users//OpenVR")
set(OPENVR_HEADERS_ROOT_DIR, "C:/Users//OpenVR/headers")
set(OPENVR_INCLUDE_DIR, "C:/Users//OpenVR/headers")
set(OPENVR_LIBRARY, "C:/Users//OpenVR/lib/win64/openvr_api.lib")
```

**Comment by xoviat** [comment]
Actually part of the reason for this request is that VTK+OpenVR has proved difficult for me to set up.

**Comment by xoviat** [comment]
Yeah, the key is to add these lines to CMakelists.txt from HEAD:

```
set(CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/CMake)

find_package(SDL2 REQUIRED)
find_package(OpenVR REQUIRED)
```

Then you need to enable the module.

**Comment by xoviat** [comment]
This is done.
