### ISSUE TITLE
Make Linux dynamic linkage a first class citizen

### ISSUE THREAD

**Issue by dweckmann** [microsoft/vcpkg#15006]
****

**Is your feature request related to a problem? Please describe.**
Currently, and on the contrary to Windows platform, the official triplet on Linux is the one with static linkage. There are many problems with that:
1. The CI only test static linkage, which means the quality is not always paired with static build.
2. Static linking make linking big libraries like Qt very slow. Really, when debugging, this is painful
3. License problem: LGPL forbid static linking. Using static linking means your code will be GPL licensed. This is not acceptable for many of us.

**Proposed solution**
- Add an official dynamic linkage triplet for linux, make them default, like on windows 
- Add a CI step to test it

**Comment by JackBoosY** [comment]
Hmm... @BillyONeal what do you think about?

**Comment by BillyONeal** [comment]
We choose static linking on the POSIX-ish platforms because dynamic linking generally forces you to use the system-provided libraries (e.g. those acquired through apt). It doesn't matter if you want to use the vcpkg version of boost in general, for example, because all the operating system's default load library paths are going to look in places owned by apt or dnf or similar.

Windows is different because on Windows your app can use version 1 of a shared library, and someone else can use version 2 of that shared library, and as long as those versions have different DLL names, a program can use both versions, since all symbols from that library are namespaced into the DLL in question. In contrast, in POSIX world, all the names go into the shared process symbol table, so trying to load multiple versions of a library into the same process will usually result in memory corruption.

(This is part of the problem domain and affects all non-system-wide package management solutions, so our ability to influence this is limited)

**Comment by dweckmann** [comment]
Yes, you are indeed right.

However, checking, at least, that the package build correctly on the CI would still increase the quality of the dynamic linkage packages. I guess the package must build out-of-the-box, in all case, even if static linking is the default (which I can live with it).

In the posix world, you have some mean to control where the dynamic loader finds their libraries (most notably by setting LD_LIBRARY_PATH to VCPKG 'installed' lib path). Another option, but this is harder, would be to use `rpath` at linking stage to ensure to load the dependencies of a library with a relative path from themself, so not the system one...

Agree, this is not easy, but other package management (Conan for stance) are able to (or they claim to) somewhat ensure that.

**Comment by BillyONeal** [comment]
>Agree, this is not easy, but other package management (Conan for stance)

While it's true that other package managers have decided to make dynamic linking on the POSIX platforms a more first class citizen, we believe that leads customer confusion; hence our strong recommendation of static linking on those platforms, and that triplet's community status.

We do have x64-linux-dynamic, and we do accept PRs that improve the experience for that triplet. However, even for folks who only use vcpkg locally, we believe it is too easy to accidentally get runtime libraries from the system at runtime resulting in "impossible" memory corruption, and we don't want to handle that support burden right now. For anything targeting wider distribution, those issues are much worse, since it's it might work due to `rpath` or similar on the dev box and then break when copied to an end user.

Despite the above, if some work is contributed to improve the experience for dynamic on those platforms, such as copying the right `.so`s in integrated build systems on the POSIX-ish platforms, that might be a reason to take that triplet out of community status. I think changing the default will remain off the table.

**Comment by dweckmann** [comment]
Yes, we already know the implication of this linkage type. However, it's not a matter of taste for us. The licence and the GPL contamination is a no go, as, even if most of our work are free and open (take a look at https://github.com/IRCAD-IHU/sight), some external part, are proprietary (just because it uses confidencial hardware, software, stuff that waits for a publication in a medical journal, ..) and we have no way to change that. Using for example static Qt (or any LGPL libraries) would mean we cannot go further than private and confidential prototype. No way to use our software in a OP room.

If your strong recommendations stays on static linkage, that's fair and understandable. We only beg for a CI support, to be sure that things compiles and that a submission doesn't break everything. We are in the process to evaluate VCPKG as a replacement for conan, and that is a real concern for us.

Anyway, thanks for listening :)

**Comment by BillyONeal** [comment]
>We do have x64-linux-dynamic,

Correction, we don't have that 😳

**Comment by Osyotr** [comment]
I've been able to build some ports with this overlay triplet:
```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

# set rpath for libraries
if(PORT MATCHES "fribidi|harfbuzz|pkgconf")
    # Meson, nuff said
    set(pretty_ORIGIN_name "\$ORIGIN")
    set(VCPKG_LINKER_FLAGS "-Wl,-rpath,${pretty_ORIGIN_name}:${pretty_ORIGIN_name}/../lib")
elseif(PORT MATCHES "python2")
    # setting rpath here breaks build and I have no idea how to fix it.
    # But since python2 has no dependencies, not setting rpath is ok
else()
    set(VCPKG_LINKER_FLAGS "-Wl,-rpath,'$ORIGIN':'$ORIGIN/../lib'")
endif()
```

**Comment by abique** [comment]
@BillyONeal I think there are new options today with `dlmopen` and `RTLD_DEEPBIND`. But I'm not a shared object expert.
