### ISSUE TITLE
[poco:netssl]-inner conflict

### ISSUE THREAD

**Issue by yuntong613** [microsoft/vcpkg#15032]
Environment: WIN10,VS2017
cmd>vcpkg install poco[netssl,mariadb]

Poco source code provide two ways to build ssl component，one by openssl，the other by WINDOWS API.

<NetSSL_OpenSSL\include\Poco\Net>,<NetSSL_Win\include\Poco\Net>,both have the files with same name,and then cmake install will miss OpenSSL related header files.

I suggest turning off the option of ENABLE_NETSSL_WIN，in poco\portfile.cmake line 30.

**Comment by JonLiu1993** [comment]
@JackBoosY ,what do you think about?

**Comment by JackBoosY** [comment]
Will look into it later.

**Comment by JackBoosY** [comment]
There are several options about ssl:
- ENABLE_NETSSL_WIN: `option(ENABLE_NETSSL_WIN "Enable NetSSL Windows" OFF)`
- FORCE_OPENSSL: `option(FORCE_OPENSSL "Force usage of OpenSSL even under windows" OFF)`
- ENABLE_NETSSL(if openssl is found): `option(ENABLE_NETSSL "Enable NetSSL" ON)`

**Comment by MCJack123** [comment]
Just to add my two cents: I've just run into this issue, where the NetSSL_Win code is now conflicting with code after an upgrade, since it changes the signature of `Poco::Net::Context::Context`. Maybe there could be an option to use either NetSSL_Win or NetSSL_OpenSSL as a feature definition? (e.g. `poco[winssl]` for NetSSL_Win, and `poco[openssl]` for OpenSSL) This issue is troublesome for me as it now breaks my HTTPS downloading code until the OpenSSL library can be restored.

**Comment by yuntong613** [comment]
@MCJack123 There is a temporary solution。
Comment the portfile.cmake line 30. and wait for vcpkg git update then merge into your branch.

`vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS`
    `pdf         ENABLE_PDF`
    `netssl      ENABLE_NETSSL`
`#    netssl      ENABLE_NETSSL_WIN`
    `netssl      ENABLE_CRYPTO`
    `sqlite3     ENABLE_DATA_SQLITE`
    `postgresql  ENABLE_DATA_POSTGRESQL`
`)`

**Comment by JonLiu1993** [comment]
Solved by #16526

**Comment by JonLiu1993** [comment]
@yuntong613 ,pr #16526 have merged ,please git pull vcpkg and try again
