### ISSUE TITLE
[libsamplerate] CMake targets are missing

### ISSUE THREAD

**Issue by gvnnz** [microsoft/vcpkg#15064]
Unlike its sibling [libsndfile](https://github.com/microsoft/vcpkg/tree/master/ports/libsndfile), libsamplerate doesn't provide CMake targets, so commands like `find_package` and `target_link_libraries` can't be used.  It would be great to add such feature to libsamplerate in order to ease the inclusion in a CMake-based project.

**Comment by NancyLi1013** [comment]
Hi @gvnnz 

Thanks for posting this issue.

Generally, we prefer to use CMake targets that provided by upstream instead of vcpkg.

I noticed that `libsamplerate` has implemented this feature in latest changes by upstream. 
https://github.com/libsndfile/libsamplerate/blob/master/src/CMakeLists.txt

So we might need to update `libsamplerate` to support CMake targets.

> libsamplerate

**Comment by Be-ing** [comment]
I have a commit which uses libsamplerate master branch in https://github.com/mixxxdj/vcpkg/pull/4
I have also opened an [upstream PR](https://github.com/libsndfile/libsamplerate/pull/137) to make vcpkg support easier.

**Comment by Be-ing** [comment]
Upstream accepted my PR and I updated the portfile.cmake in https://github.com/mixxxdj/vcpkg/pull/8 . Once upstream finally makes a new release, it will be easy to simply update the commit hash.

**Comment by Be-ing** [comment]
Fixed by #15797. This issue can be closed now.

**Comment by NancyLi1013** [comment]
Thanks for your help @Be-ing.
