### ISSUE TITLE
[ogre]: FindPackage(OGRE...) set release OGRE_PLUGIN_DIR and OGRE_CONFIG_DIR for Debug

### ISSUE THREAD

**Issue by dweckmann** [microsoft/vcpkg#15120]
**Describe the bug**
In a foreign project, using Ogre package with CMake and display the `OGRE_PLUGIN_DIR`  like:

```cmake
find_package(OGRE REQUIRED COMPONENTS Overlay)
target_link_libraries(MyTarget PUBLIC OgreOverlay)

message(OGRE_PLUGIN_DIR='${OGRE_PLUGIN_DIR}')
```

displays the same string, in debug and in release: `vcpkg/installed/x64-windows/bin`. The debug plugins are in `vcpkg/installed/x64-windows/debug/bin` 

**Environment**
- OS: Windows 10
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29335 for x64

**To Reproduce**
1. ./vcpkg install ogre
2. In a CMake project in Debug (CMAKE_BUILD_TYPE=Debug):

```cmake
find_package(OGRE REQUIRED COMPONENTS Overlay)
target_link_libraries(MyTarget PUBLIC OgreOverlay)

message(OGRE_PLUGIN_DIR='${OGRE_PLUGIN_DIR}')
```

**Expected behavior**
OGRE_PLUGIN_DIR and OGRE_CONFIG_DIR  should match the build type, as the debug plugin are not in the same directory as release one.

**Additional context**
Maybe other variable should be checked in the generated `OGREConfig.cmake`. The problem may be somewhere in `OGREConfig.cmake.in`. I begin to think it is really ambitious to mix debug and release build, sharing cmake files, includes, config..

**Comment by JackBoosY** [comment]
In _OGREConfig.cmake_:
```cmake
set(OGRE_STATIC OFF)
set(OGRE_MEDIA_DIR "${PACKAGE_PREFIX_DIR}/Media")
set(OGRE_PLUGIN_DIR "${PACKAGE_PREFIX_DIR}/bin")
set(OGRE_CONFIG_DIR "${PACKAGE_PREFIX_DIR}/bin") 

set(OGRE_PREFIX_DIR "${PACKAGE_PREFIX_DIR}")
get_filename_component(OGRE_LIBRARY_DIRS "${OGRE_PREFIX_DIR}/lib" ABSOLUTE)
get_filename_component(OGRE_INCLUDE_DIRS "${OGRE_PREFIX_DIR}/include/OGRE" ABSOLUTE)
set(OGRE_LIBRARIES)
```

This is because ogre's cmake configuration files are installed together in vcpkg.
If according to the upstream design, the configuration of debug and release are separated, then `OGRE_*_DIR` will be pointed to the corresponding folder. But in vcpkg, we merged _release/share/ogre/OGREConfig.cmake_ and _debug/share/ogre/OGREConfig.cmake_, which caused this issue.

I think we can only choose where to point to by adding a judgment `CMAKE_BUILD_TYPE` where these paths are set in _OGREConfig.cmake_.

**Comment by jimwang118** [comment]
This issue was fixed in PR [32853](https://github.com/microsoft/vcpkg/pull/32853).
