### ISSUE TITLE
Elevate x64-windows-static-md to be an official triplet 

### ISSUE THREAD

**Issue by ankurverma85** [microsoft/vcpkg#15122]
While i have nothing against the triplet x64-windows-static , it does have a pitfall of assuming that developers want the CRT to be statically linked in the binary as well which is rarely the case.

Most developers or projects while building on Windows face the issues around DLLs with regards to getting them to load from the right locations while developing or package them along with their binaries, given that DLLs dont really contain an rpath.
To circumvent such frustrations a lot of developers choose to use static-md so that all libraries are statically linked.
There may be a lot of other reasons to choose static linking too but in neither of the cases linking against a static CRT is a good idea.

Most developer if given the option would probably choose static-md rather than static

Coupled this with the fact that i've seen static-md break far too often. 
I would propose elevating x64-windows-static-md to be an official triplet. 
I would even go so far as to even consider replacing static with static-md but thats if we're given a choice between static and static-md.

The alternative (static-without-md) is simply a bloat for the binary. In most cases its not something the developer really intends anyway.

**Comment by JackBoosY** [comment]
@BillyONeal what do you think?

**Comment by BillyONeal** [comment]
There are several reasons we don't recommend static-md:

* Most projects that need static also want single binary deployment, and -md breaks that tenet.
* Static-md creates inconsistent views of the universe when your DLL is mixed with other DLLs in a program that also use one of the libraries in question, since the CRT's view is that there is only one copy of various globals like `locale::locale()`, the new handlers, atexit handlers, etc. but each of the libraries' view is that each DLL would have their own globals. We expect this is likely to lead to subtle bugs. This inconsistent view is one of the reasons many libraries (such as Boost.Test) forbid such a configuration when they are made aware that it exists.

>Most developers or projects while building on Windows face the issues around DLLs with regards to getting them to load from the right locations while developing or package them along with their binaries, given that DLLs dont really contain an rpath.

Why is the CRT any different than one of the libraries installed herein?

>Most developer if given the option would probably choose static-md rather than static

If you have actual data behind this statement it might change things. As it stands this issue doesn't really change anything about the decisions made when that triplet was made a community triplet in the first place.

**Comment by ankurverma85** [comment]
> * Most projects that need static also want single binary deployment, and -md breaks that tenet.

static-md i believe says you can have your single binary deployment but the CRT DLLs are going to be used from the OS installed locations which is fine for most cases. You can rely on the OS to provide the CRT (and keep it updated)

> * Static-md creates inconsistent views of the universe when your DLL is mixed with other DLLs in a program that also use one of the libraries in question, since the CRT's view is that there is only one copy of various globals like `locale::locale()`, the new handlers, atexit handlers, etc. but each of the libraries' view is that each DLL would have their own globals. We expect this is likely to lead to subtle bugs. This inconsistent view is one of the reasons many libraries (such as Boost.Test) forbid such a configuration 
when they are made aware that it exists.

I did not quite understand the intricasies here but if the binary is deployed as a DLL the inconsistent view already already . There's multiple DLLs that are loaded in the program and each has their own version of the CRT. There's a thousand different windows OS dlls that themselves are compiled with different CRTs.
So I don't quite understand how having a static-md makes the situation worse. 
If the different CRT dll dont play along well in a single program I'm inclined to call it a CRT bug. 
Agreed, it could be pretty subtle and hard to identify if that were indeed the case but so would any OS or CRT bug.
Moreover I believe there's a higher risk of static-crt not playing well with dynamic-crt from some other DLL that you have no control over, than dynamic-crt's not playing well with each other 

> Why is the CRT any different than one of the libraries installed herein?

VCPKG doesnt quite "install" DLLs that it compiles, wheres CRTs are usually installed in System32. 
vcpkg simply puts the DLLs in its own installed folder and that makes VCPKG dlls hard to locate for the program or tag along with the binary, but not the CRT.
Single binary deployments are usually preferred for the exact same reason that you dont want to assume DLLs are installed on a system. However, most developers will be ok assuming that the CRT is installed on the system . 
IMO the only reason where you want want to statically link with the CRT is if you're linking with a debug CRT and trying to run on a remote machine that may not contain the debug-CRT or perhaps run the binary on an older version of windows while building with the newest CRT. 

> If you have actual data behind this statement it might change things. As it stands this issue doesn't really change anything about the decisions made when that triplet was made a community triplet in the first place.

No data. But given you've configured x64-linux the same way, I'm inclined to assume that as some proof that people don't really care if the CRT is static or dynamic. 

The ask here really is to consider x64-windows-static-md as a respectable citizen and have Pull-requests CI Pipelines in place so the triplets dont break from time to time and avoid regressions.
If there are reasons to keep the default as static-mt then so be it but i would definitely like to see static-md elevated from communitiy triplet to an official triplet.

If the argument is that static-md is not a valid use case or less preferable than static-mt, I would love to be pointed to some official MSFT guidance on that to adjust my world-view


I have'nt

**Comment by BillyONeal** [comment]
>static-md i believe says you can have your single binary deployment but the CRT DLLs are going to be used from the OS installed locations which is fine for most cases. 

The OS does *not* install a CRT. You are on the hook for that. It is a common dependency, so it's likely somebody installed some CRT before you arrived, but you can't generally rely on that.

>There's multiple DLLs that are loaded in the program and each has their own version of the CRT. 

If the CRT is a DLL, that is not true, because all such global state lives in the CRT's DLL.

>Moreover I believe there's a higher risk of static-crt not playing well with dynamic-crt from some other DLL that you have no control over, than dynamic-crt's not playing well with each other

The design intent for the static triplets are that you static link everything, so there are no other DLLs bring other dynamic CRTs to the party.

**Comment by aggieNick02** [comment]
I use <arch>-windows-static-md for all of my projects. Why? If you are using any other third-party libraries (not everything is in vcpkg), they typically are dynamically linked to the runtime so that they play nice with other code. You can't have two versions of the runtime loaded (both static or one of each), so dynamic runtime linking is often the only sane choice.

I ended up on the -static-md triplets after trying to use -static and getting loads of errors about multiple runtimes. I'm using boost, protobuf, grpc, and several other libraries, and have not had any issues because of md afaik.

**Comment by aggieNick02** [comment]
> * Static-md creates inconsistent views of the universe when your DLL is mixed with other DLLs in a program that also use one of the libraries in question, since the CRT's view is that there is only one copy of various globals like `locale::locale()`, the new handlers, atexit handlers, etc. but each of the libraries' view is that each DLL would have their own globals. We expect this is likely to lead to subtle bugs. This inconsistent view is one of the reasons many libraries (such as Boost.Test) forbid such a configuration when they are made aware that it exists.

I'll readily admit I don't know about these possible issues. Can you elaborate a bit and/or point to the Boost.Test forbid so I can learn more?

> Why is the CRT any different than one of the libraries installed herein?

Because you can't mix different CRT versions in the same app. If you've got a 3rd party dll that links to a different CRT statically, or links to the CRT dynamically, you can't use it with <arch>-windows-static .

**Comment by ankurverma85** [comment]
The CRT discussion is great and insightful but not to get sidetracked from the ask here: (and I do indeed would love to continue that discussion) 
The ask here, I believe, is a lot less controversial

__ Can we have elevate x64-windows-static-md to be an official triplet __

To be specific as a first step all I'm asking here is status quo wrt -static-md:
  - The triplet moved from community folder to the official folder
  - Have Pull Request CI Pipeline monitoring so we do not have regressions for ports that are indeed working.

And then incrementally and over time
  - Identify and fix bugs in existing port-files where contributors assume VCPKG_LIBRARY_LINKAGE == static implies VCPKG_CRT_LINKAGE == static

As a side-effect, in the process, we also extend coverage and improve support for __uwp-windows__  where in some cases static-md fixes are in-fact all that stands between a library being supported and not-supported. 
(Again, sorry if thats a mis-representation or in-accurate in the general case, and if so please ignore)

As much as I'd love to debate the merits of -static and -static-md I do think they're both valid scenarios and the only ask here is to end the persecution of -static-md, that it has endured for so long.

I believe there's a good chunk of users that face the same frustration every-time they update their vcpkg git repository and pray to gods their favorite libraries still compile and someone hasn't broken those.

**Comment by JackBoosY** [comment]
In the future, I hope that vcpkg will no longer distinguish between official triplet and community triplet. vcpkg should correctly set the flags and other variables in each compiler according to the triplet.

**Comment by BillyONeal** [comment]
After some discussion we decided that it would be OK to add PR validation / testing / etc. for this if someone wants to make the initial edits to `ci.baseline.txt` etc. and add the triplet in our build scripts at `$/scripts/azure-pipelines`, we would accept such a PR.

However, we will nonetheless leave the triplet in community status because we are still strongly recommending against shipping with that configuration due to the aforementioned issues.

**Comment by ankurverma85** [comment]
Thanks a lot for the consideration.

I submitted a PR mostly replicating the x64-windows-static infrastructure
https://github.com/microsoft/vcpkg/pull/15411
However I might need some help taking this through

I'd appreciate if someone from the  maintainer-team can monitor that and pitch in.

**Comment by BillyONeal** [comment]
@ankurverma85 Thanks for your PR :)

**Comment by aggieNick02** [comment]
I stumbled onto something today that made me revisit this thread. I noticed that the default linux triplet is static link with dynamic runtime... I realize there are some differences between linux and windows, but it made me scratch my head. How can this be ok on linux but be considered dangerous on windows? Looking above, this is one of the things @ankurverma85 pointed out, but I didn't really appreciate it at the time.
> There are several reasons we don't recommend static-md: (snip)
> * Static-md creates inconsistent views of the universe when your DLL is mixed with other DLLs in a program that also use one of the libraries in question, since the CRT's view is that there is only one copy of various globals like `locale::locale()`, the new handlers, atexit handlers, etc. but each of the libraries' view is that each DLL would have their own globals. We expect this is likely to lead to subtle bugs. This inconsistent view is one of the reasons many libraries (such as Boost.Test) forbid such a configuration when they are made aware that it exists.

I dug into this point today. I'm guessing you're referring to this in auto_link.hpp:

```
#if (defined(_DLL) || defined(_RTLDLL)) && defined(BOOST_DYN_LINK)
#  define BOOST_LIB_PREFIX
#elif defined(BOOST_DYN_LINK)
#  error "Mixing a dll boost library with a static runtime is a really bad idea..."
#else
#  define BOOST_LIB_PREFIX "lib"
#endif
```
This is not what `static-md` does though. `static-md` is static linking (no dlls) with dynamic runtime. Boost issues an error when you do dynamic linking with static runtime. Aren't the other issues raised in this paragraph also for dynamic linking with static runtime? I understand why *that* would be problematic, but not `static-md`.

Can we get acknowledgment that there are *not* any issues with static-md in terms of stability/globals/new/atexit/boost/etc? I'm pretty sure the only legit point against `static-md` is that you end up with a single exe that requires the runtime be installed, and I don't think that's enough for its use to be "strongly discouraged".

**Comment by BillyONeal** [comment]
>How can this be ok on linux but be considered dangerous on windows?

Because symbols aren't namespaced to the module they come from on Linux, and a library statically linking with the CRT on that platform is effectively impossible (since it would try to stomp on symbols from the system CRT the entry point binary probably wants).

> I'm guessing you're referring to this in auto_link.hpp:

That situation is indeed worse (since instead of being likely to create inconsistent universes it absolutely does create inconsistent universes!) but the reverse mismatch is still problematic.

>Can we get acknowledgment that there are not any issues with static-md in terms of stability/globals/new/atexit/boost/etc?

The problems I enumerated are indeed still a problem.

**Comment by aggieNick02** [comment]
Sorry for the delayed response. In my looking, I wasn't able to find details about the possible inconsistencies being referenced. I'd really like to understand what they are so that I can mitigate any risks I'm taking by using x64-windows-static-md (or 3rd party libraries distributed as static lib linking windows runtime). If you have any pointers to documents about them I'd really appreciate it and could dig into them more, and be happy to write up a more detailed explanation of what they are to help other vcpkg users.

**Comment by ankurverma85** [comment]
I would love to see that *write-up* as well.

Here's some anecdotal evidence of perhaps it being largely fine.
I've been now using close to a 220 libraries (osgearth and its dependencies) all compiled with x64-windows-static-md in a single project to produce exe's that link all those libs together.
Its by no means is proof of correctness but I'm willing to swear by it mainly based on the above statistic.

x64-windows has been a nightmare for development, packaging and debugging and practically useless because of the number of dlls that need to be managed in the above project.
and I wouldn't go for x64-windows-static because that's contrary to what I've been taught all along. 
CRT-DLL = Good
CRT-Static = Bad
And
"Let the CRT be managed and updated by windows. That's good for security." 

I've also been involved with the development of onnxruntime port (under PR review) that is being used as a x64-windows-static-md port (infact that the only triplet it currently supports) which again pulls in a significant number of external libraries 

So before I index too much towards preaching x64-windows-static-md. I'd love to hear why we shouldnt be using it.

**Comment by ankurverma85** [comment]
Opened #16387 to carry the discussion forward and potentially seek and update to FAQ's or docs

**Comment by aggieNick02** [comment]
thanks @ankurverma85 for opening the new issue. I really am happy to dig a bit and at least get some documented nuggets for a whitepaper if given some pointers to examples of issues that can occur. I'll move to the new issue for any new discussion.
