### ISSUE TITLE
EOF of docs/maintainers/maintainer-guide.md is CR LF

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#15247]
After check some other docs file in `docs/maintainers`, EOF is LF for each one.
Better to fix it?

**Comment by JackBoosY** [comment]
cc @BillyONeal

**Comment by BillyONeal** [comment]
I agree that we should be consistent here, I marked requires discussion so that we discuss which way the conflict should be resolved. In other projects I've helped maintain we always stored CRLFs because all the *nix editors understood it even if it wasn't the absolute native encoding for their platforms, while notepad completely choked on LF only files. However, in recent Win10 they finally fixed Win10 so that rationale for resolving the conflict that way no longer applies.

The majority of the existing files are LF as you say, so that argues going with that, but I don't want to unilaterally make / document a policy like that.

**Comment by JackBoosY** [comment]
@BillyONeal But I think this is unnecessary...

**Comment by playgithub** [comment]
How do I noticed the EOL issue:
1. A very simple PR can not pass the ckecks
2. When trying to find the problem, `git diff` shows "maintainer-guide.md" has been modified about EOL. If it is modified by me, it must be by accident.
3. After restore EOL to LF, the PR passed the checks
4. The confusing thing, when revert changed of "maintainer-guide.md" (be the origianl EOL which is CR/LF), the PR also passed the checks

I think if it is easy to keep consistency for simplicity, why not?

**Comment by BillyONeal** [comment]
After discussion we decided that in making this consistent we should choose LF only.

**Comment by PhoebeHui** [comment]
After check all docs under vcpkg\docs\, 13 docs still end of CRLF, 

```
vcpkg\docs\maintainers\maintainer-guide.md
vcpkg\docs\users\versioning.implementation-details.md
vcpkg\docs\users\versioning.md
vcpkg\docs\users\config-environment.md
vcpkg\docs\examples\overlay-triplets-linux-dynamic.md
vcpkg\docs\examples\packaging-github-repos.md
vcpkg\docs\examples\versioning.getting-started.md
vcpkg\docs\examples\modify-baseline-to-pin-old-boost.md
vcpkg\docs\specifications\ports-overlay.md
vcpkg\docs\specifications\scripts-extraction.md
vcpkg\docs\specifications\versioning.md
vcpkg\docs\specifications\binarycaching.md
vcpkg\docs\specifications\feature-packages.md
```

**Comment by BillyONeal** [comment]
This all moved to learn.microsoft.com so it can't matter anymore.
