### ISSUE TITLE
[ OpenSSL  ]Win10 Install OpenSSL with vcpkg<Error: Building package openssl:x64-windows-static failed with: BUILD_FAILED>

### ISSUE THREAD

**Issue by wangyang1701** [microsoft/vcpkg#15323]
**Host Environment**
- OS: [e.g. Windows 10]
- Compiler:  VS2019

**To Reproduce**
Steps can be found at https://substrate.dev/docs/en/knowledgebase/getting-started/windows-users

**Failure logs** 
-Cut and past the appropriate build messages from the console output.

                            **C:\Tools\vcpkg>.\vcpkg.exe install openssl:x64-windows-static
                            Computing installation plan...
                            The following packages will be built and installed:
                                openssl[core]:x64-windows-static -> 1.1.1h#4
                            Detecting compiler hash for triplet x64-windows-static...
                            Could not locate cached archive: 
                           C:\Users\Selina\AppData\Local\vcpkg\archives\21\21be15c0d2987650b3bce59f0c0cd665949175cb.zip
                            Starting package 1/1: openssl:x64-windows-static
                            Building package openssl[core]:x64-windows-static...
                            -- Using cached C:/Tools/vcpkg/downloads/openssl-1.1.1h.tar.gz
                            -- Downloading https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip...
                            -- Downloading https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip... Failed. Status: 
                              22;"HTTP response code said error"
                            -- Downloading http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip...
                            -- Downloading http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip... Failed. Status: 
                              56;"Failure when receiving data from the peer"
                            CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):
                            
                                  Failed to download file.
                                  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
                                  variables to "https://user:password@your-proxy-ip-address:port/".
                                  Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
                            
                            Call Stack (most recent call first):
                              scripts/cmake/vcpkg_find_acquire_program.cmake:544 (vcpkg_download_distfile)
                              ports/openssl/portfile.cmake:12 (vcpkg_find_acquire_program)
                              scripts/ports.cmake:136 (include)
                            
                            
                            Error: Building package openssl:x64-windows-static failed with: BUILD_FAILED
                            Please ensure you're using the latest portfiles with `.\vcpkg update`, then
                            submit an issue at https://github.com/Microsoft/vcpkg/issues including:
                              Package: openssl:x64-windows-static
                              Vcpkg version: 2020.11.12-nohash
                            
                            Additionally, attach any relevant sections from the log files above.**

-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@wangyang1701 ,Thanks for posting this issue,Seems your network couldn't download the source package, please set a proxy then try again.

Thanks.

**Comment by wangyang1701** [comment]
it works now, thanks a lot

> @wangyang1701 ,Thanks for posting this issue,Seems your network couldn't download the source package, please set a proxy then try again.
> 
> Thanks.

**Comment by JonLiu1993** [comment]
@wangyang1701 ，I will close this issue, if you have a problem, you can reopen it

**Comment by Capone68** [comment]
I have the exact same error, I have disabled the proxy. To try again will I need to uninstall anything before trying again please? Im' new at this, but thanks would appreciate any suggestion and direction.


Resolving deltas: 100% (65545/65545), done.
Updating files: 100% (7280/7280), done.
PS C:\Tools> cd vcpkg
PS C:\Tools\vcpkg> .\bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-02-24-d67989bce1043b98092ac45996a8230a059a2d7e/vcpkg.exe -> C:\Tools\vcpkg/vcpkg.exe
Done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
PS C:\Tools\vcpkg> .\vcpkg.exe install openssl:x64-windows-static
Computing installation plan...
A suitable version of cmake was not found (required v3.19.2). Downloading portable cmake v3.19.2...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.19.2/cmake-3.19.2-win32-x86.zip -> C:\Tools\vcpkg\downloads\cmake-3.19.2-win32-x86.zip
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\Tools\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v5.5.1). Downloading portable nuget v5.5.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> C:\Tools\vcpkg\downloads\22ea847d-nuget.exe
The following packages will be built and installed:
    openssl[core]:x64-windows-static -> 1.1.1i
Detecting compiler hash for triplet x64-windows-static...
A suitable version of powershell-core was not found (required v7.1.0). Downloading portable powershell-core v7.1.0...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/PowerShell-7.1.0-win-x86.zip -> C:\Tools\vcpkg\downloads\PowerShell-7.1.0-win-x86.zip
Extracting powershell-core...
Could not locate cached archive: C:\Users\HOME\AppData\Local\vcpkg\archives\af\af0ed944fbb72653d05a7da75fe5a86c1ea6c518.zip
Starting package 1/1: openssl:x64-windows-static
Building package openssl[core]:x64-windows-static...
-- Downloading https://www.openssl.org/source/openssl-1.1.1i.tar.gz -> openssl-1.1.1i.tar.gz...
-- Downloading https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip -> strawberry-perl-5.30.0.1-32bit.zip...
-- Downloading https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip... Failed. Status: 22;"HTTP response code said error"
-- Downloading http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip -> strawberry-perl-5.30.0.1-32bit.zip...
-- Downloading http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip... Failed. Status: 56;"Failure when receiving data from the peer"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".

      If error with status 4 (Issue #15434),
      try setting "http://user:password@your-proxy-ip-address:port/".

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:544 (vcpkg_download_distfile)
  ports/openssl/portfile.cmake:12 (vcpkg_find_acquire_program)
  scripts/ports.cmake:139 (include)


Error: Building package openssl:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x64-windows-static
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**Comment by Capone68** [comment]
I'm also using windows 10 wsl and visual studio complier 2019. following substrate getting started with windows guidelines, I not sure how to set the proxy if i am supposed to. I did manually enter in the ip address and port via control panel, network Lan setting which stopped my internet connection. I have then cleared the proxy settings to get the connection back. when re-entering the code to reload this vcpkg I got the exact same error. FYI. Thanks.
