### ISSUE TITLE
Question about static linking

### ISSUE THREAD

**Issue by vmiheer** [microsoft/vcpkg#15321]
1. Does it make sense to automatically set `MSVC_RUNTIME_LIBRARY` if chosen triplet is `*-windows-static`
```cmake
set_property(TARGET maestro PROPERTY
  MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
```

2. Should `vcpkg install` show additional information about how to use in cmake if triplet is `*-windows-static`?

I think below update to message would be really helpful.

```diff
The package boost is compatible with built-in CMake targets:
+ Add `-DVCPKG_TARGET_TRIPLET=x64-windows-static` to your cmake invocation.
    find_package(Boost REQUIRED [COMPONENTS <libs>...])
    target_link_libraries(main PRIVATE Boost::boost Boost::<lib1> Boost::<lib2> ...)
```

**Comment by JackBoosY** [comment]
Since vcpkg will automatically set the specified CRT linkage based on the triplet, the cmake configuration file generated by the port contains this information.

See triplet:
https://github.com/microsoft/vcpkg/blob/4a678aa329c0a6323d7334fdf3ad37d571600d27/triplets/x64-windows-static.cmake#L2
setting:
https://github.com/microsoft/vcpkg/blob/4a678aa329c0a6323d7334fdf3ad37d571600d27/scripts/toolchains/windows.cmake#L8-L14

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
