### ISSUE TITLE
msvcp140、vcruntime140

### ISSUE THREAD

**Issue by gsegria** [microsoft/vcpkg#15386]
I develop windows tool with vs2019 and vcpkg on my desktop A. (build using a  Static Library and MT to generate tool.exe)
When i execute tool.exe is no problem no my desktop A.
But i execute tool.exe on desktop B , tool.exe cannot work and show msvcp140.dll, vcruntime140.dll...
The desktop A has install vs2019.
The desktop B doesn't install vs2019.

I don't install vs2019 or MS dll package on desktop B.  Any way to solve dll issues?

**Comment by JackBoosY** [comment]
cc @vicroms

**Comment by vicroms** [comment]
Hi @gsegria 

You need those files in your second computer because you're linking the CRT runtime dynamically in your program. The `x86-windows` and `x64-windows` triplets do that by default. 

Those files are part of the **VC++ 2015 Redistributable** package; and are absolutely needed to run your program. But, you don't need to install the complete Visual Studio in your second computer to get them. You just need to download and install the appropriate `vc_redist.exe` from:
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

If you don't want to distribute or install any kind of DLL with your application consider switching to a static triplet (`x86-windows-static` or `x64-windows-static`).

**Comment by gsegria** [comment]
Yes, I don't want to distribute or install any kind of DLL with my application.
vcpkg , how to configuration and build x86-windows-static or x64-windows-static , after link to my project with static lib?

**Comment by Hoikas** [comment]
If you absolutely need dynamic CRT but cannot install the runtime package on the user's machine, try [InstallRequiredSystemLibraries](https://cmake.org/cmake/help/latest/module/InstallRequiredSystemLibraries.html).

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
