### ISSUE TITLE
[vcpkg upgrade] vcpkg tries to upgrade Linux package when running on Windows?

### ISSUE THREAD

**Issue by ThomsonTan** [microsoft/vcpkg#15483]
**Describe the bug**
I have installed some packages for both Windows and Linux in the same location (run `vcpkg install` for Linux under WSL) which is very convenient. But when I update vcpkg and tries to run `vcpkg install` on Windows, it seems trying to upgrade the Linux packages too then failed. 

```
 vcpkg.exe upgrade --no-dry-run
The following packages will be rebuilt:
  * grpc[core]:x64-linux -> 1.33.1#2
  * grpc[core]:x64-windows -> 1.33.1#2
  * protobuf[core]:x64-linux -> 3.14.0#1
  * protobuf[core]:x64-windows -> 3.14.0#1
Removing package protobuf:x64-linux... done
Elapsed time for package protobuf:x64-linux: 99.83 ms
Starting package 4/8: protobuf:x64-windows
Removing package protobuf:x64-windows...
Removing package protobuf:x64-windows... done
Elapsed time for package protobuf:x64-windows: 132.7 ms
Detecting compiler hash for triplet x64-linux...
Error occurred while detecting compiler information. Pass `--debug` for more information.
```

**Environment**
- OS: [Windows 20H2]
- Compiler: Visual Studio 2019

**To Reproduce**
1. Install both Windows and Linux flavors of a package.
1. ./vcpkg upgrade --no-dry-run
2. See error as shown above

**Expected behavior**
`vcpkg upgrade` should succeed and only upgrade the packages for current platform.

**Failure logs** 
-(please above error log)

**Comment by JackBoosY** [comment]
Hmm...I think that's a vcpkg bug.

**Comment by StarGate-One** [comment]
- I think sharing an instance between platforms is bad business looking for trouble, but ....
- Is it a bug or is it because vcpkg thinks these were cross-compiled?
- How would/should vcpkg know when a port/triplet was compiled from windows or WSL or macOS in a case of a vcpkg shared instance on a say a network drive (or in this case the same file system between WSL and Windows).
- I created a test instance on windows (D:\Git\vcpkg\test), bootstrapped and installed ports bzip2, zlib and zstd for x64-windows.
- I think opened WSL2 (OpenSUSE Linux 15.2) and cd over to /mnt/d/git/vcpkg/test, boostrapped and installed ports bzip2, zlib and zstd for x64-linux.
- I then made edits to the CONTROL/vcpkg.json files for those ports, incrementing the Port-Version up by one.
- Did a `.\vcpkg.exe upgrade` on windows and `./vcpkg upgrade` on linux and both wanted to upgrade the ports for both triplets, even though windows installed the x64-windows ports and Linux installed the x64-linux ports.
- Windows
![image](https://user-images.githubusercontent.com/68293825/103953147-9587db00-510f-11eb-97b9-6756cae44263.png)
- WSL2 (OpenSUSE Linux
![image](https://user-images.githubusercontent.com/68293825/103953187-a8021480-510f-11eb-96ae-dca470bf0813.png)

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/3453
