### ISSUE TITLE
OpenSSL for M1/arm Mac creates a library that can only be linked with iOS platforms

### ISSUE THREAD

**Issue by heckj** [microsoft/vcpkg#15741]
**Describe the bug**

Building OpenSSL (version 1.1.1i) through vcpkg results in a complete compilation with failures, but the resulting binary is marked as being only able to be linked against iOS.

The error from the linker when I'm trying to link against libcrypto (through grpc, if that's relevant) is:

```
ld: in /Users/heckj/bin/vcpkg/installed/arm64-osx/debug/lib/libcrypto.a(a_strex.o), building for macOS, but linking in object file built for iOS
```

**Environment**
- OS: macOS 11.1, M1 native arm64
- Compiler: Clang 12 (Xcode 12.3 toolchain)

**To Reproduce**
1. `./vcpkg install grpc --triplet arm64-osx`
2. `otool -lv ./installed/arm64-osx/lib/libcrypto.a  | grep -A5 LC_`

If the output includes `LC_VERSION_MIN_IPHONEOS`, then the binary is encoded with iOS as it's platform. A binary encoded for macOS should have output that looks something like this:

```
      cmd LC_BUILD_VERSION
  cmdsize 24
 platform MACOS
    minos 11.0
      sdk 11.1
   ntools 0
```

I found this after some debugging, the full story and detail of which is available at <https://rhonabwy.com/2021/01/18/m1-arm64-native-openssl-with-vcpkg/>.

**Expected behavior**
- I'd hoped to have a libcrypto.a that was linkable to macOS binary.

**Failure logs** 
- attached as `buildtree_openssl_logs.zip`
- [buildtree_openssl_logs.zip](https://github.com/microsoft/vcpkg/files/5832781/buildtree_openssl_logs.zip)

**Additional context**
One element of note that I was able to determine: if you build the OpenSSL code through a rosetta2 enabled terminal (using `x86_64` emulation), then you'll get this same issue. To compile it locally, you need to run the compilation with an `arm64` native terminal. I'm not clear on what in OpenSSL's build is inferring platform details from the terminal session, but apparently something is.

I did replicate the cmake build steps that vcpkg ran, and ran them manually in a terminal session to debug. From that I found this detail about needing to run in arm64 native mode for OpenSSL. When I ran those steps from a rosetta enabled terminal, I got the same result as vcpkg directly.

I have tried completely removing and compiling vcpkg as arm64 native, but that didn't appear to make a difference in how everything got build and resulted in the same issues. I do have x86_64 (rosetta2 translation) installed tooling in my path using Homebrew.

**Comment by ras0219** [comment]
This could be caused by the copy of CMake being used -- on OSX we download a [prebuilt CMake executable][1] (to ensure everything is using known-good bits), and that might be a source of x86_64-ness. That means that the process tree would end up being something like:

> vcpkg (arm64) -> CMake (x64) -> sh (x64) -> perl (x64) -> clang (?)

The CMake binary package is labelled as "universal", so the above could be completely wrong. It should be simply diagnosable by adding an `execute_process(COMMAND uname -a)` to a portfile. You could also try sprinkling `arch -arm64` in front of all the process executions in [ports/openssl/unix/CMakeLists.txt][3], especially the initial `"${PERL}" Configure`.

Side note while trying to research this bug: we might want vcpkg to check the macos runtime arch via `sysctlbyname("sysctl.proc_translated", ...)`[2] or somesuch to use the right default triplet even if compiled for x86_64.

[1]: https://github.com/microsoft/vcpkg/blob/0c94afc7883faee9f188c36232d628ffa94cf27f/scripts/vcpkgTools.xml#L17
[2]: https://developer.apple.com/documentation/apple_silicon/about_the_rosetta_translation_environment
[3]: https://github.com/microsoft/vcpkg/blob/0c94afc7883faee9f188c36232d628ffa94cf27f/ports/openssl/unix/CMakeLists.txt#L157

**Comment by kafeg** [comment]
Hey! Could you please re-test this issue? It works fine for me at 28.05.21, here is `universal cmake executable (x86_64 + arm64)`. For e.g.:

```
 % ./vcpkg install --triplet arm64-osx grpc
Computing installation plan...
The following packages are already installed:
    grpc[codegen,core]:arm64-osx -> 1.37.0#1
Package grpc:arm64-osx is already installed

Total elapsed time: 5.958 us

The package grpc:arm64-osx provides CMake targets:

    find_package(gRPC CONFIG REQUIRED)
    # Note: 8 target(s) were omitted.
    target_link_libraries(main PRIVATE gRPC::gpr gRPC::upb gRPC::grpc gRPC::grpc++)

    find_package(modules CONFIG REQUIRED)
    target_link_libraries(main PRIVATE re2::re2 c-ares::cares)
```

**Comment by heckj** [comment]
🙇
