### ISSUE TITLE
[zlib:x86-windows-static] build failure on old versions

### ISSUE THREAD

**Issue by j04n** [microsoft/vcpkg#15758]
**Summary**
zlib's download URL is not working for old versions, vcpkg should use https://zlib.net/fossils/ instead

**To Reproduce**
vcpkg --feature-flags=versions,manifests --triplet=x86-windows-static install

with manifest for zlib 1.2.10:
```
{
    "name": "example",
    "version-date": "2020-01-01",
    "builtin-baseline": "c0020eb4e5f1a297b8514a03deaf58e90652257b",
    "dependencies": [
        {
            "name": "zlib",
            "version>=": "1.2.10"
        }
    ],
    "overrides": [
        {
            "name": "zlib",
            "version-string": "1.2.10"
        }
    ]
}
```

**Failure logs** 

Downloading http://www.zlib.net/zlib-1.2.10.tar.gz... Failed.

**Additional context**

URL for old zlib versions should be [https://zlib.net/fossils/](https://zlib.net/fossils/)
(e.g. https://zlib.net/fossils/zlib-1.2.10.tar.gz)

**Comment by j04n** [comment]
AFAIK the problem is not related to the triplet; it will happen with any triplet to build old versions of zlib (with versioning enabled).

**Comment by vicroms** [comment]
Hi @j04n 

Thanks for trying the new versioning features! Versioning support is still considered experimental and we're still in the process of stabilizing it and gathering user feedback.

We are aware of this issue, since versioning in vcpkg reduces to checking out the old portfiles from the vcpkg's repository history. It is possible for situations like this to occur when resources are no longer available.

It is possible to retro-actively fix the offending ports by checking-in updated portfiles for old versions and updating the corresponding version files. However, this conflicts with our current policy of not allowing to merge downgrades to ports. 

We'll explore solutions for this issues as part of our stabilization of the feature.

**Comment by j04n** [comment]
Thanks @vicroms for the explanations; other than that I experimented a bit with versionning and it worked well (when resources were still in place for old versions :)), so keep up the good work! :-)

Also, for those who might have the same problem, it can be manually solved by downloading old zlib versions and putting them directly into /download folder.
