### ISSUE TITLE
poco:x86-windows-static - pkg build failure

### ISSUE THREAD

**Issue by captainnumerica** [Microsoft/vcpkg#1590]
**Error: Building package poco:x86-windows-static failed with: BUILD_FAILED**
Please ensure you're using the latest portfiles with `.\vcpkg update`, then submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  **Package: poco:x86-windows-static**
  **Vcpkg version: 0.0.81-f31dd7dcaf174d32275673632dbca2df0eed44f1**

---

[package-x86-windows-static-rel.zip](https://github.com/Microsoft/vcpkg/files/1197870/package-x86-windows-static-rel.zip)

**Comment by ras0219-msft** [comment]
Thanks for posting your issue and sorry for the delay!

> C:\Program Files\Anaconda3\Library\lib\z.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'X86'

It looks like cmake is picking up the Anaconda copy of zlib from your machine. I'm not sure how this is possible, since we clear out the environment for building.

Could you run `vcpkg env --triplet x86-windows-static --debug` to get a shell inside the build environment and then run `set | findstr "Anaconda"`? (use `exit` to get out of the build shell afterwards)

**Comment by captainnumerica** [comment]
Thanks for getting back to me.  I'll try later this evening to repro this on the same machine.
