### ISSUE TITLE
powelshell suspended on vcpkg install openssl.

### ISSUE THREAD

**Issue by feicong** [Microsoft/vcpkg#1599]
I am trying to install openssl use the following command:
```
vcpkg install openssl
or 
vcpkg install openssl:x86-windows-static
or
vcpkg install openssl:x64-windows
```

powelshell will suspended. output like this:
```
D:\vcpkg> .\vcpkg.exe install openssl:x86-windows-static
The following packages will be built and installed:
    openssl:x86-windows-static
Building package openssl:x86-windows-static...
-- CURRENT_INSTALLED_DIR=D:/vcpkg/installed/x86-windows-static
-- DOWNLOADS=D:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/vcpkg/packages/openssl_x86-windows-static
-- CURRENT_BUILDTREES_DIR=D:/vcpkg/buildtrees/openssl
-- CURRENT_PORT_DIR=D:/vcpkg/ports/openssl/.
-- [download 0% complete]
```

suspended with message `-- [download 0% complete]`, Is there any solution? thx.

```
D:\vcpkg> vcpkg version
Vcpkg package management program version 0.0.81-17cb5b9c3483a2aca45e2a525d2ce3b386676832

See LICENSE.txt for license information.
```

**Comment by feicong** [comment]
`perl` installed from https://www.perl.org.

`nasm` downloaded from www.nasm.us and in `PATH` environment variable . 

download & buildtree dir was cleaned, but the problem is still exists.

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue!

To maximize reproducibility, we use specific versions of perl and nasm from inside the Vcpkg directory and ignore any versions installed on the system -- this is why you're seeing attempts to download even after you installed some other versions system-wide.

The best fix would be to enable vcpkg to download its specific versions. Are you perhaps using a proxy? You'll need to set the HTTP_PROXY and HTTPS_PROXY environment variables [1], since we use curl internally.

If this isn't the problem or doesn't fix it, the best workaround would be to download the specific files we need and place them in the downloads folder. In this case, that would be:
  - Perl
    - http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip
    - `downloads/strawberry-perl-5.24.1.1-32bit-portable.zip`
    - https://github.com/Microsoft/vcpkg/blob/5ef872a604cd9c1f067b4b5773ca2fef55c038e4/scripts/cmake/vcpkg_find_acquire_program.cmake#L51
  - NASM
    - http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/win32/nasm-2.12.02-win32.zip
    - `downloads/nasm-2.12.02-win32.zip`
    - https://github.com/Microsoft/vcpkg/blob/5ef872a604cd9c1f067b4b5773ca2fef55c038e4/scripts/cmake/vcpkg_find_acquire_program.cmake#L57

However, I believe you will encounter problems later on while trying to download the source code for the libraries, so it would be far, far better to fix any proxy issues instead.

[1] https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html

**Comment by feicong** [comment]
thx a lot. this problem is solved.
