### ISSUE TITLE
How do I properly use the vcpkg-tool repo?

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#16032]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
@BillyONeal  /cc: @ras0219-msft 
1. Somewhere I am missing something because my vcpkg-tool fork keeps getting out of sync saying my fork is `xx Commits ahead and yy Commits behind` microsoft/vcpkg-tool main.
2. I treat it the same as I do with vcpkg master, but use main as the branch name
   - I fork the vcpkg-tool on github to my github
   - I clone my fork of vcpkg-tool to my pc
   - I add microsoft/vcpkg-tool as an upstream main
   - Perform git pull upstream main to pull updates
   - Perform git push to update my vcpkg-tool fork
3. The past 2 days I have had to basically start over to get my fork back in sync
   - I delete my fork of vcpkg-tool on github
   - I delete the clone on my PC
   - Start over using Step 2 again, and all is in sync until an update is done to microsoft/vcpkg-tool
4. Basically my question is what am I doing wrong? 
5. Is there something I should be doing with the microsoft/vcpkg-tool repo and my fork?
Thank you for your time, I know you have been busy these past 2 days, but I appreciate any help or insight.
Have a wonderful day/evening.

**Comment by BillyONeal** [comment]
Until we actually make the switch here to start consuming the vcpkg-tool repo, every time a toolsrc change was made here I've had to rebase that whole repo on top of this one to maintain correct history. The problems you've experienced caused by those rebases being force pushes should be resolved after https://github.com/microsoft/vcpkg/pull/15474 lands and we start treating that repo like any other publicly exposed git repo.

Sorry for the confusion caused by the `filter-branch` fallout :/

**Comment by StarGate-One** [comment]
Ok - just wanted to be sure I was not doing something wrong.
I will know until #15474 goes in, my fork of vcpkg-tool could get out of sync and I can just delete the fork and re-fork again.
I have been working on a local powershell script to build the vcpkg-tool from source using cmake.
Thanks again for all the hard work👏👏👏✔✨👍
