### ISSUE TITLE
Embree build failure

### ISSUE THREAD

**Issue by tmamakov** [microsoft/vcpkg#16060]
**Host Environment**
- OS: WSL: Ubuntu 20.04
- Compiler: Cmake/gcc

**To Reproduce**
Inatall embree
`./vcpkg install embree3`

add to CMakeLists.txt
`find_package(embree 3 REQUIRED)`
`target_link_libraries(${PROJECT_NAME} PRIVATE embree)`

call
`cmake ..`

**Failure logs** 
```
  Found package configuration file:

    /path-to/vcpkg/installed/x64-linux/share/embree/embree-config.cmake

  but it set embree_FOUND to FALSE so package "embree" is considered to be
  NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  embree_avx512skx
```
**Additional context**
Switching related param in embree-config.cmake didn't help.
`SET(EMBREE_ISA_AVX512SKX OFF)`

UPD:
Direct clone/build with ```-DEMBREE_ISPC_SUPPORT=NO``` flag works fine. But it will be much better to use vcpkg embree3 ...

**Comment by Fedr** [comment]
For some reason on windows in embree-config.cmake I see:
```
SET(EMBREE_ISA_AVX512SKX OFF)
```
And on Linux in the same file:
```
SET(EMBREE_ISA_AVX512SKX ON)
```
Where does this setting come from?

**Comment by NancyLi1013** [comment]
Hi @Fedr 

Thanks for posting this issue.

Sorry for the late response. I install `embree3 `failed with the error like this:
`c++: fatal error: Killed signal terminated program cc1plus`

So it might be some tome to figure this out.

@Fedr 

The value of `EMBREE_ISA_AVX512SKX ` is decided by `@EMBREE_ISA_AVX512SKX@` in embree-config.cmake
`SET(EMBREE_ISA_AVX512SKX @EMBREE_ISA_AVX512SKX@)`

Since it behaves differently on different platform.

```
  IF (WIN32 OR APPLE)
    OPTION(EMBREE_ISA_AVX512KNL "Enables AVX512 ISA for Knights Landing." OFF)
    OPTION(EMBREE_ISA_AVX512SKX "Enables AVX512 ISA for Skylake." OFF)
  ELSE()
    OPTION(EMBREE_ISA_AVX512KNL "Enables AVX512 ISA for Knights Landing." OFF) # compilation on GCC 8 broken
    OPTION(EMBREE_ISA_AVX512SKX "Enables AVX512 ISA for Skylake." ${COMPILER_SUPPORTS_AVX512SKX})
  ENDIF()
```
