### ISSUE TITLE
Error: Building package gmp:x64-windows failed with: Build_failed

### ISSUE THREAD

**Issue by js2580** [microsoft/vcpkg#16168]
Package: gmp:x64-windows
 Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

CMake Error at installed/x64-windows/share/yasm-tool-helper/yasm-tool-helper.cmake:16 (message):
  Cross-targetting and x64 ports requiring yasm require the x86-windows
  yasm-tool to be available.  Please install yasm-tool:x86-windows first.
Call Stack (most recent call first):
  ports/gmp/portfile.cmake:19 (yasm_tool_helper)
  scripts/ports.cmake:131 (include)

**Comment by StarGate-One** [comment]
Need to install the x86 yasm-tool first, then install gmp port[features].
`./vcpkg install yasm-tool:x86-windows`

**Comment by vtraag** [comment]
I just ran into this problem as well. As @StarGate-One suggests, the fix is simple. However, ideally, it should be solved by somehow indicating the proper dependency in `ports/gmp/vcpkg.json`. Unfortunately, it does not seem possible to specify a specific triplet as a dependency. This is also discussed in issue https://github.com/microsoft/vcpkg/issues/13155.
