### ISSUE TITLE
Installation of older versions of packages

### ISSUE THREAD

**Issue by petulka8s** [microsoft/vcpkg#16170]
Hi,

I am trying to use vcpkg to install libraries. Everything is going well, but on some cases I need older version of the library.
For example, the actual version of boost is 1.75. For my project I need 1.72. Is there a way how can I install it using vcpkg?

I found something like: **vcpkg install boost:boost-$(Arch)-$(Toolchain)-$(Hash)**

vcpkg install boost:boost-x64-windows-1.72.0 is not working.
Can you help me what I am doing wrong? Or there is another way how to install older version of the package?

Thanks for you advices.

**Comment by autoantwort** [comment]
See #1681

**Comment by vicroms** [comment]
Yes, you can use manifests with the newly added versioning features.

Read our [Getting Started with Versioning guide](https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.getting-started.md).  

Boost is a unique one since you need to override each individual port. It becomes easier if you limit yourself to depend on the ports you actually need. For example:

```
{
  "name": "boost-demo",
  "version": "1.0.0",
  "builtin-baseline": "60d979c5884f9564f397fdf7bca50eb5dd8d5a20",
  "dependencies": ["boost-core"], 
  "overrides": [
    {
      "name": "boost-core",
      "version-string": "1.72.0"
    }, 
    {
      "name": "boost-compatibility",
      "version-string": "1.72.0"
    }, 
    {
      "name": "boost-config",
      "version-string": "1.72.0"
    }
  ]
}
```

**Comment by petulka8s** [comment]
Thanks.
So if I understand, there is no possibility how to install older version of packages via one line vcpkg install......
If I use manifest, there are some things like "builtin-baseline": "b60f003ccf5fe8613d029f49f835c8929a66eb61".
How can I know this number for boost 1.72?

Sorry, I am totally new to this.

**Comment by vicroms** [comment]
> Sorry, I am totally new to this.

No problem, we're here to help. You may also want to reach out to us on the [#includecpp Discord (the vcpkg channel)](https://www.includecpp.org/) for more synchronous communication.

> So if I understand, there is no possibility how to install older version of packages via one line vcpkg install......

Right now there is no way to use versions with classic vcpkg (command-line interface).

> If I use manifest, there are some things like "builtin-baseline": "b60f003ccf5fe8613d029f49f835c8929a66eb61".
How can I know this number for boost 1.72?

Since versioning was implemented fairly recently, the baseline does not go all the way back to Boost 1.72.  Because of that I suggested using `"overrides"`. 

There is a way to make a local retroactive baseline so that all the Boost packages are set to 1.72.

1. Create a new branch
```
git checkout -b boost-1.72-baseline
```
2. Modify `versions/baseline.json` to set the baseline version of all Boost packages to 1.72.0 (remember to set `port-version` to 0 too)
```
...
    "boost": {
      "baseline": "1.72.0",
      "port-version": 0
    },
    "boost-accumulators": {
      "baseline": "1.72.0",
      "port-version": 0
    },
    "boost-algorithm": {
      "baseline": "1.72.0",
      "port-version": 0
    },
...
```
3. Commit your changes.
```
git add versions/baseline.json
git commit -m "Set boost baseline versions to 1.72"
```
4. Get the SHA for your last commit.
```
git rev-parse HEAD
```
5. Use that commit ID as the "builtin-baseline" in your manifest
```
  "builtin-baseline": "<commit id SHA>",
```

The method I described above, is a bit of a hack. The proper way to do this without having to modify vcpkg locally is to use [Git registries](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/registries-2.md).

**Comment by petulka8s** [comment]
Thank you, I changed the version in versions/baseline.json, but when I want to install that package, it still install the newest one.

**Comment by vicroms** [comment]
Can you copy and paste what your `vcpkg.json` looks like?

**Comment by petulka8s** [comment]
my vcpkg is some I just rewrote everywhere in boost 1.75.0 to 1.66.0.
Should I change also something else?

**Comment by PhoebeHui** [comment]
@petulka8s, could you attach the vcpkg.json file?

**Comment by vicroms** [comment]
Hi @petulka8s 

I opened a PR that adds documentation of [how to pin specific Boost versions](https://github.com/vicroms/vcpkg/blob/versioning/docs2/docs/examples/modify-baseline-to-pin-old-boost.md).
Please take a look at it, and let me know if it helps.

**Comment by PhoebeHui** [comment]
@petulka8s, please reopen this issue if it still be a problem for you.

**Comment by cblade-gpt** [comment]
useless
