### ISSUE TITLE
[vcpkg search] Longer package names get trimmed with '...' too heavily when using vcpkg search, hurting discoverability.

### ISSUE THREAD

**Issue by ahsonkhan** [microsoft/vcpkg#16286]
Customers should be picking up the new Azure SDK for C++, which includes `azure-storage-blobs-cpp` and `azure-storage-files-shares-cpp`, instead of the older `azure-storage-cpp`.

However, due to the length, the new packages are not as discoverable, especially when they need to provide the full name to `vcpkg install`.
![image](https://user-images.githubusercontent.com/6527137/108431960-7abd8180-71f8-11eb-95ce-9ed2078e22ea.png)

Can we increase the column length so full package names are visible or structure vcpkg search in such a way to improves discoverability?

cc @ras0219-msft, @BillyONeal, @Jinming-Hu

**Comment by NancyLi1013** [comment]
Duplicated to #15446.

**Comment by ahsonkhan** [comment]
That issue is talking about the description, which is a bit more difficult to solve and up for debate. The visibility package name is a lot more critical to package acquisition and can be solved differently (in this case, simply be extending the column length a bit more).

Consider re-opening.

**Comment by NancyLi1013** [comment]
@ahsonkhan 

Thanks for your feedback about this issue. Of course, this issue is more easy to implement. I duplicate this issue to #15446 since that issue has contained this case. You can also add your comment in [discussion](https://github.com/microsoft/vcpkg/discussions/17880). I think it will be more easy to track the related issues together.
