### ISSUE TITLE
How do I specify a specific compiler to vcpkg install?

### ISSUE THREAD

**Issue by bhardwajs** [microsoft/vcpkg#16368]
Our current code only supports Clang. To do that, we pass `-DCMAKE_CXX_COMPILER=clang++` to CMake. However, when I use `vcpkg install` it goes back to system default compiler (g++ on some of the build agents.)

Is there an option to set default compiler for `vcpkg` steps to `clang++`. I can, of course, export compiler from the shell. But, I was wondering if there is another option.

Looking through the [docs ](https://vcpkg.readthedocs.io/en/latest/), didn't point to anything on these lines. Thanks!

**Comment by JackBoosY** [comment]
cc @strega-nil

**Comment by Neumann-A** [comment]
you want to set `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` in a custom triplet and set the compilers in the toolchain file. 
See https://github.com/Neumann-A/my-vcpkg-triplets for how to do it for windows.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by njk42** [comment]
Would it be possible to get a bit deeper description on how to make vcpkg compile with g++ instead of clang (the default) on macOS?

g++ 12 is installed and works fine when I ask cmake to use it for the main target, but vcpkg still uses clang to build dependencies and I end up with a ton of issues at the linking stage, especially with boost.

What is "the toolchain file" and where is it stored?  Is this something I create or is it already on my system somewhere?
Do I set VCPKG_CHAINLOAD_TOOLCHAIN_FILE to any particular value like a path string, or just set it to TRUE?

Thanks!

**Comment by dg0yt** [comment]
A toolchain file is a basic cmake thing. Read about it here:
https://cmake.org/cmake/help/v3.24/manual/cmake-toolchains.7.html
vcpkg provides a toolchain file for integration purposes, so a regular toolchain has to be chainloaded by the vcpkg file.

> vcpkg still uses clang to build dependencies and I end up with a ton of issues at the linking stage, especially with boost.

Without seeing any details, it is hard to see what is wrong. Do you use the vcpkg toolchain file correctly? Is it a port bug? 
Note that the typical gcc on macOS is just a frontend to Apple's clang.

Please don't continue discussion in this issue: Your questions are off-topic. Use https://github.com/microsoft/vcpkg/discussions
