### ISSUE TITLE
Add vcpkg into the 'PATH' variable.

### ISSUE THREAD

**Issue by Mr-Leshiy** [microsoft/vcpkg#16445]
Are you looking for to add vcpkg into 'PATH' env var during the bootstrapping process ?

**Comment by JackBoosY** [comment]
I don't think we need that, @ras0219 @ras0219-msft what do you think about?

**Comment by vicroms** [comment]
Maybe something like `vcpkg integrate PATH` could be implemented.

**Comment by Mr-Leshiy** [comment]
As for me the best solution to do it during the bootstrap process, just to modify windows and linux scripts with the additional argument. The way to update vcpkg directly seems more complicated.

**Comment by BillyONeal** [comment]
Given the dependence on the particular vcpkg tree in use I don't believe this is something we intend to investigate in the medium term; that doesn't mean we're opposed to it in concept. Note that registries will have an effect here.

**Comment by Mr-Leshiy** [comment]
@JackBoosY , @BillyONeal  Can I try to suggest an implementation of such feature, if the core team focused on the another things ? I mean will it be good if such functionality will be developed by the community ?

**Comment by BillyONeal** [comment]
> @JackBoosY , @BillyONeal Can I try to suggest an implementation of such feature, if the core team focused on the another things ? I mean will it be good if such functionality will be developed by the community ?

As I mentioned here, the team is indeed not interested in investing in this right now:

> Given the dependence on the particular vcpkg tree in use I don't believe this is something we intend to investigate in the medium term; that doesn't mean we're opposed to it in concept. Note that registries will have an effect here.

If someone submits a PR in the vcpkg-tool repo that implements such changes I'm not saying that we would reject it out of hand. However, I am saying that we believe it is going to be substantially tricky and that there needs to be substantial user experience design here that we don't see most contributors attempt. Without substantial demonstration of consideration of those edge cases it would be a long time before we could consider merging such a PR because that's where the complexity comes from.

You can always manipulate the path in your own shell :)
