### ISSUE TITLE
vcpkg_configure_make replaces the VCPKG_C_FLAGS overeagerly, which may cause compilation issues

### ISSUE THREAD

**Issue by wrobelda** [microsoft/vcpkg#16467]
**Describe the bug**
The `libtasn1` that I add as part of #14242 requires resetting the `VCPKG_C_FLAGS` back to `-g -O2`, which is what upstream sets by default in `ac_cv_prog_cc_g`. This is because `vcpkg_configure_make()` _overrides_ these flags and introduces additional optimizations which break the compilation. It's been a while since I last debugged it, so I can't pinpoint it specifically now to where in the code that happens, but this behavior is still very much in place.

I believe this can potentially cause not only issues like this particular one, which require pesky workarounds, but more importantly, can cause some more serious, hidden runtime misbehaving that will slip under the compiler's radar. 

**Environment**
- OS: macOS, Linux

**To Reproduce**
1. Edit libtasn1 port, comment-out the `set(VCPKG_C_FLAGS)` and `set(VCPKG_CXX_FLAGS)`
2. ./vcpkg install libtasn1
2. See the compilation error

**Expected behavior**
`vcpkg_configure_make` should at most add any additional flags required by vcpkg, but not replace/add any existing optimization flags.

**Failure logs** 

```
Undefined symbols for architecture x86_64:
  "_c_isdigit", referenced from:
      __asn1_expand_object_id in libtasn1.a(parser_aux.o)
      __asn1_check_identifier in libtasn1.a(parser_aux.o)
Undefined symbols for architecture x86_64:
  "_c_isdigit", referenced from:
      __asn1_expand_object_id in libtasn1.a(parser_aux.o)
      __asn1_check_identifier in libtasn1.a(parser_aux.o)
Undefined symbols for architecture x86_64:
  "_c_isdigit", referenced from:
      __asn1_expand_object_id in libtasn1.a(parser_aux.o)
      __asn1_check_identifier in libtasn1.a(parser_aux.o)
ld: symbol(s) not found for architecture x86_64
ld: symbol(s) not found for architecture x86_64
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by cenit** [comment]
mmm this is a slippery discussion. Hardcoded optimizations are very difficult do deal with, because they usually do not work with different compilers and different architectures. That's why in vcpkg it's preferred to embed them inside the toolchain and not inside port themselves. On the contrary, we often have to remove hardcoded flags from ports in order to let them build on arm or with unexpected compilers (msvc on windows for *nix common libs)

**Comment by Neumann-A** [comment]
probably related 
https://gitlab.com/gnutls/gnutls/-/issues/1033
https://gitlab.com/gnutls/libtasn1/-/issues/28
vcpkg just respects the cmake toolchain nothing more. The setting of VCPKG_C(XX)_FLAGS in the port is in this case also wrong since it does not respect user settings and is not configuration aware.

**Comment by wrobelda** [comment]
OK, so my understanding now is that this is more of a bad practice on the upstream side. 

> The setting of VCPKG_C(XX)_FLAGS in the port is in this case also wrong since it does not respect user settings and is not configuration aware.

Yeah, but this is the only way to get it to compile right now with vcpkg on platforms that are currently supported by the upstream (i.e. unaffected by the issues you linked to). I'd suggest that they stay as is and get revisited once the relevant fixes are provided upstream.
