### ISSUE TITLE
[libgit2[ssh]:x64-windows and libgit2[ssh]:x86-windows] build failure

### ISSUE THREAD

**Issue by Deputation** [microsoft/vcpkg#16497]
**Host Environment**
- OS: Windows 10 x64 20h2
- Compiler: revision

**To Reproduce**
`./vcpkg install libgit2[ssh]:x64-windows`
`./vcpkg install libgit2[ssh]:x86-windows`

**Failure logs** 
```
Building package libgit2[core,openssl,pcre,ssh,ssl,winhttp]:x64-windows...
-- Using cached C:/Users/Admin/source/repos/vcpkg/downloads/libgit2-libgit2-7f4fa178629d559c037a1f72f79f79af9c1ef8ce.tar.gz
-- Cleaning sources at C:/Users/Admin/source/repos/vcpkg/buildtrees/libgit2/src/af9c1ef8ce-4bbe42af5f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Admin/source/repos/vcpkg/downloads/libgit2-libgit2-7f4fa178629d559c037a1f72f79f79af9c1ef8ce.tar.gz
-- Using source at C:/Users/Admin/source/repos/vcpkg/buildtrees/libgit2/src/af9c1ef8ce-4bbe42af5f.clean
CMake Error at ports/libgit2/portfile.cmake:26 (message):
  Only one TLS backend (openssl,winhttp,sectransp,mbedtls) is allowed
Call Stack (most recent call first):
  ports/libgit2/portfile.cmake:42 (set_tls_backend)
  scripts/ports.cmake:128 (include)
```

**Comment by JackBoosY** [comment]
```
Only one TLS backend (openssl,winhttp,sectransp,mbedtls) is allowed
```

**Comment by dg0yt** [comment]
> ```
> Only one TLS backend (openssl,winhttp,sectransp,mbedtls) is allowed
> ```

You probably need instructions how to resolve the problem?

`winhttp` is selected on windows as SSL backend by the default `ssl` feature.
`openssl` is a dependency of the `ssh` feature.
To resolve the conflict between the backends, you must explicitly build without the `ssl` feature in order to remove `winhttp`. This shouldn't disable ssl, but only the selection of a default backend. (Untested.)
~~~
./vcpkg install libgit2[core,openssl,pcre,ssh]:x64-windows
~~~

**Comment by JackBoosY** [comment]
Since libgit2 already has multiple conflicting features, here I can only suggest that you use `libgit2[core, feature1, feature2]` to build it.

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
