### ISSUE TITLE
Qt: windeployqt don't work from CMake install scripts

### ISSUE THREAD

**Issue by ArseniyShestakov** [microsoft/vcpkg#1654]
I'm aware that ```windeployqt``` is pretty broken and this is why Vcpkg has own ```qtdeploy.ps1```, but I still wish this issues to be fixed one day. There basically few problems with using it:

- First of all there are different binary in debug directory version of libs and I find no good way to find it using ```find_program``` and no matter what paths I specify it's normal tool found. Might be there should be some way to find it or it's probably should be just removed.
- Another problem is that when I try to use it on release build I getting this output:
```Qt binaries in D:\DEV\vcpkg\packages\qt5_x86-windows\bin``` so basically while tool located in ```installed``` directory it's still looking for dependencies from ```packages``` directory. I could be wrong here, but I guess it's just might not work when Vcpkg is exported.

Surprisingly when I manually open command line, go into ```D:\DEV\vcpkg\installed\x86-windows\debug\tools\qt5``` and run windeployqt.exe from there it works, but when I try to run it using ```execute_process```  even with ```WORKING_DIRECTORY``` set it's just fail.

**Comment by ArseniyShestakov** [comment]
Just in case here is some CMake script example:
```
find_program(TOOL_WINDEPLOYQT NAMES windeployqt PATHS "${CMAKE_PREFIX_PATH}/tools/qt5")
find_program(TOOL_WINDEPLOYQT_DEBUG NAMES windeployqt PATHS "${CMAKE_PREFIX_PATH}/debug/tools/qt5")
if(NOT TOOL_WINDEPLOYQT AND NOT TOOL_WINDEPLOYQT_DEBUG)
	message(FATAL_ERROR "Could not find windeployqt")
endif()

install(CODE "
	if(\${BUILD_TYPE} STREQUAL \"Debug\")
	execute_process(
		COMMAND ${TOOL_WINDEPLOYQT_DEBUG} \"\${CMAKE_INSTALL_PREFIX}/VCMI_Launcher.exe\" -verbose=2
		WORKING_DIRECTORY ${CMAKE_PREFIX_PATH}/tools/qt5
	)
	else()
		execute_process(
			COMMAND ${TOOL_WINDEPLOYQT} \"\${CMAKE_INSTALL_PREFIX}/VCMI_Launcher.exe\" -verbose=2
			WORKING_DIRECTORY ${CMAKE_PREFIX_PATH}/debug/tools/qt5
		)
	endif()
")
```

**Comment by ras0219-msft** [comment]
>First of all there are different binary in debug directory version of libs and I find no good way to find it using find_program and no matter what paths I specify it's normal tool found.

I see; you're right that this is a difficult and different case than normal.

Normally, we assume that tools are "identical" between debug and release and therefore always deduplicate to the release versions. They run out-of-process so the usual CRT restrictions don't apply.

However, since windeployqt.exe is actually trying to deploy DLLs it's not totally immune to debug vs release.

>Surprisingly when I manually open command line, go into D:\DEV\vcpkg\installed\x86-windows\debug\tools\qt5 and run windeployqt.exe from there it works, but when I try to run it using execute_process even with WORKING_DIRECTORY set it's just fail.

This _might_ be caused by strange interactions with the environment variables and DLL loading, but I honestly have no idea. Qt's entire application model is quite complicated so it's hard to keep up without being a full-time Qt developer :).

Could you distill out some specific developer scenarios that don't work with `qtdeploy.ps1` that you're looking to solve by using `winqtdeploy`? Since we control the powershell script (and it's _significantly_ shorter), it's much easier to fix.

**Comment by ArseniyShestakov** [comment]
I can't give any useful feedback on ```qtdeploy.ps1``` since I didn't tried to integrate it. I would still prefer to not maintain Vcpkg specific code in our CMakeLists.txt since ```windeployqt``` (if working) should also be usable if someone decide to build our project with MinGW.

So I understand it's very low-priority issue, but Vcpkg would be a bit better if this eventually fixed.
