### ISSUE TITLE
Python 3.9.2 cannot run on windows 7

### ISSUE THREAD

**Issue by wasphin** [microsoft/vcpkg#16547]
In commit f9763b717eba12be38ea750406fe2a22a7ff00f6, python upgraded to 3.9.2, which does not work under Windows 7, this make all ports which require python fail to build.

So does Windows 7 still the supported OS as the README said?
> Prerequisites:
> * Windows 7 or newer

**Comment by NancyLi1013** [comment]
Hi @wasphin 

Thanks for posting this issue.

Since Python 3.9 has dropped support of Windows 7. So you cannot run Python 3.9.2 on Windows 7.

Please see the document here https://docs.python.org/3/using/windows.html#

For the description in README:
```
Prerequisites:

Windows 7 or newer
```
Most ports support Windows 7, currently only those ports requiring Python 3 cannot work on Windows 7.

**Comment by wasphin** [comment]
Some ports like `harfbuzz` only required python to run build tools, the version of python may not matter much, this kind of build failure is irrational. An option to use extern tools may be useful.

By now, I just make a link from python 3.8.8 to 3.9.2 to work around this.
```cmd
mklink /J python-3.9.2-x86 python-3.8.8-x86 
```
> Most ports support Windows 7, currently only those ports requiring Python 3 cannot work on Windows 7.

Maybe we can make this more clear in the README?

**Comment by NancyLi1013** [comment]
Hi @wasphin 

Thanks for your details. Since someone has added a feature `deprecated-win7-support` for `python3 `to support python 3.9 on Windows 7. Please see https://github.com/microsoft/vcpkg/pull/16420

In this case, users can still use python3 on Windows 7 via `python3[deprecated-win7-support]`.

**Comment by wasphin** [comment]
Hi, @NancyLi1013 

Thanks for the information, `python3[deprecated-win7-support]` has been successfully built under windows 7, but how to use the `python3[deprecated-win7-support]` to build `harfbuzz` in my case? If I understand right, `python3[deprecated-win7-support]` just build python 3.9.2, which can work under windows 7.

I think the title may have misled others, what I want is not to make python 3.9.2 worked under windows 7, but to build ports(e.g. `harfbuzz`) those do not require python 3.9.2.

**Comment by wasphin** [comment]
Hi @nabijaczleweli 

>  It seems `harfbuzz ` has no dependency of `python3`.

`harfbuzz` dependents on `meson` which in turn dependents on `python3`. So any version of `python` that can run `meson` should work for building `harfbuzz`. The version of `python3` does not have to be the latest, which is not compatible with Windows 7.

**Comment by nabijaczleweli** [comment]
(a) why are you atting me and (b) stop using Windows 7

**Comment by wasphin** [comment]
> (a) why are you atting me and

Sorry for that.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by JackBoosY** [comment]
Close this PR since #16420 merged.
