### ISSUE TITLE
[Question] FFmpeg library, How to turn off GPL? I only need LGPL v3.

### ISSUE THREAD

**Issue by ChinaChenMingQuan** [microsoft/vcpkg#16744]
Command -> vcpkg install ffmpeg[version3]:x86-windows

Log:
Starting package 1/1: ffmpeg:x86-windows
Building package ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,postproc,swresample,swscale,version3]:x86-windows.

Why is this so?
ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,postproc,swresample,swscale,version3]???
ffmpeg[gpl]!!!???

**Comment by NancyLi1013** [comment]
Hi @ChinaChenMingQuan 

Thanks for posting this issue.

Since `ffmpeg `has many default features, it will be installed automatically when you build other features or only build ffmpeg itself.

You can remove default features from CONTROL file.
` Default-Features: avresample, avcodec, avformat, avdevice, avfilter, postproc, swresample, swscale`

Then you can build feature `version3 ` via .`\vcpkg install ffmpeg[version3]:x86-windows` now.

**Comment by ChinaChenMingQuan** [comment]
@NancyLi1013.

Thanks, that's a great approach.
