### ISSUE TITLE
[opencv[ffmpeg]] build failure / wrong build

### ISSUE THREAD

**Issue by PhilLab** [microsoft/vcpkg#16741]
**Host Environment**
- OS: [e.g. Windows/Linux etc...] Windows
- Compiler: Visual Studio 16.9.1

**To Reproduce**
`./vcpkg install opencv[ffmpeg]:x64-windows`

**Failure logs** 
-

**Additional context**
The build does not use OpenCV's prebuilt FFMPEG: https://github.com/opencv/opencv/tree/master/3rdparty/ffmpeg

Instead it tries to build ffmpeg on its own which is not what you would expect. The OpenCV build string ([cv::getBuildInformation()](https://docs.opencv.org/master/db/de0/group__core__utils.html#ga0ae377100bc03ce22322926bba7fdbb5)) later reports:
```
...
Video I/O:
  DC1394: NO
  FFMPEG: NO (find_package)
...
```
and OpenCV fails to use ffmpeg.

**Possible cause**
- the vcpkg.json lists "ffmpeg" as dependency of the ffmpeg feature flag. This is wrong, as ffmpeg must actually not be built but the OpenCV prebuilt mechanism be used
- vcpkg explicitly prevents downloading during build: https://github.com/microsoft/vcpkg/blob/master/ports/opencv4/0001-disable-downloading.patch

**Comment by NancyLi1013** [comment]
Hi @PhilLab 

Thanks for posting this issue.

1.  `The build does not use OpenCV's prebuilt FFMPEG: https://github.com/opencv/opencv/tree/master/3rdparty/ffmpeg`
  vcpkg recommends to use the port that provided in vcpkg instead of the vendor dependencies. 
  Please see https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-vendored-dependencies

 2.  Could you please help confirm if you can install `opencv[ffmpeg]:x64-windows` successfully ?
 3.  Is this a problem when you use opencv? If yes, please help provide your project sample.

**Comment by JackBoosY** [comment]
Hi, does #16882 fix this issue?

**Comment by NancyLi1013** [comment]
Please try to update to the latest vcpkg to rebuild this.

Please feel free to reopen this issue if it is still a problem for you @PhilLab.
