### ISSUE TITLE
How to specify a version of a library

### ISSUE THREAD

**Issue by Sleepyowl** [microsoft/vcpkg#1681]
I cannot find any documentation on installing a specific version of a library.

Boost 1.65 breaks my build and I need to fall back to 1.64.

Is there a smart way to do that? 

Currently I just `git reset` vcpkg to the commit right before boost version bump, but that's ugly.

**Comment by ras0219-msft** [comment]
Vcpkg's approach to accessing previous versions is exactly what you've done; either using `git reset` to freeze yourself to the set of library versions you need or using `git checkout <sha> -- ports/boost` to pull a specific version of a specific port forward.

You might also find the `vcpkg export` command useful if you only need the old set of libraries for a single project and you'd otherwise like to have the newer boost version available. Simply clone a second copy of Vcpkg (at the old commit), then install all the libraries you'd like to have, then use `vcpkg export boost:x64-windows --nuget --zip` to get a fully shrink-wrapped bundle of your projects dependencies.

This approach minimizes the burden on library authors and maintainers (how many boost versions must you test against? We say: only the latest supported upstream release), though the user experience can be rough as you've experienced and we do want to improve it in the future.

**Comment by mloskot** [comment]
This should make it into the docs

**Comment by rchiodo** [comment]
How do you decide when to switch? I'm having the same problem. Boost 1.65 breaks the boost unit test adapter so I have to go backwards. 
It would be great if the command line could support different versions.

**Comment by eelstork** [comment]
If all you want is freezing packages at a given date, (I think that agreed upon ways to do relatively commonplace version-related things should make be documented, either in the FAQ or someplace versioning is addressed):
`git checkout (git rev-list -n 1 --before="2017-12-01" master)`
(assuming Powershell)

Library authors are entitled to make breaking changes; so, I think that a practical approach to getting a specific version of a library should be provided. If I understand the current approach to "pulling a specific version of a specific port" this might involve manually inspecting port version changes in the control file? Reasonably, is that something we'd like to automate? 

If so, would it be fine to avail an option for selecting a package version?

**Comment by chris1248** [comment]
I can't believe this. Microsoft put all this time in making a package manager and you CAN'T specify the version you want? ARe you freaking kidding me? What good is any package manager if you can't specify the version?

**Comment by Knitschi** [comment]
What happens if you have a dependency tree that requires one package in multiple verisons?
I think to fully solve the dependency versioning problem the package manager needs some additional features:

1. Provide a way for packages to specify the version of the depended on packages.
2. Provide a way for a package at version X to specify a list of versions that are compatible to X.
3. Allow multiple versions of the same package to be installed at the same time.
4. Provide some sort of algorithm that tries to reduce the amount of parallel used package versions by examining the compatibility specifications. To make that work for let's say CMake projects, the `find_package()` function would also need to support the same compatibility specification.

**Comment by kejxu** [comment]
from another perspective, `git reset` also reverts everything outside the `port` path (source for `vcpkg` itself). In that way, patches or updates to older versions of packages have to target the older `vcpkg` API/interface. This limits those packages from consuming newer helper functions (if any) provided by `vcpkg`.

**Comment by ChrisEt** [comment]
Same problem here, also with the `boost` framework. Current version is 1.71.0 but the project I'm building requires 1.69.0. 
Sure, I could simply go ahead and edit the 143 `CONTROL` files. Or I could `git reset` my clone to the version from 31st January 2019 (=1 year!) and hope that during this year no significant fixes or enhancements have been done to vcpkg!
Seriously, this can't be the solution, can it?

**Comment by cesss** [comment]
Really no PR for implementing this yet? I can understand that this feature was left at a side in the first **vcpkg** release, but it is so really necessary for complete the adoption of **vcpkg** in my projects, that I feel an imminent risk of modifying the source myself for my needs if I decide to adopt it.

And precisely, I prefer to avoid that, because I don't have the resources for maintaining a package manager at the moment, and moreover compatibility with older port files syntax should be preserved.

Nobody is working at implementing this? Really?

**Comment by axmeyer** [comment]
Same for me, how is this not on the roadmap by now?

I use vcpkg in multiple projects, and some of those projects require the same package, but at different versions. Now I have multiple vcpkg folders and need to keep track which folder is at which commit. Not really usable.

**Comment by JSoet** [comment]
Just adding another voice to this - just found out about vcpkg and was seriously considering using it, as we need to add some new libraries to our project and our existing method doesn't work that well.... but as I was reading through the documentation I was wondering how to specify a specific version and am surprised to see that that's not supported. Not being able to support specific versions basically makes this impossible for existing projects to adopt vcpkg, as often people can't afford to expend the effort to update all their libraries at once, and finding which specific commit supports the version that we need is not really viable.

**Comment by danperks** [comment]
Trying to make a Crow project but, being that it's no longer maintained, I need Boost pre-1.70. Seems like a simple enough feature to have.

**Comment by mukti5000** [comment]
Same here - vcpkg is great, and being able to specify package versions would make it even better!

**Comment by izosak** [comment]
Same here. I need to install an older version of OpenBLAS but can't do it using vcpkg!

**Comment by shogerr** [comment]
This is highly confusing for a user. You _must_ rollback the entire vcpkg repo? Man what a chore to even locate where in the commit history your update can be found. It's sometimes months before a new package version can be pulled int vcpkg anyhow. I guess the idea is to search the Github issues to locate when a change happened in libraries vcpkg tracks going forward?

**Comment by HoLue** [comment]
Nothing was done in the time since 2017 concerning this issue??? Such a "simple" feature request to install a specific version of a package... - or have I overseen something?

**Comment by mloskot** [comment]
@HoLue 
> Nothing was done in the time since 2017 concerning this issue??? 

https://devblogs.microsoft.com/cppblog/vcpkg-2020-04-update-and-product-roadmap/

**Comment by Ri0n** [comment]
Just took a look at the roadmap. I hope wrt versions they won't go Conan way which is very restrictive. For example you can't depend on openssl>=1.1 because openssl versions contain a letter after numbers and it breaks everything.

I prefer Gentoo Linux approach. They are way more tolerant to the all kinds of versions and allow to easily overwrite them

**Comment by bugproof** [comment]
@Ri0n what do you mean? https://conan.io/center/openssl/1.1.1g/?user=_&channel=_&revision=&os=&tab=overview

**Comment by Ri0n** [comment]
> is there any issue for that opened in conan repo?

IIRC yes. I also discussed this with Conan devs. And they said it's by design and instead OpenSSL developers should change their versioning to make version dependencies working. Currently Conan allows just exact version match for OpenSSL. For example a package may depend on openssl-1.1.1g but as soon as 1.1.1h is released a package maintainer has to change dependency in every package he uses or do some overwrite magic in its configuration files or just live with potentially insecure packages. There is no way to say "I want latest version from 1.1 branch".

I just hope vcpkg developers won't choose same way of versions handling.

**Comment by bugproof** [comment]
@Ri0n oh so you mean support for wildcards like 1.1.* or something like that which works for letters too

**Comment by Ri0n** [comment]
@bugproof rather about version comparison (>, >=, <, <=) and yes, which works for letters too.

**Comment by mnesarco** [comment]
What? A Package dependency manager without package version support? Don't you think that it is absurd?

**Comment by nenomius** [comment]
Next step will be a package manager without support for packages.

**Comment by dsazonoff** [comment]
3 years and no progress?

**Comment by IshitaTakeshi** [comment]
It's funny that everybody complains but nobody sends a pull request

**Comment by JSoet** [comment]
Thanks @vicroms for implementing this!!

**Comment by Bennett-Yang** [comment]
Thanks @vicroms!

**Comment by Coderx7** [comment]
hello everyone, 
What's the status on this? Is this finally implemented?

**Comment by TisonKun** [comment]
@vicroms did the RFC implement for manifest file way only? how can I specify the version from cli said sth. like

```
$ vcpkg install boost [version]
```

**Comment by vicroms** [comment]
At the moment versioning is not supported with CLI commands.

**Comment by mukti5000** [comment]
Hooray!

https://devblogs.microsoft.com/cppblog/take-control-of-your-vcpkg-dependencies-with-versioning-support/

**Comment by ras0219** [comment]
Links to the current documentation for versioning: https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md

**Comment by netpoetica** [comment]
Is there absolutely no way to say `vcpkg install mylib 1.0.0`, is that not a thing that vcpkg can do? I cannot find any documentation about this web wide

**Comment by yahuuu** [comment]
Foooour years have passed. We still don't have an easy way to specify the version？⊙▽⊙"

**Comment by shrddr** [comment]
It's really easy: just open the tutorial, create a json file, copypaste the contents, change the library names and versions, run vcpkg install, change the baseline string, run vcpkg install, discover you can't specify an exact version of a package (>= only), run vcpkg install, discover the version you need is not available for install, and finally just build the package manually

**Comment by tedyyu** [comment]
But still, versioning is not currently available for libraries installed via the command line (i.e. vcpkg install library_name commands). Miss npm install <package>@<version>.

**Comment by Bauxitedev** [comment]
So why exactly is this closed? You still can't install a specific version from the command line it seems.

**Comment by maxsargentdev** [comment]
Working with vcpkg for and thought I would chime in here with something I found useful, just in case people end up here via Google.

Locate the commit hash and checkout the commit:

```
commitHash=$(./vcpkg.exe x-history <package name> | grep <package version>#<package port> | awk '{print $NF}')
git -c advice.detachedHead=false checkout $commitHash
```

e.g.

```
commitHash=$(./vcpkg.exe x-history ffmpeg | grep 4.3.1#12 | awk '{print $NF}')
git -c advice.detachedHead=false checkout $commitHash
```

From here build your package as usual, for me I build and then export as nuget.

**Comment by idevlp** [comment]
> Working with vcpkg for and thought I would chime in here with something I found useful, just in case people end up here via Google.
> 
> Locate the commit hash and checkout the commit:
> 
> ```
> commitHash=$(./vcpkg.exe x-history <package name> | grep <package version>#<package port> | awk '{print $NF}')
> git -c advice.detachedHead=false checkout $commitHash
> ```
> 
> e.g.
> 
> ```
> commitHash=$(./vcpkg.exe x-history ffmpeg | grep 4.3.1#12 | awk '{print $NF}')
> git -c advice.detachedHead=false checkout $commitHash
> ```
> 
> From here build your package as usual, for me I build and then export as nuget.

No need for that

https://devblogs.microsoft.com/cppblog/take-control-of-your-vcpkg-dependencies-with-versioning-support/

> So why exactly is this closed? You still can't install a specific version from the command line it seems.
> 
> I have a Rust project that doesn't use CMake, so how exactly am I going to use the CMake dependency stuff from vcpkg?

They are working on it

**Comment by JeysonFlores** [comment]
October of 2021 and this problem doesn't have a proper solution..... One of the worst package managers ever made.

**Comment by ras0219-msft** [comment]
Just to update everyone: Versioning is fully available and supports pinning specific library versions.

https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md
