### ISSUE TITLE
[opengl] Fails on ARM64 Windows due to missing libraries in SDK

### ISSUE THREAD

**Issue by davidebeatrici** [microsoft/vcpkg#16921]
https://github.com/microsoft/vcpkg/blob/9f6157af4e5b04ab3cc63150a20b1bad901a7d0b/ports/opengl/portfile.cmake#L5-L6

```
CMake Error at ports/opengl/portfile.cmake:21 (message):
  Cannot find Windows 10.0.19041.0 SDK.  File does not exist: C:\Program
  Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\arm64\GlU32.Lib
Call Stack (most recent call first):
  scripts/ports.cmake:142 (include)
```

From https://developercommunity.visualstudio.com/t/cannot-link-opengl-programs-on-arm64/164107#T-N374601:
> It is recommended that those wishing to use OpenGL on Arm64 switch to the ANGLE open source project for roughly equivalent functionality.

This is technically not an issue in the `opengl` port, but rather in the ports that depend on it. Example:
https://github.com/microsoft/vcpkg/blob/9f6157af4e5b04ab3cc63150a20b1bad901a7d0b/ports/jasper/CONTROL#L5

Replacing `opengl` with `angle` seems to work just fine, however I believe the proper solution would be to rely on ANGLE only when OpenGL is not available.

**Comment by NancyLi1013** [comment]
Hi @davidebeatrici 

Thanks for posting this issue and also for your investigation.

Your suggestion sounds good. But it seems to be more complex to replace `opengl `with `angle`. For those libraries that depend on `opengl`, we need to add different dependencies according to different platforms. Besides this, we also need to change source codes. 

In my opinion, we should respect the upstream libraries if these ports only have one dependency of `opengl`. Since this is a problem from `opengl` itself, instead of the ports themselves.

**Comment by NancyLi1013** [comment]
Since this issue is similar to #3278. Let's track this issue there. Thanks for your attention to this issue.

**Comment by davidebeatrici** [comment]
No problem.
