### ISSUE TITLE
generate pdb file 

### ISSUE THREAD

**Issue by ad34** [Microsoft/vcpkg#1694]
Sorry to post an issue, but I cannot find how to generate .pdb files with vcpkg. is it possible? I m using openssl in my project and warnings when my project is linked

2>libeay32.lib(cryptlib.obj) : warning LNK4099: PDB 'lib.pdb' was not found with 'libeay32.lib(cryptlib.obj)' or at '***\lib.pdb'; linking object as if no debug info

**Comment by alexkaratarakis** [comment]
We believe having the ability to debug is vital to developers; therefore, we ALWAYS want to include pdb files (both for release and debug builds).
`vcpkg_copy_pdbs()` helps you with that by automatically figuring out which pdbs correspond to the dlls, so if you are not getting the pdbs there might be a bug in the portfile.

If you take a look at `$vcpkgroot\packages\openssl_x86-windows\bin` and `$vcpkgroot\packages\openssl_x86-windows\debug\bin`, you *should* see that each of the two dlls is accompanied by a pdb file. Is that not the case?

Each dll contains the information of the dll that corresponds to it. You can find it by running the following in a VS console: `dumpbin.exe /PDBPATH name.dll`
If there is a matching pdb file next to the dll, it will be picked up. If there is no matching file next to the dll, it will show you the path where the dll was originally built (in the `buildtrees\` directory). `vcpkg_copy_pdbs()` uses this command to detect the pdbs and copy them next to the dlls. 

Please try running this command on your openssl dlls and report the results. I find it strange that your error message implies that it is looking for "lib.pdb" because for me it is looking for "libeay32.pdb" and "ssleay32.pdb"

**Comment by ad34** [comment]
Thankf for your reply @alexkaratarakis 

I m using the **static** version of the libs I use with vcpkg . here is the list :  
 
openssl:x64-windows-static
zlib:x64-windows-static
libuv:x64-windows-static

I can't find any in the matching lib folders 

here is the dumpbin output of ssleay32.lib

Microsoft (R) COFF/PE Dumper Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.

Dump of file ssleay32.lib

File Type: LIBRARY

  Summary

          DD .bss
        F0C4 .data
       D0A8C .debug$S
        1C20 .debug$T
          CD .drectve
        28EC .pdata
        2E14 .rdata
       372E7 .text$mn
        3948 .xdata


debug info looks presnet but visual studio generates a lot of warnings when linking ( LNK4099 ) 

after opening the lib in an editor I found a reference to the lib.lib

F:\MyPath\External_SDKS\vcpkg-master\buildtrees\openssl\x64-windows-static-rel\openssl-1.0.2l\tmp32\lib.pdb

the lib.pdb file is still there, after copying it in the right folder I get a different warning

warning LNK4204: 'F:\MyPath\Output\lib.pdb' is missing debugging information for referencing module; linking object as if no debug info

**Comment by alexkaratarakis** [comment]
@ad34 
Sorry for the delay. Here are the repro steps I derived:

#### 1.   Build the library
`vcpkg install openssl:x64-windows-static`

#### 2. Enable integration
`vcpkg integrate install`

#### 3. Create a New Project in Visual Studio
Open Visual Studio -> New Empty Project ->Project1

#### 4. Specify the x64-windows-static triplet in the proj file
Right Click on Project-> Unload Project -> Right Click on Project -> Edit Project1 -> add the two Vcpkg lines at the end of the "Global" property group, like so:
```xml
  <PropertyGroup Label="Globals">
    <VCProjectVersion>15.0</VCProjectVersion>
    <ProjectGuid>{8C9C6181-406B-4EA4-A798-558B69EF73FD}</ProjectGuid>
    <RootNamespace>Project1</RootNamespace>
    <WindowsTargetPlatformVersion>10.0.15063.0</WindowsTargetPlatformVersion>
    <VcpkgTriplet>x64-windows-static</VcpkgTriplet>
    <VcpkgEnabled>true</VcpkgEnabled>
  </PropertyGroup>
```
Then Right Click on Project -> Reload Project.

#### 5. Create a source file with openssl code
 Right Click Source Files -> Add New Item -> Source1.cpp file. 
Paste the following example code:
```cpp
#include <stdio.h>
#include <openssl/bio.h>

int main()
{
    BIO *bio = BIO_new_fp(stdout, BIO_NOCLOSE);
    BIO_printf(bio, "%d", 1);
    BIO_free(bio);
    return 0;
}
```

#### 6.  Building
Select [Debug & x64] and Build the project.

### Outcome
I get no warnings at this point. This is because the lib knows the location that the pdb was originally placed in during build time, which (as you point out) is `vcpkg-master\buildtrees\openssl\x64-windows-static-rel\openssl-1.0.2l\tmp32\lib.pdb`. This means, the machine that did the actual build has pdbs available, but if you share the libs (e.g. via `vcpkg export`) then the pdbs will be absent. Of course, this is not ideal. Currently, we have a robust way to pick up pdbs for dlls, but not for static libs. I will be re-examining pdb-from-libs in light of this issue. 

If I remove the file, then I get the LNK4099 warnings. Now, if I place the `lib.pdb` in the appropriate directory: `vcpkg-master\installed\x64-windows-static\debug\lib`, then it is properly getting picked up from there and thus I get no warnings (note the directory that I am using in this test is `installed\`, not `packages\`). 

`lib.pdb` is a bad name here, so something needs to be done about that.

I am currently looking into solutions.

Does the above repro accurately represent your situation?

**Comment by madebr** [comment]
Hey, somewhat related. I guess.

When I compile a static lib and export it, the export does not contain any PDB.

```
vcpkg install bullet3:x64-windows-static
vcpkg export bullet3:x64-windows-static --raw
```

Including and linking to the files in the export results in the same warning as the OP.

**Comment by alexkaratarakis** [comment]
@ad34 
I added a patch to `openssl` that embeds symbols in static libs, instead of having them as a separate pdb. This will fix your issue. Relevant commits: 5a46f8e279f47229759dea9dd736d71ab74e04b9 f7b813dce8c8d67147e3b007e4c880f6a877f810

@ad34 @madebr 
In fact, previously we were handling pdbs only for dlls; static libs were more complicated so we had not handled them.
In light of this issue though, we are strongly considering always embedding symbols in static libs.

**Comment by ad34** [comment]
@alexkaratarakis , thanks it s all good for me. no more pdb warning at link. thank you so much !

**Comment by thierryba** [comment]
@alexkaratarakis I just tried with the latest version of vcpkg (0.89) and zlib static still generates pdbs.

**Comment by alexkaratarakis** [comment]
@thierryba 
I just tested and I don't see pdbs. Do you have more details?
Note that zlib's CMake always builds both dynamic and static flavors, and then we appropriately take only one of the two. The dynamic flavor has a pdb, the static version does not (at least as far as I see).

**Comment by ahmeb99** [comment]
Same, I don't see pdbs.

**Comment by autoantwort** [comment]
> I added a patch to openssl that embeds symbols in static libs, instead of having them as a separate pdb. This will fix your issue. Relevant commits: 5a46f8e f7b813d

Maybe this got lost over the years, currently I see the `ossl_static.pdb` file next to the *.lib files for openssl
