### ISSUE TITLE
[protobuf] Deprecation Warning for vcpkg_check_features()

### ISSUE THREAD

**Issue by diablodale** [microsoft/vcpkg#16988]
Minor warning of deprecated use of vcpkg_check_features() when building `protobuf` port.
Port continues to build successfully.

```
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Using source at C:/njs/vcpkg/buildtrees/protobuf/src/31c4d12c10-2e3bb0fe91.clean
CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.

      Please add the `FEATURES` keyword to the call.
Call Stack (most recent call first):
  ports/protobuf/portfile.cmake:16 (vcpkg_check_features)
  scripts/ports.cmake:142 (include)
```

### Solution

Minor update to `ports/protobuf/portfile.cmake:16` to use the `FEATURES` keyword.
🙂

**Comment by NancyLi1013** [comment]
Hi @diablodale 

Thanks for posting this issue.

Frankly speaking, this issue exists on many ports. Since `vcpkg_check_features()` has been updated recently. But we haven't implement the new requirement on those ports that use` vcpkg_check_features()` yet.

I will create a PR to fix this port. For other ports, we will fix this at the same time if there are other changes in those ports.
