### ISSUE TITLE
Support of Visual Studio 2013 builds

### ISSUE THREAD

**Issue by martin-s** [microsoft/vcpkg#1718]
Is there an interest in supporting build environments running Visual Studio 2013 (no VS 2015 or VS 2017 installed)? That means, vcpkg is still build with VS 2015 or higher, but the build toolchain supports VS 2013.
I did some testing with vcpkg and VS 2013 and the usual libs (zlib, png, tiff, boost) are generated fine.

**Comment by alexkaratarakis** [comment]
Thanks for the suggestion!

We are happy to see users using `vcpkg` to build with VS2013 and are willing to accept non-intrusive changes in mainline to make that smoother. However, supporting VS2013 (or below) will be burdensome to maintainers because they now have to also keep VS2013 in mind when making a port. This will detract from the overall quality of ports and could discourage potential maintainers from creating/updating ports.

There is a trade-off between what we have to explicitly support and not becoming over-encumbered, so for now we feel that VS2015+ strikes a good balance for explicit support.

**Comment by martin-s** [comment]
Ok, I'll check how intrusive the changes are. To adhere to the quality principle, make it an unofficial extension for expert users.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
