### ISSUE TITLE
[ffmpeg] fails to detect soxr

### ISSUE THREAD

**Issue by abique** [microsoft/vcpkg#17270]
**Describe the bug**

There is a soxr feature for ffmpeg, but this one fails to detect soxr and don't use it.

**Environment**
- OS: Macos and Windows

**To Reproduce**
1. `./vcpkg install ffmpeg[core,ffmpeg,ffprobe,mp3lame,vorbis,opus,soxr]`
2. You can see that in tools/ there will be no `soxr.dll` and that ffmpeg.exe will not be compiled with soxr even through it was compiled with --enable-soxr

I suspect that the build script fails to find soxr.

**Comment by NancyLi1013** [comment]
Hi @abique
 
Thanks for posting this issue. Confirmed this should be a bug on `ffmpeg`.

@mcmtroffaes 

I noticed the code in `configure `file:
`enabled libsoxr           && require libsoxr soxr.h soxr_create -lsoxr -lm`

And from build log, I found:
```
External libraries:
libsoxr                 mediafoundation         schannel
```
Since I'm not familiar with ffmpeg. I'm not sure where the problem is. Could you please help take a look?

**Comment by mcmtroffaes** [comment]
Soxr makes no sense without swresample, so I believe you're simply missing it from your features. The ffmpeg build script is clever enough to work out not to build soxr unless swresample is specified. For reduced confusion, perhaps swresample could be listed as a build dependency in the port?

For the record, in case it helps, it passes my own regression tests, including a small test program that verifies that the soxr engine is available:

https://ci.appveyor.com/project/mcmtroffaes/ffmpeg-msvc-build/build/job/y57ij6ge8nvo9y2c#L290
https://github.com/mcmtroffaes/ffmpeg-msvc-build/blob/master/test/swresample/find_swr_engine.cpp
