### ISSUE TITLE
FindOpenSSL finds debug libraries only

### ISSUE THREAD

**Issue by anatoly-spb** [microsoft/vcpkg#17395]
**Describe the bug**
I use the latest vcpkg and cmake to test manifest mode with OpenSSL library. As the result FindOpenSSL finds only debug libraries.

**Environment**
- OS: Windows
- Compiler: MSVC 19.27.29111.0

**To Reproduce**
1. mkdir test
2. cd test
3. create vcpkg.json
```
{
    "name": "vcpkg-openssl-issue",
    "version": "0.0.1",
    "dependencies": [
        "openssl"
    ]
}
```
4. create CMakeLists.txt
```
cmake_minimum_required(VERSION 3.20)

project(vcpkg-openssl-issue)

find_package(OpenSSL REQUIRED)
message(OPENSSL_FOUND:            ${OPENSSL_FOUND})
message(OPENSSL_INCLUDE_DIR:      ${OPENSSL_INCLUDE_DIR})
message(OPENSSL_CRYPTO_LIBRARY:   ${OPENSSL_CRYPTO_LIBRARY})
message(OPENSSL_CRYPTO_LIBRARIES: ${OPENSSL_CRYPTO_LIBRARIES})
message(OPENSSL_SSL_LIBRARY:      ${OPENSSL_SSL_LIBRARY})
message(OPENSSL_SSL_LIBRARIES:    ${OPENSSL_SSL_LIBRARIES})
message(OPENSSL_LIBRARIES:        ${OPENSSL_LIBRARIES})
message(OPENSSL_VERSION:          ${OPENSSL_VERSION})
```
5. create batch file:
```
set VCPKG_FEATURE_FLAGS=manifests
set VCPKG_DEFAULT_TRIPLET=x64-windows
mkdir build
call cmake -B build -S . -DVCPKG_TARGET_TRIPLET=%VCPKG_DEFAULT_TRIPLET% -DCMAKE_TOOLCHAIN_FILE=%VCPKG_HOME%/scripts/buildsystems/vcpkg.cmake 
```
6. set the VCPKG_HOME environment variable to vcpkg home directory
7. run the created batch file
8. you can see something like the following (output from my environment):
```
OPENSSL_FOUND:TRUE
OPENSSL_INCLUDE_DIR:D:/cmake/bug/build/vcpkg_installed/x64-windows/include
OPENSSL_CRYPTO_LIBRARY:D:/cmake/bug/build/vcpkg_installed/x64-windows/debug/lib/libcrypto.lib
OPENSSL_CRYPTO_LIBRARIES:D:/cmake/bug/build/vcpkg_installed/x64-windows/debug/lib/libcrypto.lib                                                                                                                                              
OPENSSL_SSL_LIBRARY:D:/cmake/bug/build/vcpkg_installed/x64-windows/debug/lib/libssl.lib
OPENSSL_SSL_LIBRARIES:D:/cmake/bug/build/vcpkg_installed/x64-windows/debug/lib/libssl.lib
OPENSSL_LIBRARIES:D:/cmake/bug/build/vcpkg_installed/x64-windows/debug/lib/libssl.libD:/cmake/bug/build/vcpkg_installed/x64-windows/debug/lib/libcrypto.lib
OPENSSL_VERSION:1.1.1j      
```

As you see that FindOpenSSL has found only debug library, but there are the both optimized and debug libraries in the ${CMAKE_BINARY_DIR}/vcpkg_installed/${VCPKG_TARGET_TRIPLET} 

**Expected behavior**
FindOpenSSL must find both optimized and debug libraries 

**Failure logs** 

**Additional context**

**Comment by PhoebeHui** [comment]
@anatoly-spb, thanks for reporting this issue! This is not relate to manifest mode, this issue also could repro at classic mode.

**Comment by anatoly-spb** [comment]
@PhoebeHui thank you for investigation the problem. Also I have observed danger behavior of FindOpenSSL related to search OpenSSL via windows registry:
```
set(_OPENSSL_ROOT_HINTS
    ${OPENSSL_ROOT_DIR}
    "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\OpenSSL (32-bit)_is1;Inno Setup: App Path]"
    "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\OpenSSL (64-bit)_is1;Inno Setup: App Path]"
    ENV OPENSSL_ROOT_DIR
    )
```
As for me this search list must be blocked during vcpkg searching process.

**Comment by cedral** [comment]
Anatoly's last response is confusing because it is not about this issue.  I am experiencing the same problem that was initially reported. I added a few more messages. Note that it says it doesn't find the debug libraries and then assigns the debug libraries to the release library setting. It's really odd. I am finding that vcpkg works better on linux than it does on windows because I am having multiple problems with it not selecting the right library and trying to use conflicting CRTs
'''
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
OPENSSL_FOUND:TRUE
OPENSSL_INCLUDE_DIR:C:/Development/vcpkg/installed/x64-windows/include
OPENSSL_CRYPTO_LIBRARY:C:/Development/vcpkg/installed/x64-windows/debug/lib/libcrypto.lib
OPENSSL_CRYPTO_LIBRARIES:C:/Development/vcpkg/installed/x64-windows/debug/lib/libcrypto.lib
OPENSSL_SSL_LIBRARY:C:/Development/vcpkg/installed/x64-windows/debug/lib/libssl.lib
OPENSSL_SSL_LIBRARIES:C:/Development/vcpkg/installed/x64-windows/debug/lib/libssl.lib
OPENSSL_LIBRARIES:C:/Development/vcpkg/installed/x64-windows/debug/lib/libssl.libC:/Development/vcpkg/installed/x64-windows/debug/lib/libcrypto.lib
OPENSSL_VERSION:1.1.1k
LIB_EAY_DEBUG:LIB_EAY_DEBUG-NOTFOUND
LIB_EAY_RELEASE:C:/Development/vcpkg/installed/x64-windows/debug/lib/libcrypto.lib
SSL_EAY_DEBUG:SSL_EAY_DEBUG-NOTFOUND
SSL_EAY_RELEASE:C:/Development/vcpkg/installed/x64-windows/debug/lib/libssl.lib
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Development/test/build
'''

**Comment by PhoebeHui** [comment]
Verified this issue with latest vcpkg, it looks fixed.
```
-- Running vcpkg install - done
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.29.30148.0
-- The CXX compiler identification is MSVC 19.29.30148.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: optimized;F:/vcpkgtest/test/build/vcpkg_installed/x64-windows/lib/libcrypto.lib;debug;F:/vcpkgtest/test/build/vcpkg_installed/x64-windows/debug/lib/libcrypto.lib (found version "3.1.0")
OPENSSL_FOUND:TRUE
OPENSSL_INCLUDE_DIR:F:/vcpkgtest/test/build/vcpkg_installed/x64-windows/include
OPENSSL_CRYPTO_LIBRARY:optimizedF:/vcpkgtest/test/build/vcpkg_installed/x64-windows/lib/libcrypto.libdebugF:/vcpkgtest/test/build/vcpkg_installed/x64-windows/debug/lib/libcrypto.lib
OPENSSL_CRYPTO_LIBRARIES:optimizedF:/vcpkgtest/test/build/vcpkg_installed/x64-windows/lib/libcrypto.libdebugF:/vcpkgtest/test/build/vcpkg_installed/x64-windows/debug/lib/libcrypto.lib
OPENSSL_SSL_LIBRARY:optimizedF:/vcpkgtest/test/build/vcpkg_installed/x64-windows/lib/libssl.libdebugF:/vcpkgtest/test/build/vcpkg_installed/x64-windows/debug/lib/libssl.lib
OPENSSL_SSL_LIBRARIES:optimizedF:/vcpkgtest/test/build/vcpkg_installed/x64-windows/lib/libssl.libdebugF:/vcpkgtest/test/build/vcpkg_installed/x64-windows/debug/lib/libssl.lib
OPENSSL_LIBRARIES:optimizedF:/vcpkgtest/test/build/vcpkg_installed/x64-windows/lib/libssl.libdebugF:/vcpkgtest/test/build/vcpkg_installed/x64-windows/debug/lib/libssl.liboptimizedF:/vcpkgtest/test/build/vcpkg_installed/x64-windows/lib/libcrypto.libdebugF:/vcpkgtest/test/build/vcpkg_installed/x64-windows/debug/lib/libcrypto.lib
OPENSSL_VERSION:3.1.0
-- Configuring done
-- Generating done
-- Build files have been written to: F:/vcpkgtest/test/build
```
