### ISSUE TITLE
[nlohmann-json] port name and cmake folder name mismatch

### ISSUE THREAD

**Issue by zeyangl** [microsoft/vcpkg#17411]
Currently this port generates two folders  under share/
![image](https://user-images.githubusercontent.com/1244606/115531761-bb547c80-a2c7-11eb-92d5-3eadd15d273b.png)

nlohmann-json is used for copyright and abi_info, while nlohmann_json is used for cmake files. Appear to be a simple typo.

**Comment by NancyLi1013** [comment]
Hi @zeyangl 

Thanks for posting this issue.

The current behavior is intended. Since the prefix of cmake files is `nlohmann_json`, we use `TARGET_PATH `in `vcpkg_fixup_cmake_targets` to redirected to `share/nlohmann_json`, which can make sure that `nlohmann-json` is found successfully via `find_package(nlohmann_json CONFIG REQUIRED)`.
https://github.com/microsoft/vcpkg/blob/807a7987612bbd702be9d9b8069124be62aff857/ports/nlohmann-json/portfile.cmake#L47

For `nlohmann-json`, it is the port name. Every port will install copyright to its own package name folder.
