### ISSUE TITLE
OpenMVG port not including sift.h properly.

### ISSUE THREAD

**Issue by adwodon** [microsoft/vcpkg#17457]
**Describe the bug**
OpenMVG port is not including sift.h properly.

**Environment**
- OS: x64-windows
- Compiler: revision

**To Reproduce**
1. ./vcpkg install openmvg[opencv]:x64-windows
2. Create a basic C++ command line project
3. `#include <openMVG_dependencies/nonFree/sift/SIFT_describer.hpp>` in main.cpp and build
4. Error because cant find sift with`#include <sift.h>`

**Expected behavior**
Should be able to build project

**Additional context**
Simple rememdy, the header file has been converted as sift is already vcpkg, see the following file:

https://github.com/microsoft/vcpkg/blob/master/ports/openmvg/build_fixes.patch

line 462:

```
-extern "C" {
-#include "nonFree/sift/vl/sift.h"
-}
+#include <sift.h>
```

this should be 
```
-extern "C" {
-#include "nonFree/sift/vl/sift.h"
-}
+#include <vlfeat\sift.h>
```

**Comment by NancyLi1013** [comment]
Hi @adwodon 

Thanks for posting this issue.

I will fix this soon.

**Comment by cenit** [comment]
did you link to the target unofficial::vlfeat::vl?

i can’t understand how openmvg does not have any problem but you have

**Comment by NancyLi1013** [comment]
@cenit 

I create a simple console application in Visual Studio 2017 to build, the same error as above:

`f:\test\vcpkg\installed\x64-windows\include\openmvg_dependencies\nonfree\sift\sift_describer.hpp(20): fatal error C1083: Cannot open include file: 'sift.h': No such file or directory`

I also checked that the path of `sift.h` from `vlfeat `is in `include/vlfeat` folder, instead of _include/_ folder.

So I think this is a bug in MSBuild project.

For CMake project, adding the link to target `unofficial::vlfeat::vl` can solve the problem. But I think it should not need to add the dependent target additionally.

**Comment by cenit** [comment]
> @cenit 
> 
> 
> 
> For CMake project, adding the link to target `unofficial::vlfeat::vl` can solve the problem. But I think it should not need to add the dependent target additionally.
> 
> 
> 
> 

why it should not need to link to target vlfeat if you use it?
to me it looks reasonable.

there are plenty of libraries that do not work automatically in msbuild without adding additional include dirs...

the fix you are proposing in the openmvg pr is incorrect in principle, because openmvg is fine. 
you should either install sift.h in include/ and not include/vlfeat or accept that you need to link targets and add an include dir in msbuild projects

**Comment by adwodon** [comment]
Here is the original file for openMVG:

[SIFT_describer.hpp](https://github.com/openMVG/openMVG/blob/develop/src/nonFree/sift/SIFT_describer.hpp)

Line 20 starts:

```
extern "C" {
#include "nonFree/sift/vl/sift.h"
}
```

With the openMVG package for x64-windows at least, these lines get changed to:

`#include <sift.h>`

openMVG installs sift with vcpkg but if you want to include it the path is:

`#include <vlfeat\sift.h>`

You can do a workaround in an VS project using the following additional include:

`$(VcpkgInstalledDir)x64-windows\include\vlfeat`

Yet why change that line to something incorrect for how vcpkg installs the sift package? There are no linkage issues, vcpkg just changes the file to something which is incorrect for how vcpkg will provide the include for sift.

**Comment by cenit** [comment]
I think you got it wrong, because vcpkg builds openmvg correctly without complaining about missing include files ;)

The fact is that if you target link vlfeat, as openmvg is doing, the folder `include/vlfeat/` is added to include path properly.
vlfeat in installed in an include subfolder as a best practice, but that should not touch depending ports. Here I had to patch openmvg anyway because it was unable to use an externally provided vlfeat, otherwise using its own and creating a conflict whenever installed.

Technically, if you move to <vlfeat/sift.h>, you are *breaking* openmvg, because it is target-linked to vlfeat, which adds include/vlfeat to the include path and so provides <sift.h> directly accessible. 
The "broken fix" works only because *other* target links are adding the include folder to the include path, making vlfeat/sift.h accessible.

Is it clearer now?

**Comment by cenit** [comment]
>openMVG installs sift with vcpkg but if you want to include it the path is:

nope, vlfeat installs sift.h.
OpenMVG does not install it, it is just using sift, not providing it from its own source base anymore

**Comment by adwodon** [comment]
Ah it seems you're correct, I just saw that the samples required the header and I didnt think vcpkg built the samples, but openMVG core does use the SIFT_describer_io.hpp which references it so you're right, it must work for vcpkg.

I think I understand now, it is reasonable to occasionally expect to manually add some additional includes for MSBuild.  Thanks for clarifying.

**Comment by NancyLi1013** [comment]
For MSBuild, it is clear now.

For CMake, it is still a bug. I will look into this and fix it soon. Since `opeenmvg `has the dependency of `vlfeat`, `vlfeat `has been linked to `openmvg `source. So it's unnecessary to link it again in the usage of `openmvg`.

**Comment by cenit** [comment]
there is not bug for cmake!
if you use openmvg, vlfeat is added as a dependency correctly, so if you target link openmvg, you have for free a target link to vlfeat.
Original user was not target linking to anything!

https://github.com/microsoft/vcpkg/blob/84e5852cfaa8e7875027e79a29a5534bb5d4a475/ports/openmvg/build_fixes.patch#L374

**Comment by NancyLi1013** [comment]
I checked `openmvg `source codes again and found that there is no target link to `vlfeat` in _nonFree/sift_ module.

Maybe this is the cause of this issue. But I'm not sure if it is necessary to add the target link to this module. Since I didn't find any target in this module. If there is no way to add it, your solution is reasonable.

**Comment by NancyLi1013** [comment]
Thanks for the clarification from @cenit. Seems this issue is clear now, I agree with the opinions from @cenit. Sorry for my previous confusion.
