### ISSUE TITLE
how to install Runtime library as mt

### ISSUE THREAD

**Issue by libxengine** [microsoft/vcpkg#17767]
I want to use DLL with MT runtime

**Comment by NancyLi1013** [comment]
Hi @libxengine 

Thanks for posting this issue.

I think you can add a custom triplet, such as `x64-windows-mt.cmake` like this:

```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE dynamic)
```

**Comment by libxengine** [comment]
thanks for you help

**Comment by libxengine** [comment]
i am create x86-windows-mt.cmake file
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE dynamic)

 .\vcpkg.exe install curl[openssl]:x86-windows-mt
libcurl is mt runtime but it is dependent library is not Mt....why...

**Comment by NancyLi1013** [comment]
Since you used a custom triplet, we cannot make sure all ports build successfully. As for the dependencies, whether they support the specific triplets is related with the ports themselves. If it is a bug for the port, we can post the detailed errors out in vcpkg or report to upstream if this is intended behavior from upstream.

**Comment by libxengine** [comment]
o
