### ISSUE TITLE
vcpkg export --zip ---> import into another vcpkg root

### ISSUE THREAD

**Issue by jeanga** [microsoft/vcpkg#1785]
Hi,

This is probably more a vcpkg documentation issue (or me being blind...).

I have been experimenting vcpkg export --zip feature and while the export side of the feature is frictionless, I find the "import" side of things more challenging (i.e. outside the --nuget realm).

If I simply extract the created package into my other vcpkg root (on a disconnected network which is my scenario), it will compile but features like vcpkg list or remove are not available.

Typically, I cannot easily tell which version/triplet I have installed.
Removing a library imported this way is also challenging.

I have found a workaround by manually tweaking the installed/vcpkg/status file but I cannot convince myself this was the intended way of importing an exported zip package.

Thank you for any help :-)

Jean

**Comment by ras0219-msft** [comment]
Hi @jeanga,

You're exactly right -- we don't currently have an intended way to re-import the exported package! The export command is specifically designed to make an immutable, read-only copy.

It does seem natural to be able to "re-import" and we are looking at that, however it's not a short-term goal.

If you'd like to go into more detail about your situation, maybe I can suggest an alternative.

**Comment by miurahr** [comment]
I also have same request  for my project in following scenario.

1. There is an OSS project that use AppVeyor as public CI test platform. (ex. github.com/miurahr/gdal)

2. Try to utilize vcpkg as dependencies libraries for building the project with MSVC

3. There are so many dependencies that cause vcpkg build taking a duration over 1 hour.

4. Free tier of AppVeyor test build limit a duration in 1 hour, so every build are failed.

If vcpkg support import feature, it help accelerate CI test against most recent dependent libraries.

1.  Export a snapshot installation and packages.

2. Import a export zip file.

3. purge outdated packages and install alll and additional dependencies.

4. start build an OSS project and test.

I'd like to propose the feature because,  when the OSS project contributors want to add a new driver and its dependency is on vcpkg, they will add a vcpkg command to install new dependency for a test.
It does not happen in current  read-only copy of vcpkg.

**Comment by martin-s** [comment]
This feature would be really helpful.
My requirement would be that an exported package (7z) should be able to reimport again. At least, a "vcpkg list" should correctly reflect the imported packages again.
In my opinion, should be a simple extraction and an update of the status file. Am i missing something?

**Comment by miurahr** [comment]
@martin-s to import correctry, we may need to restore not only binaries into /packages and  /installed folders but  also CONTROL and  BUILD_INFO files  , that is not in 7z, at least.

We can play PoC evaluation with extracting  and  manipulating 7z or zip file into  our repository by hand.

**Comment by miurahr** [comment]
@martin-s it may not be possible re-import from current exported archives. Details are commented  in https://github.com/Microsoft/vcpkg/pull/2947#pullrequestreview-101049179

It may be possible for us to propose a new export format for re-importing, and developing patch and Pull-Request may be welcome.

**Comment by martin-s** [comment]
I would just focus on the installed-folder in order to keep it simple. Hence, we have to take care of the status files in the vcpkg-folder etc. and keep them in sync with an existing vcpkg-folder.
Disadvantage would be that packaged-folder is skipped, but that is acceptable for me. If we can import the installed-folder and list all imported packages (vcpkg list), this would be ok.

**Comment by paul-michalik** [comment]
@miurahr Do you have the modifications on a branch? Can we pick it up somewhere?

**Comment by miurahr** [comment]
> @miurahr Do you have the modifications on a branch? Can we pick it up somewhere?

https://github.com/Microsoft/vcpkg/pull/2947/files

**Comment by miurahr** [comment]
Please find an attached patch files.

[0001-Refactoring-import-command.patch.txt](https://github.com/Microsoft/vcpkg/files/3076946/0001-Refactoring-import-command.patch.txt)
[0002-import-command-wip.patch.txt](https://github.com/Microsoft/vcpkg/files/3076947/0002-import-command-wip.patch.txt)

**Comment by danielaDESM** [comment]
@jeanga how exactly did you do it?
"I have found a workaround by manually tweaking the installed/vcpkg/status file but I cannot convince myself this was the intended way of importing an exported zip package."
Which status file, I cannot find it. Could you help me? I do have the exact same problem.
I would really appreciate your help :)

**Comment by jeanga** [comment]
The file is in "$(VCPKG_ROOT)\installed\vcpkg".
HTH

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.

**Comment by Coderx7** [comment]
is there any update in this regard?

**Comment by jeanga** [comment]
I think that this has been addressed with the new binary caching feature of vcpkg.
