### ISSUE TITLE
[vcpkg.io] Cannot find some ports in "Browse Packages"

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vcpkg#18050]
It seems that not all ports from `ports` folder can be find with the search option in `Browse Packages`.
Also this implementation: display like 10 packages and then click `show more` for a few more and then repeat is very annoying! 
How about: 
- a view with just the names of the packages/ports
- a paged view with paged numbers and ability to display more items per page
I may not remember the exact name of a package and alphabetical quick look up might help to find it which is very annoying with the current paging implementation.

**Comment by autoantwort** [comment]
Yes vcpkg.io is always outdated. I think they have to update the site manually every time. Idk why they don't have a cron job to do that.  
I have improved the site in vcpkg/vcpkg.github.io#47 and changed the default to 20, but implemented this functionality only because it was already there. On my machine it was fast enough to simply display all 1600 ports at the same time, but maybe this is a problem for smaller devices.  
> I may not remember the exact name of a package

Can you not simply use the search? I mean it searches not only in the port name. So if you search for example for `sql` it also finds ports like `libpq`

**Comment by JackBoosY** [comment]
Thanks for reporting this issue and make PR to fix that!
Please move this issue to https://github.com/vcpkg/vcpkg.github.io/issues.

Thanks.
