### ISSUE TITLE
vcpkg export --nuget: Cannot use several packages.

### ISSUE THREAD

**Issue by OpenCppCoverage** [Microsoft/vcpkg#1808]
Hello,

It seems we cannot use several packages created by ```vcpkg export --nuget``` in the same project.

Here are the steps to reproduce (You need to have nuget.exe in the current directory):

1. Run the following commands by replacing ```YOUR_FULL_CURRENT_FOLDER``` by the full path of your current folder:

```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
git fetch
git checkout ed63582f2c3a1756de967e95ee4793e96484db8d
.\bootstrap-vcpkg.bat 
mkdir packages

.\vcpkg install zlib:x86-windows
.\vcpkg export zlib:x86-windows --nuget --nuget-id=zlib --nuget-version=1.2.11.1
..\nuget.exe install zlib -Source YOUR_FULL_CURRENT_FOLDER\vcpkg -OutputDirectory packages

.\vcpkg install sqlite3:x86-windows
.\vcpkg export sqlite3:x86-windows --nuget --nuget-id=sqlite3 --nuget-version=3.19.1.2
..\nuget.exe install sqlite3 -Source YOUR_FULL_CURRENT_FOLDER\vcpkg -OutputDirectory packages
```

2. Create a new project with Visual Studio 2017 version 15.3:  

```
// main.cpp 
#include <zlib.h>
#include <sqlite3.h>

int main()
{
    return 0;
}
```

3. If I run the following commands in Visual Studio Package Manager Console,  ```sqlite3.h``` is not found
```
Install-Package zlib -Source "YOUR_FULL_CURRENT_FOLDER\vcpkg"
Install-Package sqlite3 -Source "YOUR_FULL_CURRENT_FOLDER\vcpkg"
```

3.(bis) where as if I swap the order, ```zlib.h``` is not found.
```
Install-Package sqlite3 -Source "YOUR_FULL_CURRENT_FOLDER\vcpkg"
Install-Package zlib -Source "YOUR_FULL_CURRENT_FOLDER\vcpkg"
```

I have the same behavior when I try to use at least 2 packages, the second package installed is not recognized. Is it an issue or done by design?

Note: Tested on Windows 10 x64 Creators Update.

OpenCppCoverage.

**Comment by alexkaratarakis** [comment]
This is by design.
You can only use one "instance" of `vcpkg`, be it a standard enlistment (via `vckg integrate`) or an exported one (via `vcpkg export`). 

The intention here is that all libraries your project needs (along with those libraries' dependencies) should be contained in a single nuget package; you cannot mix nuget packages. Otherwise there is no guarantee that the libraries were built against each other which is important in C++ (as opposed to C# for example). 

You can do:
```
.\vcpkg export zlib:x86-windows sqlite3:x86-windows --nuget --nuget-id=MyProjectNameDependencies --nuget-version=1.0.0
```

This will create a package that contains both zlib and sqlite (and their dependencies if they have any).

If you also need 64-bit builds, the nuget package can contain both:
```
.\vcpkg export zlib:x86-windows sqlite3:x86-windows zlib:x64-windows sqlite3:x64-windows --nuget --nuget-id=MyProjectNameDependencies --nuget-version=1.0.0
```

**Comment by OpenCppCoverage** [comment]
Hello,

Thank you for your quick answer.

**Comment by stfzy** [comment]
how to export all packages
