### ISSUE TITLE
[openal-soft] please don't remove AL_LIBTYPE_STATIC

### ISSUE THREAD

**Issue by DanielGibson** [microsoft/vcpkg#18098]
https://github.com/microsoft/vcpkg/blob/a3db16a4475b963cacf0260068c497fb72c8f3c0/ports/openal-soft/portfile.cmake#L65-L73
apparently replaces `AL_LIBTYPE_STATIC` with `1` or `0`, depending on whatever you build a static or dynamic lib.

Please don't do that - in the dedicated server (which has no sound) of [dhewm3](https://github.com/dhewm/dhewm3) (Doom3 source port) I set `AL_LIBTYPE_STATIC` and use stubs of the openal functions - but with the "system" openal headers.
That doesn't work with `AL/al.h` from vcpkg because `neo\sys\stub\openal_stub.cpp(143): error C2491: 'alSourceUnqueueBuffers': definition of dllimport function not allowed`.

Isn't there a better/cleaner way? Like making sure that `AL_LIBTYPE_STATIC` is defined when someone uses this lib (when built statically)?
If that's not possible, add something like
```c
#ifndef AL_LIBTYPE_STATIC
  #define AL_LIBTYPE_STATIC
#endif
```
to the header after `#ifndef AL_API` if it's built statically - or remove the `else() string(REPLACE "defined(AL_LIBTYPE_STATIC)" "0" AL_H "${AL_H}")` part so when your openal-soft is built dynamically `AL_LIBTYPE_STATIC` is still respected.

**Comment by PhoebeHui** [comment]
@DanielGibson, thanks for reporting this issue! we will take a look.

**Comment by PhoebeHui** [comment]
@DanielGibson, it looks you're trying to use the headers from dynamic build in your own static build project, you need build openal-soft with static triplet and reference the headers from static build. eg: ./vcpkg install openal-soft:x64-windows-static.

Please reference https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#triplet-selection to see details.

**Comment by PhoebeHui** [comment]
@DanielGibson, does this still be a question for you?

**Comment by DanielGibson** [comment]
Oh right, yes it is.

Note that vcpkg is no part of *my* build process - I maintain a Doom3 source port, [dhewm3](https://github.com/dhewm/dhewm3/), and tell people that if they want to build it, they need some libs, including openal-soft, installed. I don't care if they build those libs manually or install them with their Linux/BSD distro package manager or vcpkg on brew.sh or whatever.
Telling them that if they want to use vcpkg they also must install some static triplet *just to get working headers* would be kinda painful for everyone involved, *and* would require me to add complexity to my CMakeLists.txt to support and use one openal installation for the main game executable (dhewm3.exe) and another for the dedicated server executable (dhewm3ded.exe) - TBH, no idea if that's even possible with CMakes standard `FindOpenal.cmake`.

I consider `AL_LIBTYPE_STATIC` a feature of openal-soft's headers.
So far I could rely on it on every platform and AFAIK vcpkg is the only package manager that removes it - for example, all Linux package managers I'm aware of ship al.h like it is.

I would appreciate if you could make `AL_LIBTYPE_STATIC` work again, I think it would be very feasible to do this without breaking anything for your existing openal-soft users *(even ones who link it statically, which IMHO is a bad idea generally as 1. it's a license trap and 2. doesn't allow users to just replace the openal32.dll in case of sound issues in the future)*, see my suggestions in the initial post.

**Comment by PhoebeHui** [comment]
@DanielGibson, thanks for your response, I would talk this in our meeting.

**Comment by ras0219-msft** [comment]
Hi @DanielGibson, could you confirm that my understanding of the situation is correct:

1. You want the game (dhewm3.exe) to use a real copy of openalsoft, provided by the system, vcpkg, or elsewhere
2. For the server, you are trying to reuse the system headers without linking the original upstream library and instead linking a custom implementation (stubs). I assume this is because you are seeking to reuse object files between the two that have dependencies upon openalsoft.

I'll note that this approach is _extremely_ suspect and will completely break if openalsoft ever adds an exported global variable because those do not have a fallback signature hack that can work in both static and dynamic -- the `declspec(dllimport)` is mandatory if they are intended to be pull from a DLL. Fundamentally, the Windows platform is unfortunately not built to be agnostic of where a library comes from (static lib vs dll).

Vcpkg aims to support _all_ downstream buildsystems (including ones we haven't heard of), which means we prefer approaches like this that have no dependencies on any buildsystem capabilities -- if you can include headers, you get the right settings.

That said, the only point we can't compromise is "no macros set = correct behavior". I think we can remove the `else()` branch with a comment that this is explicitly a hack to support `dhewm3` and is in violation of our normal policies.

**Comment by DanielGibson** [comment]
Hi @ras0219-msft, thanks for looking into this!
You got it mostly right ;)
But:

> I assume this is because you are seeking to reuse object files between the two that have dependencies upon openalsoft.

This is not the case, I'm not reusing object files, everything gets rebuilt for the dedicated server, as both executables have different defines (like `-DID_DEDICATED`) set by the compiler.
But they're both built at the same time from the same CMakeLists.txt file, so there is only one imported libopenal (from `find_package(OpenAL REQUIRED)`) used by both.
I don't know if it would even be theoretically possible to import it twice with different settings, and even if it is I don't know how I should communicate to `find_package()` that I want to dynamically link in one case and statically link in the other, *in a way that works with standard `FindOpenAL.cmake` distributed by CMake on all kinds of platforms*.
And TBH, even if there was a way to do all this I really don't want to add that complexity, because the current code works with all package managers I'm aware of except for vcpkg and that whole dhewm3 CMakeLists.txt is complex enough as it is.
(As a side-node, I think the exported global variable would only be a problem if I actually used it, only openal-soft adding it would probably be ok?)

> That said, the only point we can't compromise is "no macros set = correct behavior". I think we can remove the else() branch with a comment that this is explicitly a hack to support dhewm3 and is in violation of our normal policies.

This is reasonable, and I think removing the `else()` branch should make everybody happy: For your "normal" users nothing will break *unless* they link dynamically and still set `AL_LIBTYPE_STATIC` (which I'd argue would be a clear bug in their setup and would break with any package manager or manually installed openal-soft), and weird usecases like dhewm3's that rely on the behavior of `AL_LIBTYPE_STATIC` even if generally linking dynamically will work as expected.

**Comment by ras0219-msft** [comment]
Yeah, you're right to veer far away from trying to pull in multiple copies of OpenAL in the same CMake build.

I'm sure you've thought about the problem space, but the fixes that I would suggest investigating would be:

1. Build your own replacement `openal32.dll` that is your no-op implementation. This also fixes the diamond problem of something like `dhewm3 -> SDL2 -> OpenALSoft`, because you're actually providing a "true" replacement.
2. Have your own copy of OpenAL headers to go along with your stubs. This could actually reduce maintenance burden and improve performance because you can reduce / remove things that aren't needed. Your dedicated server would be built against those headers and the client would be built against the external ones found via `find_package()`.
3. (not actually a suggestion, just an observation) If the project grew greatly in complexity with many more dependencies and more output programs, the viable solution set quickly narrows to needing two separate CMake buildtrees. There are a variety of ways to fuse those trees together with varying complexity levels.

**Comment by DanielGibson** [comment]
Thanks for your reply!

1. Is not an option, dhewm3.exe and dhewm3ded.exe live in the same directory, so the actual game would also use the dummy. Furthermore on non-Windows platforms one would have to mess with RPATH $ORIGIN or similar to use a lib (.so or .dylib or whatever) that's lying next to the executable (instead of some system library path). Having the stub as one .cpp file is also easier, of course.
BTW, SDL doesn't depend on OpenAL, and while openal-soft can use SDL for sound output, that doesn't cause a problem here. And due to `-fvisibility=hidden` there wouldn't be symbol clashes between openal_stub.cpp and a potentially indirectly linked libopenal anyway.
2. That would probably be most feasible, though I strongly prefer to just `#define AL_LIBTYPE_STATIC` for the dedicated server case, as that's even easier and that way I don't have to maintain the copied headers (in case I use new OpenAL extensions or new platforms not supported by the headers I originally copied)

Regarding **3.**, the complexity doesn't come from building two different executables, but mostly it's things like:
* Working around CMake bugs (e.g. `${CMAKE_SYSTEM_PROCESSOR}` being broken on Windows, known since at least 2014..)
* Supporting multiple platforms, including absolutely obscure ones like AROS
* (Optional) support for MFC tools (level editor etc) in the main executable

And, to a lesser degree:
* A few other optional (sometimes platform-specific) dependencies like libcurl and libbacktrace (whichs availability has to be checked)
* Supporting both MSVC and GCC/clang (though even gcc/clang support some different flags, esp. for warnings)
* Remaining compatible with old(er) CMake versions while using newer features if available, like `source_group(TREE ...`)
  - esp. for Linux it's useful to be compatible with older cmake versions for people using older LTS distros - or for building on an old distro (usually in a chroot) to create binaries that work on (basically) all distros of the same architecture


Cross-platform development is not always easy, especially with that many platforms and if you want to make it reasonably easy for users to build the code themselves :-)

**Comment by HarrievG** [comment]
Although @DanielGibson  as main maintainer does not have VCPKG in his buildprocess, I am actively using vcpkg in this project and will test any changes ASAP . just tag me and we get it done.

**Comment by BillyONeal** [comment]
@DanielGibson Can you check if https://github.com/microsoft/vcpkg/pull/20310 resolves your problem?

**Comment by HarrievG** [comment]
Yes. I'll test it over the weekend. And let you know.

**Comment by HarrievG** [comment]
@BillyONeal looking at the change,
Which removes the offending search and replace, this most definitely will work .

**Comment by HarrievG** [comment]
@DanielGibson fixed and tested in https://github.com/microsoft/vcpkg/pull/20310

**Comment by DanielGibson** [comment]
I haven't tested myself, but it looks good and I trust @HarrievG's word on it :)

**Comment by PhoebeHui** [comment]
The PR has been merged, please get latest source and try again.
