### ISSUE TITLE
After vcpkg builds hdf5 statically, my compiled DLL using hdf5 nevertheless depends on msmpi.dll...

### ISSUE THREAD

**Issue by macsinus** [Microsoft/vcpkg#1846]
...although vcpkg does seem to build msmpi statically.
Is this due to the following?
[https://support.hdfgroup.org/HDF5/faq/windows.html#vs-checklist](url)

**Comment by macsinus** [comment]
Specifically: 
> Using /MT or /MTd, requires advanced changes to the supplied HDF5 libraries.

**Comment by macsinus** [comment]
I was expecting everything to be statically linked (x86), tested OK on my PC (because I had msmpi.dll in SysWOW64) but crashed on a real 32-bit system...

**Comment by macsinus** [comment]
![grafik](https://user-images.githubusercontent.com/31918635/30651914-4b3bd6c6-9e27-11e7-9eb9-77a3fc1d569a.png)

**Comment by albertziegenhagel** [comment]
MSMPI is provided as shared binaries by Microsoft only. So vcpkg has no other option than to use the DLLs for the static triplet.

`\MT` and `\MTd` are about how to link to the CRT (C Run-Time) and have nothing to do with MSMPI specifically.

What exactly is the problem you are facing with the shared DLLs? Maybe it can be fixed in some other way?!

**Comment by macsinus** [comment]
Thanks for your answer!
I had thought that the MSMPI lib files could be linked statically.
I much prefer to deliver a single file, but it looks as if I'll just have to distribute MSMPI.DLL along with my DLL...
