### ISSUE TITLE
[hdf5] build failure

### ISSUE THREAD

**Issue by gdubost1** [microsoft/vcpkg#18656]
**Host Environment**
- OS: Windows10
- Compiler: not sure which one vcpkg picks . i have vs2019 , 2015 installed

**To Reproduce**
`./vcpkg install hdf5:x64-windows`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:83 (message):
  pkg-config error output:Package szip was not found in the pkg-config search
  path.

  Perhaps you should add the directory containing `szip.pc'

  to the PKG_CONFIG_PATH environment variable

  Package 'szip', required by 'hdf5', not found
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:184 (vcpkg_fixup_pkgconfig_check_files)
  ports/hdf5/portfile.cmake:121 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:139 (include)
  Package: hdf5:x64-windows
  Vcpkg version: 2021-05-05-b110959e13f562c2a17d7bd9e352e2dd8d6dc603

**Additional context**
works well for x86-windows

**Comment by dg0yt** [comment]
Can you rebuild port szip (remove + install)?

**Comment by gdubost1** [comment]
damn, it worked, thx a lot
I removed all versions of szip (x86 and x64)
and reinstaled szip x64
is it because i built it first as x86-windows the problem ?

**Comment by dg0yt** [comment]
I think you had an old version of szip installed for x64-windows but not for x86-windows. However, vcpkg didn't tell you to upgrade. Maybe the error message should be extended to suggest upgrading the dependencies of the current port (here: dependencies of simage).

(I added the szip pkgconfig module and requirement some weeks ago because otherwise its too hard to get the transitive usage requirements right for all possible configurations.)

**Comment by gdubost1** [comment]
anyway , thx . really appreciate .

**Comment by NancyLi1013** [comment]
Hi @gdubost1 

Thanks for posting this issue.

Seems you have solved your problem now. Please let me know if you have other concerns about this issue.

@dg0yt 

Thanks again for your help.

**Comment by NancyLi1013** [comment]
Closing this issue for now, please feel free to reopen this issue if it is still a problem for you.
