### ISSUE TITLE
utf8proc build failure

### ISSUE THREAD

**Issue by gamelaster** [microsoft/vcpkg#18801]
**Describe the bug**
utf8proc is built as static library by default, but `find_package(utf8proc CONFIG REQUIRED)` throws that package was not found.

**Environment**
- OS: Windows 10
- Compiler: MSVC 2019

**To Reproduce**
1. ./vcpkg install utf8proc
2. CMake lists:
```
find_package(utf8proc CONFIG REQUIRED)
target_link_libraries(project PRIVATE utf8proc)
```

**Failure logs** 
```
  Could not find a package configuration file provided by "utf8proc" with any
  of the following names:

    utf8procConfig.cmake
    utf8proc-config.cmake
```

**Comment by PhoebeHui** [comment]
@gamelaster, thanks for reporting this issue, it doesn't work since the Upstream doesn't export cmake config and targets files, could you submit a request or PR to https://github.com/JuliaStrings/utf8proc?

CMake also doesn't provide findutf8proc.cmake, I think we can help provide a unoffical config and targets in vcpkg.

**Comment by gamelaster** [comment]
Hi @PhoebeHui ,

the unofficial config works perfectly! Thanks.
