### ISSUE TITLE
How to export environment variable to vcpkg env?

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#1887]
Currently the libfreenect2 port is not able to compile successfully with `ENABLE_CUDA=ON`, and it is because in it's CMakeLists it is referencing to some environment variables that exists in the normal environment but not in `vcpkg env`.

For example,

``````
STRING(REPLACE "\\" "/" NVCUDASAMPLES_ROOT "$ENV{NVCUDASAMPLES_ROOT}")
STRING(REPLACE "\\" "/" NVCUDASAMPLES8_0_ROOT "$ENV{NVCUDASAMPLES8_0_ROOT}")
``````

I think the correct way to solve this is while `vcpkg install cuda`, if it's successful, there should be a way to export the cuda related environment variables into `vcpkg env`. Can someone tell me how to do it?

**Comment by martin-s** [comment]
Does something like this help?
```
vcpkg_configure_cmake(
	OPTIONS
	-DNVCUDASAMPLES_ROOT=xy 
)
```

**Comment by jasjuang** [comment]
@martin-s Problem is in different computers the environment variable `NVCUDASAMPLES_ROOT` will be slightly different. So this approach wouldn't scale.

**Comment by ras0219-msft** [comment]
One option would be to get these out of the registry, if they're available. Otherwise, the current best option is to add them to the global whitelist:

https://github.com/Microsoft/vcpkg/blob/8704db578aadbadc8757bbb1d4acc73b7e382b20/toolsrc/src/vcpkg_System.cpp#L68-L108

Alternatively, are those values discoverable based on the results of `find_package(CUDA)`?

**Comment by jasjuang** [comment]
These values are not discoverable after `find_package(CUDA)`, in fact `find_package(CUDA)` relies on the environment variable `CUDA_PATH` in order to locate cuda.

I think adding them to the global whitelist is a great idea. I will test it out and submit a PR later if it works.
