### ISSUE TITLE
[GDAL] find package error

### ISSUE THREAD

**Issue by mathisloge** [microsoft/vcpkg#19116]
@dg0yt this might be more related to you. 

```
CMake Error at C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find GDAL (missing: GDAL_LIBRARY) (found version "3.2.2")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindGDAL.cmake:185 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  D:/dev/node-mapnik/build/vcpkg_installed/x64-windows/share/gdal/vcpkg-cmake-wrapper.cmake:28 (_find_package)
  D:/dev/node-mapnik/vcpkg/scripts/buildsystems/vcpkg.cmake:751 (include)
  plugins/input/ogr/CMakeLists.txt:3 (find_package)
```

In the end, it is this line `_find_package(${ARGS})`  in vcpkg-cmake-wrapper.cmake. 

If I comment it out, it all works fine and all libraries are discovered. 

PS: I couldn't figured it out why it complainted. If I add a `message(FATAL_ERROR ${GDAL_LIBRARY})` before `_find_package` I'm getting the path of the libraries. 
contents of `GDAL_LIBRARY`
```
optimized;D:/dev/node-mapnik/build/vcpkg_installed/x64-windows/lib/gdal_i.lib;debug;D:/dev/node-mapnik/build/vcpkg_installed/x64-windows/debug/lib/gdal_i_d.lib
```

**Comment by dg0yt** [comment]
I just found two issues with wrapper (while working on kealib) and know how to resolve them:
- GDAL_LIBRARY must be set as a cache variable before calling pristine FindGDAL.cmake. 
  Solves your issue.
- The wrapper must not touch target GDAL::GDAL on a second call to `find_package(GDAL)`.
  Solves errors from `target_link_libraries(GDAL::GDAL ...)` in the wrapper on the second call because the imported target was created in another directory. (This might be fixed in CMake 3.21 but the wrapper can be used with older CMake.)
