### ISSUE TITLE
[gtest] Error while linking against GTest as a static library with dynamic CRT in Release mode.

### ISSUE THREAD

**Issue by qis** [Microsoft/vcpkg#1982]
When I build `gtest` with the `x64-windows` triplet, projects can link to it in both, Debug and Release mode.

When I use the following triplet instead, projects can link to it in Debug mode but not in Release mode.

```cmake
set(VCPKG_TARGET_ARCHITECTURE x64) 
set(VCPKG_CRT_LINKAGE dynamic) 
set(VCPKG_LIBRARY_LINKAGE static) 
```

Here is the linker output:

```
2>Generating Code...
2>gtest.lib(gtest-all.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in compat.obj
2>gtest.lib(gtest-all.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in compat.obj
2>gtest_main.lib(gtest_main.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in compat.obj
2>gtest_main.lib(gtest_main.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in compat.obj
2>gtest.lib(gtest-all.obj) : error LNK2019: unresolved external symbol __imp__invalid_parameter referenced in function "bool __cdecl std::_Debug_lt_pred<struct std::less<unsigned long> &,unsigned long const &,unsigned long const &>(struct std::less<unsigned long> &,unsigned long const &,unsigned long const &,wchar_t const *,unsigned int)" (??$_Debug_lt_pred@AEAU?$less@K@std@@AEBKAEBK@std@@YA_NAEAU?$less@K@0@AEBK1PEB_WI@Z)
2>gtest.lib(gtest-all.obj) : error LNK2019: unresolved external symbol __imp__CrtDbgReportW referenced in function "void * __cdecl std::_Allocate(unsigned __int64,unsigned __int64,bool)" (?_Allocate@std@@YAPEAX_K0_N@Z)
2>C:\Workspace\test\build\msvc\Release\main.exe : fatal error LNK1120: 2 unresolved externals
```

This triplet works well with other libraries. Tested with `zlib`, `libpng` and `angle`.

PS: I was surprised that `angle` generates shared libraries under this triplet. This is a very welcome feature since ANGLE uses LGPL code if I'm not mistaken.

**Comment by ras0219-msft** [comment]
Hi @qis, I'm not able to reproduce the issue, but I suspect your linker error is caused by some mismatch in the integration process.

Here's what works for me:
- I made a new triplet called `x64-windows-static-md` with the settings you've listed
- `vcpkg install gtest:x64-windows-static-md`
- `vcpkg integrate install`
- I made a new project and edited the MSBuild:
```xml
<PropertyGroup Label="Globals">
...
<VcpkgTriplet Condition="'$(Platform)'=='x64'">x64-windows-static-md</VcpkgTriplet>
</PropertyGroup>
```
- I threw in some generic gtest code and added `#pragma comment(lib, "gtest.lib")` (because we can't auto-link gtest by default)

This works for x64 Release and Debug for me. The linker errors you're getting indicate that you're pulling the debug libraries for gtest even in release -- I suspect you may have just directly added them to your project properties and accidentally used the `debug\` ones in release mode?

**Comment by qis** [comment]
Thank you for looking into it, @ras0219-msft 

I should have said that it's a CMake package related problem since I also have the apropriate libraries under

`vcpkg\packages\gtest_x64-windows-native\debug\lib\manual-link`

and 

`vcpkg\packages\gtest_x64-windows-native\lib\manual-link`.

Let me give you an example project: https://github.com/qis/gtest-test

This is the relevant bit from `CMakeLists.txt`:

```cmake
enable_testing()
include(GoogleTest)
find_package(GTest REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE GTest::Main)
gtest_add_tests(TARGET ${PROJECT_NAME} WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
```

**Comment by JackBoosY** [comment]
Hi @qis , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.

**Comment by qis** [comment]
@JackBoosY We switched to opening CMake projects as a directory in VS instead of generating multi-config projects with CMake (sln) and opening them directly. This solved a few other minor annoyances too.

**Comment by JackBoosY** [comment]
@qis  If you want to use sln instead of CMake project, you need to use command to integrate vcpkg: "**.\vcpkg.exe integrate install**" and reopen Visual Studio.
If you want to use static library, you need to modify .vcxproj file. Here is [document](https://devblogs.microsoft.com/cppblog/vcpkg-updates-static-linking-is-now-available/) what you need to looking for.
