### ISSUE TITLE
[proj4] build failure

### ISSUE THREAD

**Issue by snakegis** [microsoft/vcpkg#19841]
**Host Environment**
- OS: ubuntu20.04
- Compiler: g++

**To Reproduce**
`./vcpkg install proj4:x64-linux`

i also changed triplets/x64-linux.cmake
set(VCPKG_LIBRARY_LINKAGE static) to set(VCPKG_LIBRARY_LINKAGE dynamic)

**Failure logs** 
```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: */vcpkg-master/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j7
    Working Directory: */vcpkg-master/buildtrees/proj4/x64-linux-dbg
See logs for more information:
      */vcpkg-master/buildtrees/proj4/install-x64-linux-dbg-out.log
Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/proj4/portfile.cmake:55 (vcpkg_cmake_install)
  scripts/ports.cmake:140 (include)
```
install-x64-linux-dbg-out.log:
```
[1/207] cd */vcpkg-master/buildtrees/proj4/src/7.2.1-8a72a3c582.clean/data && *vcpkg-master/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/bin/cmake -DALL_SQL_IN=*/vcpkg-master/buildtrees/proj4/x64-linux-dbg/data/all.sql.in -P */vcpkg-master/buildtrees/proj4/src/7.2.1-8a72a3c582.clean/data/generate_all_sql_in.cmake
[2/207] cd */vcpkg-master/buildtrees/proj4/x64-linux-dbg/data && */vcpkg-master/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/bin/cmake -E remove -f */vcpkg-master/buildtrees/proj4/x64-linux-dbg/data/proj.db && */vcpkg-master/installed/x64-linux/tools/sqlite3 -init */vcpkg-master/buildtrees/proj4/x64-linux-dbg/data/all.sql.in */vcpkg-master/buildtrees/proj4/x64-linux-dbg/data/proj.db .quit && */vcpkg-master/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/bin/cmake -E copy */vcpkg-master/buildtrees/proj4/x64-linux-dbg/data/proj.db */vcpkg-master/buildtrees/proj4/x64-linux-dbg/data/for_tests
FAILED: data/proj.db */vcpkg-master/buildtrees/proj4/x64-linux-dbg/data/proj.db 
cd */vcpkg-master/buildtrees/proj4/x64-linux-dbg/data && */vcpkg-master/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/bin/cmake -E remove -f */vcpkg-master/buildtrees/proj4/x64-linux-dbg/data/proj.db && */vcpkg-master/installed/x64-linux/tools/sqlite3 -init */vcpkg-master/buildtrees/proj4/x64-linux-dbg/data/all.sql.in */vcpkg-master/buildtrees/proj4/x64-linux-dbg/data/proj.db .quit && */vcpkg-master/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/bin/cmake -E copy */vcpkg-master/buildtrees/proj4/x64-linux-dbg/data/proj.db */vcpkg-master/buildtrees/proj4/x64-linux-dbg/data/for_tests
SQLite header and source version mismatch
ninja: build stopped: subcommand failed.
```

**Comment by JackBoosY** [comment]
```
SQLite header and source version mismatch
```

**Comment by snakegis** [comment]
thanks for your comment, not working, re-installed sqlite3 to version 3.35.5 in system, still get this error message.

**Comment by JackBoosY** [comment]
Can you please provide the config log _config-x64-linux-dbg-out.log_ ?

**Comment by JafarAbdi** [comment]
@snakegis I have a similar problem, and it's due to linking sqlite3 as a shared library where the linker is picking the system installed one rather than the one built by vcpkg

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by danpat** [comment]
It's still sometimes an issue.  Here some more detail on what's going on on my Linux Ubuntu system in our CI environment, to give a bit more detail to what @JafarAbdi described:

  1. I have a system-wide installed sqlite3 library installed via apt
  2. I'm building my vcpkg packages with `set(VCPKG_LIBRARY_LINKAGE dynamic)`
  3. `vcpkg` is trying to build PROJ4 - it correctly identifies that it needs to use the vcpkg-supplied `sqlite3` binary via `-DEXE_SQLITE3=/root/project/build/vcpkg_installed/x64-linux/tools/sqlite3`
  4. However, because I've done shared linkage, that `sqlite3` binary is finding the system-installed `libsqlite3.so` and the `SQLite header and source version mismatch` error is printed when you try to run the executable:

```sh
root@d73f197c0a90:~# ldd /root/project/build/vcpkg_installed/x64-linux/tools/sqlite3 | grep sqlite
	libsqlite3.so => /lib/x86_64-linux-gnu/libsqlite3.so (0x00007f936ebfe000)
root@d73f197c0a90:~# /root/project/build/vcpkg_installed/x64-linux/tools/sqlite3
SQLite header and source version mismatch
2024-01-30 16:01:20 e876e51a0ed5c5b3126f52e532044363a014bc594cfefa87ffb5b82257ccalt1
2025-05-07 10:39:52 17144570b0d96ae63cd6f3edca39e27ebd74925252bbaf6723bcb2f6b4861fb1
```

This same error shows up in the PROJ4 build logs when `vcpkg` tries to build PROJ4 because part of that build process tries to execute the `sqlite3` binary.

 A simple `export LD_LIBRARY_PATH=/root/project/build/vcpkg_installed/x64-linux/lib` fixes the issue in a shell:

```sh
root@d73f197c0a90:~# export LD_LIBRARY_PATH=/root/project/build/vcpkg_installed/x64-linux/lib
root@d73f197c0a90:~# ldd /root/project/build/vcpkg_installed/x64-linux/tools/sqlite3 | grep sqlite
	libsqlite3.so => /root/project/build/vcpkg_installed/x64-linux/lib/libsqlite3.so (0x00007f280da7b000)
root@d73f197c0a90:~# /root/project/build/vcpkg_installed/x64-linux/tools/sqlite3
SQLite version 3.49.2 2025-05-07 10:39:52
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite>
```

So my current feeling is that the fault here is actually `sqlite3` - I think the tools should probably have an RPATH set to avoid picking up the system-installed `sqlite3` library when `proj` tries to run it.  `sqlite3` is such a ubiquitous system library that it's not really viable to remove it.

Interestingly, on our macOS build, it doesn't fail, and it seems that the vcpkg-supplied `sqlite3` binary _does_ have an RPATH set to the `vcpkg_installed` directory which causes it to load the right shared `libsqlite3.dylib`:

```sh
$ otool -L vcpkg_installed/arm64-osx/tools/sqlite3 | grep sqlite
	@rpath/libsqlite3.dylib (compatibility version 0.0.0, current version 0.0.0)
$ otool -l vcpkg_installed/arm64-osx/tools/sqlite3  | grep -A2 LC_RPATH                                                             
          cmd LC_RPATH
      cmdsize 32
         path @loader_path/../lib (offset 12)
```

My workaround for now for our Linux builds is to set `LD_LIBRARY_PATH=/root/project/build/vcpkg_installed/x64-linux/lib` before running `vcpkg` and `cmake`.
