### ISSUE TITLE
[blaze] Does not install cmake files needed for find_package(blaze) to work

### ISSUE THREAD

**Issue by hkaiser** [Microsoft/vcpkg#1996]
The portfile for the Blaze library does not install the generated files `blaze-config.cmake` and `blaze-targets.cmake` which makes it difficult to be discovered using `find_package(blaze)`. What would be the right way to include this library into my own projects?

**Comment by ras0219-msft** [comment]
Generally, the answer is to use `find_path()` and `find_library()`. However, I've also modified the blaze port to now install `blaze-config.cmake` in 4b66571c. It should work with:
```cmake
find_package(blaze REQUIRED)
target_link_libraries(hpx PRIVATE blaze::blaze)
```

However, due to some poor interactions with Debug/Release, I had to disable the automatic chainloading of LAPACK and Boost, so you'll need to `find_package()` those separately.

**Comment by parsa** [comment]
It now works for us. Thank you very much for resolving this. I suppose this issue can be closed now.
