### ISSUE TITLE
Add FastLZ

### ISSUE THREAD

**Issue by roalz** [Microsoft/vcpkg#20]
"free, open-source, portable real-time compression library"
URL: http://fastlz.org/
License: MIT

**Comment by adam4813** [comment]
It seems unlikely to add this from that repo as Google Code has shut down, and the "official" [github](https://github.com/ariya/FastLZ/commits/master) page was last commited to at the beginning of the copyright period (2007).

What I am suggesting is that this is actually a bad addition in the sense that is isn't anywhere near current or maintained at all.

**Comment by Orvid** [comment]
It's a reasonable library to add. The biggest reason there haven't been any changes to it is because it isn't in active development. There also haven't been any significant issues with it to need updating.

It has been relatively well battle-tested. PHP's memcached extension for instance supports (and defaults to) FastLZ as an alternative to zlib for compressing payloads.

**Comment by adam4813** [comment]
Fair enough. I can try to port this when I get a chance.
