### ISSUE TITLE
How to build `vcpkg` without telemetry code in binary?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#20097]
Not only telemetry is disabled by a flag, but also the binary of `vcpkg` contain nothing about telemtry, so that static analysis of antivrius tool will not warn anything without being signed.

**Comment by BillyONeal** [comment]
We removed easy ways to build the tool without telemetry when we moved building the tool out of bootstrap, since it isn't expected for users to need to build a new copy of the tool, we needed a way to disable telemetry without a rebuild: https://github.com/microsoft/vcpkg/commit/8414e15973097e70fe40149e922c402799804b3d

It seems unlikely that, even if we provided such a setting, that it would resolve your AV issues because the tool still contains HTTP bits in service of asset caching, binary caching, `x-download`, etc.

**Comment by playgithub** [comment]
I've removed the telemetry line by line as a try, it works.
https://github.com/playgithub/vcpkg-tool/tree/remove-telemetry

BTW I'm using Linux now, it will be helpful when porting in the future.
