### ISSUE TITLE
 C:\Temp\llvm-project\build\bin\llvm-tblgen.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

### ISSUE THREAD

**Issue by Hellolinu** [microsoft/vcpkg#20194]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.

**Comment by Hellolinu** [comment]
i am not not able to create build because of this issue ,

**Comment by PhoebeHui** [comment]
@Hellolinu, could you provide us more information? like repro steps, the environment and compiler you are using.

**Comment by Hellolinu** [comment]
I am using win10 x64 OS and trying to build clang which is compatible for Arm x86 platform . but when i am running python script getting this error .

**Comment by PhoebeHui** [comment]
@Hellolinu, could you provide us the repro steps?

**Comment by Hellolinu** [comment]
C:\Temp\llvm-project\build\bin>llvm-tblgen.exe
This version of C:\Temp\llvm-project\build\bin\llvm-tblgen.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

**Comment by PhoebeHui** [comment]
I need double confirm the following question:

1. Does llvm-tblgen.exe you used above built from vcpkg? I asked this due to vcpkg would put llvm-tblgen.exe to tools directory, not the bin directory. 
2. You built llvm with arm-windows triplet on win10?
3. You are running the arm-windows\tools\llvm-tblgen.exe on win10? If so, the error message is expected for me.

**Comment by Hellolinu** [comment]
No its not from vcpkg ,
my system is x64 win10 based pc i am trying to create build for Arm x86
Yes i am running on win10 , how to resolve this error could u pls help me to get the solution

**Comment by PhoebeHui** [comment]
> No its not from vcpkg ,

@Hellolinu, since you create the binary for arm x86, so you may need to copy all outputs to your arm machine and try again. Anyway, this is not right place to report the issue, you can report the issue to Upstream instead. Or you can ask an issue in https://stackoverflow.com/.

You can also try to build it via vcpkg, the command is './vcpkg install llvm:arm-windows', it will take some hours to build the port. Noted that it's a community triplet, so there is no guatantee that build success.
