### ISSUE TITLE
[jemalloc] update to 5.2.1

### ISSUE THREAD

**Issue by TENX-S** [microsoft/vcpkg#20227]
Library name: jemalloc

New version number: 5.2.1

> This release is primarily about Windows. A critical virtual memory leak is resolved on all Windows platforms.

**Comment by NancyLi1013** [comment]
Hi @TENX-S 

Thanks for posting this issue.

Seems there is no version 5.2.1 for `jemalloc`. Please see https://github.com/jemalloc/jemalloc-cmake/releases

So where do you get the new version 5.2.1?

**Comment by TENX-S** [comment]
https://github.com/jemalloc/jemalloc/releases

**Comment by NancyLi1013** [comment]
Thanks for your information. @TENX-S 

The repo you provided is not the same as the one that used in vcpkg. The current repo used in vcpkg supports cmake build. This might be the reason why the contributor chose this repo. 

We'll discuss if we can accept to update this to a new repo.

**Comment by NancyLi1013** [comment]
@TENX-S 

Would you like to report an issue to upstream to ask them to sync the latest changes to https://github.com/jemalloc/jemalloc-cmake?

Since we prefer using CMake to build a port when multiple buildsystems are available.
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#prefer-using-cmake

**Comment by TENX-S** [comment]
Looks like this repository https://github.com/jemalloc/jemalloc-cmake is abandoned. I'll use it in the old way.
