### ISSUE TITLE
How do I build from the command line without ever loading the Visual Studio GUI?

### ISSUE THREAD

**Issue by dulsi** [microsoft/vcpkg#20411]
### Discussed in https://github.com/microsoft/vcpkg/discussions/20235

<div type='discussions-op-text'>

The original problem is annoying but we figured we could get around it by building once in Visual Studio on each Jenkins build machine. However we are finding that is not working. We can remote desktop as the same user Jenkins is using. We can build from Visual Studio and the command line. But when Jenkins builds it fails to find any of the vcpkg installed libraries.

<sup>Originally posted by **dulsi** September 17, 2021</sup>
If I grab our source tree and try to build from the command line, it fails saying it can't find some cppunit header files. If I load the solution in Visual Studio, I can build from there. After doing that I can build from the command line without a problem. What is the GUI doing to enable this?</div>

**Comment by NancyLi1013** [comment]
Hi @dulsi 

Thanks for posting this issue.

msbuild.exe will through the following content 
```
<PropertyGroup >
    <VCLibPackagePath Condition="'$(VCLibPackagePath)' == ''">$(LOCALAPPDATA)\vcpkg\vcpkg.user</VCLibPackagePath>
  </PropertyGroup>
```
in` C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Common.props` file to find vcpkg related settings, such as the path for headers, lib and dll.
By default,  the value of `$(LOCALAPPDATA)\vcpkg\vcpkg.user` is null. So msbuild.exe will not find vcpkg.

After running `vcpkg integrate install`, vcpkg.user.targets file will be generated into `C:\Users\xxx\AppData\Local\vcpkg`, the content of this file as below:
```
     <Import Condition="Exists('F:\vcpkg\src\scripts\buildsystems\msbuild\vcpkg.targets') and '$(VCPkgLocalAppDataDisabled)' == ''" Project="F:\vcpkg\src\scripts\buildsystems\msbuild\vcpkg.targets" />
```
Then, msbuild.exe will find the settings of vcpkg when it is running. This settings will only exist in msbuild.exe itself instead of the project file or the running environment.

  >What is the GUI doing to enable this?

In your cases, reloading the project didn't change anything, it is just as msbuild.exe is changing. So you can build successfully.


  >How do I build from the command line without ever loading the Visual Studio GUI?

```
1.  .\vcpkg install cppunit
2.  .\vcpkg integrate install
3.  Open VS cmd and run the following command:
 msbuild.exe /m /t:rebuild /p:Platform=x86 /p:Configuration=Debug xxx.sln
```

**Comment by dulsi** [comment]
I think we found our issue. I had thought that you needed to run Visual Studio GUI to get it to recognize vcpkg. It appears I must have tried to build the 32 bit version of the solution and since the 32 bit version of the library wasn't installed it didn't work.

The problem with Jenkins seems to be that it alters the LocalAppData setting. By running vcpkg integrate install before building in Jenkins it setups the %LocalAppData%\vcpkg directory and everything runs.
