### ISSUE TITLE
`INTERFACE_INCLUDE_DIRECTORIES` is ignored in VS project

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#20473]
**Describe the bug**
LibA
```
/LibA/source/main.cpp
/LibA/deps/LibB/LibB.hpp # head only
```

main.cpp
```
#include <LibB/LibB.hpp>
```

For the `include` above to work, `/LibA/deps` is added to `INTERFACE_INCLUDE_DIRECTORIES` of LibA

When using LibA in a cmake project, no problem.
When using LibA in a VS project, `/LibA/deps` is not in include paths.

**Environment**
- OS: Windows
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30133 for x64

**Expected behavior**
`INTERFACE_INCLUDE_DIRECTORIES` should not be ignored in a VS project

**Comment by dg0yt** [comment]
Could you add how vcpkg is part of your issue?
You seem to want to use a vendored dependency located in LibA (`LibA/deps/LibB`), not a dependency LibB managed by vcpkg (`installed/<triplet>/include/libB`).

**Comment by playgithub** [comment]
LibB is head-only, the it is a private lib just for convenience, so just copied to to `LibA/deps`.
For LibA to build, `/LibA/deps` should be in include paths of project LibA.

**Comment by dg0yt** [comment]
So this is a VS question, not a vcpkg question.

**Comment by playgithub** [comment]
`CMakeLists.txt` of `LibA` has enough include paths in `INTERFACE_INCLUDE_DIRECTORIES` to use `LibA`,
but `vcpkg` doesn't provide all the include paths in `INTERFACE_INCLUDE_DIRECTORIES` of `LibA` to VS project

**Comment by dg0yt** [comment]
AFAIU you refer to `LibB/LibB.hpp` is in the *source* directory of LibA. 
vcpkg takes care that you can use the *installed* (aka binary) output of ports. So the owner of LibA must take care to properly install `LibB/LibB.hpp` along with LibA files, perhaps with proper exported configuration. If LibA uses CMake, it is actually a CMake question.

**Comment by playgithub** [comment]
Does `vcpkg` only find include files in `vcpkg/installed/include`?
And installed packages must meet this rule?
If yes, for `#include <LibB/LibB.hpp>` in `LibA` to work, two choices:
- port `LibB` to `vcpkg`
- patch `LibA` to `#include "LibB/LibB.hpp"` and make `LibA` find LibB locally

**Comment by dg0yt** [comment]
> Does `vcpkg` only find include files in `vcpkg/installed/include`?
> And installed packages must meet this rule?

Bascially, yes. (The path contains the triplet. For manifest mode, the location is relative to the user project.)
- The files in `installed` are all what is stored to, and restored from, the binary cache. 
  You cannot assume the existence of the source folder when vcpkg restores a binary artifact, or when working with exported packages.
- The `include` directory is the only one added for includes to VS.

> If yes, for `#include <LibB/LibB.hpp>` in `LibA` to work, two choices:
> 
>  * port `LibB` to `vcpkg`
>  * patch `LibA` to `#include "LibB/LibB.hpp"` and make `LibA` find LibB locally

AFAIU from your initial post, your problem is not "for `#include <LibB/LibB.hpp>` in `LibA` to work" *when building `LibA`*, but *for `#include <LibB/LibB.hpp>` in `AppXYZ` to work when using `LibA` because 
- it either doesn't install `LibB/LibB.hpp` to vcpkg's include directory (already in VS include path)
  (to be fixed by adding installation to port LibA, or by creating a port LibB).
- or it installs to another path which is not in VS
  (to be fixed by manually adding another path).

**Comment by playgithub** [comment]
> your problem is not "for #include <LibB/LibB.hpp> in LibA to work" when building LibA, but *for #include <LibB/LibB.hpp> in AppXYZ

Yes, for `AppXYZ` to work.

Now it's clear that for `AppXYZ` to use `LibA`, patches are needed.

Thanks for the clarification.
