### ISSUE TITLE
[harfbuzz] Add harfbuzzConfigVersion.cmake

### ISSUE THREAD

**Issue by strega-nil-ms** [microsoft/vcpkg#20567]
Currently, we don't publish a harfbuzzConfigVersion.cmake, despite publishing a harfbuzzConfig.cmake; we should start publishing that version info so that people can depend on a specific version or above (see #20557)

**Comment by mathisloge** [comment]
I've just looked intohttps://github.com/harfbuzz/harfbuzz/blob/4645c3b47c6e7a70f8d55eda543df1109e309347/CMakeLists.txt#L692 and harfbuzz don't publish a version. So that was my fault for specifying the version there. 
vcpkg behavior is correct. Bug in mapnik cmake. I'm currently fixing this upstream and adding in a new update PR for mapnik

**Comment by strega-nil-ms** [comment]
Ah, I was mistaken; I thought harfbuzz released the configVersion file with their CMake build system, but they don't seem to. I'm also planning on working on harfbuzz's CMake build system in my free time this week, so they may publish one soon.

**Comment by mathisloge** [comment]
@strega-nil-ms On mapnik, a user has just stumbled across the Harfbuzz configuration as well. It seems to be very broken in non-standard setups. This issue from neumann-a is quite interesting: https://github.com/harfbuzz/harfbuzz/issues/2653
