### ISSUE TITLE
OpenSSL 1.1.1f is not available in the list of available packages

### ISSUE THREAD

**Issue by mykhailopylyp** [microsoft/vcpkg#20600]
**Describe the bug**
I try to install OpenSSL 1.1.1f using following manifest file
```
{
    "name": "versions-test",
    "version": "1.0.0",
    "dependencies": [
        "openssl"
    ],
    "overrides": [{"name": "openssl", "version-string": "1.1.1f"}],
    "builtin-baseline": "ac030b40d53f820bad26148ed6ee46d6fd0f183d"
}
```

But I get the following message
```
EXEC : error : No version entry for openssl at version 1.1.1f. This may be fixed by updating vcpkg to the latest master via `git pull`.
1>Available versions:
1>    1.1.1l#1
1>    1.1.1l
1>    1.1.1k#8
1>    1.1.1k#7
1>    1.1.1k#6
1>    1.1.1k#5
1>    1.1.1k#4
1>    1.1.1k#3
1>    1.1.1k#2
1>    1.1.1k#1
1>    1.1.1k
1>    1.1.1j#2
1>    1.1.1j#1
1>    1.1.1j
1>    1.1.1i
1>    1.1.1h#5
1>    1.1.1h#4
1>    1.1.1h#3
1>    1.1.1h#2
1>    1.1.1h#1
1>    1.1.1g#1
1>    1.1.1g
1>    1.1.1d
1>    1
1>    0
...
``` 

Why 1.1.1f is not available even though I can see the corresponding tag and release in openssl repository?

**Environment**
- OS: Windows
- Compiler: msvc, visual studio 2019

**To Reproduce**
Use a manifest file in visual studio in order to install openssl 1.1.1f
```
{
    "name": "versions-test",
    "version": "1.0.0",
    "dependencies": [
        "openssl"
    ],
    "overrides": [{"name": "openssl", "version-string": "1.1.1f"}],
    "builtin-baseline": "ac030b40d53f820bad26148ed6ee46d6fd0f183d"
}
```

**Expected behavior**
OpenSSL 1.1.1f should be installed

**Comment by autoantwort** [comment]
> Are there instructions on how to add a new version of a package?

No, but you can use #19739 as reference

**Comment by strega-nil-ms** [comment]
Importantly, this is backfilling versions, and we currently don't have a standard for backfill versions; we should consider how we want to do this. We don't want to change `ports` to have an older version, so this needs discussion. Perhaps we can add a `backfill-versions` branch?

**Comment by ekilmer** [comment]
@strega-nil-ms Are there any more plans to discuss the issue of backfilling versions? A separate issue or discussion thread on the topic might be good for visibility and organization.

I could see the backfilling capability as a way to better accommodate packages that have more than one officially supported/maintained/updated version. Backfill versions could also be a way to continue fixing any packaging issues with older versions in a way that benefits everyone in the vcpkg community instead of users creating their own overlay ports or registries. Though, I'm unsure how we would test these changes in CI.

**Comment by JonLiu1993** [comment]
This version cannot be upgraded, I temporarily close this issue, if there is new information or other problems, you can open it at any time
