### ISSUE TITLE
[zeromq-libzmq] Built with /GL and /LTCG for static libraries

### ISSUE THREAD

**Issue by thxkiwi** [microsoft/vcpkg#20962]
/GL and /LTCG are known to be problematic. 

The specifics of the issue I have are that 
1. vcpkg is always using MSBUILD a specific location on C:
2. I'm building my actual library that uses vcpkg for dependencies using a different version of MSBUILD

Proposed solution is to not build with /GL and/or /LTCG when building static libraries. The msbuild triplet actually disables this but zeromq-libzmq is adding it specifically.

**Comment by thxkiwi** [comment]
zeromq/libzmq merged have merged my PR to master.

https://github.com/zeromq/libzmq/pull/4290

Anything I can do to help update the port?

**Comment by PhoebeHui** [comment]
@thxkiwi, thanks for reporting this issue to Upstream! could you create a patch for it? we're happy to accept the PR!

**Comment by thxkiwi** [comment]
@PhoebeHui the upstream project has merged their PR to master but have not released a new version (latest tag is still `v4.3.4`). I've inquired with upstream about their process for new tags/releases. 

Is there a preferred vcpkg process for handling cases where an upstream project has made a new official release tag but their master is ahead of the latest tag (also the tag used by vcpkg)?

**Comment by PhoebeHui** [comment]
@thxkiwi, we prefer to use the official release version, and patch the port if it has essential fix, since the develop branch does not guarantee you will get a worked version, so we avoid to use it, however, some libraries doesn't has release process, or it has no release version for a long time and may not release in future, we will choose the latest commit in master.

For zeromq, let's wait for the response from Upstream in https://github.com/zeromq/libzmq/issues/4315. Or you can create a patch for solving this problem if it takes a long time.

**Comment by ivanstepanovftw** [comment]
With clang and clang++ compilers on "Release" build type on Windows I am getting this error at the link time:
```
lld-link: error: unknown file type: CMakeFiles\libzmq-static.dir\src\zmq.cpp.obj
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by JackBoosY** [comment]
@ivanstepanovftw You should use clang triplet instead of x86 / x64 triplet on Windows.

**Comment by JackBoosY** [comment]
Waiting for the upstream publish the next release.
