### ISSUE TITLE
[vcpkg-tool] used vcvars needs to be included in the ABI

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#21292]
I am using the following triplet: https://github.com/Neumann-A/my-vcpkg-triplets/blob/master/x64-windows-llvm.cmake

It is a triplet which uses `clang-cl` external of VS by setting `set(VCPKG_ENV_PASSTHROUGH_UNTRACKED "LLVMInstallDir;LLVMToolsVersion")` which means the compiler hashes will stay the same if upgrading from VS2019 to VS2022. 
As such the version of the vcvars command vcpkg internally selects and which is out of the control of the user needs to be included in the ABI calculations. 

vcpkg should probably consider at least one of these variables:
```
UCRTVersion=10.0.19041.0
VCToolsVersion=14.30.30705
VisualStudioVersion=17.0
VSCMD_ARG_VCVARS_VER=14.3
VSCMD_VER=17.0.0
WindowsSDKLibVersion=10.0.19041.0\
```

**Comment by JackBoosY** [comment]
@BillyONeal what do you think about this?

**Comment by BillyONeal** [comment]
As I discussed with Neumann-A on Discord, I don't think this version number is any more relevant in the ABI hash than any other standard library change, and think if we really want to resolve this we need to include some form of fingerprint of the standard library itself.

**Comment by ras0219-msft** [comment]
I've spent a few hours thinking about how to do this efficiently and I've mostly hit a blank. In order to correctly find the standard library (if any!), we would need to assemble a complete compiler command line. We also would need to correctly handle cross compilation (no assuming you can actually link!) and freestanding / reduced standard library. At some future date, we may be able to leverage some unified `get_cmake_vars()` procedure, but I don't see an easy path in the near term. If we could rely on bit-for-bit reproducibility, we might build a well-known object file and hash it.

On the other hand, looking at the specifics of the situation, I think including one of the suggested version numbers _when using vcvars_ is actually a reasonable workaround until we can develop a more complex solution that fully takes into account all the possible toolchain configurations. The situation with LLVM via VS in a vcvars prompt is the only common case I'm aware of where the compiler and standard library would be disconnected _without custom flags_. In other cases, it looks like one would need to manually add path-bearing flags to the compiler, which firmly pushes you into the caveat emptor "if you're referencing paths, you need to manage binary caching on your own".

If we don't like any of the above version numbers, then I think hashing an MS-STL header from the paths in the vcvars prompt would also work -- my primary observation is that there is a reasonable subset of the general problem (only for the MS-STL and only in a vcvars prompt).

**Comment by Neumann-A** [comment]
hmm at least for windows/visual studio `find_file(yval_core.h)` and a regex search for:
https://github.com/microsoft/STL/blob/3c2fd04d441d46ec9d914d9cbb621a3bac96c3a5/stl/inc/yvals_core.h#L572-L574 ?

For the LLVM issues its probably really enough to know which version of the toolset is intended to be used.

**Comment by BillyONeal** [comment]
> I think including one of the suggested version numbers _when using vcvars_ is actually a reasonable workaround

I don't think it's a workaround at all, since there's no reason to consider the `VS 2019 16.9 -> VS 2022 17.0` release any different than `VS 2019 16.8 -> VS 2019 16.9` as far as standard library dependencies go. There are no major vs. minor standard library releases (at least, none that track Visual Studio version like this)

If we aren't going to at least detect and respond to VS update releases of that form I don't think adding stuff about it to the ABI hash and thus invalidating everyone's caches is a worthwhile trade.

For a more specific but less general solution we could search the include path for whichever files are  used as "config" files by the big 3 standard libraries and hash them. (`<yvals_core.h>` for microsoft/STL, I think libc++ uses `<ciso646>` for this purpose, don't know about libstdc++).
