### ISSUE TITLE
Problem with mongo-cxx-driver with Visual Studio 2017 and 1 byte struct alignment compiler setting 

### ISSUE THREAD

**Issue by antalyamark** [Microsoft/vcpkg#2144]
I installed the mongo-cxx-driver with the vcpkg successfully and made a new project with Visual Studio 2017 for a Visual C++ console application.
I compiled the test sample from the Mongo web site and it all worked perfectly.

I then for my project need to change the default compiler settings to use Struct Member Alignment of 1 byte which is the /Zp1 setting on the 
compiler options. When I do this the same code generates an error when a document is added to the database using the insert_one(). I believe the 
error is thrown in the bson.c file. My question is I do not think the compiler settings for my project should really effect this library. I 
need my main project to use the Struct Member Alignment of 1 since it passed Struct over the network wire to other services/programs which rely on
packed data so it would be very hard to change that.

**Comment by xoviat** [comment]
This not a place to ask questions about C++ libraries. This is a place to ask questions if:

1. There is some failure that is indirectly or directly caused by vcpkg
2. vcpkg itself experiences a failure
3. There is a feature that you would like to see

If vcpkg compiled and installed the library, and it works with the default alignment settings, you'll need to first talk to the library author and then after you've determined a fix there, possibly think about a fix in the portfile. But this is not the place to start.

**Comment by antalyamark** [comment]
Ok thanks for the reply will check with the mongo C++ guys!

**Comment by ras0219-msft** [comment]
This does have some interaction with vcpkg -- namely that we build all of our libraries with default settings (i.e. _not_ `/Zp1`). If you compile your project with `/Zp1`, it is highly likely to crash at runtime due to incompatibilities with the libraries you're using from vcpkg.

The correct fix here is to explicitly use `#pragma pack(push, mycode, 1)` and `#pragma pack(pop, mycode)` directly around _your_ structures that you want packed[1]. That way you continue to interpret the `mongo-cxx-driver` headers exactly as they were intended.

[1] https://msdn.microsoft.com/en-us/library/aa273913(v=vs.60).aspx
