### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by emastino** [microsoft/vcpkg#21842]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2022 Community Edition

**To Reproduce**
Hello everybody, 

I've ran into a seemingly not so unique situation where my antivirus software (Bitdefender) restricts the download of certain suspicious files when I use vcpkg to install omplapp. I am using PowerShell to run vcpkg . The installation of vcpkg seems to run smoothly but it is only when I try to use it that my antivirus gets upset. 
The exact command that gets me in trouble is: `vcpkg install omplapp`

**Failure logs** 
Bitdefender:
`C:\Users\USER\vcpkg\buildtrees\libjpeg-turbo\x86-windows-dbg\CMakeFiles\CMakeTmp\cmTC_a0c62.exe is infected with Gen:Variant.Razy.608090`

PowerShell Reports: 
`Error: Building package libpng:x86-windows failed with: BUILD_FAILED`

From what I gathered from [this thread](https://github.com/microsoft/vcpkg/discussions/19397) is that a work around is to deactivate the antivirus which seems highly suspicious. Has this issue been resolved since that post? 

Thank you!

**Comment by JackBoosY** [comment]
Yeah, this issue is common.
1. Some ports will generate tools containing specific operations, and these tools are not signed since,the upstream does not provide a certificate and signature process, so it will lead to anti-virus misjudgment.
2. In the cmake configuration, some cmake code will generate some temporary executables (as you can see `cmTC_a0c62.exe`) to determine the CPU architecture and compiler support options. These executable operations can also cause anti-virus misjudgments.

But please rest assured, since all the code is open source, you can check and analyze the risks yourself.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue hasn’t been updated in one month. Please reopen this issue if this is still a problem for you.
