### ISSUE TITLE
[folly] build failure

### ISSUE THREAD

**Issue by xjsxujingsong** [microsoft/vcpkg#22076]
**Host Environment**
- OS: Windows
- Compiler: vs2017

**To Reproduce**
.\vcpkg\vcpkg install folly:x64-windows-static

**Failure logs** 
vcpkg\buildtrees\folly\x64-windows-dbg\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
ninja: build stopped: subcommand failed.
vcpkg\buildtrees\folly\x64-windows-dbg\CMakeFiles\CMakeTmp\CheckSymbolExists.cxx(2): fatal error C1083: Cannot open include file: 'ucontext.h': No such file or directory
ninja: build stopped: subcommand failed.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did you install the latest version of folly? I cann't reproduce this issue locally. Could you please provide the log files?

**Comment by xjsxujingsong** [comment]
Hi Sorry for the late reply.
Here are the logs:

[CMakeError.log](https://github.com/microsoft/vcpkg/files/7775877/CMakeError.log)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/7775878/CMakeOutput.log)
[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/7775879/config-x64-windows-static-out.log)

**Comment by LilyWangLL** [comment]
Thanks for your reply. There are message in config-x64-windows-static-out.log:
```
CMake Error at CMake/FollyFunctions.cmake:95 (if):
  if given arguments:

    "C:/code/C++/vcpkg/buildtrees/folly/src/1.06.14.00-b189899f14.clean/folly/Benchmark.cpp" "MATCHES" "^C:/code/C++/vcpkg/buildtrees/folly/src/1.06.14.00-b189899f14.clean/folly/build/"

  Regular expression
  "^C:/code/C++/vcpkg/buildtrees/folly/src/1.06.14.00-b189899f14.clean/folly/build/"
  cannot compile
Call Stack (most recent call first):
  CMakeLists.txt:149 (REMOVE_MATCHES_FROM_LISTS)


-- Configuring incomplete, errors occurred!
```
The reason is your _VCPKG_ROOT_ path have **++** in _C:/code/C++/vcpkg_, you can create a new directory which doesn't contain character. I will confirm if this issue is a bug or by design soon.

**Comment by xjsxujingsong** [comment]
hi @LilyWangLL Thanks, it worked using a new directory.

**Comment by LilyWangLL** [comment]
If upstream has new change of this issue, I will reopen this issue.

**Comment by xjsxujingsong** [comment]
BTW, it seems to be caused by folly because other libraries required by folly can be installed and used successfully, like fmt or curl.

**Comment by dg0yt** [comment]
~~~
CMake Error at CMake/FollyFunctions.cmake:95 (if):
  if given arguments:

    "C:/code/C++/vcpkg/buildtrees/folly/src/1.06.14.00-b189899f14.clean/folly/Benchmark.cpp" "MATCHES" "^C:/code/C++/vcpkg/buildtrees/folly/src/1.06.14.00-b189899f14.clean/folly/build/"

  Regular expression
  "^C:/code/C++/vcpkg/buildtrees/folly/src/1.06.14.00-b189899f14.clean/folly/build/"
  cannot compile
Call Stack (most recent call first):
  CMakeLists.txt:149 (REMOVE_MATCHES_FROM_LISTS)


-- Configuring incomplete, errors occurred!
See also "C:/code/C++/vcpkg/buildtrees/folly/x64-windows-static-dbg/CMakeFiles/CMakeOutput.log".
See also "C:/code/C++/vcpkg/buildtrees/folly/x64-windows-static-dbg/CMakeFiles/CMakeError.log".
RegularExpression::compile(): Nested *?+.
RegularExpression::compile(): Error in compile.
~~~

Don't use `+` in your directory names. Folly stumbles over `C++` because it uses a raw filesystem paths as regular expressions. `+` has a special meaning.

**Comment by sfhacker** [comment]
This issue is from 2021!
