### ISSUE TITLE
use vcpkg to install caffe2 occur serious problem

### ISSUE THREAD

**Issue by how0723** [Microsoft/vcpkg#2215]
use vcpkg to install caffe2:x64-windows occur serious problem
ask why
the error information:
F1116 13:56:45.978482	1904 operator.h:608] You might have made a build error: the Caffe2 library does not seem to be linked with whole-static library option. To do so, use -W1,-force_load (clang) or -W1,—whole-archive (gcc) to link the C ffe2 library.
*** Check failure stack trace: ***

**Comment by willyd** [comment]
Did you use the /wholearchive linker flag in your project?

**Comment by JisongXie** [comment]
I encount the same problem, too. I use VS2015 on Win10, follow the installation instructions on Caffe2's website, and build successfully. Because I have a GPU, so I build with WITH_CUDA=ON and WITH_OPENCV=ON. I open Caffe2.sln in VS2015, build solution for ALL_BUILD and INSTALL. I try the tutorial in [pretrained.cc of leonardvandriel's caffe2_cpp_tutorial](https://github.com/leonardvandriel/caffe2_cpp_tutorial/blob/master/src/caffe2/binaries/pretrained.cc). I build a new project and use only the pretrained.cc, include neccessary paths and libs. But it go wrong with the same error message with you(@how0723). I use single step debug, and find it show up just when I call
`caffe2::GlobalInit(&argc, &argv);`
Also I have tried the caffe2::GlobalInit(); without command line, but it still cannot work.
Have anyone gotten the same error, and known how to solve it? It looks so annoying.

**Comment by JisongXie** [comment]
Ok, finally got the solution! Open the Caffe2.sln after I build caffe2,  find the predictor_verifier project, and set many of my project's properties like it. Then it works without this problem. This is mainly the problem of linking the library.
![image](https://user-images.githubusercontent.com/28192557/43892499-b1ac1fb2-9bfe-11e8-9f1f-36d2e393ebd0.png)
When you open the properties of preditor_verifier project, you can see how it link the library and what libs should you include.
![image](https://user-images.githubusercontent.com/28192557/43894842-fd2c22fa-9c05-11e8-905b-7ac5e94acbf5.png)

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
