### ISSUE TITLE
freeglut fails the coff post build checks

### ISSUE THREAD

**Issue by alexkaratarakis** [Microsoft/vcpkg#223]
And thus cannot be built.

**Comment by GeertVL** [comment]
Well I investigated it because I encountered the same error message. 

```Incorrect string (LIB HEADER_END) found. Expected: ` but found <blank>```

It occurs in coff_file_reader.cpp when we get the number of archive members (line 240). It gives back 331 members but we loop through it we only have 167 members and when you try to read (line 254) the archive_member_header  it returns an empty header and the call:

``` verify_equal_strings(HEADER_END, header_end.c_str(), HEADER_END_SIZE, "LIB HEADER_END");```

It fails and give the error message from above. 

Either the lib file is not really correctly done or the post test is not watertight and do not handle empty headers correctly (Is that allowed empty headers in a COFF file?).
What do you think?

**Comment by alexkaratarakis** [comment]
The implementation of the coff_file_reader was based on the documentation [here](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680547(v=vs.85).aspx). 
(pecoff.docx is the file)

As far as I can tell, it is not clear from the document if empty headers should be there. `freeglut` is the only library so far that we've seen fail the tests. But if it works and the produced binaries can be consumed without issues, then we should not block them from building. Therefore, we merged the changes from #288 (without the formatting changes). 

Thanks!
