### ISSUE TITLE
[glib] Build error "Host path separator (:) in path; this is unsupported."

### ISSUE THREAD

**Issue by jcc10** [microsoft/vcpkg#22812]
**Host Environment**
- OS: Pop!_OS (Ubuntu) 21.10
- Compiler: cmake version 3.18.4 (I think this is what you need?)

**To Reproduce**
`./vcpkg/vcpkg install glib`

**Failure logs** 
```log
digitalkitsune@pop-os:~/github/Alicevision$ ./vcpkg/vcpkg install glib
Computing installation plan...
The following packages will be built and installed:
    glib[core]:x64-linux -> 2.70.1#2
Detecting compiler hash for triplet x64-linux...
Restored 0 packages from /home/digitalkitsune/.cache/vcpkg/archives in 4.776 us. Use --debug to see more details.
Starting package 1/1: glib:x64-linux
Building package glib[core]:x64-linux...
-- Using cached glib-2.70.1.tar.xz.
-- Cleaning sources at /home/digitalkitsune/github/Alicevision/vcpkg/buildtrees/glib/src/glib-2-3e22263b95.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/digitalkitsune/github/Alicevision/vcpkg/downloads/glib-2.70.1.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch libintl.patch
-- Using source at /home/digitalkitsune/github/Alicevision/vcpkg/buildtrees/glib/src/glib-2-3e22263b95.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_host_path_list.cmake:43 (message):
  Host path separator (:) in path; this is unsupported.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_host_path_list.cmake:72 (z_vcpkg_translate_to_host_path_list)
  scripts/cmake/vcpkg_configure_meson.cmake:488 (vcpkg_host_path_list)
  ports/glib/portfile.cmake:43 (vcpkg_configure_meson)
  scripts/ports.cmake:142 (include)


Error: Building package glib:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+glib
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[glib]+Build+error
including:
  package: glib[core]:x64-linux -> 2.70.1#2
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 7baf7bc9f 2022-01-26 (5 hours ago)

Additionally, attach any relevant sections from the log files above.
```

**Additional context**
I actually need `opencv[eigen,ffmpeg,webp,contrib,nonFree,cuda]` and `openimageio[libraw,ffmpeg,freetype,opencv,gif,openjpeg,webp]` (among other things) as a build dependency and this is just one of it's dependency's.

**Comment by autoantwort** [comment]
Try removing the `:` from your `PATH` ;)

**Comment by jcc10** [comment]
Ok, but I'm on linux, what should I replace the separators with?

For refrence this is my path (newlines added for readability):
```
/home/digitalkitsune/github/meshroom/build/Linux-x86_64:
/usr/lib/cuda:/usr/lib/cuda/bin:
/home/digitalkitsune/github/emsdk:/home/digitalkitsune/github/emsdk/node/12.18.1_64bit/bin:/home/digitalkitsune/github/emsdk/upstream/emscripten:
/home/digitalkitsune/.deno/bin:
/home/digitalkitsune/.nvm/versions/node/v8.16.2/bin:
/home/digitalkitsune/.cargo/bin:
/home/digitalkitsune/.local/bin:
/home/digitalkitsune/bin:
/usr/local/sbin:/usr/local/bin:
/usr/sbin:/usr/bin:
/sbin:/bin:
/usr/games:/usr/local/games:
/snap/bin:
/home/digitalkitsune/.local/bin:
/home/digitalkitsune/.local/bin:
/home/digitalkitsune/.npm-packages/bin
```

**Comment by zpyatt** [comment]
I was thinking about posting a separate issue about this, as I've been following this for about a month, but there is finally activity again. 

I was able to get around this by modifying vcpkg_host_path_list.cmake (line ~ 21-41) to:

```cmake
       elseif("${VCPKG_HOST_PATH_SEPARATOR}" STREQUAL ":")
            set("${out_var}" "${lst}" PARENT_SCOPE)

            string(FIND "${lst}" [[\:]] index_of_host_path_separator)
        else()
```

This was just a quick hack to get things working, So far I haven't noticed anything else breaking, but I'm sure it's not correct.

I kept wondering why this only affects me at work and not at home, but this was broken in Nov. 2021, and I'm using an outdated version of vcpkg at home.

Also, this certainly isn't a port issue, it breaks a lot of packages. All of them that make direct/indirect calls to vcpkg_host_path_list, which includes all of the pkg_config, and meson ones (I think).

It's rather disconcerting more people haven't complained about this, apparently there aren't many Linux users, or they are using out-dated vcpkg.

Preventing the use of colons for paths certainly isn't an option, if you want to support Linux. It seems like there could just be a switch on platform to determine which separator to use, and ports need to use "VCPKG_HOST_PATH_SEPARATOR" instead of hard coding : or ;. But, I only dug deep enough to get it to work for my cases.

However, this is a major problem!!!

**Comment by dg0yt** [comment]
There are linux users and contributors, but they are not able to reproduce this issue. 

The function you point to tranforms a CMake list of directories (`/usr/local/bin;/usr/bin;/bin`) into a host path list (`/usr/local/bin:/usr/bin:/bin` for Linux). On you computer, the *input* CMake list already contains the host path separator (e.g. `/usr/local/bin;/usr/bin:/bin`). This indicates that this list couldn't be processed correctly in earlier functions.

Perhaps you should share the raw output of `echo "$PATH"`. Because what you shared above also contained the host path separator in some lines. You really need to check you `PATH`.

**Comment by BillyONeal** [comment]
The error message from `vcpkg_host_path_list` is saying "you tried to add a new element to the path that itself contains `:`, which isn't possible on *nix". 

https://github.com/microsoft/vcpkg/blob/5962cf5a3bfc2124e8de991a4e45a8edcb3b4c69/scripts/cmake/vcpkg_configure_meson.cmake#L489

I think the right fix is to change

```
vcpkg_host_path_list(APPEND ENV{PKG_CONFIG_PATH} "${pkgconfig_installed_dir}" "${pkgconfig_share_dir}" "$ENV{PKG_CONFIG_PATH}")
```

into:

```
vcpkg_host_path_list(APPEND ENV{PKG_CONFIG_PATH} "${pkgconfig_installed_dir}" "${pkgconfig_share_dir}")
if (NOT ENV{PKG_CONFIG_PATH} STREQUAL "")
    set(ENV{PKG_CONFIG_PATH} "$ENV{PKG_CONFIG_PATH}${VCPKG_HOST_PATH_SEPARATOR}ENV{PKG_CONFIG_PATH}")
endif()
```

or similar? It seems `$ENV{PKG_CONFIG_PATH}` likely already may have path separators in it.

/cc @strega-nil

**Comment by strega-nil-ms** [comment]
I think the correct thing is to just turn `vcpkg_host_path_list(APPEND ENV{PKG_CONFIG_PATH} "${pkgconfig_installed_dir}" "${pkgconfig_share_dir}" "$ENV{PKG_CONFIG_PATH}")` into `vcpkg_host_path_list(APPEND ENV{PKG_CONFIG_PATH} "${pkgconfig_installed_dir}" "${pkgconfig_share_dir}")`; you're already appending to `ENV{PKG_CONFIG_PATH}`, you don't need to do it again.

**Comment by BillyONeal** [comment]
Oh megaderp I didn't see that the variable was duplicated 😅
