### ISSUE TITLE
[cURLpp] Automatically link Ws2_32 and Crypt32

### ISSUE THREAD

**Issue by BullyWiiPlaza** [microsoft/vcpkg#22848]
**Is your feature request related to a problem? Please describe.**
When I'm statically linking to [cURLpp](https://github.com/datacratic/curlpp), I get linker errors until I resolve them by adding e.g.
```
#pragma comment(lib, "Ws2_32")
#pragma comment(lib, "Crypt32")
```
to my source code.

**Proposed solution**
Can the cURLpp port automatically link to those libraries on Windows so we don't have to take care of the linker libraries manually?

**Describe alternatives you've considered**
Adding the `#pragma comment` statements to my source code. However, finding the right libraries to link to can take some search engine effort and isn't immediately obvious.

**Additional context**
No.

**Comment by JackBoosY** [comment]
This is just a workaround becuase curlpp's cmake config has been added thoese system libraries.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by BullyWiiPlaza** [comment]
Hello @JackBoosY, after git pulling and bootstrapping vcpkg once again nothing has changed and I still need to place e.g. the pragma `#pragma comment(lib, "Crypt32")` into my code to successfully link as explained in the initial post. If you mean it won't be made work the way I expect then it's fine but the issue is not "solved" per se.

**Comment by JackBoosY** [comment]
The problem is that the msbuild integration does not document the system libraries and custom macros that the port needs to use. This resulted in the inability to automatically add these libraries to the link list and to automatically add custom macros to preprocessor commands when using the msbuild integration.
In the cmake integration, the port exports these system libraries, so there is no problem.
The good news is that we intend to fix the integration issue.
