### ISSUE TITLE
[vcpkg] Add field to control file which filters supported triplets

### ISSUE THREAD

**Issue by ras0219-msft** [microsoft/vcpkg#229]
From https://github.com/Microsoft/vcpkg/pull/189/files/7805bdff8cc38c83aaf2b5ea5ecc3042634fb017#r85587279 and elsewhere. This is useful for several ports, such as the TBB port (which currently only supports x64) and the PDCurses port (which currently only supports x86).

In contrast to [Debian's solution](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Architecture) to this problem, I believe that a blacklist-only solution is more appropriate for Vcpkg. This enables end-user extension and modification of triplets without sweeping changes across the ports tree to add the new triplet to every port with a whitelist.

**Comment by Orvid** [comment]
Perhaps more general set of independent whitelisting flags would work better than a blacklist approach? For example, (`32-bit Only`, `64-bit Only`), (`Dynamic CRT Only`, `Static CRT Only`), (`Dynamic Library Only`, `Static Library Only`), (`WinRT Only`, `Non-WinRT Only`) and then also a set of flags for actual CPU architectures, (`x86`, `x64`, `arm`, `arm64`) for projects that really do require that CPU due to the use of assembly or architecture-specific intrinsics.

Because each section is independent, and defaults to `All`, adding or modifying triplets should be significantly easier than with Debian's solution, which only has a single section.

**Comment by soroshsabz** [comment]
I think it is very useful feature for many library. and cause to write better user experience that without running cmake to generate building files or building library can say meaningful and useful error message if desired triplet does not support by library.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. The [Supports](https://github.com/microsoft/vcpkg/blob/e62d1361288e83eba786395b60361ab35ba83800/docs/maintainers/control-files.md#supports) has been added to CONTROL. So I am closing this issue for now.
