### ISSUE TITLE
libspeex.dll is missing when running app in debug mode

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [Microsoft/vcpkg#2293]
Hello, I'm using VS 2017 on Windows 7.
I'm using speex port in my application. When I'm trying to run it in debug mode I'm getting error:
![libspeex.dll is missing](https://user-images.githubusercontent.com/5282741/33521366-07ef16a0-d7e1-11e7-9d84-a1ee4e14c7d8.png)
Release configuration works fine.

**Comment by ras0219-msft** [comment]
Hi @WPMGPRoSToTeMa,

The debug mode import library is located at `debug\lib\libspeexd.lib`. I suspect you've just added `lib\libspeex.lib` to your project instead of using one of our preferred integration mechanisms[1], which should fix this issue.

[1] https://github.com/Microsoft/vcpkg/blob/master/docs/users/integration.md

**Comment by ras0219-msft** [comment]
Ok, resolved in latest master! There was an issue with the `.def` file. Thank you again for reporting the problem!

**Comment by WPMGPRoSToTeMa** [comment]
@ras0219-msft now `libspeexd.dll` is missing for release build...
