### ISSUE TITLE
[New Port Request] nodejs

### ISSUE THREAD

**Issue by mingmoe** [microsoft/vcpkg#23027]
Library name: node.js

Library description: Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine.

Source repository URL: https://github.com/nodejs/node

Project homepage (if different from the source repository): https://nodejs.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): None

I noticed [that](https://nodejs.org/api/embedding.html) node.js can be embedded into c++ as a library.

But vcpkg doesn't seem to provide this library.Only a `vcpkg-tool-nodejs` package provided as a building tool.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by r-rojo** [comment]
I too would like to see this port. I started trying to make my own port for this but have run into an issue where nodejs seems to only do in-source builds (which doesn't agree with vcpkg assumption to always use  out-of-tree builds (one from debug and one for release).

**Comment by dg0yt** [comment]
> have run into an issue where nodejs seems to only do in-source builds (which doesn't agree with vcpkg assumption to always use out-of-tree builds (one from debug and one for release).

@r-rojo It is possible to copy the source for each build type. (Some) maintainer function have an option to do that.

**Comment by r-rojo** [comment]
@dg0yt , I suppose it's possible to do that. However, after reading up on the node build process (and studying it as well), I've come to realize that the configure script provided is really just a Python script that configures a (Python) gyp build configuration which generates Makefiles along with the gyp configuration files. When configure is run with the --debug flag, it configures so that both Release and Debug configurations are built. Also, the build trees are at _${SOURCE_PATH}/out/(Debug|Release)_. When you run "make install", it only installs the Release files.
What I've done for now is to create a port that calls vcpkg_execute_build process for configure, make all, and make install. After that, I call execute_build_process again to install the debug files. There's probably a much better way to do this which is why it would be nice to have a MS supported portfile for node. 😄

**Comment by r-rojo** [comment]
Well, after some more trial and error, I realize that configure with the "--debug" flag is not what I wanted.
I'm now this (forgive the weird pseudocode):
* call configure with whatever flags necessary (prefix doesn't really matter here)
* for each config in (Release, Debug)
  * call "_make -C out BUILDTYPE=${config} -j ${VCPKG_CONCURRENCY}_"
  * call "_python3 ./tools/installl.py install / ${CURRENT_PACKAGES_DIR} + (config == Debug ? "/debug" : '')_"

install.py assumes prefix as /usr if only one argument is given which is why I give it "/" and ${CURRENT_PACKAGES_DIR}
Also, I had to patch install.py to support installing from either out/Debug or out/Release as it only supports installing from out/Release.

**Comment by SNMetamorph** [comment]
@r-rojo have you any progress with this?

**Comment by congzhangzh** [comment]
Hope this works, I want to use it to host nodejs.

ref: https://github.com/nodejs/node/issues/51824

**Comment by congzhangzh** [comment]
@r-rojo 
Monkey patch should be accept, and the to do some upstream change in the future.

**Comment by r-rojo** [comment]
I do have a port file that I can use with some success. It's a big hack right now but it does most of what it needs. The part I'm struggling now is having other packages find it. 
I just made a [fork](https://github.com/r-rojo/vcpkg) and [added](https://github.com/microsoft/vcpkg/commit/ffc17d9c86f38e1bb3479b668c73a25609efe103) what I have so far for the node port.

**Comment by congzhangzh** [comment]
@r-rojo cmake part should be easy, you need custom them all, as nodejs does not support cmake native, they are gyp/gn funs, which inherits from v8

maybe we can set prefix for configure, install them, and then,
1. Copy installed artifacts to vcpkg
2. Generate a cmake config file to set the include dir and libraries, or simple a new dummy target

I think v8/uv/node three part is enough to link and work with

**Comment by dg0yt** [comment]
Port skia builds with gn and generates cmake config from gn desc. But the functions still need to be generalized.

**Comment by congzhangzh** [comment]
> Port skia builds with gn and generates cmake config from gn desc. But the functions still need to be generalized.

@dg0yt Hi, maybe we use some trick of cmake file glob to find core parts, no need to be so generalized here too:)

**Comment by dg0yt** [comment]
No system detection? No macros and conditional compiles? "Maybe". From my experience, this is not very portable and a comes with a maintenance burden backpack. Even "trivial" packages quickly turn out as not so trivial.

**Comment by SNMetamorph** [comment]
There is package [vcpkg-tool-gyp-next](https://vcpkg.link/ports/vcpkg-tool-gyp-next) available, may be it can help with making portfile for Node.js in some kind?

**Comment by r-rojo** [comment]
@congzhangzh , are you suggesting adding support for gyp in new vcpkg functions?

**Comment by congzhangzh** [comment]
> @congzhangzh , are you suggesting adding support for gyp in new vcpkg functions?

@r-rojo No, I do some nodejs build for Windows/Linux these days, I would prefer to configure/build/install by nodejs itself, and we focus on cmake part for use like:
1. copy include files
2. copy lib/dll/so files
3. export an interface target

for windows:
```bat
vcbuild x64 dll debug?
: do the 1/2/3 steps
```
for linux:
```
# libuv needs to be a shard library, as we need it later, v8 should be sure to be static.
./configure --shared --debug-node --shared-libuv?
# do the 1/2/3 steps
```
for mac (TBD):

**My mac book is intel and out of date, it's a little hard to test**

**Comment by congzhangzh** [comment]
@r-rojo Hi Rodrigo, just a message,  I am trying to add a node port to vcpkg, It is very beginning.

A sample is first made, which uses a local nodejs install on Linux, hope the sample work after the node port is added to vcpkg!
<https://github.com/congzhangzh/vcpkg/tree/add_node_port>

**Comment by congzhangzh** [comment]
Btw, I found a great article 4 vcpkg: https://decovar.dev/blog/2022/10/30/cpp-dependencies-with-vcpkg/
