### ISSUE TITLE
How to provide 2 versions of a library side by side

### ISSUE THREAD

**Issue by horenmar** [Microsoft/vcpkg#2310]
This is a topic I've been thinking about for a while and vcpkg doesn't seem to have satisfactory answer for.

I maintain Catch and try to keep vcpkg port up to date as much as I can. Recently we jumped a major version and broke compatibility with C++98. That wasn't much of a problem, anyone wanting the old version could just checkout previous commit in history. Until now, as we will likely need to make a new release of the old version to fix an important bug.

The problem is that as far as I can tell, the sanest way to do this is to publish a new port, which seems kinda ugly. The less sane way of doing this is to provide a PR with 2 commits, one that would provide a checkout point for the new version of Catch Classic and one that rolls the change back, because we want to recommend using the current version. This would work, but the history would then be kinda odd (it would go `v2.0.1 -> v1.12.0 -> v2.0.1`).

Or I could just not provide the new release to vcpkg, but I'd rather avoid that.

**Comment by ras0219-msft** [comment]
Thanks for coming by!

I agree the best way to handle this is to create a `catch1` port which tracks the older release. Most users will simply install `catch` which will stay latest-and-greatest. I'll leave it up to you whether you'd like to go with `catch` and `catch2` instead, but since afaict you _intend_ for `catch2` to be the mainline version going forward I would recommend that be the "main" version.

Ideally, if the versions of catch didn't have conflicting header files, those two versions could be directly installed simultaneously and it's unambiguous which version each piece of code wants to use. However I understand that's not the case, therefore there will be some slight pain around using both versions (users will need to use two separate vcpkg instances).

This is only possible, I believe, since catch is a "leaf" library that won't normally be depended upon by other libraries. This strategy won't work for openssl1.0 vs openssl1.1, for example.

**Comment by horenmar** [comment]
Ok, I will probably publish `catch-classic` soon.

Also is it possible to alias a port? We would indeed prefer to call the project Catch2 from now on, but it would probably break people so being able to alias `catch` to `catch2` would be preferable.

**Comment by ras0219-msft** [comment]
The best way to alias a port at the moment is to simply use a dependency. This works correctly for installation (`vcpkg install catch` will correctly install `catch2`), but it will currently leave a bit to be desired for removal (`vcpkg remove catch` will not remove `catch2`).

**Comment by horenmar** [comment]
If I set a dependency, should I just remove the portfile entirely?

**Comment by ras0219-msft** [comment]
You will need to replace the entire portfile with
```cmake
set(VCPKG_POLICY_EMPTY_PACKAGE enabled)
```
