### ISSUE TITLE
Boost library clash with STL module import

### ISSUE THREAD

**Issue by steronydh** [Microsoft/vcpkg#2318]
I've used Vcpkg to install sqlite3, Cryptopp, Boost, SOCI, POCO and MS-GSL. I then created a new Command line project and entered this code:

```
#include "stdafx.h"

import std.core;
//#include <vector>

#include <boost/geometry/geometries/point_xy.hpp>


int main()
{
    boost::geometry::model::d2::point_xy<double> pt;

    std::vector<double> vec;

    return 0;
}
```

I get this compilation error:

```
1>f:\binaries.x86ret\inc\algorithm(4130): error C2475: 'std::min': redefinition; 'constexpr' specifier mismatch
1>c:\users\public\documents\vcpkg\installed\x86-windows\include\boost\config\detail\suffix.hpp(374): note: see declaration of 'std::min'
```

If I replace the module import with the usual include, it compiles with no errors.

**Comment by cdacamar** [comment]
When I see `#include "stdafx.h"` I immediately am curious what the build system did to generate the the .pch.  Currently, modules and .pch files don't mix very well because modules avoids redefining symbols based on include paths so if you have something like:
```c++
#include <vector>
import std.core
```
the vector imported by modules wouldn't cause and ODR because it would ignore the definition in the module.

When you're talking about .pch files it comes down to _who_ generated the .pch.  If it came from an outside source then there's no way modules can possibly determine where a particular symbol came from because it's original source location would be pointing at a different machine path.

**Comment by steronydh** [comment]
I've removed the precompiled header and now get a different error if I use the module instead of the include:

`1>f:\binaries.x86ret\inc\algorithm(4130): error C2475: 'std::min': redefinition; 'constexpr' specifier mismatch
1>c:\users\public\documents\vcpkg\installed\x86-windows\include\boost\config\detail\suffix.hpp(374): note: see declaration of 'std::min'
1>c:\users\public\documents\vcpkg\installed\x86-windows\include\boost\config\detail\suffix.hpp(376): fatal error C1903: unable to recover from previous error(s); stopping compilation
`
