### ISSUE TITLE
[wxWidgets] Compiling statically causes anti virus detections with Visual Studio 2022

### ISSUE THREAD

**Issue by BullyWiiPlaza** [microsoft/vcpkg#23193]
**Describe the bug**
When I compile a simple hello world GUI application using the wxWidgets vcpkg package, I get 9 false positive anti virus detections. [When using the wxWidgets sources instead of vcpkg, the AV detections do not occur](https://github.com/wxWidgets/wxWidgets/issues/22147).

**Environment**
- OS: Windows 11
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.31.30818 for x64 (Visual Studio 2022)

**To Reproduce**
1. `vcpkg install wxWidgets:x64-windows-static`
2. Compile the wxWidgets hello world application (I used a regular Visual Studio .sln file/project)
3. Upload the EXE to [VirusTotal](https://www.virustotal.com)
4. [Observe the anti virus detections](https://www.virustotal.com/gui/file/6b077713704621a521f3412f83fd0dc8bbddfcad47ef5eba198e526334c4ecd1)

**Expected behavior**
No anti virus detections for a simple hello world example since it isn't malicious in any way. This also affects Windows Defender since most users are using Windows Defender and they might receive alerts.

**Comment by JackBoosY** [comment]
All the code used to build the wxwidgets executable comes from upstream, and vcpkg **never** adds any extra code.
The issue is caused by the fact that these executables contain certain risky operations and they are not signed.
The related problem is also in the b2.exe provided by boost and the protoc.exe provided by protobuf, but please rest assured that there is no risk.

**Comment by BullyWiiPlaza** [comment]
> All the code used to build the wxwidgets executable comes from upstream, and vcpkg **never** adds any extra code. The issue is caused by the fact that these executables contain certain risky operations and they are not signed. The related problem is also in the b2.exe provided by boost and the protoc.exe provided by protobuf, but please rest assured that there is no risk.

Knowing that it's safe is not good enough, the AVs need to reflect that. Endusers are not easily convinced that it's safe if their AVs tell them otherwise. What exactly is vcpkg doing differently than the original sources to trigger the detections? There must be something that triggers the AVs. Which are the risky operations you are talking about?

**Comment by JackBoosY** [comment]
@BullyWiiPlaza You should ask these questions upstream wxWidgets.
Antivirus will first check executable certificates, which can cause this problem because user-built executables do not contain certificates.

**Comment by PBfordev** [comment]
@JackBoosY, you may have missed the information that an executable using wxWidgets built with any of the three officially supported ways for MSVC (bundled CMakeLists.txt, MSVS solution, and nmake makefile) does not trigger any of the VirusTotal warnings.

I know nothing about vcpkg but I noticed there is a major difference between the wxWidgets built the default official way and the vcpkg package: The latter uses "system" 3rd party libraries (zlib, tiff, png, expat) while the former uses their bundled versions. However, it would seem odd if this was the root cause.

I was reluctant to try to reproduce the issue with vcpkg, as I do not use it and did not want to possibly "break" my MSVS installation but I will probably try soon.

@BullyWiiPlaza, you reported that you used _x**64**-windows-static_ configuration, yet the compiler information says it is for x**86**?

**Comment by BullyWiiPlaza** [comment]
> I know nothing about vcpkg but I noticed there is a major difference between the wxWidgets built the default official way and the vcpkg package: The latter uses "system" 3rd party libraries (zlib, tiff, png, expat) while the former uses their bundled versions. However, it would seem odd if this was the root cause.
> 
> I was reluctant to try to reproduce the issue with vcpkg, as I do not use it and did not want to possibly "break" my MSVS installation but I will probably try soon.

vpckg does not mess up your MSVC installation, it fully runs in a portable folder. You can delete it again at any time.

> 
> @BullyWiiPlaza, you reported that you used _x**64**-windows-static_ configuration, yet the compiler information says it is for x**86**?
I used the wrong developer command prompt, I updated the first post with the correct version of MSVC. I definitely use 64-bit.

**Comment by PBfordev** [comment]
I cannot reproduce the issue even with vcpkg.

What I did:
1. Installed vckpg as instructed.
2. Launched elevated command prompt.
3. Ran `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat` (the compiler identification is "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30140 for x64").
4. Ran `vcpkg install wxWidgets:x64-windows-static` followed by `vcpkg integrate install`.
5. Launched MSVS 2019 and used "Windows Desktop Application" wizard to create a new project.
6.  I replaced the code in the only C++ file in the project with wxWidgets' [Hello World](https://docs.wxwidgets.org/3.0/overview_helloworld.html) code.
7. I switched the project's active configuration to Release x64 and in Configuration Properties / vcpkg set Use Static Libraries to "Yes" and in C/C++ / Code Generation set Runtime Library to "Multi-threaded (/MT)".
8. I tried to build the project but it failed due to the missing libraries, so I added libraries _rpcrt4.lib_ and _comctl32.lib_ and built the project successfully.
9. I checked the resulting executable with VirusTotal and the only issue was in the first row: Cynet. However, this one is triggered even with the executable created from the unmodified Win32 project created by the wizard.

**Comment by JackBoosY** [comment]
Thanks for the info, we will try to reproduce this later.

**Comment by JackBoosY** [comment]
Can't repro this issue using Visual Studio 2017:
https://www.virustotal.com/gui/file/29f4c53a04e0652c5725e226139ea4c4d64c372e03c7801ddb119a4db9257b72?nocache=1

Will check Visual Studio 2022 later.

**Comment by JackBoosY** [comment]
@PBfordev What's your opinion here?

**Comment by dg0yt** [comment]
> I know nothing about vcpkg but I noticed there is a major difference between the wxWidgets built the default official way and the vcpkg package: The latter uses "system" 3rd party libraries (zlib, tiff, png, expat) while the former uses their bundled versions. However, it would seem odd if this was the root cause.

The bundled versions may have been used many times before and therefore might be whitelisted. The libraries created by vcpkg may be new unique binary artifacts which don't get any credits in advance.

**Comment by JackBoosY** [comment]
I think this related to the Visual Studio compiler or the anti-virus check.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
