### ISSUE TITLE
Why does VS-Qt always go to "debug lib" in the "release lib" directory?

### ISSUE THREAD

**Issue by WindSnowLi** [microsoft/vcpkg#23481]
I use Visual Studio 2022 and vcpkg to write QT programs. When compiling "debug", link.exe always goes to the "release lib" directory to find "debug lib". I confirm that vcpkg in the project attribute has been set to "debug". Do you need me to manually copy "debug lib" into "release lib"

```
已启动生成…
1>------ 已启动生成: 项目: XDAxis, 配置: Debug x64 ------
1>Reading Qt configuration (D:/vcpkg/installed/x64-windows-static/tools/Qt6/bin/qmake)
1>XDAxis.cpp
1>main.cpp
1>qrc_XDAxis.cpp
1>qtvars_plugin_import.cpp
1>moc_XDAxis.cpp
1>LINK : fatal error LNK1104: 无法打开文件“D:\vcpkg\installed\x64-windows-static\Qt6\plugins\styles\qwindowsvistastyled.lib”
1>已完成生成项目“XDAxis.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========
```

**Comment by Neumann-A** [comment]
The Qt VS Plugin is not clever enough to pull in a qt.conf and just uses the paths qmake provides. Additionally it assumes qmake to reside in a dir called `/bin`. So there is no way to correctly make it work for both configurations using a single Qt Setup (qmake) in the Plugin. Only Release will work out of the box, Debug requires an additional setup.

**Comment by WindSnowLi** [comment]
> The Qt VS Plugin is not clever enough to pull in a qt.conf and just uses the paths qmake provides. Additionally it assumes qmake to reside in a dir called `/bin`. So there is no way to correctly make it work for both configurations using a single Qt Setup (qmake) in the Plugin. Only Release will work out of the box, Debug requires an additional setup.

Thank you for your reply

**Comment by R3uan3** [comment]
> Debug requires an additional setup

@Neumann-A  what additional setup? I'm with the same issue, but I couldn't figure out how to solve it, this is what I already tried:
https://stackoverflow.com/questions/73821704/visual-studio-doesnt-find-qt-static-source-for-debug-mode

**Comment by Neumann-A** [comment]
You basically need different qmake with two different qt.conf. otherwise it will try to use whatever was hardcoded into qmake Basically you cannot have two different configs with the same qmake unless the files are all in the same directories.

**Comment by R3uan3** [comment]
I dont understand, where is this qt.conf?

**Comment by CohortMinseok** [comment]
This issue is almost a year old, but I feel like someone might come across if they google search this issue. It took me multiple installs and days to figure out how to fix the issue.

At the moment, vcpkg has qtbase listed for version 6.5.3 and on a fresh install, this issue will come up when you try to build your project where Qt is linking debug libraries. 

The fix is rather simple. If you have Qt installed, remove it using the vcpkg remove qtbase. Navigate to the triplets folder in the main directory of vcpkg (whatever you have it set as). Open x64-windows-static.cmake or whatever format you are building qt in, and add this line below the existing 3. 

x64-windows-static.cmake ->

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
**set(VCPKG_BUILD_TYPE release)**

Do a Clean on your project that is using vcpkg Qt, and build. It should use the appropriate release libraries.

**Comment by Neumann-A** [comment]
> The fix is rather simple.

Nope this is not the fix. also the original issue was about always linking release libs instead of debug ones. Why in your case debug libs are linked cannot be deduced without knowing more about the setup and how that setup deduces which libraries to use.
