### ISSUE TITLE
lacks the RTree   extension! Spatialite and GPKG will not behave properly.

### ISSUE THREAD

**Issue by wuvalue** [microsoft/vcpkg#23622]
CMake Error at cmake/helpers/CheckDependentLibraries.cmake:438 (message):
  D:/AAA/vcpkg-master/installed/x64-windows/lib/sqlite3.lib lacks the RTree
  extension! Spatialite and GPKG will not behave properly.  Define
  ACCEPT_MISSING_SQLITE3_RTREE:BOOL=ON option if you want to build despite
  this limitation.
Call Stack (most recent call first):
  gdal.cmake:216 (include)
  CMakeLists.txt:212 (include)

-- Configuring incomplete, errors occurred!
See also "D:/AAA/build/CMakeFiles/CMakeOutput.log".
See also "D:/AAA/build/CMakeFiles/CMakeError.log".

HI,how I change the option for ACCEPT_MISSING_SQLITE3_RTREE:BOOL=ON

**Comment by dg0yt** [comment]
> CMake Error at cmake/helpers/CheckDependentLibraries.cmake:438 (message):

This is from the new CMake build system of GDAL. See #22392 for work in progress to use it.

> HI,how I change the option for ACCEPT_MISSING_SQLITE3_RTREE:BOOL=ON

Since you are building GDAL yourself with CMake, you define GDAL's configuration parameters. So add `-DACCEPT_MISSING_SQLITE3_RTREE:BOOL=ON` when running cmake to configure GDAL, or set that parameter in a CMake GUI.

**Comment by Cheney-W** [comment]
Thanks for posting this issue. 
I think dg0yt's suggestion could solve this issue, if this issue has new information, please reopen it.

**Comment by vautieri2** [comment]
I have sqlite built with the rtree option.  I'm doing a cross compile (linux -android).  simply a heads up.  I didn't look at the configuration/cmake build files yet to see why its not detecting.  I'm building with sqlite 3.38.5 and validated its rtree option is detected when it gets built.  I also use this 3.38.5 version with proj 8.x and others

**Comment by dg0yt** [comment]
> I'm at the point it needs to get fixed as I need it all working now

@vautieri2 What needs to get fixed?

**Comment by vautieri2** [comment]
I thought it was a related issue bit it doesn't belong here.  I'm cross
compiling for android where the Spatialite make system has issues with more
than just this but the prepare as well.  In the meantime I removed their
checks in the autoconfig and things work perfectly fine as I knew this and
the prepare are proper.   I'm not a guru with their make system to know how
to really fix

**Comment by nilsnolde** [comment]
FWIW, I had the same problem and turns out that SQLite3 also uses the `.pc` file to configure its paths and seems smth gets mixed up there within GDAL cmake config. On the system I used, (a [`manylinux`](https://github.com/pypa/manylinux) AlmaLinux variant) there was sqlite installed system-wide (only dynamic library, no headers). _Somehow_ the `gdal` cmake configuration ended up with `SQLite3_HAS_RTREE=` and e.g. `PC_SQLITE3_CFLAGS:INTERNAL=-I/usr/local/include`. The system-wide one doesn't have headers, but it does have a `.pc` file in `/usr/local/lib/pkgconfig`. Even though when debugging `gdal` cmake I could see it properly resolved `sqlite3.h`'s path to the `vcpkg` one (since there's none system-wide anyways), which [is being used](https://github.com/OSGeo/gdal/blob/ff1d8eb143e276163dc957e1db400638484a48f7/cmake/modules/packages/FindSQLite3.cmake#L139) to set `SQLite3_HAS_RTREE`. 

So, in the end, I still have no idea why it happened, but what worked is to remove the system-wide `sqlite3.pc` file.
