### ISSUE TITLE
[tensorflow] ARM support

### ISSUE THREAD

**Issue by abique** [microsoft/vcpkg#24139]
Hi,

It seems that tensorflow currently doesn't support ARM, but according to https://www.tensorflow.org/lite/guide/build_cmake_arm maybe there are some options there.

I wonder what could be done to be able to have a lightweight version of tensorflow that can execute a network on ARM?
I can do the training on intel cpu, but I'd like to execute the network on ARM device as well.

Thank you very much!

Regards,
Alex

**Comment by FrankXie05** [comment]
@abique Thanks for posting this issue, 
  We don't support currect that build `TensorFlow Lite` through vcpkg'cmake on arm machine, sorry. 😢
  
  However `TensorFlow `offically supports cmake to build `TensorFlow Lite` progrect on arm machine.
  You can refer to the complete cmake project documentation provided by them.
  References：https://www.tensorflow.org/lite/guide/build_cmake

**Comment by Luiz-Monad** [comment]
currectly ? currently or correctly ? or both ? 

I mean, the port file is using bazel, if I add some options to make the entire bazel target tensorflow-lite or tensorflow with android, I will probably work won't it ? 
I'll will try that.

fingers crossed we don't get problems with the freaking libstdc++ from GNU versus LLVM used by Android. 
Otherwise someone is going to have to learn how to create cross-tools on bazel, or use such things [one of the AQuery](https://github.com/hedronvision/bazel-compile-commands-extractor) to convert it to CMake.

**Comment by FrankXie05** [comment]
@Luiz-Monad We very much welcome you to modify this function. Could you submit a PR to try it out? we will help you. :)

**Comment by Luiz-Monad** [comment]
I'm currently on vacation, I'll continue it when I return.
But thanks for responding.

________________________________
