### ISSUE TITLE
New Boost version takes twice as long to build

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/vcpkg#2414]
1.65 took 6 or 7 minutes on my PC (i5-3570K), 1.66 (modularized) takes 15+ minutes.

**Comment by alexkaratarakis** [comment]
The new `boost` metapackage builds more parts than the previous `boost` package (for example boost-python and its dependencies). This leads to a longer build time.
However, packages can now only depend on parts of boost instead of the entire `boost` package; this allows you to only builds parts you need and not waste time for parts you don't need.
Overall, this should speed up your build process when libraries depend only on the parts they need.

Also, we have modified many of the boost dependents (but not all of them) to depend only on the parts they require.
