### ISSUE TITLE
[openssl] build failure

### ISSUE THREAD

**Issue by code-creator** [microsoft/vcpkg#24200]
**Describe the bug**
vcpkg install boost failes (seems to me) to download the libraries

**Environment**
- Windows 7 x64
- Visual Studio 2019 Version 16.11.11

**To Reproduce**
1. ./vcpkg install boost
2. See error
Repro code when

**Expected behavior**
Download and install of boost libraries

**Failure logs**
-see log, basically it can not download the libraries although in a browser it works

[DEBUG] Downloading https://www.openssl.org/source/old/1.1.1/openssl-1.1.1l.tar.gz
Error: Failed to download from mirror set:
https://www.openssl.org/source/openssl-1.1.1l.tar.gz: WinHttpSendRequest() failed: 12175
https://www.openssl.org/source/old/1.1.1/openssl-1.1.1l.tar.gz: WinHttpSendRequest() failed: 12175

**Additional context**
using the kicad vcpkg from 
https://gitlab.com/kicad/packaging/vcpkg

Full log:
[0.txt](https://github.com/microsoft/vcpkg/files/8500467/0.txt)

**Comment by FrankXie05** [comment]
@code-creator Thanks for posting this issue, it's not boost's bug, it's `openssl`bug.
 `openssl` will pull outdated `mingw` packages, we currently have no good way to cache outdated `mingw` packages, and due to the rolling release of upstream `mingw`, only the latest version will be retained.
 Solution: Use the latest openssl-3.0.2 of https://github.com/microsoft/vcpkg
 Related issue: #23362, #23828

**Comment by JackBoosY** [comment]
Please download [this file](https://github.com/microsoft/vcpkg/files/8504361/openssl-1.1.1l.tar.gz) and put it into _VCPKG_ROOT/downloads_ then try again.

Thanks.

**Comment by code-creator** [comment]
Hi JackBoosY, I have followed your instructions and now openssl has been built.
Thank you!
