### ISSUE TITLE
grpc build failure on arm64-osx

### ISSUE THREAD

**Issue by ghamarian** [microsoft/vcpkg#24217]
**Host Environment**
- OS: [e.g. Windows/Linux etc...] OS Monterey 
- Compiler: gcc 11

**To Reproduce**
- `./vcpkg install grpc`

It compiles fine with clang.

**Failure logs**
```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: /opt/homebrew/Cellar/cmake/3.22.2/bin/cmake --build . --config Debug --target install -- -v -j9
    Working Directory: /Users/amir/projects/github/vcpkg/buildtrees/grpc/arm64-osx-dbg
    See logs for more information:
      /Users/amir/projects/github/vcpkg/buildtrees/grpc/install-arm64-osx-dbg-out.log

Call Stack (most recent call first):
  /Users/amir/projects/m2l/gs/gs-vision-c/build/vcpkg_installed/arm64-osx/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  /Users/amir/projects/m2l/gs/gs-vision-c/build/vcpkg_installed/arm64-osx/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  buildtrees/versioning_/versions/grpc/5e3795bf43afe5243e47e18ac66a28bc722207f5/portfile.cmake:72 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)
```

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
[vcpkg-manifest-install.log](https://github.com/microsoft/vcpkg/files/8504897/vcpkg-manifest-install.log)
[install-arm64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/8504908/install-arm64-osx-dbg-out.log)

**Comment by binhlxag273** [comment]
I have the same issue when build grpc on linux using manifest mode and build shared library with override triplet. The problem is that when execute protoc tool installed in vcpkg_installed/x64-linux/tools/protobuf/protoc-3.19.4.0, it cannot read dynamic library: 
`error while loading shared libraries: libprotoc.so.3.19.4.0: cannot open shared object file: No such file or directory`
And i don't know how to fix it. Hope anyone can help to fix this.

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
