### ISSUE TITLE
[zookeeper] update to 3.8.0

### ISSUE THREAD

**Issue by PriitUring** [microsoft/vcpkg#24342]
Library name: zookeeper

New version number: 3.8.0

https://zookeeper.apache.org/doc/r3.8.0/releasenotes.html

https://zookeeper.apache.org/releases.html

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Since zookeeper 3.5.7 version release archive does not contain `zookeeper.jute.c` and `zookeeper.jute.h`, but configuage cmake need these two files. This need use java to build zookeeper project, and these two files will create when building. This cannot be implemented in vcpkg temporarily.
The related source issue: https://issues.apache.org/jira/browse/ZOOKEEPER-3820
The related code in _zookeeper-client/zookeeper-client-c/CMakeLists.txt_:
```
# include file checks
foreach(f generated/zookeeper.jute.h generated/zookeeper.jute.c)
  if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${f}")
    to_have(${f} name)
    set(${name} 1)
  else()
    message(FATAL_ERROR
      "jute files are missing!\n"
      "Please run 'ant compile_jute' while in the ZooKeeper top level directory.")
  endif()
endforeach()
```

**Comment by LilyWangLL** [comment]
> @LilyWangLL
> 
> What about updating from 3.5.5 to 3.5.7 if currently unable to update to latest version? Or is it not allowed to update packages to something that's not the very newest?

OK, I will update `zookeeper` to version 3.5.7.

**Comment by LilyWangLL** [comment]
`zookeeper` has been updated to version 3.5.6, due to it can not updated to latest version on vcpkg, I will close this issue temporarily.
