### ISSUE TITLE
[nuspell] build failure on master. 

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#24533]
nuspell build failure on master. 
Please fix it.

**Comment by Neumann-A** [comment]
CI runs fine so what is the error?

**Comment by talregev** [comment]
From master:
https://dev.azure.com/vcpkg/public/_build/results?buildId=71602&view=results
https://dev.azure.com/vcpkg/public/_build/results?buildId=71602&view=logs&j=878666d5-db33-5b27-9e7d-b0c7ee352005&t=d914c609-a9aa-5880-221f-cbd46db9069e

For example it fail on nuspell:x86-windows also for x64. test locally also fail.

**Comment by Neumann-A** [comment]
Yeah baseline issue. No reason to open up an extremely short unhelpful issue without also telling the error in detail.
Since you have been around long enough to know this, you earned my thumbs down for your main comment :P 

Main CI is rarely completely clean, so having only 1-2 ports fail is already quite good. Having a title like: "[all ports] build failure on master" seems to indicate nothing builds and everything fails which is not the case and wasn't your intention.  Please be more concise with your descriptions.

**Comment by talregev** [comment]
Sorry, You are right. I was over dramatic. Should I change the title and you will remove the thumb down?
