### ISSUE TITLE
Error: Building package bzip2:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Tezas-6174** [microsoft/vcpkg#24703]
I am using Ubuntu 20.04 LTS. I was installing the dependencies for Iroha 1 using vcpkg using the command ``./vcpkg/build_iroha_deps.sh $PWD/vcpkg-build``. But the process was interrupted by the error:

```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: /usr/bin/git fetch https://sourceware.org/git/bzip2.git 75a94bea3918e612b879d6a11ca64b8689526147 --depth 1 -n
    Error code: 128
Package: bzip2:x64-linux
Vcpkg version: 2021-01-13-unknownhash
```

Please resolve this.

**Comment by dg0yt** [comment]
> ~~~
> Vcpkg version: 2021-01-13-unknownhasha
> ~~~
> Please resolve this asap.

"ASAP" may sound impolite. Even more given that you didn't attempt to use an up-to-date version of vcpkg.

**Comment by Tezas-6174** [comment]
Sorry for that, I will check it once by using the up-to-date version of vcpkg.

**Comment by Cheney-W** [comment]
What is the result of using the latest vcpkg?

**Comment by cnelson711** [comment]
If I scrolled up, I saw that curl failed to verify the server used to download the file (likely because the embedded linux system I was running vcpkg from didn't have an up to date ca-certificates package).

I just downloaded the file manually and stuck it in the vcpkg/downloads folder to continue...
https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
