### ISSUE TITLE
Impossible to use official Boost distribution along with vcpkg?

### ISSUE THREAD

**Issue by wdx04** [microsoft/vcpkg#2477]
Hi,
I'm trying to use the official Boost 1.65.1 distribution along with vcpkg(build system is CMake 3.10.1).
When I select the default native compiler in CMake GUI,  it can detect the compiled boost libraries located in the standard <boost_root>/stage/lib directory(built with bjam).
But if I specify the vcpkg toolchain file to use any vcpkg installed packages, it can no longer detect any of the boost libraries(note I have not installed the boost libraries within vcpkg).

**Comment by ras0219-msft** [comment]
In general, to ensure consistency, we do tweak certain settings to ensure that the copy of Boost inside Vcpkg is preferred over external copies. This becomes _critically_ important if you install any other libraries that depend on boost -- otherwise you might link multiple copies of boost (or worse)!

While it would be possible to make this _very specific_ situation work (using external boost while not using any libraries that depend on boost), it isn't a high priority since there is an easy workaround: `vcpkg install boost`.
