### ISSUE TITLE
[glfw3] library not found for -lglfw3

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/vcpkg#24909]
**Describe the bug**
`glfw3` is in my vcpkg.json

**Environment**
- OS: macOS 12.4 (21F79)
- Compiler: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.5.0

**To Reproduce**
1. ./vcpkg install glfw3
```
glfw3 provides CMake targets:
    # this is heuristically generated, and may not be correct
    find_package(glfw3 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE glfw)
```
2. ```find_package(glfw3 CONFIG REQUIRED)``` with `target_link_libraries(<target_name> PRIVATE "${deps}")`
3. Found when debugging my new nuklear CMake contribution: https://github.com/Immediate-Mode-UI/Nuklear/pull/462

**Expected behavior**
Should error if it can't be linked otherwise work

**Failure logs**
```
ld: library not found for -lglfw3
```

**Additional context**
I'm on vcpkg @ 314018fef43c7e3a52a3e46599313b70ace3977a

**Comment by dg0yt** [comment]
Doublecheck that you didn't spell the library as `glfw3` when the actual imported target is `glfw`.
https://github.com/Immediate-Mode-UI/Nuklear/blob/0761cfc6c10b417696019ecc1e511b326f50e006/example/CMakeLists.txt#L11
(An exported target such as `glfw` usually carries the full path to the library.)

**Comment by dg0yt** [comment]
> maybe we can make an alias or something?

No. Adding more non-standard names just adds more sources for confusion. And the error message is already quite telling.

It would help if upstream would use a namespace. E.g. with `GLFW::glfw', error message on wrong usage would be even better.

OTOH your cmake code separates the identifier from its use in `target_link_libraries`. This makes  it more difficult to discover the errror. You cannot compare literally. See you second step "to reproduce": It won't reproduce the error because it omits relevant details.
