### ISSUE TITLE
find_package should not return system installed version if same package is installed from vcpkg

### ISSUE THREAD

**Issue by Naville** [microsoft/vcpkg#24995]
**Describe the bug**
find_package(libxml2) returning multiple include directory.

**Environment**
- OS: macOS
- Compiler: Any

**To Reproduce**
1. ./vcpkg install libxml2
2. ``find_package(libxml2) and print LIBXML2_INCLUDE_DIR``
3. Try compile any old-enough LLVM version like [11.x](https://github.com/llvm/llvm-project/blob/1fdec59bffc11ae37eb51a1b9869f0696bfd5312/llvm/cmake/config-ix.cmake#L164) with Vcpkg CMake toolchain

**Expected behavior**
``LIBXML2_INCLUDE_DIR`` should be, quoting CMake documentation ``the directory containing LibXml2 headers``, it's not a plural

**Failure logs**
```
-- Found libtool - /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
CMake Error at cmake/config-ix.cmake:158 (if):
  if given arguments:

    "(" "CMAKE_OSX_SYSROOT" ")" "AND" "(" "EXISTS" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk//Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/libxml2" "/Users/naville/Build/sysroot/installed/x64-osx/include" ")"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:617 (include)
```

**Additional context**
See comments below

**Comment by Naville** [comment]
General speaking, LLVM(and I assume many other projects) assume ``LIBXML2_INCLUDE_DIR`` to be a single path, however, if Vcpkg also installed its own libxml2, the variable becomes a list of directories, which breaks assumptions like the one in LLVM, as demonstrated below:

```
  message(FATAL_ERROR "XXXX ${LIBXML2_INCLUDE_DIR}")
```

prints

```
CMake Error at cmake/config-ix.cmake:158 (message):
  XXXX
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/libxml2;/Users/naville/Build/sysroot/installed/x64-osx/include
Call Stack (most recent call first):
  CMakeLists.txt:617 (include)\
```

**Comment by Naville** [comment]
Of course, one could in-theory avoid such behavior by avoiding installing libxml2 on Darwin, nonetheless I don't think this is a particularly good idea

**Comment by dg0yt** [comment]
General modern usage of CMake find modules:
1. If possible, use targets, not variables. `FindLibXml2.cmake` provides `LibXml2::LibXml2` since CMake 3.12.
2. If you need to *read* variables in downstream projects, use the plural form `LIBXML2_INCLUDE_DIRS` (list) aka "output variables" if possible. (For this module, this variable is documented since CMake 3.10.)
   The singular form `LIBXML2_INCLUDE_DIR` is a cache variable considered to be an "input variable", to change find module behaviour.
   (Same for the libraries variables.)

There is a number of situation where vcpkg puts lists into the singular variables. It resolves many problems (in particular with handling debug+release config for libs), but it sometimes causes other issues.
In particular, downstream still using `LIBXML2_INCLUDE_DIR` instead of `LIBXML2_INCLUDE_DIRS` is the reason why vcpkg`s libxml2 wrapper turns the input variable into a list. You will have to update your CMake usage sooner or later.

**Comment by Naville** [comment]
@dg0yt Thanks, yeah I'm kinda more or less aware of these workarounds. I'm more curious (worries) about whether the underlying cause of what we've been observing here is some due to some more generic bugs

**Comment by dg0yt** [comment]
@JackBoosY We need to do some work on the libxml2 wrapper:
- Ensure that it doesn't return system paths (this issue).
  I think the problem is in the wrapper. The wrapper appends to `LIBXML2_INCLUDE_DIR` after `_find_package`. When the user (project) did a `find_package(LibXml2)` before installing port `libxml2`, this will mix cached system paths and vcpkg paths. (Easily resolved by clean build, and so it can be regarded as a user error. But perhaps it can be completely avoided.)
- Make the wrapper forward the dl usage requirement (https://github.com/microsoft/vcpkg/pull/24935#issuecomment-1139365357).

I could perhaps bundle these changes with #24935, which would gave us test coverage by building the `xsltproc` program.

**Comment by JackBoosY** [comment]
Can this issue be fixed now?

**Comment by Naville** [comment]
I don't have the time to test myself, but if you say so I guess?
