### ISSUE TITLE
[catch2] include path "catch2/catch.hpp" broken since last port updates

### ISSUE THREAD

**Issue by andremueller** [microsoft/vcpkg#25014]
**Describe the bug**
Since the last update on the vcpkg master branch the [catch2] port was modified @RT222 such that all my projects do not compile anymore - the catch2 standard path as documented here <https://catch2.docsforge.com/v2.13.2/tutorial/#getting-catch2> which shall be 

`#include <catch2/catch.hpp>`

is not working anymore as the path of the port was changed to `#include <catch.hpp>` which seems to be not standard compliant (especially if we go up to catch3 somewhen).

**Environment**
- OS: Windows
- Compiler: Microsoft 19.29.30143

**To Reproduce**
1. ./vcpkg install catch2
2. See error

**Expected behavior**
Just compile the tests without error. And I do not to want to change all include paths!

**Failure logs**

`fatal error C1083: Cannot open include file: 'catch2/catch.hpp': No such file or directory`

**Comment by RT222** [comment]
There's no bug here. The issue is that you are using the catch 2.13.2 documentation for the 3.0.1 version. Catch v3 introduced many breaking changes, and if you want to use it, you'll have to make some changes to your code, there's no way around it.

See here for up to date documentation : https://github.com/catchorg/Catch2/blob/devel/docs/Readme.md
And here to migrate your project to the v3 : https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md#top

Basically : 

> - Change your CMakeLists.txt to link against Catch2WithMain target if you use Catch2's default main. (If you do not, keep linking against the Catch2 target.)
> - Delete TU with CATCH_CONFIG_RUNNER or CATCH_CONFIG_MAIN defined, as it is no longer needed.
> - Change #include <catch2/catch.hpp> to #include <catch2/catch_all.hpp>
> - Check that everything compiles. You might have to modify namespaces, or perform some other changes (see the [Things that can break during porting](https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md#things-that-can-break-during-porting) section for the most common things).
> - Start migrating your test TUs from including <catch2/catch_all.hpp> to piecemeal includes. You will likely want to start by including <catch2/catch_test_macros.hpp>, and then go from there. (see [other notes](https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md#other-notes) for further ideas)

And if you're not ready to upgrade to the v3, use an overlay port to stay on the v2 (as explained [here](https://github.com/microsoft/vcpkg/pull/24762#issuecomment-1139241835)) or use and override if you're using manifests.

**Comment by andremueller** [comment]
Thank you very much!
