### ISSUE TITLE
[spdlog] Add feature for SPDLOG_USE_STD_FORMAT 

### ISSUE THREAD

**Issue by meldavis** [microsoft/vcpkg#25164]
Because our project makes heavy use of C++20 `std::format` and `std::formatter`, we would like to enable `spdlog`'s option to use the  same `std::format` instead of  bringing `fmt` in as an external dependency.

**Proposed solution**
Add a feature for `stdformat` that:

1.  Changes the configure options to:
    a.  SPDLOG_FMT_EXTERNAL=OFF
    b.  SPDLOG_USE_STD_FORMAT=ON
2. Uncomments the appropriate line in `include/spdlog/tweakme.h`

**Comment by Qudix** [comment]
I'd really like to see this worked on again as the library I work on has support for `vcpkg` but dropping `fmt` as a dependency is currently impossible. The pr from `LilyWangLL` was closed last year for inactivity.

**Comment by dg0yt** [comment]
> The pr from `LilyWangLL` was closed last year for inactivity.

IMO the PR couldn't continue because it implemented (and this issue requests) an anti-pattern: Choosing an alternative backend (`std::format`) without dropping a dependency (`fmt`).

Modeling alternatives in vcpkg is currently not possible except for some limited cases. What might be acceptable is modeling the choice of the `fmt` backend as a feature (with a proper port dependency) as long as this backend doesn't offer a different/reduced API. (Features must be additive.)
To cover pre-C++20 platforms, this would probably would need to be a default feature. Then users could opt-out of the dependency by using `spdlog` with `"default-features": false`. However, this only works if no other (used) ports apply pulls in the spdlog's default features.
