### ISSUE TITLE
[uWebSockets] please remove the dllexport of static libs

### ISSUE THREAD

**Issue by z16166** [microsoft/vcpkg#25598]
hi,

Currently uWebSockets and its dependency "uSockets" define a macro "WIN32_EXPORT" in header file "libusockets.h", as the following. 
So all uSockets api functions and a uWebSockets class named "struct WIN32_EXPORT WebSocketProtocol" will appear in exe/dll export tables even if we use their static libs.
Please remove "__declspec(dllexport)" for static lib triplets. Thanks.

```
#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <winsock2.h>
#define LIBUS_SOCKET_DESCRIPTOR SOCKET
#define WIN32_EXPORT __declspec(dllexport)
#else
#define LIBUS_SOCKET_DESCRIPTOR int
#define WIN32_EXPORT
#endif
```

**Comment by Cheney-W** [comment]
This issue should be an upstream issue, please submit an issue on https://github.com/uNetworking/uSockets.

**Comment by z16166** [comment]
ok, I just submit to  https://github.com/uNetworking/uSockets/issues/184

**Comment by uNetworkingAB** [comment]
* uSockets has removed all those __declspec(dllexport) in 0.8.5, this version is also needed to build latest uWebSockets:

  * https://github.com/uNetworking/uWebSockets/issues/1549

* On a side note - now that __declspec(dllexport) is removed, uSockets should (and really should always have been) be built only as a static lib.

  * The reason is uSockets is an opaque library where a few calls are made very often in hot paths, assuming those calls are LTO/inlined rather than full on dynamic function calls.

  * I've benchmarked a 60% performance reduction when building uSockets as DLL compared to as static lib.
