### ISSUE TITLE
bootstrap-vcpkg.bat is not compatible with pwsh 7

### ISSUE THREAD

**Issue by bkmeneguello** [microsoft/vcpkg#25623]
A [per docs](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell?view=powershell-7.2#renamed-powershellexe-to-pwshexe), besides `powershell.exe` command renamed to `pwsh.exe` it also changes the default parameter from `-Command` to `-File`. To keep it compatible the `-Command` argument must be passed, and the executable should be checked for existence.

https://github.com/microsoft/vcpkg/blob/9776b51b557bb2c20d79cf541f124c48d0c2c720/bootstrap-vcpkg.bat#L2

**Comment by JackBoosY** [comment]
cc @BillyONeal

**Comment by BillyONeal** [comment]
I'm not sure I understand what the bug is here. The command was renamed to `pwsh` explicitly so that software that explicitly wants Windows PowerShell rather than PowerShell Core to continue to function. PowerShell Core is not installed by default anywhere so looking for pwsh would not actually achieve our goal of bootstrapping things. Can you describe an actual user facing problem here?

Note that what users are intended to call is explicitly a .bat so that we don't need to worry that they're calling from a different PowerShell version.

>and the executable should be checked for existence.

What would we do if it doesn't exist?

**Comment by bkmeneguello** [comment]
Is Powershell 5.1 guaranteed to be always available? I ran into this problem because in my system it's not available, only pwsh 7.2. If I'm wrong and my system isn't standard, feel free to close this issue.

**Comment by BillyONeal** [comment]
> Is Powershell 5.1 guaranteed to be always available? I ran into this problem because in my system it's not available, only pwsh 7.2. If I'm wrong and my system isn't standard, feel free to close this issue.

I don't know about "guaranteed" but it's certainly much more likely to be available than pwsh.
