### ISSUE TITLE
2022.06.15.1 is wrongly tagged as 2022.06.16.1

### ISSUE THREAD

**Issue by letmaik** [microsoft/vcpkg#25665]
![image](https://user-images.githubusercontent.com/530988/178145161-a8813c87-e301-419f-9818-7965f207df25.png)

**Comment by BillyONeal** [comment]
Oops :shrug:

I think it's too late to change now.

**Comment by letmaik** [comment]
Could this be prevented by automating the release process? Seems like it should be doable. How are releases done currently?

**Comment by BillyONeal** [comment]
> Could this be prevented by automating the release process?

Not easily, since there's no single build / artifact that is associated with the release to attach it to, and there are inputs to this thing that aren't produced in an automated way right now. Given unlimited time, sure, but ...

These releases (in the catalog repo) aren't really *meaningful* anyway; we're doing them more because people like to pick individual releases to lock to even if the release commit is not meaningfully different than any other commit.

Contrast this with the tool releases, for which at least the github 'release' creation is automated at this point.

> Seems like it should be doable. How are releases done currently?

For the "tool" repo: https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/internal/vcpkg_tool_release_process.md

For the "catalog" repo: https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/internal/vcpkg_catalog_release_process.md

**Comment by BillyONeal** [comment]
Closing this because it is too late to do anything about.
