### ISSUE TITLE
vcpkg_copy_pdbs is broken on non-English Visual Studio installs

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/vcpkg#25846]
https://github.com/microsoft/vcpkg-tool/pull/339#issuecomment-1187242711

This is caused by running `dumpbin` and looking for "PDB file found at."

We should probably fix this by adding a new z- command to the tool which does what dumpbin is doing without calling dumpbin.

**Comment by Neumann-A** [comment]
Then go ahead and make it an vcpkg command. If it is only inside the tool it won't help users ;)

**Comment by Chronial** [comment]
Bump :)
We just ran into this issue with some of our CI machines producing builds without pdbs. Since the installed language packs are not part of the compiler hash this even poisons the binary cache with pdb-less builds.

Finding the root cause of this took a few hours – a fix would be appreciated.

Shouldn't maybe https://github.com/microsoft/vcpkg-tool/pull/339 be rolled back until this issue is fixed? An error seems more helpful to me than incomplete builds.

**Comment by Chronial** [comment]
Ping. I still think rolling back https://github.com/microsoft/vcpkg-tool/pull/339 would be a sensible fix.

**Comment by Sedeniono** [comment]
I agree with @Chronial.

**Comment by smkanadl** [comment]
*Ping*

**Comment by WangWeiLin-MV** [comment]
Duplicate, see #41400
