### ISSUE TITLE
bootstrap-vcpkg.bat exists after BITS Transfer begins

### ISSUE THREAD

**Issue by 123navyblue** [Microsoft/vcpkg#2588]
I haven't been able to boostrap vcpkg for some time. I run bootstrap-vcpkg.bat and BITS Transfer shows up. But after a while the script just exists whithout any message:
![vcpkg_bits_2](https://user-images.githubusercontent.com/15800052/35011968-56e520b6-fb08-11e7-8f76-d1b1ee94178f.png)
Everything used to work well. I've tried to find out which commit is the last one that still works and it seems that 051e6d96e69535d948cfabe7aa66f43f1670d90a is the one.
I'm running on Winodws 7 (64 bit). Both Visual Studio 2015 and 2017 are installed.

Thanks in advance for any help.

**Comment by alexkaratarakis** [comment]
In 3390007020921b41e3d4d42ad9b46c671250743a, I have removed usage of BITS Transfer.
Can you try latest master to see if your issue is resolved?

**Comment by 123navyblue** [comment]
Using the latest master gives this result:
![vcpkg_bits_3](https://user-images.githubusercontent.com/15800052/35113071-82423a54-fc80-11e7-8562-67760f915298.png)
And it doesn't setup/compile/install anything except that it downloads this vswhere package.

**Comment by alexkaratarakis** [comment]
It looks like the download never completes, otherwise you would see:
```
Downloading vswhere...
Downloading vswhere has completed successfully.
```
The file is ~400KB so it should finish quickly, which means something is blocking the download.
I have tested Win7 & Win7 with proxy and it works in both cases for me.

So, there must be something else preventing the downloads. 

- Are you behind a proxy?
- Is the file "C:\\vcpkg2\downloads\vswhere-2.2.11\vswhere.exe" present?
- Can you think of anything else that might be blocking your downloads?

A workaround is to manually download the [file](https://github.com/Microsoft/vswhere/releases/download/2.2.11/vswhere.exe) and place it there, but I suspect whatever is preventing this download will cause subsequent downloads to fail as well.
