### ISSUE TITLE
vcpkg needs better error reporting

### ISSUE THREAD

**Issue by horenmar** [microsoft/vcpkg#2598]
Error saying just
```
Expected ':'
```
meant that I ended up having to read sources to find why it is happening.

**Comment by trylle** [comment]
I had the same problem and had to resort to debugging vcpkg to figure out what the problem was.

In my case, this was a bad CONTROL file for a custom port that included an improper multiline description (missing space on following lines).

Some context for the error would have been nice.

Additionally:
*  I believe this file was accepted by vcpkg before, as it's been a while since I worked on it and do not recall having these issues then.
* I am surprised that a single bad port apparently cripples vcpkg: installing and searching would fail with the same nondescript error until I removed the offending port.

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
