### ISSUE TITLE
vcpkg didn't pull the latest update from cpprestsdk

### ISSUE THREAD

**Issue by bolbol2night** [Microsoft/vcpkg#2610]
A fix was pushed to cpprestsdk to solve an issue in streams.h file on Decembrer 15th, but it is missing when I installed the package January 17th.

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

Since cpprestsdk hasn't released a new version (2.10.1 is still the latest), we're still on that version. However, you can install the latest master by running:
```
vcpkg remove cpprestsdk
vcpkg install cpprestsdk --head
```

Caveat: this is not currently preserved across calls to `vcpkg upgrade`, so you'll need to manually install it with `--head` when upgrading.

**Comment by NancyLi1013** [comment]
@bolbol2night , the latest version of cpprestsdk is updated to 2.10.10 now.
And could you please try it again and help confirm whether it still has the problem?
Thanks!
