### ISSUE TITLE
OpenCV debug mode VideoCapture with file is broken

### ISSUE THREAD

**Issue by patrikhuber** [Microsoft/vcpkg#2613]
I've installed OpenCV 3.4.0 from vcpkg with `opencv[ffmpeg]` (without ffmpeg, it doesn't work either).

In Release and RelWithDebInfo mode, both camera and reading from files (e.g. an .avi file) is fine.
In Debug mode however, reading from the camera works, but not reading from the avi file.

```
    std::string inputvideo("vid.avi)";
    cv::VideoCapture cap;
    if (inputvideo.empty()) {
        cap.open(0); // no file given, open the default camera
    }
    else {
        cap.open(inputvideo);
    }
    if (!cap.isOpened()) {
        std::cout << "Couldn't open the given file or camera 0." << std::endl;
        return EXIT_FAILURE;
    }
```

`cap.isOpened()` fails in this scenario.

The problem also does **not** occur if I build OpenCV by myself (outside of vcpkg) and also not with the binary package from opencv.org.
It also occured on OpenCV 3.3.x in vcpkg.

**Comment by sirexeclp** [comment]
Im having the same issue.
Have you found any workaround yet ?

**Comment by patrikhuber** [comment]
No I haven't, I went back to using my self-compiled version of OpenCV.
I am waiting for a magical fix from the package maintainers to fix this so I can go back to using vcpkg ;-)

**Comment by patrikhuber** [comment]
@ras0219-msft, is there anything we can do? I don't seem to be the only one with this issue, pointing to a problem in the vcpkg OpenCV package. And the camera input not working is quite a big issue.

**Comment by ras0219-msft** [comment]
Ok, so I am actually unable to reproduce this issue (it works in debug for me). Let me share my setup:
```cpp
// main.cpp
#define NOMINMAX
#define WIN32_LEAN_AND_MEAN
#include <cstdio>
#include <opencv2/opencv.hpp>

int main(int argc, char** argv)
{
    if (argc < 2)
        return -1;

    std::string inputvideo(argv[1]);

    cv::VideoCapture cap;

    if (inputvideo.empty()) {
        cap.open(0); // no file given, open the default camera
    }
    else {
        cap.open(inputvideo);
    }
    if (!cap.isOpened()) {
        std::cout << "Couldn't open the given file or camera 0." << std::endl;
        return EXIT_FAILURE;
    }

    getchar();
    return 0;
}
```
```cmake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.10)

project(main CXX)

add_executable(main main.cpp)

find_package(OpenCV REQUIRED)
include_directories(${OpenCV_INCLUDE_DIRS})
target_link_libraries(main PRIVATE ${OpenCV_LIBS})
```

I installed `opencv:x64-windows`, built my program above with the vcpkg toolchain, and tried to load the SAMPLE.avi from [1]. This fails in debug and release, because it needs ffmpeg.

I then installed `opencv[ffmpeg]:x64-windows` and rebuilt the program. It still didn't deploy the ffmpeg dll (*this is a bug we need to fix!*) but that caused failures in _both_ debug and release. Once I manually deployed the `opencv_ffmpeg340_64.dll` to the output folder for my application (found via `vcpkg owns _ffmpeg`), both debug and release ran correctly.

I suspect you might have some other OpenCV DLLs available elsewhere in your path, which are getting loaded and cause issues only in debug mode, but that's just a guess.

[1] http://www.technical-recipes.com/2011/displaying-avi-video-using-opencv/

**Comment by patrikhuber** [comment]
I can confirm that it now works in all three modes - `Release`, `Debug` and `RelWithDebInfo`, and for camera as well as video files.
The key was indeed to copy & paste `opencv_ffmpeg340_64.dll` over to the build folder. I did not do that before, which caused it to fail.

Thank you very much again for helping to investigate. Finally back to using vcpkg :-)
