### ISSUE TITLE
vcpkg manifest mode results in excessive rebuilds under msvc [Binary caching]

### ISSUE THREAD

**Issue by Qbort** [microsoft/vcpkg#26346]
I have been using vcpkg manifest mode with visual studio and cmake projects and it generally has been useful. However it results in excessive rebuilds of dependencies whenever the visual studio version is updated (e.g. from version 17.2.x to 17.3.x) to the point that I stopped using it. This seems to be related to binary caching as there is an excessive amount of detail hashed as part of the verification (ref [implementation notes](https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md#implementation-notes-internal-details-subject-to-change-without-notice))

This is understandable for linux where ABI compatibility is not guaranteed, but not for windows and visual studio versions >2015 where binary compatibility has been guaranteed for some time. According to https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-170 :
> You can mix binaries built by different versions of the v140, v141, v142, and v143 toolsets. However, you must link by using a toolset at least as recent as the most recent binary in your app. Here's an example: you can link an app compiled using any 2017 toolset (v141, versions 15.0 through 15.9) to a static library compiled using, say, Visual Studio 2019 version 16.2 (v142). You just have to link them by using a version 16.2 or later toolset. You can link a version 16.2 library to a version 16.4 app as long as you use a 16.4 or later toolset.

### Temporary workaround - disable manifest mode and use registries

In case it is useful for someone else, the workaround is to disable manifest mode as follows:
 -  Set the cmake variable `VCPKG_MANIFEST_MODE` to `OFF`
 - Copy the vcpkg-configuration.json from your project directory to the vcpkg root directory
 - Manually install all dependencies listed in your vcpkg.json (`.\vcpkg install [dependency1] [depency2] [etc]`) and upgrade to ensure the version in your vcpkg-configuration.json is being used (`.\vcpkg upgrade --no-dry-run`)
  
Obviously you loose all the benefits of having of manifest mode but his ensures that whenever your visual studio version is updated, the packages aren't rebuilt automatically. I haven't experienced any issues in doing this and I would like to see binary caching being less restrictive for msvc compilers with cmake.

**Comment by Osyotr** [comment]
This might help you: https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_disable_compiler_tracking

**Comment by PhoebeHui** [comment]
@Qbort, have you tried the flag provided by Osyotr? It should solve such cases. it will ignore compiler version in ABI tracking in binary caching.

**Comment by dalboris** [comment]
@PhoebeHui Is there a similar setting to also disable tracking changes in the CMake version? Indeed, the hosted runners of GitHub Actions change CMake versions quite frequently (e.g., 3.24.2 to 3.24.3), which seems to trigger vcpkg cache invalidation. See: https://github.com/vgc/vgc/issues/700#issuecomment-1315781664

**Comment by Osyotr** [comment]
@dalboris I use `-DVCPKG_INSTALL_OPTIONS=--x-abi-tools-use-exact-versions`

**Comment by dalboris** [comment]
@Osyotr Thanks for the hint, but I didn't manage to make it work unfortunately.

I have the following environment variables:

```
VCPKG_DEFAULT_BINARY_CACHE = D:\a\vgc\vgc\vcpkg\archives
VCPKG_ROOT = D:\a\vgc\vgc\vcpkg
```

In the vcpkg binary cache, I have previously compiled versions of my dependencies (stored and retrieved via GitHub Actions Cache), but presumably with another version of CMake.

My CMake command looks like:

```
cmake .. -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" -DVCPKG_INSTALL_OPTIONS=--x-abi-tools-use-exact-versions -DVCPKG_DISABLE_COMPILER_TRACKING=ON
```

I get the following (shortened) output:

full link (see "Configure" step): https://github.com/vgc/vgc/actions/runs/3491412294/jobs/5844014864

```
cmake version 3.24.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
-- Running vcpkg install
A suitable version of cmake was not found (required v3.24.0). Downloading portable cmake v3.24.0...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake-3.24.0-windows-i386.zip -> D:\a\vgc\vgc\vcpkg\downloads\cmake-3.24.0-windows-i386.zip
Extracting cmake...
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.2.6). Downloading portable powershell-core v7.2.6...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.2.6/PowerShell-7.2.6-win-x86.zip -> D:\a\vgc\vgc\vcpkg\downloads\PowerShell-7.2.6-win-x86.zip
Extracting powershell-core...
The following packages will be built and installed:
  * brotli[core]:x64-windows -> 1.0.9#3
  * bzip2[core,tool]:x64-windows -> 1.0.8#3
    freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.12.1#2
    harfbuzz[core]:x64-windows -> 5.0.1#2
  * libpng[core]:x64-windows -> 1.6.37#19
  * vcpkg-cmake[core]:x64-windows -> 2022-09-26
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06#1
  * vcpkg-tool-meson[core]:x64-windows -> 0.63
  * zlib[core]:x64-windows -> 1.2.12#2
Additional packages (*) will be modified to complete this operation.
Restored 0 package(s) from D:\a\vgc\vgc\vcpkg\archives in [74](https://github.com/vgc/vgc/actions/runs/3491412294/jobs/5844014864#step:15:75)1 us. Use --debug to see more details.
Installing 1/9 vcpkg-cmake:x64-windows...
```

So we can see that vcpkg (invoked from cmake 3.24.2), tried to install CMake 3.24.0 and powershell for some reason. But anyway, it still doesn't re-use the binary cache (see "Restored 0 package(s) from D:\a\vgc\vgc\vcpkg\archives"), and instead recompiles everything.

All I want is for vcpkg (invoked from cmake in manifest mode), to completely ignore the current version of cmake and msvc, and use the available binary cache, is this possible? I feel at the point the only thing that is going to work is to disable manifest mode, which is sad since conceptually, manifest mode makes sense. I just don't want it to depend on my version of cmake or msvc, or powershell, etc.... it makes no sense, the binary generated will be compatible anyway.

**Comment by Osyotr** [comment]
> `-DVCPKG_DISABLE_COMPILER_TRACKING=ON`

This will not work. The variable should be set from inside a triplet file.
Also note that modifying triplet file will invalidate binary cache.

> So we can see that vcpkg (invoked from cmake 3.24.2), tried to install CMake 3.24.0 and powershell for some reason

This is intentional. Vcpkg uses its own copy of cmake and powershell to build packages. `--x-abi-tools-use-exact-versions` flag makes sure that vcpkg will not chose other version of cmake that would imply cache miss.

> All I want is for vcpkg (invoked from cmake in manifest mode), to completely ignore the current version of cmake and msvc, and use the available binary cache, is this possible?

Currently there is no way to explicitly exclude entries from `vcpkg_abi_info.txt`.
However, there is a way to avoid cache misses:
1) `set(VCPKG_DISABLE_COMPILER_TRACKING ON)` in your custom triplet
2) Pass `--x-abi-tools-use-exact-versions` to vcpkg install (via `-DVCPKG_INSTALL_OPTIONS=--x-abi-tools-use-exact-versions`)
2) Use the same version of vcpkg-scripts on every machine (e.g. vcpkg repo is checked out at the same commit)
3) Use baselines
I'm following these steps and only rebuild libraries when I update baseline or patch ports.

**Comment by dalboris** [comment]
Thank you a lot for this detailed answer @Osyotr, it really helps getting the right mental model, as I find the official documentation confusing.

> The variable should be set from inside a triplet file.

Thanks, I didn't realize triplet files was a thing, as I always used the built-in triplets. I'll take the time to learn about those so I know where to write the line `set(VCPKG_DISABLE_COMPILER_TRACKING ON)`.


> 2. Pass --x-abi-tools-use-exact-versions to vcpkg install (via -DVCPKG_INSTALL_OPTIONS=--x-abi-tools-use-exact-versions)
> 3. Use the same version of vcpkg-scripts on every machine (e.g. vcpkg repo is checked out at the same commit)

Yep, I was doing 3. for a long time, and now doing 2. as well. Thanks for your explanation of how `--x-abi-tools-use-exact-versions` works, it clears things up. In the future, I hope there will be more options to control binary caching, so we could simply tell what should participate in the binary caching hash key. It seems wasteful to download different versions of cmake/powershell just so that the cache key becomes the same: it makes more sense to me to simply not include the versions of cmake and powershell in the cache key, since they're not supposed to affect the compiled binaries. The compiler version is more debatable: personally I'd prefer only recompiling if the major version of the compiler changes (so that it recompiles less often), but I can see why someone would want to recompile even on minor/patch versions, as bug fixes in the compiler may improve the compiled binaries.

> 4. Use baselines

I'll have to learn about this, thanks for the pointer.

**Comment by dalboris** [comment]
Hi @Osyotr , thanks again for your help, I think I got it working now. For anyone interested, I have at the repo below a (reasonably) minimal  example implementing the ideas discussed here:

https://github.com/dalboris/test-cpp-github-actions/blob/master/.github/workflows/windows.yml

An even more minimal example would be the following, where we assume that there is a `CMakeLists.txt` and `vcpkg.json` file at the root of your repository:

```
name: Windows

on: [push, pull_request]

env:
  BUILD_TYPE: Release
  MSVC_VERSION: 2019
  VCPKG_VERSION: 2022.05.10
  VCPKG_INSTALL_OPTIONS: --x-abi-tools-use-exact-versions
  VCPKG_BUILD_TYPE: release
  VCPKG_DISABLE_COMPILER_TRACKING: ON

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-2019

    steps:

    - uses: actions/checkout@v2

    - name: Configure vckpg
      run: |
        echo "VCPKG_ROOT_PARENT=${{github.workspace}}" >> $GITHUB_ENV
        echo "VCPKG_ROOT=${{github.workspace}}/vcpkg" >> $GITHUB_ENV
        echo "VCPKG_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV
        echo "VCPKG_OVERLAY_TRIPLETS=${{github.workspace}}/vcpkg/custom-triplets" >> $GITHUB_ENV
        echo "VCPKG_DEFAULT_TRIPLET=custom-x64-windows" >> $GITHUB_ENV
        echo "VCPKG_DEFAULT_BINARY_CACHE=${{github.workspace}}/vcpkg/archives" >> $GITHUB_ENV

    - name: Cache vcpkg
      id: cache-vcpkg
      uses: actions/cache@v3
      with:
        path: ${{env.VCPKG_ROOT}}
        key: vcpkg=${{env.VCPKG_VERSION}}-msvc=${{env.MSVC_VERSION}}-json=${{hashFiles('vcpkg.json')}}

    - if: ${{ steps.cache-vcpkg.outputs.cache-hit != 'true' }}
      name: Bootstrap vcpkg and install packages (if cache miss)
      working-directory: ${{env.VCPKG_ROOT_PARENT}}
      run: |
        git clone --depth=1 --branch "$VCPKG_VERSION" https://github.com/microsoft/vcpkg.git
        cd vcpkg
        mkdir archives
        mkdir "$VCPKG_OVERLAY_TRIPLETS"
        TRIPLET_FILE="$VCPKG_OVERLAY_TRIPLETS/$VCPKG_DEFAULT_TRIPLET.cmake"
        cp triplets/x64-windows.cmake "$TRIPLET_FILE"
        echo "set(VCPKG_BUILD_TYPE $VCPKG_BUILD_TYPE)" >> "$TRIPLET_FILE"
        echo "set(VCPKG_DISABLE_COMPILER_TRACKING $VCPKG_DISABLE_COMPILER_TRACKING)" >> "$TRIPLET_FILE"
        cmd.exe /c bootstrap-vcpkg.bat
        vcpkg.exe \
          --vcpkg-root="$VCPKG_ROOT" \
          --overlay-triplets="$VCPKG_OVERLAY_TRIPLETS" \
          --triplet="$VCPKG_DEFAULT_TRIPLET" \
          $VCPKG_INSTALL_OPTIONS \
          install

    - name: Setup Developer Command Prompt for VS
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure
      working-directory: ${{github.workspace}}
      run: |
        mkdir build
        cd build
        cmake --version
        cmake .. \
          -G Ninja \
          -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
          -DCMAKE_TOOLCHAIN_FILE="$VCPKG_TOOLCHAIN_FILE" \
          -DVCPKG_OVERLAY_TRIPLETS="$VCPKG_OVERLAY_TRIPLETS" \
          -DVCPKG_TARGET_TRIPLET="$VCPKG_DEFAULT_TRIPLET" \
          -DVCPKG_INSTALL_OPTIONS="$VCPKG_INSTALL_OPTIONS"

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build .
```

**Comment by nilsnolde** [comment]
fwiw, here's the workflow I ended up with: https://github.com/valhalla/valhalla/blob/b665a1b11d2dc5a9d1ffcfebd17ef51e871706fb/.github/workflows/win.yml. the main difference to above is:
- don't run an explicit `vcpkg install`, it's not necessary, the cmake configuration step will do the installation (potentially a second time if you run it manually before)
- don't cache all of it, exclude the huge subdirectories vcpkg doesn't need to install things from cache

all in all, I love vcpkg, but all these different ways of installing things these days is VERY confusing. and there's no good docs I came across explaining things neatly. I do **NOT** want a nuget server haha and I don't want the "fancy" vcpkg binary caching which seems not working too properly with github actions. I just want some transparent path of a directory which I can cache and restore. however, the caveat is that the above way might break some day if anything changes in scope of the subdirectories.

I wrote down some comments for my future self, maybe it helps someone (if I got things right even..): https://github.com/valhalla/valhalla/pull/4573#discussion_r1482109484
