### ISSUE TITLE
[libmariadb] build failure

### ISSUE THREAD

**Issue by beats-dh** [microsoft/vcpkg#26366]
**Host Environment**
- OS: Ubuntu 22.04 ARM64
- OS: Ubuntu 22.04

**To Reproduce**
`./vcpkg install libmariadb[mariadbclient]`

**Failure logs**
-config-arm64-linux-CMakeCache.txt.log: https://pastebin.com/1dSuBgg5
-config-arm64-linux-out.log: https://pastebin.com/z7cpZwiB

**Additional context**
This error started after the commit: https://github.com/microsoft/vcpkg/commit/581099d541ec960db5c2a8efe4639f1e2e25de60

![image](https://user-images.githubusercontent.com/61994374/184758853-f61c68ac-e0a5-40e7-98fd-e41a43877309.png)

**Comment by Adela0814** [comment]
This is caused by Ninja. If the version is equal or greater than `1.9.0`, which will trigger this issue if we use ninja to build the ports on Windows.

Currently, there are several ports that will build fail due to this reason.
For the root cause of this kind of issue, please see https://github.com/microsoft/vcpkg/pull/10964#issuecomment-656362040.

**Comment by BenDol** [comment]
Having the same issue

**Comment by Kodpact** [comment]
Only Windows? I'm getting error on WSL 2 Ubuntu 20

**Comment by DanMargera** [comment]
I'm having the same problem. I've investigated a little bit and found these two PRs that fix similar problems in other ports:
PR [#13982](https://github.com/microsoft/vcpkg/pull/13982) - fixed it for portaudio
PR [#13401](https://github.com/microsoft/vcpkg/pull/13401) - fixed it for tmx 

Did anyone have any luck in finding a workaround?
