### ISSUE TITLE
Export package without its dependencies

### ISSUE THREAD

**Issue by amc522** [Microsoft/vcpkg#2640]
It would be nice to export a package without any of its dependencies. For example, I would like to export the headers and built libraries for libpng, but I would like to have all the dependencies (zlib headers and binaries excluded).

**Comment by jasjuang** [comment]
Just curious what's the use case for this feature? Without the dependencies the exported libs wouldn't work.

**Comment by amc522** [comment]
I keep all the thirdparty dependencies for my project in the project source tree. Instead of putting all header files in one include directory, libs all in one lib directory, etc., each thirdparty dependency has its own folder. Just the way I like to organize things. I've been using the export feature to copy packages from the vcpkg directories to my projects directory.

Alternatively, if there was a command in vcpkg that listed the files of each package (without its dependencies), that would work as well.

**Comment by amc522** [comment]
I just discovered vcpkg owns. This solves my problems of identifying the files that belong to each package. Sorry for the confusion.

**Comment by SNiLD** [comment]
> I just discovered vcpkg owns. This solves my problems of identifying the files that belong to each package. Sorry for the confusion.

What solved the problem?

I have the same issue where we store bin, lib and include per library separately in our own repository and we have our own CMake system that fetches these libraries. But doing `vcpkg export <lib> --raw` exports also the dependency libraries/includes/pdbs so I can't just copy the directories directly.

**Comment by SNiLD** [comment]
Turns out there's list of files installed by each package in the `vcpkg-export\installed\vcpkg\info\package-triplet.list` file. So I made a batch file that copies files referenced here to a separate directory. 

Here is the batch file (`strip_export.bat`) located in vcpkg root directory (where vcpkg.exe is):
```
@echo off
set export_directory=%~f1
set export_library=%2
set full_file=vcpkg/info/%export_library%.list

pushd %export_directory%\installed
mkdir %export_directory%\stripped
setlocal enabledelayedexpansion
for /F "tokens=*" %%A in (vcpkg/info/%export_library%.list) do (
    set "file_name=%%~dfA"
    set "file_path=%%~dpA"
    set "relative_file_path=!file_path:%CD%\=!"
    xcopy /Y !file_name! %export_directory%\stripped\!relative_file_path!
)
endlocal
popd
```

Usage: `strip_export.bat <export_directory> <export_list_name>`

For example I have exported GDAL with `vcpkg export gdal --triplet=x64-windows-gdal --raw` command and renamed the export directory to `vcpkg-export-gdal-2.4.1-13`. I would run the strip batch file like this: `strip_export.bat vcpkg-export-gdal-2.4.1-13 gdal_2.4.1_x64-windows-gdal`

This results in `vcpkg-export-gdal-2.4.1-13\stripped` directory that contains only the files that come from GDAL package but not the dependencies.

**Comment by Thieum** [comment]
> Just curious what's the use case for this feature? Without the dependencies the exported libs wouldn't work.

It would prevent multiple versions of the same dependency in the dependency graph, for a project that would install different exports.

Consider libpng depending on zlib. If I install another export from another lib that depends on zlib, or an export of zlib by itself, they could conflict with one another.

Without this possibility, the only safe way to handle exports a a consumer is to consume only one a time in a project.
