### ISSUE TITLE
wxWidgets: "webview" feature does not work correctly

### ISSUE THREAD

**Issue by fishnet37222** [microsoft/vcpkg#26466]
**Describe the bug**
When using the "webview" feature of the wxWidgets port on Windows, calling "wxWebView::IsBackendAvailable(wxWebViewBackendEdge)" returns false.

**Environment**
- OS: Windows 10/11
- Compiler: Visual Studio 2022

**To Reproduce**
1. Make sure vcpkg is installed and integrated with Visual Studio
2. Build and run the attached project.

**Expected behavior**
The application window has an empty wxWebView control in it.

**Failure logs**
There are no failure logs, but I wrote the sample to display a label with the message "Edge backend is not available!" if the Edge backend isn't available.

**Additional context**
If I manually copy "WebView2Loader.dll" to the project's output folder, the application works as expected.

[WebViewTest.zip](https://github.com/microsoft/vcpkg/files/9394614/WebViewTest.zip)

**Comment by LilyWangLL** [comment]
I try to reproduce this issue locally, but I install `wxwidgets` failed, the related issue: https://github.com/microsoft/vcpkg/issues/25479, I will confirm this issue soon.

**Comment by pndsimpson** [comment]
I have had the same issue. 
It can be fixed by linking WebView2 statically, which requires modifying the port. I have a local patch for this, which I can convert to a PR against the main repository, if desired.
In my patch I only enable static linking of WebView2 if wxwidgets is linked statically, I have not tried linking wxwidgets dynamically. Maybe the static linkig of webview2 should be a separate feature?

**Comment by dg0yt** [comment]
> If I manually copy "WebView2Loader.dll" to the project's output folder, the application works as expected.

This is an indication that this DLL is loaded as a plugin. Plugins are not deployed automatically for vcpkg (except for Qt and magnum).
