### ISSUE TITLE
[zlib] patch CVE-2022-37434

### ISSUE THREAD

**Issue by Faaux** [microsoft/vcpkg#26790]
Library name: zlib

zlib through 1.2.12 (newest in VCPKG afaik) is currently vulnerable by: CVE-2022-37434

- Already fixed upstream but not released yet: https://github.com/madler/zlib/issues/692
- NixOS used this patch: https://github.com/NixOS/nixpkgs/pull/185693

Any chance we can get an update for this?

**Comment by FrankXie05** [comment]
@Faaux Thanks for posting this issue.
This is indeed a serious and urgent bug, but `zlib` has been fixed in a short time. Although the release of a new version can guarantee the downstream error adaptation. But new releases may be too hasty for zlib, apparently they are not ready yet.
The best solution so far is to apply a patch. :)

**Comment by Neustradamus** [comment]
@madler has done the new build, the 1.2.13 has been released with the CVE-2022-37434 fix.
