### ISSUE TITLE
Error finding Imath headers when including certain OpenEXR headers.

### ISSUE THREAD

**Issue by amc522** [microsoft/vcpkg#27076]
**Describe the bug**
When compiling a file including certain OpenEXR headers. there are errors about not being able to find Imath related headers. This is in a Visual Studio 2022 project running with vcpkg manifest mode.

**Environment**
- OS: Windows 10
- Compiler: Visual Studio 2022 17.3.5
- vcpkg running in manifest mode in a visual studio project

**To Reproduce**
1. Create new visual studio c++ project
2. Create vcpkg.json with openexr dependency in the project directory
3. Switch the project to vcpkg manifest mode
4. Create a .cpp file in the visual studio project with the line `#include<OpenEXR/ImfHeader.h>`
5. See compilation error `ImfHeader.h(22,10): fatal  error C1083: Cannot open include file: 'ImathVec.h': No such file or directory`

**Expected behavior**
There should be no compilation errors. Include paths should be setup correctly by vcpkg.

**Failure logs**
`ImfHeader.h(22,10): fatal  error C1083: Cannot open include file: 'ImathVec.h': No such file or directory`

**Additional context**
Example project is included.
[OpenEXR_Test.zip](https://github.com/microsoft/vcpkg/files/9693325/OpenEXR_Test.zip)

**Comment by amc522** [comment]
Thanks for the information. But that doesn't solve the problem. I understand that `imath` is a separate library and it is marked as dependency for `openexr`. So `imath` and `openexr` are successfully installed by vcpkg, but the include paths are not setup correctly. I should be able to use `openexr` without having to setup any extra include paths. `vcpkg` should be taking care of that.

**Comment by dg0yt** [comment]
I see, `ImfHeader.h` (from openexr) does `#include <ImathVec.h>` from imath, but Imath headers are installed to `include/Imath`.

> I should be able to use `openexr` without having to setup any extra include paths. `vcpkg` should be taking care of that.

Use CMake? This works well in CMake toolchains because the packages' cmake config files take care include path setup. (And they take care of all the transitive usage requirements, as configured via features and depedencies.)

Without CMake, there is nothing which would automatically add the additional include path (`.../include/Imath`) which is needed to make it work AFAIK. This is a common issue with include files in subdirs, as often used by big packages.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
