### ISSUE TITLE
Debian11(bulleye) install  the kitty terminal

### ISSUE THREAD

**Issue by knigth95** [microsoft/vcpkg#27140]
The wayland-protocols package on your system is missing the staging/xdg-activation/xdg-activation-v1.xml protocol definition file
Disabling building of wayland backend
os version:Linux king 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
debian11(bulleye)
install command: 
git clone https://github.com/kovidgoyal/kitty && cd kitty
ls
make
vcpkg version：apt 2.2.4(amd64)
error log:
command "make" end :+1: 
take place error:
The wayland-protocols package on your system is missing the staging/xdg-activation/xdg-activation-v1.xml protocol definition file
Disabling building of wayland backend

and then used command:  sudo apt install wayland-protocols
result: the wayland-protocols version is already up to date

**Comment by Cheney-W** [comment]
Could you please describe in detail the problem you encountered? Please include the following information:
1. OS version.
2. vcpkg version.
3. Install command.
4. Error log.

**Comment by knigth95** [comment]
> Could you please describe in detail the problem you encountered? Please include the following information:
> 
> 1. OS version.
> 2. vcpkg version.
> 3. Install command.
> 4. Error log.



> 您能详细描述一下您遇到的问题吗？请提供以下信息：
> 
> 1. 操作系统版本。
> 2. vcpkg version.
> 3. 安装命令。
> 4. 错误日志。

issues have been updated

**Comment by Cheney-W** [comment]
This issue is not a vcpkg issue.
[vcpkg](https://github.com/Microsoft/vcpkg) is a C++ Library Manager for Windows, Linux, and MacOS. Vcpkg helps you manage C and C++ libraries on Windows, Linux and MacOS. This tool and ecosystem are constantly evolving, and we always appreciate contributions!

If you've never used vcpkg before, or if you're trying to figure out how to use vcpkg, check out our [Getting Started](https://github.com/Microsoft/vcpkg#getting-started) section for how to start using vcpkg.

**Comment by knigth95** [comment]
![Uploading 1.png…]()
