### ISSUE TITLE
bootstrap command fails

### ISSUE THREAD

**Issue by redstag91** [Microsoft/vcpkg#2734]
On Windows 10 with VS 2017 running .\bootstrap-vcpkg.bat results in:

PS C:\src\vcpkg> .\bootstrap-vcpkg.bat
Copy-Item : Der Pfad "C:\src\vcpkg\toolsrc\Release\vcpkg.exe" kann nicht gefunden werden, da er nicht vorhanden ist.
In C:\src\vcpkg\scripts\bootstrap.ps1:66 Zeichen:1
+ Copy-Item $vcpkgSourcesPath\Release\vcpkg.exe $vcpkgRootDir\vcpkg.exe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\src\vcpkg\toolsrc\Release\vcpkg.exe:String) [Copy-Item], ItemNotFoun
   dException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : Der Pfad "C:\src\vcpkg\toolsrc\Release\vcpkgmetricsuploader.exe" kann nicht gefunden werden, da er nicht
vorhanden ist.
In C:\src\vcpkg\scripts\bootstrap.ps1:67 Zeichen:1
+ Copy-Item $vcpkgSourcesPath\Release\vcpkgmetricsuploader.exe $vcpkgRo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\src\vcpkg\to...icsuploader.exe:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Path "C:\src\vcpkg\toolsrc\Release\vcpkg.exe" is not found because it is not there, also does not seem to be there in git at all. After failing to install powershell.exe is strangely identified as a threat by my antivirus (happens both in Avast and AVG).

**Comment by automaton-samir** [comment]
Same issue happens to me right now. 


Microsoft (R) Build Engine version 15.5.180.51428 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 06/02/2018 4:15:11 PM.
Copy-Item : Cannot find path 'D:\Program Files\vcpkg\toolsrc\Release\vcpkg.exe' because it does not exist.
At D:\Program Files\vcpkg\scripts\bootstrap.ps1:66 char:1
+ Copy-Item $vcpkgSourcesPath\Release\vcpkg.exe $vcpkgRootDir\vcpkg.exe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\Program File...lease\vcpkg.exe:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : Cannot find path 'D:\Program Files\vcpkg\toolsrc\Release\vcpkgmetricsuploader.exe' because it does not
exist.
At D:\Program Files\vcpkg\scripts\bootstrap.ps1:67 char:1
+ Copy-Item $vcpkgSourcesPath\Release\vcpkgmetricsuploader.exe $vcpkgRo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\Program File...icsuploader.exe:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

**Comment by automaton-samir** [comment]
Disable avast.

**Comment by redstag91** [comment]
Seems to do the trick, thanks.
