### ISSUE TITLE
[nu-book/zxing-cpp] update to 1.4.0

### ISSUE THREAD

**Issue by duanqn** [microsoft/vcpkg#27704]
Library name:
zxing-cpp
New version number:
1.4.0
Other information that may be useful (release notes, etc...)
The repository has been moved from nu-book/zxing-cpp to zxing-cpp/zxing-cpp. Can we rename the package to remove the organization name in it? It will make it easier for people to find it.

**Comment by Cheney-W** [comment]
Do the two repositories store the same source? If yes, then you don't need to change the name, if not, then you need to change it.
Because changing the name will affect the work of `versioning feature` , but also affect its upstream and downstream port (if any), so if it is not very necessary, then generally do not actively change the name.

**Comment by duanqn** [comment]
Yeah I agree changing names will introduce more cost. The two repositories store the same code so it's not necessary to change the name now.
