### ISSUE TITLE
vcpkg-configuration.json not following git registry baseline commit?

### ISSUE THREAD

**Issue by martingalvan-nordic** [microsoft/vcpkg#27852]
**Describe the bug**
I have a project which uses a vcpkg git registry that I maintain myself. In the project's vcpkg-configuration.json I set a commit hash for the registry's "baseline" field; however, whenever I try to grab dependencies from the registry I see that the registry's HEAD is used instead of the baseline commit.

**Environment**
- OS: Windows, Linux, macOS.

**To Reproduce**
1. Set up a vcpkg git registry, with two commits C1 and C2, both containing different portfiles for a dependency. C1 is the latest master, and C2 is the latest commit on a different branch.
2. Set up a project which grabs its dependencies from the registry on step 1, and use C2 for the "baseline" field on vcpkg-configuration.json, i.e.

```
"registries": [
  {
    "kind": "git",
    "repository": "https://github.com/my-registry",
    "baseline": "C2_hash",
    "packages": [ "my_dependency" ]
  }
]
```
3. Install the dependency for the project (e.g. by building it using CMake and manifest mode).

**Expected behavior**
vcpkg will install the dependency as specified in commit C2 of the registry.

**Actual behavior**
vcpkg ignores commit C2 completely, and always grabs the latest master instead (i.e. C1).

**Additional context**
From https://vcpkg.io/en/docs/maintainers/registries.html#git-registries I see the following:

> Since your user will set their baseline to a commit ID, that commit ID must always exist, and be accessible from your HEAD commit, which is what is actually fetched. This means that your HEAD commit should be a child of all previous HEAD commits. 

Does that mean that the "baseline" hash can only correspond to a commit on master? If so, this is even less useful than I thought. See also https://github.com/microsoft/vcpkg/issues/27583

**Comment by martingalvan-nordic** [comment]
Hi @Cheney-W @BillyONeal, I'm pinging this issue since I haven't gotten a response yet. Is there anyone currently looking at this? Thanks.

**Comment by jespergustinmsft** [comment]
Hi @Cheney-W and @BillyONeal! This seems to be an issue still. Any updates? We recently moved to vcpkg and just bumped into this issue today. This issue will start causing headaches for us very soon when we have different branches in our repo pointing to different baselines.

//Best regards, Jesper [MSFT]

**Comment by BillyONeal** [comment]
The intended design is:

The version database used comes from the fetched HEAD ref. The baseline selects versions that exist within that version database, subject to constraints placed upon the version selection.

So given:

```
main -> z_v2_added -> x_v2_added -> baseline -> z_v1_added -> y_v1_added -> x_v1_added
```

and

```
{
    "dependencies": ["x", "y", "z"]
    "vcpkg-configuration": {
        "registries": [{
            "ref": "main",
            "baseline": "baseline",
            "ports": ["x", "y", "z"]
        }]
    },
    "overrides": [
        {
            "name": "x",
            "version": "2"
        }
    ]
}
```

This will select x = 2, y = 1, z = 1, according to the version database located in main, because the baseline says x = 1, y = 1, z = 1, but x is overridden to be 2.

Are you seeing behavior different than this? (Your issue says that vcpkg looks at master, but doesn't talk about what versions are selected, so it isn't clear if the problem is that we fetched that in the first place or that we selected incorrect versions...)

**Comment by martingalvan-nordic** [comment]
Hi @BillyONeal, I think the difference is that I don't have a `"ref"` field within `"registries"`. My understanding was that the `"baseline"` commit simply told vcpkg which versions of the portfiles to grab, but from your comment I see that it's more complex than that.

**Comment by jespergustinmsft** [comment]
Hi @BillyONeal!

How come x is v2 but not z since main has both z and x as v2 according to the graph you provided?

And can you also please clarify - a commit is unique and can only hold one set of changes, so what is the purpose of "ref" when "baseline" points out a specific commit that should be used? I fail to understand how you should be able to provide two conflicting commits to be used.

//Best regards, Jesper [MSFT]

**Comment by BillyONeal** [comment]
> I think the difference is that I don't have a `"ref"` field within `"registries"`.

**Comment by BillyONeal** [comment]
> I think the difference is that I don't have a `"ref"` field within `"registries"`.

Then I believe it will be whatever head ref that repo advertises.

> How come x is v2 but not z since main has both z and x as v2 according to the graph you provided?

Because the version selections come from the baseline, and the baseline said they are all v1.

> And can you also please clarify - a commit is unique and can only hold one set of changes, so what is the purpose of "ref" when "baseline" points out a specific commit that should be used?

The version database comes from <s>"ref"</s>"reference". The version database must name any and all versions reachable ever. "baseline" names a floor on which versions will be used; you can get versions that disagree with the baseline either through overrides or constraints.

> EDIT: Also - [documentation](https://learn.microsoft.com/en-us/vcpkg/users/registries) mentions nothing about this "ref" property!?

Sorry, that's what I get for doing an example without actually trying it. It should be "reference" rather than "ref": https://github.com/microsoft/vcpkg-tool/blob/7c1708eaeb1f87126ec808e9fe0f6bc7cb2c72ec/docs/vcpkg-schema-definitions.schema.json#L600 . If not specified it's whatever the head ref that git repo says is.
