### ISSUE TITLE
gflags applying patch fails

### ISSUE THREAD

**Issue by patrikhuber** [Microsoft/vcpkg#2796]
```
Building package gflags[core]:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/Users/Patrik/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/Users/Patrik/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/Patrik/vcpkg/packages/gflags_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/Patrik/vcpkg/buildtrees/gflags
-- CURRENT_PORT_DIR=C:/Users/Patrik/vcpkg/ports/gflags/.
-- Downloading https://github.com/gflags/gflags/archive/v2.2.1.tar.gz...
-- Downloading https://github.com/gflags/gflags/archive/v2.2.1.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/Users/Patrik/vcpkg/downloads/gflags-gflags-v2.2.1.tar.gz
-- Extracting done
-- Applying patch C:/Users/Patrik/vcpkg/ports/gflags/revert-fix-install.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/Patrik/vcpkg/ports/gflags/revert-fix-install.patch done
```

I don't think this should fail, as it's my first time installing gflags.

**Comment by ras0219-msft** [comment]
This is expected behavior, unfortunately.

There was a problematic patch applied previously. The fix was to remove the patch, however any _existing_ users already had the patch applied. Therefore, this patch _reverts_ the other patch, but only if it was installed. You're absolutely right to open this issue based on the message, though, so thank you very much!

(We don't want to simply always apply the old patch and the new one, because they'll just constantly thrash the code forwards and backwards ;p)

**Comment by patrikhuber** [comment]
Haha! Oh crap... what a situation :-)))
