### ISSUE TITLE
Ceres featurepackages support

### ISSUE THREAD

**Issue by patrikhuber** [Microsoft/vcpkg#2798]
Hi!

It would be great if the `Ceres` package supported optional features.

For example, `metis` is an optional part of Ceres, and not needed. It is quite a large package.

Second, `openblas` is also an optional dependency. In fact, it's quite huge. It downloads strawberry-perl, which apparently is a 32-bit portable version of Perl. It took ages to download and install and I don't even want to know how big it is. And now openblas has been building for the past half hour.

Third, suitesparse could also be made optional. It's not very large though and compiles "fairly" quickly so not a too huge issue, compared to the others.

It seems to me that the "Configuring" steps for glog is also taking quite a long time, not sure what's going on there, but the build is then rather quick.

In contrast to that, a lightweight, functional Ceres build only takes 5 or so minutes to compile with no additional downloads needed.

**Comment by jasjuang** [comment]
metis, openblas and suitesparse are all included before the introduction of "feature packages" and no one really goes back to separate it. 

IMO we shouldn't abuse the usage of feature packages, otherwise there is just too much combination to test out and make sure everything works prior to submit a PR to update a port, also it will be very cumbersome on the maintainer's end to get the CI to work properly.

IMO the solution to your main problem of "taking too long to compile" should be by upgrading the functionality of `vcpkg export` to the level of the convenience of what the linux ppa is, so you only have to build the libraries on an AWS server, it can be building while you are sleeping, not draining your cpu power when you are working, and it will be upgraded periodically by a cronjob automatically. In your downstream computer, you can simply do something equivalent to `sudo apt install ceres` and it will pull the libs/dlls/headers in the vcpkg `installed` from your server.

**Comment by patrikhuber** [comment]
> metis, openblas and suitesparse are all included before the introduction of "feature packages" and no one really goes back to separate it.

I think that's not a good argument :-)

I agree with your point actually that the featurepackages feature shouldn't be too abuse as to not create too many combinations to test. But these are things that make a huge difference in compile time, space requirements (we're talking 0.5-1 hour and megabytes/gigabytes here - and yes gigabytes are relevant in the age of laptops that only have (small-ish) SSDs); and I am guessing they will also make quite a difference in the library's deployed sizes, which is quite relevant actually. So the problem is not just "taking too long to compile".

I disagree a bit with your point on building on AWS. What if I want to build with the latest VS2017 or 2017 Preview. Sure I can build it by hand, but that defies the usefulness of vcpkg. Of course right now vcpkg builds everything so that it's ABI compatible with VS2015U3 - but once the next ABI-breaking VS toolchain version comes out, vcpkg will need a solution for that. And then I might want to build for the latest version, which in your scenario might not be on AWS.

So I think to summarise, I agree featurepackages shouldn't be abused for the reasons you mention, but for quite big things, like opencv / opencv-contrib, and ceres with/without metis/openblas (which pulls in even perl etc.), it is the perfectly right tool, and if featurepackages are not meant for this, what are they meant for then.

**Comment by ras0219-msft** [comment]
> IMO we shouldn't abuse the usage of feature packages, otherwise there is just too much combination to test out and make sure everything works prior to submit a PR to update a port, also it will be very cumbersome on the maintainer's end to get the CI to work properly.

It is our goal to represent the configuration space exposed by the library -- I too wish libraries were simpler, but I don't believe not supporting it in vcpkg is an option. For maintainers and the CI system, we will focus our efforts on the `Default-Features` case because you're absolutely right that as the feature space grows it becomes impossible to properly test everything. Ideally, we will also (in the CI system, not as much for maintainers on their local machines) test "all-features" and "no-features".

>And then I might want to build for the latest version, which in your scenario might not be on AWS.

I believe what @jasjuang is suggesting (though I may be actually just expressing my own opinion here :)) is that we would have some sort of awesome `vcpkg build-in-the-cloud` command, which will build your binaries on demand using _your_ toolchains and send you an email with a drop link whenever it finishes.

I'd appreciate both you commenting on https://github.com/Microsoft/vcpkg/pull/2800; it looks good to me and (barring regressions) I plan to merge it.

**Comment by jasjuang** [comment]
@patrikhuber When I say AWS, it's a windows server instance that you have total control of. You can install the latest vs2017 on there and compile everything with vcpkg as you like. The point is the build will only happen once in AWS, your laptops/you co-worker's laptop etc can pull in the installed stuff directly from it. This is exactly how I am doing it for my linux dev environment. 

@ras0219-msft If vcpkg can eventually implement a linux ppa equivalent but on top of that with the on demand functionality that will be pretty amazing.

**Comment by KindDragon** [comment]
> @ras0219-msft If vcpkg can eventually implement a linux ppa equivalent but on top of that with the on demand functionality that will be pretty amazing.

If vcpkg will support anything that supports Artifactory, https://jfrog.com/artifactory/features/ - it's good enough for me

**Comment by patrikhuber** [comment]
To be honest I don't get the "binary packages repo" hype. Look at `pacman`, it's amazing, and loved by many people. I know that I was the one that actually complained/complains about compile-times. Yes. But to be honest, there are few packages with long compile times - and the key here is to manage their dependencies. Ceres and OpenCV are the best examples - if you build them with all their possible (optional) dependencies, they take 30-60+ mins to build, even on a 2017 Quad i7. That's really inconvenient (and unnecessary). If you build them on a more "minimalistic" or a "build-what-you-need" basis, they literally build in less than 5 minutes. So the key to me here is to manage the dependencies, and then with modern CPUs we can just always build everything from source - most packages take <30secs, a few will take a few minutes. Completely fine. And okay, if you really ever need full-blow OpenCV or Ceres with **all** their optional dependencies, then well, in these very specific circumstances, you'll wait a bit - that's fine too. But the point is, **by default**, these shouldn't be so monstrous builds.
