### ISSUE TITLE
[qtbase] wayland plugin

### ISSUE THREAD

**Issue by bramtayl** [microsoft/vcpkg#28077]
Unless I'm being stupid, there's no way to build q6base with a wayland platform plugin. Adding the `xcb` feature yields a usable xcb platform plugin, but there is no similar `wayland` feature.

**Comment by bramtayl** [comment]
Oh, while I'm at it, to get xcb working I had to install lots of xcb related packages from Ubuntu (again unless I'm missing something). The error messages in the build logs weren't very helpful. It would be helpful to have better error messages.

**Comment by bramtayl** [comment]
And also, it seems like features that depend on other features are supposed to be automatically included but it's not always working. For example, I also had to add doubleconversion, and to use fontconfig, I had to add png

**Comment by Neumann-A** [comment]
> add doubleconversion,

That depends on your distro as far as I could tell since it could be provided. 

> to use fontconfig, I had to add png

That might be a missing cross dependency. 

>  I had to install lots of xcb related packages from Ubuntu

If you know the list you can add them as dependencies since vcpkg should have nowadays ports for all of them. But it will still be required that those libs are installed by the system you just will get a message that `<port>` should be provided by the system without checking if it actually does.

**Comment by bramtayl** [comment]
Thanks, that's helpful. Could vcpkg automatically add the xcb dependencies then? I found the list here: https://doc.qt.io/qt-6/linux-requirements.html
