### ISSUE TITLE
vcpkg integrate bug

### ISSUE THREAD

**Issue by chriscp-cat** [microsoft/vcpkg#28200]
**Describe the bug**
I set the project’s use vcpkg to false
However, the installed directory of vcpkg is still in the includes

**Environment**
- OS: windows
- Compiler: msvc

**To Reproduce**
1. ./vcpkg integrate install

**Expected behavior**
![image](https://user-images.githubusercontent.com/68489543/205891312-fd2b742c-c555-4d55-9cf7-615ec23d8165.png)
![image](https://user-images.githubusercontent.com/68489543/205891325-816a577e-f1b0-42de-afd7-3704ca7b335b.png)

**Comment by FrankXie05** [comment]
@chriscp-cat Thanks for posting this issue, 
1. The `Use vcpkg` function is set to `No`: it will disable the project to use the library and header files provided by `vcpkg`.

2. For `External Include Directories`, you need to run `./vcpkg integrate remove` and restart `VS`.

3. If you do not restart `vs`, the path of `vcpkg` still exists, but you cannot use `vcpkg`(`error LNK2019`). This is because the integration of `vcpkg` and vs (MSBuild) is implemented by importing`.props` and `.targets` files. Therefore, you need to run the command to restart VS and it will disappear.
View https://github.com/microsoft/vcpkg/blob/master/docs/users/buildsystems/msbuild-integration.md for more help.

**Comment by chriscp-cat** [comment]
But when I run `./vcpkg integrate remove` Even without restart vs The path of vcpkg in the `External Include Directories` will also be removed
I have tried to restart vs before, but my problem has not been solved

**Comment by chriscp-cat** [comment]
this problem did not exist before

**Comment by FrankXie05** [comment]
Yes, at present, this function can only implicitly disable the library provided by vcpkg, and cannot be explicitly displayed. 
It's a vcpkg bug. 🧐

**Comment by FrankXie05** [comment]
I contacted them, but the problem was not solved thoroughly This time we will thoroughly improve this method. :)

**Comment by chriscp-cat** [comment]
I see. Thank you for your help

**Comment by FrankXie05** [comment]
@chriscp-cat Coule you please test PR #28216 ? :)

**Comment by chriscp-cat** [comment]
@FrankXie05 I've already tested,it solved my problem
