### ISSUE TITLE
[vcpkg-tool] Diagnose missing folder for an overlay port

### ISSUE THREAD

**Issue by horenmar** [microsoft/vcpkg#28317]
****

**Is your feature request related to a problem? Please describe.**
Yesterday I was using overlay ports to test new portfile for a pkg, and by mistake copied the files into the top level folder. This meant that I had `overlay-ports/portfile.cmake`, `overlay-ports/vcpkg.json` and so on.

To my surprise, vcpkg happily used the overlay port from this folder.

**Proposed solution**
vcpkg should warn (or error out) when dealing with port's files in top level folder. This causes only slight inconvenience but can prevent a great deal of confusion.

**Comment by Adela0814** [comment]
The overlay port feature will search whether the required `vcpkg.json` is included in the path following the `--overlay-ports` option. Users can customize the search path, and it can be installed correctly whether it contains the port name. This is by design.

Please refer to [here](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md#3-proposed-solution:~:text=From%20a%20user,org%5Ccustom%2Dports).

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
