### ISSUE TITLE
[portfile helpers] vcpkg_from_git should support LFS for/from arbitrary endpoint

### ISSUE THREAD

**Issue by horenmar** [microsoft/vcpkg#28593]
**Is your feature request related to a problem? Please describe.**
Right now, `vcpkg_from_git` support `LFS` argument to also check out LFS files. The problem is that the check out happens against the git url specified in the `URL` argument, rather than where the files actually are.

This means I still cannot use `vcpkg_from_git` for a private port, so I still need to use `vcpkg_apply_patches`, as per #22042.

**Proposed solution**
Either run `git-lfs` in a way that takes into account the repository's `.lfsconfig`, or provide `LFS_URL` argument, where I can point to a specific lfs remote.

**Comment by LilyWangLL** [comment]
cc @DDoS

**Comment by DDoS** [comment]
@horenmar The git fetch never checks-out the repository files. It only does a fetch and archive, so it won't see the `.lsconfig` file.

The LFS fetch runs after the git fetch, and the URL is passed explicitly. As you said it's using the same URL as the git fetch, but we could change this to a different URL if one is provided. I think it could be an optional argument to the `LFS` keyword (if declared in `cmake_parse_arguments` as a "one value keyword" and no value is passed by the caller, the keyword will be in placed in `<prefix>_KEYWORDS_MISSING_VALUES`).

For testing all that's needed is to setup a second temporary test repo, and to try fetching from its URL.

If you want to tackle this, you can look at https://github.com/microsoft/vcpkg/commit/57ae838ee87313a3f0c5e14b008767d97d94debe to get an idea of which files will need to be modified for this improvement. Otherwise I should have time to work on this next week, after my holidays.
