### ISSUE TITLE
[openvpn3] openvpn3 should use the upstreams CMakeLists.txt

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#28861]
Currently it uses a custom CMakeLists.txt file. Maybe this also fixes the macOS build

**Comment by autoantwort** [comment]
still valid

**Comment by Cheney-W** [comment]
Stay active

**Comment by dg0yt** [comment]
This package isn't sane.

The vcpkg port builds a lib which doesn't match directly an upstream artifact. Upstream provides a python lib using swig, and it provides command line tools. That lib and and the tools are the only translation units. Everything else is inline in the headers.

I have a patch to build the vcpkg lib instead of the python lib, to deal with deps and to fix the exported config. But with most of the code being headers, I wonder if the binary artifact is used at all, or if the port's usage is mostly header-only.
