### ISSUE TITLE
Fail to install zlib

### ISSUE THREAD

**Issue by seojun-chang** [microsoft/vcpkg#28918]
**Describe the bug**
Fail to install zlib

**Environment**
- OS: [Windows]
- Compiler: revision

**To Reproduce**
vcpkg install zlib:x64-windows

**Expected behavior**

**Failure logs**
-- Downloading https://github.com/madler/zlib/archive/v1.2.13.tar.gz -> madler-zlib-v1-44b834fb.2.13.tar.gz...
error: https://github.com/madler/zlib/archive/v1.2.13.tar.gz: WinHttpReceiveResponse failed with exit code 12002

**Additional context**
zlib file url is
https://github.com/madler/zlib/releases/download/v1.2.13/zlib-1.2.13.tar.gz
NOT
https://github.com/madler/zlib/archive/v1.2.13.tar.gz

**Comment by Cheney-W** [comment]
I can't reproduce this issue in my side. I could download the https://github.com/madler/zlib/archive/v1.2.13.tar.gz successfully.
Also, I can download both urls you mentioned successfully.

[zlib-1.2.13.tar.gz](https://github.com/microsoft/vcpkg/files/10409238/zlib-1.2.13.tar.gz)

I think this may be caused by your network problem, as a workaround, please download the attachment and save it into vcpkg\downloads folder.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
