### ISSUE TITLE
Binarycaching to github nuget doesn't set package to public when linked to public repository

### ISSUE THREAD

**Issue by cnSchwarzer** [microsoft/vcpkg#28975]
> metadata.repository
> The nuget and nugetconfig source providers additionally respect certain environment variables while generating nuget packages. The metadata.repository field of any packages will be generated as:
> 
>     <repository type="git" url="${VCPKG_NUGET_REPOSITORY}"/>
> or
> 
>     <repository type="git"
>                 url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
>                 branch="${GITHUB_REF}"
>                 commit="${GITHUB_SHA}"/>
> if the appropriate environment variables are defined and non-empty. This is specifically used to associate packages in GitHub Packages with the building project and not intended to associate with the original package sources.

After setting env VCPKG_NUGET_REPOSITORY it can linked properly to a repository, but the package visibility doesn't keep with repo visibility. Even linked to a public repo the package is still private

**Comment by FrankXie05** [comment]
@cnSchwarzer Because many NuGet servers require additional credentials to access. Unless you use the package source as a public property, it can only be used as a private package with credentials, which is for security reasons.

**Comment by cnSchwarzer** [comment]
> @cnSchwarzer Because many NuGet servers require additional credentials to access. Unless you use the package source as a public property, it can only be used as a private package with credentials, which is for security reasons.

Just for curiosity, why packages uploaded by a github action is public by default? (Which use secrets.GITHUB_TOKEN as apikey)

**Comment by FrankXie05** [comment]
@cnSchwarzer 

> Which use secrets.GITHUB_TOKEN as apikey, and uploading to public repository

Because the secrets.GITHUB_TOKEN has read and write permissions to the repository associated with the workflow. When the secrets.GITHUB_TOKEN is used to upload a package, the package is added to the repository's release page, which is public by default.

> While upload and link to same repository from local computer with a generated PAT is private by default

Because the PAT has the permissions to read and write only to the specific repository to which it has been granted access. Therefore, the package is uploaded to the repository's releases page, which is also private by default.

**Comment by FrankXie05** [comment]
@cnSchwarzer 
The difference in default privacy settings between these two methods of uploading packages is due to the different permissions and access levels granted by secrets.GITHUB_TOKEN and a generated PAT. 

Since `secrets.GITHUB_TOKEN` has read and write permissions to the entire repository, packages uploaded using it are by default public. 

In contrast, a generated `PAT` has limited permissions to only the specific repository to which it has been granted access, which means packages uploaded using it are by default private to that specific repository.

**Comment by FrankXie05** [comment]
see: 
https://docs.github.com/en/actions/security-guides/automatic-token-authentication
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by cnSchwarzer** [comment]
What about a PAT that was assigned administrative permission and granted all access to all repositories? Does it also private by default?

**Comment by FrankXie05** [comment]
If a PAT has been assigned administrative permission and granted access to all repositories in an organization, and is used to upload a package to a repository's release page, the package is still private by default. 

This is because, by default, the release page for a repository is private, and the PAT only has access to the specific repository to which it has been granted access, regardless of the permissions assigned to it.

And It is very dangerous to grant administrative permissions to pat and all access to the repository. This is generally not recommended

**Comment by cnSchwarzer** [comment]
Thank you for answering that! 🌹
