### ISSUE TITLE
Handling different names of output libraries

### ISSUE THREAD

**Issue by alexkaratarakis** [microsoft/vcpkg#291]
Context: This was encountered recently with `boost` (#278).

Depending on the configuration of library linkage and static linkage (and others, see [link](http://www.boost.org/doc/libs/1_62_0/more/getting_started/windows.html#library-naming)) the output boost libs are named differently. For example, for dynamic libs we get:
`boost_atomic-vc140-mt-1_62.lib` (release)
`boost_atomic-vc140-mt-gd-1_62.lib` (debug)

whereas for static libs we get:
`libboost_atomic-vc140-mt-s-1_62.lib` (release)
`libboost_atomic-vc140-mt-sgd-1_62.lib` (debug)

[diff = the "lib" in the beginning and the -s- before the version]

FindBoost.cmake (which ships with CMake, so it will be in `C:\Program Files\CMake\share\cmake-3.7\Modules` or equivalent) looks for the dynamic lib names by default and you can specify `Boost_USE_STATIC_LIBS` to have it look for the static lib names instead.

However, in `vcpkg` only one flavor of the library may be present in the same triplet. Therefore, the intention is that a library's functionality is either present or not present; names should not matter. We have therefore opted to rename the output static libs to the corresponding names of the dynamic libs. This will make them automatically discoverable by FindBoost without the need to specify the `Boost_USE_STATIC_LIBS` flag. 

This is not isolated to boost; the same thing is being done for `zlib.lib`. In the static flavors the output is `zlibstatic.lib` and we rename it to `zlib.lib`. In fact, unlike boost, FindZLIB.cmake only looks for `zlib.lib` and there does not seem to be a way for it to look for `zlibstatic.lib`. 

We would like to ask you about your experience regarding the matter and whether you think this is an appropriate way to handle differently named lib files between dynamic and static. Do you think it is a good idea to adopt this strategy in general (i.e. not just boost, zlib)?

**Comment by barcharcraz** [comment]
most libraries seem to have different named libs on windows (probably due to the fact that import libraries and static libs share the same format/extension). That said since cmake really does not have great facilities for saying "static link all the things" renaming may be correct.

I'm not sure how the linter can verify things are named correctly without looking at the dynamic version (which may not be around).

Also maybe we should change boost to a system install (it's an option in boost's build system that gets rid of all that version and linkage cruft in the filenames).

**Comment by barcharcraz** [comment]
A thought: If a package depends on another package and has a non-cmake build system then it probably does not support linking against different export libraries depending on debug or release configuration. HOWEVER renaming things solves this issue because the symbols are almost by definition the same, and the debug and release versions should be drop-in replacements for each other. 

It does mean more mucking about with the package config.cmake files though.

**Comment by alexkaratarakis** [comment]
I was not aware of the "system install". It looks interesting, I will investigate.

**Comment by alexkaratarakis** [comment]
3588f534dbc97f74b90ca8c7d1e9713281ae8b81 adds the flag --layout=system.

**Comment by alexkaratarakis** [comment]
The current layout is as follows:

- All dynamic libs are built with name: `boost_xyz.lib`.
- All static libs are built with name: `libboost_xyz.lib`. They are renamed to `boost_xyz.lib`
- In the dynamic build, there are a few libs that are build statically (possibly because they can only be built statically), for example `libboost_exception.lib`. Those are renamed to `boost_xyz.lib`, unless that name already exists, in which case `libboost_xyz.lib` is simply deleted.

This is because `FindBoost.cmake` is by default only looking for `boost_xyz.lib` names.

**Comment by OlafvdSpek** [comment]
IMO support for building libs on Windows is still a mess.. *not vcpkg's fault*

Ideally it would be automated (and standardized). Boost is special, let's focus on a simple example like png or z. The lib names shouldn't be chosen manually, but this requires support from the build system.

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in two year, if it is still an issue, please reopen.
