### ISSUE TITLE
boost targets for debug config refer to release

### ISSUE THREAD

**Issue by pwm1234** [Microsoft/vcpkg#2912]
Perhaps I am doing something wrong--I am new to vcpkg. (I think it is GREAT!) 

I have built boost for x64-windows. In my client cmake I do a find_package of boost and that works but the link libraries refer to installed\x64-windows\lib rather than the -gd variants in installed\x64-windows\debug\lib. 

How do I fix this? For packages that correctly distinguish their built debug artifacts from the release artifacts (like boost , opencv, qt, and many others) shouldn't the installed artifacts just go to the top-level installation directory rather than the debug subdirectory?

Thanks, Phil.

**Comment by ras0219-msft** [comment]
Thanks for the kind words!

Are you using our toolchain file as recommended in the documentation[1]?

While some libraries like the ones you mentioned do have different names in release and debug, it's all too common to have the same name. Since we certainly need to handle these cases, the entire system is more consistent and robust if the binaries are always separated.

[1] https://github.com/Microsoft/vcpkg/blob/1fb3785beed7dfb24c796619d3c596f34758298e/docs/examples/using-sqlite.md#cmake-toolchain-file

**Comment by pwm1234** [comment]
Yes, you are right--I should have read the documentation more carefully! Sorry about that. The correct path to the boost debug libraries was used once I used ``-DCMAKE_TOOLCHAIN_FILE=c:\my_install_dir\scripts\buildsystems\vcpkg.cmake`` in my cmake configure step. The interesting thing is that except for this one detail, and even this for the boost libraries only, I did not need to read the documentation to get things to work. My suspicion is that boost needs this additional toolchain config argument to help its find module script work. Most of the other projects that I use are cmake-based and produce reasonable config scripts for the find step; so the toolchain file arg is not necessary.

Thanks for your help. I look forward to moving ahead with vcpkg. (Now if we can just get it working on Linux! :-)
