### ISSUE TITLE
Error: Building package liblma:x86-windows

### ISSUE THREAD

**Issue by mathieusr** [Microsoft/vcpkg#2913]
Dear,

When I want to install package i meet this errors:
![image](https://user-images.githubusercontent.com/29339406/36817917-315d5208-1ce3-11e8-9a3c-0494fd5f180e.png)

I don't know, why I have hash problem ?

I did all the recommendations

Many thanks for your help

**Comment by cmpute** [comment]
This would happen if your download file is broken. If you can successfully extract the files in the archive and ensure the completeness of files in it, you can edit the SHA512 hash can make a pr.

**Comment by glachancecmaisonneuve** [comment]
In this case however, @mathieusr's downloaded xv.tar file 656 bytes long and contains an error message instead of the expected 1.5kb source for xz.  The current download source (sourceforge) is undergoing a dos attack.  Change the url in the portfile for any other source (cursory search on github gave me https://raw.githubusercontent.com/gnu-mcu-eclipse/files/1d5112ea3ac1d189e2bf017bece19d19ce269ec4/libs/xz-5.2.3.tar.gz) and close this issue.

**Comment by mathieusr** [comment]
It works thanks
