### ISSUE TITLE
add caffe

### ISSUE THREAD

**Issue by barcharcraz** [microsoft/vcpkg#294]
The caffe deep learning library could be a good thing to add. I've got some scripts and it's a fairly standard build. Although many people probably want the python bindings.

**Comment by willyd** [comment]
I could contribute part of this as I maintain the windows branch of caffe. However, if someone could submit a port for HDF5 that would help getting caffe in vcpkg. After that I beleive only LMDB and caffe itself would be missing.

**Comment by ras0219-msft** [comment]
Thanks for chiming in @willyd! I added #384 to track HDF5.

**Comment by willyd** [comment]
I also created an issue for the LMDB port at #385. I added a link to the (rudimentary) CMake build I currently use.

**Comment by tobiaskohlbau** [comment]
Now that #384 and #385 are solved and merged, I would like to bring the idea of an Caffe port back.

I'm willing to help for an port, but I'm not into Caffe right now. @willyd could you give some information about your build setup?

**Comment by willyd** [comment]
@tobiaskohlbau I totally missed one crucial dependency of caffe when I first looked: OpenBLAS. An OpenBLAS port was investigated but abandonned by @traversaro in https://github.com/Microsoft/vcpkg/issues/23. OpenBLAS can be built with MSVC 2012 and above but the performance won't be as good as with MinGW as described [here](https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio#2-cmake-and-visual-studio). An alternative would be to link to MKL instead but I guess this is suboptimal since everyone will have to install MKL first. I am currently using prebuilt binaries from source forge for OpenBLAS.

As for the build setup, currently the CMake scripts downloads and extracts pre-built binaries (which are built using [caffe-builder](https://github.com/willyd/caffe-builder)) for all dependencies and then includes the `caffe-builder-config.cmake` file which sets a bunch of CMake cache variables. Most dependencies are built with CMake with the exception of the Boost and OpenBLAS. So it should only be a matter of setting the correct <package_name>_DIR to get caffe to build within vcpkg. Caffe supports static library linking and shared library linking, In both cases I tend to prefer the Ninja generator as it is much faster. Also, when building with CUDA, the VS generator will fail to create the library because of CMake issue. As a first port it is probably safer to disable CUDA with CPU_ONLY=ON and to disable Python and matlab with WITH_PYTHON=OFF and WITH_MATLAB=OFF. You should also disable LevelDB with USE_LEVELDB=OFF.

Let me know if you need more details.

**Comment by traversaro** [comment]
For the sake of completeness: in https://github.com/Microsoft/vcpkg/issues/23 I discussed a brief attempt to package lapack and the reference implementation of blas that is distributed with lapack, I did not try to package OpenBLAS at all.

**Comment by willyd** [comment]
> I did not try to package OpenBLAS at all.

Right. Sorry for the confusion everyone.

Also, I guess that some of https://github.com/Microsoft/vcpkg/issues/241 also applies here.

**Comment by willyd** [comment]
I am currently looking into this I have something that almost works here: https://github.com/willyd/vcpkg/tree/caffe
and here: https://github.com/willyd/caffe/tree/vcpkg

I'll submit a PR when ready.

**Comment by lazylazypig** [comment]
@willyd Hi, which compiler is in your toolchain VS2015 or VS2017? Thanks

**Comment by willyd** [comment]
VS2015

**Comment by NancyLi1013** [comment]
Hi @barcharcraz, thanks for posting this issue. The port caffe2 has added to the vcpkg. Can this port meet your demand? If yes, we will close this issue. If not, we will consider to add caffe. Please help us confirm this.
Thanks in advance.
