### ISSUE TITLE
All coin-or ports are conflicting with the maintainer guidelines. 

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#29403]
The following ports:
coinutils, clp, cgl, osi, openmvg(?)
are conflicting with maintainer guidelines. 

a) vendored `CMakeLists.txt` (upstream also doesn't seem eager to add it https://github.com/coin-or/CoinUtils/pull/101)
b) exported targets not namespaced with `unoffical::`
c) no pc files from original build system
d) port names don't reflect entries in https://repology.org (those are typically prefixed with `coin-or-`)

So I vote to remove those ports from the version db and move them to their correct names while at the same time moving them to their upstream buildsystem. 

The reason i discovered this is because i wanted to add `coin-or-ipopt`

**Comment by dg0yt** [comment]
I experimented with the upstream autotools build system for coinutils in https://github.com/microsoft/vcpkg/pull/26524.
The problem is that it uses such heavy customizations of autotool that they are bound to specific version of each autothing. They are lagging behind current versions, and we can't `autoreconf` easily, and so we can't easily get improvements need for `uwp` et al.

**Comment by Neumann-A** [comment]
#29398 works for x64-windows. Uwp looks a bit sketchy maybe there is just an include missing but otherwise I'll consider it unsupoorted by upstream. don't know about the linux error yet.

**Comment by Neumann-A** [comment]
also maybe I was lucky that they seem to have updated autotools yesterday.

**Comment by Neumann-A** [comment]
stll relevant
