### ISSUE TITLE
VCPKG_CHAINLOAD_TOOLCHAIN_FILE can be split to prechain and postchain

### ISSUE THREAD

**Issue by congzhangzh** [microsoft/vcpkg#2958]
VCPKG_CHAINLOAD_TOOLCHAIN_FILE can be split to prechain and postchain, this will enable acess vcpkg related var, and will enable more scenes!

**Comment by qis** [comment]
It will also allow the usage of automatic VS detection in a custom windows toolchain file.

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.

**Comment by qis** [comment]
Better solution that was implemented after this issue was opened:

1. Set `VCPKG_LOAD_VCVARS_ENV`.
2. Set `VCPKG_CHAINLOAD_TOOLCHAIN_FILE`.
3. Include triplet and `vcpkg.cmake` in the chain-loaded toolchain.
4. Include anything else you want.

Seems that there is no need for it anymore. Good cleanup. :)
