### ISSUE TITLE
[monkeys-audio] Port 9.05 still downloads 6.07, and missing MACDll.h

### ISSUE THREAD

**Issue by vividos** [microsoft/vcpkg#29592]
**Describe the bug**
Two issues came up while trying out the updated port, from #29187:
1. The port still (may) download version 6.07. When I check the output folder after a build, in `include\monkeys-audio\Version.h` it still has version 6.07.

I think this change is not correct:
[ports/monkeys-audio/portfile.cmake](https://github.com/microsoft/vcpkg/pull/29556/files#diff-a5b7cdccb97431e45bf633d8dca4be8dbccb462580f3c6cb770e4a564e09413c)
the second URLS link points to version 6.07, not the new 9.05.

2. For dynamic linking with `MACDll.dll`, the header `MACDll.h` is missing, which is needed to get all exported functions. The header should be installed.

**Environment**
- OS: Windows
- Compiler: VS 2022 version 17.4.4

**To Reproduce**
1. ./vcpkg install monkeys-audio
2. Check out the folder  `include\monkeys-audio\Version.h` for the wrong version, and missing `MacDll.h`

**Expected behavior**
only version 9.05 should be downloaded and installed, and the `MacDll.h` header should be there.

**Failure logs**
Log with the two `URLS`:
[stdout-x86-windows.log](https://github.com/microsoft/vcpkg/files/10713490/stdout-x86-windows.log)

**Additional context**
I'm using vcpkg in Manifest mode.

**Comment by dg0yt** [comment]
> the second `URLS` link points to version 6.07.

IMO https://web.archive.org shall not be used as a mirror at all. What I find at https://archive.org/about/terms.php is:
> Access to the Archive’s Collections is provided at no cost to you and is granted for scholarship and research purposes only.

**Comment by FrankXie05** [comment]
> **Describe the bug** Two issues came up while trying out the updated port, from #29187:
> 
> 1. The port still (may) download version 6.07. When I check the output folder after a build, in `include\monkeys-audio\Version.h` it still has version 6.07.
> 
> I think this change is not correct: [ports/monkeys-audio/portfile.cmake](https://github.com/microsoft/vcpkg/pull/29556/files#diff-a5b7cdccb97431e45bf633d8dca4be8dbccb462580f3c6cb770e4a564e09413c) the second URLS link points to version 6.07, not the new 9.05.
> 
https://github.com/microsoft/vcpkg/pull/15359
The link published by port a only supports short-term downloads, so multiple download sources are added. However, since there is only one `vcpkg_extract_source_archive()` to process, the source of the `https://web.archive.org` covers the `https://monkeysaudio.com`  source. The downloaded version is a lower version.
https://github.com/microsoft/vcpkg/blob/36fb23307e10cc6ffcec566c46c4bb3f567c82c6/ports/monkeys-audio/portfile.cmake#L12
> 2. For dynamic linking with `MACDll.dll`, the header `MACDll.h` is missing, which is needed to get all exported functions. The header should be installed.

The header file MACDll.h was remove. 
https://github.com/microsoft/vcpkg/blob/36fb23307e10cc6ffcec566c46c4bb3f567c82c6/ports/monkeys-audio/portfile.cmake#L67
https://github.com/microsoft/vcpkg/commit/16ca72dfe9bca88246b5b56a103f725c9a346931
I think it was because when port `monkeys-audio` was added, it only supported static builds at the time, so it was deleted. But after adding the patch, it supports dynamic builds but forgot to remove it.

**Comment by FrankXie05** [comment]
cc @c72578 @cmpute

**Comment by vividos** [comment]
Thanks for fixing this!
