### ISSUE TITLE
 cmake find_package(libzip) support 

### ISSUE THREAD

**Issue by benstieg** [microsoft/vcpkg#2973]
It would be nice if `find_package(libzip REQUIRED)` would work after `vcpkg.exe install libzip`.
Installing something like the attached files to the installed\<your-triplet>\share\libzip when installing libzip should do it.

[libzip-config.cmake.zip](https://github.com/Microsoft/vcpkg/files/1784160/libzip-config.cmake.zip)

**Comment by janisozaur** [comment]
Please see relevant discussion here: https://github.com/nih-at/libzip/issues/27

**Comment by janisozaur** [comment]
@benstieg would you take a look at possibly fixing the linked issue upstream?

**Comment by 0-wiz-0** [comment]
You can use the CMake standard module FindPkgConfig to detect and use libzip:
https://cmake.org/cmake/help/v3.11/module/FindPkgConfig.html

**Comment by PhilLab** [comment]
@ras0219-msft Using the cmake files provided by benstieg does work. I know that upstream fixes are preferred but as I am not a cmake-wizard, I am not of a big help here. But would committing the above files as module patch in vcpkg be an acceptable solution?

**Comment by 0-wiz-0** [comment]
I've added `find_package()` support to libzip itself in https://github.com/nih-at/libzip/commit/dadba129cd2f2aee9095882cc0f9e28e3afd6575
Pull requests with improvements welcome!

**Comment by endrift** [comment]
So now that libzip 1.7 is in vcpkg, vcpkg has decided to export the target as `zip` instead of `libzip::zip`. I don't know why but vcpkg likes to export a bunch of libraries with names that differ from what you'd import them as in _any other environment_ (e.g. I have to search for FFMPEG (which isn't even the name of the library; it's FFmpeg) instead libavcodec, libavutil, etc) and it's extremely annoying to have to add these workarounds. This one is particularly egregious because it goes against the convention of the CMake targets that libzip specifically exports.

**Comment by JackBoosY** [comment]
Now, libzip support to export cmake configuration files.

**Comment by JackBoosY** [comment]
Same with pkgconfig.
