### ISSUE TITLE
[directxtk, directxtk12, directxmesh, directxtex, uvatlas] Add a tools feature for the command-line tools

### ISSUE THREAD

**Issue by walbourn** [microsoft/vcpkg#30076]
Per feedback in another PR, the building of the command-line tools for these ports is a little confusing. The "proper" solution is to add a 'tools' feature that supports ``windows & !uwp & !xbox``.

**Comment by BillyONeal** [comment]
I'm not sure I agree that there needs to be a tools feature, but the generic "can I possibly run the outputs here" which is supposed to be `NOT VCPKG_CORSSCOMPILING` really needs something that makes sense here rather than reinventing the wheel every time.

How about something like `VCPKG_TARGET_RUNNABLE` defined as `NOT VCPKG_CROSSCOMPILING OR (we know there's an emulator that works here)`?

**Comment by walbourn** [comment]
This commit adds the tools feature

https://github.com/microsoft/vcpkg/pull/30685
