### ISSUE TITLE
[libmysql] 32-bit builds are not supported by libmysql

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/vcpkg#3029]
```
32-bit builds are not supported by libmysql
```

Really? So 32-bit apps can't connect to MySQL anymore?

**Comment by ras0219-msft** [comment]
Yes, it seems oracle has dropped support for 32-bit windows :(

https://github.com/mysql/mysql-server/blob/577fbcf856cd693434d554545d499559bcdd3695/cmake/os/Windows.cmake#L56-L57

**Comment by OlafvdSpek** [comment]
Makes sense for the server but not for the client lib..
One more reason to use MariaDB.

**Comment by jumpinjackie** [comment]
So what of ports that currently depend on libmysql (poco, gdal, libodb-mysql) and can be built on 32-bit but cannot currently because of this?

Switch them over to libmariadb (assuming it's API compatbile)? Leave them terminally un-buildable unless you use git trickery to "pin" libmysql to an older version?

**Comment by ShinNoNoir** [comment]
@jumpinjackie Another solution would be to remove the dependency and make it optional as I detailed in https://github.com/Microsoft/vcpkg/issues/3793#issuecomment-402636981.
