### ISSUE TITLE
[ffmpeg] update to <6.0>

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#30448]
Library name:ffmpeg

New version number:6.0

Other information that may be useful (release notes, etc...)
https://ffmpeg.org/

February 28th, 2023, FFmpeg 6.0 "Von Neumann"

**Comment by jrosener** [comment]
I'm also very interested by having the port of ffmpeg v6.0, especially for the support of Intel's OneVPL (required to deal with hardware encoder/decoder of Intel CPUs gen 12+).
Some info from Intel about FFMPEG build instructions (https://www.intel.com/content/www/us/en/developer/articles/technical/onevpl-in-ffmpeg-for-great-streaming-on-intel-gpus.html) :
`The switch to oneVPL from Media SDK in FFMPEG, is simple. Just substitute ‘--enable-libvpl’ instead of ‘--enable-libmfx’ in the configure stage of FFMPEG compilation.  Both options enable compilation of Intel® Quick Sync Video (*_qsv) codecs, which can be used without change from the FFMPEG command line or in applications.`

**Comment by kadirlua** [comment]
Is there any progress for ffmpeg 6.0?

**Comment by LeenHawk** [comment]
> Is there any progress for ffmpeg 6.0?
Same question.

**Comment by luzpaz** [comment]
Bumping

**Comment by shuax** [comment]
Looks like 6.0 is pretty good

**Comment by LeenHawk** [comment]
> Looks like 6.0 is pretty good

Every patch need to be added manually by major edtion, no one is willing to do this...

**Comment by LeenHawk** [comment]
I often feel puzzled about ffmpeg patches... They are a little stupid between two major version trans...

**Comment by julianxhokaxhiu** [comment]
Fixed by #30135

**Comment by LeenHawk** [comment]
> Fixed by #30135

Works, thank you.

**Comment by luzpaz** [comment]
Ticket can be closed

**Comment by julianxhokaxhiu** [comment]
cc @Neumann-A @BillyONeal
