### ISSUE TITLE
[raylib] CMake config reports version 4.2 for raylib 4.5

### ISSUE THREAD

**Issue by miss-programgamer** [microsoft/vcpkg#30908]
The current config-version.cmake file in the raylib port incorrectly reports the version as 4.2 while raylib.h reports a version of 4.5. Please update the cmake script so it parses raylib.h and grabs the version numbers from the #define statements directly so this desync doesn't happen again.

**Comment by Cheney-W** [comment]
The issue has already been fixed in upstream https://github.com/raysan5/raylib/commit/0d4db7ad7f6fd442ed165ebf8ab8b3f4033b04e7, and I have submitted a pull request to apply the upstream's changes.

I understand that this change is not what you were expecting, but the way the current version is being obtained is determined by upstream. If you would like your needs to be addressed, please submit an issue to upstream. Thank you.
