### ISSUE TITLE
[ffmpeg] use yasm instead nasm

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#31113]
>### Library name

ffmpeg

>### New version number

all

>### Other information that may be useful (release notes, etc...)

I just compile ffmpeg on linux and it want me to install nasm. I search on vcpkg and discovered a yasm port. 
Can we use it yasm instead nasm in ffmpeg and link to it?

**Comment by BillyONeal** [comment]
We stopped using yasm because all available versions are:
* unmaintained
* full of memory corruption bugs
* as a result of the memory corruption bugs, sometimes fail for no reason

vcpkg-tool-yasm was a last ditch workaround to attempt to workaround those bugs by building a more recent yasm than available in any binary form from source.

**Comment by talregev** [comment]
Thank you for let me know and your detail answer!
