### ISSUE TITLE
Error: Building package zlib:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by hoopan** [Microsoft/vcpkg#3122]
Package: zlib:x64-windows
  Vcpkg version: 0.0.106-2018-03-24-21ef72d02a7ea840b3427bda2ea2705aeaef2f00

**Comment by miurahr** [comment]
Duplicated with #1797 ?
@hoopan you seems to living in China then you may use Chinese Windows. It may cause a compilation problem.

**Comment by hoopan** [comment]
Thank you ！
I succeeded in switching to Windows in English.

**Comment by hoopan** [comment]
Thank you ！
I succeeded in switching to Windows in English.

**Comment by miurahr** [comment]
@hoopan  Good news! OK, we now clarify the problem. But it is also a bad news for a users community.
Every ordinary people who want to use vcpkg and  is living in China, Japan, Korea and Russian may get the problem. It is difficult to find a cause by themselves.

Do you have  any idea to help these people? Otherwise, there are so many similar issues filed again and again by users like you.

**Comment by miurahr** [comment]
It is duplicated discussion with  
https://github.com/Microsoft/vcpkg/issues/2895#issuecomment-369104163

**Comment by miurahr** [comment]
@ras0219-msft Could you take any actions to help these CJKR users? There seems to be a bunch of similar issues filed on an issue tracker.

**Comment by hoopan** [comment]
The way I know it now is to set the vs language to English so that it can be compiled successfully.

Specific steps

Find Tools-> Options->Environment->International Settings  in the menu bar.

Select English

**Comment by superdopenoob** [comment]
I ran into the same problem,and I almost shit my pants due to it.

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
