### ISSUE TITLE
[libexif] Does not create CMake targets

### ISSUE THREAD

**Issue by nickdademo** [microsoft/vcpkg#31687]
### Is your feature request related to a problem? Please describe.

I am not sure if this is by design, but when using this port I have to do the below rather than using `find_package` way:

```
add_library(libexif
    SHARED IMPORTED GLOBAL
)
set_property(TARGET libexif PROPERTY IMPORTED_IMPLIB ${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libexif.lib)
set_property(TARGET libexif PROPERTY IMPORTED_LOCATION ${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/bin/libexif.dll)
set_property(TARGET libexif PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include)
```

Is this the proper way to use this port?

### Proposed solution

Port should provide CMake targets.

I assume this can be achieved via `CMakePackageConfigHelpers`? Happy to do the PR if this is the case.

**Comment by ilya-lavrenov** [comment]
Hi,

This is because this [CMakeLists.txt](https://github.com/microsoft/vcpkg/blob/master/ports/libexif/CMakeLists.txt) does not produce package config file.
Maybe it's better to contribute to original repo then https://github.com/libexif/libexif? You can start with backporting cmake scripts from this repo and then adding generation of cmake config file with approach you mentioned

**Comment by FrankXie05** [comment]
This port is too old, we should update to the new build system `Make` and remove `CMakeLists.txt` 'cmake'.

**Comment by FrankXie05** [comment]
I will update this. :)

**Comment by dg0yt** [comment]
Upstream uses autotools and provides pkg-config files. This can be used from CMake.

**Comment by nickdademo** [comment]
Thanks @FrankXie05 !
