### ISSUE TITLE
Legal: licenses conflict

### ISSUE THREAD

**Issue by Karlson2k** [microsoft/vcpkg#31741]
According to the repo licence (`MIT`/`Expat`), any person have rights to use the code in this repository, while according to [`Contribution License Agreement`](https://github.com/microsoft/ContributorLicenseAgreement/blob/main/src/ContributorLicenseAgreement.Core.Tests/Data/claContent.yml) (CLA) only Microsoft and persons who receive the code from Microsoft (directly or indirectly) have rights to use it.

Isn't it a legal issue?

How can I check that code, which I receive from 3rd party, is coming from Microsoft?

Do these two licences conflict with each other?

Related issues:
* CLA does not mention that `Submission` will be used under another license, while the code is actually distributed clearly under other license.
* CLA does not require to accept project's license, so the code could distributed under license which not originally accepted by the contributor.

**Comment by Karlson2k** [comment]
Note: typically in FLOSS world the contribution to the project used the same licence as the project itself.

**Comment by FrankXie05** [comment]
cc @BillyONeal

**Comment by BillyONeal** [comment]
I am not a lawyer, but my understanding is that the CLA is the terms by which you license your contributions to Microsoft, and MIT is the license by which we license the resulting composed product back to customers. For example, if we ever made a commercial version of vcpkg, the terms of the commercial copy would be bound by its license, not by MIT, and we need additional stuff in the CLA in order to do so. If this concerns you I recommend you consult a lawyer.
