### ISSUE TITLE
[xmlsec] public & internal structures don't match for x64

### ISSUE THREAD

**Issue by bevancollins** [microsoft/vcpkg#31866]
### Is your feature request related to a problem? Please describe.

XMLSEC_NO_SIZE_T needs to be public so that structure match. This was causing signature verification to fail for x64. See also https://www.aleksey.com/pipermail/xmlsec/2007/008005.html

### Proposed solution

target_compile_definitions(xmlsec1 PUBLIC XMLSEC_NO_SIZE_T)

**Comment by FrankXie05** [comment]
@bevancollins 
>target_compile_definitions(xmlsec1 PUBLIC XMLSEC_NO_SIZE_T)

Thanks for posting this isse, but whether we should `public` it. This macro `XMLSEC_NO_SIZE_T` is used to disable `size_t`.

>This results in a size_t being an unsigned int rather than size_t 

It is precisely because the user passed this macro definition that the `size_t` type cannot be recognized.

I don't know much about this usage scenario for this macros `XMLSEC_NO_SIZE_T`, but it seems like it has some transitive qualification. Can you please provide some information please? :)

`vcpkg` currently does not have this constraint, this is what we need to change.
https://github.com/microsoft/vcpkg/blob/75059166857a374297e5edd6e1e7a60912907a46/ports/xmlsec/CMakeLists.txt#L86

**Comment by bevancollins** [comment]
@FrankXie05 before including an xmlsec header, the macro XMLSEC_NO_SIZE_T must match what was used when xmlsec was built or else structures will be different on 64 bit eg xmlSecPtrList https://github.com/lsh123/xmlsec/blob/68f1e089deaa0cb3b20f47ac6c9a440e66fd99bb/include/xmlsec/list.h#L37
