### ISSUE TITLE
how to manual add the vcpkg include/lib path to visual studio

### ISSUE THREAD

**Issue by huyuguang** [Microsoft/vcpkg#3188]
I know vcpkg integrate install, but I do not like it.

I want to add the include path and lib path manually, for example, through Microsoft.Cpp.Win32.user.

What makes me confused is how can I set for x86-windows and x86-windows-static, and debug and release? All these projects settings use Microsoft.Cpp.Win32.user. I think maybe we should have Microsoft.Cpp.Win32.Debug.user and Microsoft.Cpp.Win32.Static.Debug.user?

**Comment by ras0219-msft** [comment]
Here is our documentation on the raw structure: https://github.com/Microsoft/vcpkg/blob/master/docs/users/integration.md#manual-compiler-settings.

Otherwise, this looks like an issue with Visual Studio and unrelated to vcpkg. Please post this over on the Visual Studio User Voice[1] so the right people will hear about it!

[1] https://visualstudio.uservoice.com/forums/121579-visual-studio-ide
