### ISSUE TITLE
vcpkg's find_package should verify libraries are found before appending

### ISSUE THREAD

**Issue by donny-dont** [microsoft/vcpkg#3204]
I've been hitting an issue with my own port of freetype where I am not including bzip2 support. Because of the overridden find_package library it always has `BZIP2_LIBRARY-NOTFOUND`. All the libraries in there should not append unless they are actually found.

Also with libxml2 it is also assuming that it builds with iconv and charset though ICU is also a perfectly acceptable target.

**Comment by Fleischner** [comment]
To be honest I think that find_package (or finding dependent libraries in general) is currently THE number one problem of vcpkg.

Its so damn brittle that it is no wonder that the number of open vcpck issues is constantly rising. It just doesn't work now, it will not work in the near future, nor in 10 years, because it is just fundamentally broken. It's a inexhaustible source of strange hard or impossible to detect errors, and I know at least a couple issues that arise from this, that I currently don't time time to report about. But even if I had time it wont make any sense, because the next mini update to port ... will break everything again. It just cannot be fixed the way it is.

And vcpkg already is hacking partially around it by a macro in the toolchain file on some ports, which is just beautiful if you are wondering after hours of searching why your patches don't show any effects.

I don't know which feature the vcpkg team is working on currently, but I strongly suggest to stop right now and and fix this issue before continuing with anything else, because it will become worse with every minute.

I'm not an cmake expert, so any suggestions how to improve this are welcome.

My current proposal would be to add an post-build check that disallows any cmake targets files and any pkgconfig files in the installed directory.
Then for each internal build system that vcpck supports, during build just feed depended libraries and include-directories according to the dependencies listed in the port control file (for cmake that would mean to bypass find_package, find_library, ... with some general macros that fill in the required variables) (This will of course have the result that each library links to all libraries of dependent ports and not only the required ones. Maybe msvc can drop those unnecessary connections if no symbols are used)

However don't know if this is feasible or which other information cmake might transported on magic ways over the target files.

**Comment by Voskrese** [comment]
возможно сделав линковку на библиотеку с переименованием исправит ситуацию, я часто с таким сталкиваюсь, здесь vcpkg вовсе не причем

> probably by making a link to the library with renaming will fix the situation, I often encounter this, here vcpkg does not have

BZIP2.lib <-> LIBBZIP2.lib

mklink

**Comment by NancyLi1013** [comment]
Hi @donny-dont thanks for posting this issue.
Could you please list the ports that have similar issues you found?
Related #6045

**Comment by Osyotr** [comment]
@NancyLi1013 I'm not sure if it's the same issue, but every time I do minor change in some CMakeLists.txt, I get this output:
```
1> CMake generation started for configuration: 'WSL-GCC-Debug'.
1> Found cmake executable at cmake.
1> cmake -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="/mnt/d/MyProject/Sources/../out/install/WSL-GCC-Debug" -DCMAKE_TOOLCHAIN_FILE:FILEPATH="~/development/vcpkg/scripts/buildsystems/vcpkg.cmake"  /mnt/d/MyProject/Sources/CMakeLists.txt;
1> [CMake] -- Found Boost: /mnt/d/MyProject/out/build/WSL-GCC-Debug/vcpkg_installed/x64-linux/include (found version "1.75.0")  
1> [CMake] -- Eigen found (include: /mnt/d/MyProject/out/build/WSL-GCC-Debug/vcpkg_installed/x64-linux/include/eigen3, version: 3.3.9)
1> [CMake] -- Found Boost: /mnt/d/MyProject/out/build/WSL-GCC-Debug/vcpkg_installed/x64-linux/include (found suitable version "1.75.0", minimum required is "1.55.0") found components: system filesystem date_time iostreams regex 
1> [CMake] ** WARNING ** io features related to png will be disabled
1> [CMake] ** WARNING ** surface features related to qhull will be disabled
1> [CMake] -- looking for PCL_COMMON
1> [CMake] CMake Warning (dev) at /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
1> [CMake]   The package name passed to `find_package_handle_standard_args` (PCL_COMMON)
1> [CMake]   does not match the name of the calling package (PCL).  This can lead to
1> [CMake]   problems in calling code that expects `find_package` result variables
1> [CMake]   (e.g., `_FOUND`) to follow a certain pattern.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   /mnt/d/MyProject/out/build/WSL-GCC-Debug/vcpkg_installed/x64-linux/share/pcl/PCLConfig.cmake:594 (find_package_handle_standard_args)
1> [CMake]   /home/me/development/vcpkg/scripts/buildsystems/vcpkg.cmake:772 (_find_package)
1> [CMake]   DatCls/cpc/CMakeLists.txt:96 (find_package)
1> [CMake] This warning is for project developers.  Use -Wno-dev to suppress it.
######################################## 200 LINES OMITTED 
1> [CMake] -- looking for PCL_STEREO
1> [CMake] CMake Warning (dev) at /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
1> [CMake]   The package name passed to `find_package_handle_standard_args` (PCL_STEREO)
1> [CMake]   does not match the name of the calling package (PCL).  This can lead to
1> [CMake]   problems in calling code that expects `find_package` result variables
1> [CMake]   (e.g., `_FOUND`) to follow a certain pattern.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   /mnt/d/MyProject/out/build/WSL-GCC-Debug/vcpkg_installed/x64-linux/share/pcl/PCLConfig.cmake:594 (find_package_handle_standard_args)
1> [CMake]   /home/me/development/vcpkg/scripts/buildsystems/vcpkg.cmake:772 (_find_package)
1> [CMake]   DatCls/cpc/CMakeLists.txt:96 (find_package)
1> [CMake] This warning is for project developers.  Use -Wno-dev to suppress it.
1> [CMake] -- Found Boost: /mnt/d/MyProject/out/build/WSL-GCC-Debug/vcpkg_installed/x64-linux/include (found version "1.75.0") found components: python39 
1> [CMake] -- Found Boost: /mnt/d/MyProject/out/build/WSL-GCC-Debug/vcpkg_installed/x64-linux/include (found version "1.75.0")  
1> [CMake] -- Found Boost: /mnt/d/MyProject/out/build/WSL-GCC-Debug/vcpkg_installed/x64-linux/include (found version "1.75.0") found components: date_time 
1> [CMake] -- Found Boost: /mnt/d/MyProject/out/build/WSL-GCC-Debug/vcpkg_installed/x64-linux/include (found version "1.75.0")  
1> [CMake] -- Found Boost: /mnt/d/MyProject/out/build/WSL-GCC-Debug/vcpkg_installed/x64-linux/include (found version "1.75.0") found components: python39 
1> [CMake] -- Configuring done
1> [CMake] -- Generating done
1> [CMake] -- Build files have been written to: /mnt/d/MyProject/out/build/WSL-GCC-Debug
1> [CMake] 
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted code model.
1> Extracted includes paths.
1> CMake generation finished.
```

I do use boost, eigen3 and pcl, but I also use glm, flann and Qt which are not being searched over and over again:
```cmake
# thirdparty

find_package(Boost REQUIRED)
target_include_directories(${MY_LIB_NAME} SYSTEM PUBLIC ${Boost_INCLUDE_DIRS})
target_link_directories(${MY_LIB_NAME} PUBLIC ${Boost_LIBS_DIR})

find_package(Eigen3 REQUIRED)
target_link_libraries(${MY_LIB_NAME}
  PUBLIC
    Eigen3::Eigen
)

find_package(flann REQUIRED)
target_link_libraries(${MY_LIB_NAME}
  PUBLIC
    flann::flann
)

find_package(glm REQUIRED)
target_link_libraries(${MY_LIB_NAME}
  PUBLIC
    glm::glm
)

find_package(PCL REQUIRED)
target_include_directories(${MY_LIB_NAME} PUBLIC ${PCL_INCLUDE_DIRS})
target_link_libraries(${MY_LIB_NAME} PUBLIC ${PCL_LIBRARIES})

find_package(Qt5 REQUIRED COMPONENTS Core Gui Widgets)
target_link_libraries(${MY_LIB_NAME}
  PUBLIC
    Qt::Core
    Qt::Gui
    Qt::Widgets
)
```

As a result, every change in some unrelated `CMakeLists.txt` is 15 seconds wasted.

**Comment by JonLiu1993** [comment]
@donny-dont ，Thanks for posting this issue,Can you give a list of libraries that have this problem on the latest version of vcpkg currently?

**Comment by donny-dont** [comment]
Hey @JonLiu1993 its been a long while since I opened this and I believe I encountered this when I was trying to make my own port of FreeType which was doing a `find_library` on BZIP2. I was surprised because I had no idea that `vcpkg` was overriding `find_library` internally and opened this when I determined it.

**Comment by Neumann-A** [comment]
@JonLiu1993 I think this can be closed.
