### ISSUE TITLE
[xerces-c] hard coded path to libnsl.so

### ISSUE THREAD

**Issue by davesworking** [microsoft/vcpkg#32170]
On Linux platforms, `XercesCConfigInternal.cmake` contains are hard coded path to `libnsl.so`:

**Linux x86-64 .../share/xercesc/XercesCConfigInternal.cmake**
`    INTERFACE_LINK_LIBRARIES "/usr/lib64/libnsl.so;\$<LINK_ONLY:Threads::Threads>"`
**Linux ARM64 .../share/xercesc/XercesCConfigInternal.cmake**
`    INTERFACE_LINK_LIBRARIES "/usr/lib/aarch64-linux-gnu/libnsl.so;\$<LINK_ONLY:Threads::Threads>"`

Is this correct? The absolute path is causing the library to fail to load.

**Comment by dg0yt** [comment]
https://packages.debian.org/search?searchon=contents&keywords=libnsl.so&mode=path&suite=stable&arch=any
This is system library, not a vcpkg port. Doesn't the file exist? 
What do you mean by "fail to load", a build-time issue or a run-time issue?

**Comment by rafal-c** [comment]
I would say the problem here is that vcpkg build of xerces-c is not portable, meaning that if you call 
```
vcpkg install xerces-c
``` 
on machine A where libnsl is under `/usr/lib64/` and copy the resulting library files to machine B where you build your executable that links to xerces then your application will fail to link if machine B has libnsl under a different location, say, `/usr/lib/x86_64-linux-gnu/`.

I believe that it is a port bug and there should be no absolute paths in any of the CMake config files that vcpkg generates. A simple workaround (not sure how robust though) would be to put "nsl" into `INTERFACE_LINK_LIBRARIES` instead of the absolute path to at least give linker a chance to find libnsl on machine B.

**Comment by dg0yt** [comment]
> your application will fail to link if machine B has libnsl under a different location, say, `/usr/lib/x86_64-linux-gnu/`.

Sure, this is stating the obvious. I wanted to get an explicit confirmation that this is the error which the OP meant by "The absolute path is causing the library to fail to load."

But even with `-lnsl`, there might be errors, due do (rare) API changes. What is available at usage time simply varies independently from what was available at build time.  
I wonder if a "validating XML parser" really needs that lib at all.
