### ISSUE TITLE
[Request] Can not build rttr library

### ISSUE THREAD

**Issue by bsviglo** [Microsoft/vcpkg#3263]
Hi, I can't build rttr library using latest vcpkg revision.
BTW there is newer version of rttr 0.9.6, current version in vcpkg is 0.9.5-2

CMake Error at ports/rttr/portfile.cmake:41 (file):
  file must be called with at least two arguments.
Call Stack (most recent call first):
  scripts/ports.cmake:72 (include)
Error: Building package rttr:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: rttr:x86-windows
  Vcpkg version: 0.0.108-2018-04-13-4e48a1c235d776b5099a61252ff726edb5b6a6b7

**Comment by OliverKlages** [comment]
replace line 41 in ports/rttr/portfile.cmake

```cmake
file(REMOVE ${REL_EXES} ${DBG_EXES})
```

with this:

```cmake
if(REL_EXES)
	file(REMOVE ${REL_EXES})
endif(REL_EXES)

if(DBG_EXES)
	file(REMOVE ${DBG_EXES})
endif(DBG_EXES)
```

The problem is that the script tries to remove executables (from previous build) which are stored in *${REL_EXES}* and *${DBG_EXES}*. Since those cmake vars are empty on first build, *file* gets just the *REMOVE* argument but no actual files, and cmake doens't like that.
