### ISSUE TITLE
[VTK|clang-cl] unable to use in downstream projects due to proj toolset version restrictions

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#32771]
@dg0yt:

```
CMake Error at build/ClangCL-2022-amd64/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake:855 (_find_package):
[cmake]   Could not find a configuration file for package "PROJ" that is compatible
[cmake]   with requested version "".
[cmake] 
[cmake]   The following configuration files were considered but not accepted:
[cmake] 
[cmake]     G:/MPINew/mpi_cpp/Sources/build/ClangCL-2022-amd64/vcpkg_installed/x64-win-llvm-san-rel/share/proj/proj-config.cmake, version: 9.2.1 (MSVC_TOOLSET_VERSION = 143)
[cmake] 
[cmake] Call Stack (most recent call first):
[cmake]   build/ClangCL-2022-amd64/vcpkg_installed/x64-win-llvm-san-rel/share/vtk/VTK-vtk-module-find-packages.cmake:585 (find_package)
[cmake]   build/ClangCL-2022-amd64/vcpkg_installed/x64-win-llvm-san-rel/share/vtk/vtk-config.cmake:150 (include)
[cmake]   build/ClangCL-2022-amd64/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake:855 (_find_package)
[cmake]   Applications/ScannerConf/CMakeLists.txt:12 (find_package)
[cmake] 
```

Please do not simply replace modules with configs if the config is doing a wrong toolset check which don't agree between usage and configure. (proj has been build with exactly the same toolchain/toolset)

**Comment by dg0yt** [comment]
> Please do not simply replace modules with configs if the config is doing a wrong toolset check which don't agree between usage and configure.

Nothing is done "simply" (but you probably know that), and it is reasonable to assume that the installed config is working for all triplet until proven otherwise. When there is a bug in proj config, it must be fixed anyways to make it usable.

I guess you refer to this spot:
https://github.com/OSGeo/PROJ/blob/fde3d58e4af51f8e6c9cafeeb2b0299ab1218d91/cmake/project-config-version.cmake.in#L31-L38
I can't fix it because I don't use MSVC except in vcpkg CI. But for vcpkg it is probably safe to remove it, due to its ABI tracking.

**Comment by dg0yt** [comment]
Previous incident: #24035
