### ISSUE TITLE
pcl[tools] failed to install because of boost 1.67 upgrade

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#3289]
`vcpkg install pcl[tools]` failed to build because of boost 1.67 upgrade. The error message is similar to the ones shown in https://github.com/PointCloudLibrary/pcl/issues/2284

Based on the comments, I manually add `add_definitions(-DBOOST_UUID_RANDOM_GENERATOR_COMPAT)` into the root CMakeLists for pcl in the source folder and it successfully compiles. However, this doesn't feel like the right way to fix it, I couldn't find a way to use `add_definitions` or `target_compile_definitions` to propagate the macro in the pcl portfile when building it.

@UnaNancyOwen @ras0219-msft What do you think is the best way to fix this?

**Comment by claudiofantacci** [comment]
I confirm this issue and that it was solved by adding the definition suggested by @jasjuang.
Thanks for posting it here.

I created a [patch](https://github.com/claudiofantacci/vcpkg/commit/d5306817886f6368144d3066345f585f8f37a5ee) and added it to PCL port, pushing the associated commit on my [fork](https://github.com/claudiofantacci/vcpkg).
Since the release cycles of PCL are quite slow (last one August 2017), I would suggest to add my patch to PCL port while waiting for a fix upstream and the next release.

Let's see what the maintainers opinion is.

**Comment by UnaNancyOwen** [comment]
Thanks for reporting. Sorry, I have not working about this problem yet, because I have so busy recently.
It seems that it is still under discussion on upstream. (I have not examined it in detail yet,) I think the [breaking changes of Bore.Uuid](https://www.boost.org/users/history/version_1_67_0.html) is cause of this problem. 

Anyway, I agree to add a patch to the PCL port for now as a temporary measure.
@claudiofantacci Could you send pull-request?

**Comment by MukilanP** [comment]
How to run the above patch?. I am seeing the missing uuid in my build

**Comment by jasjuang** [comment]
@MukilanP It should be applied automatically. If not, try deleting the pcl folder in buildtree and install again.

**Comment by MukilanP** [comment]
@jasjuang Thanks for your reply. I followed your steps and it is not working. Then removed entirely and followed below steps
1. git clone https://github.com/Microsoft/vcpkg.git
2. cd vcpkg
3. PS> .\bootstrap-vcpkg.bat
4. PS> .\vcpkg integrate install
5. PS> .\vcpkg install boost

I couldn't find the uuid package.

**Comment by jasjuang** [comment]
@MukilanP It's not necessary to `vcpkg install boost` first. Just directly do `vcpkg install pcl` than the patch will be automatically applied.
