### ISSUE TITLE
ImGui is out-of-date

### ISSUE THREAD

**Issue by YukinoHayakawa** [Microsoft/vcpkg#3311]
The source repo is now 1.61 (although a WIP) and some compatibility-breaking changes had been made to its API since the version in vcpkg (updated 4 months ago). Since this library has been a WIP for a long time so it doesn't really mean anything. I think it's the time to upgrade the version.

**Comment by ocornut** [comment]
The "WIP" marker refers to the fact that 1.61 is in progress. 
The latest tagged version is 1.60, I also recommend updating since the amount of changes between 1.53 and 1.60 are massive :)

(Dear ImGui doesn't use semantic versioning, some parts of the API frequently evolve. The changes are generally well documented, and functions/flags marked are Beta are most likely to evolve. It's a very unusual library, but its users tends to work well with it and are aware of its pecularities)

**Comment by PhoebeHui** [comment]
@YukinoHayakawa, thanks for posting this issue, ImGui currently updated the version to 1.67.
