### ISSUE TITLE
dlls not being copied properly

### ISSUE THREAD

**Issue by IbrahimHindawi** [microsoft/vcpkg#33261]
**Describe the bug**
I have a vcpkg + cmake + msbuild + clang power tools setup to generate debug and release builds for my exe using sdl2 and sdl2gfx.  
Here is my CMake setup: https://github.com/IbrahimHindawi/fzx/blob/main/CMakeLists.txt  
When I run my build scripts to compile after building the VS solution it compiles fine but it crashes when I run it.  
When I have a look at the build directory (Debug) I ideally need to see `SDL2d.dll` with `SDL2_gfx.dll` but it non-deterministically keeps copying one of `SDL2.dll` `SDL2.d.dll` `SDL2_gfx.dll` or even puts all 3.  
I have no idea how to debug this, maybe it is something with my CMakeLists.txt or my setup.   
I'm mainly using the VCPKG heuristically generated cmake commands.  

**Environment**
- OS: Windows 10 x64
- Compiler: Visual Studio 17 2022

**To Reproduce**
Steps to reproduce the behavior: https://github.com/IbrahimHindawi/fzx/tree/main  

**Expected behavior**
It should just properly build the exe with the proper dlls.  

**Failure logs**
N/A

**Additional context**
If I recompile a few times it eventually will get it right.

**Comment by dg0yt** [comment]
Are you sure things don't already fail at build time, due to SDL2_gfx? IIUC SDL2_gfx doesn't come from vcpkg. And you use a vendored find module which is unaware of the multi-config nature of msbuild and vcpkg.

**Comment by IbrahimHindawi** [comment]
I wish it crashes at build time. On Windows I'm using the vcpkg version of sdl2_gfx not vendored. You can tell from the CMakeLists.txt

**Comment by IbrahimHindawi** [comment]
It only runs after I execute `scripts\ccompilerun.bat` 3 times!

**Comment by FrankXie05** [comment]
We have this port `sdl2-gfx`.

https://github.com/microsoft/vcpkg/tree/master/ports/sdl2-gfx

**Comment by FrankXie05** [comment]
Strangely, we do not provide `SDL2.d.dll` on `Debug`.

**Comment by FrankXie05** [comment]
Sorry I can't use your project because I can't find a header file `#include "hkArray.h"`.
I created a project, using ports `sdl2` and `sdl2-gfx`. 
There is no error you mentioned, I think there may be some conflicts between your script settings and VS.

Set your `CMAKE_TOOLCHAIN_FILE` , then build the project.

Below is an example of a simple CPP file using the `sdl2 `and `sdl2-gfx` libraries. This code will create a window and draw a simple line segment in it
[CMakeLists.txt](https://github.com/microsoft/vcpkg/files/12393702/CMakeLists.txt)
[fzx.cpp.txt](https://github.com/microsoft/vcpkg/files/12393708/fzx.cpp.txt)


![image](https://github.com/microsoft/vcpkg/assets/65999885/aa246b61-3260-425f-8253-4dbf62269073)

![image](https://github.com/microsoft/vcpkg/assets/65999885/bc3ae2c3-2ed4-43a9-b394-5e7f48702418)

**Comment by IbrahimHindawi** [comment]
you need to `git submodule update --init --recursive`

**Comment by IbrahimHindawi** [comment]
I tried your config and I got the same problems.
Seems like there is something wrong with my vcpkg environment or something.
No idea how to debug, I'll try reinstalling vcpkg.
running with `cmake .. "-DCMAKE_TOOLCHAIN_FILE=C:\devel\vcpkg\scripts\buildsystems\vcpkg.cmake" "-DCMAKE_BUILD_TYPE=Debug"`

**Comment by IbrahimHindawi** [comment]
found the issue: `set_target_properties(${PROJECT_NAME} PROPERTIES VS_GLOBAL_VcpkgEnabled true)`
removing this line fixes my setup

**Comment by IbrahimHindawi** [comment]
Any idea why? 😅

**Comment by IbrahimHindawi** [comment]
fix: https://github.com/IbrahimHindawi/fzx/blob/main/scripts/ccompile.bat

**Comment by IbrahimHindawi** [comment]
I now understand why this was happening. My setup was conflicting with the `vcpkg.exe integrate install` command:  
this cmake command `set_target_properties(${PROJECT_NAME} PROPERTIES VS_GLOBAL_VcpkgEnabled true)` cannot coexist with `vcpkg.exe integrate install` unless we also disable it from the `msbuild build\fzx.sln /property:VcpkgEnabled=false`.
Thanks!
