### ISSUE TITLE
[New Port Request] boost-header-only

### ISSUE THREAD

**Issue by nilsnolde** [microsoft/vcpkg#33282]
### Library name

boost

### Library description

Only provide Boost header-only libraries

### Source repository URL

https://github.com/boostorg/boost

### Project homepage (if different from the source repository)

https://boost.org

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

It seems there no way to canonically install boost header-only libraries. Of course a project could define all their `vcpkg` boost dependencies and list them separately, it's not so much work. But so wouldn't be this port I think:) It should be very similar to https://github.com/microsoft/vcpkg/blob/master/ports/boost, i.e. an empty package right?

**Comment by Neumann-A** [comment]
So you want a boost-headers meta-port which has all boost ports which are header only as dependency? Don't really see a reason to do that.

**Comment by nilsnolde** [comment]
For a very similar reason as the overall boost meta-port: to not have to specify each and every dependency. I usually try to depend on header only libraries. Boost has many and instead of installing them one by one, I’d like to install all in one go.

**Comment by SchaichAlonso** [comment]
Most guidelines would require you to explicitly list each and every direct dependency into the `COMPONENTS` field of your `find_package(boost)` field, in which case you can just copy that list into your vcpkg manifest file.

From a functional point of view, explicitly listing all directly referenced components introduces compatibility with environments where the components aren't all installed into the same path, i.e. no single components' include path provides access to all of the others.

From a non-functional point of view, we want to generate software bill of materials (SBOM), which can be used to automate dependency tracking. As an update of any of our dependencies and deep-endencies might introduce a regression to the own software, regression testing is required to be done for each of them in order to decide whether an update of the corresponding dependency is possible, or the update should be postponed until a fix or workaround for the regression was developed. There's also the thing with "security" updates, which despite claims have no lesser potential to introduce regressions then regular updates have, but need to be addressed quickly, potentially smashing time schedules. For that reason, SBOMs shouldn't be filled with unused software that was referred as a requirement simply because a metaport introducing dozens of additional dependencies was faster to add then the 5 dependencies that are actually used.

**Comment by nilsnolde** [comment]
Thanks for the thorough explanation @SchaichAlonso ! I'm clearly not used to package managing:) What you said makes sense to me. FWIW, that applies verbatim to the entire boost meta port, but maybe those concerns weren't around when it was introduced.

**Comment by nilsnolde** [comment]
Also for future reference: it's not quite that easy as "this is the list of boost libs that are header-only", since quite a few of those have optional library dependencies making them optionally non-header-only.

**Comment by sarlinpe** [comment]
> in which case you can just copy that list into your vcpkg manifest file

Header-only components of Boost are grouped into a common target `Boost::headers` and do not have their own cmake config files. Currently vcpkg does not export such target so `find_package(boost COMPONENTS headers)` fails. I think that it shouldn't, so vcpkg should have a `boost-headers` port that exports `Boost::headers`.

**Comment by Zitrax** [comment]
Related request #38244

**Comment by sfhacker** [comment]
This is almost a year old!
