### ISSUE TITLE
VCPKG dose not run proppely on a GitLab runner

### ISSUE THREAD

**Issue by Vildnex** [microsoft/vcpkg#33317]
**Environment**
- OS: Ubuntu 22.03

**To Reproduce**
I have created this [repository][1] where I recreated this bug and explained every step individually. Could any of you explain to me what exactly I am missing or is this a bug on the VCPKG side?

The short description is that when I am running the VCPKG command `./vcpkg install --feature-flags=manifests` which is going to be used inside of the Dockerfile is going to fail to one of the libs that have to be downloaded, each time will fail to other libs, is not going to be the same every single time. 

How can I fix this? Does anyone know?

  [1]: https://github.com/Vildnex/example_gitlab_and_vcpkg

**Comment by autoantwort** [comment]
Does this also happen when you executing curl directly?

**Comment by Vildnex** [comment]
@autoantwort i am not sure what do you mean

**Comment by autoantwort** [comment]
Can you execute `curl https://github.com/google/googletest/archive/release-1.12.1.tar.gz > /dev/null` instead of vcpkg?

**Comment by autoantwort** [comment]
If not, the problem is not vcpkg related (I guess it is not vcpkg related)

**Comment by Vildnex** [comment]
Ok so I've just checked it and works. I've update my Dockerfile to be like this:


```
FROM ubuntu:23.04

ARG VCPKG_VERSION

# update system & install required dev packages
RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    cmake \
    make \
    libjsoncpp-dev \
    uuid-dev \
    openssl \
    libssl-dev \
    zlib1g-dev \
    openssh-server \
    net-tools \
    vim \
    less \
    rsync \
    gdb \
    flex \
    bison \
    python3-sphinx \
    python3-sphinx-rtd-theme \
    python3-sphinx-sitemap \
    python3-breathe \
    nginx \
    htop \
    bat \
    zip curl git g++ build-essential pkg-config \
    libmariadb-dev-compat=1:10.11.2-1 \
    libmariadb-dev=1:10.11.2-1 \
    mariadb-server=1:10.11.2-1 \
    && rm -rf /var/lib/apt/lists/*

RUN curl https://github.com/google/googletest/archive/release-1.12.1.tar.gz > /dev/null

```

And I commented everything else and works just fine, this is the output below:
```

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.64kB done
#1 DONE 0.0s
#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s
#3 [internal] load metadata for docker.io/library/ubuntu:23.04
#3 DONE 1.5s
#4 [1/3] FROM docker.io/library/ubuntu:23.04@sha256:7a520eeb6c18bc6d32a21bb7edcf673a7830813c169645d51c949cecb62387d0
#4 DONE 0.0s
#5 [2/3] RUN apt-get update && apt-get install -y     git     build-essential     cmake     make     libjsoncpp-dev     uuid-dev     openssl     libssl-dev     zlib1g-dev     openssh-server     net-tools     vim     less     rsync     gdb     flex     bison     python3-sphinx     python3-sphinx-rtd-theme     python3-sphinx-sitemap     python3-breathe     nginx     htop     bat     zip curl git g++ build-essential pkg-config     libmariadb-dev-compat=1:10.11.2-1     libmariadb-dev=1:10.11.2-1     mariadb-server=1:10.11.2-1     && rm -rf /var/lib/apt/lists/*
#5 CACHED
#6 [3/3] RUN curl https://github.com/google/googletest/archive/release-1.12.1.tar.gz > /dev/null
#6 0.096   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#6 0.096                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
#6 DONE 0.7s
#7 exporting to image
#7 exporting layers 0.0s done
#7 writing image sha256:541736a8507cf8715af17aee8e1a62e6e7621ac01eb533b3b1d18b2e0cceae8b done
#7 naming to docker.io/library/docker_test_container done
#7 DONE 0.0s
Network docker_default  Creating
Network docker_default  Created
Container test_container  Creating
Container test_container  Created
Attaching to test_container
```

**Comment by Vildnex** [comment]
Does this mean it's a problem with VCPKG? Or I just need do set some kind of extra setting?

**Comment by SchaichAlonso** [comment]
There's no inherent problem with running vcpkg inside a gitlab runner, I'm doing it every day at work.

Your runner likely has no internet access. Can you run curl inside the runner, i.e. as part of the build pipeline that you're triggering vcpkg with?

Adding curl to the docker build results in curl be executed by the docker container composition pipieline, not the build pipeline that you want to run inside the container.

**Comment by Vildnex** [comment]
> 

I am not sure... but how exactly can my runner lack the internet access when it downlad all the libs unilt a randome one? Do you mean that at some point the internet is just gone at a randome library? 

Also I am not sure what you mean, but when you said to run the curl command inside of them runner as part of the build pipeline, you mean to change the .gitlab-ci file, right?
If so, after I change it like this:

```
script:
    - curl https://github.com/google/googletest/archive/release-1.12.1.tar.gz > /dev/null
```

I will get an error saying that I don't have curl installed.

**Comment by Vildnex** [comment]
> Here's a GitLab Cloud hosted public runner project that builds and consumes libpng using vcpkg on a raw ubuntu-23.04 docker image: https://gitlab.com/schaichalonso1/my-vcpkg-consumer
> 
> CI Run: https://gitlab.com/schaichalonso1/my-vcpkg-consumer/-/jobs/4927004756

I see... so in theory if I will use another server as runner should work...?

**Comment by SchaichAlonso** [comment]
> I see... so in theory if I will use another server as runner should work...?

You can give it a try. The [prologue of your the build log](https://gitlab.com/schaichalonso1/my-vcpkg-consumer/-/jobs/4927004756#L2) indicates the host being used to run the job.

Docker build failures are harder to troubleshoot then the same applications that are being `RUN` are outside of docker. You could put all the RUN stuff into a shell script, then execute that script when the container image starts up, before running the other code you're already running inside the container, which should work just as well at the expense of a longer startup time... however, as you probably run the composed container with a second pipeline, the second pipeline can artifact any log files produced by the setup/build script on top of the ones you're already collecting there.

---

Completely off topic, a [line like this one](https://github.com/Vildnex/example_gitlab_and_vcpkg/blob/283e656367f369596c286683efabd7513acf4b09/docker/Dockerfile#L50) is a ticking time bomb. Gitlab has support for [secret masking](https://docs.gitlab.com/ee/ci/variables/#mask-a-cicd-variable) to get the clear-text password out of the Dockerfile as well as the pipeline log, but to a malicious insider, overcoming the secret mechanism won't be difficult.

Deploy a ssh public key into `~root/.ssh/authorized_keys` instead. Public keys have no confidentiality whatsoever, so only manipulations of the file can introduce a breach, and for the manipulation to make it into any deployment it needs to be merged first, i.e. will be traceable to identify affected deployments as well as the insider having introduced it.

**Comment by Vildnex** [comment]
Thanks, I will check it later today and see it work

**Comment by Vildnex** [comment]
Ok so I fixed the issue, for some reasone it was related to my internet and I had to do some settings, and now works just fine. Thanks for help :D

Also one more question if may I, do you know how can I use gitlab cache system, in order to cashe my VCPKG libs? Such that they will not be downloaded every single time if they are already there?

**Comment by SchaichAlonso** [comment]
> Also one more question if may I, do you know how can I use gitlab cache system, in order to cashe my VCPKG libs? Such that they will not be downloaded every single time if they are already there?

We use nuget over here, though it works only so-so-ish. On the micro repository I posted earlier, something like [60aec55](https://gitlab.com/schaichalonso1/my-vcpkg-consumer/-/commit/60aec556fa1c6c6c975ac8dc7c9a9e86cd2df93d) turns on nuget binarycaching into the [gitlab package registry](https://gitlab.com/schaichalonso1/my-vcpkg-consumer/-/packages), which will result in future build jobs to download and reuse a previously generated nuget package rather then building the package ([old](https://gitlab.com/schaichalonso1/my-vcpkg-consumer/-/jobs/4927004756#L1370) vs [new](https://gitlab.com/schaichalonso1/my-vcpkg-consumer/-/jobs/4951877589#L3039)). It's seemingly irrelevant (14s old to 5s new) for the small demo project as libpng and friends compile in no significant time, but the larger the dependency set gets, the more time nuget will save.

More on nuget binary caching:
- https://docs.gitlab.com/ee/user/packages/nuget_repository/
- https://learn.microsoft.com/en-us/vcpkg/users/binarycaching

Note that this will break reproducibility, as vcpkg will simply download and extract packages rather then compiling them with all side effects of not building them (no build logs, no build intermediates, build-time-only dependencies won't be installed, ...) whenever the container environment is [compatible enough](https://learn.microsoft.com/en-us/vcpkg/users/binarycaching#abi-hash) to the previous run's one. You also need to have Gitlab Package publishing permissions (which are enabled by default) .

The main reason to favor a package publishing system (including tencent objects or others) over CI-specific cache functionality is that it isn't limited to the CI but instead can be setup to allow developers to use the package cache, too. In case of nuget on GitLab, developers working on their own computers (rather then the web-ide of gitlab) can to acquire a [Personal Access Token](https://gitlab.com/help/user/profile/personal_access_tokens.md) and feed it, and their gitlab username to `nuget source` on the developer machine, which grants them access to the package registry if the token has `read_registry` and they are otherwise eligable to access the registry. As the developer's environment is likely incompatible to the CI runner's one, the developer will not be able to reuse a CI runner generated package, however if the Personal Access Token also has `write_registry`, and the user is eligable to post packages on the repository, the local build result of the developer's box can be published and then be available for anyone eligable to access the registry, including the developer who published it, in the future (e.g. after removing the build directory or recloning the repository).

In [gitlab package registry](https://gitlab.com/schaichalonso1/my-vcpkg-consumer/-/packages), you might have noticed that each package is listed twice: one variant has been uploaded by the CI runner executing the pipeline of the `main` branch using an `ubuntu:23.04` image, while the other originates from `debian` branch which uses `debian:12` and is therefore "obviously" not compatible. Gitlab failing to group the packages nicely in the overview is one of the reasons I said it works only so-so-ish.
