### ISSUE TITLE
Missing symbol exports with gtkmm release build

### ISSUE THREAD

**Issue by mojofunk** [microsoft/vcpkg#3339]
To Reproduce:

1. Enable Visual Studio integration using $ vcpkg integrate install
2. Use vcpkg to build/install gtkmm
3. Clone the gtkmm-book from https://github.com/GNOME/gtkmm-documentation
4. Checkout the version that is relevant for the version of gtkmm that is in the vcpkg repository using $ git checkout -b 3.20.0 3.20.0
5. Create a new solution in Visual Studio (I used 2017 Community Edition) and add the 3 source files from the examples/book/treeview/list directory

Building/running a debug build should be successful.

Building a release build will fail with an error something like:

Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: void __thiscall Gtk::TreeViewColumn::`vbase destructor'(void)" (__imp_??_DTreeViewColumn@Gtk@@QAEXXZ)	TreeViewListExample	C:\Users\timbyr\Data\src\gtkmm-documentation\examples\book\treeview\list\TreeViewListExample\TreeViewListExample\examplewindow.obj	1

This issue is related to GTKMM_API being used for TreeViewColumn and CellLayout classes.

I ended up fixing this issue locally by writing a vcpkg focused CMake build of gtkmm and using the WINDOWS_EXPORT_ALL_SYMBOLS functionality. You can find the commit here:

https://github.com/mojofunk/vcpkg/commit/a025f1de251e985cf18e40843889f2feeb61f254

I'm not very familiar with CMake, but this seemed like a more robust fix than working out how to regenerate the Release/Win32/obj/gtkmm/gtkmm.def file (and the other .def files I guess).

**Comment by LarryIII** [comment]
@mojofunk Thanks for your feedback！ Looks like you did a great change with gtkmm in your branch. Could you please submit a new pull request for this issue? Please do not forget update the ports/gtkmm/control. For example, update 'Version: 3.22.2' to 'Version: 3.22.2 - 1'. Thank you!

**Comment by mojofunk** [comment]
Hi @LarryIII 

It is very unlikely at this point that I would submit a PR to add a CMake build system for Gtkmm. You or others are welcome to take what I have done and use it, if you feel that is the best way to fix this issue with Gtkmm on Windows. 

I personally think it would be better to either:

-  Work with upstream to fix the existing build system, or
-  Propose adding a CMake build system to the upstream repository that isn't specific to vcpkg and maintain it there.

But as I'm not involved in either vcpkg or gtkmm these are of course only my opinions.

This is also assuming that this issue hasn't been subsequently fixed in a newer version of gtkmm.

Thanks,

Tim

**Comment by NancyLi1013** [comment]
Hi @mojofunk, thanks for posting this issue. Gtkmm has been updated to 3.22.2 in vcpkg. I have tested this issue and it can be built successfully now. Please try to update this port and use it.

**Comment by kpeeters** [comment]
Is there any news on this? Or lacking that, can someone please post the last vcpkg commit for which gtkmm still works? Thanks!

**Comment by mojofunk** [comment]
I just had a quick look and it looks like same version of gtkmm is packaged that I had the issue with, which is 3.22.2.

So I would assume that the release build is still missing those exported symbols.

It looks like there was a change in the Windows build system in the version 3.22.3 that may address this issue: http://ftp.gnome.org/pub/GNOME/sources/gtkmm/3.22/gtkmm-3.22.3.news

**Comment by Illation** [comment]
I encountered the same issue when I started using a tree view in my program. Builds in Debug but not Release.

**Comment by jrbarne1** [comment]
I'm having this issue with the current build process.  Is there a fix for this in progress?  Either that, or could someone provide some instructions on how to make use of the CMake build mentioned?  I see that the meson build #9154 has stopped work.  I'd work with the debug version, but it has issues as well with bad memory addresses.

**Comment by rglbssw** [comment]
Having the same problem I found two possible "solutions" (or better: workararounds) based on two questions:

1. Why ist the symbol missing in the import library of the release version?
2. Why is the symbol needed by the code using Gtk::TreeView?

ad 1:
gtkmm does not use __declspec(dllexport) to export symbols. The  build process uses gendef to scan the obj-files for symbols to export and generates a def-file from which the import library is generated. The symbol is found in the debug version of the obj-file but missing in the release version. It seems to be optimized away and indeed, if we turn off  optimization in the release version the problem vanishes. A bit unusual to turn off optimization in release builds but because gtmm is only a wrapper around gtk it should not have big impact on performance.
(see https://github.com/rglbssw/vcpkg/commit/23df976f951943ed425f2a9291671ee6b1ab60ab)

ad 2:
The reason the symbol is needed linking the calling library or application seems to be a constructor template. As a template function it has to be inline and therefore it needs everything that's needed to construct an object of this class. Fortunately since C++-11 it is allowed to call one constructor from another one and we can avoid calling base class initialization from inline code by calling a non-inline constructor doing base class initialization. And fortunately this approach seems to fix the issue as well.
(see https://github.com/rglbssw/vcpkg/commit/67947cb4c150af8859e16134fc7eb8555f6bd55c)

Both workarounds are not perfect. I prefer the second one.

(Hopefully future versions of gtkmm will not have this issue, because gtkmm seems to switch to the __declspec(dllexport) approach, see https://github.com/GNOME/gtkmm/commit/fb0e7147fa56e6a66ed0e6d67a68a6f77c231f1b)
