### ISSUE TITLE
[Feature discussion] cmake package store management

### ISSUE THREAD

**Issue by barcharcraz** [Microsoft/vcpkg#334]
Cmake has the ability to get paths to packages from a global system specific location. For windows it's
HKCU:\Software\Kitware\CMake\packages\<packagename>

You just add a REG_SZ value to that key with any name and the path where the config files are located.

This could be used this to add vcpkg integrate support......

This could also allow something like vcpkg integrate zlib:x64-windows-static and have just zlib be redirected to a particular triplet.

Also a good new lint check would be that the package does not have any other keys in the registry, also the flag to tell cmake to never write to the registry (with export(PACKAGE)) may be a good thing to add to the default options.

**Comment by traversaro** [comment]
+1 to enable by default the [`CMAKE_EXPORT_NO_PACKAGE_REGISTRY`](https://cmake.org/cmake/help/v3.3/variable/CMAKE_EXPORT_NO_PACKAGE_REGISTRY.html#variable:CMAKE_EXPORT_NO_PACKAGE_REGISTRY) CMake variable.

**Comment by traversaro** [comment]
Other options that may be useful to use : https://cmake.org/cmake/help/v3.3/manual/cmake-packages.7.html#disabling-the-package-registry .

**Comment by ras0219-msft** [comment]
Thanks for bringing this up.

Adding CMake `vcpkg integrate` support would be interesting, however I don't think the user-wide package registry will work for us. Vcpkg is designed from the ground up to support simple and efficient cross-compilation. This is the motivation behind always qualifying a build with a triplet.

Each triplet specifies everything about the "platform" being built for, including target architecture, OS, compiler, compilation flags, and even library configuration. That's why we integrate through a `TOOLCHAIN` file; we are acting like a cross-compilation platform definition.

We _might_ be able to get away with only allowing export of packages under your host architecture's triplet (so, x64-windows, for example). However, another direct design goal of Vcpkg is to bake in consistency: every package you get from Vcpkg is guaranteed to be pulling its dependencies from the same set of libraries. Put another way, everyone using Boost in Vcpkg _must_ use the exact Boost that we built. We believe this brings a lot more sanity to building native code which isn't captured by most other systems (except possibly Nix, which is a _very_ cool project).

The ideal CMake integration, in my opinion, is to get CMake to default to our toolchain file on Windows if no other toolchain is specified. Maybe setting a user-wide environment variable for `CMAKE_TOOLCHAIN_FILE`?
