### ISSUE TITLE
[capnproto] update to 1.0.1

### ISSUE THREAD

**Issue by advisoft** [microsoft/vcpkg#33430]
### Library name

capnproto

### New version number

1.0.1

### Other information that may be useful (release notes, etc...)

The current version of Cap’n Proto isn't compatible with Visual Studio 2022 >17.6 when building as C++20

Issue has been fixed here: https://github.com/capnproto/capnproto/issues/1752 and is available in Cap’n Proto 1.0.1.

I've made the following change locally. The issue was resolved.
![image](https://github.com/microsoft/vcpkg/assets/11500738/5e1624b6-8d8d-44c0-bf50-cec2e4fb68d6)

**Comment by hornang** [comment]
I added a draft PR to update the port to `v1.0.1`, but then I got the following error:
```
...include\kj\async-inl.h(2296): error C2143: syntax error: missing ';' before 'function-style cast'
...include\kj\async-inl.h(2320): note: see reference to class template instantiation 'kj::_::Coroutine<T>::Awaiter<U>' being compiled
...include\kj\async-inl.h(2296): error C2059: syntax error: ''
...include\kj\async-inl.h(2296): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
```

The above problem has been fixed in https://github.com/capnproto/capnproto/commit/25caef2418d7b7b89fee220b98c1605faf668873, but it's not in v1.0.1. I added a patch to disable that `KJ_HAS_COROUTINE` section entirely.

**Comment by advisoft** [comment]
Awesome, thank you for sorting this so quick.
