### ISSUE TITLE
[paraview] build failure

### ISSUE THREAD

**Issue by petersteneteg** [microsoft/vcpkg#33489]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg install paraview

find_package(ParaView)
```

### Failure logs

CMake Error at build/vcpkg_installed/x64-windows/share/paraview/ParaView-targets.cmake:1116 (message):
  The imported target "ParaView::WrapClientServer" references the file

     "R:/ttk/build/vcpkg_installed/x64-windows/tools/paraview/vtkWrapClientServer-pv5.11d.exe"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "R:/ttk/build/vcpkg_installed/x64-windows/share/paraview/ParaView-targets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  build/vcpkg_installed/x64-windows/share/paraview/paraview-config.cmake:86 (include)
  R:/vcpkg/scripts/buildsystems/vcpkg.cmake:855 (_find_package)
  CMake/config.cmake:50 (find_package)
  CMakeLists.txt:12 (include)

### Additional context

in ParaViewClients-targets-debug.cmake:
```
# Import target "ParaView::WrapClientServer" for configuration "Debug"
set_property(TARGET ParaView::WrapClientServer APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ParaView::WrapClientServer PROPERTIES
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/tools/paraview/vtkWrapClientServer-pv5.11d.exe"
  )
```
Note the 'd' at the end

in https://github.com/microsoft/vcpkg/blob/8568364fbeb414db3fa5b5bfc436e57b4368c55f/ports/paraview/portfile.cmake#L152-L155
that debug exe is removed

same probably goes for: 
smTestDriver, vtkProcessXML

**Comment by FrankXie05** [comment]
vcpkg will put the `${CURRENT_PACKAGES_DIR}/${PORT}/tools` provided by all ports into the tool folder. 
Please confirm whether your locally installed these exe files.

![image](https://github.com/microsoft/vcpkg/assets/65999885/3bb97221-6baf-4472-839b-c862a5d18d7d)

**Comment by petersteneteg** [comment]
Yes, I have all those, but in `ParaView-targets-debug.cmake` the `ParaView::WrapClientServer` is refering to the debug versions of those tools

Note: I had the wrong config file above it should be `ParaView-targets-debug.cmake`

```
# Import target "ParaView::WrapClientServer" for configuration "Debug"
set_property(TARGET ParaView::WrapClientServer APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ParaView::WrapClientServer PROPERTIES
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/tools/paraview/vtkWrapClientServer-pv5.11d.exe"
  )
```

Just removing the trailing 'd' in the files names in that file will solve the issue. But Im not sure how to address that in the port file, I thought that vcpkg_cmake_config_fixup would have fixed it but it seems it does not...

**Comment by Neumann-A** [comment]
There are two possible solutions here: 

a) Do not remove the debug version of the tools
b) Point the debug targets to the release binaries. (Either by editing the files or removing them)

Comments for a)
- goes against vcpkg policy. Since only release version of tools should be provided
- does take significantly more space due to copying all the dependent dll's
- might not be required if there is no difference between release/debug versions
- would sill require to move the stuff somewhere else due to dll's with conflicting names

Comments for b)
- if there is no usage difference between release/debug; the debug version is simply not required
- could be easily fixed by either replacing `pv5.11d` with `pv5.11` or removing the `-debug.cmake` targets file if it only contains executable targets (unlikely)
