### ISSUE TITLE
[luajit] Crash on x64-osx with custom deployment target

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/vcpkg#33558]
**Describe the bug**

**Environment**
- OS: macOS 12.6.6 x86_64
- Compiler: Apple clang version 14.0.0 (clang-1400.0.29.202)

**To Reproduce**

I have a custom triplet `x64-osx-catalina-static-release.cmake`
```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_ARCHITECTURES x86_64)
set(VCPKG_BUILD_TYPE release)
set(VCPKG_OSX_DEPLOYMENT_TARGET 10.15)
```

1. ./vcpkg install luajit:x64-osx-catalina-static-release
2. Build and run my demo project https://github.com/xiaozhuai/vcpkg_demo/tree/master/src/luajit
3. It crash.

It works if I remove this line (`set(VCPKG_OSX_DEPLOYMENT_TARGET 10.15)`) in `x64-osx-catalina-static-release` triplet

This problem was introduced by #30608, before that, my custom triplet can work.
It's very odd.
Maybe @dg0yt knows clues about the problem.

**Comment by dg0yt** [comment]
This is the error I can reproduce with a custom triplet file for the target:
~~~
result: false
libc++abi: terminating with uncaught exception of type std::runtime_error: error in error handling
~~~
The error goes away when I also set the host triplet to the custom one, i.e. enforce a native build instead of a cross build.
And cross builds are what #30608 changed significantly. luajit is particular difficult to adapt to vcpkg's triplet regime, and upstream is very rigid...

**Comment by xiaozhuai** [comment]
> The error goes away when I also set the host triplet to the custom one

@dg0yt 
Can we fix it in `luajit` port?

**Comment by xiaozhuai** [comment]
@dg0yt 
How about add a port named `luajit-buildvm` and make it host only.

**Comment by dg0yt** [comment]
Please test #33581. Based on comparing native vs. cross build.

**Comment by xiaozhuai** [comment]
> Please test https://github.com/microsoft/vcpkg/pull/33581. Based on comparing native vs. cross build.

@dg0yt 
It works like a charm!
