### ISSUE TITLE
[<vsgxchange>]  cannot create ALIAS target "utf8::cpp" because another target   with the same name already exists.

### ISSUE THREAD

**Issue by Brucewu998** [microsoft/vcpkg#33734]
### Operating system

Ubuntu 20.04 LTS

### Compiler

GCC 9.4.0

### Steps to reproduce the behavior

```Shell
// vcpkg.json
{ "name": "",
   "version": "",
  "dependencies": {
      "name": "vsgxchange",
      "default-features": false,
      "features": ["assimp"]
   },
}
```

### Failure logs

CMake Error at /home/user/vcpkg/scripts/buildsystems/vcpkg.cmake:639 (_add_library):
  _add_library cannot create ALIAS target "utf8::cpp" because another target
  with the same name already exists.
Call Stack (most recent call first):
  build/vcpkg_installed/x64-linux/share/utf8cpp/utf8cppConfig.cmake:30 (add_library)
  /home/user/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  /snap/cmake/1329/share/cmake-3.27/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  build/vcpkg_installed/x64-linux/share/assimp/assimpConfig.cmake:38 (find_dependency)
  /home/user/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  /snap/cmake/1329/share/cmake-3.27/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  build/vcpkg_installed/x64-linux/share/vsgXchange/vsgXchangeConfig.cmake:4 (find_dependency)
  /home/user/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  src/core/app/CMakeLists.txt:11 (find_package)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Do you have a `CMakeLists.txt` file in your project? If so, please provide the `CMakeLists.txt` file for reproduction.

**Comment by dg0yt** [comment]
Typical reproducer for such problems:
~~~
cmake_minimum_required(...)
project(...)
find_package(FOO) # success
find_package(FOO) # failure
~~~

Typical solution:
The config file or find module must guard an `add_library` with `if(NOT TARGET ...)`.

For utfcpp, it is this line:
https://github.com/nemtrif/utfcpp/blob/f23474118c5c544c1403883976d78128d17125f9/utf8cppConfig.cmake.in#L6

**Comment by dg0yt** [comment]
https://github.com/nemtrif/utfcpp/pull/107

**Comment by Brucewu998** [comment]
> [nemtrif/utfcpp#107](https://github.com/nemtrif/utfcpp/pull/107)

I use this commit in my project, the problem fixed. thanks @dg0yt

**Comment by SaschaKaden** [comment]
I had the same problem and it was solved with this commit. (I have the same ubuntu and gcc version)
But atfter this solution I got a new error:

CMake Error at /home/sascha/develop/vcpkg/scripts/buildsystems/vcpkg.cmake:639 (_add_library):
  _add_library cannot create ALIAS target "utf8::cpp" because target
  "utf8cpp" is imported but not globally visible.
Call Stack (most recent call first):
  /home/sascha/develop/vcpkg/installed/x64-linux/share/utf8cpp/utf8cppConfig.cmake:31 (add_library)
  /home/sascha/develop/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /home/sascha/develop/vcpkg/installed/x64-linux/share/assimp/assimpConfig.cmake:38 (find_dependency)
  /home/sascha/develop/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  CMakeLists.txt:30 (find_package)

**Comment by dg0yt** [comment]
@SaschaKaden Either upgrade to at least CMake 3.18, and/or try to enabling `CMAKE_FIND_PACKAGE_TARGETS_GLOBAL` (CMake 3.24).
