### ISSUE TITLE
vcpkg fails to download git using curl on Linux Centos 7

### ISSUE THREAD

**Issue by bangusi** [Microsoft/vcpkg#3415]
I installed vcpkg on Centos 7. Then tried to build boost librarie and got the following error:

`vcpkg]$ ./vcpkg install boost`
The following packages will be built and installed:
    boost[core]:x64-linux
  * boost-accumulators[core]:x64-linux
...........
Starting package 1/138: boost-vcpkg-helpers:x64-linux
Building package boost-vcpkg-helpers[core]:x64-linux... 
A suitable version of git was not found (required v2.7.4). Downloading portable git v2.7.4...
Downloading git...
`curl: (3) <url> malformed`
Could not download 

My git version 
```
vcpkg]$ git --version
git version 1.8.3.1
```

My curl version
```
vcpkg]$ curl --version
curl 7.29.0 (x86_64-redhat-linux-gnu)
```

**Comment by alexkaratarakis** [comment]
The git version is very old. As the message says, it is looking for git v2.7.4 or above but we are currently not able to automatically download it if not found (I have improved the error message to state that). This is because portable versions of git are not available from official sources (except for windows). I assume this is because on linux you would typically get git from your package manager.

On latest master, I have made some modifications that might help you (specifically, in commit ab58f531ccf6da9895502cb8ae7bd85b29823d1d).
The required git version is now read from [vcpkgTools.xml](https://github.com/Microsoft/vcpkg/blob/master/scripts/vcpkgTools.xml#L31).
```
    <tool name="git" os="linux">
        <version>2.7.4</version>
        <exeRelativePath></exeRelativePath>
        <url></url>
        <sha512></sha512>
    </tool>
```

Therefore, you can try either:
- Updating git to a sufficiently new version
OR
- Reducing the required version to 1.8.0 in `vcpkgTools.xml` so it passes the check. Not sure if such an old version will work, but you can try.
