### ISSUE TITLE
[freetype] update to 2.13.2

### ISSUE THREAD

**Issue by carsten-grimm** [microsoft/vcpkg#34307]
### Library name

freetype

### New version number

2.13.2

### Other information that may be useful (release notes, etc...)

The current version in vcpkg is 2.12.1.

Release Notes 2.13.0: https://sourceforge.net/projects/freetype/files/freetype2/2.13.0/
Release Notes 2.13.1: https://sourceforge.net/projects/freetype/files/freetype2/2.13.1/
Release Notes 2.13.2: https://sourceforge.net/projects/freetype/files/freetype2/2.13.2/

**Comment by Cazadorro** [comment]
What is going on with this?  This is legit a work stoppage for me, and I'd try to fix this myself, but I can't figure out what is so special about this upgrade that it's been stopped for this long?   None of the comments make sense here, I don't see how any of the changes have caused this thing to be spending almost a year in limbo, I don't see how the package *wasn't already broken* if any of those issues were a thing after a simple version upgrade, in which case.  @Osyotr Why did you cancel your pull request in favor of a version where the person knew even less about the issues presented?  https://github.com/microsoft/vcpkg/pull/31382#discussion_r1193414743

**Comment by Osyotr** [comment]
> what is so special about this upgrade

Latest version of freetype exports `Freetype::Freetype` in its CMake config. Built-in CMake find module also creates this target.
IIRC the problem was that both `find_package(freetype CONFIG)` and `find_package(Freetype MODULE)` were called in one package (the former was called in form `find_dependency(freetype)`).

>Why did you cancel your pull request in favor of a version where the person knew even less about the issues presented?

Check timestamps on messages. I didn't have time to fix baseline regressions and hoped that that person had.
