### ISSUE TITLE
List supported build on linux 

### ISSUE THREAD

**Issue by edmBernard** [microsoft/vcpkg#3436]
I try to build some libraries and some of them are not able to build on linux yet. (uwebsockets, libuv, rocksdb)
Does someone try to make a list of supported build on linux ? (I don't know how much time it take to build all libs)
If there is a list of not supported libs, that can help contributor work. For example, libuv is configure to build the windows version [link](https://github.com/Microsoft/vcpkg/blob/master/ports/libuv/CMakeLists.txt#L5)

**Comment by mariusz102102** [comment]
I think that this project missing appveyor, travis configuration. We should have table with build status for each library and tripled for some predefined configuration

------------------
|library|x86-windows | x86-uwp | x64-linux | x64-osx | .................. |
|name_|OK __________ | FAILED___|FAILED___|OK______ | .................. |
.....................................

**Comment by cmpute** [comment]
continuous integration is not trivial for vcpkg, because building all of the libraries will take a considerably long time exceeding the time limit.

**Comment by mariusz102102** [comment]
Yes, it is not trivial. ... but we can:
1. Run builds in parallel. Create matrix library/triplet. 
AppVeyor in Enterprise mode support "Unlimited concurrent jobs" https://www.appveyor.com/pricing/
travis run few builds in parallel even for free plan
2. Check/build modified ports only. There is nice PR (I hope that it will be merged soon ...)
https://github.com/Microsoft/vcpkg/pull/2877
3. Choose only few most popular libraries e.g.: opencv, libpng, jpeg, zlib
https://github.com/trending/c++?since=monthly
4. Speedup vcpkg build e.g. on one build host run libraries with common dependencies

**Comment by edmBernard** [comment]
I have done a small script to launch build in docker [here](https://github.com/edmBernard/vcpkg_test)
I run each build in a new container. It use gcc-7 and cmake 3.11.
At this time I have this list (I'll update it later)

| Library | x64-linux |
| :-- | -- |
| abseil | Success |
| ace | Failed |
| alac | Success |
| alac-decoder | Success |
| alembic | Failed |
| allegro5 | Failed |
| anax | Success |
| angle | Failed |
| antlr4 | Failed |
| apr | Failed |
| apr-util | Failed |
| arb | Failed |
| args | Failed |
| armadillo | Failed |
| arrow | Failed |
| asio | Success |
| asmjit | Success |
| assimp | Success |
| atk | Failed |
| atkmm | Failed |
| atlmfc | Failed |
| aubio | Failed |
| aurora | Success |
| avro-c | Failed |
| aws-sdk-cpp | Failed |
| azmq | Failed |
| azure-c-shared-utility | Failed |
| azure-iot-sdk-c | Failed |

**Comment by JackBoosY** [comment]
Now you can find the ports that support the selected triplet in _scripts/ci.baseline.txt_.
