### ISSUE TITLE
Docs request: How to use Vcpkg in a Company CI scenario

### ISSUE THREAD

**Issue by jmecosta** [microsoft/vcpkg#345]
hi,

First off thanks for the providing this tool to the community. 

I am coming from coapp, we have put all our libs into NuGet packages and this solution is very flexible in a build farm. Nuget caches those binary libraries so restore is fast and when supporting multiple branches with multiple different reference versions we can have fine control over those libs.

Now i tried to look into vcpk to see if it can simplify our setup, and if i understand properly we need to install special target (same target) into each of our projects making it a very similar setup as nuget since each package install its own targets. Is it possible to define this per repository/branch rather than system wide as it would prevent the merge conflicts that arise when you upgrade a package (altought less since its only one package). 

Then in a build farm, where we tend to clean our checkout repositories we will not be able to use any caching mechanism to speed up the builds since we need to install the tool inside each checkout folder and each "restore" will cause recompilation of the libraries? 

Then nuget also allowed us to specify what libraries to use and only those libraries are used. This is very good to prevent illegal packages or illegal libraries to be used. If we want to have this kind of fine granularity then we would need to install different vcpk packages into different projects and the complexity starts rising a lot for a project like this.

I am creating this because in the FAQ using different version of same library is not very detailed. So would be good to know your opinion about those.

thanks in advance

jorge costa

**Comment by ras0219-msft** [comment]
Hi Jorge,

Thanks for bringing this up! We definitely need more documentation in this space and having context about what users are _actually_ doing is critical to make effective suggestions. For everyone else reading this in the future, please feel free to chime in with your own internal situations or email us directly using `vcpkg contact` if that's more comfortable for you -- we'd be happy to make specific recommendations and work with you to make sure Vcpkg works perfectly for your situation.

Let me first restate some assumptions I'm making about what you've said above. You currently use some OSS libraries which we have packaged in Vcpkg along with several separately-versioned internal components. You currently build the OSS libraries yourself and manually bundle them into individual NuGet packages which are consumed by the other internal components and your "main" build. Your other internal components, however, are built separately and you use NuGet to cache various binary builds between the components. For these internal components, it isn't a big deal if `B@v3` built against `A@v2` but `C@v4` depends on both `B@v3` and `A@v3`; you're fine with NuGet's solution of "Silently give C's build A@3 and B@3, B probably doesn't care _that_ much about having A@v2;)".

Finally, I will assume that the "illegal" libraries you're talking about are to enforce good code organization, structure, and layering amongst your internal components. For "platform"-type libraries like Boost or Zlib or the Win32 APIs, I assume you aren't as concerned about who uses them -- if anyone does, they will be pulled into your final executable, so there's really no "benefit" to restricting access to a privileged few.

##### Philosophy
If I got that right, then what Vcpkg is designed to replace is the painstaking step of building the _external_ libraries and convincing them to use each other. Like other "system"-style package managers, we are not a good fit for generic, rapid binary caching where you really want to "explore" the larger state space of every permutation of different library versions (like is commonly done with internal dependencies). To illustrate what I mean by this a bit better, let's say you have ExtA, ExtB, and ExtC which you update whenever a new official stable version comes out (~every month). You then have IntA, IntB, IntC which are "secret sauce" components that you rebuild multiple times a day against each other. At any given time, you expect your buildservers to have access to every possible value of:
```
{ExtA@v1} x {ExtB@v2} x {ExtC@v3}
times
{IntA@v0.95, IntA@v0.96, IntA@v0.97, ... IntA@v0.99}
times
{IntB@above versions}
times
{IntC@above versions}
```
which with just _5_ commits per day on each component works out to be up to 125 different builds of IntC if all the internal components are heavily interdependent and you do not assume binary compatibility between versions (which we don't in Vcpkg). This makes Vcpkg not a good fit for internal packages which you are more familiar with or are willing to place additional constraints over, such as changing underlying dependency versions without rebuilding.

However, in the above diagram, ExtA, ExtB, and ExtC clearly only need to be built once -- they don't depend on your secret sauce! Additionally, whenever you perform updates, you'll probably be updating all of them in one atomic bump instead of asking for every possible combination of versions, which really cuts down on the number of different builds required. This is where "system"-style package managers like Vcpkg shine at exploiting the simplicity here to making your life easier. We linearize all our internal independently-versioned packages into a single, simple "vcpkg version".

##### Recommendation
I would recommend adopting Vcpkg with the following approach. First, categorize your components into two classes:
 - The slowly updating components which you want to universally enforce a version upon. Example: "We're updating to openssl 1.0.2j and boost v1.62; we _really_ do not want any packages accidentally building against the older (possibly insecure) version!" Most commonly, these are going to be your external libraries, but in a large company you might have far-flung teams that fit in well here.
- Your fast-updating internal components where mixing various versions is expected. Teams working on `A` will use an old version of `B` and vice-versa for team `B`. Some companies will check all these pieces into a single gigantic monorepo and just do massive incremental builds (famously google and facebook), whereas others will do lots of binary caching between components that deals with the combinatoric version space (famously amazon).

Vcpkg is ideal for managing that first set of "platform" dependencies and enforcing rules across your entire product instead of allowing every project to potentially disagree with each other. Given your current packaging solution, I think a good step in this direction would be to start using Vcpkg to build the very bottom of your stack (such as boost). Then, take the entire Vcpkg repo after the build and chuck it into a single NuGet package which can be depended upon by any of your internal pieces. You should use the `[1.0]` syntax [1] for these references to disable the default NuGet behavior of allowing you to mix versions! You will then get a nice, hard error at NuGet package upgrade time if you try to mix incompatible binaries instead of build (or worse, runtime) failures.

The NuGet-package integration we currently provide is a thin veneer over an MSBuild props file located at `scripts\buildsystems\msbuild\vcpkg.targets`. For build integration, you can add the usual NuGet `build\native\<package>.targets` that redirects to Vcpkg's props file.

I can definitely see value in a command that exports the entire set of Vcpkg-built binaries out to a single, consistent NuGet package and I want to ensure it works great for your situation if you'd be interested in using it.

I'd also be happy to work more directly with you via email if you have specific details you'd prefer to not share publicly.

[1] https://docs.nuget.org/ndocs/create-packages/dependency-versions#version-ranges

**Comment by jmecosta** [comment]
@ras0219-msft thanks for your points. i think providing export of vcpkg repo  nuget package is the closest i think we have at the moment and the easiest to take on board.

i would however like to describe a bit more of our internal structure and how we got to the nuget solution, can you share you email or do i send to opencode@microsoft.com ?

**Comment by ras0219-msft** [comment]
Use vcpkg@microsoft.com; this should be the email displayed from `vcpkg contact` as well.

**Comment by jmecosta** [comment]
@ras0219-msft ive sent email vcpkg@microsoft.com, ensure if it reach there.

**Comment by ras0219-msft** [comment]
We received it, thanks!

**Comment by ras0219-msft** [comment]
We've added that export command that makes this much easier: `vcpkg export`!

Take a look at our release blog post (https://blogs.msdn.microsoft.com/vcblog/2017/05/03/vcpkg-introducing-export-command/) or the in-command help.

**Comment by jmecosta** [comment]
oh yeah :) this now starts to be interesting. reading through some questions?

version of the nuget package does  not seem to follow sem version 2.0 -> is there a switch to enforce sem version or some other version format?

symbols? are the export commands also packaging symbols in the nuget package? if thats the case how big do we expect packages to be. If not is there a way to package symbols. Earlier CoApp splited those in to 3 package (lib, redist and symbols)

but this indeed look something that we can use to replace CoApp :)

**Comment by jmecosta** [comment]
and then i read the comments and the symbols question is answer there. so just quick question about version

**Comment by ras0219-msft** [comment]
Because native code doesn't (as a universal rule) follow SemVer, we currently create unique NuGet packages to reflect that. We believe this is the safest and simplest way to use export, because it makes it obvious when you mix vcpkg versions (you clearly have two vcpkg entries in your manifest) and you won't accidentally upgrade between different exports and hit ABI incompatibility problems.

We have an open issue to add the ability to customize the name (and we'll also allow customizing the version), so you will be able to ask the command to generate packages according to whatever scheme is appropriate for you. A workaround to get that _now_ would be to edit the NuGet package using something like NuGet Package Explorer or just to unpack and repack it with the changed name.

**Comment by jmecosta** [comment]
Alright thanks for the clarification,  good this will be possible in future
out of the box. And this is indeed a very good improvement for this tool.

Regards

**Comment by scramsby** [comment]
Excellent news! Thank you for the update.

Even if the symbols are always included in a single package, curious to see if you can avoid through MSBuild settings always copying the pdbs to the target project, as that's wasted space and time during the build process for all but the final application package project.

Also curious what is coming next in terms of improving NuGet package versioning and potentially allowing for more granular generated packages.

-Scott Ramsby
________________________________

**Comment by mloskot** [comment]
I have just opened issue on general documentation about vcpkg installation, #1874, with some questions related to this issue as well.

**Comment by calumr** [comment]
Could we also have some documentation on simple ways to publish the .nupkg files and consume them from VS? I'm building osg from vcpkg, and we'd like to avoid building it on every developer's machine (with dependencies it takes longer than I'd like to build).

Serving the .nupkg file from a private server would be nice, but this seems difficult as it's not just as simple as hosting the file somewhere. I also don't want to check the .nupkg in to git, it's 100MB after I've trimmed osg down to what we need.

**Comment by L4ZZA** [comment]
what's the status on this? are any of the features discussed implemented yet?

**Comment by PhoebeHui** [comment]
@jmecosta, we do a lot of improvements since then, could you help confirm if feature [bianry cache](https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md#ci-examples) meet your requirements?
