### ISSUE TITLE
 When `export CMAKE_<LANG>_COMPILER_LAUNCHER=sccache`, second build `waiting to take filesystem lock` should not be endless.

### ISSUE THREAD

**Issue by loynoir** [microsoft/vcpkg#34658]
**Describe the bug**

When 

- `export CMAKE_<LANG>_COMPILER_LAUNCHER=sccache`

Bug

- second build `waiting to take filesystem lock` should not be endless.

**Environment**
- OS: Docker ArchLinux
- Compiler: default

**To Reproduce**

- cmake version 3.27.7

- vcpkg package management program version 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce

```sh
$ rm -rf build; cmake -B build -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake >/dev/null && echo OK
OK
$ rm -rf build; cmake -B build -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake >/dev/null && echo OK
OK
$
$ export CMAKE_C_COMPILER_LAUNCHER=sccache
$ export CMAKE_CXX_COMPILER_LAUNCHER=sccache
$
$ rm -rf build; cmake -B build -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake >/dev/null && echo OK
OK
$ rm -rf build; cmake -B build -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake && echo OK
-- Running vcpkg install
waiting to take filesystem lock on /path/to/VCPKG_ROOT/.vcpkg-root...
(Ctrl-C)
```

**Expected behavior**

When 

- `export CMAKE_<LANG>_COMPILER_LAUNCHER=sccache`

Bug

- second build `waiting to take filesystem lock` should not be endless.

**Failure logs**
-(please attached failure logs)

**Additional context**

**Comment by autoantwort** [comment]
Hm I also have this problem since a few days and few days ago I started using `CMAKE_<LANG>_COMPILER_LAUNCHER` and `ccache` and `sccache`. Hmm .... 

But I am curious how this could affect the file locking behavior of vcpkg-tool

**Comment by klalumiere** [comment]
This issue has been plaguing me and my team for a long time, but I think I finally understood it, and found a workaround.

I ran `pstree` while `vcpkg install` was running, and I got the output

```
vcpkg─┬─sh───cmake───cmake───ninja───11*[sh───sccache───11*[{sccache}]]
      └─{vcpkg}
```

If I'm not mistaken, File Descriptors (FD) are inherited. Hence, `sccache` ends up with FDs on `$VCPKG_ROOT/.vcpkg-root`. The thing is, `sccache` runs as a server in order to be as efficient as possible, so it never releases that lock.

The workaround that seems to work is to run `sccache --start-server` manually before `vcpkg install`, so it's not vcpkg that starts the `sccache` server.

**Edit:** The workaround doesn't work if vcpkg fails. In this case, you still need to manually call `sccache --stop-server && sccache --start-server` to land on your feet. 🙁
