### ISSUE TITLE
[vcpkg] bootstrap failure on windows with latest updates

### ISSUE THREAD

**Issue by cenit** [Microsoft/vcpkg#3473]
VS 15.7.1
Win10SDK: 10.0.17134.0

I am trying to boostrap a secondary instance of vcpkg and I am stuck with some problems with it: both the `bootstrap-vcpkg.bat` and the `CMakeLists.txt` builds of `vcpkg` fail (I tried to build vcpkg using CMake since in principle I thought that it would have been possible).

The error with `bootstrap-vcpkg.bat` is the following:

```
CL : fatal error C1083: Cannot open compiler intermediate file: 'c:\users\sinigard\codice\vcpkg_2nd\toolsrc\vcpkglib\release\vcpkglib.pch': No such file or directory [C:\Users\sinigard\Codice\vcpkg_2nd\toolsrc\vcpkglib\vcpkglib.vcxproj]
```
the file `vcpkglib.pch` is there, I don't know what's the issue. My compiler works and I can build other codes fine

**Comment by nagua** [comment]
Hey, I had the same problem and it turned out to be a problem with using WSL for git.
In the newest WSL version Windows 10: 1803 directories created with WSL get case-sensitive file lookup.
This does not work well with msbuild which tries to use an all uppercase filename (at least with cmake) to find files. So I suspect that this is the real problem with error.

**Comment by cenit** [comment]
fixed in latest October 2018 update, or manually setting case=off in /etc/wsl.conf (https://gist.github.com/cenit/baa2d11e7dd0a66362437b5808ceb624)
