### ISSUE TITLE
[onnx] Allow dynamic builds

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#34899]
### Is your feature request related to a problem? Please describe.

onnx has `declspec(dllimport/dllexport)` macros so why it is only allowed to be build as a static library?

### Proposed solution

Remove `vcpkg_check_linkage(ONLY_STATIC_LIBRARY)`

**Comment by traversaro** [comment]
> ### Is your feature request related to a problem? Please describe.
> 
> onnx has `declspec(dllimport/dllexport)` macros so why it is only allowed to be build as a static library?
> ### Proposed solution
> 
> Remove `vcpkg_check_linkage(ONLY_STATIC_LIBRARY)`

I am not sure if that was the original reason, but I encountered a problem in packaging onnx in conda-forge, and I found a problem building the library has shared on Windows, due to using the same export macro in two different libraries, see https://github.com/conda-forge/onnx-feedstock/pull/105#issuecomment-1794599952 for more details, as I think it could be interesting also for vcpkg.

I a

**Comment by dg0yt** [comment]
Is there onnx-proto in vcpkg?

**Comment by ilya-lavrenov** [comment]
> Is there onnx-proto in vcpkg?

it's a part of onnx port.

**Comment by dg0yt** [comment]
Okay...
Anyways, this should really be fixed properly.

**Comment by Neumann-A** [comment]
> due to using the same export macro in two different libraries, see https://github.com/conda-forge/onnx-feedstock/pull/105#issuecomment-1794599952 for more details,

Interesting. Without having read that before I already opt for a very similar solution in https://github.com/Neumann-A/my-vcpkg-ports/blob/master/onnx/fix-build.patch except forcing the onnx target to be a static library since I didn't want to export all symbols.
