### ISSUE TITLE
[vulkan] Port should install SDK & runtime

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#34908]
### Is your feature request related to a problem? Please describe.

Failure to load `vulkan-1.dll` since RT component was not checked by the port. 

### Proposed solution

Simply extract the required components into the installed tree instead looking for it on the system

**Comment by Neumann-A** [comment]
If I read https://sdk.lunarg.com/sdk/download/1.3.268.0/windows/config.json correctly the vulkan SDK is just a bunch of libraries put together. As such vcpkg should not request the user to install the SDK at all.

**Comment by charles-lunarg** [comment]
VulkanSDK/Vulkan-Loader maintainer here.

The VulkanSDK installer is more than just a bunch of libraries put together. But I can see how someone can come to that conclusion. Its kinda messy and in my opnion not well designed, but for historical reasons is the way it is.

The Vulkan-Loader is the 'driver frontend' that all Vulkan applications use to load graphics drivers & layers. On windows, it is the `vulkan-1.dll` and is located in Windows/System32. It is installed by graphics drivers or by the VulkanRT installer (some drivers use the VulkanRT, some have their own mechanisms to install it). On linux/apple, there is only one file (`libvulkan.so`/`libvulkan.dylib`). However on windows there is also the import library `vulkan-1.lib` which the VulkanSDK is responsible for. CMake's FindVulkan.cmake looks for `vulkan-1.lib` in the VulkanSDK bin directory. 

Because `vulkan-1.dll` is a driver front end and is installed by graphics drivers, the VulkanSDK does *not* include it. Without graphics drivers installed, there is no way to use Vulkan anyhow, so installing Vulkan-1.dll with the SDK (or with vcpkg for that matter) doesn't make applications run. 

> Failure to load vulkan-1.dll since RT component was not checked by the port.

Can you elaborate on where this error is coming from? Is that from running a Vulkan application?

**Comment by Neumann-A** [comment]
So who is responsible for installing the layers normally? For me this seems something a final app installer needs to do or the graphics driver already took care of it?

**Comment by charles-lunarg** [comment]
On Windows, the VulkanSDK installs the layers it manages. Non-SDK layers (like renderdoc, OBS, steam, etc) manage their own installation. On Linux/MacOS system package managers often have packages for layers that work out of the box. Same goes for non-sdk layers, though that depends on the layer in question.

**Comment by Neumann-A** [comment]
> On Windows, the VulkanSDK installs the layers it manages

What do I need these VulkanSDK layers for? Especially since they will never be installed on the final deployment target since the deployment target will probably not install an SDK.

**Comment by charles-lunarg** [comment]
Discussing layers is a digression from the original issue (and only relevant to the "VulkanSDK is a bundle of libraries comment"). So apologies for pulling this issue off track.

**Comment by charles-lunarg** [comment]
> Failure to load vulkan-1.dll since RT component was not checked by the port.

While this could be stated as 'by design' (at least in the case of the VulkanSDK) there is nothing technically wrong with vcpkg installing the required components to allow applications to link and even run. 

Because vcpkg is a dependency manager, it makes sense to manage dependencies. How novel! 

What I push back against is applications bundling the vulkan-loader (ie vulkan-1.dll) into their application. [Full explanation is here](https://github.com/KhronosGroup/Vulkan-Loader/blob/main/docs/LoaderApplicationInterface.md#bundling-the-loader-with-an-application). Gist is that at least on windows, there has been multiple changes to how drivers are found, which caused apps with old loaders to no longer find drivers. How applications ship themselves isn't for vcpkg to decide, but its worth knowing about.
