### ISSUE TITLE
Can't install live555

### ISSUE THREAD

**Issue by emptyVoid** [Microsoft/vcpkg#3511]
-- Downloading http://www.live555.com/liveMedia/public/live.2018.02.28.tar.gz... Failed. Status: 22;"HTTP response code said error"

Can't you use live555-latest.tar.gz instead?

**Comment by pravic** [comment]
Actually, good point. But it contradicts the Vcpkg policy about having snapshots of precise versions.

@ras0219-msft @alexkaratarakis Here is a problem: live555 ships only the latest library version [here](http://www.live555.com/liveMedia/public/) and [does not support](http://www.live555.com/liveMedia/faq.html#no-source-code-repository) source code archives or repositories. 

How to resolve this? On the one hand, Vcpkg requires a specific version in portfiles. On the other hand, it is impossible to build a specific version (because of live555). 

What can we do? We can go with something like "Live555 latest" meta version and build always [the latest](http://www.live555.com/liveMedia/public/live555-latest.tar.gz) library archive. Well, actually, we can't because of SHA512 absence. 

Another way is to use some public mirror. But there are no official ones and any of unofficial can be abandoned.

**Comment by Cheney-W** [comment]
Currently, we have re-set the live555 installation, which must to use the --head option, so it will always use live555-latest.tar.gz.
