### ISSUE TITLE
[qtdeclarative] Build error on x64-windows

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#35247]
To reproduce: 
`vcpkg x-set-installed qtwebengine[core]`

You get:
```
Installing 38/40 qtdeclarative:x64-windows...
error: The following files are already installed in G:/v/vcpkg1/vcpkg_installed/x64-windows and are in conflict with qtdeclarative:x64-windows
Installed by qttools:x64-windows
tools/Qt6/bin/libcrypto-3-x64.dll

Elapsed time to handle qtdeclarative:x64-windows: 22.4 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtdeclarative
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[qtdeclarative]+Build+error+on+x64-windows
Include '[qtdeclarative] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2999-12-31-unknownhash
    vcpkg-scripts version: 7039df020 2023-11-21 (8 hours ago)
```

**Comment by Adela0814** [comment]
@autoantwort I'm not able to repro this issue, I tried to install `qttools` through `qttools: x64 Windows` and `qttools [*]: x64 Windows`, but I couldn't find the conflict file `tools/Qt6/bin/libcrypto-3-x64.dll`.

**Comment by autoantwort** [comment]
strange :)

**Comment by dg0yt** [comment]
Not so strange: Installation order and artifact caching. Note that `tools/Qt6/bin` is a shared folder, not a per-port folder.

I would assume that `libcrypto-3-x64.dll` is a transitive dependency via `qtbase` runtime. All runtime in `tools/Qt6/bin` related to `qtbase` should probably be installed and owned by `qtbase` - even if not used by `qtbase` directly. Otherwise the ownership is taken over by reverse dependencies of `qtbase`, subject to installation order. And then you will get clashes it packages are restored from artifact cache.

**Comment by autoantwort** [comment]
But in the binary cache is only the content of the packages folder which is not shared. So the clash should be reproducible or there should be none in the first place.
