### ISSUE TITLE
[grpc] update to 1.60.0

### ISSUE THREAD

**Issue by nicely-dev** [microsoft/vcpkg#35566]
### Library name

grpc

### New version number

1.60.0

### Other information that may be useful (release notes, etc...)

Current version (1.51.1) is more than a year old.

Thank you.

**Comment by Tradias** [comment]
@Adela0814  I have started to work on this. Already added `utf8-range` as a new dependency to vcpkg which is a requirement of the updated `upb`. However, my work on updating `upb` has been slow due to the massive patch required to get it to work, now I am running into what seems like ODR violations too.

**Comment by nicely-dev** [comment]
Hello,

the current version is now 1.62.0 so please skip 1.60.0 if we can get it working ;)

**Comment by nicely-dev** [comment]
I manually compiled the library. I won't need it anymore. Thank you anyway.
