### ISSUE TITLE
[gdal 3.6.4] undefined symbol

### ISSUE THREAD

**Issue by davesworking** [microsoft/vcpkg#36243]
Hi,

I have successfully build gdal but a Developer reporting the following issue linking:

> I need to use the API of one of the static libraries included in gdal (libproj). The problem is that for some reason the runtime linker appears to be unable to resolve all the dependencies and I got errors like :
> 
> symbol lookup error: ... undefined symbol: _ZN5osgeo4proj2io15DatabaseContext
> 
> However the symbol is indeed in the library libgdal.so

Is it possible that I need some compiler flag to expose these symbols?

Thanks,
Dave

**Comment by dg0yt** [comment]
Is it possible that you are refering to an OSGeo build of GDAL, instead of a vcpkg build?

The information about names and library is confusing, too:  
Your description: unknown, "libgdal.so", "static libraries included in gdal (libproj)".  
x64-linux-dynamic (community): dynamic, libgdal.so, libproj.so  
x64-linux (vcpkg CI): static, libgdal.a, libproj.a
