### ISSUE TITLE
Add Cinder

### ISSUE THREAD

**Issue by BryanDiLaura** [microsoft/vcpkg#363]
I'd be interested in seeing [Cinder](https://libcinder.org/about). 

Description from their website: 
Cinder is a C++ library for programming with aesthetic intent - the sort of development often called creative coding. This includes domains like graphics, audio, video, and computational geometry. Cinder is cross-platform, with official support for OS X, Windows, iOS, and WinRT.
Cinder is production-proven, powerful enough to be the primary tool for professionals, but still suitable for learning and experimentation.
Cinder is released under the 2-Clause BSD License.

**Comment by sdcb** [comment]
To add cinder, There is a bunch of dependencies need to resolve here:
https://github.com/cinder/Cinder/tree/master/include

As you can see, some dependency are not included in vcpkg for the moment, I think that's the block.

**Comment by MikeGitb** [comment]
I also would very much like to see this library in vcpkg. 

@sdcb: Can you elaborate why this is a blocking issue and what would be necessary to unblock it? Cooking cinder brings all necessary dependencies either as source code or as a prebuilt library. It should however not bee too difficult to remove all dependencies that are already provided by vcpkg in the build script if that leads to conflicts otherwise (I'm not sure though if any of those dependencies have cinderspecific modifications.

**Comment by alexkaratarakis** [comment]
Using system dependencies when they are available enables:

- Upgrading/security patching
- Static linking (otherwise there are symbol conflicts with the system copies)
- Sane debugging (`#include <cinder>` does the same thing everywhere)

Removing/not-using the checked-in dependencies that are already in `vcpkg` and leaving the others would be reasonable. Here is the current status (checked means it is in `vcpkg`):
- [ ] angle
- [x] asio
- [x] boost
- [x] freetype
- [x] glfw
- [ ] glload
- [x] glm
- [x] jsoncpp
- [ ] msw
- [x] vorbis / ogg
- [x] rapidxml
- [x] stb
- [ ] tinyexr
- [x] utfcpp

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
