### ISSUE TITLE
[<zlib>] build failure

### ISSUE THREAD

**Issue by 123ysys** [microsoft/vcpkg#36400]
### Operating system

Windows 10 x86

### Compiler

cmake

### Steps to reproduce the behavior

```Shell
`G:\Snax\vcpkg>call ./bootstrap-vcpkg.bat -disableMetrics`
```

### Failure logs

Error: Building package zlib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[zlib]+Build+error
including:
  package: zlib[core]:x64-windows -> 1.2.11#13
    vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
    vcpkg-scripts version: 4d94109ff 2022-03-18 (1 year, 10 months ago)

Additionally, attach any relevant sections from the log files above.

vcpkg install FAILED... Return code: 1
Carefully review the message log to find the cause.
Spaces in directory names are known to cause an error.
[config-x64-windows-err.log](https://github.com/microsoft/vcpkg/files/14071052/config-x64-windows-err.log)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/14071053/config-x64-windows-out.log)
[extract-err.log](https://github.com/microsoft/vcpkg/files/14071054/extract-err.log)
[extract-out.log](https://github.com/microsoft/vcpkg/files/14071055/extract-out.log)
[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/14071056/install-x64-windows-dbg-err.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/14071057/install-x64-windows-dbg-out.log)
[install-x64-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/14071058/install-x64-windows-rel-err.log)
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/14071059/install-x64-windows-rel-out.log)
[patch-x64-windows-0-err.log](https://github.com/microsoft/vcpkg/files/14071060/patch-x64-windows-0-err.log)
[patch-x64-windows-0-out.log](https://github.com/microsoft/vcpkg/files/14071061/patch-x64-windows-0-out.log)
[patch-x64-windows-1-err.log](https://github.com/microsoft/vcpkg/files/14071062/patch-x64-windows-1-err.log)
[patch-x64-windows-1-out.log](https://github.com/microsoft/vcpkg/files/14071063/patch-x64-windows-1-out.log)
[patch-x64-windows-2-err.log](https://github.com/microsoft/vcpkg/files/14071064/patch-x64-windows-2-err.log)
[patch-x64-windows-2-out.log](https://github.com/microsoft/vcpkg/files/14071065/patch-x64-windows-2-out.log)
[patch-x64-windows-3-err.log](https://github.com/microsoft/vcpkg/files/14071066/patch-x64-windows-3-err.log)
[patch-x64-windows-3-out.log](https://github.com/microsoft/vcpkg/files/14071067/patch-x64-windows-3-out.log)
[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/14071069/stdout-x64-windows.log)
[x64-windows.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/14071070/x64-windows.vcpkg_abi_info.txt)

### Additional context

I saw many issues reported the zlib package failed on Windows. However, I am using a bat script which will bootstrap vcpkg and "Build dependencies using VCPKG" as it said. And it failed, when I am in the step of "call ./bootstrap-vcpkg.bat". Though the error tips advise me to "using the latest portfiles with `git pull` and `.\vcpkg update`" but this is not working.

**Comment by StarGate-One** [comment]
>vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
>vcpkg-scripts version: https://github.com/microsoft/vcpkg/commit/4d94109ffbe2fbffe500b3035c6c9a972f3787dc 2022-03-18 (1 year, 10 months ago)

The vcpkg repo and the vcpkg-tool are outdated, almost 2 years for both.

From the stdout-x64-windows.log:
>[DEBUG] Downloading https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
[DEBUG] Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
Error: Failed to download from mirror set:
https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404
https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404
https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404
https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404
https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: WinHttpSendRequest() failed: 12029
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: WinHttpSendRequest() failed: 12029
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: WinHttpSendRequest() failed: 12029
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: WinHttpSendRequest() failed: 12029
https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404
https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404

- Try the following:
`cd <vcpkg-root>` in your case it is `G:\Snax\vcpkg>`
`git pull`  Many updates should be performed since the repo is almost 2 years old
`.\vcpkg-bootstrap.bat`
`.\vcpkg upgrade` follow with `vcpkg upgrade --no-dry-run` if there are upgrades to be applied
`.\vcpkg install <port, features> <port, features>`

- If the above does not fix, then deleting and recreating the vcpkg repo from scratch would be needed:
  To delete and recreate vcpkg repo:
`cd G:\Snax`
`rmdir /q /s .\vcpkg`
`git clone <vcpkg.repo>`
`cd G:\Snax\vcpkg`
`.\vcpkg-bootstrap.bat`
`.\vcpkg install <port, features> <port, features>` as needed 

The failures downloading tools needed by vcpkg to build some of the ports are updated often by msys/mingw maintainers with older versions being removed and are unavailable - vcpkg is updated often to pull the latest available versions available.
