### ISSUE TITLE
[libtorch] fails to run with glog

### ISSUE THREAD

**Issue by magni-mar** [microsoft/vcpkg#37141]
### Operating system

Linux

### Compiler

GCC 13

### Steps to reproduce the behavior

```Shell
cmake_minimum_required(VERSION 3.28)
project(libtorch-test)

set(CMAKE_CXX_STANDARD 23)
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/cmake_modules" "${CMAKE_CURRENT_LIST_DIR}/cmake_modules/findModules")

find_package(Torch REQUIRED)

add_executable(main main.cpp)
target_link_libraries(main
  PRIVATE
    torch
)



and then run the exe. For reference, this is the exe so no one is confused:

```cpp
auto main() -> int {
    return 0;
}
```

### Failure logs

ERROR: something wrong with flag 'timestamp_in_logfile_name' in file '/opt/vcpkg/buildtrees/glog/src/v0.6.0-1e4356b0ac.clean/src/logging.cc'.  One possibility: file '/opt/vcpkg/buildtrees/glog/src/v0.6.0-1e4356b0ac.clean/src/logging.cc' is being linked both statically and dynamically into this executable.

### Additional context

When linking libtorch to any executable I get this error when I run the file. This error disappears if I use my own portfile and only change these flags:

```txt
-DUSE_GFLAGS=OFF
-DUSE_GLOG=OFF
```

these flags are normally ON.

**Comment by mheyman** [comment]
I fixed this with a custom triplet on linux (I have another for windows). You may not need the `VCPKG_CMAKE_CONFIGURE_OPTIONS` line if you are not building on a system with lots of CUDA installations - mine was picking the wrong CUDA version without that line. The relevant part is that the `gflags` and `glog` vcpkg ports, for some reason, must be compiled as shared libraries to run with the `libtorch` port currently. I suspect a bug in the `libtorch` port.

```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DCUDAToolkit_ROOT=/usr/local/cuda-12.1 -DCMAKE_CUDA_COMPILER=/usr/local/cuda-12.1/bin/nvcc -DCUDAToolkit_INCLUDE_DIR=/usr/local/cuda-12.1/include)
# libtorch requires gflags and glog to be dynamic to link to it
if (${PORT} MATCHES "gflags|glog")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
    set(VCPKG_FIXUP_ELF_RPATH ON)
endif()
```

I have an `"overlay-triplets": ["./custom-triplet"]` line in my `vcpkg-configuration.json` file and a `"cacheVariables": { "VCPKG_TARGET_TRIPLET": "x64-linux-libtorch" }` (and similar for windows) in my `CMakePresets.json` file to point to those custom triplets.

<details>
<summary>windows</summary>
Windows custom triplet for otherwise static-linked vcpkg ports:

```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
# libtorch only builds dynamic and requires glog and openblas to be dynamic to link to it
if (${PORT} MATCHES "libtorch|glog|openblas")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
```
</details>
