### ISSUE TITLE
[New Port Request] CopperSpice

### ISSUE THREAD

**Issue by BA7LYA** [microsoft/vcpkg#37511]
### Library name

CopperSpice

### Library description

Set of cross platform C++ libraries (Core, Gui, Network, Multimedia, SQL, Vulkan, etc)

### Source repository URL

https://github.com/copperspice/copperspice

### Project homepage

https://www.copperspice.com

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

CopperSpice is a set of individual libraries which can be used to develop cross platform software applications in C++. It is a totally open source project released under the LGPL V2.1 license and was initially derived from the Qt framework. Over the last several years CopperSpice has completely diverged, with a goal of providing a first class GUI library to unite the C++ community.

Our motivation for developing CopperSpice was to change the fundamental design and turn the existing framework into a set of libraries for C++ developers. We are accomplishing this by leveraging modern C++ functionality, new technology, and modern tooling. CopperSpice currently requires C++17 or newer.

**Comment by BA7LYA** [comment]
[CppCon 2015: Barbara Geller & Ansel Sermersheim “CopperSpice: A Pure C++ GUI Library"](https://www.youtube.com/watch?v=LIiwBNvTllk)

**Comment by BA7LYA** [comment]
CopperSpice is a pretty good library, hope vcpkg could absorb it.

**Comment by Neumann-A** [comment]
I have a port for 1.8.2 but their code simply did not compile (https://twitter.com/Iluinrandir/status/1737238813284671772). I might retry with 1.9.1.

Authors claimed (on X/twitter) to have had contact with the vcpkg team and that the team required changes to their installation layout and license (https://twitter.com/copperspice_cpp/status/1734355938373693685 & https://twitter.com/copperspice_cpp/status/1734356034633015613). I smelled a lot of nonsense from that claim so i wanted to make a port for it since it should be simple enough if upstream supports cmake. But as it turns out upstreams code did not compile so I never finished the port (and thus did not add the required adjustments). 
Here are the files:
[portfile.cmake (requires rename from txt)](https://github.com/microsoft/vcpkg/files/14626953/portfile.txt)
[vcpkg.json](https://github.com/microsoft/vcpkg/files/14626954/vcpkg.json)
Feel free to adjust so that it works.
