### ISSUE TITLE
Get rid of Mono for binary caching with NuGet

### ISSUE THREAD

**Issue by konjac** [microsoft/vcpkg#37540]
Hi team,

I want to propose an update for binary caching with NuGet.

The implementation is using nuget.exe. Nuget.exe itself is windows only. For Linux OS, vcpkg uses Mono as a workaround. 

However, Mono is on a deprecation path. For example, our production pipelines are using Microsoft 1P Linux image, which doesn't provide Mono environment as its current status.

Could we consider moving to use `dotnet nuget` which has similar functionality and is cross-platform?

**Comment by SchaichAlonso** [comment]
VCPKG uses nuget's implicit authentication ability, which has to have been setup using `nuget.exe`'s [set-api-key](https://learn.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-setapikey) prior to the vcpkg invokation.
[set-api-key](https://learn.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-setapikey), however, is not interfaced by `dotnet nuget`, which means that `nuget.exe` will be needed even if vcpkg was invoking `dotnet nuget`, in order to setup the authentication on the build agent.

**Comment by konjac** [comment]
> VCPKG uses nuget's implicit authentication ability, which has to have been setup using `nuget.exe`'s [set-api-key](https://learn.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-setapikey) prior to the vcpkg invokation. [set-api-key](https://learn.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-setapikey), however, is not interfaced by `dotnet nuget`, which means that `nuget.exe` will be needed even if vcpkg was invoking `dotnet nuget`.

Hi @SchaichAlonso, authentication should not be a problem, because dotnet can leverage https://github.com/microsoft/artifacts-credprovider. Actually, I have tried to create a fake mono which translates `nuget.exe` command to `dotnet nuget` which could workaround.
