### ISSUE TITLE
Error: Building package pcl:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by skycowninja** [Microsoft/vcpkg#3757]
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:170 (message):
    Command failed: C:/vcpkg-master/downloads/tools/cmake-3.10.2-windows/cmake-3.10.2-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: C:/vcpkg-master/buildtrees/pcl/x64-windows-dbg
    See logs for more information:
      C:\vcpkg-master\buildtrees\pcl\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/pcl/portfile.cmake:75 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package pcl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pcl:x64-windows
  Vcpkg version: 0.0.113-nohash

Additionally, attach any relevant sections from the log files above.

[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2124402/install-x64-

[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2124402/install-x64-windows-dbg-out.log)

I ran .\vcpkg update and no new updates were found. I had it installed before and it was good, but I messed up something. I deleted everything and tried a new install, then this occurred.

**Comment by kangdw91** [comment]
If you solve the  ploblem?
I have same Ploblem help me

**Comment by ZYberTanC** [comment]
The same happens to me recently, have you found the solution?

**Comment by PhoebeHui** [comment]
From install-x64-windows-dbg-out.log, it failed due to C:\vcpkg-master\installed\x64-windows\include\flann/flann.hpp(41): fatal error C1083: Cannot open include file: 'flann/util/matrix.h': No such file or directory.

I installed pcl:x64-windows successfully now. could you have a try?

PS F:\vcpkg\src> ./vcpkg version
Vcpkg package management program version 2018.11.23-nohash

PS F:\vcpkg\src> ./vcpkg install pcl:x64-windows
The following packages will be built and installed:
  * boost-asio[core]:x64-windows
  * boost-context[core]:x64-windows
  * boost-coroutine[core]:x64-windows
  * boost-interprocess[core]:x64-windows
  * boost-ptr-container[core]:x64-windows
  * boost-signals2[core]:x64-windows
  * boost-uuid[core]:x64-windows
  * flann[core]:x64-windows
  * glew[core]:x64-windows
  * libogg[core]:x64-windows
  * libtheora[core]:x64-windows
    pcl[core]:x64-windows
  * qhull[core]:x64-windows
  * vtk[core]:x64-windows
....
Building package pcl[core]:x64-windows... done
Installing package pcl[core]:x64-windows...
Installing package pcl[core]:x64-windows... done
Elapsed time for package pcl:x64-windows: 55.07 min

Total elapsed time: 1.543 h

The package pcl:x64-windows provides CMake targets:

find_package(PCL CONFIG REQUIRED)
target_link_libraries(main PRIVATE ${pcl_component})

**Comment by PhoebeHui** [comment]
@skycowninja, thanks for posting this issue. I installed pcl:x64-windows successfully with VS 2017 15.9.7. Please open a new issue if this is still a problem for you.
