### ISSUE TITLE
[freerdp] ld: library not found for -lwinpr-tools on macOS

### ISSUE THREAD

**Issue by KangLin** [microsoft/vcpkg#37581]
@dg0yt  I see ports/freerdp/vcpkg.json. winpr-tools is !ios. Why?

    "winpr-tools": {
      "description": "Build winpr tools",
      "supports": "!android & !ios & !uwp"
    },

The following error appears on macOS:

[ 80%] Building CXX object build_plugins/FreeRDP/Client/CMakeFiles/PluginClientFreeRDP.dir/DlgGetUserPasswordFreeRDP.cpp.o
[ 80%] Building CXX object build_plugins/FreeRDP/Client/CMakeFiles/PluginClientFreeRDP.dir/DlgDesktopSize.cpp.o
[ 80%] Building CXX object build_plugins/FreeRDP/Client/CMakeFiles/PluginClientFreeRDP.dir/PluginClientFreeRDP_autogen/EJRQKI7XPS/qrc_translations_FreeRDP.cpp.o
[ 81%] Linking CXX shared library ../../../plugins/Client/libPluginClientFreeRDP_d.dylib
ld: library not found for -lwinpr-tools
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [plugins/Client/libPluginClientFreeRDP_d.0.0.26-75-g24432233.dylib] Error 1
make[1]: *** [build_plugins/FreeRDP/Client/CMakeFiles/PluginClientFreeRDP.dir/all] Error 2
make: *** [all] Error 2

Detail see: https://github.com/KangLin/RabbitRemoteControl/actions/runs/8368726585/job/22913291207#step:14:1495

**Comment by dg0yt** [comment]
ios: The feature is meant to control winpr-tools *executables*, not libs. But probably this is coupled at the moment. I didn't expect the tools lib to be used outside freerdp's own tools.

osx: So you want to use the `winpr-tools` *library*. It is installed as `libwinpr-tools3.a`, according to the CI logs. Note the `3`.
But AFAICS the CMake config provided by port freerdp doesn't offer a target `winpr-tools`. The target  would encode the exact lib location. And that's a problem because other freerdp targets refer to `winpr-tool` via interface link libraries.
This is a port bug. The build directory has export files at least when `winpr-tools` is enabled.
(That's the downside of not using target namespaces: Poor diagnostics.)

**Comment by dg0yt** [comment]
> ios: The feature is meant to control winpr-tools _executables_, not libs. But probably this is coupled at the moment. I didn't expect the tools lib to be used outside freerdp's own tools.

No, the libs are always built. We just lack the cmake config. PR is coming.

**Comment by dg0yt** [comment]
> No, the libs are always built. We just lack the cmake config. PR is coming.

No, I mixed it up again: You don't get the winpr-tools lib without actually building tools (`winpr-hash`, `winpr-makecert`). I won't change this aspect: It needs patching or upstream changes.

You can still test the feature on ios by modifying the manifest locally, or by using `--allow-unsupported`. If it builds successfully, we can relax the condition.

**Comment by KangLin** [comment]
@dg0yt Thank you.

**Comment by dg0yt** [comment]
It is not fixed until https://github.com/microsoft/vcpkg/pull/37589 is merged.

**Comment by KangLin** [comment]
> It is not fixed until #37589 is merged.

The is not bug. I am modify. please close #37589 . thank you!

**Comment by KangLin** [comment]
@JonLiu1993 Why reopend?

**Comment by JonLiu1993** [comment]
It is not fixed until https://github.com/microsoft/vcpkg/pull/37589 is merged.

**Comment by dg0yt** [comment]
> It is not bug. I am modify. please close #37589 . thank you!

There is a BIG FAT port bug. CMake config is incomplete, not providing all targets as cross-referenced.

**Comment by dg0yt** [comment]
> ~~~
> ld: library not found for -lwinpr-tools

This should never appear. The lack of the `winpr-tools` CMake target should already stop the CMake configuration of your project, not letting you proceed to the build.
If the target would be named `FreeRDP::winpr-tools`, it would be obvious.
If the project used `target_link_libraries main private $<TARGET_NAME:winpr-tools>)`, you would get a similar effect even without a namespace prefix.

**Comment by KangLin** [comment]
> > It is not bug. I am modify. please close #37589 . thank you!
> 
> There is a BIG FAT port bug. CMake config is incomplete, not providing all targets as cross-referenced.

It's better to file a new bug. It is not the main cause of this PR.

**Comment by dg0yt** [comment]
> It's better to file a new bug. It is not the main cause of this PR.

It is, as explained in https://github.com/microsoft/vcpkg/issues/37581#issuecomment-2011539338.

Please don't close the bug again. It is destructive.

**Comment by KangLin** [comment]
> Error message in title and original post:

This is the result of my forgetting find_package(winpr-tools)

**Comment by KangLin** [comment]
> Error message in title and original post:
> 
> > ```
> > ld: library not found for -lwinpr-tools
> > ```
> 
> This should never appear. The lack of the `winpr-tools` CMake target should already stop the CMake configuration of your project, not letting you proceed to the build. If the target would be named `FreeRDP::winpr-tools`, it would be obvious. If the project used `target_link_libraries main private $<TARGET_NAME:winpr-tools>)`, you would get a similar effect even without a namespace prefix.

This is the result of my forgetting find_package(winpr-tools)

**Comment by dg0yt** [comment]
I'm glad that you found that you don't need it, because it resolves the ios aspect.

`find_package(winpr-tools)` only works when the port bug is fixed. And the port bug must be fixed to resolve the cross references in exported targets. And so I'm glad that your error report quickly put us on the right track. I used the chance to look for more missing configs, and fixed them, too.

(Maybe I also need to check that there are `find_dependency` calls as needed...)

**Comment by KangLin** [comment]
@dg0yt Good luck :)
