### ISSUE TITLE
How to choose whether to compile as a dynamic library or a static library when using the manifest mode in Linux

### ISSUE THREAD

**Issue by newpeople123** [microsoft/vcpkg#37792]
In Linux, use the vcpkg manifest mode to install OSG, draco and other libraries, run the vcpkg install command, and the compilation is successful, but the compiled libraries are static libraries (*.a), how to set the compilation to dynamic libraries (*.so) in the manifest mode?
[vcpkg.json](https://github.com/microsoft/vcpkg/files/14785886/vcpkg.json)

**Comment by SchaichAlonso** [comment]
The `x64-linux` and `x86-linux` presets are exclusively static.

There is a [x64-linux](https://github.com/microsoft/vcpkg/blob/master/triplets/community/x64-linux-dynamic.cmake) triplet, which you can force to be used by setting the `VCPKG_TARGET_TRIPLET` cmake variable either in the command line or in your [CMakePresets.json](https://cmake.org/cmake/help/v3.29/manual/cmake-presets.7.html) , i.e. before parsing the toolchain.

While the triplet file is shipped with vcpkg's mainline distribution, it is not officially supported, so you might also want to add `--allow-unsupported` to your `VCPKG_INSTALL_OPTIONS` cmake variable, to suppress port developers over-eagerly having blacklisted everything but the supported triplets in some ports.

```
cmake -DVCPKG_TARGET_TRIPLET=x64-linux-dynamic -DVCPKG_INSTALL_OPTIONS="--debug;--allow-unsupported" -B ${builddir} -S ${sourcedir}
``` 

Or add something like this to your preset file
```
{
  "version": 6,
  "cmakeMinimumRequired": {
    "major": 3,
    "minor": 25,
    "patch": 0
  },
  "configurePresets": [
    {
      "name": "x64-linux-dynamic-vcpkg",
      "description": "use dynamic libraries from vcpkg submodule",
      "cacheVariables": {
        "VCPKG_INSTALL_OPTIONS": "--debug;--allow-unsupported",
        "VCPKG_TARGET_TRIPLET": "x64-linux-dynamic"
      },
      "toolchainFile": "${sourceDir}/vcpkg/scripts/buildsystems/vcpkg.cmake"
    }
  ]
}
```

If your linux supports RPaths (which most do), you can also set the `VCPKG_APPLOCAL_DEPS` cmake option to `OFF` in order to avoid copying the dynamic libraries next to your executables while linking, which saves time and space on some projects that have many paths for executables (notoriously unit tests can end up producing a lot of executables each in it's own directory).

**Comment by newpeople123** [comment]
> You can pass the option `--triplet=x64-linux-dynamic` to your installation command.

Thank you

**Comment by newpeople123** [comment]
> The `x64-linux` and `x86-linux` presets are exclusively static.
> 
> There is a [x64-linux-dynamic](https://github.com/microsoft/vcpkg/blob/master/triplets/community/x64-linux-dynamic.cmake) triplet, which you can force to be used by setting the `VCPKG_TARGET_TRIPLET` cmake variable either in the command line or in your [CMakePresets.json](https://cmake.org/cmake/help/v3.29/manual/cmake-presets.7.html) , i.e. before parsing the toolchain.
> 
> While the triplet file is shipped with vcpkg's mainline distribution, it is not officially supported, so you might also want to add `--allow-unsupported` to your `VCPKG_INSTALL_OPTIONS` cmake variable, to suppress port developers over-eagerly having blacklisted everything but the supported triplets in some ports.
> 
> ```
> cmake \
>   -DVCPKG_TARGET_TRIPLET=x64-linux-dynamic \
>   -DVCPKG_INSTALL_OPTIONS="--debug;--allow-unsupported" \
>   -DCMAKE_TOOLCHAIN_FILE=${vcpkgdir}/scripts/buildsystems/vcpkg.cmake \
>   -B ${builddir} \
>   -S ${sourcedir}
> ```
> 
> Or add something like this to your preset file
> 
> ```
> {
>   "version": 6,
>   "cmakeMinimumRequired": {
>     "major": 3,
>     "minor": 25,
>     "patch": 0
>   },
>   "configurePresets": [
>     {
>       "name": "x64-linux-dynamic-vcpkg",
>       "description": "use dynamic libraries from vcpkg submodule",
>       "cacheVariables": {
>         "VCPKG_INSTALL_OPTIONS": "--debug;--allow-unsupported",
>         "VCPKG_TARGET_TRIPLET": "x64-linux-dynamic"
>       },
>       "toolchainFile": "${sourceDir}/vcpkg/scripts/buildsystems/vcpkg.cmake"
>     }
>   ]
> }
> ```
> 
> If your linux supports RPaths (which most do), you can also set the `VCPKG_APPLOCAL_DEPS` cmake option to `OFF` in order to avoid copying the dynamic libraries next to your executables while linking, which saves time and space on some projects that have many paths for executables (notoriously unit tests can end up producing a lot of executables each in it's own directory).

Thank you
