### ISSUE TITLE
System Integration for triplet x64-windows-static 

### ISSUE THREAD

**Issue by degski** [Microsoft/vcpkg#3780]
I have built a number of libs with the triplet `x64-windows-static`. I've also built tbb, this library can only be built /MD or /MDd and therfor used `x64-windows`.

Hence, I have the following folder structure:
    ..\vcpkg\installed\vcpkg
    ..\vcpkg\installed\x64-windows
    ..\vcpkg\installed\x64-windows-static

`..\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets` dictates the `System Integration`, but does not take into account (**at all !!!**) that the triplet could actually be `x64-windows-static`, so system integration fails as the integration assumes `x64-windows` (in my case).

EDIT: Workaround: create a junction `..\installed\x64-windows` pointing to `..\installed\x64-windows-static`, not ideal, but it solves the problem (without changing any code) to an extent, while creating another, as all will go in the same folder now.

**Comment by SeanFarrow** [comment]
Could this be corrected using the props/tartgets files. How do you create a junction on windows in the meantime?

**Comment by ras0219-msft** [comment]
Thanks for posting!

This is by design -- each triplet is a completely independent graph of packages that shouldn't be mixed.

If you'd like to have some libraries built statically and others built dynamically, please see our documentation on triplets[1] which shows how to customize your local triplets to meet your needs :)

[1] https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md#per-port-customization

**Comment by Voskrese** [comment]
`cmake --build . -- /p:VcpkgTriplet=x86-windows-static`

`msbuild *.vcxproj` or `*.sln /p:VcpkgTriplet=x86-windows-static` or `/p:VcpkgTriplet=x64-windows-static`
