### ISSUE TITLE
liblzma port uses compromised version

### ISSUE THREAD

**Issue by marekr** [microsoft/vcpkg#37839]
**Describe the bug**
vcpkg updated liblzma to 5.6.0. This version is known as compromised and backdoored

https://nvd.nist.gov/vuln/detail/CVE-2024-3094
https://www.redhat.com/en/blog/urgent-security-alert-fedora-41-and-rawhide-users

This is a solid 10.0 CVE score vulnerability

vcpkg should immediately revert from 5.6.0

**Comment by MichaelCurrie** [comment]
[This PR](https://github.com/microsoft/vcpkg/pull/37841) already addresses the issue by downgrading xz version.

However - to fix your build, run `git pull` and then make this unofficial one-liner change to grab xz from an unofficial mirror.

![image](https://github.com/microsoft/vcpkg/assets/5267078/a0d322e3-d3d3-440b-a743-d752af3b79b5)

Then building will work again:

```
.\vcpkg install liblzma:x64-windows
```

**Comment by carsten-grimm** [comment]
> [This PR](https://github.com/microsoft/vcpkg/pull/37841) already addresses the issue by downgrading xz version, but it still leaves the build broken because the entire xz repo has been disabled by GitHub so ALL versions are blocked.
> 
> So, to fix your build, run `git pull` to sync that fix, and then make this unofficial one-liner change to grab xz from an unofficial mirror.
> 
> ![image](https://private-user-images.githubusercontent.com/5267078/318187590-a0d322e3-d3d3-440b-a743-d752af3b79b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MDI5MDAsIm5iZiI6MTcxMTgwMjYwMCwicGF0aCI6Ii81MjY3MDc4LzMxODE4NzU5MC1hMGQzMjJlMy1kM2QzLTQ0MGItYTc0My1kNzUyYWYzYjc5YjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzBUMTI0MzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTQzNWJiN2FmZjhjY2EwYTRjMTUyNjc2NmI1YTM3MjEyNGVmOGEyNjQ3NGMzYjBkNGRjMjk1YzdiZDE5OWJkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HKd6JWmZuZ3oSA6RGY7eO9PcY0Mmtp9-MUWMtlgn05w)
> 
> Then building will work again:
> 
> ```
> .\vcpkg install liblzma:x64-windows
> ```

If you are using vcpkg in manifest mode with a builtin baseline that references an affected version of liblzma, you can use [an overlay port](https://learn.microsoft.com/en-us/vcpkg/concepts/overlay-ports) to implement the suggestion by @MichaelCurrie .

**Comment by dg0yt** [comment]
> to implement the suggestion by @MichaelCurrie

... until that fork is taken down for the same reasons as the official repo.

**Comment by carsten-grimm** [comment]
> > to implement the suggestion by @MichaelCurrie
> 
> ... until that fork is taken down for the same reasons as the official repo.

Yes. I am sure the folks involved do not make these decisions lightly. I hope there will be an actual solution soon.

**Comment by Neustradamus** [comment]
The official XZ team announcement is here:
- https://tukaani.org/xz-backdoor/

Important to know: There is no problem with contributors here like @carsten-grimm.

But several people mix all because I have requested the XZ update in vcpkg.
I have received a lot of bad messages (private and public).
I have no link with XZ project, I follow only the project and do announcement or/and update requests.
I have requested 5.4.5 and 5.6.0 because there was only 5.4.4 in vcpkg.

@gowthamgts has participated on Reddit against me badly and I have commented on two places where he has commented (on my SCRAM request publications):
- https://github.com/duesee/imap-flow/issues/96#issuecomment-2027899343
- https://github.com/marlam/msmtp/issues/36#issuecomment-2027900141

You can look here the original comment:
- https://news.ycombinator.com/item?id=39871685
- All the XZ backdoor story on Reddit is here: https://news.ycombinator.com/item?id=39865810

You can follow my announcements here:
- https://mastodon.social/@neustradamus
- https://twitter.com/neustradamus
- https://bsky.app/profile/neustradamus.bsky.social
- https://news.ycombinator.com/user?id=neustradamus

The good point, people speak about SCRAM "Salted Challenge Response Authentication Mechanism" security ;)
- https://github.com/scram-sasl/info/issues/1

Badly, some people or projects like only old unsecure mechanisms, some would like security improvements.

cc: @duesee, @canselcik, @winkelcode, @timrobbins1, @sebpretzer, @sroussey, @masklinn, @asmor (not sure).

**Comment by blessio** [comment]
> [This PR](https://github.com/microsoft/vcpkg/pull/37841) already addresses the issue by downgrading xz version, but it still leaves the build broken because the entire xz repo has been disabled by GitHub so ALL versions are blocked.
> 
> So, to fix your build, run `git pull` to sync that fix, and then make this unofficial one-liner change to grab xz from an unofficial mirror.
> 
> ![image](https://private-user-images.githubusercontent.com/5267078/318187590-a0d322e3-d3d3-440b-a743-d752af3b79b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTcyMDIsIm5iZiI6MTcxMjE1NjkwMiwicGF0aCI6Ii81MjY3MDc4LzMxODE4NzU5MC1hMGQzMjJlMy1kM2QzLTQ0MGItYTc0My1kNzUyYWYzYjc5YjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMTUwODIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGYwZTg1OGJmYmIxZTE0YjEzOTE0MTIxNWY2YjNiNDNmOWJkYmIwOGY0MDdjYTYxMWZlYzhmM2RiZmE4MzAzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JTX-AKPQSfg4WV9tqGFMhyhTtGB1pwxnue39yvtKn4s)
> 
> Then building will work again:
> 
> ```
> .\vcpkg install liblzma:x64-windows
> ```

You may have to not only reinstall the library as explained in the above (THANKS! @MichaelCurrie)

1) clean the vcpkg cache
https://github.com/microsoft/vcpkg/issues/14157 ( on windows this is to delete C:\Users<your-user>\AppData\Local\vcpkg\archives - on other platforms please search the internet )
2) update the file `portfile.cmake` as explained above in all subfolders of VCPKG_ROOT\buildtrees\versioning_\versions\liblzma\

**Comment by Neustradamus** [comment]
@teo-tsirpanis has done a PR about the new XZ version (5.6.2) here:
- https://github.com/microsoft/vcpkg/pull/39024

cc: @carsten-grimm.

Linked to:
- https://github.com/microsoft/vcpkg/issues/37893
- https://github.com/microsoft/vcpkg/pull/37841
- https://github.com/microsoft/vcpkg/issues/37839
- https://github.com/microsoft/vcpkg/pull/37199
- https://github.com/microsoft/vcpkg/issues/37197
- https://github.com/microsoft/vcpkg/pull/34306

Official XZ links:
- https://tukaani.org/
- https://tukaani.org/xz/
- https://tukaani.org/xz/#_stable
- https://tukaani.org/xz-backdoor/
- https://github.com/tukaani-project/
- https://github.com/tukaani-project/xz
