### ISSUE TITLE
[liburing] can't be used as dependency with the PkgConfig in other port

### ISSUE THREAD

**Issue by jiayuehua** [microsoft/vcpkg#37876]
### Operating system

linux

### Compiler

gcc

### Steps to reproduce the behavior

```Shell
gh pr checkout 31768 
./vcpkg install "folly[liburing]"
```

### Failure logs

 /home/jiayuehua/vcpkg/buildtrees/folly/config-x64-linux-out.log   

-- Looking for ASN1_TIME_diff
-- Looking for ASN1_TIME_diff - found
-- Found PkgConfig: /home/linuxbrew/.linuxbrew/Homebrew/bin/pkg-config (found version "0.29.2")
-- Checking for module 'liburing>=2.0'
--   No package 'liburing' found
CMake Error at /home/jiayuehua/vcpkg/downloads/tools/cmake-3.29.0-linux/cmake-3.29.0-linux-x86_64/share/cmake-3.29/Modules/FindPkgConfig.cmake:619 (message):       
  The following required packages were not found:

   - liburing>=2.0

Call Stack (most recent call first):
  /home/jiayuehua/vcpkg/downloads/tools/cmake-3.29.0-linux/cmake-3.29.0-linux-x86_64/share/cmake-3.29/Modules/FindPkgConfig.cmake:847 (_pkg_check_modules_internal) 
  CMake/folly-deps.cmake:147 (pkg_check_modules)
  CMakeLists.txt:141 (include)

-- Configuring incomplete, errors occurred!
ninja: build stopped: subcommand failed.

### Additional context

liburing should be able to used as pkgconf dependency in other port.

**Comment by dg0yt** [comment]
AFAICS there is nothing wrong with the liburing pkgconfig file.
And `vcpkg_fixup_pkgconfig` verifies the file during the port build.
Even a real test is successful:
~~~
-- Checking for module 'liburing>=2.0'
--   Found liburing, version 2.5
~~~
The problem is folly. In particular, when the minimum required version of CMake is less than 3.1,  
`-DPKG_CONFIG_USE_CMAKE_PREFIX_PATH=ON` must be added to the options.

**Comment by jiayuehua** [comment]
you are right, confirmed. I close this issue.
