### ISSUE TITLE
GDAL:x86-windows does not build because it depends on libmysql

### ISSUE THREAD

**Issue by ahhz** [Microsoft/vcpkg#3793]
GDAL:x86-windows does not build because it depends on libmysql

See also: 
https://github.com/Microsoft/vcpkg/issues/3574 (same issue but lacks clear title)
https://github.com/Microsoft/vcpkg/issues/3614 (osgearth fails, depends on gdal and hence libmysql)
https://github.com/Microsoft/vcpkg/issues/3029 (libmysql fails, how about dependent libraries?)

**Comment by ShinNoNoir** [comment]
One possible solution is to make `libmysql` optional using [features](https://blogs.msdn.microsoft.com/vcblog/2018/02/06/vcpkg-introducing-installation-options-with-feature-packages/).

I have done this for [a fork of vcpkg that has a port for the legacy version of GDAL (1.x)](https://github.com/ShinNoNoir/vcpkg/tree/gdal1/ports/gdal1). Basically, you'd need to remove `libmysql` from `Build-Depends` in the `CONTROL` file and then add the following new section:

    Feature: mysql
    Description: MySQL support for GDAL 1.x
    Build-Depends: libmysql

Next, `portfile.cmake` needs to be modified by guarding the `file` commands for `libmysql` with an `if`:

    if("mysql" IN_LIST FEATURES)
        file(TO_NATIVE_PATH "${CURRENT_INSTALLED_DIR}/include/mysql" MYSQL_INCLUDE_DIR)
        file(TO_NATIVE_PATH "${CURRENT_INSTALLED_DIR}/lib/libmysql.lib" MYSQL_LIBRARY_REL)
        file(TO_NATIVE_PATH "${CURRENT_INSTALLED_DIR}/debug/lib/libmysql.lib" MYSQL_LIBRARY_DBG)
    endif()

Now, `vcpkg install gdal` should work since it won't rely on `libmysql`. If you want to have MySQL support for the 64 bits version of gdal, you could execute `gdal[mysql]:x64-windows`.

**Comment by OlafvdSpek** [comment]
Another option is to use libmariadb..

**Comment by ShinNoNoir** [comment]
@OlafvdSpek That is certainly another option, but I don't know how much work it entails to get that working. Making libmysql support an optional feature was quite easy.

**Comment by OlafvdSpek** [comment]
Changing Build-Depends might be all that's required.

**Comment by ahhz** [comment]
Thank you both. I followed ShinNoNoir's advice now, because I don't really need libmysql at the moment. It is not clear to me whether Olaf's solution would require a GDAL and/or vcpkg fix, but replacing the dependency on a library that is no longer supported seems to be the sustainable solution.

**Comment by widdyZale** [comment]
I revert the libmysql to the previous version 5.7.17-3, pass build x86-windows and install successfully.

**Comment by JackBoosY** [comment]
Hi @ahhz , thanks for reporting this issue!
Now GDAL has been fixed by adding a feature gdal [mysql-libmariadb]. Please update vcpkg and rebuild GDAL. If still has problem, please open a new issue.
Thanks.
