### ISSUE TITLE
How to compile vcpkg libraries using Clang?

### ISSUE THREAD

**Issue by BiliBiliFox** [microsoft/vcpkg#38042]
**Environment**
- OS: Windows 10
- Compiler: Clang

Dear vcpkg team,

I am currently using vcpkg to manage dependencies for my project, and I must say it is an incredibly useful tool that has greatly enhanced my productivity. However, I have encountered an issue with compiler compatibility that I hope you can assist me with.

Issue Description:

My project requires compilation with the Clang compiler due to bugs I have encountered with MSVC, which prevent successful compilation. When I switch to using Clang, the compilation proceeds without issues. This has led me to conclude that the bugs are indeed with MSVC.

The problem arises when I attempt to link my project. Since my project is compiled with Clang, and the libraries installed via vcpkg are compiled with MSVC by default, I am experiencing ABI incompatibility issues.

My question is: Is there a way to configure vcpkg to use the Clang compiler for building libraries? This would ensure that both my project and the dependencies are compiled with the same compiler, thus avoiding ABI compatibility issues.

If this is not currently a supported feature, I would like to suggest considering adding support for the Clang compiler. This would make vcpkg more versatile and accommodating to a wider range of project requirements.

Thank you very much for your time and assistance!

Feel free to modify and expand on this draft based on your specific situation. Good luck with your issue!

**Comment by diehard2** [comment]
Not part of the vcpkg team, but saw your question. You need to create a toolchain file and triplet that point to clang. You can look at the community ones as a template. I'm successfully using it for clang currently although its officially (as far as I can tell) even less supported than the community triplets, so YMMV with how successful you are. You're going to need to manually set CXX and CC in there for clang also, or some packages will fail during configuration.

**Comment by Neumann-A** [comment]
See: https://github.com/Neumann-A/my-vcpkg-triplets/blob/master/x64-win-llvm.cmake for an example how to use clang-cl. You can probably adjust use clang instead.

**Comment by felixf4xu** [comment]
I would like to share what I have done.

- Mare sure clang-cl.exe is installed.
in my case, it's at `C:\Program Files\LLVM\bin\clang-cl.exe`

- Download the overlay-triplets as motioned above, 
in my case, to `D:\github\my-vcpkg-triplets-master`

- Use the triplets
```sh
D:\github\vcpkg> .\vcpkg.exe install libiconv --overlay-triplets=D:\github\my-vcpkg-triplets-master --triplet=x64-win-llvm
```

**Comment by Neumann-A** [comment]
`.\vcpkg.exe install libiconv --overlay-triplets=D:\github\my-vcpkg-triplets-master --triplet=x64-win-llvm`

better use

`.\vcpkg.exe install libiconv --overlay-triplets=D:\github\my-vcpkg-triplets-master --host-triplet=x64-win-llvm`

**Comment by diehard2** [comment]
For the llvm toolchain I've found I needed to add

set(ENV{CC} "/usr/bin/clang")
set(ENV{CXX} "/usr/bin/clang++")

since there's a subset of ports that depend on those environmental variables to build. Depending on how clang was installed, I've also had to manually set the linker in toolchains. 

set(CMAKE_LINKER "/opt/rh/gcc-toolset-13/root/usr/bin/g++")
set(CMAKE_C_COMPILER_LINKER "/opt/rh/gcc-toolset-13/root/usr/bin/ld")
set(CMAKE_CXX_LINK_EXECUTABLE "<CMAKE_LINKER>  <FLAGS> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")

This is needed if you're on a redhat based system (centos/rocky/alma/rhel) and you're using a toolkit. Clang will use the highest level toolkit you have for everything except the linker. That defaults to /usr/bin/ld and you can get binutils version conflicts.

**Comment by dg0yt** [comment]
> set(ENV{CC} "/usr/bin/clang") set(ENV{CXX} "/usr/bin/clang++")
> 
> on Linux, since there's a subset of ports that depend on those environmental variables to build.

You should name these ports, to get them fixed. 
While CC and CXX are expected to (usually) have effect on CMake (i.e. *input*), non-CMake build systems are expected to follow the *result* of CMake toolchain configuration (i.e. *output*). With vcpkg and CMake there can be a custom chainloaded toolchain file which sets `CMAKE_<LANG>_COMPILER` directly, Then CC and CXX must be overridden before running other build systems.

**Comment by MonicaLiu0311** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by onecable5781** [comment]
> `.\vcpkg.exe install libiconv --overlay-triplets=D:\github\my-vcpkg-triplets-master --triplet=x64-win-llvm`
> 
> better use
> 
> `.\vcpkg.exe install libiconv --overlay-triplets=D:\github\my-vcpkg-triplets-master --host-triplet=x64-win-llvm`

Hello @Neumann-A 

I tried the following: 

`PS C:\vcpkg> .\vcpkg.exe install mlpack --overlay-triplets=C:\my-vcpkg-triplets --host-triplet=x64-win-llvm`

so as to get mlpack library built using clang-cl.exe

This runs okay for a while but I end up with the following error:

-- Building x64-win-llvm-dbg
-- Building x64-win-llvm-rel
-- Fixing pkgconfig file: C:/vcpkg/packages/openblas_x64-win-llvm/lib/pkgconfig/openblas.pc
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.3.0-1-any.pkg.tar.zst
-- Using cached msys2-msys2-runtime-3.5.4-2-x86_64.pkg.tar.zst
-- Using msys root at C:/vcpkg/downloads/tools/msys2/21caed2f81ec917b
-- Fixing pkgconfig file: C:/vcpkg/packages/openblas_x64-win-llvm/debug/lib/pkgconfig/openblas.pc
-- Installing: C:/vcpkg/packages/openblas_x64-win-llvm/share/openblas/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 546 ms.
Elapsed time to handle openblas:x64-win-llvm: 3.7 min
openblas:x64-win-llvm package ABI: 3a8d758d151360df5a74f77f9379af7b385a65c7a9c9db54158c4b995834cee6
Installing 4/12 blas:x64-win-llvm@2023-04-14#2...
Building blas:x64-win-llvm@2023-04-14#2...
C:\my-vcpkg-triplets\x64-win-llvm.cmake: info: loaded overlay triplet from here
-- Skipping post-build validation due to VCPKG_POLICY_EMPTY_PACKAGE
Stored binaries in 1 destinations in 32.9 ms.
Elapsed time to handle blas:x64-win-llvm: 88 ms
blas:x64-win-llvm package ABI: 5945cc37502756ad3b8e835e14639c2906e62b1b201e7f2afccebc0546ab2624
Installing 5/12 vcpkg-gfortran:x64-win-llvm@3#3...
Building vcpkg-gfortran:x64-win-llvm@3#3...
C:\my-vcpkg-triplets\x64-win-llvm.cmake: info: loaded overlay triplet from here
-- The Fortran compiler identification is unknown
-- Skipping post-build validation due to VCPKG_POLICY_EMPTY_PACKAGE
Stored binaries in 1 destinations in 30.1 ms.
Elapsed time to handle vcpkg-gfortran:x64-win-llvm: 164 ms
vcpkg-gfortran:x64-win-llvm package ABI: 5d6284d3ddf727a2928cdc8791d61920987af2a719f133224aa5d813f63d9d6a
Installing 6/12 lapack-reference[blas-select,core,noblas]:x64-win-llvm@3.11.0#6...
Building lapack-reference[blas-select,core,noblas]:x64-win-llvm@3.11.0#6...
C:\my-vcpkg-triplets\x64-win-llvm.cmake: info: loaded overlay triplet from here
-- Using cached Reference-LAPACK-lapack-v3.11.0.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/lapack-reference/src/v3.11.0-6ae738f586.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/Reference-LAPACK-lapack-v3.11.0.tar.gz
-- Applying patch cmake-config.patch
-- Applying patch lapacke.patch
-- Applying patch fix_prefix.patch
-- Using source at C:/vcpkg/buildtrees/lapack-reference/src/v3.11.0-6ae738f586.clean
-- The Fortran compiler identification is unknown
-- Found external ninja('1.12.1').
-- Configuring x64-win-llvm
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/vcpkg/buildtrees/lapack-reference/x64-win-llvm-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\lapack-reference\config-x64-win-llvm-dbg-CMakeCache.txt.log
      C:\vcpkg\buildtrees\lapack-reference\config-x64-win-llvm-rel-CMakeCache.txt.log
      C:\vcpkg\buildtrees\lapack-reference\config-x64-win-llvm-dbg-CMakeConfigureLog.yaml.log
      C:\vcpkg\buildtrees\lapack-reference\config-x64-win-llvm-rel-CMakeConfigureLog.yaml.log
      C:\vcpkg\buildtrees\lapack-reference\config-x64-win-llvm-out.log

Call Stack (most recent call first):
  installed/x64-win-llvm/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:269 (vcpkg_execute_required_process)
  ports/lapack-reference/portfile.cmake:59 (vcpkg_cmake_configure)
  scripts/ports.cmake:196 (include)


error: building lapack-reference:x64-win-llvm failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle lapack-reference:x64-win-llvm: 3.9 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+lapack-reference
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[lapack-reference]+Build+error+on+x64-win-llvm&body=Copy%20issue%20body%20from%20C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

Any help to fix this is appreciated.

Thank you.

**Comment by Neumann-A** [comment]
You need to setup a Fortran compiler for lapack or disable the setting of VCPKG_CHAINLOAD_TOOLCHAIN file in the triplet for the lapack-reference port. I have an overlay which uses intel-mkl instead of lapack-reference which is why I don't run into that issue.

**Comment by onecable5781** [comment]
> You need to setup a Fortran compiler for lapack or disable the setting of VCPKG_CHAINLOAD_TOOLCHAIN file in the triplet for the lapack-reference port. I have an overlay which uses intel-mkl instead of lapack-reference which is why I don't run into that issue.

Thank you for the response. I have IntelOneAPI installed as a result of which I do have Intel's fortran compiler at C:\Program Files (x86)\Intel\oneAPI\compiler\2025.0\bin\ifx.exe

Should I indicate this path somewhere in the vcpkg triplet to move ahead of the error?

**Comment by Neumann-A** [comment]
> Thank you for the response. I have IntelOneAPI installed as a result of which I do have Intel's fortran compiler at C:\Program Files (x86)\Intel\oneAPI\compiler\2025.0\bin\ifx.exe
Should I indicate this path somewhere in the vcpkg triplet to move ahead of the error?

I mean it is up to you what you want. If you want to compile lapack-reference with ifx you need to tell vcpkg that somehow which means using an env passthrough for OneAPI_ROOT variable or similar and setup the toolchain to use that as the fortran compiler. You'll probably also need to setup some compiler flags for that to work correctly. (since intel name mangling on windows still assume UPPERCASE symbols with no _ prefix while the whole rest of the world only tests for _lowercase)
