### ISSUE TITLE
error when installing vtk with mpi and hdf5 with parallel.

### ISSUE THREAD

**Issue by KasterMist** [microsoft/vcpkg#38060]
Recently I used vcpkg and cmake to install vtk with mpi and hdf5 with parallel but found error below:

"CMake Error at CMake/vtkModule.cmake:1038 (message):
  The VTK::IOParallelNetCDF module (enabled via a `YES` setting (via
  `VTK_GROUP_ENABLE_MPI`)) requires the disabled module VTK::IONetCDF
  (disabled via a `NO` setting (via `VTK_MDDULE_ENABLE_VTK_IONetCDF`)).
Call Stack (most recent call first):
  CMakeLists.txt:364 (vtk_module_scan)"

Below is the screenshot I changed in vcpkg.json.
![20240409-152210](https://github.com/microsoft/vcpkg/assets/43816414/ed8f2142-956b-485e-b179-628a20f363cc)

I also noticed that the error mentioned is "VTK_MDDULE_ENABLE_VTK_IONetCDF" instead of "VTK_MODULE_ENABLE_VTK_IONetCDF". Is this the problem?
![20240409-152216](https://github.com/microsoft/vcpkg/assets/43816414/93a76095-2d18-42ed-9b8d-d470d364d532)

**Comment by Neumann-A** [comment]
You probably simply need to disable IOParallelNetCDF also? 
VTK just tells you that you disabled a module which is explicitly required by some other VTK module. 

This is not strictly a vcpkg issue since you just need to find the combination of VTK modules you actually want and which are required by the build itself due to inter module dependencies.

**Comment by KasterMist** [comment]
@Neumann-A Thank you. I had to use HDF5 parallel with VTK, so I cannot disable vtk MPI (therefore I cannot disable IOParallelNetCDF then). Still, I understand this is not the vcpkg issue. I will try to find the problem in vtk things.
