### ISSUE TITLE
Where is dylib file? > if vcpkg generates sdl2 into libSDL2-2.0.0.dylib.

### ISSUE THREAD

**Issue by ghost** [microsoft/vcpkg#3823]
Hello everyone, 

I have problem with vcpkg. I have downloaded and let generating dynamic library for macOS.

But it generates only library file.

vcpkg/installed/x64-oss/"bin/libSDL2-2.0.0.dylib" is not seeing to my macOS :(

![image](https://user-images.githubusercontent.com/3496136/42134904-082b85d2-7d44-11e8-86d7-81ff61f0d129.png)

nothing /bin here if I download library example sdl2, curl, opengl, glfw3 into any dylib files...

// EDIT same under Linux too
Why does vcpkg not generate to *.so / *.dso for Linux?

But for Windows has not problem with dll files = OK But for Linux and Mac won't generate to dynamic libraries.
Thanks!

**Comment by JackBoosY** [comment]
Hi @gnu-lorien, thanks for reporting this issue!
By default, vcpkg only provides official static build triplets in `Linux` / `OSX`. If you want to build dynamic libraries, please change `VCPKG_LIBRARY_LINKAGE` in _VCPKG_PATH/triplets/x64-osx.cmake_ to `dynaimc`.

Thanks.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by vignesh-arbadev** [comment]
Yes, it resolved for me.

**Comment by oleksandrlynda** [comment]
@JackBoosY what is the reason that vcpkg builds libraries as static for MacOS by default? And then why it is done in another way for Windows?

**Comment by JackBoosY** [comment]
> @JackBoosY what is the reason that vcpkg builds libraries as static for MacOS by default? And then why it is done in another way for Windows?

I don't know either, maybe related to system libs?
BTW, you can created a triplet and set it to dynamic.

**Comment by dg0yt** [comment]
@oleksandrlynda You jumped on an old issue. Today there are dynamic community triplets for osx coming with vcpkg, so you don't have create new ones. They are not tested in vcpkg CI.

AFAIK static triplets for non-windows platforms were chosen as default due to concerns about dealing with runtime paths. The concerns should be resolved for linux/ELF, but not yet for osx.

For more new questions, better use https://github.com/microsoft/vcpkg/discussions than old issues.
