### ISSUE TITLE
Shared Object support on Linux

### ISSUE THREAD

**Issue by pakdel** [microsoft/vcpkg#3841]
@ras0219-msft I was listening to CppCasts and my understanding about including DLLs in Windows packages is that Vcpkg includes them in the same directory as the executable.
Can the same thing be done for Linux ELF binaries with `runpath` set to `$ORIGIN`?
If the package is simply extracted to a directory, the executable will have its dependencies in the same directory and the linker will find them. If it has an installer that puts the binary under a directory like `/usr/bin`, the same installer will put libraries under a directory like `/usr/lib` and the linker will still find them.

**Comment by arthur-tacca** [comment]
> If the package is simply extracted to a directory, the executable will have its dependencies in the same directory and the linker will find them. 

Are you sure that's true? I don't think that the runtime linker on Linux looks in the executable's directory e.g. see [this q/a on StackOverflow](https://serverfault.com/questions/279068/cant-find-so-in-the-same-directory-as-the-executable)

> If it has an installer that puts the binary under a directory like /usr/bin, the same installer will put libraries under a directory like /usr/lib

Wouldn't this be bad? Then the vcpkg version of a dependent library (which is probably very new) will clash with the one supplied by the OS package manager (which is probably a bit older). Even just two different applications built with vcpkg will probably have different versions of libraries. 

It seems to me that if you supply your own libraries, rather than using the OS package manager, then you would have to put all the libraries for the executable in a separate directory (like Windows does in a subdirectory of Program Files). As I just pointed out above, this wouldn't work on Linux (at least not without tweaking the system environment).

**Comment by pakdel** [comment]
To demonstrate what I mean, I downloaded SuperTuxKart
https://supertuxkart.net/Download


the DEB package for stable version of Google Chrome and extracted its files into a tar file, but did not install its dependencies:
```
~ $ cd ~/tmp/
~/tmp $ tar xf ~/Downloads/supertuxkart-0.9.3-linux.tar.xz
~/tmp $ cd supertuxkart-0.9.3-linux
~/tmp/supertuxkart-0.9.3-linux $ ldd bin-64/supertuxkart | fgrep png
        libpng12.so.0 => not found
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007fef1b339000)
```
If I install the dependency, it will become:
```
~/tmp/supertuxkart-0.9.3-linux $ ldd bin-64/supertuxkart | fgrep png
        libpng12.so.0 => /usr/lib/libpng12.so.0 (0x00007f9f3b2c1000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f9f37f75000)
```
And If I want to put it in the same directory as the binary:
```
~/tmp/supertuxkart-0.9.3-linux $ ls bin-64/libpng12.so*
bin-64/libpng12.so  bin-64/libpng12.so.0  bin-64/libpng12.so.0.59.0
~/tmp/supertuxkart-0.9.3-linux $ patchelf --set-rpath '$ORIGIN' bin-64/supertuxkart
~/tmp/supertuxkart-0.9.3-linux $ ldd bin-64/supertuxkart | fgrep png
        libpng12.so.0 => .../tmp/supertuxkart-0.9.3-linux/bin-64/libpng12.so.0 (0x00007f8fbeefc000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f8fbbbb0000)
```

**Comment by pakdel** [comment]
There has not been any interest in improving Linux support!
I strongly believe that there is not a big community, or at least it is not widely used on Linux.

**Comment by JackBoosY** [comment]
Please track issue https://github.com/microsoft/vcpkg/issues/15006.
