### ISSUE TITLE
Add LMDB

### ISSUE THREAD

**Issue by willyd** [Microsoft/vcpkg#385]
Webiste: https://symas.com/products/lightning-memory-mapped-database/

Github: https://github.com/LMDB/lmdb

A CMake build for windows (cmake branch): https://github.com/willyd/lmdb/tree/cmake

Required for #294

**Comment by willyd** [comment]
I just added a shared library build of LMDB and configurable install locations for headers, libs, dlls and cmake configuration files to the above LMDB fork. 

@ras0219-msft my fork is based on LMDB master since it needs commits https://github.com/LMDB/lmdb/commit/fb5a768a77ca5330e15a3a34ceb694bc11cb216a and https://github.com/LMDB/lmdb/commit/29ebd02efd72fa0b558b6d87fc32afc1061f97ff which are in none of the releases. Otherwise LMDB cannot be used on Windows at least within caffe. 

How should I got about this if I want to submit a port? 

Can I make an alpha release on my LMDB repository and use that? What would be the version string in the CONTROL file for an alpha version?

**Comment by ras0219-msft** [comment]
Ideally, you would author the needed changes as a small patch on top of some revision of the _upstream_ sources and apply it using `vcpkg_apply_patches()`. Also, GitHub provides zip archives of every commit[1], so there's no need to make a release.

Since it looks like LMDB is pretty stable (only 15ish commits this year since the release), the best approach is probably to just use "0.9.18-1" as the version because the chance of regression is pretty low. Alternatively, you could use the last release and "cherry pick" the relevant commits by downloading them as patch files[2], then applying them as above.

It's best to depend only on the upstream public repo if possible, because it makes things more "intuitively trustable". As a user, I simply need to (a) trust the upstream sources and (b) look at any patches. If the portfile is downloading code from a fork, it adds a indirection that makes things much more troublesome to audit.

[1] For example: https://github.com/LMDB/lmdb/archive/fb5a768a77ca5330e15a3a34ceb694bc11cb216a.zip
[2] For example: https://github.com/LMDB/lmdb/commit/fb5a768a77ca5330e15a3a34ceb694bc11cb216a.diff

**Comment by willyd** [comment]
> Ideally, you would author the needed changes as a small patch on top of some revision of the upstream sources and apply it using vcpkg_apply_patches().

This is what I tought.

> Also, GitHub provides zip archives of every commit[1], so there's no need to make a release.

> It's best to depend only on the upstream public repo if possible, because it makes things more "intuitively trustable". As a user, I simply need to (a) trust the upstream sources and (b) look at any patches. If the portfile is downloading code from a fork, it adds a indirection that makes things much more troublesome to audit.

Makes sense. I was suggesting making a release since even if it is bad practice anyone can rewrite the history of a github repository so if we linked to a particular commit archive it could just disappear at some point. However, this seems very unlikely.

Ok I am going to try either depending on the 0.9.18 release and applying patches or on the specific revision if that turns out to be unsuccesful. 

Thanks for you feedback.

**Comment by willyd** [comment]
I started to work on this but I am not finished yet. See this branch: https://github.com/willyd/vcpkg/tree/lmdb

I will submit a PR when ready.
