### ISSUE TITLE
Could Vcpkg manage find<package>.cmake  files?

### ISSUE THREAD

**Issue by philjdf** [microsoft/vcpkg#3875]
If a package X produced a findX.cmake file, and Vcpkg installed it somewhere standard for other packages to find, this would make relationships between packages and dependencies higher level than the package looking for .lib files with a CMake find_* command, and more maintainable than packages supplying their own findX.cmake files.

Or does Vcpkg already do this and I'm missing something?

**Comment by traversaro** [comment]
I am not sure if I fully understand your point, but typically CMake-based projects produce `<package>-config.cmake` or `<package>Config.cmake` files to make sure that downstream packages are able to find them using the `find_package` command without writing any custom `find<package>.cmake` script. See https://cmake.org/cmake/help/v3.10/manual/cmake-packages.7.html for the relevant upstream CMake docs

In `vcpkg`, these files are already installed in `<prefix>/share/<package>` . See https://github.com/Microsoft/vcpkg/issues/77 for an old but related vcpkg issue. 

In a related note, there are some vcpkg ports that actually just install CMake moules including `Find<package>.cmake` scripts for several projects that do not provide native cmake support. To see an example of such a port, check the `ecm` port in https://github.com/Microsoft/vcpkg/tree/master/ports/ecm (it is the port for https://github.com/KDE/extra-cmake-modules).

**Comment by philjdf** [comment]
Thank you for your reply. Perhaps my [PR](https://github.com/Microsoft/vcpkg/pull/3839) can be simplified then!

**Comment by edmBernard** [comment]
@traversaro If vcpkg manage automaticaly `<package>-config.cmake`, I have an issu with `cpr` library. It is build with cmake, but we are not able to find it with `find_package(cpr REQUIRED)`

**Comment by arthur-tacca** [comment]
@edmBernard: That is a bug in the cpr library. The [CMakeLists.txt of cpr](https://github.com/whoshuu/cpr/blob/master/CMakeLists.txt) lack the commands to generate the information used by `find_package`. The [CMake packaging docs](https://cmake.org/cmake/help/v3.10/manual/cmake-packages.7.html), which traversaro linked to above, describe what they would need to do (although some if it, like the version stuff, is not strictly necessary for `find_package()` to work).

In fact the CMakeLists.txt of that library doesn't even contain to install the library itself with CMake, but the vcpkg port [manually added the necessary extra stuff](https://github.com/Microsoft/vcpkg/blob/master/ports/cpr/enable-install.patch) to workaround this problem. So you could either file a bug report over at the upstream cpr repo asking them to fix their CMake installation (that would be the ideal solution), or file a bug/pull request here on the vcpkg repo to workaround that bit of installation too. Someone already did [submit a pull request for the vcpkg workaround](https://github.com/Microsoft/vcpkg/pull/3185) but it hasn't been updated since getting feedback from the vcpkg devs in April. You might wish to follow or update that.

**Comment by edmBernard** [comment]
@arthur-tacca Thanks for these precisions. Indeed that was not clear. I will see what can I do.

**Comment by PhoebeHui** [comment]
@traversaro, @arthur-tacca, thanks for your replying!

@edmBernard, you can find cpr via find_package now. I tried, it find correctly.
See commit https://github.com/microsoft/vcpkg/commit/442d5c1b543d94b1902a17da597891104bab170e#diff-9cbf7ab4ebde412005bc6040f8392cd2
