### ISSUE TITLE
Add docopt.cpp

### ISSUE THREAD

**Issue by studoot** [Microsoft/vcpkg#3935]
[docopt.cpp](https://github.com/docopt/docopt.cpp) is a very nice command-line parsing library, which would make a nice addition to vcpkg's list of ports. It's already cmake based, so would probably be quite easy to integrate.

**Comment by myd7349** [comment]
Related issue: [docopt.cpp 97](https://github.com/docopt/docopt.cpp/issues/97).

**Comment by myd7349** [comment]
I made a port for `docopt.cpp`:
[prs/docopt](https://github.com/myd7349/vcpkg/commits/prs/docopt)

Finally I decided to use `docopt` as the package name.  (Currently `docopt.c` is still a single header only library. So when we need a new port for `docopt.c` one day, we may use `docopt-c`.).

@alexkaratarakis @ras0219-msft I am not sure if it is a good idea.

Besides, there are still two problems:

1. Currently, this port will build a static library and a dynamic library, and install them both. I don't know how to handle this yet. 

2. In a Visual Studio project, you need to include `<docopt/docopt.h>`. In a CMake project, you should include `<docopt.h>` since the installed CMake targets has added `%VCPKG_ROOT%\include\docopt` into include directories.
