### ISSUE TITLE
Repeal the 'unofficial-' prefix

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/vcpkg#40240]
We are considering repealing the 'unofficial' prefix as documented at https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#add-cmake-exports-in-an-unofficial--namespace

The original intent remains the same: we don't want to create 'vcpkg lock in' and expose things the same way things would be exposed from the system. However, since creating this policy, we have observed several upstreams adopt CMake bindings we authored for them wholesale, or ones substantially similar to ones we author. Once this happens, it creates its own kind of lock-in, as all customers who wrote the 'unofficial-' name effectively only work with vcpkg, creating the exact situation we were trying to avoid.

As a result, we are strongly considering removing this rule from the maintainer guide and replacing it with a general one saying, more or less, don't try to create lock-in and author CMake bindings and targets such that they would be adoptable upstream in outside-of-vcpkg-contexts if that upstream would so choose.

However, this is a major change in policy so we want contributors' opinion before proceeding. What are folks thoughts?

https://github.com/microsoft/vcpkg-docs/pull/376

**Comment by Osyotr** [comment]
I like the idea because
> all customers who wrote the 'unofficial-' name effectively only work with vcpkg.

**Comment by talregev** [comment]
I have a questions:

>  don't try to create lock-in and author CMake bindings and targets such that they would be adoptable upstream in outside-of-vcpkg-contexts if that upstream would so choose

This mean they will write targets in general way? 
vcpkg will must wait for upstream approval? 
Can we write in general way and suggest it to upstream without a must to wait for them?

This is effects only targets as I understand. All other patch that we do for upstream in vcpkg will remain the same.

**Comment by BillyONeal** [comment]
> This mean they will write targets in general way?

If it's possible to make bindings that work both inside and outside of vcpkg, that's preferred, yes.

> vcpkg will must wait for upstream approval?

No. We are usually worried about making sure we don't 'speak for' upstream but we consider build system bindings and behavior kind of our table.

> Can we write in general way and suggest it to upstream without a must to wait for them?

Of course it's always nice to give upstream an FYI but for adding build system bindings where they do not exist in the same places we would add unofficial ones, we would add ones without the unofficial prefix.

> This is effects only targets as I understand. All other patch that we do for upstream in vcpkg will remain the same.

Yes. Basically, the farther away you get from build system specific edits the more we are going to want to see upstream in the loop.

**Comment by dg0yt** [comment]
> > This is effects only targets as I understand. All other patch that we do for upstream in vcpkg will remain the same.
> 
> Yes. Basically, the farther away you get from build system specific edits the more we are going to want to see upstream in the loop.

In addition to targets (`unofficial::<PORT>::`), this also affects package names (`unofficial-<PORT>`). Which is a major element in dependency resolution.

> We are considering repealing the 'unofficial' prefix 

I'm mildly against.

Basically, it is much worse to have *hidden* lock-in than to have *obvious* lock-in.
"unofficial" is a strong marker.

Considerations:

- Most significantly, the vendored config packages are no longer easy to identify. 
  This will become a source of trouble when upstreaming CMake config patches for reverse dependencies. Regardless of being pushed from vcpkg or pulled by the projects.
  As an extra complication, this is mostly an issue for static library linkage which is less popular in the POSIX-focused open-source world.
- vcpkg strictly installs either static or shared libs. A uniform target name is desired and feasible.
  In contrast, some projects prefer to install static and shared libs side by side. They can't use the same name.
  Mitigation: Provide the uniform name as an ALIAS or INTERFACE based on @BUILD_SHARED_LIBS@.
- Many contributors (and many upstreams) have difficulties in arriving at good choices both for package names and target names.
  In particular, the value of namespaces and of qualifying as a drop-in replacement for official Find modules isn't understood.
- vcpkg is biased to choose port names based on repo names. There is a significant number of ports where the package names or target names chosen by upstream does differ from the port name, e.g. by CapiTalization or `lib` prefixes.
- It is fairly easy to move from unofficial to official names once upstream offers them.
  It is fairly easy to provide polyfill in the ports.

**Comment by talregev** [comment]
> > This mean they will write targets in general way?
> 
> If it's possible to make bindings that work both inside and outside of vcpkg, that's preferred, yes.
> 
> > vcpkg will must wait for upstream approval?
> 
> No. We are usually worried about making sure we don't 'speak for' upstream but we consider build system bindings and behavior kind of our table.
> 
> > Can we write in general way and suggest it to upstream without a must to wait for them?
> 
> Of course it's always nice to give upstream an FYI but for adding build system bindings where they do not exist in the same places we would add unofficial ones, we would add ones without the unofficial prefix.
> 
> > This is effects only targets as I understand. All other patch that we do for upstream in vcpkg will remain the same.
> 
> Yes. Basically, the farther away you get from build system specific edits the more we are going to want to see upstream in the loop.

I am vote in favor to that good change and remove unofficial and try to create changes that works inside and outside vcpkg.

**Comment by talregev** [comment]
What about all the ports that have unofficial targets?

**Comment by dg0yt** [comment]
> to create changes that works inside and outside vcpkg

... they must be applied outside vcpkg. 

That's my point: With "unofficial", I can tell that I cannot expect them to work outside. Without "unofficial", it will be try-and-error.

**Comment by Neumann-A** [comment]
> Once this happens, it creates its own kind of lock-in, as all customers who wrote the 'unofficial-' name effectively only work with vcpkg, creating the exact situation we were trying to avoid.

What is the problem here? If the lock in is a conscious decision it is ok. It is not your problem at that point any more. 

What, however, will become your problem if you provide targets with conflicting names/namespaces. You don't now what is out in the wild and if any targets conflict with an already existing one it becomes a problem for you and the user. As such having some kind of vcpkg specific prefix is mandatory to avoid conflicts

The whole argument also feels survivorship biased. Have you looked at what conan and spack users do? E.g. you can take a look at something like https://docs.conan.io/2/reference/tools/cmake/cmakedeps.html#conan-tools-cmakedeps however wasn't one of the complains of conan the prefixed targets provided by conan?

I wouldn't mind if vcpkg would have an extra port similar to https://github.com/KDE/extra-cmake-modules providing the additional stuff and people make a conscious decision to lock in on vcpkg has a dep tool. 

However, I also think that there is more important stuff like fixing FindPkgConfig for multi config. Nearly everything has pc files, so why not fix that?

**Comment by ADKaster** [comment]
From a user perspective, the use of the unofficial- prefixed CMake packages creates confusion for developers, distro maintainers, and hobbyists who want to maintain a 'pure system lib' build of a project that uses vcpkg for developer convenience. Especially if their distribution does not ship the dependency at all. Which leads us to consider providing a separate build script for those developers if they don't want to pull in an entire vcpkg build tree, and supply the system deps themselves...

I'm not sure if using vcpkg only for developer convenience rather than a library/application distribution strategy is the expected use case of vcpkg, but that's how we're using it. That is, run our script that builds a vcpkg install root for you instead of installing 20+ more system dependencies that may differ versions between distros. (And instead of using a docker container for most development, yuck).

As one example, the nixpkgs maintainer for our application opened a PR to specifically look for a dependency (skia) via a pkgconfig setup that they are maintaining themselves. <https://github.com/LadybirdBrowser/ladybird/pull/382/files>

It's possible that our interaction with the unofficial- package here is expected for skia though, as the upstream for skia seems to expect you to pull them in as a vendored package via gn or bazel files, rather than CMake :man_shrugging: .

**Comment by dg0yt** [comment]
> * Most significantly, the vendored config packages are no longer easy to identify.
>   This will become a source of trouble when upstreaming CMake config patches for reverse dependencies. Regardless of being pushed from vcpkg or pulled by the projects.

Example: In #40249, I patch `mongo-c-driver` to using `unofficial-utf8proc`. With the prefix, me and reviewers immediately know that this patch cannot be upstreamed.

**Comment by cenit** [comment]
thanks for adding me to the discussion.
In the past i'd have said forget the unofficial prefix and that's it (i wrote many CMakeLists.txt here and even modules originally [ffmpeg] that created target without any unofficial prefix). But others pointed out good arguments against it. I'd take the chance to discuss the topic on even a broader scale. For example, if not upstream-able for any reason, why not creating a cmake module and make it work also outside vcpkg environment, for better usage everywhere? just throwing random ideas to say that if we revisit this decision, let's consider it on the broadest perspective

**Comment by dg0yt** [comment]
> But others pointed out good arguments against it.

Against using the prefix or against repealing the prefix?
(I fail to see strong arguments against using a prefix.)

> why not creating a cmake module and make it work also outside vcpkg environment, for better usage everywhere?

- cmake module (i.e not config): No. 
  Reason: Config mored provides the more powerful search procedure. This is strongly desired.
- work also outside vcpkg environment: No.
  Reason: Exported unofficial config is most useful due to encoding build-time configuration (dependencies, binary names, multi-config installation layout). 

A find modules which chainloads suitable configs via 
~~~
find_package(skia NAMES unofficial-skia nix-skia conan-skai system-skia)
~~~
might be a different story.

**Comment by cenit** [comment]
> > But others pointed out good arguments against it.
> 
> Against using the prefix or against repealing the prefix? (I fail to see strong arguments against using a prefix.)
> 

against repealing the prefix. Sorry for the bad wording, the "but" at the beginning of the phrase was supposed to write something contrary to the previous phrase (that was against using the prefix).

> > why not creating a cmake module and make it work also outside vcpkg environment, for better usage everywhere?
> 
> * cmake module (i.e not config): No.
>   Reason: Config mored provides the more powerful search procedure. This is strongly desired.
> * work also outside vcpkg environment: No.
>   Reason: Exported unofficial config is most useful due to encoding build-time configuration (dependencies, binary names, multi-config installation layout).
> 
> A find modules which chainloads suitable configs via
> 
> ```
> find_package(skia NAMES unofficial-skia nix-skia conan-skai system-skia)
> ```
> 
> might be a different story.

I know pros and cons of modules and configs. But instead of having a config that works only inside vcpkg because for whatever the reason it is not upstream-able, I think that a good designed module, that takes into consideration the possibility of offloading library search to config if available (because it detects vcpkg-custom-built libraries that export unofficial targets) and at the same time works also in case the library is provided in other ways, gives more value and might reach the same goals that @BillyONeal and the vcpkg team are targeting

**Comment by xiaozhuai** [comment]
> We are considering repealing the 'unofficial' prefix

I'm against. This actually hides the problem but not solve it.
Maybe changing the `unofficial` prefix to `vcpkg` prefix is what we need.
I'm curious why `vcpkg` was not chosen as the prefix.
I agree with most of @dg0yt 's points

**Comment by BillyONeal** [comment]
OK, we are convinced by @dg0yt and will not make this policy change. We should probably adopt a similar 'unofficial' policy for `.pc` files Soon :TM:
