### ISSUE TITLE
[boost-cobalt] Build error on x64-windows-static

### ISSUE THREAD

**Issue by pavel-cpp** [microsoft/vcpkg#40310]
Package: boost-cobalt:x64-windows-static@1.85.0#2

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.29.30154.0
-    vcpkg-tool version: 2024-08-01-fd884a0d390d12783076341bd43d77c3a6a15658
    vcpkg-scripts version: a2367ceec 2024-08-06 (6 hours ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Using cached boostorg-cobalt-boost-1.85.0.tar.gz.
-- Cleaning sources at D:/lib/vcpkg/buildtrees/boost-cobalt/src/ost-1.85.0-74ba267639.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/lib/vcpkg/downloads/boostorg-cobalt-boost-1.85.0.tar.gz
-- Using source at D:/lib/vcpkg/buildtrees/boost-cobalt/src/ost-1.85.0-74ba267639.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: D:/lib/vcpkg/buildtrees/boost-cobalt/x64-windows-static-dbg
    See logs for more information:
      D:\lib\vcpkg\buildtrees\boost-cobalt\install-x64-windows-static-dbg-out.log
      D:\lib\vcpkg\buildtrees\boost-cobalt\install-x64-windows-static-dbg-err.log

Call Stack (most recent call first):
  S:/Sophus/bin/.build/cmake/Release/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  S:/Sophus/bin/.build/cmake/Release/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  S:/Sophus/bin/.build/cmake/Release/vcpkg_installed/x64-windows/share/vcpkg-boost/boost-install.cmake:65 (vcpkg_cmake_install)
  buildtrees/versioning_/versions/boost-cobalt/2c39cef923bb54a5c8230dea5b7d72586f4d67ec/portfile.cmake:12 (boost_configure_and_install)
  scripts/ports.cmake:192 (include)



```

<details><summary>D:\lib\vcpkg\buildtrees\boost-cobalt\install-x64-windows-static-dbg-err.log</summary>

```
ninja: error: unknown target 'install'
```
</details>

<details><summary>D:\lib\vcpkg\buildtrees\boost-cobalt\install-x64-windows-static-dbg-out.log</summary>

```
Change Dir: 'D:/lib/vcpkg/buildtrees/boost-cobalt/x64-windows-static-dbg'

Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v -v -j9 install
```
</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "builtin-baseline": "a2367ceec5f092d8777606ca110426cadd7ed7db",
  "dependencies": [
    {
      "name": "grpc",
      "features": [
        "codegen"
      ]
    },
    "protobuf",
    "boost"
  ],
  "overrides": [
    {
      "name": "grpc",
      "version": "1.60.0"
    },
    {
      "name": "protobuf",
      "version": "4.25.1"
    },
    {
      "name": "boost",
      "version": "1.84.0"
    }
  ]
}

```
</details>

**Comment by greenozon** [comment]
@pavel-cpp looks like your compiler toolchain does not me the libarary prerequisites:

>This library is supported since Clang 14, Gcc 10 & MSVC 19.30 (Visual Studio 2022).

```
if(MSVC_VERSION AND MSVC_VERSION LESS 1930)
    message(STATUS "Boost.Cobalt: not building, the lowest supported MSVC version is 1930.  ${MSVC_VERSION} is not supported")
    return()
endif()

```

**Comment by dg0yt** [comment]
Similar: https://github.com/microsoft/vcpkg/issues/40290#issuecomment-2269639431

**Comment by pavel-cpp** [comment]
> @pavel-cpp looks like your compiler toolchain does not met the libarary prerequisites:
> 
> > This library is supported since Clang 14, Gcc 10 & MSVC 19.30 (Visual Studio 2022).
> 
> ```
> if(MSVC_VERSION AND MSVC_VERSION LESS 1930)
>     message(STATUS "Boost.Cobalt: not building, the lowest supported MSVC version is 1930.  ${MSVC_VERSION} is not supported")
>     return()
> endif()
> ```

I'm trying to build boost 1.84.0 which is compatible with my compiler, why does this package pull the boost 1.85.0 libraries?

**Comment by greenozon** [comment]
1.85 is the version specified in the boost port json file
c:\Dev\vcpkg\ports\boost\vcpkg.json 

BTW, I don't know if it's possible to use vcpkg and ask for older versions?...

**Comment by dg0yt** [comment]
> I'm trying to build boost 1.84.0 which is compatible with my compiler, why does this package pull the boost 1.85.0 libraries?

@pavel-cpp The `vcpkg.json` overrides the version of the `boost` meta-port. But the failing port is boost-cobalt`. If you don't pin the version of that port, you might get a newer version.

**Comment by dg0yt** [comment]
> I don't know if it's possible to use vcpkg and ask for older versions?

@greenozon Manifest mode allows to control versions. https://learn.microsoft.com/en-us/vcpkg/users/versioning

**Comment by pavel-cpp** [comment]
> > I'm trying to build boost 1.84.0 which is compatible with my compiler, why does this package pull the boost 1.85.0 libraries?
> 
> @pavel-cpp The `vcpkg.json` overrides the version of the `boost` meta-port. But the failing port is `boost-cobalt`. If you don't pin the version of that port, you might get a newer version.

@dg0yt Don't you find it strange that a package of an older version has dependencies on packages of a newer one? So you're suggesting that we go through all the boost dependencies and select compatible versions at random?

**Comment by pavel-cpp** [comment]
How do I specify a specific version of a package and make it take dependencies that are compatible with its version?

**Comment by greenozon** [comment]
@pavel-cpp   you could find more info here
https://learn.microsoft.com/en-us/vcpkg/consume/boost-versions

**Comment by pavel-cpp** [comment]
> @pavel-cpp you could find more info here https://learn.microsoft.com/en-us/vcpkg/consume/boost-versions

@greenozon I don't really understand where I should get the baseline version of boost 1.84.0#1 for each of the packages, in principle, the use of such a hike is not very obvious. As a user, I want to specify the package version and get it, if I want to put a restriction that the library version must be >= I will specify it, but how am I supposed to guess that I need to specify some abstract baseline? Totally not a user friendly approach.

**Comment by pavel-cpp** [comment]
And how do I use these baselines for other packages, because oin is also subject to the fact that in a couple of years I will not be able to download the version I need, because its dependencies will be newer

**Comment by dg0yt** [comment]
It might be difficult to form a neutral answer to a suggestive question. 

> Don't you find it strange that a package of an older version has dependencies on packages of a newer one? 

I would find that strange indeed. Fortunately, it is not the case. `boost` 1.84 depends on `boost-cobalt` 1.84 *or newer*. It is not so strange that new versions can *satisfy* minimum version requirements. AFAICS `boost-cobalt` 1.85 *is compatible* with `boost` 1.84. That's not the problem.  

> So you're suggesting that we go through all the boost dependencies and select compatible versions at random?

No. I suggest you select specific versions where you actually see a problem. So `boost-cobalt` and `boost`. That's just two ports. (I acknowledge that you can't choose 1.84 for `boost-cobalt` without choosing 1.84 for `boost`. That's the downside of the `>=` version constraints in port `boost`.)

The real problem is a combination of `boost-cobalt` 1.85 having higher *compiler requirements* than most ports (maybe higher than `boost-cobalt` 1.84), and of failing to meet the requirement resulting in a poor UX with the vcpkg port because `boost-cobalt` simply decides to silently create no build/install steps instead of reporting a clear error during configuration.

And the question from here is how to improve that UX.

If you don't need `boost-cobalt`, and don't need most other boost ports, it might be better to not install the `boost` meta-port but the individual components which are relevant.

**Comment by pavel-cpp** [comment]
@dg0yt 


Sorry for being too rude in my previous posts.

I think as a vcpkg user I would like to see the following changes:
1. So that the project in manifest mode does not clutter up CMakeCache, but pulls dependencies from buildtrees
2. So that you don't have to use the overrides zone to determine a specific package version
3. So that vcpkg downloads dependencies compatible with my port + we have dependencies that require boost-1.84 modules and maybe the boost 1.84.0 package itself can use dependencies from boost 1.85.0, but our project does not support them and this creates a lot of problems, I would like to work on our project, and not rewrite parts of the project because boost has decided to release an update.

Maybe I'm not very experienced in using vcpkg, if this is the case, you can help with writing the manifest that I attached above and fix the current versions of libraries + add boost 1.84.0

**Comment by dg0yt** [comment]
I'm only a contributor, so don't expect official answers.

> So that the project in manifest mode does not clutter up CMakeCache, but pulls dependencies from buildtrees

I might misunderstand some items, but I guess the answer is No.
IMO "Buildtrees" are cluttered, and only available when dependencies are really being built instead of being installed from artifact cache.  
What manifest mode promises to deliver - an exact solution to the given manifest - can only be done in an installation tree which considers the manifest and the cmake configuration. This is well placed in the CMake binary dir.

> So that you don't have to use the overrides zone to determine a specific package version

`Overrides` is precisely for the case when you really need a specific version of package. You have to declare this in some way.

> ... boost ...

It is not an easy example. `boost` is not "one" package. It is a meta-port which depends on the individual packages, in some cases even subject to platform expressions.  
To pin (nearly) all boost ports to a specific version, the tutorial at https://learn.microsoft.com/en-us/vcpkg/consume/boost-versions#2---use-a-baseline-to-override-boost-packages shows the suggested solution: Using a second registry entry with the desired boost baseline revision together with suitable package name patterns (`boost*`).

**Comment by pavel-cpp** [comment]
@dg0yt Thank you so much for your answer, it's a pleasure to communicate with you. When I first started using vcpkg, I thought it was an analog of pip, only for C++, but apparently this is not so, I think now you understand my expectations from the package manager, I really hope that the UX of vcpkg will one day come closer to pip. While I have found an excellent analog that allows you to specify the exact version of the package and install it without any problems, I will try to use Conan, if it is worse, then I do not know what to do(
