### ISSUE TITLE
Policy on /MP flag

### ISSUE THREAD

**Issue by bjornpiltz** [microsoft/vcpkg#405]
Would you consider passing along the compile flag /MP ([Multi.Processor Compilation](https://msdn.microsoft.com/en-us/library/bb385193.aspx)) to C/C++ projects? It can shorten compile times *a lot*. For CMake projects you just need to append " /MP" to  "CMAKE_C[XX]_FLAGS".

**Comment by bjornpiltz** [comment]
You can also specify max *n* processes with /MP*n*.

**Comment by barcharcraz** [comment]
I thought we already did this. Long term I think people want to switch to using ninja to build if possible.

**Comment by ras0219-msft** [comment]
We throw the MSBuild /m switch which builds projects in parallel, but we don't throw `cl.exe`'s /MP switch which builds files _within_ a project in parallel. An unfortunate situation with MSBuild's C++ support today is that these two switches don't talk to each other: on an `N` processor machine, throwing both will potentially spawn `N^2` processes. On quad core machines, this doesn't regress throughput _too_ badly (it just eats a bunch more RAM), but on higher core servers it can really start to cause problems.

Switching to Ninja for desktop builds solves this issue most soundly because Ninja looks inside each project build and will schedule down to the file level. Therefore, I think it's probably best to channel effort towards that move instead of tweaking combinations of `/MPn` and `/m`.

**Comment by codicodi** [comment]
While we're at compiler flags, wouldn't it be beneficial to use `/GL` switch in release builds?

**Comment by bjornpiltz** [comment]
Is this information about `MSBuild /m ` up to date?  My builds seem to be strictly sequential. Some projects utilize all cores, while some are strictly single threaded. GDAL, for instance, takes 48 minutes to build on a powerful build machine - not counting dependencies. It would speed things up *a lot* to throw in /MP there.

**Comment by claudiofantacci** [comment]
> Is this information about MSBuild /m up to date? My builds seem to be strictly sequential. Some projects utilize all cores, while some are strictly single threaded. GDAL, for instance, takes 48 minutes to build on a powerful build machine - not counting dependencies. It would speed things up a lot to throw in /MP there.

Looking at [this line](https://github.com/Microsoft/vcpkg/blob/30a6668e224dca086ce57ecc6f2fd3c4f4b9a5b0/scripts/cmake/vcpkg_build_msbuild.cmake#L87) it seems that the info is up-to-date.

However, the compilation with VS is still really slow. It took me almost 5 hours to compile OpenCV with QT and CUDA feature (QT and CUDA were already installed).

**Comment by VioletGiraffe** [comment]
Calling `set CL=/MP` in the command line prior to calling `vcpkg install` solves the problem. Now my 8-core CPU has something to do.

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in two year, if it is still an issue, please reopen.
