### ISSUE TITLE
[qt5] Failure in applyng patch set-shared-qmakespec.patch , even if the patch was not previously applied

### ISSUE THREAD

**Issue by traversaro** [Microsoft/vcpkg#411]
On a newly downloaded vcpkg, when I try to install the `qt5` port (I tried for triplets `x86-windows` and `x64-windows`) I always get this error (even if the patch was not previously applied):

~~~
-- Applying patch C:/vcpkg-qt-png/ports/qt5/set-shared-qmakespec.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/vcpkg-qt-png/ports/qt5/set-shared-qmakespec.patch done
~~~

`buildtrees\qt5\patch-x86-windows-0-err.log` file contains:
~~~
Checking patch qtbase/mkspecs/common/msvc-desktop.conf...
error: while searching for:
QMAKE_YACCFLAGS         = -d
QMAKE_CFLAGS            = -nologo -Zc:wchar_t
QMAKE_CFLAGS_WARN_ON    = -W3
QMAKE_CFLAGS_WARN_OFF   = -W0
QMAKE_CFLAGS_RELEASE    = -O2 -MT
QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO += -O2 -MT -Zi
QMAKE_CFLAGS_DEBUG      = -Zi -MTd
QMAKE_CFLAGS_YACC       =
QMAKE_CFLAGS_LTCG       = -GL

error: patch failed: qtbase/mkspecs/common/msvc-desktop.conf:29
error: qtbase/mkspecs/common/msvc-desktop.conf: patch does not apply
~~~

**Comment by ras0219-msft** [comment]
I think that the correct underlying behavior is occurring, although we should manipulate the `msvc-desktop.conf` in a way that doesn't use `vcpkg_apply_patches()`.

The `qt5` port uses patch files to set configuration settings _in the source tree_ at build time based on the triplet. Unfortunately, because of qt5's size, it would probably be very painful to duplicate the source tree for every triplet.

I think the ideal fix here is for `msvc-desktop.conf` to be patched once and have the relevant flags all supplied by the command line, if that's possible. I don't know anything about qmake, nor how qt uses it, but I'll take a look.

**Comment by Barath-Kannan** [comment]
Yeah, this is correct behaviour - it just switches between the static and shared patch depending on which you chose to install. I don't think that there is a nicer solution without a significant amount of work though I haven't really looked at it in detail - perhaps performing a check within the msvc-desktop.conf file to see if a static build flag has been enabled somewhere else so that it can always set the right flags without constant repatching.

Might also be worth considering introducing the concept of "configuration" patches in vcpkg so that it doesn't get marked as an error.

**Comment by traversaro** [comment]
I understood the problem now! Yes, avoiding to output an error message would be definitely easier for users. The simplest and cleanest solution would be to add a parameter to `vcpkg_apply_patches` to conditionally suppress the error message.
