### ISSUE TITLE
Creating package from non-CMake project

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#4118]
Trying to create a package, namely, SPDK
First question, in case of non-CMake project, which builds by executing two commands
```
./configure
make
```
is it there something more than just executing from portfile a bash command to run these two above?

Second, this project (on GitHub) has a gutmodule pointing to DPDK, how do vcpkg should handle submodules?

**Comment by ras0219-msft** [comment]
Thanks for the questions!

>something more than just executing from portfile a bash command to run these two above?

In the case of a large library like SPDK, that's the general approach. However, there are a few notes to keep in mind:
- We _strongly_ recommend against in-source builds to avoid cross-contamination. This means the source code should be copied out into a separate folder before running `./configure && make`.
- Because you can't use the built-in msbuild/cmake helpers, options won't be handled automatically. I think for an initial port it's probably fine to ignore these, but there's room for improvement in the future :)
- Generally, use `vcpkg_execute_required_process()`[1] instead of `execute_process()` because it will fail the build on error instead of silently continuing.

I recommend looking at `ffmpeg`[2] as an example of a "custom" build process looks like :).


Generally, submodules are used as a low-cost form of package management; in this case, the submodule should be made into a separate port with a dependency between them. The buildsystem of SPDK may need to be patched to handle this (because previously it expected to build the submodule and now it needs to consume prebuilt binaries) but this usually is quite straightforward.

However, if it is a more complex situation where the submodule is providing source code that gets compiled into the SPDK binary itself, the best immediate option is to download the submodule explicitly via a `vcpkg_download_distfile()` command and unpack it into the expected location[3].

[1] https://github.com/Microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_execute_required_process.md
[2] https://github.com/Microsoft/vcpkg/blob/master/ports/ffmpeg/portfile.cmake
[3] https://github.com/Microsoft/vcpkg/blob/5e57beb401c260cea9cb5c355410f1ffc4e49347/ports/google-cloud-cpp/portfile.cmake#L18-L27

**Comment by kreuzerkrieg** [comment]
Thanks for the input.
>>I recommend looking at ffmpeg[2] as an example of a "custom" build process looks like :)

Huh, I guess the smiley in the end was meant to be "evil grin", I've already took a look at it, and it looks, ummmm, complicated :) Indeed, looks like too much lines for simple `./configure && make`


>> The buildsystem of SPDK may need to be patched to handle this
As I understand, `vcpkg_download_distfile()` solves this problem and no changes to SPDK should be changed, right?

**Comment by JackBoosY** [comment]
Now, vcpkg has `vcpkg_*_make` functions, you can use them to install ports.
