### ISSUE TITLE
boost 1.68 output DLLs' name are incorrect

### ISSUE THREAD

**Issue by haquocviet** [Microsoft/vcpkg#4127]
I just upgraded boost to version 1.68 and I got output dlls named incorrectly.
Example:
it produces "boost_atomic-vc141-mt-x64-1_67.dll" instead of "boost_atomic-vc141-mt-x64-1_68.dll"

**Comment by degski** [comment]
I build statically and got this kind of output `boost_wserialization-vc140-mt.lib`. I'm just stating that, no other intention.

**Comment by ras0219-msft** [comment]
Thanks for catching this!

We're definitely using the new source, however it looks like we missed updating a text file somewhere that changes the dll name :)

**Comment by degski** [comment]
@ras0219-msft I don't know whether intentional or not, but building x64-windows-static creates libs named like `boost_program_options-vc140-mt.lib`, which is fine with me. Two points though, why is there in this case no boost version? Second, why is vc141 renamed to vc140, as I have no vc140 on my system? We need to keep it though, as it seems at some point clang could be used as a tool-chain (it seems so at least), in that case it will, need say something like `clang7-vc141` as the crt version is obviously still important.

**Comment by ras0219-msft** [comment]
Removing the version from the `.lib` name improves compatibility with cmake versions before 3.12. In the vc140/vc141 case, they are binary compatible so we "collapse" the two into just `vc140` to enable sharing between both VS2015 and VS2017.  I think in the clang case you may also get collapsed to `clang7-vc140`, but assuming everything still links this is fine (the CRT is binary compatible).

**Comment by degski** [comment]
@ras0219-msft 

Why not collapse it into vc14 then, at least that's factual.
