### ISSUE TITLE
[qt5] qt5:x64-windows install step fails

### ISSUE THREAD

**Issue by cweiglemec** [Microsoft/vcpkg#413]
Attempting to build x64 version of qt5. Build seems to be working. Install step fails:

```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: D:/dev/3rdparty/vcpkg/downloads/tools/jom/jom.exe;-j1;install
    Working Directory: D:/dev/3rdparty/vcpkg/buildtrees/qt5/x64-windows
    See logs for more information:
      D:\dev\3rdparty\vcpkg\buildtrees\qt5\install-x64-windows-out.log
      D:\dev\3rdparty\vcpkg\buildtrees\qt5\install-x64-windows-err.log

Call Stack (most recent call first):
  ports/qt5/portfile.cmake:74 (vcpkg_execute_required_process)
  scripts/ports.cmake:73 (include)
```

Complete console messages attached, along with install logs.

[qt5_x64_build.log.txt](https://github.com/Microsoft/vcpkg/files/649793/qt5_x64_build.log.txt)
[install-x64-windows-err.log.txt](https://github.com/Microsoft/vcpkg/files/649789/install-x64-windows-err.log.txt)
[install-x64-windows-out.log.txt](https://github.com/Microsoft/vcpkg/files/649790/install-x64-windows-out.log.txt)

**Comment by Barath-Kannan** [comment]
Just tried on a fresh install and it worked fine for me. Looks like there were some issues with network stuff in your install log. Try doing a remove --purge of qt5 and open ssl, and also delete their directories in vcpkg/buildtrees, then install again with the latest version of vcpkg. I've also noticed some issues when trying to install from a git bash command line instead of a regular command prompt so if you're using git bash, try just using cmd and see if that works better.

**Comment by cweiglemec** [comment]
That did work, thanks. Well, I also had to reinstall libpq, because dependencies.

If there was an error building Qt5Networkd.dll, shouldn't the build have stopped there, so I could see that error, instead of failing on the install step?

This was all from powershell ... no offence to the suggestion, but perhaps that should go in a log so one doesn't have to guess.
