### ISSUE TITLE
[openexr] [ilmbase] Include dir problem

### ISSUE THREAD

**Issue by malkia** [Microsoft/vcpkg#4151]
Vcpkg splits OpenEXR into two packages: ilmbase, and openexr

  This actually works well, if the packages are later "installed"
  under a common lib, include, etc. folders - they don't have any overlapping files
  (apart from COPYRIGHT, which is the same in both cases, and as expected BUILD_INFO, CONTROL).

  The issue is when we use these packages independently, basically having,
     -I<sdk>/openexr/<openexr.version>/include
     -I<sdk>/ilmbase/<ilmbase.version>/include

  So headers from openexr, expect to find other headers from ilmbase as their siblings, e.g:
     openexr\2.2.1-1\include\OpenEXR\ImfRgba.h
  includes half.h like this:
     #include "half.h"
  but "half.h", when separate packaging is used, is here:
     ilmbase\2.2.1-1\include\OpenEXR\half.h

  Now tt could be argued, that maybe additional
     -I<sdk>/ilmbase/<version>/include/OpenEXR
  should be done, but that poisons needlesly the header dirs list, just for the sake of OpenEXR itself
  finding it's other header files.

  And then the usage I've seen, in code using OpenEXR (and ilmbase) done is to do it like this:
     #include <OpenEXR/half.h>

  not like:
     #include <half.h>

  Not sure what the right approach here would be, but essentially you've got only one "mode" (combined,
  a.k.k. the unix way (is that the right name?)), while the separate packaging does not. Or maybe I'm
  missing something.

  Please advise! It's nothing urgent on our side, I'll simply combine both packages into one, for the
  time being.

**Comment by ras0219-msft** [comment]
Thanks for letting us know!

As documented in our integration docs [1], we recommend consuming the files from `installed\` which is actually exactly the combined mode you're talking about :). We explicitly have not documented the packages folder, because we intend to compress those files in the future and they will not be accessible in that format.


[1] https://github.com/Microsoft/vcpkg/blob/master/docs/users/integration.md#manual-compiler-settings

**Comment by malkia** [comment]
Hmm.. I have to rethink our strategy then. Thanks for letting us know :)

Ideally we want to support a structure (stored into our SCM), like this:

<root>/sdk/<package>/<package.version>/include
<root>/sdk/<package>/<package.version>/lib
<root>/sdk/<package>/<package.version>/debug/lib

We also compiled, and "deployed" one or two, non-vcpkg packages this way (actually "p4api" itself, and another internal one), to mimik the structure. Currently we may have more than one version, as users of our "sdk" in one project may decide to use one version, vs. another.

Then again, we are looking into removing the packages from the SCM (we use, as it maybe implied perforce), and have them downloaded from local share, or local http:// server. Started even looking into NuGet, or custom internal solution. Not sure yet.

Now that you've mentioned that installed\ is the officially supported way, we may have to change how we approach this, but for some reason felt that the "packages" artifacts were the right ones. Now though I see the light.

The real issue we are facing is this:
  - We have tons of projects (each with .sln file). Maintainers of some of these projects might link some of the libraries we provide already in some other fashion (typically - zlib, luajit, etc.). They still might be users of our "sdk", but due to transitive dependencies - e.g. they use some internal lib, that happens to link to the "vcpkg-ed" zlib that we use. At this point we don't want that "zlib" from vcpkg to be linked back.
  - There would be a bit of assumptions, and failures. Obviously we have compiled against vcpkg-ed provided zlib, yet user of our libs, has linked zlib directly (maybe even from zlib's own .vcxproj file). We can ("unsafely") assume that ABI would be the same, and things would go alright.
  - But the realization I've came was that we need the "installed\" layout to be generated per .sln, or maybe per .vcxproj that targets .dll, or .exe (e.g. actual binary). And for each such "binary" we have exactly one "installed\" folder that symlinks only the vcpkg libraries requested for that project, and no more.
  - Say ToolGaba uses vcpkg'd curl and sqlite3, but not under our control, and also links to custom zlib.vcxproj. We need "installed\" layout for that tool that only contains "sqlite3, curl, openssl, maybe libssh2, etc. the curl's own deps".
  - Now AppZaba uses vcpkg'd zlib, libzip, minizip, sqlite3 - we also need to provide it's own "installed\" layout (again may be just symlinks pointing back to a "unified" vcpkg'd tree with all).
  - This all effort might seem a bit too much, only to basically (in this simple example) exclude the vcpkg'd zlib from the first "installed\" symlinked tree - and make sure the "other" zlib (zlib.vcxproj) is included. The last one, you may can be replaced with vcpkg, but as it happens shipping games to consoles, that "zlib.vcxproj" also targets PS4, XboxOne, etc. - and it's an App that actually may run on actual device, but also on PC as more general Tool or App.
  - To recap - if we have single "installed\" layout for all our projects, tools, apps - we risk that by having an vcpkg'd library in this "installed\" dir, we are exposing inadvertently header files, and (maybe libs, though this could be guarded) to users that may not want to link with these, but their owns.
   - The alternative, is rather to have one "installed\" is to have several such, where each just symlinks to the root, but only parts of it. E.g. I have a symlinked "installed\" folder for only zlib, cpprest-sdk, boost, another for just sqlite3, curl (and deps), etc. And then each .vcxproj user of these just sees one of them, not the global "installed\" tree.

So how do I currently solve this? I've made my own MSBuild plumbing, where I can specify (at the .vcxproj) level which packages are to be used by the project. Something like <VcpkgUse Include="zlib;sqlite3;libzip;"/>, then have one global "sdk" folder, with a vcpkg.props file where things are declared like: "<VcpkgDeclare Include="zlib" Version="1.2.3"/>", etc. for the rest (made up version here). This "vcpkg.props" file is the same per studio, team (but the studio or team might decide to use different versions). Then I do the crossproduct of "VcpkgUse" and "VcpkgDeclare" (and check for "uses" that were not "declared"), and from there having a "VcpkgRoot" property - basically a dir with all packages with the layout at the top of my post, I sprinkle various <AdditionalDirectories>, <AdditionalDependencies> for linking... <VcpkgUse> effetivelly adds the "-I<sdk>/<package>/<package.version>/include" to the compiler, and <sdk>/<package>/<package.version>/lib/*.lib to the linker (so for "debug", and then also additionally manual-link as needed say for gtest). I do also have <VcpkgUseHeaders> and <VcpkgUseLibs> which just does the first part (-I<sdk> for compiler), or only the latter. The latter is more useful, as sometimes linking to internal library, you don't care what that library needs, that library simply exposes into it's .public.props file that it needs to <VcpkgLibs Include="zlib;sqlite3"/> - e.g. these gets linked, but the -I<folders> are not poisoned with unneeded include dirs there.

Sorry for the long description, just trying to come up with better plan how to change my strategy, as we are really "bought" into the vcpkg packaging and the plethora of libraries that it provides.

Thanks for answering my question, and I guess the issue can be closed!

**Comment by malkia** [comment]
Hmm.. Github ate "<>" if they were not quoted. I'll fix the comment above later today.

**Comment by ras0219-msft** [comment]
I noticed you added some comments that may have since been deleted, but perhaps I can provide some useful commentary on top of that :)

One of the core design criteria of vcpkg is to _completely prevent_ ODR violations. This means that we want to make it incredibly difficult to accidentally pull in two different copies of the same library. Part of our strategy for preventing this is placing every library into a single root -- this guarantees exactly one copy of each library and trivially ensures that if `libA` was built against version 2 of `libB`, you will definitely get version 2 of `libB` if you use that `libA` (instead of version 1 or 3 etc).

If you want to have a special `libB` that's different than the one in vcpkg, just change the portfile to use your special one! There are several options to do this:
1. Apply patch files to the sources using `vcpkg_apply_patches()`
2. Redirect the source download step to your own custom fork
3. Rewrite the portfile entirely to do a completely custom build
4. Rewrite the portfile entirely to inject prebuilt binaries by simply copying them directly to `${CURRENT_PACKAGES_DIR}/{include,lib,debug/lib}`.

This approach removes all ODR and ABI worries since we will make sure to rebuild all libraries on top of that special variant with the special variant :). Additionally, if these changes are additive (like supporting PS4/XB1), we'd be happy to accept them upstream :D.

Now, for the case of multiple executables that want different dependencies: in this case, you will effectively need separate vcpkg instances for each unique version set. This is critical for libraries like boost which are not ABI compatible between versions; everything using boost needs to be built differently depending on the boost version being used by that particular process.

If you want to make _subsets_ of a particular graph (so all libraries are the same version but you don't want `libD` available to `exeB` and `libB` available for `exeD`), you might want to look at our Export command[2]. This command is quite useful for a lot of different things, but in this case it allows you to "export" a subgraph of packages out of a given vcpkg instance into either a raw folder, a zip file, or a nuget package. This is also the command we recommend if you want to do binary caching.

Since it sounds like you use .vcxproj files pretty extensively, I'll also note that we recently added `vcpkg_install_msbuild()`[1] which can make it a lot easier to package msbuild-based libraries.

[1] https://github.com/Microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_install_msbuild.md
[2] https://github.com/Microsoft/vcpkg/blob/master/docs/users/integration.md#export-command

**Comment by malkia** [comment]
Thank you so much for clarifying it! We are evaluating vcpkg on our side, and through different ways. At first I was simply looking for system (and landed on vcpkg) that would produce pre-compiled packages for us, to fit in our existing ad-hoc "sdk" folder. 

The first thing I've liked from VCPKG was the uniform way of how packages were structured: include/, lib/, debug/lib/ folders. We still have packages in this "sdk" folder, not compiled by "vcpkg" because we need somewhat more tight control there, our patches, like "qt5", and others. Then I've actually "mimicked" how certain other libs were done (for example perforce's p4api), or "opencensus-cpp", and packaged them in similar way as vcpkg. Simply experimenting how far this would go.

I generally like the idea of one "include", and one (or two) lib/ (debug/lib) folders. But the current state of things is that we need to keep sdk/<package/<version> layout, as there might be more than one version, and different users of our code might be stuck on different versions there too. (our clients, may integrate our code directly through the SCM, but may have chosen different versions of the packages). This freezing is mainly around various milestone deliveries (could be from days, to weeks to months, even years, if a product needs to be supported for a longer period). As such we need to keep these versions for them, and can't rely only on latest.

It seems like vcpkg export, for example "vcpkg export openexr" would do what I need (just tried it, so it packs together ilmbase, but also pulls zlib, not ideal - but there are also manifests files produced in there, so some small tool that is a bit more explicit version of "vcpkg export" - e.g. "vcpkg export openexr --strip zlib,.etc." might do it for us.

But most of all, thank you for the awesome project!
