### ISSUE TITLE
[New Port Request] < EventBus >

### ISSUE THREAD

**Issue by ilongshan** [microsoft/vcpkg#41549]
### Library name

EventBus

### Library description

A lightweight and very fast event bus / event framework for C++17

### Source repository URL

https://github.com/gelldur/EventBus

**Comment by motazmuhammad** [comment]
@ilongshan This library uses an older version of catch2 and since overrides are not active in the script mode, I am unsure, how is that handled here?

**Comment by ilongshan** [comment]
@motazmuhammad Not sure how to deal with it. Maybe pending the port util the project updates to the catch2 v3.

**Comment by dg0yt** [comment]
Is catch2 needed for something else than tests?  
vcpkg port shall not run tests. So any catch2 dependency can be disabled.

**Comment by motazmuhammad** [comment]
@dg0yt , just for tests thank you, removing it does solve the problem,

another question in that area , it seems that the .lib files are not generated in the dynamic build, which causes this error
LINK : fatal error LNK1104: cannot open file 'lib\EventBusd.lib'

the dll files are existent however, this is a problem with dynamic linking only as if I set the linkage to static only the build works fine, the only way I can think of to solve this problem is via adding a patch to cmakelists file to force it to produce lib files, have you faced that before? or do you know how it should be solved? or should I make this library static only library?

**Comment by dg0yt** [comment]
If there is a DLL (for runtime) without lib (for build time), then the packages lacks proper exports for Windows. Then do not build a DLL. Start the portfile with:
~~~cmake
if(VCPKG_TARGET_IS_WINDOWS)
    vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
endif()
~~~

**Comment by motazmuhammad** [comment]
@dg0yt thank you, I will use that then
