### ISSUE TITLE
[curl] Debug libraries are incorrectly embedding vsnprintf and other functions

### ISSUE THREAD

**Issue by jonahbeckford** [microsoft/vcpkg#41761]
**Describe the bug**
Using the latest vcpkg (`git clone --depth 1 https://github.com/microsoft/vcpkg.git`) the Debug build exports the following symbols that should not be present:

```
                  LongToHandle
                  __local_stdio_printf_options
                  __local_stdio_scanf_options
                  _vsscanf_l

                  snprintf
                  sscanf
                  vsnprintf
```

That causes errors for consumers of `curl`:

```
error LNK2005: vsnprintf already defined in libcurl-d.lib(libcurl-d.dll)
```

In fact, the Debug build seems to import *many* more symbols that are not present in the Release build, although these extra symbols are prefixed with `Curl_` or `curlx_` so they won't cause problems:

```
                  Curl_GetFTPResponse
                  Curl_HMAC_final
                  Curl_HMAC_init
                  Curl_HMAC_update
                  Curl_MD5_final
...
                  Curl_xfer_setup1
                  Curl_xfer_setup2
                  Curl_xfer_setup_nop
                  Curl_xfer_write_done
                  Curl_xfer_write_resp
                  Curl_xfer_write_resp_hd

                  curlx_convert_UTF8_to_wchar
                  curlx_convert_wchar_to_UTF8
                  curlx_mstotv
...
                  curlx_uztoui
                  curlx_uztoul
                  curlx_verify_windows_version
                  curlx_win32_fopen
                  curlx_win32_open
                  curlx_win32_stat
                  curlx_write
```

**Environment**
- OS: Windows
- Compiler: VS 2022. `Y:\VS\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe`

**To Reproduce**
1. `$env:VCPKG_BINARY_SOURCES="clear;files,$PWD/vcpkg/archive,readwrite"; .\vcpkg\vcpkg install --Triplet=x64-windows curl`
2. `dumpbin /EXPORTS vcpkg\buildtrees\curl\x64-windows-dbg\lib\libcurl-d.lib > libcurl-d.lib.EXPORTS.txt`
3. `dumpbin /EXPORTS vcpkg\buildtrees\curl\x64-windows-rel\lib\libcurl.lib > libcurl.lib.EXPORTS.txt`

**Failure logs**
- See the good Release exports [libcurl.lib.EXPORTS.txt](https://github.com/user-attachments/files/17513423/libcurl.lib.EXPORTS.txt) (attached).
- Compare it to the problematic Debug exports [libcurl-d.lib.EXPORTS.txt](https://github.com/user-attachments/files/17513422/libcurl-d.lib.EXPORTS.txt)(attached)

**Additional context**

After some research, it looks like exporting all the symbols is something done upstream in curl/curl:
https://github.com/curl/curl/blob/b8c12634fce509673f8eda657e9a2222890707c1/CMake/CurlSymbolHiding.cmake#L27-L32

> ... disable symbol hiding for debug builds and for memory tracking.

Regardless, re-exporting C runtime functions is a problem.

I can mitigate it with the following patch added to `portfile.cmake`: [symbol-hiding.patch](https://github.com/user-attachments/files/17513762/symbol-hiding.patch)

I think it should be enabled only through a vcpkg feature? I'm not an expert in vcpkg.

**Comment by dg0yt** [comment]
The CURL debug build is configured with `ENABLE_DEBUG=ON`.

Since CURL 8.4.0, this option unconditionally enables `CURL_HIDDEN_SYMBOLS` on `WIN32`.
https://github.com/curl/curl/commit/a8ebde99f7beffb8df33f797180da077eac169db#diff-31dbcd75744281bc2bbeb464df9949e67246eabbd8adfbafe20a87f86fa7eb2fR32

For MSVC, `CURL_HIDDEN_SYMBOLS` leads to the infamous `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`:
https://github.com/curl/curl/blob/b8c12634fce509673f8eda657e9a2222890707c1/CMake/CurlSymbolHiding.cmake#L58-L60

@vszakats Are you aware of the MSVC symbol issue?

Possible mitigation: Remove `ENABLE_DEBUG` from the port's debug configuration.

**Comment by vszakats** [comment]
I wasn't aware, thanks for the heads up.

First thought: Is it intended to use `ENABLE_DEBUG=ON`?
It's a 100% insecure option meant for developing curl itself and running
its tests suites.

To obtain a build with debug info and asserts, it's enough to use
`-DCMAKE_BUILD_TYPE=Debug` or any other Debug config.
Such build is safe for "normal" use and/or by dependents.

This aside, what's interesting is that curl isn't supposed to be defining
these functions (`snprintf`, `sscanf`, `vsnprintf`, `_vsscanf_l`, `LongToHandle`),
and according to a quick grep: they are not defined anywhere in the source.

I don't have MSVC to test it locally, but a similar MinGW build is not
producing these symbols in `libcurl.dll`, with `ENABLE_DEBUG=ON`.

Which specific objects are exporting these symbols?

---

Perhaps `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON` is the
culprit, and perhaps it's an option to avoid?

In any case this issue applies to all `-DURL_HIDDEN_SYMBOLS=OFF`
MSVC build, not just `ENABLE_DEBUG=ON`, so it'd be nice to find the
root cause.

**Comment by dg0yt** [comment]
In vcpkg, port authors are not allowed *to add* `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` because it is known to cause problems. However, it is not required *to remove* it from upstreams.

IIUC the port should simply remove `-DENABLE_DEBUG=ON`. People interested in digging deeper into CURL can add it in other ways.

> I don't have MSVC to test it locally

Neither do I ;-)

**Comment by dg0yt** [comment]
> This aside, what's interesting is that curl isn't supposed to be defining
> these functions (`snprintf`, `sscanf`, `vsnprintf`, `_vsscanf_l`, `LongToHandle`),
> and according to grep: they are not defined anywhere in the curl source.

That's the problem of `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`: it may unexpectedly export symbols which actually belong to other libs.

**Comment by vszakats** [comment]
> In vcpkg, port authors are not allowed _to add_ `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` because it is known to cause problems. However, it is not required _to remove_ it from upstreams.
> 
> IIUC the port should simply remove `-DENABLE_DEBUG=ON`. People interested in digging deeper into CURL can add it in other ways.

Yes, that'd be sensible.

> > I don't have MSVC to test it locally
> 
> Neither do I ;-)

:)

**Comment by vszakats** [comment]
> > This aside, what's interesting is that curl isn't supposed to be defining
> > these functions (`snprintf`, `sscanf`, `vsnprintf`, `_vsscanf_l`, `LongToHandle`),
> > and according to grep: they are not defined anywhere in the curl source.
> 
> That's the problem of `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`: it may unexpectedly export symbols which actually belong to other libs.

Nice! I'll make some experiments with it, and see if there is a way to avoid it in curl.

**Comment by vszakats** [comment]
> > That's the problem of `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`: it may unexpectedly export symbols which actually belong to other libs.
> 
> Nice! I'll make some experiments with it, and see if there is a way to avoid it in curl.

It seems without this option, MSVC doesn't export symbols. There is no
implib generated.

According to the [documentation](https://learn.microsoft.com/en-us/cpp/build/reference/wholearchive-include-all-library-object-files?view=msvc-170), there is no option to export all declared symbols.
(or if there is, I did not find it)

The methods offered are variations of explicitly listing symbols to be exported.
That needs a list, which isn't practical to maintain or generate. CMake goes
with the latter, ending up with extra symbols. It's [extracting them](https://gitlab.kitware.com/cmake/cmake/-/issues/22092#note_943718) from .obj files.

This leaves the option to decorate every function with a macro and set that macro
accordingly, which is in turn an excessive change and hard to justify for this.

Keeping `ENABLE_DEBUG` disabled seems like the best fix IMO.

**Comment by jonahbeckford** [comment]
> @jonahbeckford. I can mitigate it with the following patch added to portfile.cmake: [symbol-hiding.patch](https://github.com/user-attachments/files/17513762/symbol-hiding.patch)

> @vszakats. Keeping `ENABLE_DEBUG` disabled seems like the best fix IMO.

Is there anything wrong with keeping the approach used in curl's Release mode? The Release mode makes use of [lib/libcurl.def](https://github.com/curl/curl/blob/master/lib/libcurl.def), so my tiny patch gets you the Debug build with the correct symbols.

**Comment by vszakats** [comment]
> > [@jonahbeckford](https://github.com/jonahbeckford). I can mitigate it with the following patch added to portfile.cmake: [symbol-hiding.patch](https://github.com/user-attachments/files/17513762/symbol-hiding.patch)
> 
> > [@vszakats](https://github.com/vszakats). Keeping `ENABLE_DEBUG` disabled seems like the best fix IMO.
> 
> Is there anything wrong with keeping the approach used in curl's Release mode? The Release mode makes use of [lib/libcurl.def](https://github.com/curl/curl/blob/master/lib/libcurl.def), so my tiny patch gets you the Debug build with the correct symbols.

It could work, but with the complexity of idenfiying each symbol necessary
for tests, then maintaining a second copy of `libcurl.def` with an up-to-date
list of these symbols and the official ones.

`ENABLE_DEBUG`'s purpose is to enable hooks and other internal debug
things for curl's own tests, via an internal `DEBUGBUILD` macro. It also
enables memory tracing by default, and effectively nils security features.

It's independent from the Debug preset offered by CMake.

I wonder, what would be the use-case for consuming an `ENABLE_DEBUG` libcurl?
Would a normal libcurl built in Debug mode work instead?

**Comment by jonahbeckford** [comment]
> I wonder, what would be the use-case for consuming an ENABLE_DEBUG libcurl?

There is no use case

> Would a normal libcurl built in Debug mode work instead?

I thought that was what my patch did, but perhaps I was mistaken. I'll defer to your analysis!
