### ISSUE TITLE
[bitmagic] Projects using bitmagic can't be build using clang 19

### ISSUE THREAD

**Issue by vasil-pashov** [microsoft/vcpkg#41935]
### Is your feature request related to a problem? Please describe.

While the package itself can be build projects using it cannot be build. The issue is reported [here](https://github.com/tlk00/BitMagic/issues/76) and is fixed in master. Tested with clang 19.2. Older versions of bitmagic also fail the build.

### Proposed solution

A new update that uses the latest master of v7.13.4 of bitmagic.

**Comment by Cheney-W** [comment]
Since the upstream has not yet released a version that includes this modification, and we cannot arbitrarily switch from using the original tag system to the latest commit system, we will temporarily address this issue in vcpkg with a patch. Once the upstream releases a new version, we will update the port version and remove the patch.
