### ISSUE TITLE
integrate install with static port unable to find includes

### ISSUE THREAD

**Issue by brucebob** [Microsoft/vcpkg#420]
Install ports with triplet x64-windows-static and x86-windows-static.
Then run integrate install.
Open up a VCProg and try to include the port I installed and unable to find file.
Check project properties and see the VcpkgRoot is "C:\vcpkg\installed\x64-windows".
Where is should be "C:\vcpkg\installed\x64-windows-static"
Am i missing something on the integrate install?

**Comment by ras0219-msft** [comment]
We, by default, reference the x64-windows and x86-windows triplets. This is primarily because the Visual Studio project defaults are to use the dynamic CRT (/MD). In contrast, the *-windows-static triplets use the static CRT (/MT), which you'll need to change in your project settings if you'd like to use those triplets.

However, switching the CRT alone won't change the referenced triplets, due to the particular way that the CRT reference is implemented inside MSBuild. You'll need to set the MSBuild property `VcpkgTriplet` to specify exactly which triplet you'd like to use binaries from. For more information on this, take a look at the blog post [1]. In specific, you will probably want to do the following (if you only care about building x64):
```xml
<PropertyGroup Label="Globals">
    ....
    <VcpkgTriplet>x64-windows-static</VcpkgTriplet>
    <VcpkgEnabled>true</VcpkgEnabled>
</PropertyGroup>
```

You can try it out first in a developer prompt by adding `/p:VcpkgTriplet=x64-windows-static` to the msbuild line:
```
C:\>msbuild /p:VcpkgTriplet=x64-windows-static /p:Platform=x64 MyAwesomeApp.sln
```

Sorry for the confusion!

[1] https://blogs.msdn.microsoft.com/vcblog/2016/11/01/vcpkg-updates-static-linking-is-now-available/

**Comment by pravic** [comment]
Hello,
I also stuck with integrating static libraries. I think, it would be nice to add this explanation to the documentation.
