### ISSUE TITLE
Discussion: Separate ports from vcpkg core

### ISSUE THREAD

**Issue by parkovski** [Microsoft/vcpkg#4242]
The main motivation behind this is - I go on the issues tab to see what has been proposed and what is in progress for a project. With vcpkg, it's really hard to tell because the page is cluttered with "add such and such port" or "fix $LIBRARY on $PLATFORM". It seems to me that it'd be better to separate out the ports into its own repo with its own issues tracker, and allow this one to just be for the vcpkg core project. Thoughts?

**Comment by patrikhuber** [comment]
This seems more like a labelling issue to me. People reporting issues, as well as Microsoft vcpkg maintainers, could use GitHub labels for this. I'm actually not sure people reporting issues can select labels, but anyway, it's a task of a few seconds to label an issue, even if you would "only" do 5 per minute, it would take just 3 hours for a single employee to label all 1000 open issues.

And then you could perfectly search the issues by labels!

I think the core problem at heart is that Microsoft is too overwhelmed with the number of issues that get reported here - probably it's only one or two people working on it, part-time.
The growing number of open issues is something I've noticed a few months ago and it's quite concerning actually, and since then, it has only gotten worse (over 1000 open issues now).

I hope that MS can put the appropriate manpower to make sure vcpkg is a continued success and is being maintained appropriately. I understand that this is an open-source project where everybody can contribute, so in theory it would be as much "their" project as it is "ours" (which is an awesome thing!), but the practical reality is that it doesn't just work like that (as is evident by the over 1000 open (and growing number of) issues).
