### ISSUE TITLE
Upgrade OpenSSL to 1.1.1

### ISSUE THREAD

**Issue by fcharlie** [microsoft/vcpkg#4267]
Good News OpenSSL 1.1.1 has been released, it supports **TLS1.3 RFC 8446**.
OpenSSl 1.1.1 is New LTS. OpenSSL 1.1.1 is API and ABI compliant with OpenSSL 1.1.0.

Support for various new cryptographic algorithms including:
+   **SHA3**
+   SHA512/224 and SHA512/256
+   EdDSA (including Ed25519 and Ed448)
+   X448 (adding to the existing X25519 support in 1.1.0)
+   Multi-prime RSA
+   SM2
+   SM3
+   SM4
+   SipHash
+   ARIA (including TLS support)

In fact, some ports cannot be upgraded to the latest version because the version of openssl of vcpkg is too low, such as libssh.

>Our previous LTS release (OpenSSL 1.0.2) will continue to receive full support until the end of this year. After that it will receive security fixes only. It will stop receiving all support at the end of 2019. Users of that release are strongly advised to upgrade to OpenSSL 1.1.1.

It's time to upgrade OpenSSL.

See: https://www.openssl.org/blog/blog/2018/09/11/release111/

Here are the ports that depend on openssl: 

|ports|support OpenSSL 1.1.1|
|---|---|
|librabbitmq|✔|
|aws-sdk-cpp|✔|
|wt|✔|
|azure-c-shared-utility|✔|
|libimobiledevice||
|yara|✔|
|libwebsockets|✔|
|podofo|✔|
|thrift|✔|
|ffmpeg|✔|
|qpid-proton||
|folly|✔|
|libssh|✔ (0.8.* Only 1.1.*) (2019-07 move to mbedTLS)|
|paho-mqtt||
|websocketpp|✔|
|apr-util|✔|
|libarchive|✔|
|cppcms|✔|
|libmysql|✔|
|mongo-c-driver|✔|
|fastrtps|✔|
|freerdp|✔|
|qt5-base|✔ (5.13)|
|caf|✔|
|curl|✔|
|opusfile|✔|
|librtmp||
|libevent|✔|
|mosquitto|✔|
|uwebsoockets|✔|
|libgit2|✔|
|libpq|✔ (11.4 test OK, ubuntu 18.04 apt install openssl 1.1.1)|
|boost-asio|✔|
|cpprestsdk|✔|
|libtorrent||
|wangle|✔|
|grpc|✔|
|libssh2|✔|

**Comment by fcharlie** [comment]
@ras0219-msft @alexkaratarakis

**Comment by madig** [comment]
I think this calls for splitting the openssl package into a 1.0.x and 1.1.x branch. The API changed considerably in 1.1.x and older applications must be updated...

**Comment by zhulika** [comment]
In case someone else is tripped up by this, I'd like to point out that this problem may also cause vcpkg's integration for Visual Studio to break other projects. It may not spring to mind when you first see the errors, because openssl tends to be installed implicitly as a dependency by vcpkg, but vcpkg's version of OpenSSL will take precedence during the link phase over any local copy of OpenSSL that is part of the project's distribution.

I have just spent some time tracing the cause of a bunch of duplicate-symbol linker errors when trying to build NodeJS and it turned out to have been the copy of OpenSSL 1.0.2 that is being inserted at the top of MSBUILD's stack by vcpkg's integration with Visual Studio.

**Comment by fcharlie** [comment]
@ras0219-msft @alexkaratarakis Only a handful of ports do not support OpenSSL 1.1.1

**Comment by alexkaratarakis** [comment]
Very nice! qt5 concerns me a bit; the others look more easily patchable.

**Comment by fcharlie** [comment]
@alexkaratarakis https://bugreports.qt.io/browse/QTBUG-67463

**Comment by anluoma** [comment]
Just asking that are we waiting for Qt bug to finish before this gets fixed? We are interested of updating to 1.1.1 as well. Or is my assumption wrong?

**Comment by jozefizso** [comment]
Is there OpenSSL 1.1 port available which can be used internally?

It looks like Qt will block this port for some time.

**Comment by Rastaban** [comment]
it looks like PR #4983 may be dependent on this.

**Comment by mjaafar** [comment]
Hi there I want to know if there is any chance that it supports EVP_sha256. Thanls cause I do need it in my integration https://github.com/Microsoft/vcpkg/issues/5529

**Comment by fcharlie** [comment]
@mjaafar See: [https://github.com/openssl/openssl/blob/OpenSSL_1_1_1b/include/openssl/evp.h#L707](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1b/include/openssl/evp.h#L707)

**Comment by mjaafar** [comment]
The issue is related to configure the default options put sha256 in no option I hope in openssl 1.1.1 integration it will be activated

**Comment by illera88** [comment]
any update here? there are several ports that depends on this

**Comment by fcharlie** [comment]
@illera88 It seems difficult, [OpenSSL 1.1.1 for the UWP](https://github.com/Microsoft/openssl/issues/65) transplant for a long time without movement, I recommend that you build your own OpenSSL 1.1.1, which is much better than waiting to be built with vcpkg.

**Comment by HLXEasy** [comment]
Is there some kind of a roadmap? It would be very cool to use the whole vcpkg content but as long as OpenSSL is stuck on 1.0.x, it's impossible to migrate.

**Comment by MouriNaruto** [comment]
I have opened a new PR in the offical OpenSSL repo. (https://github.com/openssl/openssl/pull/8917)

**Comment by HLXEasy** [comment]
Any news here?

**Comment by illera88** [comment]
Waiting for OpenSSL devs to merge https://github.com/openssl/openssl/pull/8917

**Comment by HLXEasy** [comment]
Nice, openssl/openssl#8917 get's merged some minutes ago.

**Comment by HLXEasy** [comment]
@MouriNaruto What do you think? Which steps are the next ones to get this PR closed?

**Comment by MouriNaruto** [comment]
@HLXEasy I have open an issue. (https://github.com/openssl/openssl/issues/9125)

**Comment by illera88** [comment]
https://blog.qt.io/blog/2019/06/17/qt-5-12-4-released-support-openssl-1-1-1/

Qt can now use OpenSSL 1.1.1

**Comment by kelteseth** [comment]
@illera88  Qt 5.13 Apps now __require__ OpenSSL 1.1.1 and Qt itself does not ship it with the binaries. I was hoping to simply use vcpkg for this...

**Comment by thedevilfish** [comment]
Just an FYI folks: 
- For `mosquitto`, `OpenSSL 1.1.x` is supported as of `mosquitto v1.4.x`
- For `paho-mqtt`,`OpenSSL 1.1.x` is already supported as of `paho-c library v1.3.x`

**Comment by fcharlie** [comment]
Libssh now starts using mbedtls instead of OpenSSL. see: #4983 (comment). Note that the author of that PR is the maintainer of libssh.

**Comment by illera88** [comment]
It's better moving out from using OpenSSL than leading with their maintainers... Good decision from libssh maintainer

**Comment by fcharlie** [comment]
Building openssl 1.1.1 without using vcpkg is easier. I built curl using my own script (depending on openssl 1.1.1). Https://github.com/fstudio/clangbuilder/blob/master/sources/wincurl/wincurl.ps1

No matter what package management tool you use, you may end up being bothered by the fact that this main dependency cannot be upgraded in time. Therefore, it may be better to build from source.

**Comment by jozefizso** [comment]
Any updates for supporting the OpenSSL 1.1.1 port?

**Comment by wegylexy** [comment]
It's been a year. I realize that OpenSSL changed a lot since 1.1.0 for building on Windows. Has someone got the time to make any progress?

**Comment by fcharlie** [comment]
OpenSSL 1.0.2 EOL 2019-12-31

Reference: [https://www.openssl.org/news/secadv/20190910.txt](https://www.openssl.org/news/secadv/20190910.txt)

>OpenSSL 1.0.2 is currently only receiving security updates. Support for 1.0.2
will end on 31st December 2019.

**Comment by alcroito** [comment]
Would like to chime in and say that Qt 6 built with CMake would also benefit from having openssl 1.1 in vcpkg, instead of forcing users to download and install a package manually.

**Comment by barcharcraz** [comment]
This is a blocking issue for me, I'm using conan instead of vcpkg because of this.

It's also a bit of a blocking issue for the azure-c-sdk team.

**Comment by dilin-MS** [comment]
Hi, any update on openssl exposing option to override version instead of hardcoded to 1.0.2s?

We rely on azure iot c sdk which depends on openssl. This openssl vcpkg hardcoded to 1.0.2 cause azure iot c sdk to be unable to be compiled with openssl 1.1.1.  ([Cross-compile application with openssl 1.0.2 fails in openssl 1.1.1 environment #1341](https://github.com/Azure/azure-iot-sdk-c/issues/1341))

Any plan or update on enabling openssl 1.1.1? Thanks!

**Comment by fcharlie** [comment]
@dilin-MS 

See: https://github.com/microsoft/vcpkg/pull/8566

Some ports have not been migrated and upgrade to openssl 1.1.1 is blocked

**Comment by SilviuArdelean** [comment]
Looking forward to see the **vcpkg** based on **openSSL 1.1.1+**.
Accidentally, it caused me some headaches the last period.
https://silviuardelean.ro/2019/12/14/openssl-vs-vcpkg-some-strange-experiences/

**Comment by qis** [comment]
> I think this calls for splitting the openssl package into a 1.0.x and 1.1.x branch. The API changed considerably in 1.1.x and older applications must be updated...

Stalling this issue solved the problem of requiring to split it into two versioned ports. The best course of action would be to just merge it and fix remaining problems afterwards.

Since I don't believe that there will be any major development done in the next 46 hours, which you have left until 1.0 is officially unsupported anymore, you **could** just merge it and be done with it!

**Comment by dhkatz** [comment]
Was going to write a port for Valve's [GameNetworkingSockets](https://github.com/ValveSoftware/GameNetworkingSockets) but the build fails because it requires at least OpenSSL 1.1.0. 

This is just going to end up causing more and more problems for upgrading and adding new ports in the future the longer OpenSSL isn't updated.

**Comment by JackBoosY** [comment]
If the interface changes too much after openssl update, I think it is better to create a new port name `openssl1_1`.

**Comment by qis** [comment]
> If the interface changes too much after openssl update, I think it is better to create a new port name `openssl1_1`.

@JackBoosY I strongly disagree and urge you not to do it! This is not a simple major release!

Using OpenSSL 1.0 from now on is not only a bad choice, it's outright dangerous for both, developer and his customers. Leaving it as the default and requiring the user to tag 1_1 will result in tragedy (lost money, lost reputation, lawsuits, etc.).

Look at Linux distros: they didn't add OpenSSL 1.1 - they replaced OpenSSL and added OpenSSL 1.0:

```
openssl/bionic-updates,bionic-security,now 1.1.1-1ubuntu2.1~18.04.4 amd64 [installed,automatic]
  Secure Sockets Layer toolkit - cryptographic utility

openssl1.0/bionic-updates,bionic-security 1.0.2n-1ubuntu5.3 amd64
  Secure Sockets Layer toolkit 1.0 - cryptographic utility
```

**Comment by JackBoosY** [comment]
@qis If we completely upgrade openssl without keeping the old version, we must fix many ports that currently do NOT support openssl 1.1.
Updates for each port in vcpkg must be compatible with ports that depend on it.

**Comment by dhkatz** [comment]
But library maintainers have known for over a year that OpenSSL was ending its support for 1.0.2. 1.0.2 ended main LTS support in 2018! It was only receiving security updates in 2019.

As the main post shows, a lot more ports support 1.1.1 than don't. So many newer ports would also probably require at least 1.1.0. I don't see the point of holding back this change for a few stragglers.

**Comment by jozefizso** [comment]
The package name should stay **openssl**.

As 1.0 is totally unsupported now, it does not make sense to build other packages against such version.

Does somebody really compile for outdated security library? They can checkout earlier git release and/or maintain their own local version.

PS: we must maintain local version of openssl 1.1 because vcpkg was not able to provide the most recent release for several months now. And this is huge pain for us.

**Comment by fcharlie** [comment]
@jozefizso This is actually a common problem with package management software, and specific software packages are always difficult to upgrade in time. Actually when I use openssl, I always manually build from source.

**Comment by qis** [comment]
@jozefizso I think you misunderstood dhkatz - you two argue for the same outcome.
@fcharlie We currently use the PR to build OpenSSL with vcpkg and it works quite well:

```
git clone git@github.com:microsoft/vcpkg && cd vcpkg
git remote add neumann git@github.com:neumann-a/vcpkg
git fetch neumann
git merge --strategy-option theirs neumann/libpq_with_openssl_111d
```

**Comment by JackBoosY** [comment]
I hope #8566 can solve these problems completely.

**Comment by MikeGitb** [comment]
Here is another vote for upgrading the openssl package. If absolutely necessary add a openssl-1.0 package, but don't let the unsupported version stay the default.

The other way around only creates more work (first pointing compatible packages to 1.1 and then back to main), more people with insecure software configurations and less visibility of the problem.

**Comment by dhkatz** [comment]
Just because I care so much I decided to go through every single port that depended on OpenSSL in some way and check if it had support for OpenSSL > 1.1

I wouldn't consider this an extremely thorough search, but I my process was essentially:

* Check the README for mentions of OpenSSL version
* Check the code for mentions of OpenSSL version or function calls
* Check commit and PR history for addition of 1.1 support

Any port with a check I'm *pretty sure* will support 1.1, and with a question I couldn't really tell but nothing suggests it wouldn't work. Any port with an X, I believe may not work due the age of the library and its use of OpenSSL.

Port| OpenSSL 1.1 Support
:-----:|:-----:
ace| ✔️
amqpcpp| ✔️
apr-util| ✔️
aws-sdk-cpp| ✔️
azure-c-shared-utility| ✔️
boost-asio| ✔️
caf| ✔️
cppcms| ✔️
cppfs| ❔
cpprestsdk| ✔️
curl| ✔️
evpp| ❌
fastrtps| ✔️
ffmpeg| ✔️
fizz| ✔️
fmi4cpp| ❔
folly| ✔️
freerdp| ✔️
freetds| ✔️
grpc| ✔️
hiredis| ❌
ixwebsocket| ❔
libarchive| ✔️
libevent| ✔️
libgit2| ✔️
libimobiledevice| ❔
libmysql| ✔️
libnice| ❔
libpq| ✔️
librabbitmq| ✔️
librdkafka| ✔️
librtmp| ❔
libsrt| ✔️
libssh| ✔️
libssh2| ✔️
libtorrent| ✔️
libu2f-server| ✔️
libwebsockets| ✔️
libzip| ✔️
live555| ❔
mongo-c-driver| ✔️
mongoose| ✔️
mosquitto| ✔️
msix| ❔
nmap| ✔️
opendnp3| ✔️
openscap| ❔
opusfile| ✔️
paho-mqtt| ✔️
paho-mqttpp3| ❔
podofo| ✔️
ppconsul| ✔️
proxygen| ✔️
python3| ✔️
qpid-proton| ✔️
qt5-base| ✔️
quickfix| ✔️
restbed| ✔️
signalrclient| ❔
slikenet| ❔
thrift| ✔️
wampcc| ✔️
wangle| ✔️
websocketpp| ✔️
wt| ✔️
xeus| ✔️
xmlsec| ✔️
yara| ✔️

**Comment by dhkatz** [comment]
Have started checking each port individually to see if the current port needs to be updated to support OpenSSL 1.1+

**Comment by JackBoosY** [comment]
@dhkatz So, at least we need to support openssl 1.1.

**Comment by dhkatz** [comment]
@JackBoosY As was mentioned in the original post OpenSSL 1.1.1 is API and ABI compliant with OpenSSL 1.1.0. Any library that has added support for at least 1.1.0 will also support 1.1.1

**Comment by JunielKatarn** [comment]
@fcharlie Does your port build successfully?

**Comment by fcharlie** [comment]
@JunielKatarn I have closed it because there is better: https://github.com/microsoft/vcpkg/pull/8566

**Comment by JackBoosY** [comment]
OpenSSl has been updated in #8566, thank you for your contribution, can I close this PR now?

**Comment by fcharlie** [comment]
@JackBoosY I close this issue now
