### ISSUE TITLE
Add Microsoft MPI

### ISSUE THREAD

**Issue by vmaks** [Microsoft/vcpkg#429]
Hi!

It would be great if you add Microsoft MPI.

Link:
https://www.microsoft.com/en-us/download/details.aspx?id=41634

Thanks in advance!

**Comment by albertziegenhagel** [comment]
Microsoft MPI is distributed as binaries only and the source code is not available. The most recent version can usually be found at https://msdn.microsoft.com/en-us/library/bb524831(v=vs.85).aspx and currently is 7.1 (available at https://www.microsoft.com/en-us/download/details.aspx?id=52981).

The problem that I encountered is that the binaries are redistributed via installers only and a simple archive to extract is not available. There are two installers 'msmpisdk.msi' which includes the developer components (*.lib and header files) and 'MSMpiSetup.exe' which includes the runtime components (*.dll and mpiexec.exe).

I was able to create a portfile that downloads the developer tools and extracts those by using 'msiexec' (which should be available on any windows machine?!) but I was not able to extract the runtime components without installing it (which i don't think is desired since it adds registry entries and may have conflicts if the msmpi runtime has been installed on the machine already.). In general the developer components are sufficient to compile any library that depends on msmpi but executing those files would still require the runtime components to be available.

Currently I do have the runtime components installed system-wide on my machine, but this comes with the risk that the versions of the runtime and the developer components do not match. I solution where the runtime is installed in the vcpkg directories would be preferred.

Does anyone have a solution or knows how to extract an .exe installer without installing it and without relying on tools like 7z (which itself has to be installed system-wide?)

Or is the current solution that installs the developer tools only sufficient enough and I should submit a pull request for the port?

**Comment by alexkaratarakis** [comment]
If you require 7zip to do the extract, you can check for the existence of 7zip. If it is not installed, you can either:
1) fail the build and ask the user to install it
2) download a portable version of it (recommended). 

We do this for various tools that are needed in order to perform the build (and are not required for the library's functionality after the build). 

Take a look at `scripts\vcpkg_find_acquire_program.cmake`. 
PYTHON2 uses option 1. Everything else uses option 2. 
I think it would be reasonable to add 7zip there.
