### ISSUE TITLE
vcpkg not copying DLLs to target directory

### ISSUE THREAD

**Issue by tobbi** [microsoft/vcpkg#4311]
We're using vcpkg for installing all of our dependencies. Yet, when we compile it, it shows that most of the DLLs are missing from the final executable.

Here's the output from wine:
```
002a:err:module:import_dll Library SDL2_image.dll (which is needed by L"C:\\Program Files\\SuperTux\\bin\\supertux2.exe") not found
002a:err:module:import_dll Library libpng16.dll (which is needed by L"C:\\Program Files\\SuperTux\\bin\\supertux2.exe") not found
002a:err:module:import_dll Library vorbisfile.dll (which is needed by L"C:\\Program Files\\SuperTux\\bin\\supertux2.exe") not found
002a:err:module:import_dll Library boost_filesystem-vc140-mt-x32-1_68.dll (which is needed by L"C:\\Program Files\\SuperTux\\bin\\supertux2.exe") not found
002a:err:module:import_dll Library boost_date_time-vc140-mt-x32-1_68.dll (which is needed by L"C:\\Program Files\\SuperTux\\bin\\supertux2.exe") not found
002a:err:module:import_dll Library boost_locale-vc140-mt-x32-1_68.dll (which is needed by L"C:\\Program Files\\SuperTux\\bin\\supertux2.exe") not found
002a:err:module:import_dll Library glew32.dll (which is needed by L"C:\\Program Files\\SuperTux\\bin\\supertux2.exe") not found
002a:err:module:import_dll Library libcurl-d.dll (which is needed by L"C:\\Program Files\\SuperTux\\bin\\supertux2.exe") not found
002a:err:module:attach_dlls Importing dlls for L"C:\\Program Files\\SuperTux\\bin\\supertux2.exe" failed, status c0000135
```

Here's the code:
https://github.com/SuperTux/supertux/compare/appveyor-vcpkg

If you have any ideas, please let me know.

**Comment by ras0219-msft** [comment]
Thanks for letting us know!

I suspect the issue is that we don't currently add your dependencies to the `make install` target; however, we should be copying them to the executable output folder. If you were to try to run the executable from the output folder instead of after the `make install`, I believe it should work (though I understand that you want `make install` to work as well :)).

First, the obvious suggestion: have you considered static linking? All you need to do is modify the `C:\tools\vcpkg\triplets\x64-windows.cmake` file to have `set(VCPKG_LIBRARY_LINKAGE static)` and clear your appveyor cache. When you build the libraries again, they will be built statically. I'd recommend something like [1]:
```
cache:
  - C:\tools\vcpkg\installed -> .appveyor.yml
```

If you'd like to use DLLs instead, you'll need to add installation steps for the DLLs manually. This will look probably look something like
```
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/SDL2_image.dll ... DESTINATION bin)
```
However you may experience issues with `make` not knowing how to build the dlls. In that case, you'll need to create a fake custom command[2] that depends on your main build and claims to produce the DLLs (though they'll truly be created by a `POST_BUILD` action on your main `add_executable()` call).

I'd strongly recommend first trying the static build route :).

[1] https://www.appveyor.com/docs/build-cache/#cleaning-up-cache
[2] https://cmake.org/cmake/help/latest/command/add_custom_command.html

**Comment by tobbi** [comment]
Thanks for the pointers so far, I made the necessary changes so that it copies custom triplet files to the necessary directories. However, upon linking, I now get this error:
```
LINK : fatal error LNK1149: output filename matches input filename 'C:\projects\supertux-9ml4d\Release\supertux2.lib' [C:\projects\supertux-9ml4d\supertux2.vcxproj]
```
as can be found here: https://ci.appveyor.com/project/supertux/supertux-9ml4d/build/2607

**Comment by ras0219-msft** [comment]
I'm almost certain that the issue is caused by setting the outputs of your executable and library to be the same[1]. However, assuming this worked before, this is most likely due to a bug in one of the vcpkg-built libraries that has declared something as `dllexport` while being built statically.

This can be immediately worked around by just commenting out those two lines, I believe. Assuming that fixes things, and assuming we do indeed have a bug, there will be a `supertux2.lib` AND `supertux2_lib.lib` created. In this case, if you can run `dumpbin /exports supertux2.lib` it will tell us exactly which dependency is misbehaving so we can fix it upstream here in vcpkg.

[1] https://github.com/SuperTux/supertux/blob/4013f7ff548f95cc22adc88288ea46303dee2788/CMakeLists.txt#L635-L636

**Comment by tobbi** [comment]
When I do that, I keep getting linter errors en masse: https://pastebin.com/GYY6e2rd

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.

**Comment by Triasmus** [comment]
This is still a problem for me.

Making it static by modifying 'x64-windows.cmake' to `set(VCPKG_LIBRARY_LINKAGE static)` did "solve" it, but I don't really consider having to modify my vcpkg submodule a proper solution (multiple devs working on the project all have to manually do the same modification, or we can fork vcpkg and use a branch in our fork, or continue to manually copy the dlls when building on windows.... I'm not a fan of any option).

I did attempt
```
include(vcpkg/scripts/buildsystems/vcpkg.cmake)
set(VCPKG_LIBRARY_LINKAGE static)
```
in my toplevel `CMakeLists.txt`, but that didn't work :(

Note: I seem to recall that there's a way to specify a triplet. That doesn't work in my case because my project is multiplatform. (I spent a lot of time attempting to make Windows static while still being able to build on Linux when I first started using vcpkg. It _is_ nice to finally have an _alright_ way to do that)

**Comment by dg0yt** [comment]
@Triasmus You are *not* facing the same problem. Open a new issue with a proper description please.

**Comment by Triasmus** [comment]
Oh sorry, the first response described my problem
> I suspect the issue is that we don't currently add your dependencies to the make install target; however, we should be copying them to the executable output folder. If you were to try to run the executable from the output folder instead of after the make install, I believe it should work (though I understand that you want make install to work as well :)).

so I figured that's what this issue is about.

**Comment by dg0yt** [comment]
... where "currently" was in 2018, and #26397 is for correctly using CMake's `BundleUtilities`. 
There are other ways to go wrong (e.g. plugins). That's why I wrote: Open a new issue with a proper description please.
