### ISSUE TITLE
Error: Building package zeromq:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by mtorkashvand** [Microsoft/vcpkg#4318]
[config-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/2403209/config-x64-windows-out.log)

  Package: zeromq:x64-windows
  Vcpkg version: 0.0.113-nohash

**Comment by mtorkashvand** [comment]
I have tried installing different versions of Cmake and it didn't help.
I also saw in another issue that it was suggested to use 
```
choco install ninja 

``` 
and it didn't help

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

This is specifically caused by a misbehavior in the zeromq port with spaces in the source path. The best immediate workaround for this (which will also fix many other libraries) is to make sure there are no spaces in your vcpkg path.

I'd recommend something like `C:\src\vcpkg`, which will also avoid max path length issues when building things like Qt.

**Comment by Voskrese** [comment]
`"C:/Users/dragonfly/Documents/Git Repositories/vcpkg/downloads/tools/cmake-3.11.4-windows/cmake-3.11.4-win32-x86/bin/cmake.exe" "C:/Users/dragonfly/Documents/Git Repositories/vcpkg/buildtrees/zeromq/src/a44e6fad0e-d531ae760a" "-DZMQ_BUILD_TESTS=OFF" "-DPOLLER=select" "-DBUILD_STATIC=0" "-DBUILD_SHARED=1" "-DWITH_PERF_TOOL=OFF" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/dragonfly/Documents/Git Repositories/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/dragonfly/Documents/Git Repositories/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS= "-IC:/Users/dragonfly/Documents/Git Repositories/vcpkg/buildtrees/zeromq/src/a44e6fad0e-d531ae760a/builds/msvc"" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS= "-IC:/Users/dragonfly/Documents/Git Repositories/vcpkg/buildtrees/zeromq/src/a44e6fad0e-d531ae760a/builds/msvc"" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/dragonfly/Documents/Git Repositories/vcpkg/packages/zeromq_x64-windows""`

`FAILED: ../CMakeCache.txt `

Error most likely due to spaces in paths and too long paths

**Comment by Voskrese** [comment]
@ras0219-msft  Why is the Ninja utility taken from MSVC is and not vcpkg?
`"-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe"`

**Comment by mtorkashvand** [comment]
@ras0219-msft  Thank you for your fast response. I changed vcpkg path to what you recommended. It is working now and I could install the libraries successfully.
