### ISSUE TITLE
[glew] CRT linkage is handled incorrectly

### ISSUE THREAD

**Issue by alexkaratarakis** [Microsoft/vcpkg#435]
Currently the CRT linkage is treated the same as the library linkage, but they are distinct. 
More information here: #342

**Comment by bangusi** [comment]
So this is an issue not just ro 'glew' for all libraries. Initially I thought the Vcpkg static builds meant I could link to a library static *also* I would get static linkage to the CRT.
For example, whenever I build  my boost libraries I use these options:
`--toolset=msvc-14.0  address-model=64 link=static threading=multi runtime-link=static ` 
OR
`--toolset=msvc-14.0 address-model=64 link=static threading=multi runtime-link=shared `
It looks like the Vcpkg build gives me neither of the two. But rather I am getting:
`--toolset=msvc-14.0 address-model=64 link=dynamic threading=multi runtime-link=static `
Correct?

**Comment by ras0219-msft** [comment]
Currently, the `*-windows-static` triplets request static library linkage AND static CRT linkage. This would be `link=static runtime-link=static` in your boost example[1]. The `*-windows` triplets ask for dynamic/shared. For CMake based libraries, we can automatically deal with this by changing the base compiler flags (see [2]), however MSBuild and custom libraries such as boost require special attention.

As an aside, if you'd like to have the "undesired" configuration, you could create a new file inside `triplets\` which sets `VCPKG_CRT_LINKAGE` and `VCPKG_LIBRARY_LINKAGE` appropriately.

[1] https://github.com/Microsoft/vcpkg/blob/45425fe6f01f45847679d27d169e9de37fad824c/ports/boost/portfile.cmake#L50
[2] https://github.com/Microsoft/vcpkg/blob/45425fe6f01f45847679d27d169e9de37fad824c/scripts/cmake/vcpkg_configure_cmake.cmake#L54

**Comment by bangusi** [comment]
@ras0219-msft 
Your statement :
>  Currently, the *-windows-static triplets request static library linkage AND static CRT linkage. This would be link=static runtime-link=static in your boost example[1].

Is not entirely correct. I have just re-built my vcpkg and installed `boost:x64-windows `and `boost:x64-windows-static` only. 
I have enabled integrate all
I then compiled this piece of code:
```
typedef boost::gregorian::date Date;
typedef boost::posix_time::ptime Timestamp;
typedef boost::posix_time::time_duration Interval;
void f0()
{
	std::string s("2017-01-10");
	Date dt = boost::gregorian::from_simple_string(s);
	std::cout << dt << std::endl;
	Timestamp temp(dt, Interval(23, 59, 59));
	std::cout << temp << std::endl;
}
int main()
{
	f0();
	return  0;
}
```
In my project settings / code generation I used /MT switch.
The produced executable is not statically linked to boost static. The file boost_date_time-vc140-mt-1_62.dll is required in order to run my executable which is not what I was expecting.

When I look at the link command line I see, it is using `D:\vcpkg\installed\x64-windows\lib` instead of
`D:\vcpkg\installed\x64-windows-static\lib` Could the problem be in the way the integration is done perhaps?

**Comment by ras0219-msft** [comment]
Yes, this is an issue with the automatic triplet selection for system wide integration. Essentially, due to the way that msbuild represents the /MT switch, we can't use it during the triplet determination. Therefore, by default, you will always get x64-windows.

To change this, you just need to add an msbuild property to override the triplet selection in your project. I believe the property is "VcpkgTriplet", it should be listed in the vcblog post about static linking. No GUI yet for this unfortunately.

**Comment by cdcseacave** [comment]
Everyone has different needs related to this topic. For example for me linking statically to both CRT and library is what I need, so the `x64-windows-static` behavior is fine. Creating a new triplet is trivial, and limiting them to only the current 8 versions is ok, otherwise it will become way too confusing.

What I think would be useful though is a way to configure `vcpkg` to set default triplet, and maybe automatically create a new triplet if the combination of options selected is missing.

**Comment by wangli28** [comment]
Hi everyone, Please open a new issue if this is still a problem for you.
Thanks.
