### ISSUE TITLE
vcpkg for Raspberry Pi

### ISSUE THREAD

**Issue by kenr** [microsoft/vcpkg#4406]
Are there any plans to support Raspberry Pi (RPi) 32-bit distributions as a target for vcpkg?

**Comment by Paco93** [comment]
I would be also interested in RPi support.

**Comment by YoDaMa** [comment]
Would also appreciate this feature for our team.

**Comment by heydojo** [comment]
> Are there any plans to support Raspberry Pi (RPi) 32-bit distributions as a target for vcpkg?

Which rpi variant? The latest one? Version 4?
Which target OS?

Is there something specifically unavailable for _"insert rpi Linux distro here"_ which vcpkg solves?
Just asking.
I'm not a big fan of this at all, as compiling software on a rpi is probably the last thing a sensible person would do with one. And ARM 32 is only really suitable for very low power devices at this point. Low power devices aren't running Windows. And compiling for rpi is done cross by everyone who understands the devices.

**Comment by mprather** [comment]
Couple of comments to an old thread but worth sharing, nonetheless. Vcpkg was working on RPi until recently (see #21142). Cross compilation is not an easy thing to get right nor is really truly realistic to expect that other packages are setup for that type of compilation. We build on a RPi 3B+ because our app relies on libraries that easily distributed via vcpkg. Further, we actually have that board incorporated into our Azure Devops pipelines. Our code that is used on Windows, Ubuntu, macOS, and RPi all get validated/tested and we can ensure that no mysterious cross issues sneak in. Works great. Much lower entry to use if you can build directly.
