### ISSUE TITLE
How does vcpkg work across VS 2015/2017 w.r.t. ABI compatibility, and what about packages that need VS 2017?

### ISSUE THREAD

**Issue by patrikhuber** [Microsoft/vcpkg#4453]
Hi!

I was wondering about a few things today:

1) According to [this Microsoft documentation](https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=vs-2017), ABI/binary compatibility is guaranteed (only) if packages are built with a lower (or equal) version of VS as the eventual application is built with. So e.g. a library compiled with 2017 is *not* ABI-compatible with 2015, according to that document. So I am wondering, if multiple VS versions and toolsets are installed on a machine, does vcpkg auto-select VS 2015? Or if only VS 2017 is installed, but with let's say the 14.11 and 14.15 toolsets, does it auto-select the lowest version? I can also imagine this becoming a larger problem if packages are exported and then copied to a different system or user. E.g. I build a library with the latest 14.15 toolset locally, and then export the package to some system that is still on 14.14.
I think it would be adequate to more clearly mark (or at least document) with which VS version a particular library has been compiled with.

2)
    a) How does vcpkg handle packages that need VS 2017, and don't compile with 2015? (Like libraries using some C++14 or C++17 features that didn't compile in VS 2015). Would they just fail on anyone's system that has only VS 2015 or a not high enough VS 2017 toolset version?

    b) What if a user has VS 2015 *and* VS 2017 installed, and then installs a package that needs >=2017? If vcpkg auto-selects VS 2015, it means the build will always fail? The same if a user has two toolsets of VS 2017 installed, e.g. 14.11 and 14.15, and a particular library needs 14.15 - will it just always fail?

Thanks!

**Comment by degski** [comment]
Is there a particular reason you are sticking with VS2015, to all intents and purposes, VS2017 is a minor upgrade from VS2015, nothing has been broken? As far as I know, vcpkg will select the latest version of VS, and will link to VS2015 stuff. But why would you like to have that laying around, it's inefficient [because the relevant STL is not up to scratch], has security issues and is just a pain in the bud. Also by making this an issue, you are holding the rest of us, from moving forward, coz you're dwelling in the past. Purposely, for a reason I cannot fathom, Boost f.e. is renamed as if it was compiled with VS2015. But generally, move on, uninstall VS2015, soon there will be VS2019, you just are creating yourself unnecessary trouble [Yes, I agree VC6 was great!].

**Comment by ras0219-msft** [comment]
We currently select the latest toolset in the v14x series, which means we will select the VS2017 that's installed. I think a) and b) have obvious answers given that decision.

Regarding that documentation, your interpretation is technically correct (with the nuance that the most important piece of that compatibility is that you may need to link the newest c++ runtime import library and use the newest linker). However, the probability of hitting an issue here is very small to begin with, and the vast majority of those issues are going to be due to the library using a feature of the new runtime -- one which would have prevented it from building with VS2015 in the first place. Therefore, selecting the "oldest" valid VS version available would not fix the problem, because VS2015 wouldn't have been valid anyway.

For example, if we add (say) the experimental filesystem TS in VS 2017 15.7, that would go into the import library of the C++ runtime from that VS version and forward. If you made a static library that uses the experimental filesystem TS, it obviously would need to link against those APIs, which wouldn't be present in previous versions.

We document our selection process here[1], as well as the triplet setting that you can use to specify which toolset to use.

[1] https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_platform_toolset

**Comment by degski** [comment]
@patrikhuber 

> Many clients are still on VS 2013 or 2015, and they don't, or can't, upgrade (yet) for a variety of reasons.

I can see a [bad] case for VS2013 [dinheiro probably], but I don't see that for VS2015. VS2017 was named as such to make it look less old [in 2018], but is really just a continuation of micro [and not so micro] upgrades from VS2015. This is also fully reflected in Robert's post. 

The interoperability of different compiler versions and language versions is far less than desired and/or assumed by C++ users [Robert alludes to that as well]. What has maybe been true in the past is no longer valid. You cannot mix linking to libraries compiled with different standards [and by implication different compilers].

Spectre like issues are being addressed in VS2017, for those security conscious people/organizations that seems to be a must. Doesn't VS2017 install Unreal [on demand], I presume it works.
