### ISSUE TITLE
Add GSoap

### ISSUE THREAD

**Issue by mostafaSataki** [Microsoft/vcpkg#4457]
Hi.
Please add GSoap library.

**Comment by JackBoos** [comment]
working...

**Comment by JackBoosY** [comment]
#5295

**Comment by martin-s** [comment]
I see currently three build setups:

1. - automake (see e.g. icu in a msys environment)
2. - src/MakefileManual, Make_mvc,mak (see e.g. gdal with make/nmake)
3. - VisualStudio 2005 (with the help of msbuild command)

Prerequisites/Dependencies are bison and flex. You can skip these with the option 3 in Visual Studio. Unfortunately, all these setups have to be adopted/patched, in order to be executed without errors.

**Comment by JackBoosY** [comment]
Hi @mostafaSataki , gsoap has been added in vcpkg. Enjoy it!
