### ISSUE TITLE
Add support for custom Solution Configurations

### ISSUE THREAD

**Issue by mikebmcl** [Microsoft/vcpkg#451]
I'm running Windows 10 Pro x64 10.0.14393 en-us.

Repro steps:

1. I install vcpkg and integrate it with system-wide integration.
2. I install the zlib port for x86-windows.
3. In Visual Studio 2017 RC Enterprise, I create a new empty solution for C++.
4. I add a file named main.cpp with the following contents:

```
#include <zlib.h>
#include <iostream>
 
int main()
{
    std::cout << zlibVersion();
    return EXIT_SUCCESS; // Place breakpoint here
}
```

5. Using Solution Manager, I create a new Solution Configuration named "Debug_ClangC2" with the settings copied from the "Debug" configuration.
6. In Project Properties, with Configuration set to "Debug_ClangC2" and Platform set to "Win32", under "Configuration Properties -> General" I set the Platform Toolset to "Visual Studio 2017 - Clang with Microsoft CodeGen (v141_clang_c2)" and then under "C/C++ -> General" I set the Warning Level to "EnableAllWarnings (-Wall)".
7. I build the solution using the "Debug" "Win32" configuration.
8. I change the "Debug" solution to use Clang/C2 as set forth in step 6 above.
9. I repeat step 7.
10. I build the solution using the "Debug_ClangC2" "Win32" configuration.
11. I add a new Visual C++ Property Sheets file named "PropertySheets.props" to the project.
12. I set the contents of Property Sheets.props to the following:

``

Expected outcome:

I expect the solution to build successfully in steps 7, 9, and 10.

Actual outcome:

The solution builds correctly in steps 7 and 9 but fails to build in step 10 with "LNK2019: unresolved external symbol _zlibVersion referenced in function _main" and "LNK1120: 1 unresolved externals".

The issue is that [https://github.com/Microsoft/vcpkg/blob/master/scripts/buildsystems/msbuild/vcpkg.targets](https://github.com/Microsoft/vcpkg/blob/master/scripts/buildsystems/msbuild/vcpkg.targets) is hard coded to only link vcpkg .lib files when the "$(VcpkgConfiguration)" is set to "Debug" or "Release", which value it takes from "$(Configuration)".

The desired resolution is either that vcpkg .lib files are linked regardless of the "$(Configuration)" name. A simple workaround in the meantime is highly desirable (e.g. an example of a property sheet that would provide a workaround).

**Comment by ras0219-msft** [comment]
The design of VcpkgConfiguration is that it will only use Configuration if you haven't overridden it. Therefore, you can add configurations of any name and add an MSBuild property sheet to conditionally set VcpkgConfiguration to the type of libs you'd like to link based on your configuration.

We could probably add some heuristics (configurations with "Debug" in them _probably_ want debug libs), but there are a lot of situations where that won't work. We unfortunately can't detect it automatically because of how the crt linkage is implemented in the C++ MSBuild (a per-item setting instead of a global property).

So, to restate: VcpkgConfiguration needs to be set to match your CRT rel/debug setting in order for the libs to link correctly. For custom configurations, you'll have to override it yourself.

**Comment by ras0219-msft** [comment]
Let me know if this didn't solve your issue.
