### ISSUE TITLE
gtk debugging is extremely slow

### ISSUE THREAD

**Issue by davetopia** [microsoft/vcpkg#4529]
Gtk3 registers a low level keyboard hook in gdkevents-win32.c which causes system-wide keyboard input to be unbearably slow when debugging is paused.  Stepping over `set_up_low_level_keyboard_hook` results in normal performance.  One potential solution is to check for the presence of a debugger before registering the hook.

**Comment by fungos** [comment]
@JackBoosY I think this should be closed. it is not a vcpkg issue. This is a GTK bug and should be reported to that project.

**Comment by bart-goossens** [comment]
The problem here is that the low level hook proc is interrupted by the debugger break. This causes the system wide keyboard input to be stalled, at least until the internal timeout is reached (the default timeout is around 5 seconds I believe, not very practical when debugging).
I found a workaround to this problem: set  [KEY_CURRENT_USER\Control Panel\Desktop\LowLevelHooksTimeout](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms644986(v=vs.85)?redirectedfrom=MSDN) DWORD value to 20 (corresponding to 20 msec). Then the delay when typing will not be longer than 20 msec. Changing the setting may require logging in again to have effect.
* First notice that this problem applies to any application that installs low level keyboard hooks.
* The solution for GTK would be not to use low level hooks at all, I don't know if it is feasible, but this issue would indeed belong to the GTK project.

Anyway, this issue seems unrelated to vcpkg and can be closed.

**Comment by JackBoosY** [comment]
Can you report this issue to the official?

Thanks.
