### ISSUE TITLE
nanodbc library obsolete  

### ISSUE THREAD

**Issue by ShreyasNirgude** [microsoft/vcpkg#4607]
The nanodbc library provided by vcpkg is obsolete which is causing several bugs and syntax errors in pre-compiled and build tested code. Spicifically inserting blob data is not possible.

**Comment by Farwaykorse** [comment]
To be fair, vcpkg contains the latest official release (v2.12.4) with a few additional patches.
But this is a release from 2016 with a rather large changelog above it.
The release of v2.13 is [underway](nanodbc/nanodbc#181),

My suggestion was to install the package from HEAD using `vcpkg install nanodbc --head`.
Pull request #4641 adds support for this.

While adding this, I encountered a potential issue:  
Vcpkg compiles the current release as a dynamic library, but [officially only static libraries are supported](nanodbc/nanodbc#13). (This might be the connected to your issues.)  
V2.13 (and HEAD) will only build as a static library.

@ShreyasNirgude Since I'm not a user of this library, I'd appreciate it if you'd test it.

**Comment by PhoebeHui** [comment]
@ShreyasNirgude, nanodbc has no new revision release from now, currently still be v2.12.4, you can use '.\vcpkg install nanodbc --head' to install latest source from master. We will upgrade it when it has new revision. Please reopen it if it still be an issue for you.
