### ISSUE TITLE
Force MSBuild (.sln, .vcxproj) to use embedded debug info (e.g. /Z7)

### ISSUE THREAD

**Issue by malkia** [microsoft/vcpkg#4613]
Some packages tend to setup custom PDB locations, hence "vcpkg" might not be able to pick them, thus storing the debug information "OldStyle" might be the best thing to do. E.g. your "/Z7" option.

Then there are packages, like directxtex, that are build using MSBuild, and while one can do various sed "s///g" tricks to patch it up, there is a more straightforward method of using Directory.build.props (and/or Directory.build.targets) file to achieve this. E.g. more documentation here: https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2017

So basically for DirectXTex, all I had to do was to place this file (Directory.build.props) in the "src/<version>" folder - e.g. "src/jul2018-abacbbcd72/Directory.build.props" with these contents:

```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup>
    <ClCompile>
      <DebugInformationFormat>OldStyle</DebugInformationFormat>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
```

What would be the best way to go with such patch? Should VCPKG itself be patched, or do it per package?

NOTE: DirectXTex would still include a .pdb reference to the file, but the debug information would be in the .obj/.lib file (that's because a

```<ProgramDataBaseFileName>$(IntDir)$(TargetName).pdb</ProgramDataBaseFileName>```

was specified in there, so not completely clean, but no actual .pdb files got regenerated.

**Comment by malkia** [comment]
In the mean time, I've found this trick, which ChakraCore is using (on a side note, having all ports file as local makes it real easy to dig for such things, workarounds, etc. So another BIG PLUS for vcpkg in that respect).

https://github.com/Microsoft/vcpkg/blob/master/ports/chakracore/portfile.cmake#L33
specifying this file: https://github.com/Microsoft/vcpkg/blob/master/ports/chakracore/no-warning-as-error.props

so I'll use this for my local directx patch, but not sure if I propose the same would be good, or just not have VCPKG to do it for all. Looks like there are 30 packages out there using "vcpkg_build_msbuild" so they might benefit too.

**Comment by PhoebeHui** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.

**Comment by nick42** [comment]
This is still an issue, for reference, but I've figured out a workaround.

The core issue which I had is that .pdb files are not copied with .lib files, so you get the dreaded "linking without debugging information" warnings. This is because vcpkg_copy_pdbs is kinda dumb, and only copies .pdb files for .dll's (not .lib's).

Workaround, as promised:

1. Add SKIP_CLEAN option to vcpkg_install_msbuild command
2. Add the following code (or variation) to the portfile.cmake for your library after the build:

```
if(NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "release")
    set(BUILD_TREE_PATH ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel)
    file(GLOB_RECURSE PDB_FILES ${BUILD_TREE_PATH}/*.pdb)
    if(PDB_FILES)
        file(COPY ${PDB_FILES} DESTINATION ${CURRENT_PACKAGES_DIR}/lib)
    endif()
endif()

if(NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
    set(BUILD_TREE_PATH ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg)
    file(GLOB_RECURSE PDB_FILES ${BUILD_TREE_PATH}/*.pdb)
    if(PDB_FILES)
        file(COPY ${PDB_FILES} DESTINATION ${CURRENT_PACKAGES_DIR}/debug/lib)
    endif()
endif()

```
3. Add vcpkg_clean_msbuild() to the bottom of the port file

Note: Code sorta exposes a leaky abstraction, since you need to pull the .pdb files from the msbuild script tree, but there doesn't appear to be a supported alternative method to fix the issue. Also, no promises this will work for all libraries, of course.

It might be nice to add an option/script to allow this via a simple option passed to vcpkg_install_msbuild(), but I'm not exactly important enough to make that type of change.
