### ISSUE TITLE
[New port request] libpmemobj-cpp, pmdk-convert

### ISSUE THREAD

**Issue by igchor** [microsoft/vcpkg#4683]
Please update PMDK to version 1.5

We would also like two more packages to be added:
- libpmemobj-cpp: https://github.com/pmem/libpmemobj-cpp
- pmdk-convert: https://github.com/pmem/pmdk-convert

**Comment by marcinslusarz** [comment]
PMDK maintainer here.

Is there any problem with updating PMDK? 1.5 performs much better than the version you have in the tree (1.4.2), especially on the recently launched Intel Optane DC Persistent Memory.

Since the request in November, we released PMDK 1.6 and libpmemobj-cpp 1.6, so I'd kindly ask you to update to this version.

There is one more aspect of this request: We recently found a critical bug affecting all PMDK versions on Windows, which means we will be releasing a new stable version soon. If possible, I'd like to limit the number of stable releases to just one (1.6.1), but if you will stay on the older line (1.4 or 1.5) we will have to release 1.5.2 and/or 1.4.3.

**Comment by wangli28** [comment]
Hi @igchor,
The latest version of pmdk is 1.6, you can update vcpkg and rebuild.
Thanks.

**Comment by marcinslusarz** [comment]
Thanks, @wangli28. There are a couple of problems with this update:
- libvmem.dll is no longer installed
- C++ headers are missing
- there's no way to convert pools created with pmdk < 1.5 to the vcpkg version

@igchor didn't communicate it clearly enough, but adding libpmemobj-cpp and pmdk-convert was crucial for the update. libpmemobj-cpp provides the headers that were removed in pmdk 1.5 and pmdk-convert provides conversion tool for pools created with pmdk < 1.5.

**Comment by ras0219-msft** [comment]
Thanks for the explanation @marcinslusarz, it really helps to have an author involved!

I've pushed #7098 which should fix the missing `libvmem.dll` issue. It also updates the separately-packaged c++ headers to 1.7.

Finally, vcpkg is a library manager for C and C++ developers, not a generic application distribution system. As far as I can tell, there's no unique library component to pmdk-convert (it just rebuilds pmdk), so that isn't suitable for vcpkg. Instead, we'd recommend users look to a dedicated application manager like Chocolatey, Apt, Homebrew, or otherwise to get utility applications.

**Comment by marcinslusarz** [comment]
Thanks for the fixes and updates. 

I understand that vcpkg is intended for libraries, but I'm not sure why do you guys want to artificially limit its scope.

You probably won't change this overnight :), so I'd like to ask you to make an exception for pmdk-convert. Before pmdk 1.5 the equivalent code of pmdk-convert was part of **pmempool** utility, shipped with pmdk. The code was quite convoluted and with the changes to libpmemobj made between 1.4 and 1.5, it would become a nightmare to maintain (we would basically have to forever maintain a fork of libpmemobj 1.4 in the same tree). So we made a decision to radically change the approach - add a new project that builds out of various versions of pmdk and replace the guts of "pmempool convert" subcommand with a call to pmdk-convert.

Even though pmdk-convert is a utility and not a library, application developers willing to provide an update path for older versions of their applications (and data created with those applications) will need to ship pmdk-convert along with libpmemobj.dll.

IOW, pmdk-convert being outside of pmdk repository doesn't make it a separate project and I think making it available through vcpkg makes some sense.

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
