### ISSUE TITLE
[Question] Switch Qt from Jom to nmake?

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#4692]
I have one PC (out of 3) where Jom consistently deadlocks (4 Jom process running without any progress for hours) within bigger builds of qt (e.g. qt5-base)

I would thus suggest to use nmake instead of jom to have a failproof mechanism for building qt.
(Of course I would also add /MP to CL to have reasonable build times)

**Comment by heydojo** [comment]
https://wiki.qt.io/Jom
http://code.qt.io/cgit/qt-labs/jom.git/

I can't confirm your issue here. 🤷‍♂
I have built qt using vcpkg (and in turn jom) numerous times.

Please try to:
Find the bug patch it and send the fix upstream.
Or
Speak to the MSVC guys and ask them if it underperforms for them and find out if it is an MSVC problem.
Or
Try jom from git.

https://code.qt.io/cgit/qt-labs/jom.git/tree/README
Did you try JOMFLAGS?

**Comment by Neumann-A** [comment]
> I can't confirm your issue here. 🤷‍♂
> I have built qt using vcpkg (and in turn jom) numerous times.

@heydojo:
I can only reproduce this issue on one of at least 5 machines where i already build qt5 using vcpkg. Unfortunally it hangs on my main desktop pc.... 

>Please try to:

I attached a debugger once and looked at the disassembly. It looks like a deadlock, one process/thread spins and the rest just waits without making any progress (And without debug symbol getting further is kind of impossible). Although the hang itself is reproducible the time it happens in the build is not. Meaning the build sometimes progresses further than other times. 
Since qt will be migrating to cmake it is probably not worth my time to investigate the issue in jom further and just switch to nmake.

**Comment by alcroito** [comment]
If anybody ever feels like tackling jom deadlocking, some investigation was done at https://bugreports.qt.io/browse/COIN-598?focusedCommentId=520710#comment-520710

**Comment by JackBoosY** [comment]
Now, we can manually set `VCPKG_QMAKE_USE_NMAKE` on _scripts/triplets.cmake_ to avoid this situation.
