### ISSUE TITLE
Poppler isn't available

### ISSUE THREAD

**Issue by RealLitb** [microsoft/vcpkg#4702]
Following the advice from MSDN, I want to recommend to add the "Poppler" PDF library, which uses CMake as buildsystem. Poppler supports rendering using Qt and Cairo, both of which are already available in vcpkg.

**Comment by ChaoJia** [comment]
I've created a port for poppler, available [here](https://github.com/ChaoJia/ports/tree/master/poppler). It has only been tested on Windows (x64, dynamic linkage). It would be nice if someone had the time to fully test it and make a PR.

**Comment by raffaem** [comment]
I support this issue

**Comment by Hideki2103** [comment]
Thank you for creating port-file.
When compiling with x86-windows, the following error occurred.
ｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰ
CMake Error at ports/poppler/portfile.cmake:72 (file):
  file RENAME failed to rename

    C:/vcpkg/packages/poppler_x86-windows/share/man

  to

    C:/vcpkg/packages/poppler_x86-windows/share/poppler/man

  because: File exists

Call Stack (most recent call first):
  scripts/ports.cmake:91 (include)


Error: Building package poppler:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: poppler:x86-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
ｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰ
I cannot solve this problem. I need help. Please let me know if you know. Thank you.

**Comment by ChaoJia** [comment]
@Hideki2103 I have no clue either. Maybe try this https://github.com/Microsoft/vcpkg/issues/4950: deleted the entire content under the folder `C:/vcpkg/downloads`, and reinstall?

**Comment by Hideki2103** [comment]
When compiling with x86-windows, the following error occurred.

-----------------------------------------------------------------------------
CMake Error at ports/poppler/portfile.cmake:72 (file):
  file RENAME failed to rename

    C:/vcpkg/packages/poppler_x64-windows/share/man

  to

    C:/vcpkg/packages/poppler_x64-windows/share/poppler/man

  because: File exists

Call Stack (most recent call first):
  scripts/ports.cmake:91 (include)


Error: Building package poppler:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: poppler:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
---------------------------------------------------------------------------------

**Comment by Hideki2103** [comment]
Thank you for your comment. I issued a Microsoft New Port Request. I'll try the method you gave me later because I have another library installed.

**Comment by Hideki2103** [comment]
Good evening. At last I installed the qt5 library in vcpkg and started working on the problem with the portfile.cmake file. We did not get satisfactory results as intermediate results. The build went through, but the poppler executable and poppler-qt5.lib and poppler-glib library files could not be generated. The port directory and package at that time will be attached. Please let me know if you know.
[poppler.zip](https://github.com/microsoft/vcpkg/files/3631345/poppler.zip)

**Comment by Hideki2103** [comment]
I deleted the contents of C: / vcpkg / downloads, but there was no change.

**Comment by ChaoJia** [comment]
@Hideki2103 Sorry I have no solution to your problem at the moment. But I'm considering making a new port for poppler 0.80 as soon as I find the time. I'll keep you posted.

**Comment by Hideki2103** [comment]
ご返事ありがとうございます。port-fileがアップロードされるのを気長に待ってます。自分もCMakeについて勉強して、いつかプロダクトに貢献できるよう頑張ります。

**Comment by ChaoJia** [comment]
@Hideki2103 Hi, finally I made new ports for poppler(v0.82.0) and poppler-data (v0.4.9). Despite that it failed all the tests (didn't get any useful information from build artifacts; seems fixing those problems is above my pay grade which is none, so I'll just leave it there), you can still manually download the port files and try it out. Please also update lcms portfile and (re)install it, otherwise LCMS2 could not be found. Feature `splash` has to be selected if you are not using `glib`. Please let me know if you have further questions or run into problems.

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!

**Comment by playgithub** [comment]
I have built project `poppler-cpp` successfully.

The dependents:

1. set TESTDATADIR in CMakeLists
`git clone git://git.freedesktop.org/git/poppler/test poppler-test.git`

2. `vckpg install freetype devil openjpeg libiconv`
BTW I installed some vcpkg's pkgs ahead, that might include other dependents, e.g. `gperf.exe`.

3. 'clang-format`
https://releases.llvm.org/download.html

**Comment by JackBoosY** [comment]
@playgithub Consider to open a PR to add it?

**Comment by playgithub** [comment]
@JackBoosY I'm learning it. Maybe later.

**Comment by kelteseth** [comment]
@playgithub would be cool if you can make a PR, it is one of the dependencies needed to build Krita via vcpkg :)
