### ISSUE TITLE
openssl build error

### ISSUE THREAD

**Issue by ghost** [microsoft/vcpkg#4706]
Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:74 (vcpkg_execute_required_process)
  scripts/ports.cmake:71 (include)

Error: Building package openssl-windows:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x86-windows
  Vcpkg version: 2018.10.20-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by gitlsl** [comment]
I have same issue 
PS E:\vsproject\vcpkg>  .\vcpkg.exe install openssl-windows
The following packages will be built and installed:
    openssl-windows[core]:x86-windows
Starting package 1/1: openssl-windows:x86-windows
Building package openssl-windows[core]:x86-windows...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
Please install the English language pack.
-- Using cached E:/vsproject/vcpkg/downloads/openssl-1.0.2q.tar.gz
-- Applying patch E:/vsproject/vcpkg/ports/openssl-windows/ConfigureIncludeQuotesFix.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch E:/vsproject/vcpkg/ports/openssl-windows/STRINGIFYPatch.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch E:/vsproject/vcpkg/ports/openssl-windows/EnableWinARM32.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch E:/vsproject/vcpkg/ports/openssl-windows/EmbedSymbolsInStaticLibsZ7.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configure x86-windows-rel
-- Configure x86-windows-rel done
-- Build x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: nmake;-f;ms\ntdll.mak;install
    Working Directory: E:/vsproject/vcpkg/buildtrees/openssl-windows/x86-windows-rel/openssl-1.0.2q
    See logs for more information:
      E:\vsproject\vcpkg\buildtrees\openssl-windows\build-x86-windows-rel-1-out.log
      E:\vsproject\vcpkg\buildtrees\openssl-windows\build-x86-windows-rel-1-err.log

Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:96 (vcpkg_execute_required_process)
  scripts/ports.cmake:71 (include)


Error: Building package openssl-windows:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
@gitlsl, could you attach E:\vsproject\vcpkg\buildtrees\openssl-windows\build-x86-windows-rel-1-out.log? I can't repro your issue, everything built successfully for me.

**Comment by PhoebeHui** [comment]
Please report a new issue and attach failure logs if this still be an problem for you.
