### ISSUE TITLE
Need per-pkg documentation

### ISSUE THREAD

**Issue by harrywye** [Microsoft/vcpkg#471]
As a new user to vcpkg (as well as to cmake), I find it a bit confusing to use vcpkg port packages. 

I've tried a few so far, and all seem to have different "install" behaviors. Some appear to copy over dll's to bin dir, and some don't. For some, I need to explicitly link the libs, and for some it doesn't seem necessary. What about include files? Some packages use find_package(), and some don't, etc. I am not sure if this is because of my unfamiliarity with cmake in general, or it's just the way it is. If it's not possible to "enforce" a consistent install behavior, I think we need an absolutely minimal doc for each package regarding how to get started. 

Is it an option to include some kind of INSTALL doc (just like CONTROL file) with each package?

**Comment by OlafvdSpek** [comment]
IMO the behaviour should be consistent..

Ideally you'd just #include the stuff you need and not require any 'manual' find-pkg stuff.

**Comment by harrywye** [comment]
@OlafvdSpek I absolutely agree with you.

But, it's not very clear to me what `vcpkg` is:    
(1) On Unix platform, for example, there are common shared lib and include directories, etc. And, if you follow the convention (as a library vendor, or as a developer), everything works seamlessly. Is that the model vcpkg is trying to follow?     
(2) For all modern package management systems, Python, Ruby, or .Net (Nuget), etc., no extra steps are necessary for pkg install, like configuring include/lib paths, etc. _It just works._ Is that also vcpkg's goal?

**Comment by adam4813** [comment]
For 2. vcpkg install ... is all it takes to install a package.

As for 1 currently the license/copyright file is copied over into the installed directory. Perhaps making some form of symlink to the documentation such as a doc/ folder would be beneficial, during the install step?

**Comment by alexkaratarakis** [comment]
In contrast to other languages, C++ has many many build systems. CMake, autotools, make, custom build systems (e.g. boost). Even if you are using the same system, different project might specify different flags to do the same thing. For example, a differently named flag to specify whether you want static or dynamic builds. 
Therefore, it is hard/impossible to have all the portfiles be "consistent".`vcpkg` IS the layer that is trying to make the situation consistent. As in, you can install available libraries with: `vcpkg install lib`

I would like to clarify the usage of the "install" term in case it is causing confusion.

> Building phase for zlib
Relevant folders: `downloads\`, `buildtrees\` and output in `packages\`
- Download the sources
- Apply patches if available
- Configure, build, "install".
"Install" in this context is placing the files in the prescribed hierarchy in the `packages\zlib-x86-windows` directory.

> Install phase for zlib
Relevant folders: `packages\` and output in `installed\`

Place the zlib files in the common and shared lib/include/directories under `installed\`.
The "Install" terms in the portfile have nothing to do with this part. 

Hence, the install phase is the same for all ports. It is the building part that is highly different between ports. Everything in the portfile only applies to the building phase. 

____

(1) Similarly to the Unix platform, `vcpkg` has common lib/include/dll directories (for example, take a look at `installed\x86-windows\`). The hierarchy is actually the same. 

(2) You need `vcpkg install` to be able to have a package available for use.
If you using Visual Studio, you need to `vcpkg integrate install` once. After that, all installed packages are available for you to use within VS, automatically. If you are using CMake, you need to provide a single toolchain file, for example `-DCMAKE_TOOLCHAIN_FILE=D:\src\vcpkg\scripts\buildsystems\vcpkg.cmake` (more [here](https://github.com/Microsoft/vcpkg/blob/master/docs/EXAMPLES.md#example-1-2-b)).

I would classify this as just-works, while still retaining the ability to specify which vcpkg installation to use (you can have multiple) instead of being forced to use a global one. But, you definitely don't need to specify include/lib etc paths.

**Comment by harrywye** [comment]
Thanks for the clarification, @alexkaratarakis. `vcpkg`, however, currently does not seem to behave as expected. 

> But, you definitely don't need to specify include/lib etc paths.

I used a new fresh machine to install vcpkg and tested it with one port package, boost, for example. Here are the steps:

1. Clone Microsoft/vcpkg into `C:\vcpkg`. 
1. `cd C:\vcpkg`.
1. Run `powershell -exec bypass scripts\bootstrap.ps1`.
1. `.\vcpkg integrate install`.
1. `.\vcpkg install boost` and `.\vcpkg install boost:x64-windows`.
1. Make sure everything went fine by checking install folders and run `.\vcpkg list`, etc.
1. Create a VC++ Win32 exe project in Visual Studio 2015 Update 3.
1. Try to include a boost header, say, `#include <boost/algorithm/string.hpp>` in the main cpp file.

* Result: Visual Studio fails to find the boost include file.
* Expected: _But, you definitely don't need to specify include/lib etc paths._

The behavior is the same with `cmake`. I need to explicitly specify `include_directories` to make it work, which should be unnecessary.

**Comment by harrywye** [comment]
Correction: I was using an old forked version of `vcpkg`.  After updating the repo, VS project include path was correctly updated (`%VCPKG_ROOT%include`). Still trying to figure out why it does not automatically work with `cmake`....

**Comment by adam4813** [comment]
You have to use the provide tool chain/build script file as per step 2 just
above.

**Comment by harrywye** [comment]
I do use the tool chain file, I think.

	C:\Projects\vcpkgs\port-boost\build-x86>cmake -G "Visual Studio 15 2017" -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%scripts\buildsystems\vcpkg.cmake ..\source
	-- The C compiler identification is MSVC 19.10.24728.0
	-- The CXX compiler identification is MSVC 19.10.24728.0
	-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.24728/bin/HostX86/x86/cl.exe
	-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.24728/bin/HostX86/x86/cl.exe -- works
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.24728/bin/HostX86/x86/cl.exe
	-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.24728/bin/HostX86/x86/cl.exe -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Detecting CXX compile features
	-- Detecting CXX compile features - done
	-- Boost version: 1.62.0
	>> Boost_ROOT =
	>> Boost_INCLUDE_DIR = C:/vcpkg/installed/x86-windows/include
	-- Configuring done
	-- Generating done
	-- Build files have been written to: C:/Projects/vcpkgs/port-boost/build-x86

The generated sln/proj file does not have the include path correctly set. If I use "CMake Tools for Visual Studio" (with the cmake tool chain file specified in `CMakeSettings.json`), I get the same error. The only way I can make this work at this point is to explicitly set `include_directories` in the `CMakeLists.txt` file...

**Comment by ras0219-msft** [comment]
#### CMake behavior
We chose not to have the same behavior with CMake as we have with MSBuild (w.r.t. automatic linking) because we wanted to follow the "conventions" and design of CMake, which is to (as far as possible) give you an identical experience across platforms. This means you generally would need to call `find_package()`, `find_library()`, and `find_path()` to locate your dependencies, then manually link them to the projects you want them available in.

I think it's a debatable point about whether CMake "intends" for header only packages to be automatically available without configuration (i.e. whether `include_directories` has already been called), but it's certainly true that on Linux and OSX you typically don't need to do this. We would therefore like to do it by default, however there is actually a technical issue here: I couldn't find a way to add the include path to the _end_ of the compiler command line. This means that whereas most projects would expect their calls to `include_directories()` to _override_ the system include path, we wouldn't have that behavior.

This actually did break local builds of `cpprestsdk` -- it would pick up the vcpkg copy of cpprestsdk instead of the local include folders.

Thus, you currently must call the above directives to correctly set your CMake settings. For example, you'll have to add `include_directories(${Boost_INCLUDE_DIR})` after calling `find_package(Boost)`. This fortunately is the more "sanitary" way to use CMake anyway if you are publishing as open source for other platforms, because this enables users to provide a custom-built boost instead of only using the system one.

If you would prefer to have the MSBuild behavior when using CMake, please let us know in a separate issue! The most important thing is to have a comfortable and productive user experience.

#### MSBuild behavior
The ideal MSBuild behavior is _exactly_ what you described for "modern" managers: you just install the package, then it's simply a `#include` away -- no fussing with linker inputs or include paths. We're able to provide this experience for most packages automatically, regardless of what buildsystem they come from.

However, there is one really nasty thorn that causes headaches: frameworks that want to provide `main()` for you. This is surprisingly common (SDL2, gtest, boost test, and more), and it implies that you **must make a choice at link time** -- we can't automatically figure out what you wanted! For these, you do have to specify the choice on the link line (See #306 and #352 for detailed accounts of the problems these cause). We have implemented this using a special subdirectory under the `lib\` directory that contains these "mutually-exclusive" libraries. They are available on the msbuild linker path, which means you can choose to use one by adding it to your project's AdditionalDependencies property.

Hope this helps. Let me know if this is unclear at all :).

**Comment by OlafvdSpek** [comment]
IMO `find_package` is kinda annoying, personally I don't use it on Linux: https://github.com/OlafvdSpek/xbt/blob/master/Tracker/CMakeLists.txt

Has a cmake issue been filed for the `include_directories()` issue?

**Comment by harrywye** [comment]
Thanks for the elaboration, @ras0219-msft. I think it's really a matter of "expectation". I was initially rather confused, but now that I know a bit better in terms of what to expect, things definitely make more sense to me now. Thanks. So, I guess the answer to the question "do we need a per-pkg documentation?" would be "no"? :)
