### ISSUE TITLE
Targets are being ommited in grpc build

### ISSUE THREAD

**Issue by rishikant-sharma** [microsoft/vcpkg#4890]
**The machine setup:** Windows 10 Pro

**Steps to reproduce:** vcpkg install grpc

**Expected Outcome:** Successfully installed grpc

**Actual Outcome:**
The package grpc:x64-windows provides CMake targets:

    find_package(gRPC CONFIG REQUIRED)
    # Note: 8 target(s) were omitted.
    target_link_libraries(main PRIVATE gRPC::gpr gRPC::grpc gRPC::grpc++ gRPC::grpc_cronet)

**Comment by NancyLi1013** [comment]
Hi @rishikant-sharma, thanks for posting this issue. The result you listed above is expected. These messages are the usage that tells users how to use this port. In fact, this port is installed successfully.

**Comment by atimholt** [comment]
What does the “target(s) were omitted” message mean? The google search “`vcpkg "target(s) were omitted"`” reveals a total of 31 (totally irrelevant) results on the entire internet. I thought it might make sense to ask here, just because it is an existing issue based on the same confusion that brought me here.

**Comment by NancyLi1013** [comment]
Hi @atimholt 

If the package has more than 4 targets that need to link, it will only show four targets in the usage info. And the rests will be omitted.

Please refer to these codes here.
https://github.com/microsoft/vcpkg/blob/master/toolsrc/src/vcpkg/install.cpp#L731
