### ISSUE TITLE
[fmt] fmt 5.2.1: Entry Point Not Found error

### ISSUE THREAD

**Issue by ChewyGumball** [Microsoft/vcpkg#5133]
When trying to run my program built in release mode using fmt 5.2.1, I get a crash dialog with the following error:
`The procedure entry point ?ZERO_OR_POWERS_OF_10_32@?$basic_data@X@internal@v5@fmt@@2QBIB could not be located in the dynamic link library {path to my executable}`
I get no build errors, or vcpkg installation errors. I have tried removing and reinstalling the package.
If I build using debug mode, I do not get this error. This is the first time I have run my program in release mode, so I don't know if this is a new problem or not. 

I am running Microsoft Windows 10 Pro 10.0.17134, and Visual Studio v15.9.4

I tried to reproduce this in a new project, but was unable to. The project properties are identical for both the broken and working project (from looking at the vcproj files). I am probably using some part of the library in the broken project which requires that procedure that I wasn't in the working one.

**Comment by SuperWig** [comment]
I get something similar with fmt::sprintf and fmt 5.3.0.

The procedure entry point `??$sprintf_format@N@internal@v5@fmt@YAXNAEAV?$basic_buffer@D@012@Ucore_format_specs@12@@Z` could not be located in the dynamic link library.

I'm unable to run the spdlog example from their README due to this.

**Comment by PureRonin** [comment]
@ChewyGumball So I had something similar happen, getting the Entry Point Not Found error.

I was using CMake to generate the project. Project was working correctly and then I updated VCPKG to pick up the latest fmt, fmt package built without errors. Re-configure my CMake project and it appears to work correctly but I started getting the "The procedure entry point {mangled function name} could not be found in the dynamic link library". I did a new cmake build in a new folder and everything worked correctly.

Diffing between my two cmake build directories, I found that the path to the linker was cached. Since I'd originally ran the CMake configuration I have updated Visual Studio. The broken build directory was using the old linker, the working build directory was using the current linker. 

Broken CMakeCache.txt contains:
```
//Path to a program.
CMAKE_LINKER:FILEPATH=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/link.exe
```
Working CMakeCache.txt contains:
```
//Path to a program.
CMAKE_LINKER:FILEPATH=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/link.exe
```

There isn't any forward compatibility guarantee with MSVC's linker so I'm guessing that might be the problem.

**Comment by SuperWig** [comment]
Thanks for this. Reinstalled Windows recently (new sdd) and just checked fmt::sprintf and spdlog and both seem to work without problems now.

**Comment by MikeGitb** [comment]
Can someone confirm that this is not a port bug, but a problem with not clearing the cmake cache?

**Comment by PureRonin** [comment]
Hey Mike,
I can confirm that when it happened to me it was a problem with a stale cmakecache.txt
PR

**Comment by SuperWig** [comment]
I was using Visual Studio so I assume it's a similar issue?

**Comment by SuperWig** [comment]
Forgot to update that I don't still have the issue on my laptop so 🤷‍♂️

**Comment by MikeGitb** [comment]
@ChewyGumball: If the problem is solved for you as well, maybe you can close the issue?

Disclaimer: I'm not a member of vcpkg or microsoft, but I think it would be great, if we could reduce the numer of stale issues at the vcpkg repository.

**Comment by ChewyGumball** [comment]
I "solved" the problem in that I no longer have it. I don't know what exactly was the issue, as I am not using a CMake file to generate my project. I'm going to close because I am pretty sure it is not a problem with fmt in vcpkg, but some caching problem somewhere when updating visual studio.

**Comment by JackBoosY** [comment]
Hi All, since #5688 merged, this issue cannot repro anymore.
