### ISSUE TITLE
Include sha as part of version during build

### ISSUE THREAD

**Issue by sgrebnov** [microsoft/vcpkg#5257]
I've noticed that due to the following change SHA has been removed from package version.
https://github.com/Microsoft/vcpkg/commit/f1653a23d5a4a1f4ce8b4d034594526a649de0d1

We build and install vcpkg from master and always want to know what particular version we used to build. Is there any information wrt reason for this change? I volunteer to help fixing this

**Comment by Rastaban** [comment]
The SHA was removed because we were concerned that it could be used as personal identifiable information in the user statistics that are collected.  We would happily accept a PR that adds the SHA back to the package version as long it it is stripped back off when usage data is uploaded.  Stripping it back off should be as simple as removing everything after a '-' in the version string.

**Comment by PhoebeHui** [comment]
@sgrebnov, feel free to summit a PR if you want.
