### ISSUE TITLE
Change default triplet

### ISSUE THREAD

**Issue by alzie** [Microsoft/vcpkg#53]
The default triplet is "x86-windows".

Since we mainly develop very memory demanding applications, I build all libraries for x64. This means I always have to use "vcpkg install boost:x64-windows" etc. It would be very convenient to make it possible to let the user set a default triplet that is then used when building any package.

**Comment by Ninetainedo** [comment]
If you install everything at once, you can use `--triplet x64-windows` to save yourself some typing.

**Comment by ras0219-msft** [comment]
Would an environment variable work?

Something like `VCPKG_DEFAULT_TRIPLET` or `VCPKG_TRIPLET`?

**Comment by alzie** [comment]
I think an environment variable would be great.

**Comment by Kwizatz** [comment]
Sooner or later the need for a config file will arise. Why wait?

**Comment by MikeGitb** [comment]
The Question about the individual configuration aside: Shouldn't the default be x64 anyway?

**Comment by ras0219-msft** [comment]
@MikeGitb The reason to use `x86-windows` as the default triplet is to make the new user experience as absolutely streamlined as possible: Visual Studio defaults to x86 for new projects and remembering to change the architecture is one of those tiny details that's easy to overlook even for experts.

@Kwizatz You're absolutely right, we will certainly need a config file eventually. However, I'd like to accumulate as many concrete use cases as reasonable first to make sure we can make solid design decisions (for example, should the setting be per-repository or user-wide? It's easy to say both, but I'd like to hear of the need in practice before jumping to the most complex option).

Additionally, I've heard asks offline for a triplet environment variable as well, so that's the motive for proposing it above.

**Comment by MikeGitb** [comment]
Right, and imho the default in VS is wrong too ;) 
But I see your point.

**Comment by 9prady9** [comment]
Having a way to atleast switch the default triplet helps, especially in docker and/or ci environments.

**Comment by KindDragon** [comment]
@9prady9 you can set environment variable `VCPKG_DEFAULT_TRIPLET` https://vcpkg.readthedocs.io/en/latest/users/triplets/#additional-remarks

**Comment by 9prady9** [comment]
thank you @KindDragon

**Comment by ibrahimLearning** [comment]
@albertziegenhagel @9prady9 @Telokis 

where will I set VCPKG_DEFAULT_TRIPLET or use --triplet x64-windows? would you tell me please?

**Comment by drescherjm** [comment]
One way is to set it as a windows environment variable.

**Comment by ibrahimLearning** [comment]
@drescherjm

> One way is to set it as a windows environment variable.
Thank you very much for your comment. How can I use --triplet x64-windows?  it will be look like this:
./vcpkg.exe  --triplet x64-windows install cgal
or in a different way

**Comment by Timmmm** [comment]
> The reason to use x86-windows as the default triplet is to make the new user experience as absolutely streamlined as possible: Visual Studio defaults to x86 for new projects

Not on my system. At least, not with CMake:

```
PS C:\Users\Tim\Realsense\realsense_recorder> cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=C:/Users/Tim/local/vcpkg/scripts/buildsystems/vcpkg.cmake
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The CXX compiler identification is MSVC 19.28.29913.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features - done
CMake Error at C:/Users/Tim/local/vcpkg/scripts/buildsystems/vcpkg.cmake:794 (_find_package):
  Could not find a package configuration file provided by "realsense2" with
  any of the following names:

    realsense2Config.cmake
    realsense2-config.cmake
```

Has that changed?
