### ISSUE TITLE
Error installing various boost packages on VS 2019 preview 2.1

### ISSUE THREAD

**Issue by sylveon** [Microsoft/vcpkg#5302]
When installing boost projects that compile binaries (list boost-exception, boost-system and boost-winapi), I get the following error (portfiles are up to date, this is a fresh clone of vcpkg)
```
T:\Projects\vcpkg>vcpkg install boost-exception
The following packages will be built and installed:
    boost-exception[core]:x86-windows
Starting package 1/1: boost-exception:x86-windows
Building package boost-exception[core]:x86-windows...
-- Using cached T:/Projects/vcpkg/downloads/boostorg-exception-boost-1.69.0.tar.gz
-- Using source at T:/Projects/vcpkg/buildtrees/boost-exception/src/ost-1.69.0-2efe4bac04
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: T:/Projects/vcpkg/installed/x86-windows/tools/boost-build/b2.exe;--stagedir=T:/Projects/vcpkg/buildtrees/boost-exception/x86-windows-rel/stage;--build-dir=T:/Projects/vcpkg/buildtrees/boost-exception/x86-windows-rel;--user-config=T:/Projects/vcpkg/buildtrees/boost-exception/x86-windows-rel/user-config.jam;-j12;--debug-configuration;--debug-building;--debug-generators;--disable-icu;--ignore-site-config;--hash;-q;-sZLIB_INCLUDE="T:/Projects/vcpkg/installed/x86-windows/include";-sBZIP2_INCLUDE="T:/Projects/vcpkg/installed/x86-windows/include";threading=multi;threadapi=win32;runtime-link=shared;link=shared;address-model=32;architecture=x86;toolset=msvc-14.1;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="T:/Projects/vcpkg/installed/x86-windows/lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="T:/Projects/vcpkg/installed/x86-windows/lib";variant=release;debug-symbols=on
    Working Directory: T:/Projects/vcpkg/buildtrees/boost-exception/src/ost-1.69.0-2efe4bac04/build
    See logs for more information:
      T:\Projects\vcpkg\buildtrees\boost-exception\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  installed/x86-windows/share/boost-build/boost-modular-build.cmake:270 (vcpkg_execute_required_process)
  ports/boost-exception/portfile.cmake:14 (boost_modular_build)
  scripts/ports.cmake:71 (include)


Error: Building package boost-exception:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-exception:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.
```

Here's the log file:
```
notice: found boost-build.jam at T:/Projects/vcpkg/installed/x86-windows/tools/boost-build/boost-build.jam
notice: loading Boost.Build from T:/Projects/vcpkg/installed/x86-windows/tools/boost-build/src/kernel
notice: Site configuration files will be ignored due to the
notice: --ignore-site-config command-line option.
notice: Loading explicitly specified user configuration file:
    T:\Projects\vcpkg\buildtrees\boost-exception\x86-windows-rel\user-config.jam
notice: Searching 'T:\Projects\vcpkg\buildtrees\boost-exception\x86-windows-rel' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from 'T:/Projects/vcpkg/buildtrees/boost-exception/x86-windows-rel'.

warning: Did not find command for MSVC toolset. If you have Visual Studio 2017 installed you will need to specify the full path to the command, set VS150COMNTOOLS for your installation, or build from the 'Visual Studio Command Prompt for VS 2017'.

notice: will use 'cl.exe' for msvc, condition <toolset>msvc
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>', setup: 'T:/Projects/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>', setup: 'x86'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>32', setup: 'T:/Projects/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>32', setup: 'x86'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>', setup: 'T:/Projects/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>', setup: 'x86'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>32', setup: 'T:/Projects/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>32', setup: 'x86'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>64', setup: 'T:/Projects/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>64', setup: 'amd64'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>64', setup: 'T:/Projects/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>64', setup: 'amd64'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>', setup: 'T:/Projects/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>', setup: 'x86_ia64'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>64', setup: 'T:/Projects/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>64', setup: 'x86_ia64'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>', setup: 'T:/Projects/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>', setup: 'x86_arm'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>32', setup: 'T:/Projects/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>32', setup: 'x86_arm'
notice: [cmdline-cfg] toolset msvc-14.1 not previously configured; attempting to auto-configure now
error: msvc initialization: parameter 'version' inconsistent
error: no value was specified in earlier initialization
error: an explicit value is specified now
```

**Comment by jesec** [comment]
#https://github.com/boostorg/build/issues/389
My workaround: replace VS150COMNTOOLS with VS160COMNTOOLS (vcpkg\installed\<arch>\tools\boost-build\src\tools\msvc.jam).
Note that vs developer command prompt may need to be used.

**Comment by OlafvdSpek** [comment]
This sounds like a bug, not a feature.. with 2019 about to be released it'd be nice to have this fixed.

**Comment by OlafvdSpek** [comment]
```


```
notice: found boost-build.jam at C:/vc/vcpkg/installed/x86-windows/tools/boost-build/boost-build.jam
notice: loading Boost.Build from C:/vc/vcpkg/installed/x86-windows/tools/boost-build/src/kernel
notice: Site configuration files will be ignored due to the
notice: --ignore-site-config command-line option.
notice: Loading explicitly specified user configuration file:
    C:\vc\vcpkg\buildtrees\boost-serialization\x86-windows-rel\user-config.jam
notice: Searching 'C:\vc\vcpkg\buildtrees\boost-serialization\x86-windows-rel' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from 'C:/vc/vcpkg/buildtrees/boost-serialization/x86-windows-rel'.

warning: Did not find command for MSVC toolset. If you have Visual Studio 2017 installed you will need to specify the full path to the command, set VS150COMNTOOLS for your installation, or build from the 'Visual Studio Command Prompt for VS 2017'.

notice: will use 'cl.exe' for msvc, condition <toolset>msvc
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>', setup: 'C:/vc/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>', setup: 'x86'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>32', setup: 'C:/vc/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>32', setup: 'x86'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>', setup: 'C:/vc/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>', setup: 'x86'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>32', setup: 'C:/vc/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>32', setup: 'x86'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>64', setup: 'C:/vc/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>64', setup: 'amd64'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>64', setup: 'C:/vc/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>64', setup: 'amd64'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>', setup: 'C:/vc/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>', setup: 'x86_ia64'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>64', setup: 'C:/vc/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>64', setup: 'x86_ia64'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>', setup: 'C:/vc/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>', setup: 'x86_arm'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>32', setup: 'C:/vc/vcpkg/installed/x86-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>32', setup: 'x86_arm'
notice: [cmdline-cfg] toolset msvc-14.1 not previously configured; attempting to auto-configure now
error: msvc initialization: parameter 'version' inconsistent
error: no value was specified in earlier initialization
error: an explicit value is specified now


```

**Comment by omegacoleman** [comment]
VS2019 is too new so its unsupported by boost's build system. There's no sign of v14.2 in msvc.jam

https://github.com/boostorg/build/issues/389 here they promised to add it in 1.70, we'll have it after vcpkg update.

**Comment by Faq** [comment]
@omegacoleman they kinda realeased 1.70.

**Comment by omegacoleman** [comment]
> 
> 
> @omegacoleman they kinda realeased 1.70.

https://github.com/boostorg/build/blob/bc7659b9afe79f6ea8e70e8ea4a6974286d67d0d/src/tools/msvc.jam
still not a sign *sigh*

**Comment by OlafvdSpek** [comment]
@omegacoleman https://github.com/boostorg/build/blob/master/src/tools/msvc.jam ;)

**Comment by omegacoleman** [comment]
> 
> 
> @omegacoleman https://github.com/boostorg/build/blob/master/src/tools/msvc.jam ;)

thanks. happy new year :)

**Comment by sylveon** [comment]
Stuff now installs for me after using latest master of vcpkg.

**Comment by josevqzmdz** [comment]
> 
> 
> #[boostorg/build#389](https://github.com/boostorg/build/issues/389)
> My workaround: replace VS150COMNTOOLS with VS160COMNTOOLS (vcpkg\installed<arch>\tools\boost-build\src\tools\msvc.jam).
> Note that vs developer command prompt may need to be used.

jeez man, you're the kind of people that make this world spin. thank you so much
