### ISSUE TITLE
redundant copying of dlls during project build

### ISSUE THREAD

**Issue by RobertSpir** [microsoft/vcpkg#532]
I'm trying to create port of [vtk](http://www.vtk.org/) library here https://github.com/RobertSpir/vcpkg/tree/add-vtk
I managed to create working portfile and install the library. When I try to compile testing project using this library, the project builds and runs successfully, but during the compilation, the library dll files are copied many thousand times again and again. Anyone has any idea why is this happening?
I'm attaching build log
[vtktest.log.txt](https://github.com/Microsoft/vcpkg/files/700861/vtktest.log.txt)

**Comment by RobertSpir** [comment]
testing project is here https://github.com/RobertSpir/vtktest

**Comment by ras0219-msft** [comment]
The is due to the pretty naïve algorithm used inside `appLocal.ps1` [1]. The good news is that we aren't actually copying the DLL this many times, the bad news is that even when we don't copy the DLL, we still print it out to MSBuild (and then recurse).

If you'd like to silence this immediately, you can remove the linked line from appLocal.ps1. I'll file this as a bug to get fixed as well.

[1] https://github.com/Microsoft/vcpkg/blob/ff40fcaf95a6da48d46ecffc886d6b5d724d004b/scripts/buildsystems/msbuild/applocal.ps1#L21

**Comment by Cheney-W** [comment]
Thansk for reporting this issue. It has been fixed, please use the latest vcpkg.
