### ISSUE TITLE
[New port request] Libreoffice

### ISSUE THREAD

**Issue by luzpaz** [microsoft/vcpkg#5326]
https://wiki.documentfoundation.org/ReleaseNotes/6.2

Chocolatey: https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/libreoffice-streams/tools/chocolateyInstall.ps1

Scoop repo: https://github.com/lukesampson/scoop-extras/blob/master/bucket/libreoffice-fresh.json

**Comment by MikeGitb** [comment]
Is Libreoffice a c++ library? Vcpkg usually doesn't provide packages for executables.

**Comment by luzpaz** [comment]
I think it contains c++ libraries, yes

**Comment by MikeGitb** [comment]
@luzpaz: I mean: Is it containing a c++ library you want to use? 

Just curious, because - as far as I can tell - the repositories you linked to seem to just install the executables (and probably precompiled dlls needed to run them) which is out of scope for vcpkg, but e.g. installing libraries needed to develop libre office plugins might be.

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
