### ISSUE TITLE
Integration into VS

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/vcpkg#533]
Don't know if this is the right spot to ask for this, but are there any plans to integrate vcpkg into Visual Studio in a similar manner as nuget? 

The way it works now is great if you "just want it to work", but it would really nice to have the ability to select which libraries from vcpkg you want to use in a particular project / see what libraries are (directly or indirectly) used.

**Comment by ras0219-msft** [comment]
Are you looking for a ui to perform an existing feature, or are you suggesting new functionality? It isn't clear to me based on the paragraph above.

Unless it is extremely VS-specific, we would like all functionality to be equally accessible outside the IDE (for scripting purposes).

**Comment by MikeGitb** [comment]
I think it is mainly about an GUI, but 'm not 100% sure that all those functionalities already exist. To give you some examples:

- If I download libpng with vcpkg and just write `#include <libpng>` the library gets linked automatically. Now it would be nice to have a central place, where I can see all vcpkg libraries that get linked (directly or indirectly as a dependency).
- In the same menue I'd like to be able to not use the vcpkg version of libpng, because I e.g. want to use a different version, that I manually included in my project instead.
- Finally, it would be nice if I could manage the installed libraries directly from within Visual Studio.

**Comment by ras0219-msft** [comment]
Thanks for the clarification!

- Just for clarification, we actually link every well-behaved library into your project (some libraries go into the `lib\manual-link` folder because they would cause problems). The linker is able to very efficiently sort out which libraries you've used (maybe you forward declared a function -- just between friends ;)) and which you've not (say you #include a header just for some macros).
That said, it would definitely be nice to see "these are the libraries you're actually using". This can be a bit tricky in the case of header only libraries (the compiler itself is the only one who truly knows that), however we could very easily add something that does a dependency analysis on the runtime DLLs you're using and tells you which packages they came from!
- Depending on what you precisely want, this should "just work" if you add the appropriate include/link/etc to your project settings. We put our directives into the "project defaults", so you can override them easily by adding yours before the inheritance entry (`%(AdditionalDependencies)`).
However, please note that if you're using any other libraries that depend on libpng, you might get really nasty results due to them being built against the Vcpkg version of libpng! You may be better served by replacing your local `ports\libpng\portfile.cmake` to build your custom copy, which will result in all our other packages being built accordingly.
- Definitely noted -- this is one of the top feedback items we're getting from the survey (#530) thus far!

**Comment by MikeGitb** [comment]
Regarding the second point, I thought that in the past it didn't "just work" for the gsl library (#281). But I might have been wrong back then. I'll try to make a repro when I have the time.

**Comment by MikeGitb** [comment]
Is there any update on this?

**Comment by MikeGitb** [comment]
I think after a year without activity or any up/downvotes this can be closed.
