### ISSUE TITLE
pcre 8.38 download file not found

### ISSUE THREAD

**Issue by gknowles** [Microsoft/vcpkg#545]
The referenced location ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.38.zip doesn't exist,  where it looks like 8.38 has been removed, 8.39 and 8.40 are both present, That ftp site is the official home, but maybe it would be better to pull from sourceforge (listed as a mirror) where versions going all the way back to 3.3 are still available.

**Comment by alexkaratarakis** [comment]
Thanks for bringing this to our attention. 
ff40fcaf95a6da48d46ecffc886d6b5d724d004b updates pcre to 8.39 and adds a sourceforge mirror.

I used version 8.39 because that is the last version according to [pcre.org](http://pcre.org/) and also because 8.40 is not available in sourceforge. Thus, I am guessing 8.40 is not fully released yet.
