### ISSUE TITLE
planning for qt5.13 while keeping qt5.12 lts

### ISSUE THREAD

**Issue by TheScarfix** [microsoft/vcpkg#5649]
I am thinking about splitting qt5 into two ports, one for lts one for the latest release. What is your opinion on this?

**Comment by vicroms** [comment]
Speaking as a mantainer, I don't think that's a good idea.

Also in my experience using Qt for desktop development, upgrading to newer versions is quite a painless experience. Except for rare ocasions, e.g: [that time when 5.9 made QTcpSocket::connectToHost() horribly slow](https://stackoverflow.com/questions/48525022/qtcpsocket-connecttohost-takes-too-long-time).

I do see the need to keep using a LTS version, but in that regard is no different than all other libraries in vcpkg with multiple releases. A different argument could be made for when Qt 6 releases.

**Comment by MikeGitb** [comment]
They would be mutually exclusive right?

As long as vcpkg doesn't have native support for multiple versions in parallel,  I'd avoid it, because then the question becomes,  on which version other packages should depend  and be tested.

If this is to happen regardless,  I would prefer if LTS was treated as an optional feature of qt5 not as a separate list of ports (a bit like the opposite of --head).

**Comment by Neumann-A** [comment]
I certainly would also prefer this as a feature like: vcpkg install `qt5[lts]:x64-windows` but the real pain with qt is always updating all the hashes in all the portfiles. 
Probably ports like qt need to be completely rewritten as feature packages instead of using multiple port files to make updating and maintaining the ports easier. (and probably also allow the qt VS plugin to actually work somehow)

**Comment by Neumann-A** [comment]
I think this issue can be closed since qt has a latest feature in master now
