### ISSUE TITLE
Could not find StbConfig when using find_package(Darknet)

### ISSUE THREAD

**Issue by mschmidbauer** [microsoft/vcpkg#5832]
Hey Guys,

when trying to use Darknet (aquired via vcpkg) in my cmake Project there is an error while generating the Makefile:

CMake Error at C:/Dev/vcpkg/scripts/buildsystems/vcpkg.cmake:233 (_find_package):
  Could not find a package configuration file provided by "Stb" with any of
  the following names:
    StbConfig.cmake
    stb-config.cmake
  Add the installation prefix of "Stb" to CMAKE_PREFIX_PATH or set "Stb_DIR"
  to a directory containing one of the above files.  If "Stb" provides a
  separate development package or SDK, be sure it has been installed.

Stb[core] was installed correctly with the darknet library.

I think the problem here is that the stb package doesnt deliver a stb-config.cmake in the share folder.

Any suggestions?

**Comment by cenit** [comment]
I prepared a `FindStb.cmake` script for darknet, but maybe i left a bug so that it is not correctly propagated for downstream projects. Let me check and I will let you know asap. 
Sorry... since I am using darknet mostly outside vcpkg (unfortunately, but that will change soon) I still had no time to use it fully from here and do some well-deserve dogfooding

**Comment by cenit** [comment]
@mschmidbauer the latest PR for darknet #6047 should fix your issue. Please let me know if you encounter any problem

**Comment by cenit** [comment]
it is now merged in master. I hope that just updating fixes your problems. If not, again, please let me know

**Comment by PhoebeHui** [comment]
Thank you cenit for the fix, @mschmidbauer, please reopen it if it still be an issue for you.
