### ISSUE TITLE
Build-Depends does not respect choosen feature

### ISSUE THREAD

**Issue by kiwixz** [microsoft/vcpkg#5887]
If you have a package 000 with this CONTROL file:
```
Source: 000
Version: 0
Build-Depends: opencv[core]
```

`vcpkg install 000` should install:
```
    000[core]:x64-windows
  * opencv[core]:x64-windows
  * zlib[core]:x64-windows
```

but instead it tries to install:
```
    000[core]:x64-windows
  * eigen3[core]:x64-windows
  * libjpeg-turbo[core]:x64-windows
  * liblzma[core]:x64-windows
  * libpng[core]:x64-windows
  * opencv[core,eigen,flann,jpeg,opengl,png,tiff]:x64-windows
  * opengl[core]:x64-windows
  * tiff[core]:x64-windows
  * zlib[core]:x64-windows
```

Specs: Windows 10 Education 1803, locale en_US

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue!

This is the intended behavior, because the user has not declared their "understanding" of the opencv package. Consider this scenario:

> Library "libarchive" is a format-agnostic wrapper around various compression formats. Technically, it can be built with no back-ends (in which case it's useless). Since it's useless with no back-end formats however, it lists a few as defaults (zlib, bzip2, etc).
>
> Library "magic" uses "libarchive" to provide some cool behaviors for archive files (maybe fast indexing and searching). It doesn't technically need any specific format, so it declares a dependency on `libarchive[core]`.

Now, a user wants to use "magic". They run `vcpkg install magic`. Under our current behavior, the user will get something like "magic + libarchive + zlib + bzip2". Out of the box, everything will work reasonably well and they'll be able to operate on common formats. When an advanced user comes by and determines that they really just need `zstd` support (and don't want zlib+bzip2), they can achieve this by running `vcpkg install magic libarchive[core,zstd]`.

Under the alternate behavior you've described, the basic user will run `vcpkg install magic` and only get "magic + libarchive". They'll then try to run their program, but even the most simple examples online won't work -- they won't even be able to open zip files! To get the "basic" scenario, they'd need to explicitly run `vcpkg install magic libarchive` -- but they've never even heard of libarchive.

We'd like the simple situation to be simple and the advanced situation to be advanced; to get the advanced behavior you're looking for, you'll need to run `vcpkg install 000 opencv[core]`.

@Rastaban for visibility.

**Comment by PhoebeHui** [comment]
Documentation has added to vcpkg, see https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md#build-depends.
