### ISSUE TITLE
[New port request] Cyrus SASL

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#5894]
This is the Cyrus SASL API implementation. It can be used on the client or server side to provide authentication and authorization services. See RFC 4422 for more information.
https://github.com/cyrusimap/cyrus-sasl

Microsoft Windows **build**
https://github.com/cyrusimap/cyrus-sasl/tree/master/win32

**PreBuilt** and Source
https://sourceforge.net/projects/saslwindows/files/

**Comment by tan-wei** [comment]
`libgpod` [https://github.com/fadingred/libgpod](github) is a library which is used to read/write iPod database. Unfortunately, it uses `autoconf` instead of `cmake` to build the library. I find that all the dependencies are ported in `vcpkg`, so I think it is not that hard for `cmake` master to port.
If I have enough time to writing a good `CMakeLists.txt` file, I would like to add it. :-P

**Comment by SpareSimian** [comment]
Why close this? I'm interested in this port as a stepping stone to get Mailcore added and have done a little work to get it to build. (I need a couple patches yet and haven't had time to implement them.)

**Comment by Voskrese** [comment]
@SpareSimian 
you can add without a request) I can open it again, but I have lost the need
