### ISSUE TITLE
Fix boost-build for VS2019 (vc142)

### ISSUE THREAD

**Issue by ncihnegn** [microsoft/vcpkg#5976]
This will fix multiple boost issues, like #5807, #5302, #6021 .

**Comment by degski** [comment]
@ncihnegn @ras0219-msft If you experienced the same as me (or is it I) [see below], I'll describe a work-around (just to be able to continue programming).

I've got VS17 and VS19 installed, side-by-side. Trying to [do a vcpkg] update (glew in this case, but that's irrelevant), vcpkg wacks the current glew install out of existence and then carries on its merry way [why not rename and delete after a successful build and then delete [the old stuff] or rename it back to how it was, depending on the result of the build, is beyond me ( @ras0219-msft )]. But there's a snag, even though I have cmake 3.14.1 installed vcpkg [why not prefer the installed version of cmake iff it's newer than the VS included ones] insists on using cmake 3.12.4 in combination with VS19. This doesn't work, because VS19 is not supported [by that version of cmake], so now your f'ed.

A work-around (just to be able to get a compiled library, so you can keep on building/programming) is to just rename (temporarily)  `C:\Program Files (x86)\Microsoft Visual Studio\2019` to let's say `C:\Program Files (x86)\Microsoft Visual Studio\2019_` and do the build of said libraries (now it will work again). Then obviously just rename it [that folder] back to its original name.

**Comment by ncihnegn** [comment]
Thanks, @degski, but I uninstalled VS 2017.
My workaround is fixing boost-build by merging some upstream patches.

**Comment by degski** [comment]
> 
> 
> Thanks, @degski, but I uninstalled VS 2017.
> My workaround is fixing boost-build by merging some upstream patches.

Boost-1.70 will be out soon, I'll probably uninstall VS17 as well, but for the moment the whole thing simply has bugs and incomplete support for Clang/MKL/TBB etc ...  I'll wait for those to catch-up...

**Comment by scpeters** [comment]
I think boost 1.70 is out

* https://github.com/boostorg/boost/releases/tag/boost-1.70.0

**Comment by maximilian578** [comment]
As a temporary fix modify boost-build package to use 1.70. That should allow building all other boost 1.69 packages using msvc 2019, at least it allows to build all packages i use.

**VCPKG_ROOT\ports\boost-build\portfile.cmake:**
```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/build
    REF boost-1.70.0
    SHA512 be4e410a9656313519e089977a24da8f633db2182985f5d60e07e489f9eac8c887e8cab7e3cbd13f2b747bc3d9dab2899f174be1eaac73cfd7895015fb6b9b58
    HEAD_REF master
)
```

...

```
vcpkg_download_distfile(BOOSTCPP_ARCHIVE
    URLS "https://raw.githubusercontent.com/boostorg/boost/boost-1.70.0/boostcpp.jam"
    FILENAME "boost-1.70.0-boostcpp.jam"
    SHA512 7fac16c1f082821dd52cae39601f60bbdbd5ce043fbd19699da54c74fc5df1ed2ad6d3cefd3ae9a0a7697a2c34737f0c9e2b4bd3590c1f45364254875289cd17
)
```

**Comment by ncihnegn** [comment]
Will be closed by #6141 .

**Comment by ras0219-msft** [comment]
Additionally, if you want to pin a triplet to a specific compiler version, you can use the `VCPKG_PLATFORM_TOOLSET`[1] triplet option.

[1] https://github.com/Microsoft/vcpkg/blob/745a0aea597771a580d0b0f4886ea1e3a94dbca6/docs/users/triplets.md#vcpkg_platform_toolset

**Comment by NancyLi1013** [comment]
Hi everyone here, thanks for posting this issue and focusing on this issue.
Boost has been updated to 1.71.0 and it can support for VS2019 now.
Please update vcpkg and try to use them.

Thanks.
