### ISSUE TITLE
Error updating boost

### ISSUE THREAD

**Issue by marcogroppo** [Microsoft/vcpkg#60]
I tried to update boost from 1.60 to 1.61 using these commands:
```
vcpkg remove --purge boost:x86-windows 
vcpkg install boost:x86-windows
```
but the installation failed because of linking errors. The old build directories (1.60) were still there and they probably contained the old files. After removing these directories (`buildtrees\boost\x86-windows-rel` and `buildtrees\boost\x86-windows-dbg`) the installation went fine.

Should these directories be removed by the `vcpkg remove` command?
Is it ok to remove everything in `buildtrees\*` after installing a package?

**Comment by ras0219-msft** [comment]
The buildtrees are not currently removed by `vcpkg remove --purge`. It is always safe to delete `buildtrees\`, however this is where the unpacked source code and (sometimes) the pdbs are kept, so it may adversely affect debugging.

These build directories are normally removed by `vcpkg_configure_cmake` (see https://github.com/Microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_configure_cmake.cmake#L23). But, since Boost doesn't use that function, it needs to explicitly clear them.

**Comment by alexkaratarakis** [comment]
After f03590eeb7f49495b1f3276c56ee3c84843b4bd1 the boost portfile properly handles this by removing relevant directories before initiating a build. 
Thanks for reporting!
