### ISSUE TITLE
Anaconda adds `z.lib` to the path, which interferes with find_package(Zlib)

### ISSUE THREAD

**Issue by 4creators** [microsoft/vcpkg#610]
[libssh2.zip](https://github.com/Microsoft/vcpkg/files/740346/libssh2.zip)

Trying to build libssh2 for x86 target on Win 10 v1607 x64 box from VS2017 RC command prompt fails while x64 target build succeeds. Log files for configuration and build are attached.

**Comment by ras0219-msft** [comment]
Thanks for attaching the logs!

```
-- Found ZLIB: optimized;C:/Program Files/Anaconda3/Library/lib/z.lib;debug;E:/src/ms/vcpkg/git/installed/x86-windows/debug/lib/zlibd.lib (found version "1.2.11") 
```
```
       "E:\src\ms\vcpkg\git\buildtrees\libssh2\x86-windows-rel\install.vcxproj" (default target) (1) ->
       "E:\src\ms\vcpkg\git\buildtrees\libssh2\x86-windows-rel\ALL_BUILD.vcxproj" (default target) (3) ->
       "E:\src\ms\vcpkg\git\buildtrees\libssh2\x86-windows-rel\src\libssh2.vcxproj" (default target) (4) ->
       (Link target) -> 
         C:\Program Files\Anaconda3\Library\lib\z.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'X86' [E:\src\ms\vcpkg\git\buildtrees\libssh2\x86-windows-rel\src\libssh2.vcxproj]
```
Somehow, CMake is finding the Anaconda3 copy of zlib instead of our internal copy. This happened before (#90) though we didn't ever conclude what the exact mechanism was. I'll try to take a look if I can reproduce the issue locally.

**Comment by codicodi** [comment]
I had similar problems with finding different libraries which led me to analyze how find_library exactly works.
In general `find_library` first searches in `CMAKE_LIBRARY_PATH`, then in envioronment variables (among few other locations). However, if you specify multiple names, like this:
`find_library(ZLIB_LIBRARY NAMES z zlib)`
It first searches for `z.lib` in all search paths, then for `zlib.lib` in all search paths.

I have no idea whether Anacoda adds itself to PATH, but it looks like CMake searches in similar manner as example above. 
https://github.com/Kitware/CMake/blob/master/Modules/FindZLIB.cmake#L67

**Comment by 4creators** [comment]
After upgrading to #2a83c5eda6288cba46cb723996f95b0f6b21e61f problems are solved

**Comment by ras0219-msft** [comment]
@codicodi Arg! Thanks so much for tracking that down, it was really frustrating.

I think the overall best solution here is to exercise more control over the environment passed in. We should really be applying a whitelist to the user's path and filtering out "unknown" directories that could interfere with file/program lookups. It would be the responsibility of the portfile to supply that whitelist, so several existing ports would need changes.

However, as an immediate fix for Anaconda (since that's the particular case that keeps coming up), we could explicitly blacklist any path entries that start with "%PROGRAMFILES%Anaconda3".

**Comment by codicodi** [comment]
[CMAKE_FIND_ROOT_PATH](https://cmake.org/cmake/help/v3.0/variable/CMAKE_FIND_ROOT_PATH.html)  option seems to be intended to separate build environment from the rest of the world, but I'm not sure how it works.
Another option could be to wrap `find_library`/`find_path `calls (similar to how vcpkg.cmake does with `add_library`/`add_executable`). The wrappers could ensure the path starts with `${CURRENT_INSTALLED_DIR}`, possibly rerunning the original function a few times.

**Comment by cloudhan** [comment]
I also encountered this issue when building `libpng:x86-windows`, but `libpng:x64-windows` built successfully. I think vcpkg shoud add its own way to control PATH instead of plainly relaying on system's env variable which vary from user to user. In this way, vcpkg will act more like a closure and it will make reproduce way easier on different machine.

**Comment by cloudhan** [comment]
Current I use following PowerShell command to remove `Anaconda` related pathes from PATH env
``` PowerShell
$($Env:PATH).Split(';') | where { $_ -notmatch "Anaconda" } | %{ $temppath += "$_;"};  $Env:PATH = $temppath
```
Anyone have issue with Anaconda's z.lib can use it as a temporary walkaround without messing with system's PATH setting.

**Comment by willyd** [comment]
Not sure why this happens since like @ras0219-msft mentioned CMake doc's clearly states that it searches CMAKE_PREFIX_PATH first. That being said adding those lines: 
```CMAKE
# Workaround for issue #610
set(ZLIB_LIBRARY_RELEASE ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/zlib.lib CACHE FILEPATH "Path to zlib")
set(ZLIB_LIBRARY_DEBUG ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/zlibd.lib CACHE FILEPATH "Path to zlib")
``` 
to the vcpkg.cmake toolchain file solves the issue for me.

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in two year, if it is still an issue, please reopen.
