### ISSUE TITLE
vcpkg_extract_archive_ex REF variable 10 characters limit

### ISSUE THREAD

**Issue by invy** [microsoft/vcpkg#6101]
There is a problem with vcpkg_extract_archive_ex: REF variable is limited to 10 characters (and not documented)

https://github.com/Microsoft/vcpkg/blob/60db384541ad9e0c65a8219d9628140692dc600a/scripts/cmake/vcpkg_extract_source_archive_ex.cmake#L74-L76

What is the purpose for such limit?

This limit totally defeats the purpose of the variable: instead of making a friendly names it makes them rather unfriendly, for example:
Building package boost-regex[core]:x64-linux...
-- Using cached /mnt/d/vcpkg/downloads/boostorg-regex-boost-1.69.0.tar.gz
-- Using source at /mnt/d/vcpkg/buildtrees/boost-regex/src/**ost**-1.69.0-80bf9a4997

**Comment by Rastaban** [comment]
The 10 character limit was put in place because some ports will fail if the path becomes too long.  It cuts off the beginning rather than the end of the tag because the version number is typically at the end of the tag, and that is the value that changes the most.  This should definitely be added to the documentation for vcpkg_extract_archive_ex.

The names end up looking weird though.  How do you think it should be done?

**Comment by Rastaban** [comment]
updated docs in #7039
