### ISSUE TITLE
Build of sqlite3 fails to detect CMake 3.7.2 x64 installation and installs CMake 3.7.2 x86

### ISSUE THREAD

**Issue by 4creators** [Microsoft/vcpkg#611]
While testing vcpkg I have encoutered bug in which sqlite3 installation depends on CMake 3.7.2 x86 binaries while ignores already installed x64 binaries (they are available in PATH). After downloading x86 version build proceeds without errors. This affects some other packages as well which fail to detect x64 CMake and do not ask for installation of x86 binaries. Some x86  or both x86 and x64 builds than fail (libtheora, libogg) with log output indicating that no c and cxx compilers were detected..

**Comment by ras0219-msft** [comment]
System information from #613:
> win10 v1607, VS2015 U3, VS2017 RC, CMake v3.7.2.x64 available via PATH

Ideally, the specific version of CMake being used is completely package agnostic, so this issue should affect _every_ package. I've merged the three issues together for now assuming that's the case; we can reopen them if it turns out to be a package-specific issue.

At the beginning of every command (save a few trivial ones) we locate the "desired" CMake instance. We do this by _prepending_ the downloaded CMake location to your current path, and then _appending_ both program files directories (x64 and x86) [1]. Then, we run `cmake --version` to ensure we meet a minimum requirement (at the moment, that is 3.7.2). If the located version isn't sufficient, then we prompt to perform a local download (note: we explicitly _don't_ install it!). The locally downloaded version will then-on always be used to improve the general reliability of builds (e.g. the behavior you saw where everything started working).

Could you confirm a few more things about your environment to better diagnose the issue?
1. Can you (using your system installed x64 cmake) build a hello world cmake project using the "Visual Studio 15 2017" generator?
2. What Vcpkg version are you using (`vcpkg version`)? Make sure you've pulled the latest commit and re-run the bootstrap script.
3. After updating Vcpkg in (2), delete the `vcpkg\downloads\` directory and try to rebuild `libtheora` or `libogg`. Are you prompted to download the portable cmake? If not, does the build fail?
4. For sanity's sake, could you confirm what the output of `cmake --version` is for the version on your path? If you happen to have multiple sources providing CMake, we won't iterate through all of them -- we'll just test the first on the path and abort if it isn't new enough.

[1] https://github.com/Microsoft/vcpkg/blob/d5e7a501e907f06ad1e8bb4ffdebce9a29179d2d/toolsrc/src/vcpkg_Environment.cpp#L75

**Comment by 4creators** [comment]
@ras0219-msft Please find below all info you requested - after updating to #515 all packages build successfully. Before this I have update VS2017 RC to latest version. CMake x64 install works well as I have build llvm and clang with it. Unfortunately bootstrap script is not working from command prompt but work from powershell console.

``**********************************************************************
** Visual Studio 2017 RC Developer Command Prompt v15.0.26127.0
** Copyright (c) 2016 Microsoft Corporation
**********************************************************************

C:\Windows\System32>cd /d e:src\ms\vcpkg\git

E:\src\ms\vcpkg\git>.\vcpkg version
Vcpkg package management program version 0.0.70-d776322d2a99aebff6147081e98fac434e6f6dc6

See LICENSE.txt for license information.

E:\src\ms\vcpkg\git>git pull

....

E:\src\ms\vcpkg\git> powershell -exec bypass scripts\bootstrap.ps1

PowerShell version: 5.1.14393.693
Free physical memory: 9809 MB out of 16300 MB

scripts\bootstrap.ps1 : The module 'scripts' could not be loaded. For more information, run 'Import-Module scripts'.
At line:1 char:1
+ scripts\bootstrap.ps1
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (scripts\bootstrap.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule

*****************************************************

Switch to PowerShell console and run

E:\src\ms\vcpkg\git> scripts\bootstrap.ps1

*****************************************************

E:\src\ms\vcpkg\git>.\vcpkg version
Vcpkg package management program version 0.0.71-2a83c5eda6288cba46cb723996f95b0f6b21e61f

See LICENSE.txt for license information.

E:\src\ms\vcpkg\git>cmake --version
cmake version 3.7.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

E:\src\ms\vcpkg\git>.\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
The following packages differ from their port versions:
    openssl:x64-windows         1.0.2k-1 -> 1.0.2k-2
    openssl:x86-windows         1.0.2k-1 -> 1.0.2k-2

To update these packages, run
    vcpkg remove --purge <pkgs>...
    vcpkg install <pkgs>...

**Comment by ras0219-msft** [comment]
Thanks for the extra information.

Let me reiterate to be sure I'm following correctly: there's no longer any issue with CMake for any packages, however you are now hitting an issue with the bootstrap script (the same issue as #584)?

Assuming this is the case, I'm going to close this issue and we can work on the bootstrap issue over in #584. Thanks for bringing this to our attention!
