### ISSUE TITLE
Lack of support WebRTC in vcpkg

### ISSUE THREAD

**Issue by kinglezhuang** [microsoft/vcpkg#6205]
Can add webrtc lib into vcpkg so that user can use it easily?

**Comment by Voskrese** [comment]
webrtc-audio ?

meson
test msvc x64 windows dynamic

[webrtc-audio-processing.zip](https://github.com/microsoft/vcpkg/files/3398668/webrtc-audio-processing.zip)

**Comment by NancyLi1013** [comment]
Hi @kinglezhuang  thanks for posting this request. Could you help provide the source code link about this port?

**Comment by jherico** [comment]
WebRTC uses [GN](https://gn.googlesource.com/gn/+/master/README.md) for it's build system.  Are there any existing ports that wrap GN?  That might make it easier to generate a port script as opposed to doing everything from scratch.

**Comment by niklaskorz** [comment]
This should be easier to accomplish once #8963 is merged, right? It adds the relevant cmake scripts required to integrate other GN projects into vcpkg.

**Comment by janisozaur** [comment]
#10505 added gn support

**Comment by makitsune** [comment]
The crashpad port here is an example using gn so I took a look at adding WebRTC today. 

However, I think compiling WebRTC through Vcpkg is not very intuitive at all because the amount of dependencies add up to a total of 10 GB. I'm not sure if that's with or without android deps.

I found this website and git repo that provides automatic builds. The website explains more about the complexity of building it yourself.
https://sourcey.com/precompiled-webrtc-libraries
https://github.com/sourcey/webrtc-builds

I don't know if it's against the rules of Vcpkg but I could submit a pr that add WebRTC from these automated builds. I'm also not sure how trusted this source is but there are similar community efforts to provide complex and hard to get packages. From the top of my head I was thinking of https://github.com/phracker/MacOSX-SDKs which is trusted.

**Comment by arsdever** [comment]
Hi guys. Currently, I'm trying to compile the library for UWP, but have some problems and would like you to help me if you can. I'm basically done with x86 and x64 platforms and I can share the patch if necessary, but having problems with `xmmintrin` and similar headers (like `emmintrin`) when building for `arm`. As I understood, `arm` uses `arm[64]_neon.h` for `SSE`, but it requires some (maybe huge) changes in the source code. Is there a better approach than doing this changes?

**Comment by makitsune** [comment]
Oh awesome! After days of looking, I found up-to-date builds of WebRTC for all platforms here on GitHub. https://github.com/crow-misia/libwebrtc-bin/releases

This person setup Gh actions to automatically create `libwebrtc.a` or `webrtc.lib` and header files archived ready to use in your own projects. What's neat about this is that any of us can fork it and still get builds if the owner decides to stop updating it. I've been using this in our project with a custom port that extracts the archives and it works great! Windows 10, macOS 10.11+ and Linux

**Comment by Cheney-W** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
