### ISSUE TITLE
vcpkg unable to use BITS when running as a Windows Service

### ISSUE THREAD

**Issue by bmharper** [Microsoft/vcpkg#627]
As you'd expect, vcpkg runs as part of our CI infrastructure. We run Jenkins as a Windows Service on Windows 10, and the user under which this service runs, is a domain user that has admin rights on that machine (ie it's not LocalSystem or Network Service).
We frequently see the following error message emitted by vcpkg:

```
Start-BitsTransfer : The operation being requested was not performed because the user has not logged on to the 
network. The specified service does not exist. (Exception from HRESULT: 0x800704DD)
At C:\Jenkins\workspace\Maps-Windows-Analyze\windows_deps\vcpkg\scripts\fetchDependency.ps1:73 char:13
+             Start-BitsTransfer -Source $url -Destination $downloadPat ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Start-BitsTransfer], COMException
+ FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.BackgroundIntelligentTransfer.Management.NewBitsTransferCommand
```

This happens when vcpkg is trying to use BITS to download a package.

If I hunt around on the internet, using the top line as the search query, I come across various suggestions, but I'd appreciate some clarity from the vcpkg authors. Obviously a build tool such as vcpkg must be runnable by automated systems. Is there something wrong in our setup? If there's a simple scriptable thing that we can run on the CI slaves to fix this issue, then that's OK (I'd love to know what that magic incantation is). But if it requires human button pressing, then I think this is a real problem.

**Comment by alexkaratarakis** [comment]
We definitely intend for `vcpkg` to run in automated systems; in fact, this is the reason why we avoided requiring admin (with one exception: the first time you run `vcpkg integrate` for VS2015, but that should not affect automated scenarios). 

It appears BITS could not be reached in your case for some reason. Is this consistent?
Either way, we use BITS for transferring files because it is faster, but we also have a fallback download mechanism.
ce9927f7327bc71ade246108a7d984deda6293fd aims to fix said fallback in case the BITS invocation throws. 
(no need to rebuild `vcpkg`, just do a `git pull`). 
Please let me know if this resolves the issue.

**Comment by alexkaratarakis** [comment]
Something relevant: 
This download is most likely trying to get CMake. We recently bumped the required version of CMake to 3.7.2 due to Visual Studio 2017 support. It is possible that the download was not triggered for your systems before because they already had CMake <3.7.2.

**Comment by bmharper** [comment]
Thanks for the swift turnaround. I literally opened the ticket before I went to sleep, and woke up with the fix! I've updated to latest, and haven't seen any errors yet, but will report back again in a few hours.

**Comment by bmharper** [comment]
Looks good! A bunch of CI machines have been building without any problems today.
