### ISSUE TITLE
No postfix in debug dll of libwebm (followup)

### ISSUE THREAD

**Issue by chrisaverage** [microsoft/vcpkg#6553]
It doesn't seem to be fixed. I don't think a simple file rename is a way to handle this. The debug dlls do have a "d" postfix now but they are not copied to the output directory on build and when running the app there's an error saying libwebm.dll is missing so it's still linking to the old name without the postfix. This needs to be handled at build time, not as a post-build rename.

_Originally posted by @chrisaverage in https://github.com/microsoft/vcpkg/issues/4878#issuecomment-485952765_

**Comment by Neumann-A** [comment]
~~Does it install a config and generate a target file?~~ (After checking it, it does nothing like that)

somebody should stop people manually renaming libraries .... cmake has an option to do that automatically! There is probably a filename link within the .lib file. (@LarryIII / @Rastaban)
Yeah `dumpbin /HEADERS webmd.lib` reveals `DLL name     : libwebm.dll`
(hmm interesting this should be its own issue. Manual library renames will break things)

Instead of the manual rename in the portfile you could try to set CMAKE_DEBUG_POSTFIX in the configure step of libwepm and remove all the other renames currently in the portfile.
