### ISSUE TITLE
[gdal]: x64-linux port issues

### ISSUE THREAD

**Issue by jumpinjackie** [microsoft/vcpkg#6680]
1. When tapping into any projection functionality, it tries to autoload `libproj.so` which fails because by default most ports for `x64-linux` builds for static libs and `PROJ_STATIC` is not defined for the `gdal` port for Linux

2. My application that uses the `gdal` port prints this to the output:

```
libpng warning: Application was compiled with png.h from libpng-1.6.37
libpng warning: Application  is  running with png.c from libpng-1.2.56
libpng error: Incompatible libpng version in application and library
```

And segfaults shortly after.

It looks like the GDAL build has its wires crossed, finding the `png.h` header from the vcpkg port (whose current version as of writing this is 1.6.37), but presumably building and linking against GDAL's internal copy of `libpng` (whose version is 1.2.56)

I think the solution here is same as for #6304 on Windows, instruct GDAL to build against an external libpng (the vcpkg port)

PR to follow (unless someone else beats me to the punch)

**Comment by jumpinjackie** [comment]
Awaiting on an appropriate outcome for #6752 before I can make a PR

**Comment by JackBoosY** [comment]
Hi @jumpinjackie, thanks for reporting this issue.
After several times repairing gdal, it should be able to build successfully in linux.
So can you update vcpkg and try again?

Thanks.

**Comment by lakinwecker** [comment]
I'm still having this issue.  @JackBoosY what info do you need? I made a simple example which illustrates the lack of static-linking against proj - https://github.com/lakinwecker/vcpkg-gdal-issue

By default, the x64-linux triplet uses static linking, but gdal is not told to link against proj statically, so it assumes it can dynamically open libproj.so when it needs it.  This doesn't not work, because no libproj.so exists.

**Comment by JackBoosY** [comment]
@lakinwecker See my [comment](https://github.com/microsoft/vcpkg/issues/9068#issuecomment-557390897).

**Comment by JackBoosY** [comment]
Please track #9068.

Thanks.
