### ISSUE TITLE
vcpkg install fails to parse CONTROL files (need vcpkg version bumb)

### ISSUE THREAD

**Issue by Farwaykorse** [microsoft/vcpkg#6946]
## Problem
On systems running an older build of vcpkg `vcpkg install` throws warnings for any port control file containing the new 'Homepage` field (https://github.com/microsoft/vcpkg/pull/2933) and fails to build those:
````
vcpkg install ms-gsl:%PLATFORM%-windows
Warning: an error occurred while parsing 'alembic'
...
Warning: an error occurred while parsing 'ms-gsl'
...
Error: Cannot find definition for package `ms-gsl`.
````
Both on Windows and Linux builds:
[TravisCI - Linux](https://travis-ci.com/Farwaykorse/fwkSudoku/jobs/208172339#L451)
[Appveyor - Windows](https://ci.appveyor.com/project/Farwaykorse/fwksudoku/builds/25348544/job/i51ky0w2q44p8one#L92)

The problem is that `vcpkg v2018.11.23` as build in November 2018 is not compatible with the updated format for the control files used with `vcpkg v2018.11.23` build in June 2019.
Without a version bump there is no warning, users have to figure for themselves out that a rebuild is necessary.
As also noted with one of the PR's: https://github.com/microsoft/vcpkg/pull/6844#issuecomment-501625789

### Workaround
Rebuild vcpkg: `./bootstrap-vcpkg.bat`
Or for CI systems (travis) remove the cache.

### Solution
Vcpkg needs a version increase.
To warn users and to get CI systems, that contain an older build (Appveyor) or cache vcpkg, to rebuild vcpkg.

**Comment by Farwaykorse** [comment]
@vicroms Why would you label this as a feature?
The current version is `2018.11.23` and the associated update behaviour* has always been a part of vcpkg.
\* When the version is changed users receive a warning message with instructions to rebuild vcpkg.

It used to be that @alexkaratarakis regularly updated the version number and changelog.
Solving the issue by creating a PR for [toolsrc/VERSION.txt](https://github.com/microsoft/vcpkg/blob/master/toolsrc/VERSION.txt) is easy, but updating [CHANGELOG.md](https://github.com/microsoft/vcpkg/blob/master/CHANGELOG.md) with all the changes in the past 7 months ...

**Comment by ras0219-msft** [comment]
Thanks for pointing out this issue!

We do recommend that users always re-run ./bootstrap whenever they change the vcpkg commit. However, for certain changes that we _know_ will cause problems, we do have the warning mechanism that you've mentioned. In this case, we should definitely be using that warning mechanism!

We are currently considering alternative approaches to the `CHANGELOG.md` file than directly tying it to the version in `toolsrc/VERSION.txt`; due to that, we would be more than happy to accept a PR just bumping the VERSION.txt :)
