### ISSUE TITLE
[WINDOWS] [VCPKG] [MSVC 2019] Automatically install missing components

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#6986]
https://devblogs.microsoft.com/setup/configure-visual-studio-across-your-organization-with-vsconfig/

vswhere `+` .vsconfig 
https://github.com/Microsoft/vswhere/commit/215dd2dab917b12c1756887fe8e754f8cd3913b6
https://github.com/microsoft/terminal/blob/master/.vsconfig

can also implement, there will be fewer errors from users

**Comment by PhoebeHui** [comment]
@Voskrese, you are trying to bring up some idea here? if I understand correctly, automatically install such as Visual studio components or windows sdk, English package, right?

**Comment by Voskrese** [comment]
Yes, this is a suggestion, because there are a lot of problems with installing on Windows, both vcpkg and libraries.

I would like to see in the form of a script to check whether the necessary components are installed and, if necessary, their installation

**Comment by heydojo** [comment]
> because there are a lot of problems with installing on Windows, both vcpkg and libraries.

Please elaborate. My experience indicates that if you don't know which libraries you should be using and how to install them, that vcpkg probably isn't for you.
Please be more concise and exacting by giving clear examples of what you mean.
Compiler messages inside the logs found in the build tree for the failed build (when vcpkg even tells you where to look to find out what the error is and thus that you are missing x) mean that it is trivial to correct your mistake of not installing required external build dependencies before starting a build.

The basic MS Visual studio C++ components, msbuild and the Windows 10 SDK are all that are required 99% of the time.

Are you new to C++ development on Windows?

**Comment by Voskrese** [comment]
@heydojo 
write here
https://devblogs.microsoft.com/setup/configure-visual-studio-across-your-organization-with-vsconfig/
that they were wasting their time because

> The basic MS Visual studio C++ components, msbuild and the Windows 10 SDK are all that are required 99% of the time.

:-)

**Comment by heydojo** [comment]
> that they were wasting their time because

I'm just going to assume that maybe that's an English translation error? And you aren't trying to put words into my mouth. I certainly **did not** imply that anyone was wasting their time.
I said and I quote:

> My experience indicates that if you don't know which libraries you should be using and how to install them, that vcpkg probably isn't for you.

From the documentation https://github.com/microsoft/vcpkg#overview :

> Vcpkg helps you manage **C and C++** libraries on Windows, Linux and MacOS

Your link: https://devblogs.microsoft.com/setup/configure-visual-studio-across-your-organization-with-vsconfig/

Is about installing the "kitchen sink" using a deployment tool for Visual Studio - within a corporate environment. At corporate level, we have several meetings with all stakeholders before anything is installed at all. vcpkg would never have any say in any of that.

Attempting to add a feature to vcpkg where it manipulates anything outside of it's own tree is a yikes from me. Let alone an installation of VS on a build machine. Couple that with the fact that storage space and bandwidth are still mostly prized due to their lack of abundance in many places and you have a non-starter.

**Comment by Voskrese** [comment]
I wrote links to example
do you think `microsoft/terminal` is from a corporate environment and only for it?
