### ISSUE TITLE
Parallel compilation

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/vcpkg#704]
While installing aws-sdk-cpp on a 2C 4T CPU:

I think using 4 parallel invocations is more than enough for this poor CPU..
Running this many in parallel also runs into memory issues on my machine.

![vcpkg](https://cloud.githubusercontent.com/assets/2218936/23219455/649f0d8e-f91f-11e6-845b-62f74b0c286a.PNG)

**Comment by ras0219-msft** [comment]
Ouch, I'm not sure how the build ended up spawning 24 processes there. At worst, (due to an unfortunate interaction between MSBuild and cl.exe), I would have expected 16 -- still not great, but better.

To first confirm what I think will fix the problem, could you try editing `scripts\cmake\vcpkg_build_cmake.cmake`, commenting out the line `list(APPEND MSVC_EXTRA_ARGS "/m")`, then rebuilding `aws-sdk-cpp`? I would expect to see 4 or 5 (and if 5, one of them should be mostly idle).

If this fixes the issue, then we can look into a user-specific option to globally disable MSBuild's parallel project builds (perhaps automatically based on the machine's RAM / CPU).

Additionally, as we switch more projects over to use Ninja, this problem should get significantly better without any configuration on the user's part.

**Comment by OlafvdSpek** [comment]
Ninja creates less processes, which is good.
The build still takes very long though, one hour and counting.. 

I'll try without ninja later today.
