### ISSUE TITLE
How to deal with tool only packages

### ISSUE THREAD

**Issue by laserallan** [Microsoft/vcpkg#711]
I have a project dependent on flex and bison and I added a port to build them but the post validation doesn't like them because it doesn't generate any libraries or include files.
Is there a way of building projects like this and installing tools only into the tools directory?

**Comment by ras0219-msft** [comment]
For tools that don't have runtime components, we _generally_ think it's best to handle them by downloading prebuilt binaries. Most tools like this can be mix-and-matched inside the same process just fine, so we tend to prefer private copies that we download ourselves. If this applies to flex and bison (it's been a few years since I've used them, so I'm a bit foggy on that), then we would add them to [1].

For users who want to use flex and bison in their applications, we _could_ package them, but we only want to do that if we can give them a significantly better experience than they already get with Chocolatey [2] or just checking the executables into their source tree. For libraries, this is upgrade management -- you can upgrade a base level library and we'll make sure the rest of the tree gets rebuilt to stay consistent. With tools, that's often a far smaller problem -- we don't _really_ need to rebuild \<tool\> when you upgrade boost, even though it uses it internally.

[1] scripts\cmake\vcpkg_find_acquire_program.cmake
[2] https://chocolatey.org/packages/winflexbison

**Comment by laserallan** [comment]
Cool. I'll do it that way instead then.
