### ISSUE TITLE
using the packages in other than cmake and msbuild systems (qmake)

### ISSUE THREAD

**Issue by amigo421** [Microsoft/vcpkg#722]
this is request for an assistance, not a bug report or feature request

one of my projects is qmake based, so I'd like to use automated build of the libs/dependencies using vcpkg.
please correct me if my understanding is wrong, in terms of availability vcpkg libs, I have to provide my project with INCLUDE/LIB/PATH variables extension refers to:
[vcpkg]/installed/arch-platform/include
[vcpkg]/installed/arch-platform/lib
[vcpkg]/installed/arch-platform/bin
respectively,
and DEBUG versions:
[vcpkg]\installed\arch-platform\include
[vcpkg]\installed\arch-platform\debug\lib
[vcpkg]\installed\arch-platform\debug\bin

is it correct?

**Comment by ras0219-msft** [comment]
You'll also need to add `\lib\manual-link` and `\debug\lib\manual-link`. See https://github.com/Microsoft/vcpkg/blob/master/docs/EXAMPLES.md#example-1-2-c.

Note that where you've labelled "arch-platform" is the triplet, which _can_ be an arbitrary customizable string (but arch-platform is a reasonably sane bet).

**Comment by ras0219-msft** [comment]
Also, if you're successful and would like to write up a short description of how to use Vcpkg with qmake, I'd be happy to add it to the EXAMPLES document.

**Comment by amigo421** [comment]
could you clarify please 
1. My current installation doesn't conatin "manual-link" , the link above does only refer to those folders but doesn't explain what is it and why additional paths required. 
2. do I understand this right - import libs and static libs (both use *.lib) placed in the same folder? any difference in the naming ? e.g. unix style "lib..." prefix? 
3. When I was refer to INCLUDE/LIB/PATH env variables , I didn't mean qmake specific , this is just a preparing an environment for visual c++, to provide vc compiler and linker with a paths(just from VC documentation). and - yes, no problem , I can describe (in .md) the steps for that.

**Comment by alexkaratarakis** [comment]
@amigo421 
1) We automatically add all installed libraries to the link line for the msbuild integration. However, some libraries are not automatically linked because they define main() for you. The libs of these libraries are placed in a sub-directory called `manual-link` and as the name implies, you have to manually link those. Only a few libraries do this (e.g. gtest) so you might not really need it. Other than that, and for non-msbuild purposes, it is just another folder to inspect for lib files.

2) Both static and import libraries are *.lib files, yes, but the lib files of static and dynamic builds of the same library don't end up in the same folder. 
We have the notion of triplets, e.g.:
- x86-windows
- x64-windows
- x86-windows-static
- x64-windows-static
- arm-uwp
etc..

Those are completely independent and placed in different folders in your `installed\` directory. Because static and dynamic builds are different triplets, you won't end up with both dynamic and static builds of the same library in the same triplet. 

For example, if you want both builds of zlib:
`vcpkg install zlib:x86-windows zlib:x86-windows-static`

you will get these separate packages:
`vcpkg\packages\zlib_x86-windows`
`vcpkg\packages\zlib_x86-windows-static`
Each of these two folders has its own `lib\` subdirectory. 

Furthermore, the installed lib files will be placed in a triplet-specific subfolder of `installed\`:
`vcpkg\installed\x86-windows\lib`
`vcpkg\installed\x86-windows-static\lib`
So, again they can't overwrite each other. 

Each triplet can only have at most one instance of a library. Therefore, the name of static and dynamic libs are not related to each other.

**Comment by ras0219-msft** [comment]
Closing, assuming the current documentation is sufficient for now.
