### ISSUE TITLE
cleaner directory seperation between release and debug

### ISSUE THREAD

**Issue by Fleischner** [Microsoft/vcpkg#723]
Currently include files are shared between debug an release build, with debug binaries placed in a debug subfolder of the release folder.

I think this could give some problems:
a) Some libraries auto-generate custom header files during compilation. Eg configuartion headers.
These might be different for release and debug, possibily resulting in horrible abi breakages. 
b) Same problem holds for generated cmake files in install folder (?)
c) The upcoming c++ module system ifc files are (probably) different for realease and debug builds, thus require an clean seperation anyways
d) With the debug libraries in the same folder, wrong libraries could be linked in when referencing libraries by hand.

Maybe its better to split:
- realease and debug folders with bin, include, lib, ... subfolders
- build an checksum over the include folder to allow a consistency check later

**Comment by ras0219-msft** [comment]
a)
This is a good point, and one we did consider when initially deciding the file layout initially. The idea was to _potentially_ support a `debug\include\` folder that could optionally be provided and would be put first in the include order compared to the base `include\` folder. This would allow libraries that did what you've described (different headers in release vs debug) to override our base behavior.

However, in the 175+ libraries we have, this has yet to be an issue. This inclines me to say that it's rare enough (<0.5% of libraries) that we can have "special" handling when it's needed instead of making it the default behavior for every library. An example of this special handling would be to generate "shadow" headers which simply have an "#ifdef NDEBUG" and forward to the correct true header.

As with everything, it's tradeoffs. We think that avoiding duplication of headers for Debug vs. Release is pretty important given the number of header-only libraries that exist for C++ (such as large parts of Boost). The cost that we may need to do some "ugly" things for one or two libraries that generate different debug and release headers seems worth it.

Do you have a concrete example of a library which does generate incompatible headers for debug and release?

I do agree that the checksum over the headers sounds like a reasonable way to check for difference between debug/release, however the devil is in how to implement it without placing undue burden onto port maintainers.

b)
CMake supports multiple configurations out-of-the-box for "config" mode. We already have many libraries that provide these files; essentially there is a "foo-targets-release.cmake" and "foo-targets-debug.cmake" which each supply the relative paths for their configuration. These do require fixups on install to make it work (see opencv for one of the most complex examples).

c)
We will probably put ifc files into either the `lib\` folder or they will get their own toplevel folder which will be split for debug/release.

d)
Not 100% sure what you're stating here, but we currently put debug libraries into `debug\lib\` and `debug\bin\` to fix this exact issue. There is an outstanding issue with CMake's multi-configuration generators, "FindX.cmake" modules, and libraries that do not use debug suffixes where the wrong import library will be selected; the workaround for these libraries is (for now) to use separate build trees for Release and Debug.
