### ISSUE TITLE
Norton very unhappy with vcpkgmetricsuploader

### ISSUE THREAD

**Issue by JEJ0** [microsoft/vcpkg#7240]
I just installed the current vcpkg and encountered this as well. I've read through [#6551](https://github.com/microsoft/vcpkg/issues/6551) and [#3345.](https://github.com/microsoft/vcpkg/issues/3345) I see these closed but don't see any resolution.

What I do see is that Norton is very, very unhappy on my system with this tool. I've gotten SONAR reports about the metrics upload (and I'll also put in a vote for making metrics opt-in. I'm surprised that it is opt-out, and not terribly well documented opt-out). Norton is now saying that it needs to restart to finish cleaning out the security risks.

This is not the level of security awareness I expect Microsoft to have. Minimally fix this to be opt-in. Beyond that, work with your security teams to get the uploader qualified by at least the major vendors.

**Comment by heydojo** [comment]
> This is not the level of security awareness I expect Microsoft

I don't work for MS. Your tone is derogatory.

Your software (Norton) has established a false positive in it's threat detection. Please work with the software manufacturer to establish a resolution on their part.

There is nothing Microsoft or anyone else can do if a piece of third party software on your machine malfunctions.
One solution is to use Windows built-in threat detection tools instead of the unreliable Norton software. I am actually quite shocked that Norton are even still in business. Their AV and other "Security" products have been malfunctioning and underperforming for well over 20 years.

Because vcpkg is open source, you can modify the source code any way that you wish once you have obtained a copy locally, so I'm unsure what else to say other than it would appear that the software Norton have sold you is not providing you value for money and is also causing you frustration instead as well.

**Comment by JEJ0** [comment]
As I pointed out this has been reported repeatedly in the past, and closed with no explanation or correction.  Specifically, #3345 is clear that it is much more widespread.  I'd focus less on Norton, per se, based on these prior reports.

The initial issue is the issuance of telemetry without opt-in.  It is, in fact, that telemetry that is causing the image to be considered suspect.

Furthermore, vcpkg is recommended by Microsoft (e.g. see https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=vs-2019 as an example).  I was, and am, surprised that Microsoft is recommending a solution that performs telemetry by default.  And one that does not have a clear statement that it is taking telemetry, exactly what telemetry it is taking, and does not have a very clear opt-out.

Now, can I fork the code to do whatever I want?  Sure.  Can I propose a fix?  Sure. Does that change the surprise at the telemetry by default and the lack of visibility, or that this has been reported for over a year?  Not really.

**Comment by timautry** [comment]
There are several options you may try to solve the problem:
1. Run the bootstrap process with the ".\boostrap-vcpkg.bat -disableMetrics"  option to compile vcpkg without metrics.
2. Tell Norton not to scan the vcpkg.exe executable
3. Tell Norton not to scan the directory/folder containing vcpkg.exe

**Comment by JEJ0** [comment]
My workaround was to tell Norton to reverse the quarantine decision and to not scan the metrics upload image.

Maybe I'm the only person bothered by the opaque decision to have this process upload data from my machine to some remote site.  But I am bothered by it.

I can surely support a ".\bootstrap-vcpkg.bat -enableMetrics" approach.  Or an approach that directly asks at the start of the bootstrap process if I want to upload metrics and either directly disclose, or be able to disclose, what will be uploaded.

**Comment by heydojo** [comment]
@JEJ0 

https://github.com/microsoft/vcpkg/blob/7d72108b9a09e92342ff695c074766fb068049df/docs/about/privacy.md

>  I'd focus less on Norton, per se, based on these prior reports.

This is the incorrect approach based upon your issue.

Because:

> Your software (Norton) has established a false positive in it's threat detection.

And one single other bug report:

> Specifically, #3345 is clear that it is much more widespread.

Does not validate your position. Your logic fails to accommodate the fact that AV software (especially badly maintained, poorly coded AV software) is highly prone to false positive detection rates. The simple solution since the false positive problem was identified (decades ago) has been to report the false positive to the manufacturer using (commonly) their automatic reporting tool.
I have already suggested that you do this and yet you persist to assert that your problem is one of Microsoft's making.

>  I was, and am, surprised that Microsoft is recommending a solution that performs telemetry by default.

I'm sorry but if you were unaware, telemetry by default is how Windows 10 is shipping too. It is the default position of Microsoft products to do so.
If you do not like this behaviour (and I personally find it repugnant) then turn it off. The method to do so, as already mentioned is `-disableMetrics`.

> Now, can I fork the code to do whatever I want? Sure. Can I propose a fix? Sure.

Both rhetorical questions.

> Does that change the surprise at the telemetry by default and the lack of visibility, or that this has been reported for over a year?

And yet according to your report:

> This is not the level of security awareness I expect Microsoft to have.

Please don't attempt to change the topic of this thread. We get it. You don't like metrics.
False positive detections by AV products have nothing to do with Microsoft's level of security awareness. You can report false positives to AV product manufacturers. And you can also turn off vcpkg's metrics using a single switch. This in turn should prevent the false positive triggering.

Let us know how you get on.
Thanks.

**Comment by Rastaban** [comment]
It is annoying that Norton flags the metrics uploader, but at this time there is no solution that works for the team at this time.  The uploader cannot be qualified by the major anti-virus vendors because it is built on the end users machine and is not signed.  We have discussed fiddling with the implementation of the uploader, but have decided against it because we don't want to obfuscate the code.  Also tricks that may work now could end up backfiring later.  Making the metrics uploader opt-in rather than opt-out does not solve the anti-virus issue either, it only makes it less noticeable.

In response to your concerns of the collection of usage metrics, I refer you to the privacy policy: https://github.com/Microsoft/vcpkg/blob/master/docs/about/privacy.md.
