### ISSUE TITLE
[New port request] dbus

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#7261]
D-Bus specification and reference implementation, including libdbus and dbus-daemon

https://gitlab.freedesktop.org/dbus/dbus

**deps** win32: `xsltproc.exe, docbook-xml, docbook-xsl, doxygen`

test win x64 dynamic, ok

[d-bus.zip](https://github.com/microsoft/vcpkg/files/3390435/d-bus.zip)

https://pages.lip6.fr/Jean-Francois.Perrot/XML-Int/Session1/WinLibxml.html
https://www.zlatkovic.com/libxml.en.html

libxml2 `+` tools `=` xmllint.exe
libxslt `+` tools `=` xsltproc.exe

docbook-xsl
https://github.com/docbook/xslt10-stylesheets

docbook-xml
https://www.docbook.org/xml/5.0/docbook-5.0.zip

**Comment by heydojo** [comment]
Not seeing a use case for this layer beyond Linux.
Interested to know the rationale.

AFAIK applications ported from Linux which use dbus there don't get dbus on Windows because Windows already has it's own IPC layer.
Win64 should be the default target. Not 32 (it's 2019 - XP from 2000 even had a 64 bit version.)

`xsltproc.exe, docbook-xml, docbook-xsl, doxygen`

Building the documentation and requiring the documentation build dependencies should be optional. The documentation is available online.

Maybe it's time to consider a triplet to control the building of arbitrary documentation?

**Comment by Voskrese** [comment]
kf5 or qt require this bilyatoque, this time. on the account of documentation, it's not for documentation. xml markup
