### ISSUE TITLE
Angle is not built for UWP

### ISSUE THREAD

**Issue by konsoletyper** [microsoft/vcpkg#7264]
# Steps to reproduce

* Clone latest vcpkg
* Run `bootstrap-vcpkg.bat`
* Run `vcpkg.exe install angle:x64-uwp`

# Actual behaviour

Vcpkg produces following error:

```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/Users/konsoletyper/devel/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: C:/Users/konsoletyper/devel/vcpkg/buildtrees/angle/x64-uwp-dbg
    See logs for more information:
      C:\Users\konsoletyper\devel\vcpkg\buildtrees\angle\install-x64-uwp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/angle/portfile.cmake:35 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)


Error: Building package angle:x64-uwp failed with: BUILD_FAILED
```

# Expected behaviour

Vcpkg installs Angle successfully.

# Additional notes

Looks like it's regression introduced by 7a3818f575fadf1ded97244f803930fe2464f190#diff-f08e5b272610fce9183fc679c06667e3.

**Comment by JackBoosY** [comment]
Windows uwp does NOT currently support pipe, which is the main reason for the build failure.
I am not sure what problem will be caused by disabling the pipe code of angle under uwp, so this issue is more reasonable by official fix.

See [documentation](https://docs.microsoft.com/en-us/uwp/win32-and-com/alternatives-to-windows-apis-uwp).

**Comment by konsoletyper** [comment]
@JackBoosY I don't care for the reason. I only care for Angle working in my project. What additional steps should I take to force this issue fixed? Should I report it somewhere else? Who is responsible for Angle package?

**Comment by JackBoosY** [comment]
@konsoletyper `Google::angle` does not support uwp. In the previous versions, we supported uwp by modifying its source files (commenting some code and replacing some functions in _ports/angle/001-fix-uwp.patch_), but now more code needs to be changed due to source upgrades.

I don't know what it would be to just comment on the pipe-related code. So please report this to [google](https://bugs.chromium.org/p/angleproject/issues/list).

Thanks.

**Comment by JackBoosY** [comment]
Fixed.
