### ISSUE TITLE
vcpkg port CZMQ giving runtime error on Ubuntu (18.04)

### ISSUE THREAD

**Issue by Formulator** [microsoft/vcpkg#7308]
@myd7349 recently ported  `CZMQ` to vcpkg.

To test the port and the remote build capability of `VS2019-CMake-vcpkg`  I took one of my existing apps which has a `CZMQ` dependency and from `Windows 10` performed a build of my app on a remote `Ubuntu` `64bit` machine linked against the `vcpkg` `CZMQ` library.  The build reported success.

However, there is a run-time error related to the CURVE message encryption.  My app can be run with or without CURVE security.  When CURVE is enabled on `Ubuntu` my `vcpkg` `CZMQ` linked app crashes whenever it detects the presence of a networked counterpart and prints:

Illegal instruction (core dumped).

When CURVE is disabled the app runs fine.

This app is created from well tested source code which I know is functional.  Indeed by swapping to a `Windows x86` build with the same source and `Windows` installation of `vcpkg` the app builds and runs as it should, CURVE or no CURVE.

To investigate this matter further & rule out other factors I used the same source code to perform a native build on the `Ubuntu` machine and linked against the `Ubuntu` `libczmq-dev` package.

The natively built app is fully operational on `Ubuntu` with and without CURVE.

My vcpkg installations were created like so:

`./vcpkg install zeromq[sodium]`
`./vcpkg install czmq`

The use of `sodium` is important as in the past I have found it to accommodate a higher rate of message throughput.

All this leads me to believe that there is an issue causing the `vcpkg` build of `CZMQ` to malfunction on `Linux`.

**Comment by myd7349** [comment]
Hi! @Formulator Thanks for the report!
It is in #5600 that I migrated the build system of `libsodium` to CMake so that it can be installed on Linux/macOS easily with `vcpkg`. I think it is possible that I made a mistake in `libsodium`'s `CMakeLists.txt` that causes this core dump. Though I tested the `CMakeLists.txt` with `libsodium`'s test suits(and all tests passed), there still might be some points that got missed. 
Could you give this a test?
1. ./vcpkg install libsodium
    Then we will get `libsodium.a` under both `installed/x64-linux/lib` and `installed/x64-linux/debug/lib`.
2. Build `libsodium` by using the official build system
    ```
    ./autogen.sh
    ./configure
    make
    make install
    ```
    Then we get `libsodium.a` under `/usr/local/lib`
3. Replace `libsodium.a` we got in step 1(both the debug and release version) with the one we got in step 2
4. ./vcpkg install zeromq[sodium]
5. ./vcpkg install czmq
6. Run your app again. If the problem disappears, then it confirms my guess above.

**Comment by Formulator** [comment]
@myd7349 inspired guess!  That made the problem disappear and my app now runs as intended on Ubuntu with CURVE security enabled.

A few extra details of what I did:
1.  I used the 'autogen.sh' found under `vcpkg/buildtrees/libsodium/src/1.0.18-20c5988cfb`
2. Needed elevated privileges like so: `sudo make install`
3. Needed to rebuild my app before the fix worked.

**Comment by myd7349** [comment]
@Formulator Thanks for your reply! I will look into it as soon as possible.

**Comment by dg0yt** [comment]
Stale issue?
Anyways, #36800 suggests using the official build systems for port `libsodium`.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Now `libsodium` use the official build systems, please update vcpkg and rebuild it. If this issue still exist, please reopen.
