### ISSUE TITLE
Can't use glm?

### ISSUE THREAD

**Issue by Swoorup** [microsoft/vcpkg#732]
I think this is a cmake issue? 

But

```
cmake_minimum_required(VERSION 3.6)
project (astha)


find_package(glm REQUIRED)

link_libraries(glm)
add_executable(astha main.cpp)
```

And I get this?
```
CMake Error at CMakeLists.txt:5 (find_package):
  By not providing "Findglm.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "glm", but
  CMake did not find one.

  Could not find a package configuration file provided by "glm" with any of
  the following names:

    glmConfig.cmake
    glm-config.cmake

  Add the installation prefix of "glm" to CMAKE_PREFIX_PATH or set "glm_DIR"
  to a directory containing one of the above files.  If "glm" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "C:/msys64/home/Swoorup/projects/astha/build/CMakeFiles/CMakeOutput.log".
```

**Comment by ras0219-msft** [comment]
It would seem that cmake doesn't have a built-in module for Glm. Because it is a header only library, we aren't generating the config files either.

doesn't have a built in cmake module nor does it provide cmake config files. You'll unfortunately need to fall back to calling something like `find_path(GLM_PATH glm/glm.h)` and then including `GLM_PATH`.

*Note: I don't actually know the right header name, so make sure to fix that in your cmake.*

Also, I noticed your root directory is C:/msys64. Note that vcpkg uses the MSVC toolchain and will _not_ generally work with mingw. If you'd like to use mingw, you'll need to install the correct devel packages from something like msys2.

**Comment by Swoorup** [comment]
I am not using mingw compiler, it just happens that I installed vcpkg in that folder.

**Comment by PhoebeHui** [comment]
Document has added to VCPKG, see https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md#handling-libraries-without-native-cmake-support

**Comment by jiuqing1851** [comment]
so how to resolve

**Comment by sfhacker** [comment]
This issue is from 2017! God save us all!

**Comment by lintianfang** [comment]
> so how to resolve

So you solve this issue?

**Comment by lintianfang** [comment]
> so how to resolve

@jiuqing1851 Do you solve this issue? Thank you
