### ISSUE TITLE
make patch failure (during port install) an error

### ISSUE THREAD

**Issue by crusader-mike** [microsoft/vcpkg#7321]
I noticed that during clean `vcpkg install <list-of-libs>` there are quite a few "patch failed" messages. This isn't good. If patch failed, but it works -- then why patch at all? If it doesn't work -- why installation continues as if nothing happened?

I've seen the message "this may be ok if patch was already applied" (or something to that effect), but (1) it was a clean install (2) we probably shouldn't have this situation at all -- it leads to "port rot", where port gets "stale" with time accumulating non-functioning patches that nobody pays attention anymore.

**Comment by crusader-mike** [comment]
Clarification:
- make patch failure (during port install) an error
- get rid of situations that could lead to patch failure (i.e. repeated application of patch, etc)

**Comment by NancyLi1013** [comment]
Hi @crusader-mike 
Thanks for posting this issue.
In the current status, there will be no "patch failed" messages if the patch does apply well. It will post the specific details if there is something wrong with the patch.

Please update vcpkg to the latest version and rebuild it.

I'm closing this issue for now since it has been solved.

**Comment by crusader-mike** [comment]
@NancyLi1013 So, if patch fails -- does "install" operation fails too?

**Comment by NancyLi1013** [comment]
Yes, you're right. If patch fails, the install process will stop.
