### ISSUE TITLE
[gtk:x86/x64_windows] build failure

### ISSUE THREAD

**Issue by z-ninja** [microsoft/vcpkg#7352]
**Host Environment**
- OS: windows 7
- Compiler: visual studio 2015

**To Reproduce**
vcpkg install gtk:x86-windows

**Failure logs** 
The following packages will be built and installed:
  * atk[core]:x86-windows
  * cairo[core]:x86-windows
  * dirent[core]:x86-windows
  * expat[core]:x86-windows
  * fontconfig[core]:x86-windows
  * freetype[core]:x86-windows
  * gdk-pixbuf[core]:x86-windows
  * gettext[core]:x86-windows
  * glib[core]:x86-windows
    gtk[core]:x86-windows
  * harfbuzz[core,glib,ucdn]:x86-windows
  * libepoxy[core]:x86-windows
  * libffi[core]:x86-windows
  * libiconv[core]:x86-windows
  * libpng[core]:x86-windows
  * pango[core]:x86-windows
  * pcre[core]:x86-windows
  * pixman[core]:x86-windows
  * ragel[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/19: libepoxy:x86-windows
Building package libepoxy[core]:x86-windows...
CMake Error at scripts/ports.cmake:67 (file):
  file problem creating directory: C:/vcpkg-master/buildtrees/libepoxy

Error: Building package libepoxy:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libepoxy:x86-windows
  Vcpkg version: 2019.07.18-nohash

Additionally, attach any relevant sections from the log files above.
**Additional context**
Disappointing

**Comment by cenit** [comment]
Do you have privileges to read/write in that folder? Looks like you expanded vcpkg-master.zip through explorer.
Better to clone it using git from command line

- open Powershell
- go to your preferred folder (better if you have privileges to write there, in c:\ usually you have not, but in user sub folders yes, otherwise you should just take ownership of your preferred folder)
- git clone https://github.com/microsoft/vcpkg
- bootstrap
- retry your install command

**Comment by z-ninja** [comment]
OMG. I am a moron. 
I left out of disc space on my virtual machine.
Everything is ok.
Sorry for disturbance.

**Comment by cenit** [comment]
No problem. Just close both issues!
