### ISSUE TITLE
[libpqxx] find_package failure

### ISSUE THREAD

**Issue by qqrm** [microsoft/vcpkg#7485]
find_package didnt work for libpqxx in cmake

work:
```
find_package( yaml-cpp )
find_package( protobuf )		
```		

didnt work:
```
find_package( libpq )
find_package( libpqxx )
find_package( pq )
find_package( pqxx )
```
How include libpqxx with cmake? Is it bug?

**Environment**
- OS: Windows 10
- Compiler: Visual C++ 2019 16.2.0
- Vcpkg package management program version 2019.07.18-nohash

**Comment by ahmedskhalil** [comment]
you can find the Postgrepsql by typying:
 `find_package( PQXX REQUIRED )`

then include the discovered directories:
`include_directories( ${PQXX_INCLUDE_DIRECTORIES} )`

and then link the libraries to your project:
`target_link_libraries(${YOUR_PROJECT_NAME}  ${PQXX_LIBRARIES} )`

**Comment by qqrm** [comment]
```
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:266 (_find_package):
  By not providing "FindPQXX.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PQXX", but
  CMake did not find one.

  Could not find a package configuration file provided by "PQXX" with any of
  the following names:

    PQXXConfig.cmake
    pqxx-config.cmake

  Add the installation prefix of "PQXX" to CMAKE_PREFIX_PATH or set
  "PQXX_DIR" to a directory containing one of the above files.  If "PQXX"
  provides a separate development package or SDK, be sure it has been
  installed.

```

**Comment by ahmedskhalil** [comment]
that's because there aren't any `PQXXConfig.cmake` found in the root direcotry of `PQXX`

You'd either wanna write your own find module for cmake to locate the headers and the lib like so:

`# Finding libpqxx
# Once done this will define
#  PQXX_FOUND - System has PQXX
#  PQXX_INCLUDE_DIRS - The PQXX include directories
#  PQXX_LIBRARIES - The libraries needed to use PQXX
#  PQXX_DEFINITIONS - Compiler switches required for using PQXX

find_package(PkgConfig)
pkg_check_modules(PC_LIBPQXX QUIET libpqxx)
set(PQXX_DEFINITIONS ${PC_LIBPQXX_CFLAGS_OTHER})

find_path(PQXX_INCLUDE_DIR libpq.h
          HINTS ${PC_LIBPQXX_INCLUDEDIR} ${PC_LIBPQXX_INCLUDE_DIRS}
          PATH_SUFFIXES libpqxx )

find_library(PQXX_LIBRARY NAMES libpqxx
             HINTS ${PC_LIBPQXX_LIBDIR} ${PC_LIBPQXX_LIBRARY_DIRS} )

include(FindPackageHandleStandardArgs)
# handle the QUIETLY and REQUIRED arguments and set PQXX_FOUND to TRUE
# if all listed variables are TRUE
find_package_handle_standard_args(LibPQXX  DEFAULT_MSG
                                  PQXX_LIBRARY PQXX_INCLUDE_DIR)

mark_as_advanced(PQXX_INCLUDE_DIR PQXX_LIBRARY )

set(PQXX_LIBRARIES ${PQXX_LIBRARY} )
set(PQXX_INCLUDE_DIRS ${PQXX_INCLUDE_DIR} )
`

or specify the location of the header and the library in your `CMakeLists.txt` like so:

`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -lpqxx -lpq")

set(PQ_INCLUDE_DIR ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include/libpq)
set(PQXX_INCLUDE_DIR ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include/pqxx)

set(PQXX_LIB ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/pqxx)
set(PQ_LIB ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libpq)

find_library(PQXX_LIB pqxx)
find_library(PQ_LIB pq)
`

then inlcude the directories:

`include_directories(${PQ_INCLUDE_DIR} ${PQ_INCLUDE_DIR})`

and finally target link the library to your project according your needs.

**Comment by JackBoosY** [comment]
Hi @qqrm, thanks for reporting this issue.
Since libpqxx does not officially support building with cmake, libpqxx_config.cmake is not given.
You can temporarily use the following code to find libpqxx:
```
find_path(libpqxx_INCLUDE_DIR /pqxx/pqxx)
include(SelectLibraryConfigurations)
find_library(libpqxx_LIBRARY_RELEASE NAMES libpqxx)
find_library(libpqxx_LIBRARY_DEBUG NAMES libpqxxd)
select_library_configurations(libpqxx)
```

Thanks.

**Comment by gnaggnoyil** [comment]
@JackBoosY Does this mean that XXXXX_config.cmake file won't be provided by VcPkg if the library is built with build processes other than CMake? If so, such behavior is a bit weird.

**Comment by JackBoosY** [comment]
@gnaggnoyil Libpqxx does not officially support cmake, but now it is built using our **CMakelists.txt**(_vcpkg/ports/libpqxx/CMakeLists.txt_). In this case we need to manually add the 
**config.cmake** file to it, which is why I marked the port feature for this issue.

**Comment by zhuji-fudan** [comment]
> Hi @qqrm, thanks for reporting this issue.
> 
> Since libpqxx does not officially support building with cmake, so **libpqxx_config.cmake** is not given.
> You can temporarily use the following code to find libpqxx:
> 
> ```
> find_path(libpqxx_INCLUDE_DIR /pqxx/pqxx)
> include(SelectLibraryConfigurations)
> find_library(libpqxx_LIBRARY_RELEASE NAMES libpqxx)
> find_library(libpqxx_LIBRARY_DEBUG NAMES libpqxxd)
> select_library_configurations(libpqxx)
> ```
> 
> Thanks.

Hello, I follow your hints and add
```
target_link_libraries(research PRIVATE ${PQXX_LIBRARIES} ${PQ_LIBRARIES})
```
It turns out 
```
CMakeFiles/research.dir/gen_seri_data.cpp.o: In function `pqxx::internal::basic_transaction::~basic_transaction()':
/home/ji/libs/vcpkg/installed/x64-linux/include/pqxx/transaction.hxx:31: undefined reference to `pqxx::dbtransaction::~dbtransaction()'
```

Could you please tell me how to locate pqxx and pq libraries?

**Comment by JackBoosY** [comment]
@zhuji-fudan You should use `${libpqxx_LIBRARIES}` instead of `${PQXX_LIBRARIES}`.
