### ISSUE TITLE
Change hdf5 package to use normal build specifications. 

### ISSUE THREAD

**Issue by Iluinrandir** [Microsoft/vcpkg#755]
the current hdf5 package has non default build settings and depends on msmpi.
Please rename current package to hdf5-mpi/hdf5-parallel or something similar and use default/normal build settings for the hdf5 package.

**Comment by albertziegenhagel** [comment]
Is there any reason the additional parallel support is a problem for you? Even with parallel support enabled HDF5 should be usable in sequential, non-mpi code, as usual. The only reason I can see is that the C++ bindings are not compatible with parallel. Do you need those?

I don't think that just renaming the port to hdf5-parallel and having a default hdf5 port will work, since both packages will install the same headers and therefor will be in conflict.

**Comment by Iluinrandir** [comment]
Exactly, I use the c++ bindings.
Having both packages is not a real problem because you do not need to install both at the same time.
I would install the hdf5 package and you would install the hdf5-parallel package. 
If I ever need the parallel version:
vcpkg remove hdf5 followed by vcpkg install hdf5-parallel
Maybe a flag can be set somewhere to define conflicting packages and ask automatically if the conflicting packages should be removed or at least warn me about it.

**Comment by ras0219-msft** [comment]
Having side-by-side packages is not a good solution to this problem in general, because
- You need 2^N packages for N different configuration switches
- Other packages can no longer meaningfully depend on `hdf5`; most packages don't care about what options you've picked, but because you've encoded options into the name they are _forced_ to care.

We're definitely aware of this problem though! Being forced to install MSMPI when you only need the non-parallel hdf5 is really unfortunate. We are working on a solution, but for now the best workaround we can offer is for you to copy the existing `ports\hdf5\` to `ports\hdf5-nompi\` and modify it according to your needs.

**Comment by nagua** [comment]
It would be really cool, if we can have a system similar to gentoos portage. There you can specify different use flags that determine what features should be enabled in a package to be build. Also you can specify which (supported) version of the package you want to install.

In many ways vcpkg and gentoo's portage are very similar. In case you didn't do that already you should really take a look how the system works and if something of that is usefull enough to be adapted to vcpkg.

**Comment by stekyne** [comment]
Any update on this? It's a real pain when using this package to have to install something outside of VCPKG.

**Comment by ras0219-msft** [comment]
Sorry for the delay on this! We have officially published feature packages, so msmpi is no longer a requirement to build hdf5!
```
D:\src\vcpkg> vcpkg search hdf5
hdf5                 1.10.1-1         HDF5 is a data model, library, and file format for storing and managing data
hdf5[parallel]                        parallel support for HDF5
hdf5[cpp]                             Builds cpp lib
highfive             1.5              HighFive is a modern C++/C++11 friendly interface for libhdf5

If your library is not listed, please open an issue at and/or consider making a pull request:
    https://github.com/Microsoft/vcpkg/issues
```
