### ISSUE TITLE
[boost-fiber] build failure with VCPKG_BUILD_TYPE release

### ISSUE THREAD

**Issue by josch** [microsoft/vcpkg#7559]
Hi, I'm building boost-fiber on appveyor with Visual Studio 2017. Before the build starts I do:

    echo.set(VCPKG_BUILD_TYPE release)>> C:\Tools\vcpkg\triplets\x64-windows.cmake

but this leads to a build failure of boost-fiber:

```
Starting package 70/115: boost-fiber:x64-windows
Building package boost-fiber[core]:x64-windows...
-- Downloading https://github.com/boostorg/fiber/archive/boost-1.70.0.tar.gz...
-- Extracting source C:/Tools/vcpkg/downloads/boostorg-fiber-boost-1.70.0.tar.gz
-- Using source at C:/Tools/vcpkg/buildtrees/boost-fiber/src/ost-1.70.0-57b4c46dd0
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: C:/Tools/vcpkg/installed/x64-windows/tools/boost-build/b2.exe --stagedir=C:/Tools/vcpkg/buildtrees/boost-fiber/x64-windows-rel/stage --build-dir=C:/Tools/vcpkg/buildtrees/boost-fiber/x64-windows-rel --user-config=C:/Tools/vcpkg/buildtrees/boost-fiber/x64-windows-rel/user-config.jam -j2 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q -sZLIB_INCLUDE="C:/Tools/vcpkg/installed/x64-windows/include" -sBZIP2_INCLUDE="C:/Tools/vcpkg/installed/x64-windows/include" threading=multi threadapi=win32 runtime-link=shared link=shared address-model=64 architecture=x86 toolset=msvc -sZLIB_BINARY=zlib -sZLIB_LIBPATH="C:/Tools/vcpkg/installed/x64-windows/lib" -sBZIP2_BINARY=bz2 -sBZIP2_LIBPATH="C:/Tools/vcpkg/installed/x64-windows/lib" variant=release debug-symbols=on
    Working Directory: C:/Tools/vcpkg/buildtrees/boost-fiber/src/ost-1.70.0-57b4c46dd0/build
    Error code: 1
    See logs for more information:
      C:\Tools\vcpkg\buildtrees\boost-fiber\build-x64-windows-rel-out.log
Call Stack (most recent call first):
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:278 (vcpkg_execute_required_process)
  ports/boost-fiber/portfile.cmake:19 (boost_modular_build)
  scripts/ports.cmake:74 (include)
Error: Building package boost-fiber:x64-windows failed with: BUILD_FAILED
```

Or, a maybe more meaningful excerpt:

```
error: at C:/Tools/vcpkg/installed/x64-windows/tools/boost-build/src/kernel\modules.jam:107
error: Unable to find file or target named
error:     '/boost//C:/Tools/vcpkg/installed/x64-windows/debug/lib/boost_context-vc140-mt-gd.lib'
error: referred to from project at
error:     '..'
```

Naively, it seems that the problem is, that it looks for a file in `x64-windows/debug` which obviously is empty because we set `VCPKG_BUILD_TYPE` to `release`.

Here is the full log:

https://ci.appveyor.com/project/josch/3dtk/builds/26484351

**Comment by josch** [comment]
This issue is reproducible in a fresh Windows 10 1903 machine with Visual Studio 2017 on vcpkg git HEAD.

To make this issue reproducible for you I created https://github.com/josch/vcpkg-boost-release-test which essentially runs the following script on appveyor:

     git clone https://github.com/microsoft/vcpkg.git
     cd %APPVEYOR_BUILD_FOLDER%\vcpkg
     git reset --hard %COMMIT%
     git status
     git show HEAD --no-patch
     echo.set(VCPKG_BUILD_TYPE release)>> %APPVEYOR_BUILD_FOLDER%\vcpkg\triplets\x64-windows.cmake
     call bootstrap-vcpkg.bat
     %APPVEYOR_BUILD_FOLDER%\vcpkg\vcpkg.exe version
     %APPVEYOR_BUILD_FOLDER%\vcpkg\vcpkg.exe --triplet x64-windows install boost

Where `%COMMIT%` is the earliest commit I found that didn't error out earlier (commit 3d87ec6 from August 2018) and `HEAD`, respectively. Both fail with the same error.

**Comment by josch** [comment]
Something I only noticed now: There is a weird `/boost/` prefix in front of an absolute path in the log output I pasted above. Maybe something gets concatenated wrongly?

**Comment by josch** [comment]
Additionally, as you can see in this test output:

https://ci.appveyor.com/project/josch/vcpkg-boost-release-test/builds/26516306/job/gi9bq43yylodnhj2

Even if the `/boost/` prefix were stripped, the requested file `boost_context-vc140-mt-gd.lib` does not exist in the `debug/lib` folder (as expected because we are doing a release build).

**Comment by RemiDav** [comment]
Did anyone find a workaround to make this work until it is fixed in vcpkg ?

**Comment by heydojo** [comment]
> 
> 
> Did anyone find a workaround to make this work until it is fixed in vcpkg ?

@RemiDav 
I just came across this issue.
Use a fresh copy of vcpkg to test the following:

Delete the options `--debug-configuration` `--debug-building` `--debug-generators` from the file **boost-modular-build.cmake**
https://github.com/microsoft/vcpkg/blob/master/ports/boost-modular-build-helper/boost-modular-build.cmake#L156

Also change `debug-symbols=on` to `debug-symbols=off` in the same file
https://github.com/microsoft/vcpkg/blob/master/ports/boost-modular-build-helper/boost-modular-build.cmake#L304

Change `debug-symbols=on` to `debug-symbols=off` in the file **CMakeLists.txt**
https://github.com/microsoft/vcpkg/blob/master/ports/boost-modular-build-helper/CMakeLists.txt#L158

Then delete every single line containing `<variant>debug` inside the file **Jamroot.jam**
https://github.com/microsoft/vcpkg/blob/master/ports/boost-modular-build-helper/Jamroot.jam

Delete whole lines in that file, every single one which contains `<variant>debug`. Not just the string on it's own.

I have no idea what's going wrong, so a maintainer will have to take a look. It's fairly easy to test.

I tested using `vcpkg install boost-fiber:x64-windows` which fails to build if you set configuration to release via triplet unless you make my changes.

I haven't offered a patch because my solution is pretty hacky and it needs the author of the port or someone who is familiar with boost to make the changes in my opinion.

I observed that once you start to build boost packages, the files inside ports/boost-modular-build-helper moves to the directory installed\x64-windows\share\boost-build so that's why I recommend a fresh copy of vcpkg to try this out with. If that's not possible for you, you should purge all of your installed vcpkg boost packages and vcpkg boost build trees first before trying to follow the steps above.

**Comment by heydojo** [comment]
@ras0219-msft would you mind taking a look please? I notice you have some history with this port.
It's fairly easy to test. Add `set(VCPKG_BUILD_TYPE release)` to **triplets/x64-windows.cmake** and then use `vcpkg install boost-fiber:x64-windows` to see the point of failure.

To observe my hack, complete the same steps again with a fresh copy of vcpkg and follow my instructions above to see an approximation of what needs to change.

Thanks in advance for any help!

**Comment by josch** [comment]
I can confirm that the first commit from https://github.com/microsoft/vcpkg/pull/9224 fixes this issue.

**Comment by PhoebeHui** [comment]
The PR has been merged, pleasse get latest source and try agin.
