### ISSUE TITLE
[date] Resolve link error to date::locate_zone

### ISSUE THREAD

**Issue by degski** [microsoft/vcpkg#7591]
~~I don't know what the solution is, but~~ https://github.com/HowardHinnant/date/issues/398 is the problem.

EDIT: It looks like the port's `CMakeLists.txt` file does not deal with compiling for C++17 (std is set to C++11), then thereafter (when called), from a program compiled with C++17, now all of a sudden `std::string_view` is defined, but that overload is not available.

I've for now `plugged` the file for my purposes, but it should obviously be done correctly (I'm not qualified).

[CMakeLists.txt](https://github.com/microsoft/vcpkg/files/3480057/CMakeLists.txt)

**Comment by MonicaLiu0311** [comment]
At present, the upstream has [set C++17 in CMakeLists](https://github.com/HowardHinnant/date/blob/v3.0.1/CMakeLists.txt#L28). I successfully build and link to my library after trying it locally. 


Fixed by [upstream#492](https://github.com/HowardHinnant/date/pull/492), https://github.com/microsoft/vcpkg/pull/11968.
