### ISSUE TITLE
[easyhook] support static build

### ISSUE THREAD

**Issue by mmhatami** [microsoft/vcpkg#7676]
Library name: easyhook

Library description:

Source repository URL: https://github.com/EasyHook/EasyHook

Project homepage (if different from the source repository):

Please Add static easyhook library

**Comment by mmhatami** [comment]
@JackBoosY thanks

**Comment by mmhatami** [comment]
please support static build of easyhook @JackBoosY

**Comment by JackBoosY** [comment]
Blocked by [#260](https://github.com/EasyHook/EasyHook/pull/260) [#138](https://github.com/EasyHook/EasyHook/issues/138).

**Comment by lanyizi** [comment]
Besides static build, it's also desirable to have a dynamic version of EasyHook that is available when using static triplets.
Injected DLLs often needs to be self-contained (it should not reference any 3rd party DLLs) because the dependencies of injected DLL is usually not inside the target process's DLL search path. Linking to (the dynamic version of) EasyHook will be fine, because EasyHook will load itself into the target process beforehand.

This means we need to build our library with the static triplet, but currently EasyHook cannot be installed using static triplet..

**Comment by JackBoosY** [comment]
Close this PR until upstream fixes this.
