### ISSUE TITLE
Boost with external dependencies

### ISSUE THREAD

**Issue by albertziegenhagel** [microsoft/vcpkg#78]
Currently building boost includes only the default packages.
- boost.python is explicitly disabled via "--without-python" in the current port file.
- boost.mpi would have to be enabled by changing the user-config.jam (http://www.boost.org/doc/libs/1_61_0/doc/html/mpi/getting_started.html#mpi.config)
- boost.iostreams allows to enable additional compression filters for zlib, gzip and bzip2 via environment variables or explicit arguments when calling b2 (http://www.boost.org/doc/libs/1_61_0/libs/iostreams/doc/installation.html)
- I don't know whether there are any other boost libraries that take additional parameters

As far as I understood vcpkg does not yet support passing arguments to the port files to enable additional components at all. This could not only be interesting for boost, but for all packages in general.

**Comment by ras0219-msft** [comment]
First, Boost in particular:

The reason why boost.python is disabled is that I am unfamiliar with the library and how it needs to relate to your particular build of `python.exe` and `libpython.dll`. I am conservatively assuming that it must be built against your specific copy of `libpython`, which is itself specific to your version of `python.exe`. In this case, since we aren't building the `python.exe` you'd actually deploy in production, I don't think we can effectively package boost.python. I would love an expert here to come by and explain the situation clearly so we can make the right determination. I hope I'm being overly conservative above!

We should enable MPI, unless there are compelling reasons not to. For boost.iostreams, we should enable bzip2 compression once `libbz2` is available.

Second, the more general scope:

I think our default stance should be to build with all the (secure) capabilities by default, making it suitable without modification for the widest audience -- the same as other systems package managers. 

Today, you can modify the build options by changing the portfile itself. However, in the future, I'm sure we'll need to have a more convenient way to specify options that conflicts less with pulling down new portfile versions. I am biased against adding command line options to `install` because I believe that path leads to hard-to-reproduce state, unless the command also records the options into some version controlled file.

**Comment by mmassing** [comment]
See #330 for a patch which adds zlib support in iostreams.

**Comment by rwebber** [comment]
I have found installing boost.python rather difficult and would greatly appreciate it if vcpkg could simplify the process.

**Comment by wrosecrans** [comment]
One nice thing is that libpython exports a strictly C API, which simplifies ABI compatibility compared to a C++ API.  Boost.Python does need to be built with the right version of the Python library, but binary compatibility with Python.exe only matters if you intend to distribute a Python module.  If you are trying to embed a Python runtime into a C++ application then you don't have any reason to care about python.exe, because your own exe is the only one that matters.  So there is definitely a use case for a Boost.Python linked to a libpython that is completely private to a Vcpkg install if that simplifies getting something working.

I haven't had problems using the msvc14.0-64 Windows boost binaries from https://sourceforge.net/projects/boost/files/boost-binaries/

With Python27 from here:
https://www.python.org/downloads/windows/

Without any special concern about which python lib is being linked with.  It seems to have "just worked" for me.  In the case of building modules, since the interface between Python.exe and your module is all in C, I think the difficulties of C++ ABI wouldn't really com into play.  That's all internal to the dll you've built, but c++ symbols need not be exposed publicly at all.  I don't have practical experience making bare python modules to shipped out and put into existing Python installs though, so my understanding of that use case is a bit theoretical.

**Comment by wrosecrans** [comment]
For kicks, I decided to try to figure out how hard it would be to get Boost.Python working.  I started with the main boost port and substituted --without-python for --with-python

A bit of tinkering later, and I have something that mostly works.  It automatically detected my standard Python install in C:\Python27, but I have done nothing to try to install it if it isn't found.  I also haven't figured out how to make shared linkage work yet.  If anybody is curious, here's my commit:
https://github.com/wrosecrans/vcpkg/commit/0da6eda1969e0e08c283b925428ab305ed14b278

**Comment by alexkaratarakis** [comment]
@wrosecrans 
You can use `vcpkg_find_acquire_program(PYTHON2)` to verify that python is there and provide install links otherwise.

**Comment by ras0219-msft** [comment]
@albertziegenhagel 
> As far as I understood vcpkg does not yet support passing arguments to the port files to enable additional components at all.

We've just published a draft specification in PR #1205 which would enable optional components and should really nail this situation. Please take a look at it and let us know about any feedback you have!

**Comment by eelstork** [comment]
@ras0219-msft regarding your doubt: "I am conservatively assuming that it must be built against your specific copy of libpython, which is itself specific to your version of python.exe."
That is not the case. There is a version of boost python for python 2.x, another for python 3.x. As tested by @wrosecrans the sourceforge binaries just work, regardless of minor version differences.

What's making the sourceforge binaries especially relevant to this case (notwithstanding incompatibilities that I may not be aware of), is that they are standard, and recommended by Boost folks. The ability to install/configure optional components is great, but I believe building both `boost_python` and `boost_python3` is the correct default.

**Comment by rjoco** [comment]
ZLib support in boost.iostreams appears to be longer supported in the latest revision. References to ZLIB were removed from ports/boost/portfile.cmake and the equivalent code doesn't seem to be in boost-module.cmake...

**Comment by PhoebeHui** [comment]
Looks no discussion run its course and the issue can be closed, the original issue for boost.python boost.mpi and boost.iostreams solved now. please reopen this if I misunderstood something here.
