### ISSUE TITLE
vcpkg with cmake  not getting .exe file

### ISSUE THREAD

**Issue by vija9751** [microsoft/vcpkg#7832]
a source code which run on linux system the same code i want to make run on windows and is should get an .exe file   i have install vcpkg  ,visual studio 2015 ,git ,cmake done everything that mentioned in preprequisite in readme  every thing done Configuring done
Generating done  but it did'nt create .exe file 

after generating done   open project button goes to directly to visual studio 2015 still i have seen every file  but it could'nt create the .exe file which i want ?

**Comment by PhoebeHui** [comment]
@vija9751,  if I understand correctly, you are trying to generate VS solution by cmake, and build the source via VS IDE. You can set 'Configuration type' to Application (.exe) in property page to generate the .exe file.

It didn't create .exe file in configuration steps since it just config the something needed when build the project, if the source support in VCPKG, you can simply build the source via VCPKG, however, the .exe file be removed when install the port.

**Comment by PhoebeHui** [comment]
@vija9751, please reopen this if it still be an problem for you.
