### ISSUE TITLE
Change Compiler settings from MT to MD

### ISSUE THREAD

**Issue by Pantau123** [Microsoft/vcpkg#784]
Hi,
i want to build static Libs with the /MD Options. I had researched and i had found sparks of informations.
I had add under triplets/x86-windows-static.cmake the following:
set(CompilerFlags
        CMAKE_CXX_FLAGS
        CMAKE_CXX_FLAGS_DEBUG
        CMAKE_CXX_FLAGS_RELEASE
        CMAKE_C_FLAGS
        CMAKE_C_FLAGS_DEBUG
        CMAKE_C_FLAGS_RELEASE
        )
foreach(CompilerFlag ${CompilerFlags})
  string(REPLACE "/MT" "/MD" ${CompilerFlag} "${${CompilerFlag}}")
endforeach()
and compiled it against, but i have the old results.
Can anybody help me?

thx
Pantau 123

**Comment by ras0219-msft** [comment]
Hi Pantau123,

This should be as easy as copying `triplets\x86-windows-static.cmake` to a new file of your own name (`triplets\x86-windows-static-md.cmake`, for example). Then change the setting for `VCPKG_CRT_LINKAGE` to `dynamic` instead of `static`.

You may experience some issues in this configuration (portfiles that don't correctly respect that combination of options), so please do open new issues for any problems you encounter!

**Comment by Pantau123** [comment]
Thx it is functional
