### ISSUE TITLE
`create` treats all arguments as package specs

### ISSUE THREAD

**Issue by alzie** [Microsoft/vcpkg#79]
E.g. a command like

`.\vcpkg.exe create somepackage http://somewhere.com/somepackage.zip a:b:c.zip`

fails with

```
Error: Too many colons: a:b:c.zip
Example:
  vcpkg create zlib:x64-windows
```

Even though I admit that ```a:b:c.zip``` may not be a very good choice for the filename it should still be valid.

**Comment by ras0219-msft** [comment]
There's definitely a bug here w.r.t. the message output. However, the Win32 shell APIs actually don't accept filenames containing any of `/ \ : * ? " < > |`, so those characters do need to be filtered out (to get the list for yourself, try renaming a file to contain a `:` in explorer). 

We certainly should avoid calling `vcpkg_cmd_arguments::parse_all_arguments_as_package_specs()` in `create` since it really isn't accurate.

**Comment by alexkaratarakis** [comment]
a8b0651e50bf217e361789d1d6a59905309a3372
Fixed `vcpkg create` to parse arguments properly instead of treating them all as package specs.
Also add check for invalid characters so you get a better error message than what you would get if you let cmake touch the file and fail.
