### ISSUE TITLE
bootstrap-vcpkg.bat is not able to find the VS install

### ISSUE THREAD

**Issue by mmjr-x** [microsoft/vcpkg#7903]
**Describe the bug**
On my newly installed clean Windows 10 Enterprice LTSC machine with visual studio 2019 Enterprise installed the bootstrap-vcpkg.bat script is not able to find the visual studio 2019 install directory.

**Environment**
- OS: Windows 10 Enterprise LTSC
- Compiler: Visual Studio 2019 Enterprise

**To Reproduce**
1. clone the latest git repo
2. navigate to the vcpkg folder
3. run bootstrap-vcpkg.bat

**Expected behavior**
It should find the VS2019 installation directory.

**Failure logs** 
```
c:\Tools\vcpkg>bootstrap-vcpkg.bat
The property 'instance' cannot be found on this object. Verify that the property exists.
At C:\Tools\vcpkg\scripts\bootstrap.ps1:78 char:31
+         foreach ($instance in $asXml.instances.instance)
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.
At C:\Tools\vcpkg\scripts\bootstrap.ps1:143 char:9
+         throw "Could not find Visual Studio. VS2015 or VS2017 (with C ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.
```

**Additional context**
I did some debugging of the /scripts/bootstrap.ps1 script and the issue seems to be with the following line `$output = & $vswhereExe -prerelease -legacy -products * -format xml` (75). The vswhere.exe utility does not return any results if the command line arguments are specified as followed `vswhere.exe -prerelease -legacy -products *`.

Since it seems to me that the desired result of vswhere execution is to return all results. Hence my suggested fix is to replace the arguments with the single -all parameter. I have already tested this solution on my machine and raised a PR for this ( #7904 ).

**Comment by strega-nil** [comment]
I'm not sure this is still an issue that needs solving? If someone still has this issue, please ping me and open a new issue.

**Comment by parikshit-ai** [comment]
I am still getting the same issue 


The property 'instance' cannot be found on this object. Verify that the property exists.
At C:\vcpkg\scripts\bootstrap.ps1:78 char:31
+         foreach ($instance in $asXml.instances.instance)
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.
At C:\vcpkg\scripts\bootstrap.ps1:143 char:9
+         throw "Could not find Visual Studio. VS2015 or VS2017 (with C ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.

**Comment by strega-nil** [comment]
@parikshit-ai Could you post the output of the following (in a regular command prompt): `"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -format json`

**Comment by grillopf** [comment]
Try this, it worked for me: https://github.com/microsoft/vcpkg/issues/9982
But I had some extra work. You have to have Windows SDK installed before making modifications in Visual Studio instalation (checking language and Desktop development with C++). If you dont have Windows SDK installed, you will have to repeat modifications (checking boxes) in Visual Studio.
Hope it works

**Comment by parikshit-ai** [comment]
@strega-nil  it is empty array []

**Comment by strega-nil** [comment]
@parikshit-ai what about `& "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -products * -format json`

**Comment by richu101** [comment]
Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.
At I:\appllicatation files\vcpkg-master\vcpkg-master\scripts\bootstrap.ps1:143 char:9
+         throw "Could not find Visual Studio. VS2015 or VS2017 (with C ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.



how can i solve this error

**Comment by strega-nil** [comment]
@richu101 do you have the english language pack installed?

**Comment by FrostyshadowCorp** [comment]
> 
> 
> I'm not sure this is still an issue that needs solving? If someone still has this issue, please ping me and open a new issue.

still have this issue i have both vss2017 and vs2019 for the longest time

**Comment by strega-nil** [comment]
@FrostyshadowCorp do you have the english language packs for vs2017 and vs2019 installed?

**Comment by FrostyshadowCorp** [comment]
> 
> 
> @FrostyshadowCorp do you have the english language packs for vs2017 and vs2019 installed?

I believe so because i dont use any other language

**Comment by strega-nil** [comment]
Could you please run the following command and paste the output:

```cmd
> "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -prerelease -legacy -products * -format json
```

**Comment by FrostyshadowCorp** [comment]
[
  {
    "instanceId": "f6285e77",
    "installDate": "2019-06-19T00:01:28Z",
    "installationName": "VisualStudio/16.5.4+30011.22",
    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
    "installationVersion": "16.5.30011.22",
    "productId": "Microsoft.VisualStudio.Product.Community",
    "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
    "state": 4294967295,
    "isComplete": true,
    "isLaunchable": true,
    "isPrerelease": false,
    "isRebootRequired": false,
    "displayName": "Visual Studio Community 2019",
    "description": "Powerful IDE, free for students, open-source contributors, and individuals",
    "channelId": "VisualStudio.16.Release",
    "channelUri": "https://aka.ms/vs/16/release/channel",
    "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
    "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.5.4",
    "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
    "updateDate": "2020-05-06T19:54:10.9353129Z",
    "catalog": {
      "buildBranch": "d16.5",
      "buildVersion": "16.5.30011.22",
      "id": "VisualStudio/16.5.4+30011.22",
      "localBuild": "build-lab",
      "manifestName": "VisualStudio",
      "manifestType": "installer",
      "productDisplayVersion": "16.5.4",
      "productLine": "Dev16",
      "productLineVersion": "2019",
      "productMilestone": "RTW",
      "productMilestoneIsPreRelease": "False",
      "productName": "Visual Studio",
      "productPatchVersion": "4",
      "productPreReleaseMilestoneSuffix": "1.0",
      "productSemanticVersion": "16.5.4+30011.22",
      "requiredEngineVersion": "2.5.2141.57745"
    },
    "properties": {
      "campaignId": "748295578.1539039165",
      "canceled": "0",
      "channelManifestId": "VisualStudio.16.Release/16.5.4+30011.22",
      "nickname": "",
      "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"
    }
  }
]

**Comment by strega-nil** [comment]
@FrostyshadowCorp could you run:

```
> powershell scripts\bootstrap.ps1 -Verbose
```

**Comment by FrostyshadowCorp** [comment]
VERBOSE: Examining C:\Winsrc\Source_Bin\Kit\kitten-build\vcpkg\scripts for .vcpkg-root
VERBOSE: Examining C:\Winsrc\Source_Bin\Kit\kitten-build\vcpkg for .vcpkg-root - Found
VERBOSE: VS Candidates:
PreferenceWeight3::StableRelease::16.5.30011.22::C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
VERBOSE: Inspecting: PreferenceWeight3::StableRelease::16.5.30011.22::C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
VERBOSE: Picking: PreferenceWeight3::StableRelease::16.5.30011.22::C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
VERBOSE: Finding WinSDK
VERBOSE:
VERBOSE: Looking for Windows 10 SDK
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.18362.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.17763.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.17134.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.16299.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.15063.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\um\windows.h - Not Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.18362.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.17763.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.17134.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.16299.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.15063.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\um\windows.h - Not Found
VERBOSE: C:\Program Files\Windows Kits\10\Include - Not Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.18362.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.17763.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.17134.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.16299.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.15063.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\um\windows.h - Not Found
VERBOSE:
VERBOSE: Looking for Windows 8.1 SDK
VERBOSE: C:\Program Files (x86)\Windows Kits\8.1\\Include - Found
VERBOSE: Found 8.1
VERBOSE: C:\Program Files\Windows Kits\8.1\Include - Not Found
VERBOSE: C:\Program Files (x86)\Windows Kits\8.1\Include - Found
VERBOSE: Found 8.1
VERBOSE:


VERBOSE: The following Windows SDKs were found:
VERBOSE: 10.0.18362.0
VERBOSE: 10.0.17763.0
VERBOSE: 10.0.17134.0
VERBOSE: 10.0.16299.0
VERBOSE: 10.0.15063.0
VERBOSE: 10.0.18362.0
VERBOSE: 10.0.17763.0
VERBOSE: 10.0.17134.0
VERBOSE: 10.0.16299.0
VERBOSE: 10.0.15063.0
VERBOSE: 10.0.18362.0
VERBOSE: 10.0.17763.0
VERBOSE: 10.0.17134.0
VERBOSE: 10.0.16299.0
VERBOSE: 10.0.15063.0
VERBOSE: 8.1
VERBOSE: 8.1
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\cimv2,'className' = win32_operatingsystem'.
VERBOSE: Operation 'Enumerate CimInstances' complete.

Building vcpkg.exe ...

VERBOSE: Clean-Executing: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe "/p:VCPKG_VERSION=-nohash"
"/p:DISABLE_METRICS=0" /p:Configuration=Release /p:Platform=x86 /p:PlatformToolset=v142 /p:TargetPlatformVersion=10.0.18362.0 /p:PreferredToolArchitecture=x64
/verbosity:minimal /m /nologo "C:\Winsrc\Source_Bin\Kit\kitten-build\vcpkg\toolsrc\dirs.proj"
  pch.cpp
  archives.cpp
  checks.cpp
  chrono.cpp
  cofffilereader.cpp
  downloads.cpp
  enums.cpp
  files.cpp
  hash.cpp
  json.cpp
  machinetype.cpp
  parse.cpp
  strings.cpp
  stringview.cpp
  system.cpp
  system.print.cpp
  system.process.cpp
  unicode.cpp
  binarycaching.cpp
  binaryparagraph.cpp
  build.cpp
  cmakevars.cpp
  commands.autocomplete.cpp
  commands.buildexternal.cpp
  commands.cache.cpp
  commands.ci.cpp
  commands.contact.cpp
  commands.cpp
  commands.create.cpp
  commands.dependinfo.cpp
  commands.edit.cpp
  commands.env.cpp
  commands.exportifw.cpp
  commands.import.cpp
  commands.integrate.cpp
  commands.list.cpp
  commands.owns.cpp
  commands.porthistory.cpp
  commands.portsdiff.cpp
  commands.search.cpp
  commands.setinstalled.cpp
  commands.upgrade.cpp
  commands.version.cpp
  commands.xvsinstances.cpp
  dependencies.cpp
  export.cpp
  export.chocolatey.cpp
  export.prefab.cpp
  globalstate.cpp
  help.cpp
  input.cpp
  install.cpp
  logicexpression.cpp
  metrics.cpp
  packagespec.cpp
  paragraphparseresult.cpp
  paragraphs.cpp
  portfileprovider.cpp
  postbuildlint.buildtype.cpp
  postbuildlint.cpp
  remove.cpp
  sourceparagraph.cpp
  statusparagraph.cpp
  statusparagraphs.cpp
  tools.cpp
  triplet.cpp
  update.cpp
  userconfig.cpp
  vcpkgcmdarguments.cpp
  vcpkglib.cpp
  vcpkgpaths.cpp
  versiont.cpp
  visualstudio.cpp
  vcpkglib.vcxproj -> C:\Winsrc\Source_Bin\Kit\kitten-build\vcpkg\toolsrc\msbuild.x86.release\vcpkglib.lib
  vcpkg.cpp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 17625 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  vcpkg.vcxproj -> C:\Winsrc\Source_Bin\Kit\kitten-build\vcpkg\toolsrc\msbuild.x86.release\vcpkg.exe
  vcpkgmetricsuploader.cpp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 6758 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  vcpkgmetricsuploader.vcxproj -> C:\Winsrc\Source_Bin\Kit\kitten-build\vcpkg\toolsrc\msbuild.x86.release\vcpkgmetricsuploader.exe
VERBOSE: Execution terminated with exit code 0.

Building vcpkg.exe... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience. The data collected by Microsoft is anonymous. You can opt-out of telemetry by re-running bootstrap-vcpkg.bat with -disableMetrics.
Read more about vcpkg telemetry at docs/about/privacy.md

VERBOSE: Placing vcpkg.exe in the correct location

**Comment by FrostyshadowCorp** [comment]
Thank you so much it seems like its work :) @strega-nil

**Comment by RebelionTheGrey** [comment]
I'm sorry, I have a similar problem - I can't install the "vcpkg" with instructions.
Pls, help me, I've installed all packages, connected with C++, all available Windows SDK, choose an English language pack.
I don't really know what to do...((((

Here is my `powershell scripts\bootstrap.ps1 -Verbose` execution log:

```
C:\Windows\System32\vcpkg>powershell scripts\bootstrap.ps1 -Verbose
VERBOSE: Examining C:\Windows\System32\vcpkg\scripts for .vcpkg-root
VERBOSE: Examining C:\Windows\System32\vcpkg for .vcpkg-root - Found
VERBOSE: VS Candidates:
PreferenceWeight3::StableRelease::16.6.30114.105::C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
PreferenceWeight1::Legacy::14.0::C:\Program Files (x86)\Microsoft Visual Studio 14.0
PreferenceWeight1::Legacy::14.0::C:\Program Files (x86)\Microsoft Visual Studio 14.0
PreferenceWeight1::Legacy::14.0::C:\Program Files (x86)\Microsoft Visual Studio 14.0
VERBOSE: Inspecting: PreferenceWeight3::StableRelease::16.6.30114.105::C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community
VERBOSE: Picking: PreferenceWeight3::StableRelease::16.6.30114.105::C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community
VERBOSE: Finding WinSDK
VERBOSE:
VERBOSE: Looking for Windows 10 SDK
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.19041.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.18362.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.17763.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.17134.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.16299.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\um\windows.h - Not Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.19041.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.18362.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.17763.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.17134.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.16299.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\um\windows.h - Not Found
VERBOSE: C:\Program Files\Windows Kits\10\Include - Not Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.19041.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.18362.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.17763.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.17134.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um\windows.h - Found
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\shared\sdkddkver.h - Found
VERBOSE: Found 10.0.16299.0
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\um\windows.h - Not Found
VERBOSE:
VERBOSE: Looking for Windows 8.1 SDK
VERBOSE: C:\Program Files\Windows Kits\8.1\Include - Not Found
VERBOSE: C:\Program Files (x86)\Windows Kits\8.1\Include - Not Found
VERBOSE:


VERBOSE: The following Windows SDKs were found:
VERBOSE: 10.0.19041.0
VERBOSE: 10.0.18362.0
VERBOSE: 10.0.17763.0
VERBOSE: 10.0.17134.0
VERBOSE: 10.0.16299.0
VERBOSE: 10.0.19041.0
VERBOSE: 10.0.18362.0
VERBOSE: 10.0.17763.0
VERBOSE: 10.0.17134.0
VERBOSE: 10.0.16299.0
VERBOSE: 10.0.19041.0
VERBOSE: 10.0.18362.0
VERBOSE: 10.0.17763.0
VERBOSE: 10.0.17134.0
VERBOSE: 10.0.16299.0
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' =
root\cimv2,'className' = win32_operatingsystem'.
VERBOSE: Операция "Enumerate CimInstances" завершена.

Building vcpkg.exe ...

VERBOSE: Clean-Executing: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
 "/p:VCPKG_VERSION=-nohash" "/p:DISABLE_METRICS=0" /p:Configuration=Release /p:Platform=x86 /p:PlatformToolset=v142
/p:TargetPlatformVersion=10.0.19041.0 /p:PreferredToolArchitecture=x64 /verbosity:minimal /m /nologo
"C:\Windows\System32\vcpkg\toolsrc\dirs.proj"
MSBUILD : error MSB1009: файл проекта не существует.
Ключ: C:\Windows\System32\vcpkg\toolsrc\dirs.proj
VERBOSE: Execution terminated with exit code 1.
C:\Windows\System32\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed Visual St
udio with the Desktop C++ workload and the Windows SDK for Desktop C++.
At line:1 char:1
+ scripts\bootstrap.ps1 -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1 
```

**Comment by strega-nil** [comment]
@RebelionTheGrey why do you have vcpkg installed in `C:\Windows\System32`?

**Comment by RebelionTheGrey** [comment]
@strega-nil I've just done steps written on the main vcpkg page:

> git clone https://github.com/Microsoft/vcpkg.git
> cd vcpkg

PS> .\bootstrap-vcpkg.bat

I don't know the reason of usage System32.

See `dir` result below:

```
C:\Windows\System32\vcpkg>dir C:\Windows\System32\vcpkg\toolsrc
 Volume in drive C has no label.
 Volume Serial Number is 4600-AD86

 Directory of C:\Windows\System32\vcpkg\toolsrc

26.05.2020  22:40    <DIR>          .
26.05.2020  22:40    <DIR>          ..
26.05.2020  22:40               896 .clang-format
26.05.2020  22:40    <DIR>          cmake
26.05.2020  22:40             5 348 CMakeLists.txt
26.05.2020  22:40               773 dirs.proj
26.05.2020  22:40    <DIR>          include
26.05.2020  22:40    <DIR>          src
26.05.2020  22:40    <DIR>          vcpkg
26.05.2020  22:40             1 572 vcpkg.natvis
26.05.2020  22:40             7 180 vcpkg.sln
26.05.2020  22:40    <DIR>          vcpkglib
26.05.2020  22:40    <DIR>          vcpkgmetricsuploader
26.05.2020  22:40    <DIR>          vcpkgtest
26.05.2020  22:40                13 VERSION.txt
               6 File(s)         15 782 bytes
               9 Dir(s)  243 550 707 712 bytes free

C:\Windows\System32\vcpkg>
```

**Comment by RebelionTheGrey** [comment]
@strega-nil  I've solved this issue by calling cmd from SysWOW64, thank you. But, it's really strange - I don't know why, but running cmd.exe (from SysWOW64) in the administrator's mode changes the working directory to the System32...

**Comment by RebelionTheGrey** [comment]
@strega-nil  Last question, if it possible: how to set up max optimization level for installed libraries like blaze with ./vcpkg install? Thank you.

**Comment by strega-nil** [comment]
@RebelionTheGrey two versions of packages are installed, debug and release; if you build in release, you get the optimization automatically.

**Comment by YXGuan** [comment]
@strega-nil 
Hello, I am experiencing  a similar issue: 
After running > powershell scripts\bootstrap.ps1 -Verbose, it still shows me the error

`: Examining C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\vcpkg-master\scripts for .vcpkg-root
: Examining C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\vcpkg-master for .vcpkg-root - Found
: VS Candidates:
PreferenceWeight3::StableRelease::16.6.30114.105::C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
: Inspecting: PreferenceWeight3::StableRelease::16.6.30114.105::C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community
Could not find MSBuild version with C++ support. VS2015, VS2017, or VS2019 (with C++) needs to be installed.
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\vcpkg-master\scripts\bootstrap.ps1:195 字符: 5
+     throw "Could not find MSBuild version with C++ support. VS2015, V ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find MSBuild version with C++ support. VS2015, VS2017, or VS2019 (with C++) ne
   eds to be installed.`

**Comment by strega-nil** [comment]
@YXGuan could you run the command from above and paste the output?

```
> "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -prerelease -legacy -products * -format json
```

**Comment by YXGuan** [comment]
@strega-nil  Never mind, the problem's solved already. So there are two mistakes of mine: 
1. Did not install C++ Desktop development from VS installer. 
2. Did not run the power shell as admin
thank you for the help thou.

**Comment by strega-nil** [comment]
No problem!

**Comment by PhoebeHui** [comment]
This should not be a problem with latest vcpkg source.
