### ISSUE TITLE
Variables set by triplets should be available when using the vcpkg cmake toolchain file

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/vcpkg#8056]
****

**Is your feature request related to a problem? Please describe.**
I constructed a new CMake build script that needs to include different source files based on the target build architecture, or link to different libraries. CMake's reporting mechanisms for the target hardware appear to always report values from the hosting machine, not the target machine, which makes them of limited use. However, when invoking my build script, the user already has to tell vcpkg what platform to use (as it is a triplet property) by setting `VCPKG_TARGET_TRIPLET`. Rather than deriving this constant again, it would be nice for vcpkg to make those values available for use in consuming CMakeLists.txt.

**Proposed solution**
Any of the following would work:
* Set a variable in `vcpkg.cmake` that contains the path to the currently selected triplet file that a user can `include()`
* Set a variable in `vcpkg.cmake` to the root of the vcpkg instance in use (from which the user can select a triplet file by combining with VCPKG_TARGET_TRIPLET themselves)
* Just make the values set by the triplet available as variables in the consuming build directly.

**Describe alternatives you've considered**
At the moment I am extracting the target architecture using a regular expression against `VCPKG_TARGET_TRIPLET`, but this is fragile as it doesn't tolerate customized user triplets.

**Additional context**
This is something of a lighter version of https://github.com/microsoft/vcpkg/issues/3807

**Comment by Neumann-A** [comment]
I think you are looking for VCPKG_CHAINLOAD_TOOLCHAIN_FILE
but be aware that this file is loaded before VCPKG_TARGET_TRIPLET is defined. 
What CMake variables did you try to use because vcpkg.cmake just parses CMAKE_GENERATOR(_PLATFORM) to define the triplet.

**Comment by BillyONeal** [comment]
>I think you are looking for VCPKG_CHAINLOAD_TOOLCHAIN_FILE

I don't want to author a toolchain file to control which source files are included in a library.

>What CMake variables did you try to use because vcpkg.cmake just parses CMAKE_GENERATOR(_PLATFORM) to define the triplet.

The user sets `-DVCPKG_TARGET_TRIPLET=whatever` on the command line (or vcpkg tries to guess a default based on the detected path to `cl`).

**Comment by Neumann-A** [comment]
If your are crosscompiling you probably want to have a `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` because you need to tell CMake what your are targeting which means setting at least:
[CMAKE_SYSTEM_NAME](https://cmake.org/cmake/help/v3.15/variable/CMAKE_SYSTEM_NAME.html)
[CMAKE_SYSTEM_VERSION (optional?; docs are a bit strange about that one)](https://cmake.org/cmake/help/v3.15/variable/CMAKE_SYSTEM_VERSION.html)
[CMAKE_SYSTEM_PROCESSOR](https://cmake.org/cmake/help/v3.15/variable/CMAKE_SYSTEM_PROCESSOR.html)
If you fail to do so CMakes doc explicitly says that without that all those variables will be set to their respective HOST versions.
[see also](https://cmake.org/cmake/help/v3.15/manual/cmake-toolchains.7.html#cross-compiling-toolchain) 

>  At the moment I am extracting the target architecture using a regular expression against VCPKG_TARGET_TRIPLET, but this is fragile as it doesn't tolerate customized user triplets.

So in your case it would be correct to test `CMAKE_SYSTEM_PROCESSOR` for the different architectures.

**Comment by Neumann-A** [comment]
Ah there might also be a serious bug in `vcpkg_configure_cmake.cmake` because it does not pass `CMAKE_SYSTEM_PROCESSOR` to cmake depending on a comparison of `_csc_HOST_ARCHITECTURE` vs `VCPKG_TARGET_ARCHITECTURE`. So that might be the real problem.

**Comment by cbezault** [comment]
@Neumann-A, it seems like Billy wants to be able to take advantage of all the VCPKG variables available to ports in his own buildsystem. I agree with him that it's unnecessary to author a toolchain file. I'm inclined to choose his third option of just directly including all the triplet variables directly in vcpkg.cmake so they are available to the consuming build.

**Comment by BillyONeal** [comment]
>If your are crosscompiling

I don't consider a build on a machine capable of running x86 programs, where cmake was launched from an x86 prompt, "cross compiling"; CMAKE_SYSTEM_NAME should still be "Windows" as if we set that to something else other CMakeLists.txt upon which we depend might be confused and think we're targeting *nix or similar.

**Comment by Neumann-A** [comment]
>I don't consider a build on a machine capable of running x86 programs, where cmake was launched from an x86 prompt, "cross compiling"

Then consider it a bug/limitation in CMake using `PROCESSOR_ARCHITECTURE` instead of looking into `__VCVARSALL_TARGET_ARCH` for `CMAKE_SYSTEM_PROCESSOR` if it is available (or do not use ninja as a generator?)

>I'm inclined to choose his third option of just directly including all the triplet variables directly in vcpkg.cmake 

No, bad design, Might lead to error with user defined triplets since there are different variables available in vcpkg/cmake port script mode and vcpkg toolchain mode. One of those is e.g. `${PORT}`. The triplet file should only be used internally by vcpkg and nothing else. If there is something which all ports and external projects need -> toolchain file is the way to go. 
the only think i would agree on is setting the mentioned cmake variables depending on the select triplet for the user since `x64-linux` does not make a lot of sense for a `CMAKE_SYSTEM_NAME` which is "Windows"

**Comment by BillyONeal** [comment]
>If there is something which all ports and external projects need -> toolchain file is the way to go.

The problem is that there isn't a way to fix this in a toolchain. The user already had to tell vcpkg which architecture to target, and making the user repeat themselves to tell my chainloaded toolchain file what the architecture is would be a suboptimal user experience.

If the assertion is that it's something the toolchain file should do, then vcpkg.cmake should be doing things to make `PROCESSOR_ARCHITECTURE` return the correct answer, since vcpkg uses `VCPKG_TARGET_ARCHITECTURE` from the triplet and ignores `PROCESSOR_ARCHITECTURE` completely. We don't want the user to have to jump through hoops to say they want x86 again if they've already done `-DVCPKG_TARGET_TRIPLET=x86-windows`. (And similarly BUILD_SHARED_LIBS should probably get set to `VCPKG_LIBRARY_LINKAGE`, and on recent versions of CMake  `VCPKG_CRT_LINKAGE` should probably affect `CMAKE_MSVC_RUNTIME_LIBRARY`)

**Comment by Neumann-A** [comment]
>The user already had to tell vcpkg which architecture to target.

Only necessary if the Generator is not Visual Studio or a custom triplet is used. For VS Generators the automatic detection of the triplet kicks in. 

> The user already had to tell vcpkg which architecture to target, and making the user repeat themselves to tell my chainloaded toolchain file what the architecture is would be a suboptimal user experience.

I think the trick here is that the user should avoid directly using the vcpkg toolchain file but define his own toolchain which chainloads the vcpkg toolchain. This way the user can make use of `CMAKE_SYSTEM_NAME` and `CMAKE_SYSTEM_PROCESSOR` to build the VCPKG triplet name they want to use. Furthermore by defining that toolchain file it can simply be loaded by a customized triplet and set the required variables.  
The only thing I see vcpkg do here, is a test against the triplet file: Testing if the settings are compatible or, if the variables are not defined, setting those according to the triplet. (This could be done by _including the triplet file in a function_ (to not leak the `VCPKG_` prefixed variables into the user cmake variables) but I see hard errors in custom triplet files occurring due to `if(${PORT} MATCHES "xyz")` and `${PORT}` being undefined. 

>And similarly BUILD_SHARED_LIBS should probably get set to VCPKG_LIBRARY_LINKAGE

Simply no. A custom triplet might define it differently for any number of ports. Also VCPKG_LIBRARY_LINKAGE dynamic means nothing and some ports in vcpkg are build as static libraries with that setting

**Comment by BillyONeal** [comment]
>I think the trick here is that the user should avoid directly using the vcpkg toolchain file but define his own toolchain which chainloads the vcpkg toolchain.

So CMake's behavior where it uses the target architecture of the compiler on the path is just wrong?

I .... don't know what to say to that.

**Comment by Neumann-A** [comment]
>So CMake's behavior where it uses the target architecture of the compiler on the path is just wrong?
 
Where should CMake get that information from? It probably needs to know that before testing the compiler and if you don't tell CMake what the target is, it will just assume that target = host. The only cases CMake has additional information is if the used Generator gives this information in e.g. [CMAKE_GENERATOR_PLATFORM](https://cmake.org/cmake/help/v3.15/variable/CMAKE_GENERATOR_PLATFORM.html) which is very limited.
So CMake has in most cases no way to deduce what target architecture the user wants and that's why you have to explicitly tell it to CMake if it should be different than the host.

**Comment by BillyONeal** [comment]
>Where should CMake get that information from?

I don't know where it gets it from, only that it does.

**Comment by Neumann-A** [comment]
You probably want to look into 
`<cmakeinstallpath>\share\cmake-3.15\Modules\Platform\Windows-MSVC.cmake`
and test for `MSVC_CXX_ARCHITECTURE_ID` or `MSVC_C_ARCHITECTURE_ID`. 
I found some old [arguments](http://cmake.3232098.n2.nabble.com/Get-Visual-Studio-target-Arch-td7588391.html) why `CMAKE_SYSTEM_PROCESSOR` is not setup properly for MSVC but they were really not that convincing. `Windows-MSVC.cmake` should setup `CMAKE_SYSTEM_PROCESSOR` because at that point it seems to know what the target architecture should be.

Another interesting read on crosscompiling with [CMake](https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/CrossCompiling)

Some other variable used by boost?
[CMAKE_CXX_COMPILER_ARCHITECTURE_ID ](https://gitlab.kitware.com/cmake/cmake/issues/18553)

Hope this helps to solve your target architecture issues

**Comment by BillyONeal** [comment]
CMAKE_CXX_COMPILER_ARCHITECTURE_ID does appear to make this problem solvable. It's unfortunate that it might be specified differently than what vcpkg uses though :(. Certainly it solves my immediate problem, but it'd still be nice to be compatible with whatever vcpkg is using for `VCPKG_LIBRARY_LINKAGE` and `VCPKG_CRT_LINKAGE`.
