### ISSUE TITLE
How can I add include directory for an imported library with higher priority than vcpkg include directories

### ISSUE THREAD

**Issue by harokyang** [microsoft/vcpkg#8071]
I installed a library with vcpkg

I also built a version with custom setting of this library somewhere else
What I needed is to override the library installed by vcpkg and test with my own version

It's easy to target a library with different path
The problem is the header files

I included the custom library with cmake setting
`add_library(CustomLib UNKNOWN IMPORTED)`
`set_target_properties(CustomLib PROPERTIES IMPORTED_LOCATION ${CUSTOM_LIB})`
`set_target_properties(CustomLib PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${CUSTOM_INCLUDE_DIR})`

The CUSTOM_INCLUDE_DIR pointed to the new location
But if I #include <lib.h> in my code, it always reference to the one installed by vcpkg

I check the generated build script, found that the include search path of vcpkg already added before CUSTOM_INCLUDE_DIR which bind with the CustomLib

I know I can use target_include_directories() with BEFORE keyword to move the include search path ahead
But this function won't support imported library, I'm stuck with set_target_properties which do not have a BEFORE keyword
Another workaround is to use target_include_directories() direct on the final target which depend on my CustomLib, I really want to avoid this method if possible

So is there any way to only add vcpkg search path at last place, or some way to move include directory of imported libray ahead

**Comment by JackBoosY** [comment]
Hi @harokyang, When you integrate vcpkg into Visual Studio with the command `.\vcpkg.exe integration install`, vcpkg will adds _VCPKG_PATH\installed\MATCHED_TRIPLET\include_ to the system include path.
However, using angle brackets(`<>`) to include port header files will find their path in the system include path, so although you add custom port header paths to your configuration, Visual Studio uses the vcpkg path to find them.

Of course, vcpkg does this to prevent user-custom-build ports from being used when installing ports, because their versions do not necessarily match.

So, please don't use angle brackets to include header files, just use double quotes(`""`).

**Comment by Neumann-A** [comment]
Counter questions:
a) which generator are you using. If you use VS generators than maybe the vcpkg integration is screwing with you
b) If you use only CMake: What other dependencies do you have? The vcpkg toolchain itself does *not* add `<vcpkgtripletpath>/include ` to the include directories. So another dependency might be doing that. 

Note on include with  `<>` or `""`: If your costumLib is isolated/separated (like vcpkg ports) and you are just writing `FindCostumLib` or `CoustomLib-config` than usage of `<>` within your own code separated from costumLib is correct. If it is within the code of costumLib itself than usage of  `""` is correct. If you allow CostumLib to be optional build with your code than you probably need a include wrapper switching between `<>` or `""` just as ports like VTK do it with their third party dependencies

**Comment by harokyang** [comment]
I use the latest cmake 3.15 with ninja back-end

My project is a shared library, which require some other libraries as dependency
I want to create some helper FindModule.cmake to find those dependency
The end-user can choose either install the dependency with vcpkg or another way

Those FindModule.cmake work if one of the situation met
But if both vcpkg installed and custom provided libraries existed, FindModule.cmake will pick the correct one(controlled by cmake variable)

Because of this issue, it is forced to choose the vcpkg version of both existed

The <> and "" method won't help, because the generated build script shows include directory of imported library also marked as system search path, it won't be picked before vcpkg by using ""
Additional, I can't control how the end-user coding their #include lines

**Comment by JackBoosY** [comment]
Yes, if there is no built-in `Find<PORT>.cmake`, the vcpkg toolchain will preferentially use the generated ports in vcpkg. Because we need to ensure that the ports that are dependent on when building a port are always provided by vcpkg.

So, I think you need to add a `Find<PORT>.cmake` and use non-`CONFIG` mode to find dependencies.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
