### ISSUE TITLE
[New Port Request] BoringSSL

### ISSUE THREAD

**Issue by TaylorSasser** [microsoft/vcpkg#8084]
Library name: BoringSSL

Library description:Googles fork of OpenSSL

Source repository URL:
https://github.com/google/boringssl
https://boringssl.googlesource.com/boringssl

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

I went ahead and tried doing it myself.I  was able to get it working up until the installation of the lib and headers. Not exactly sure how to fix it. Side Note: I had some major issues using ninja as the build system for this. Not exactly sure why, but it just never worked

[CONTROL.txt](https://github.com/microsoft/vcpkg/files/3586017/CONTROL.txt)
[portfile.txt](https://github.com/microsoft/vcpkg/files/3586018/portfile.txt)

**Comment by TaylorSasser** [comment]
Hey, I've made some more progress. BoringSSL has no install target. so I've had to create one. This is what I've ended up with. 

`include(GNUInstallDirs)

install(
    TARGETS crypto ssl
    EXPORT  boringssl_targets
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
)

install(
    EXPORT boringssl_targets
    FILE unofficial-boringssl-config.cmake
    NAMESPACE unofficial::boringssl::
    DESTINATION share/unofficial-boringssl
)

install(DIRECTORY include/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})`

**Comment by qis** [comment]
@TaylorSasser After playing around with OpenSSL/LibreSSL in vcpkg, this is my suggestion:

1. Don't export unofficial targets and let users rely on `FindOpenSSL.cmake`.
2. Patch `ports/openssl-{unix,uwp,windows}/portfile.cmake` line 8 to include BoringSSL.
3. Handle OpenSSL or LibreSSL like OpenSSL handles LibreSSL (detect the `ssl.h` header).

In fact, using `ports/libressl` as the `ports/boringssl` template might be a good idea.

Does the VCPKG team agree? How about tools like `openssl.exe` that BoringSSL does not provide?

**Comment by qis** [comment]
@TaylorSasser Could you please make a PR for that, so that we can test and contribute.

**Comment by qis** [comment]
I've created a PR (https://github.com/microsoft/vcpkg/pull/8440) for the Go dependency and written a port against it:

https://github.com/qis/vcpkg/tree/dev/qis/boringssl

There are several issues I see with BoringSSL:

1. It does not support UWP due to usage of desktop-only APIs like [RtlGenRandom](https://docs.microsoft.com/en-us/windows/win32/api/ntsecapi/nf-ntsecapi-rtlgenrandom).
2. It totally ignores `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS` variables set by a MSVC toolchains.
3. When `CMakeLists.txt` is patched to honor flags set by a toolchain, `/EH` flags break compilation.
4. It uses its own gtest for tests which has the same `/EH` flags issues.
5. It uses Go for codegen.

I'll submit a PR for BoringSSL if Go is added to vcpkg, but don't want to maintain it since I use toolchains at work that can't build it.

**Comment by NancyLi1013** [comment]
Hi @TaylorSasser 
Thanks for posting this request.
boringssl has been added to vcpkg. Please try to update vcpkg and use it.
@qis Thanks for your efforts.
