### ISSUE TITLE
How to solve the following problems when create new ports?

### ISSUE THREAD

**Issue by saedrna** [Microsoft/vcpkg#834]
Hi, 

I would like to add a new port following [this tutorial](https://github.com/Microsoft/vcpkg/blob/master/docs/EXAMPLES.md#example-2), the library to be ported is [OpenSceneGraph(osg)](https://github.com/openscenegraph/OpenSceneGraph), which is also cubersome to be built for new comers. But vcpkg has all the dependencies and it is quite easy to be ported.

The port is successfully configured and built, but I have some post-built problems as below.

1,  To remove installation of includes for debug. There is the following warning, I think it is easy to handle as described.

```
Include files should not be duplicated into the /debug/include directory. If this cannot be disabled in the project cmake, use
    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)
```

2, To not install exe files to bin.  OSG has some handy apps to be built, but how to install them? Absolutely, I could disable by `-BUILD_OSG_APPLICATIONS=OFF` in the profile.cmake, but how to install them? Because these apps are also often used.

```
The following EXEs were found in /bin and /debug/bin. EXEs are not valid distribution targets.

    D:/build/vcpkg/packages/openscenegraph_x64-windows/bin/osgarchive.exe
    D:/build/vcpkg/packages/openscenegraph_x64-windows/bin/osgconv.exe
    D:/build/vcpkg/packages/openscenegraph_x64-windows/bin/osgfilecache.exe
    D:/build/vcpkg/packages/openscenegraph_x64-windows/bin/osgversion.exe
    D:/build/vcpkg/packages/openscenegraph_x64-windows/bin/osgviewer.exe
    D:/build/vcpkg/packages/openscenegraph_x64-windows/bin/present3D.exe
    D:/build/vcpkg/packages/openscenegraph_x64-windows/debug/bin/osgarchived.exe
    D:/build/vcpkg/packages/openscenegraph_x64-windows/debug/bin/osgconvd.exe
    D:/build/vcpkg/packages/openscenegraph_x64-windows/debug/bin/osgfilecached.exe
    D:/build/vcpkg/packages/openscenegraph_x64-windows/debug/bin/osgversiond.exe
    D:/build/vcpkg/packages/openscenegraph_x64-windows/debug/bin/osgviewerd.exe
    D:/build/vcpkg/packages/openscenegraph_x64-windows/debug/bin/present3Dd.exe
```

3. Plugin dlls are not able to be installed with the following warnings. The plugins are dynamically loaded when reading and writing specific files and as said no exports lib is available for them. How to install them?

```
The following DLLs have no exports:

    D:/build/vcpkg/packages/openscenegraph_x64-windows/debug/bin/osgPlugins-3.5.5/osgdb_3dcd.dll
    D:/build/vcpkg/packages/openscenegraph_x64-windows/debug/bin/osgPlugins-3.5.5/osgdb_3dsd.dll
    D:/build/vcpkg/packages/openscenegraph_x64-windows/debug/bin/osgPlugins-3.5.5/osgdb_acd.dll
    D:/build/vcpkg/packages/openscenegraph_x64-windows/debug/bin/osgPlugins-3.5.5/osgdb_bmpd.dll
    ...
DLLs without any exports are likely a bug in the build script.
```

4. And finally is the error to stop the installation to the `installed/x64-windows` folder.

```
-- Performing post-build validation done
Found 4 error(s). Please correct the portfile:
    D:\build\vcpkg\ports\openscenegraph\portfile.cmake
Error: Building package openscenegraph:x64-windows failed with: POST_BUILD_CHECKS_FAILED
```

Is there are some hints on how to solve this? Or direct me to some existing ports with solution to similar problem?

Thanks,

Han

**Comment by alexkaratarakis** [comment]
Hi!
1) Indeed, simply copy-pasting the line towards the end of the portfile (i.e. after the build is complete and the headers/binaries are collected) will work. If there is a way for the build to not install them in the first place, that is even better. 

2) In general, `vcpkg` deals with libraries, not applications. There are some applications (tools) that are included in the portfolio, but this is because they are used during the build of some other library(an example of this is `protobuf`). 
I am not familiar with the usage of `osg`, but I believe `-BUILD_OSG_APPLICATIONS=OFF` is the right thing here. If you believe the `exes` are required then:
- delete the debug versions
- place the release versions under a folder named `tools\`  (`${CURRENT_PACKAGES_DIR}/tools/`)

3) Let me get back to you on this one!

4) This is not an additional error, it is just a summary of the previous errors. It will go away, once the others checks pass. You are right that this is not clear, so I have reordered the messages with ca3e3c125ad550ff18ec732a73f6d9c155caf793 so it will now be like this:

```
Found 4 error(s). Please correct the portfile:
    D:\build\vcpkg\ports\openscenegraph\portfile.cmake
Error: Building package openscenegraph:x64-windows failed with: POST_BUILD_CHECKS_FAILED
-- Performing post-build validation done
```

Hopefully this makes it clearer that the message is part of the post-build validation.

**Comment by saedrna** [comment]
Thanks!

For the third problem, after looking into the toolsrc, I think there is no workaround without add additional options in these lines. I hope I'm wrong, if not, maybe adding some options in `vcpkg_configure_cmake` or other function may do the work?

```
   error_count += check_exports_of_dlls(dlls, dumpbin_exe);
   error_count += check_uwp_bit_of_dlls(spec.target_triplet().system(), dlls, dumpbin_exe);
   error_count += check_dll_architecture(spec.target_triplet().architecture(), dlls);
```

**Comment by ras0219-msft** [comment]
One option is to move the plugins to the `tools\` directory. For example:

```cmake
file(MAKE_DIRECTORY ${CURRENT_PACKAGES_DIR}/tools/openscenegraph)
file(RENAME ${CURRENT_PACKAGES_DIR}/debug/bin/osgPlugins-3.5.5 ${CURRENT_PACKAGES_DIR}/tools/openscenegraph/plugins)
```
This way, the core library (which is expected to be linked into the user's application) will still be fully checked.

However, we generally don't have a strong story for libraries with a plugin architecture today because you can't make a choice at compile time; you have to choose at deployment time. We'd like to make this a better experience in the future!
