### ISSUE TITLE
boost and cpprest header ordering

### ISSUE THREAD

**Issue by treigilbert** [Microsoft/vcpkg#836]
Header ordering of boost and cpprest causes compile error.

#include "stdafx.h"
#include <cpprest/http_client.h>
#include <cpprest/json.h>
#include <boost/property_tree/ptree.hpp>

int main()
{
    return 0;
}

gives compile error:
e:\code\penelope\vcpkg\installed\x64-windows\include\boost\move\detail\type_traits.hpp(757): error C2187: syntax error: ')' was unexpected here

#include "stdafx.h"
#include <boost/property_tree/ptree.hpp>
#include <cpprest/http_client.h>
#include <cpprest/json.h>

int main()
{
    return 0;
}

compiles and runs.

Visual Studio 2017 Release x64

**Comment by alexkaratarakis** [comment]
Found the reason. 

`boost` has this code:
```
         template <class U>
         static yes_type test(U&, decltype(U(source<U>()))* = 0);
```

Notice the template parameter `U` (and there are other instances of using `U` as the template parameter). 

`cpprestsdk` defines a macro `U`:
```
#ifndef _TURN_OFF_PLATFORM_STRING
#define U(x) _XPLATSTR(x)
#endif // !_TURN_OFF_PLATFORM_STRING
```

@ras0219-msft

**Comment by MikeGitb** [comment]
What is it with microsoft and bad header hygiene? If cpprestsdk is still maintained, this should be submitted as a bug against it. Boost is certainly not the only library using `U` as a template parameter.

**Comment by siok8000** [comment]
I am also facing the same error.. Please help..

**Comment by ras0219-msft** [comment]
Since this is specifically about the behavior of Cpprestsdk, please submit issues against its GitHub page:

https://github.com/Microsoft/cpprestsdk

**Comment by mudasira** [comment]
Solved it by undefining U i.e.

**Comment by PBRCW** [comment]
> Since this is specifically about the behavior of Cpprestsdk, please submit issues against its GitHub page:
> 
> https://github.com/Microsoft/cpprestsdk

Has this already been done? The problem still seems to persist (and it is a real annoyance!!).

Dunno why MS did it that way at all. At least they should've prepended their bloody macro with a leading underscore to sign it as proprietary (as they did it with the omnipresent _T()-macro):
`#define _U(x) _XPLATSTR(x)`. Doing so would've prevented the name collision with boost and possibly others because they all know (and follow) that names with leading underscores are vendor reserved.

As I'm using the SDK and boost in many different compilation units this macro is a real nightmare! My solution to get rid of the problem was to include all boost files that suffer from this macro in the project's precompiled header, asuring that they always get included *before* any of the REST stuff. However this keeps being a kludge of course.

> Solved it by undefining U i.e.
>
> #undef U

Seems not to be the best way to do it, as at least they offer a switch to turn that beast off:
`#define _TURN_OFF_PLATFORM_STRING` should do the trick - well, sort of, there are headers in the REST SDK that indiscriminately use the bloody U-macro (instead of relying to the other macro that was intended for the SDK implementaton, _XPLATSTR()). But `#undef U` will collide with these as well...

**Comment by ras0219-msft** [comment]
@pbrcw Please do file that feedback against cpprestsdk!

However, as I stated above, this is clearly off-topic for Vcpkg, so I'm locking this issue.
