### ISSUE TITLE
Conditional compile depending on if library is installed

### ISSUE THREAD

**Issue by treigilbert** [microsoft/vcpkg#841]
I have a header only library that conditionally compiles depending on what libraries are available. This allows the library to be used without requiring several extra libraries to be installed, but will use the extra libraries if they are present.

#ifdef HAS_OPENVR
.....
#endif 

For NuGet Packages, I have HAS_LIBRARYNAME defined for all the packages I build. I'm moving from all the NuGet packages I built to vcpkg. Thank you for vcpkg! Is there a consistent why in code to check if a library is installed?

**Comment by ras0219-msft** [comment]
Today, we don't have a perfect story for this -- each package can only request a single set of dependencies. We currently make our best judgement about what will be useful to the maximum set of users; this generally means enabling as many features as is reasonably possible. Advanced users can always modify the portfile themselves to change settings as they wish.

Therefore, I would first recommend that any packages consuming your header-only lib do the following:

1. They list openvr and my_header_lib in their `Build-Depends:`
2. They internally define HAS_OPENVR for their own build.

Unfortunately, external projects will need to remember to manually define HAS_OPENVR if they want that functionality compiled in.

An alternative option is to list openvr as a dependency of your header only library and perform a text replacement on the headers ("HAS_OPENVR" => 1) as they are installed. This way, there is no configuration needed for consumers because the macros have all already been evaluated "correctly" according to the state of Vcpkg. However, it means that consumers can't _not_ require openvr even if they do not use that portion of the header only library.

> is there a consistent [way] to check if a library is installed?

From CMake, we support all the standard CMake-isms: `find_package()`, `find_library()`, and `find_path()` all work exactly as expected. We recommend using these if your are consuming libraries from CMake.

From MSBuild, we don't currently have a way to check whether libraries are installed during the build.

For portfiles, we recommend _not_ checking whether a library is installed during the build. If you want to build with a library, then you should add it to your dependencies and assume it is installed. If you do not want to build with a library, then you should assume it is not installed. This approach keeps things sane and predictable -- install A B C gets you to the same state as install C B A.

**Comment by ras0219-msft** [comment]
I've opened a PR (#1205) to support optional dependencies and functionality. Please take a look and let us know any feedback!

**Comment by treigilbert** [comment]
The new __has_include in C++ 17 might solve the way to handle conditionally compiles depending on what libraries are available. Visual Studio currently does not have this feature, but once it is added, checking for installed libraries may become a simple #if __has_include(<header>).

**Comment by ras0219-msft** [comment]
That's a really nice idea; anything that lets us move more logic into our C++ code and out of the buildsystem is good in my book :)

However, the trouble with relying on __has_include is:
1. It's very hard to surface the concept that "Yes you have python installed, yes you have boost installed, but you built them in the wrong order so you don't have boost python"
2. There's no _standard_ way to instruct a package "I know I have python, but please don't use it."
3. It focuses interactions on _dependencies_ instead of _APIs_. From a programmer's perspective, I care about having libcurl work with https URLs. I don't care about whether `#include <openssl/ssl.h>` works.

**Comment by PhoebeHui** [comment]
See #1205, currently vcpkg support to add feature for ports. I guess we can close it now.
