### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by wjx0912** [microsoft/vcpkg#8618]
i have install vs2015, then install vcpkg,  all works well.

after a new vs2019 install,  i run 'vcpkg integrate install' (admin priviledge) again.
but vs2019 project configuration doesn't have vcpkg include.

how to fix it? thanks

**Comment by wjx0912** [comment]
http://vps3.xueweiqi.com/vs2015.png
http://vps3.xueweiqi.com/vs2019.png

**Comment by NancyLi1013** [comment]
Hi @wjx0912  thanks for posting this issue. Could you add `set(VCPKG_PLATFORM_TOOLSET v142)` in triplet and try it again?
Also please refer to the document here https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md
Similar issue #5983.

**Comment by PhoebeHui** [comment]
@wjx0912, it should not block you, they should find the installed libraries headers correctly.

It doesn't show $(VcpkgRoot)include in VS2017 and VS2019 since they have different way to import vcpkg targets in msbuild, In VS2015, it import the target when the solution create. in VS2017 and VS2019, it will import the target when build the solution.

**Comment by wjx0912** [comment]
hi @PhoebeHui 
it works, thank you.
