### ISSUE TITLE
How do I include external library dependencies?

### ISSUE THREAD

**Issue by maxlovic** [microsoft/vcpkg#8705]
Hi. I would like to add support for [SRT](https://github.com/Haivision/srt) network protocol library.
Would this be welcome?

Ьн сгккуте barrier is in specifying external dependencies. I went throught the [docs](https://github.com/microsoft/vcpkg/blob/master/docs/index.md), but was not able to find the dolution in a reasonable time so far.

I want to include a library, that depends on OpenSSL and pthreads. I would like to specify this dependency on the libraries, built by vcpkg. How do I do this?

My port so far: [link](https://github.com/maxlovic/vcpkg/commit/8a2fe012f7b9af84b6cba8714d9c22276cefbbe8).

**Comment by JackBoosY** [comment]
Hi @maxlovic, thanks for reporting this issue.
When you use cmake, if you need to add a dependency library, you can use `find_package(${PORT_NAME} CONFIG REQUIRED)` (${PORT_NAME}config.cmake is provided)  / `find_library(${PORT_NAME} NAMES ${LIBRARY_NAME_WITHOUT_SUFFIX})`(${PORT_NAME}config.cmake is **NOT** provided).

If you need to rely on the port to output `find_package (... CONFIG ...)` after port build with vcpkg, you can use `find_package(${PORT_NAME} CONFIG REQUIRED)`, otherwise you need to use `Find${PORT_NAME}.cmake` provided by cmake to find (using `find_package(${PORT_NAME} REQUIRED)`, excluding CONFIG).

Or we can create a PR based on your commit.

**Comment by JackBoosY** [comment]
You need to add the dependency ports `openssl` and `pthreads` in file `CONTROL` like:
`Build-Depends:  openssl, pthreads (windows)`
And should also modify `CMakeLists.txt` to add `find_package` / `find_library`.

When executing `CMakeLists.txt` with `vcpkg_configure_cmake`, vcpkg will set `CMAKE_MODULE_PATH` to _VCPKG_PATH/installed/CURRENT_TRIPLET/lib_(release) and _VCPKG_PATH/installed/CURRENT_TRIPLET/debug/lib_(debug), so you don't have to worry about finding libraries under other paths.

If you have not enough time, I will create a PR base on your [commit](https://github.com/maxlovic/vcpkg/commit/8a2fe012f7b9af84b6cba8714d9c22276cefbbe8).

**Comment by maxlovic** [comment]
Adding `Build-Depends...` did the trick!
Now I have issues with instalation. Post-install validation check is failing:
```
The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    d:/Projects/vcpkg-max/packages/libsrt_x86-windows/debug/bin/srt-file-transmit.exe
    d:/Projects/vcpkg-max/packages/libsrt_x86-windows/debug/bin/srt-live-transmit.exe
    d:/Projects/vcpkg-max/packages/libsrt_x86-windows/debug/bin/srt-tunnel.exe
```
So executables can't be installed to that directory?

Please feel free to use my commit to create a PR.

**Comment by JackBoosY** [comment]
Vcpkg default directories are:
- bin -> shared library path
- lib -> static library path
- tools -> executable path
- include -> headers path
- share -> documentation / configure file path
