### ISSUE TITLE
linking to various libraries on Mac fails when linking Qt with CMake

### ISSUE THREAD

**Issue by TheScarfix** [microsoft/vcpkg#8732]
**Describe the bug**
linking to pcre2 fails using qt on mac in Debug config. In Release config libpq doesn't link correctly.

**Environment**
- OS: Mac OS X 10.15
- Compiler: Clang 11.0.0

**To Reproduce**
1. link to Qt in CMake
2. build the executable with CMake in Debug config

**Expected behavior**
Executable using Qt on Mac builds and runs.

**Failure logs** 
ld: library not found for -lpcre2-16_LIBRARY_DEBUG-NOTFOUND
clang: error: linker command failed with exit code 1 (use -v to see invocation)**Additional context**

**Comment by JackBoosY** [comment]
@Neumann-A What do you think about this issue?

**Comment by Neumann-A** [comment]
@TheScarfix: Could you give me list of installed files in lib and debug/lib on your MacOSx system? 

@JackBoosY: We have simply have to find out why the find_library call in the vcpkg-cmake-wrapper.cmake fails

**Comment by TheScarfix** [comment]
[lib.txt](https://github.com/microsoft/vcpkg/files/3773256/lib.txt)
[debuglib.txt](https://github.com/microsoft/vcpkg/files/3773258/debuglib.txt)

**Comment by Neumann-A** [comment]
@TheScarfix: seem like pcre is missing the debug suffix on macosx for some reason. (you could add the non debug suffixed name to the find_library call in the vcpkg-camke-wrapper)
Do you use a multi configuration generator? Or what exactly is happening which the release linkage of libpq? (probably linking the debug version in release? should be fixed in the PR with the update to 12.0)

**Comment by TheScarfix** [comment]
@Neumann-A can't get it to work :( and I use cmake-tools for vscode.
