### ISSUE TITLE
vcpkg error "No such file or directory"

### ISSUE THREAD

**Issue by didotb** [Microsoft/vcpkg#875]
This is my first time building vcpkg via bootstrap.ps1 inside %vcpkg_dir%\scripts\
build provided me with 0 warnings and 0 errors
however it gave me 1 fatal before the building process began: 

> fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

never encountered such problem like that with git though

Error(s): attachment bellow

![image](https://cloud.githubusercontent.com/assets/13257408/24493738/7c07f1d4-1562-11e7-9e21-9cb2bdb0eefb.png)

**Comment by ras0219-msft** [comment]
Hi @didotb, thanks for trying Vcpkg!

First, the strange message is most likely because you downloaded Vcpkg as a zip file instead of using git clone. This will still work, though it will be harder for you to update (we rely on git to make that easy).

Second, we recently had a regression (and even more recently fixed) in the new user experience that causes the error you've hit! Could you clone today's sources and try once more?

**Comment by alexkaratarakis** [comment]
@didotb 
Also, adding `--debug` to any `vcpkg` command will give you a line number indicating where an error was detected. We can use that as a starting point to investigate further.

**Comment by ras0219-msft** [comment]
Let us know if you're still encountering that issue!
