### ISSUE TITLE
Package: openmpi:x86-windows   Vcpkg version: 2019.09.12-nohash

### ISSUE THREAD

**Issue by thierleft** [microsoft/vcpkg#8796]
**Host Environment**
- OS: Windows 10

**To Reproduce**
`./vcpkg install openmpi`

**Comment by JackBoosY** [comment]
@thierleft The error info shows:
>  This port is only for openmpi on Unix-like systems

We need to support windows in the future.

**Comment by thierleft** [comment]
@JackBoosY  do you know if they will support installation of library HEALPix in a near future?
https://sourceforge.net/projects/healpix/

**Comment by JackBoosY** [comment]
@thierleft After some searching, I found this [link](https://github.com/open-mpi/ompi/wiki/WindowsPort). So I guess we can support windows.

**Comment by JonLiu1993** [comment]
@thierleft, thanks for posting this issue, since the upstream has stopped supporting Windows version support, our vcpkg will not add this feature again. I will close this issue. If you have any other questions, please contact me and I will open it again.
https://www.open-mpi.org/software/ompi/v1.6/ms-windows.php
````
Due to lack of interest and anyone to maintain them, binary support for a Microsoft Windows Open MPI build has been discontinued. There will be no further releases of them unless a new maintainer can be found. Windows-based Open MPI users may choose to use the [Cygwin-based Open MPI builds](http://cygwin.com/packages/), instead.
````
