### ISSUE TITLE
hiredis, redis-plus-plus

### ISSUE THREAD

**Issue by RameshKandukuriB** [microsoft/vcpkg#8840]
****

**Is your feature request related to a problem? Please describe.**
can't find, make and build hiredis/redis-plus-plus on windows 64 bit

**Proposed solution**
include hiredis/redis-plus-plus in the list.

**Describe alternatives you've considered**
build locally

**Additional context**
none

**Comment by NancyLi1013** [comment]
Hi @RameshKandukuriB thanks for posting this request.
These two ports have been added to vcpkg. Please update vcpkg and try to use them.

**Comment by RameshKandukuriB** [comment]
Hi @NancyLi1013 
Thanks for the update, however the windows build failed for me. See following 

![vcpkg_hiresis_failed](https://user-images.githubusercontent.com/57233915/69439122-4f599780-0d14-11ea-8e71-6ae85a2aac2d.PNG)
![hiredis windows cmake failed](https://user-images.githubusercontent.com/57233915/69439132-5385b500-0d14-11ea-9ab3-10bd6189eba9.PNG)

**Comment by NancyLi1013** [comment]
Hi @RameshKandukuriB thanks for posting this issue.
Since the version of hiredis in vcpkg currently doesn't support Windows. So the behavior you encountered is intended. 
I have submitted a PR #8902 to support Windows. But it can only support for static build on windows.
Please wait for some time and I will fix it in near future.

Thanks.
