### ISSUE TITLE
[HDF5] When building with the x64-windows triplet, both static and dynamic libs are built

### ISSUE THREAD

**Issue by contre** [microsoft/vcpkg#8873]
****

**Is your feature request related to a problem? Please describe.**
When building HDF5 with the x64-windows triplet, I expect to only get dynamic libraries but both static and dynamic libraries are built. This later becomes a problem when attempting to export a nuget package since the machinery for the nuget package includes *.lib in the msbuild files which leads to duplicate symbols since both static and dynamic libs are included.

**Proposed solution**
Make HDF5 not build the static version when building the dynamic version.

**Describe alternatives you've considered**
For the specific issue with the nuget package above, I specifically wrote code to open the generated nupkg file and delete the static libs since the names for the static libs started with lib where the dynamic version didn't.

**Comment by Neumann-A** [comment]
did you add the define `H5_BUILT_AS_DYNAMIC_LIB` ? 
This is required if you use the shared library version of HDF5 without using CMake.

Only building the dynamic library requires to remove/deactivate the shared targets from the hdf5 cmakelists.txt which is not (yet) supported by upstream.  
Also a word of warning: If you also use MATLAB on your PC never use a dynamic version of HDF5 in your own program (unless you build your hdf5 with different dll names or build the same version as MATLAB uses) 

Note for somebody who fixes the issue: Do not alias the `hdf5-static` targets to the `hdf5-shared` targets... or the other way around (This was done before and I removed that aliasing because it is just wrong to do something like that).

**Comment by contre** [comment]
> did you add the define `H5_BUILT_AS_DYNAMIC_LIB` ?

Yes. I added this define to my consuming code. The end result was still that both a static and dynamic version of the library were built.

> Only building the dynamic library requires to remove/deactivate the shared targets from the hdf5 cmakelists.txt which is not (yet) supported by upstream.

I was aware of this as I had tried to fix it myself but was unable to do so. 

I figured I would report the issue here in the hopes that it may get fixed within vcpkg. I had recently watched the cppcon talk about creating packagable libraries which mentioned specifically being able to build static or dynamic individually instead of both together and that the vcpkg maintainers has to work around this for several ports. So here we are with me reporting another port that doesn’t allow separating the two build types.

> Also a word of warning: If you also use MATLAB on your PC never use a dynamic version of HDF5 in your own program (unless you build your hdf5 with different dll names or build the same version as MATLAB uses)

Add one more reason to the pile of why I dislike matlab. What exactly are they doing wrong? Spending themselves to the PATH, installing their own version in a system location, something worse?

> Note for somebody who fixes the issue: Do not alias the `hdf5-static` targets to the `hdf5-shared` targets... or the other way around (This was done before and I removed that aliasing because it is just wrong to do something like that).

The simplest, at this point, is likely to just remove the static built libs at the end of the build when building dynamic.

**Comment by JackBoosY** [comment]
Hi @contre, thanks for reporting this issue!
I've fixed it, please update vcpkg and rebuild hdf5.

Thanks.
