### ISSUE TITLE
Trying to push changes results with permission denied

### ISSUE THREAD

**Issue by yuvalg-MSFT** [microsoft/vcpkg#8914]
I’m trying to push some code into a repo from a branch I created (Linux) and I’m seeing the following error: "permission to Microsoft/vcpkg.git denied to yuvalg-MSFT"

In an attempt to resolve this permission problem, I followed the guidelines here:
https://help.github.com/en/enterprise/2.14/user/articles/error-permission-to-userrepo-denied-to-userother-repo
 
This is what I did:
1.	Created a new SSH keys
2.	Added the key to the local SSH agent
3.	Updated my GitHub account with the public key
 
However, I’m still seeing the same error. Note that I also defined a Personal Access Token (PAT) which I'm using as a password. But this too has no effect
 
What am I missing?

Thanks,
-Yuval
![error](https://user-images.githubusercontent.com/52262536/68253803-c2a59e80-ffdd-11e9-95ad-41e415dd571f.jpg)

**Comment by vicroms** [comment]
Hi @yuvalg-MSFT 

We use the fork and pull request model, you should fork the vcpkg repo and push changes to branches in your own fork. When you're ready to submit your changes upstream just make a Pull Request against Microsoft/vcpkg and we'll review it for merging!

**Comment by yuvalg-MSFT** [comment]
Ok I actually created a branch off of the vcpkg clone directly. I guess that was a mistake as I should have forked first the entire repo - is that correct?

**Comment by vicroms** [comment]
If you plan to contribute back or make private modifications then you should fork the vcpkg repo, I suggest keeping a remote linking back to `Microsoft/vcpkg` in order to update your copy of the ports and to receive the latest updates to the vcpkg tool. 

1) Fork vcpkg with GitHub
2) Clone your fork of vcpkg `git clone git@github.com:yuvalg-MSFT/vcpkg.git`
3) Add a remote to the original repo `git remote add upstream git@github.com:microsoft/vcpkg.git`
4) Push your changes to your own fork `git push origin <branch>`
5) Pull updates from upstream periodically `git pull upstream master`

**Comment by JackBoosY** [comment]
Related: #8916.

**Comment by PhoebeHui** [comment]
@yuvalg-MSFT, looks your issue solved.
