### ISSUE TITLE
curl:x64-windows-static with http2 requires nghttp2.dll when using curl.

### ISSUE THREAD

**Issue by anluoma** [microsoft/vcpkg#8923]
**Describe the bug**
When building libcurl with curl[http2] option and using it in my executable windows is yelling me that it could not find nghttp2.dll. I checked that somebody has added a patch (0004_nghttp2_staticlib.patch) to remove bin/nghttp2.dll from build but I think that is not the correct way to solve this issue as this needs some build time flags when compiling IMHO.

How to build the nghttp2 with curl statically so that it won't need the dll?

**Environment**
- OS: Windows 10
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x64

**To Reproduce**
1. ./vcpkg install curl[http2]
2. build app and link it against curl and try starting it.
3. windows is saying that it needs nghttp2.dll

**Expected behavior**
nghttp2 should not be needed as a separate dll when using curl statically.

**Additional context**

**Comment by JackBoosY** [comment]
Hi @anluoma, thanks for reporting this issue!
`curl[http]:x64-windows-static` should not use nghttp2.dll because we already defined `NGHTTP2_STATICLIB` in pre-definitions. You can find this macro in _nghtt2/nghttp2.h_ line 57:
```
#ifdef NGHTTP2_STATICLIB
#  define NGHTTP2_EXTERN
```
So when linking curl with nghttp2, curl will link the nghttp2 static library and add all the code belonging to nghtttp2 to the curl static library. 

Curl has been update to 7.68.0, can you update vcpkg and try again?
If this issue still repro, please provde sample code.

Thanks.

**Comment by anluoma** [comment]
Hi, @JackBoosY 

just to make sure it is the curl[http2] and not curl[http]. I'll remember seeing that NGHTTP2_STATICLIB definition as I did little bit checking on this matter but could not figure it out. 

Anyway I updated to latest vcpkg, recompiled and it seems to start ok now. I'll close this and reopen if problem comes again.

thanks

-antti

**Comment by dnikolic-zfx** [comment]
I've ran into the same issue, and I'm able to reproduce it on windows.

Running the following command still produces dynamic .lib file on windows:
`.\vcpkg.exe install nghttp2:x86-windows-static`

Running the application linked with the nghttp2.lib built this way prompts for nghttp2.dll even tho it is supposed to be a static lib.
