### ISSUE TITLE
[qt5] update to 5.12.6

### ISSUE THREAD

**Issue by TheScarfix** [microsoft/vcpkg#9002]
Library name: qt5*

New version number: 5.12.6

https://wiki.qt.io/Qt_5.12_Release

**Comment by JackBoosY** [comment]
@Neumann-A Do you have a plan to update Qt5? We are really busy.

**Comment by heydojo** [comment]
@TheScarfix this is the 6th Qt LTS release of this branch this year. I can't speak for everyone but I rarely pull a release from Qt without six months passing by and [5.12.5 is already in the ports tree](https://github.com/microsoft/vcpkg/blob/master/ports/qt5-base/CONTROL#L2).

Please feel free to submit a pull request with a version bump but you might want to wait a bit because there is something going on with the build bots which run on the pull requests right now.
A port as big as Qt really needs to pass CI tests before being merged. The port is too complex to just bump because there was a new release upstream.

**Comment by Neumann-A** [comment]
@JackBoosY No plan at all. What I want is rewrite the qt5 metaport to be all features for the different qt5 subports and then update. But as long as CI is not working it is probably just adding more work for you ;)

@heydojo I don't think you need to lecture TheScarfix on this since he typically makes the PRs for updating qt which I just happened to hijack in the past. But I think bumping the version to 5.12.6 will be trivial when CI is back up (since 5.13 is also already working through the [latest] feature)

**Comment by pwinter1991** [comment]
Sadly the only versions available of qt5 on vcpkg share a bug in the SerialPort on Windows environments. This got fixed in 5.12.6 and in 5.13.2 sadly we have only 5.12.5 and 5.13.1 available. I tried updating the port files myself but never added / updated a package before.

https://bugreports.qt.io/browse/QTBUG-78086

**Comment by Neumann-A** [comment]
https://wiki.qt.io/Qt_5.12_Release shows 5.12.7 to be released (tomorrow) somewhere around next week
5.14.1 was release this week. I have a branch with 5.14 but I am not touching Qt again unless #9705 is merged. 

Due to the changes of Qt licensing I am struggling if VCPKG should still contain the LTS release or just always contain the latest release.
