### ISSUE TITLE
openal-soft:x64-windows build vs2015 failure

### ISSUE THREAD

**Issue by mruizf** [microsoft/vcpkg#9053]
**Host Environment**
- OS: Windows 10 Professional
- Compiler: VS2015 update 3

**To Reproduce**
./vcpkg install openal-soft:x64-windows

**Failure logs** 
Unable to empty directory: E:/vcpkg/packages/openal-soft_x64-windows Files are likely in use. Error: Building package openal-soft:x64-windows failed with: BUILD_FAILED

**Comment by timautry** [comment]
This is usually caused by the userid you are running vcpkg with doesn't have the required permissions to delete the file(s) or folder(s) within and to include the E:/vcpkg/packages/openal-soft_x64-windows folder itself, or something else has one of the files and/or folders open, an example would be antivirus software scanning the folder.
You may need to login with an administrator account and take ownership of the file(s) and/or folders the delete them manually - just the E:/vcpkg/packages/openal-soft_x64-windows and everything contained within it only - then try run the ./vcpkg install openal-soft:x64-windows again.
This happens to me from time to time when there is a reason vcpkg has to delete and reinstall a package because you have added another option to an existing package or downloaded and update to a package already installed, or not running vcpkg under the same login your originally installed a package with. 
Note: I know its bad practice, but I run my two vcpkg environments (VS2017 and VS2019) using the "vcvarsall.bat x64" command using an administrator account. It seems to eliminate this issue most of the time, but there are still times I have to take ownership of the package directory and delete it manually...

**Comment by PhoebeHui** [comment]
@mruizf, we usually see this error message when 'E:/vcpkg/packages/openal-soft_x64-windows folder itself, or one of the files and/or folders open, close them, and try to rebuild it. It should works.
