### ISSUE TITLE
protobuf:x86-windows build failure

### ISSUE THREAD

**Issue by hyperxpizza** [microsoft/vcpkg#9062]
**Host Environment**
- OS:  Windows 10
- Compiler: revision

**To Reproduce**
`./vcpkg install protobuf`

**Failure logs** 
$ ./vcpkg.exe install protobuf
The following packages will be built and installed:
    protobuf[core]:x86-windows
Starting package 1/1: protobuf:x86-windows
Building package protobuf[core]:x86-windows...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
Please install the English language pack.
-- Using cached C:/Users/w.frackowski/vcpkg/downloads/protocolbuffers-protobuf-v3.10.0.tar.gz
-- Using source at C:/Users/w.frackowski/vcpkg/buildtrees/protobuf/src/v3.10.0-3635dcc912
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/Users/w.frackowski/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: C:/Users/w.frackowski/vcpkg/buildtrees/protobuf/x86-windows-dbg
    See logs for more information:
      C:\Users\w.frackowski\vcpkg\buildtrees\protobuf\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/protobuf/portfile.cmake:55 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package protobuf:x86-windows failed with: BUILD_FAILED

**Comment by timautry** [comment]
I think you need to verify if you have the **English language pack** installed, and if not install if for the version of visual studio you are using:
**...**
Starting package 1/1: protobuf:x86-windows
Building package protobuf[core]:x86-windows...
**Warning: The following VS instances are excluded because the English language pack is unavailable.**
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
**Please install the English language pack.**
-- Using cached C:/Users/w.frackowski/vcpkg/downloads/protocolbuffers-protobuf-v3.10.0.tar.gz
-- Using source at C:/Users/w.frackowski/vcpkg/buildtrees/protobuf/src/v3.10.0-3635dcc912
-- Configuring x86-windows
-- Building x86-windows-dbg
**...**

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
