### ISSUE TITLE
[tesseract] build failure / feature name mismatch

### ISSUE THREAD

**Issue by mwetzko** [microsoft/vcpkg#9102]
**Host Environment**
- OS: Windows 10 Pro x64
- Compiler: VS2019 Community

**To Reproduce**
`./vcpkg install tesseract[cpu_independed]:x64-windows`

**Additional context**

CONTROL file of tesseract contains a feature named `cpu_independed`, but the portfile.cmake inside <vcpkg path>\ports\tesseract checks for a feature named `independed_architecture`.

Please rename `cpu_independed` into `independed_architecture` of CONTROL file.

https://github.com/microsoft/vcpkg/blob/506299a173c565f64976be2a2d24a9efbc4f7117/ports/tesseract/CONTROL#L11

https://github.com/microsoft/vcpkg/blob/506299a173c565f64976be2a2d24a9efbc4f7117/ports/tesseract/portfile.cmake#L29

**Comment by NancyLi1013** [comment]
Hi @martinwetzko thanks for posting this issue.
I can build it successfully on my local with the command 
`.\vcpkg.exe  install tesseract[cpu_independed]:x64-windows`

The result is as follows:
```
PS F:\Files\vcpkg\vcpkg> .\vcpkg.exe install tesseract[cpu_independed]:x64-windows
The following packages will be built and installed:
  * leptonica[core]:x64-windows
    tesseract[core,cpu_independed]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: leptonica:x64-windows
Building package leptonica[core]:x64-windows...
Warning: abi keys are missing values:
    giflib
    libjpeg-turbo
    libpng
    libwebp
    tiff
    zlib

-- Using cached F:/Files/vcpkg/vcpkg/downloads/DanBloomberg-leptonica-87b8219360bca3c9929a5705c3d9c50c42c34bca.tar.gz
-- Using source at F:/Files/vcpkg/vcpkg/buildtrees/leptonica/src/0c42c34bca-9673fffe25
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package leptonica[core]:x64-windows... done
Installing package leptonica[core]:x64-windows...
Installing package leptonica[core]:x64-windows... done
Elapsed time for package leptonica:x64-windows: 4.342 min
Starting package 2/2: tesseract:x64-windows
Building package tesseract[core,cpu_independed]:x64-windows...
Warning: abi keys are missing values:
    leptonica

-- Note: tesseract only supports static library linkage. Building static library.
-- Using cached F:/Files/vcpkg/vcpkg/downloads/tesseract-ocr-tesseract-4.1.0.tar.gz
-- Using source at F:/Files/vcpkg/vcpkg/buildtrees/tesseract/src/4.1.0-adb63d30fa
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package tesseract[core,cpu_independed]:x64-windows... done
Installing package tesseract[core,cpu_independed]:x64-windows...
Installing package tesseract[core,cpu_independed]:x64-windows... done
Elapsed time for package tesseract:x64-windows: 12.51 min

Total elapsed time: 16.85 min

The package tesseract:x64-windows provides CMake targets:

    find_package(Tesseract CONFIG REQUIRED)
    target_link_libraries(main PRIVATE libtesseract)
```
So it should be not related with feature name.
Could you please provide the build log for us?

**Comment by martinwetzko** [comment]
Dear @NancyLi1013,

there is no problem with the build process itself. It runs successfully on my machine too. The problem comes from the compiled result. I came across this problem, when I tried to run the program on a different CPU.

If you run `https://live.sysinternals.com/Coreinfo.exe`, it will show you the features of your CPU. By default, `tesseract:x64-windows` will compile in `auto` mode

https://github.com/microsoft/vcpkg/blob/506299a173c565f64976be2a2d24a9efbc4f7117/ports/tesseract/portfile.cmake#L32

which uses all available instruction sets of the current CPU, which on my machine is a `Intel(R) Core(TM) i7-4770K`, that includes BMI and BMI2 instruction sets. When I copy the app over to a server that uses a `Intel® Xeon® Prozessor E5-2430 v2` CPU, which does not have BMI2 support, the app crashes.

So how can you reproduce it? As follows:

Required tools and hardware: 
- a modern CPU, that supports BMI2 instruction set
![image](https://user-images.githubusercontent.com/49561427/69708345-bc49a480-10fb-11ea-9a2e-f36ac5eb2185.png)

- dumpbin.exe (Preferably Visual Studio 2019)
- a program to view a disassembled text file

Steps to reproduce:

1) Remove tesseract with `vcpkg remove tesseract:x64-windows` in order to have a clean state to begin with
2) Compile tesseract with `vcpkg install tesseract:x64-windows`
3) Open x64 Native Tools Command Promt
![image](https://user-images.githubusercontent.com/49561427/69711833-07ff4c80-1102-11ea-8116-496484682e41.png)

4) Run `dumpbin /disasm <path vcpkg>\installed\x64-windows\lib\tesseract41.lib > C:\tesseract41.txt` where `<path vcpkg>` is the path of your vcpkg instance.
5) Open `C:\tesseract41.txt` and search for `shlx` instruction, which is part of the BMI2 instruction set and only supported by modern CPU's
![image](https://user-images.githubusercontent.com/49561427/69709832-793d0080-10fe-11ea-880d-e09e5a666462.png)

6) Remove tesseract with `vcpkg remove tesseract:x64-windows`
7) This time, compile tesseract with `vcpkg install tesseract[cpu_independed]:x64-windows`
8) Run `dumpbin /disasm <path vcpkg>\installed\x64-windows\lib\tesseract41.lib > C:\tesseract41cpu_independed.txt`
9) Open `C:\tesseract41cpu_independed.txt` and search for `shlx` instruction
![image](https://user-images.githubusercontent.com/49561427/69709832-793d0080-10fe-11ea-880d-e09e5a666462.png)

You will see, the feature named `cpu_independed` **does not work**.

10) Remove tesseract with `vcpkg remove tesseract:x64-windows`
11) Add the following lines to the `vcpkg\ports\tesseract\CONTROL` file
` `
`Feature: independed_architecture`
`Description: build on any cpu extension commands support`
12) This time, compile tesseract with `vcpkg install tesseract[independed_architecture]:x64-windows`
13) Run `dumpbin /disasm <path vcpkg>\installed\x64-windows\lib\tesseract41.lib > C:\tesseract41independed_architecture.txt`
14) Open `C:\tesseract41cpu_independed.txt` and search for `shlx` instruction. You will not find it.
![image](https://user-images.githubusercontent.com/49561427/69712228-c3c07c00-1102-11ea-8b26-713af37a29d4.png)

As you can see, the bit shift instruction is now compiled into `shl` instead of `shlx`.

So please rename `cpu_independed` into `independed_architecture` 
https://github.com/microsoft/vcpkg/blob/506299a173c565f64976be2a2d24a9efbc4f7117/ports/tesseract/CONTROL#L11

or change `independed_architecture` of `portfile.cmake` into `cpu_independed`
https://github.com/microsoft/vcpkg/blob/506299a173c565f64976be2a2d24a9efbc4f7117/ports/tesseract/portfile.cmake#L29

Thank you!

**Comment by NancyLi1013** [comment]
@martinwetzko thanks for your detail description about this issue.
It's my fault that I missed something before.
I will rename it and try to test if this feature can work normally.

**Comment by NancyLi1013** [comment]
@mwetzko thanks for waiting so long time.
This issue has been fixed now. Please try to update vcpkg and use it.

**Comment by mwetzko** [comment]
Thanks @NancyLi1013, it works!
