### ISSUE TITLE
openssl:x86-uwp & x64-uwp. Build failed

### ISSUE THREAD

**Issue by AJIOB** [Microsoft/vcpkg#912]
I don't know what is that, but:
I'm trying to build mongo-cxx-driver to UWP and have such error with it's dependence: openssl

	-- CURRENT_INSTALLED_DIR=D:/Alex/Documents/SourceTree/vcpkg/installed/x64-uwp
	-- DOWNLOADS=D:/Alex/Documents/SourceTree/vcpkg/downloads
	-- CURRENT_PACKAGES_DIR=D:/Alex/Documents/SourceTree/vcpkg/packages/openssl_x64-uwp
	-- CURRENT_BUILDTREES_DIR=D:/Alex/Documents/SourceTree/vcpkg/buildtrees/openssl
	-- CURRENT_PORT_DIR=D:/Alex/Documents/SourceTree/vcpkg/ports/openssl/.
	-- Using cached D:/Alex/Documents/SourceTree/vcpkg/downloads/openssl-microsoft-1.0.2k_WinRT.zip
	-- Testing integrity of cached file...
	-- Testing integrity of cached file... OK
	-- Extracting done
	-- Build x64-uwp
	CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
		Command failed: D:/Alex/Documents/SourceTree/vcpkg/buildtrees/openssl/src/openssl-OpenSSL_1_0_2k_WinRT/make-openssl.bat;x64
		Working Directory: D:/Alex/Documents/SourceTree/vcpkg/buildtrees/openssl/src/openssl-OpenSSL_1_0_2k_WinRT
		See logs for more information:
		  D:\Alex\Documents\SourceTree\vcpkg\buildtrees\openssl\make-openssl-x64-uwp-out.log
		  D:\Alex\Documents\SourceTree\vcpkg\buildtrees\openssl\make-openssl-x64-uwp-err.log

	Call Stack (most recent call first):
	  ports/openssl/portfile-uwp.cmake:53 (vcpkg_execute_required_process)
	  ports/openssl/portfile.cmake:2 (include)
	  scripts/ports.cmake:73 (include)

	Error: Building package openssl:x64-uwp failed with: BUILD_FAILED
	Please ensure you're using the latest portfiles with `.\vcpkg update`, then
	submit an issue at https://github.com/Microsoft/vcpkg/issues including:
	  Package: openssl:x64-uwp
	  Vcpkg version: 0.0.79-2e7896e89e7f0cb15b30b7d087f8001c57b3220a

	Additionally, attach any relevant sections from the log files above.

I have cmake 3.8.0 rc4 x64 version installed. I have VS 2015 Update 3, Windows 10 Pro x64.
P.S. Visual Studio was installed on D:\ drive (D:\Program Files (x86)\Microsoft Visual Studio 14.0)
P.P.S. I have the similar error trying to build x86-uwp version

**Comment by AJIOB** [comment]
What about this bug. Are you fixed it in other branches?

**Comment by amoldeshpande** [comment]
I'm not sure whose fault this is, but I'm going to blame Microsoft (SDK installer) since this used to work just fine before I installed the latest 15063 SDK.
Basically, the registry key that ms\setvsvars.bat   trawls for  are under 

\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\v10.0

ProductVersion is used by above batch file to set the include paths (constructed from installationfolder\productversion)

Unfortunately, the ProductVersion is 15063, while the install directory is 15063.0

You can change the registry entry as I did, but god only know what that will break in the SDK. 

I'm putting this comment here because 
1. I don't know who the heck would be fixing this
2. If you find this bug looking for why vcpkg can't compile openssl, at least this will give you a workaround.

20+ years of shipping  and you still make me tear my rapidly diminishing hair out every time you ship a new version of something.

**Comment by darekrusin** [comment]
Are you perhaps on VS2017? I've ran into the same problem while trying to build **curl**. I've asked @stammen about it and he said that **OpenSSL is not yet building in VS2017**.

So I guess all packages with **openssl** dependency are breaking now (for VS2017) and could stay this way for a while.

**Comment by stammen** [comment]
@darekrusin  @ras0219-msft  It looks like there is a now preliminary support for building OpenSSL with VS2017 in the Microsoft repo.

https://github.com/Microsoft/openssl/tree/OpenSSL_1_0_2_WinRT-stable-vs2017
https://github.com/Microsoft/openssl/issues/45

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
