### ISSUE TITLE
Port with generic dependency to select the installed version

### ISSUE THREAD

**Issue by cdcseacave** [microsoft/vcpkg#9193]
An example is the best explanation: `dbow2` depends on `opencv`, however multiple versions of `opencv` are supported by `vcpkg`; currently `opencv` is an alias for the latest `opencv4` version supported by `vcpkg`, and if `opencv3` is installed instead of `opencv4` the `dbow2` port installation fails as it expects `opencv4` version, which can not (and should not) be installed alongside existing `opencv3`.

**Proposed solution**
When a generic dependency is used by a port, the installed version to be selected by the generic alias.

**Comment by NancyLi1013** [comment]
Hi @cdcseacave 
Thanks for posting this issue.
In my opinion, we just need to update the dependency of `dbow2 `as `opencv4` instead of `opencv`. This may be more suitable. What do you think?

Since `opencv3 `and `opencv4` are conflicts with each other. So whatever `opencv3 `or `opencv4` is installed at first, another one will build fail. This is due to the relationships between `opencv3 `and `opencv4`, which has nothing to do with the port that depends on them.

**Comment by cdcseacave** [comment]
In fact I disagree, most of openCV depending libraries support any version of openCV, only rarely a library is using a feature only added in the very last version; here dbow2 is a good example for that, and this issue is just an instance of a general improvement for vcpkg

**Comment by NancyLi1013** [comment]
Thanks for your clarification.
I have made sense what you want to express. But in fact, it would be better to depend on `opencv`. In this case, those libraries that depend on `opencv` will use the latest version of `opencv` by default. For now, it is `opencv4 `in vcpkg. As different versions for `opencv `have conflicts with each other. We need to handle the conflicts manually if there are two different `opencv` installed. Otherwise, it will always install the latest.

Unfortunately, we have no any plans to detect `opencv `version installed on our local. So I'm closing this issue for now.
