### ISSUE TITLE
[yaml-cpp] build failure

### ISSUE THREAD

**Issue by viperman1271** [microsoft/vcpkg#9245]
**Host Environment**
- OS: Linux (Linux 3.10.0-1062.4.1.el7.x86_64 / CentOS 7)
- CMake 3.6.2

**To Reproduce**
- `./vcpkg install yaml-cpp`
- Add `find_package(yaml-cpp CONFIG REQUIRED)` in CMakeLists.txt
- Run cmake (ex: `cmake .`)

**Failure logs** 
CMake Error in CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "main"

**Additional context**
Commenting or removing
`
set_target_properties(yaml-cpp PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
)
`

from vcpkg/installed/x64-linux/share/yaml-cpp/yaml-cpp-targets.cmake will fix the issue.

Issue appears to come from #8006
https://github.com/microsoft/vcpkg/blob/ffed6950623fd17a0928a71e74d31d097b6dcc21/ports/yaml-cpp/0003-cxx-std-features.patch#L9

**Comment by NancyLi1013** [comment]
Hi @viperman1271 thanks for posting this issue.
It seems that `target_compile_features() ` is supported by `CMake `3.8 or newer.
So could you please remove your local `CMake `or update your local `CMake`?

**Comment by viperman1271** [comment]
Can confirm that ```CMake 3.16.1``` is functional. For greater backwards compatibility wouldn't ```set_property(TARGET yaml-cpp PROPERTY CXX_STANDARD 11)``` make more sense?

**Comment by NancyLi1013** [comment]
@dan-shaw Could you help comment about this?
`target_compile_features()` is supported by `CMake `3.8 or newer. This user used `CMake `3.6.2 first.
 Since this user used his local `CMake `instead of that vcpkg provided. 
How should we handle this issue?
Is there needed to detect `CMake `version and post some messages? Or use other function to take place of this?

**Comment by viperman1271** [comment]
After reading the documentation again, I noticed the requirements in the documentation for ```CMake 3.12.4```. However, this doesn't appear to be enforced anywhere with ```cmake_minimum_required (VERSION 3.12.4)``` Perhaps this should be added?

**Comment by NancyLi1013** [comment]
Hi @viperman1271 
Sorry for the late reply.

First, I need to correct the above comment from me. 
The `cxx_std_11` compiler meta-feature was introduced in cmake 3.8 instead of `target_compile_features()`, which can be found in  [CMake 3.8 release notes ](https://cmake.org/cmake/help/v3.8/release/3.8.html#c-c).
Second, Considering  to cmake compatibility, perhaps we can use `set (CMAKE_CXX_STANDARD 11)` to replace `target_compile_features(yaml-cpp PUBLIC cxx_std_11)`.

What do you think about this?

**Comment by NancyLi1013** [comment]
Since this issue only exists on the lower version of cmake and there's been inactive for a long time.
I'm closing this issue for now.
