### ISSUE TITLE
[ffmpeg] add amd/amf, qsv hard encoding and openh264 encoding support

### ISSUE THREAD

**Issue by fawdlstty** [microsoft/vcpkg#9272]

**Comment by MicroYY** [comment]
Anything update? Still no qsv support

**Comment by NancyLi1013** [comment]
@mcmtroffaes

Would you like to help add these features for `ffmpg`?

Thanks in advance.

**Comment by mcmtroffaes** [comment]
Currently a bit too swamped with other things to take a lead on this.

I lack the hardware to test amf or qsv. For openh264, https://github.com/cisco/openh264 needs to be added as a port first. Judging from the readme, this will be non-trivial for vcpkg, requiring msvc to be called from an msys2 shell (similar to what we currently do to compile ffmpeg itself). Happy to help with reviewing and testing where I can.

**Comment by NancyLi1013** [comment]
Thanks for your help and clarifications about this.

We might delay to implement these features.

**Comment by shahneil** [comment]
For AMF, it looks like https://github.com/GPUOpen-LibrariesAndSDKs/AMF needs to be added as a port first, as the AMF framework headers are needed to configure ffmpeg with `--enable-amf` (see https://www.ffmpeg.org/general.html#toc-AMD-AMF_002fVCE).

Since AMF/VCE is Windows-only (see the ffmpeg link above), I believe a new Windows-only ffmpeg feature `amf` would need to be added that includes the `--enable-amf` option during ffmpeg compilation.

If anyone can provide further guidance that would be great, as I'm quite new to vcpkg. I'll try to create a port for the AMF headers in the meantime.

**Comment by xiaozhuai** [comment]
Any progress? Still no qsv support.
