### ISSUE TITLE
GraphicsMagick package

### ISSUE THREAD

**Issue by josuegomes** [Microsoft/vcpkg#934]
Hi,

Is there any interest for a package for GraphicsMagick library?
GraphicsMagick is a image processing library. More details [here](http://www.graphicsmagick.org/).

I have some time ago written a CMake script for it for my own use. In the past few days I adapted it for vcpkg. I'm not really a CMake or vcpkg expert so please take it with a grain of salt.

Attached you find CMakeLists.txt, CONTROL and portfile.cmake. Hopefully some expert could take a look on them for tips, corrections, and improvements.

BR
Josue

[graphicsmagick.zip](https://github.com/Microsoft/vcpkg/files/917766/graphicsmagick.zip)

**Comment by ras0219-msft** [comment]
Your port looks really good! 💯 

Comments/questions:
- Why do you use `include(FindFreetype)` instead of `find_package(Freetype REQUIRED)`[1]?
- It is a bit unusual to see directives like `add_definitions` and `include_directories` repeated multiple times for each individual directory/library/definition. I usually see them in a single directive (space separated), but this does have a certain stylistic appeal ;). Is it regex/machine generated?
- Does this work with static builds? I noticed you're defining `-D_DLL` and friends.
- Since you're writing a custom CMakeLists.txt, consider adding the ability to suppress the headers installation in debug mode:

```cmake
# CMakeLists.txt
option(INSTALL_HEADERS "Install development header files" ON)
if (INSTALL_HEADERS)
  install(FILES ....)
endif()

# portfile.cmake
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    OPTIONS_DEBUG -DINSTALL_HEADERS=OFF
)
```

I'd be happy to review and merge a PR for this!

[1] https://cmake.org/cmake/help/v3.6/command/find_package.html

**Comment by josuegomes** [comment]
Thank you!!

I'll make some changes and submit a PR.

BR
josue

**Comment by josuegomes** [comment]
PR submitted.

**Comment by josuegomes** [comment]
Tested with:

Visual Studio 2015 Up 3 on Windows 7: x86-windows, x64-windows, x86-windows-static, x64-windows-static
Visual Studio 2017 on Windows 10: x86-windows, x64-windows, x86-windows-static, x64-windows-static
