### ISSUE TITLE
Working with Openframeworks

### ISSUE THREAD

**Issue by rwebber** [microsoft/vcpkg#938]
I have found that global integration while working with Openframeworks can cause a number of issues, since OF contains specific version of a number of popular libs, and its easy to have vcpkg replace these.
Are there any specific settings that can be adjusted to remove integration with a project or solution in vs2015?

**Comment by ras0219-msft** [comment]
Yep! The you probably want `<VcpkgEnabled>false</VcpkgEnabled>`, which will completely disable all our project modifications (include directories, link directories, link libraries, and dll deployment). This can be safely added to any project and will do nothing if the user doesn't have Vcpkg.

I found an example[2] by searching GitHub for VcpkgEnabled.

You might also find it useful to browse through our MSBuild integration file[1] which has a few other properties that can configure our behavior (such as `VcpkgTriplet` and `VcpkgConfiguration`).

It also sounds like OpenFrameworks might be a nice library addition as well, since we have so many of their dependencies already packaged 😄!

[1] https://github.com/Microsoft/vcpkg/blob/master/scripts/buildsystems/msbuild/vcpkg.targets
[2] https://github.com/congzhangzh/vld/blob/0fbf335bab5cfdde85cdfacee9ba9a20bb986017/src/vld.vcxproj#L45

**Comment by rwebber** [comment]
where would I add: <VcpkgEnabled>false</VcpkgEnabled>
I tried a couple spots in the xml, but got loading errors.

**Comment by codicodi** [comment]
Try here:
```
  <PropertyGroup Label="Globals">
    ...
    <VcpkgEnabled>false</VcpkgEnabled>
  </PropertyGroup>
```

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in two year, if it is still an issue, please reopen.
