### ISSUE TITLE
[msmpi] Install msmpifec.lib and msmpifmc.lib

### ISSUE THREAD

**Issue by KineticTheory** [microsoft/vcpkg#9556]
**Summary**

* The MS-MPI installer provides three implib files:
  * `msmpi.lib`
  * `msmpifec.lib`
  * `msmpifmc.lib`

The vcpkg port only installs the first file into `%vcpkg-root%/installed/x64-windows/lib/`, but  I need `msmpifec.lib` to support MPI builds that have both C++ and Fortran sources.

**Describe alternatives you've considered**

* As a work around, I am manually copying these files from `%MSMPI_LIB64%` into the %vcpkg% install directory.

**Comment by NancyLi1013** [comment]
Hi @KineticTheory thanks for posting this issue.
If you want to use `msmpifec.lib` or `msmpifmc.lib`, you can try to install `x64-windows-static` triplet.
Since we put these libs into static lists. 
https://github.com/microsoft/vcpkg/blob/master/ports/msmpi/portfile.cmake#L105-L110

Could you please try to run` .\vcpkg.exe install msmpi:x86-windows-static` and then use it?

**Comment by KineticTheory** [comment]
@NancyLi1013 I ended up going a different route on this.  I use gendef and dlltool to create a mingw libmsmpi.a library equivalent of msmpi.  This seems to bypass the issue I was having with missing implib files.
