### ISSUE TITLE
Telemtry notice is displayed even when building with disableMetrics

### ISSUE THREAD

**Issue by Mike-Devel** [microsoft/vcpkg#9688]
Even when calling `./bootstrap-vcpkg.sh -disableMetrics`, the bootstrap script prints the notification about telemetry data and that you can deactivate it by using `-disableMetrics`. That is a bit confusing, because at first I thought I misspelled the option or that the switch wouldn't actually do anything (didn't dive into the sources, but it does get passed to cmake, so I guess it is fine).

> Telemetry
> ---------
> vcpkg collects usage data in order to help us improve your experience. The data collected by Microsoft is anonymous. You can opt-out of telemetry by re-running bootstrap-vcpkg.sh with -disableMetrics
Read more about vcpkg telemetry at docs/about/privacy.md

I think that banner should be supressed when `-disableMetrics` flag is used.

Btw.: Same behavior on windows with bootstrap-vcpkg.bat

**Comment by zirahvi** [comment]
This particular feature badly undermines the trust in this otherwise great tool. 

It gives the impression that either the argument doesn't have any effect, or that the user has accidentally somehow managed to failed to type the parameter name (even when copy-pasting) correctly, because it doesn't seem to have any effect. 

I had to actually read through the bootstrap script to be sure that it really is disabling telemetry when `-disableMetrics' is specified, as my initial assumption was that there was a bug in there.

Please do suppress the banner when `-disableMetrics` is used, and output "Telemetry data collection disabled." or something instead.

**Comment by Mike-Devel** [comment]
Thanks

**Comment by zirahvi** [comment]
That was fast. Thanks!
