### ISSUE TITLE
gtest package version number is erroneous

### ISSUE THREAD

**Issue by gallafent** [microsoft/vcpkg#9768]
**Describe the bug**
Per https://github.com/microsoft/vcpkg/issues/8452 gtest has been updated to 1.10.0.
For some reason the version number in the vcpkg metadata at https://github.com/microsoft/vcpkg/blob/master/ports/gtest/CONTROL contains the calendar date six days after the date on which version 1.10.0 was released, instead of the version number.

To be clear, 2019-10-09 is not a valid version number for gtest. This has caused problems for others, too, e.g. https://gitlab.kitware.com/cmake/cmake/issues/19837 .

gtest 1.10.0 release tag at https://github.com/google/googletest/releases/tag/release-1.10.0 .

**To Reproduce**
`vcpkg search gtest`
returns
`gtest                2019-10-09     GoogleTest and GoogleMock testing frameworks.`

**Expected behavior**
The version number "1.10.0" should be reported:
`gtest                1.10.0     GoogleTest and GoogleMock testing frameworks.`

**Comment by JackBoosY** [comment]
Hi @gallafent, thanks for reporting this issue!
The version number `2019-10-09` is only used in vcpkg, it shouldn't be used elsewhere.

For why we use this version number, please check the [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md#version).
This update incorrectly updated gtest to a development board instead of a release version. We will use the release version in the next update.

For usage, after successfully building gtest, the console will display:
> The package gtest is compatible with built-in CMake targets:
\
    enable_testing()
 \
    find_package(GTest CONFIG REQUIRED)
    target_link_libraries(main PRIVATE GTest::gtest GTest::gtest_main GTest::gmock GTest::gmock_main)
 \
    add_test(AllTestsInMain main)

`GTest :: gtest GTest :: gtest_main GTest :: gmock GTest :: gmock_main` is generated by `CMakeLists.txt` in gtest, I think there should be no errors here.

**Comment by JackBoosY** [comment]
Close this issue via #10963 merged.
