### ISSUE TITLE
How do I get "no additional confiuration" working?

### ISSUE THREAD

**Issue by dims12** [microsoft/vcpkg#9789]
I have installed vcpkg, have installed some libraries (like CGAL), also ran 

vcpkg integrate install

and now I wish to have this

In Visual Studio, you can create a New Project (or open an existing one). All installed libraries are immediately ready to be #include'd and used in your project without additional configuratio

How to?

**Comment by vicroms** [comment]
After running `vcpkg integrate install`, all libraries that you install via `vcpkg install <library>` should be usable in **Visual Studio projects (MSBuild)**.

### Example

1. Enable system-wide integration

 ```bash
./vcpkg integrate install
```

2. Install ZLIB via VCPKG

```bash
./vcpkg install zlib:x86-windows
```

3. Create a new C++ Empty Project in VS.

4. Create source file with contents:

```cpp
#include <iostream>
#include "zlib.h"

int main()
{
    std::cout << "ZLIB version: " << zlibVersion() << std::endl;
    return 0;
}
```
5. Build and run the program (Visual Studio will detect the installed vcpkg libraries and link them to your project)

Output:
```
ZLIB version: 1.2.11
```

### Notes

The installed library's triplet must match the Visual Studio configuration. If you're using a x64-Debug or x64-Release configuration in Visual Studio you should install the library for the `x64-windows` triplet (e.g.: `vcpkg install zlib:x64-windows`).

If you're using a CMake project instead of MSBuild, you must pass the following argument to your command line `-DCMAKE_TOOLCHAIN_FILE=<path_to_vcpkg>/scripts/buildsystems/vcpkg.cmake`.
