### ISSUE TITLE
How do I use x86-windows-static

### ISSUE THREAD

**Issue by illera88** [microsoft/vcpkg#9894]
Hi, 

I'm trying to install boost for x86 static but it seems there is only the x64 version. Is `x86-windows-static` deprecated? I know I could install boost 1.21.0 version for `x86-windows-static`.

Thanks

**Comment by vicroms** [comment]
Hi @illera88 

Does `vcpkg install boost:x86-windows-static` not work for you? 

The Boost version currently on vcpkg master is 1.72. 

I would add that `x86-windows-static` is a "Community Triplet" which means that we don't do regression testing for that specific triplet but it could still work for you.

**Comment by illera88** [comment]
It does not:
```C:\Users\user\Documents\code\vcpkg>vcpkg install boost:x86-windows-static
Warning: Different source is available for vcpkg (2019.9.12 -> 2020.1.17). Use .\bootstrap-vcpkg.bat to update.
Error: invalid triplet: x86-windows-static
Available architecture triplets:
  arm-uwp
  arm64-windows
  community
  x64-linux
  x64-osx
  x64-uwp
  x64-windows
  x64-windows-static
  x86-windows
```

**Comment by illera88** [comment]
I guess that the triplet is not being set up for 32 bits systems.

**Comment by vicroms** [comment]
Short answer: 

You need to rebuild vcpkg by  running `/bootstrap-vcpkg.bat` and then try again.

Long answer:

You have a `vcpkg.exe` that precedes the move of `x86-windows-static` to the community triplets folder (`<vcpkg path>/triplets/community/`). You need to rebuild vcpkg (by running the bootstrap again) with the latest sources so that vcpkg knows to search for triplets in the community folder. If you have a reason you cannot rebuild `vcpkg` then you can move the `x86-windows-static` triplet back into the root of the triplets folder.
