### ISSUE TITLE
gRPC update to 1.27.0

### ISSUE THREAD

**Issue by itayzafrir** [microsoft/vcpkg#9940]
Library name:

New version number:
1.27.0

Other information that may be useful (release notes, etc...)
gRPC v1.27.0 has been released, please provide an update. Thank you.

**Comment by Qv2ray-dev** [comment]
Please update this ASAP since gRPC 1.26 has a serious bug preventing users start the application.

Possible related bugs:
https://github.com/grpc/grpc/issues/21609
https://github.com/grpc/grpc/issues/21633
https://github.com/grpc/grpc/issues/21280
https://github.com/grpc/grpc/issues/21213
https://github.com/grpc/grpc/issues/21273
https://github.com/grpc/grpc/issues/21507
https://github.com/grpc/grpc/issues/21552
https://github.com/grpc/grpc/issues/21548
https://github.com/grpc/grpc/issues/21213

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed, so I am closing this issue for now.
